### ISSUE TITLE
Why not creating a searx network?

### ISSUE THREAD

**Issue by aurora-anon** [searx/searx#1001]
How about connecting searx.me with other searx instances to share bandwidth and computational resources?

**Comment by dalf** [comment]
see #792

**Comment by asciimoo** [comment]
@aurora-potter the main problem is that I cannot ensure that other instances don't leak data.
Personally I don't want to implement privacy degrading features for my instance, however anybody can create and host a wrapper you mentioned. A good example is https://searxes.danwin1210.me/ which randomly selects a searx instance on every search.

**Comment by aurora-anon** [comment]
@asciimoo
But it is a server-to-server communication.
The other instances don't know who a search query belongs to.

**Comment by asciimoo** [comment]
@aurora-potter they don't know the original IP, that's true, but the search data is accessible, also the response can be tampered. It is +1 uncontrollable component in the chain.
