### ISSUE TITLE
Add Persian to searx's transifex project

### ISSUE THREAD

**Issue by aurora-anon** [searx/searx#1002]

**Comment by kvch** [comment]
Please, request it on Transifex, so someone who speaks Persian translate it.

**Comment by ahangarha** [comment]
I can do translation. Just let me know how to do

**Comment by dalf** [comment]
* Go 
https://www.transifex.com/asciimoo/searx/language/fa_IR/
* log in with your github account
* ask to join the team using the the upper right corner button.

**Comment by aurora-anon** [comment]
@kvch Searx is now fully translated to Persian.

Please add fa and fa-IR as search languages in searx.

**Comment by ahangarha** [comment]
@aurora-potter Translation is done. it is ready to review and use.

**Comment by ahangarha** [comment]
Do you have any person to review Persian translations?

**Comment by aurora-anon** [comment]
@ahangarha So why am I here for?

**Comment by ahangarha** [comment]
@aurora-potter I meant a person who can review Persian translation on the transifex, to review translations.

**Comment by aurora-anon** [comment]
@ahangarha I know Persian.
But I don't know how to become a reviewer on searx's transifex project. Any ideas?

**Comment by aurora-anon** [comment]
@ahangarha I don't think so. It works fine for me. Can you explain the problem in more detail?

**Comment by aurora-anon** [comment]
@ahangarha That's not possible.
Give me a screenshot.
Check the searx's settings page and enable all major search engines like bing, google, yahoo, yandex, duckduckgo & ixquick and disable the rest in general engines list.

**Comment by kvch** [comment]
@ahangarha @aurora-potter I can add both of you on Transifex as a reviewer of Persian. Just give me your Transifex user names.

**Comment by ahangarha** [comment]
@aurora-potter Please take a look on these two screenshots:
![image](https://user-images.githubusercontent.com/11241315/38459371-ebdd8416-3abd-11e8-86c4-fba68db3a7ad.png)

**Comment by aurora-anon** [comment]
@kvch nasty786

**Comment by aurora-anon** [comment]
@ahangarha You're right. I've never noticed that.
I'm a native Persian speaker, but I seldom write in Persian.

The problem is only from the search language.

Look at this: https://searx.me/?q=%D9%86%D8%B1%D9%85%20%D8%A7%D9%81%D8%B2%D8%A7%D8%B1%20%D8%A2%D8%B2%D8%A7%D8%AF&categories=general&language=fa

I've manually set the search language. It works fine.

Persian has to be added to the searx's search languages.

**Comment by aurora-anon** [comment]
@kvch Please add fa and fa-IR to searx's search languages.

**Comment by MarcAbonce** [comment]
Persian is now available in the search languages drop-down as `فارسی - fa-IR`.

**Comment by ahangarha** [comment]
Thanks to all

**Comment by kvch** [comment]
@aurora-potter I added you as a reviewer. Thanks for your help in advance. :)

**Comment by kvch** [comment]
Have you accepted the invitation? I tried adding you again, but Transifex doesn't allow me as you are already added.
What is the language code? I might added you for a different Persian language.

**Comment by aurora-potter** [comment]
@kvch I'm added as a Persian reviewer, not as Iranian Persian.
The language code I mean is fa_IR.
Please add me to the 'Persian' tranlators list and also yo the 'Persian(Iran)' reviewers list.

**Comment by aurora-anon** [comment]
@kvch I'm added as a Persian reviewer, not as Persian(Iran).
The language code I mean is fa_IR.

Please add me to the 'Persian' tranlators list and also to the 'Persian(Iran)' reviewers list.

**Comment by kvch** [comment]
Done. Let me know if it's not working.

**Comment by aurora-anon** [comment]
@ahangarha Sorry, but please don't ruin my translation on searx's Transifex project.
You're degrading the translation quality.

**Comment by aurora-potter** [comment]
@ahangarha I'm a Linguistics expert, I've translated texts back in 1600.
You don't translate with much accuracy.

**Comment by aurora-anon** [comment]
@ahangarha I'm a Linguistics expert, I've translated texts written back in 1600.
You don't translate with much accuracy.

**Comment by aurora-anon** [comment]
@kvch Searx is now 100% translated and reviewed in Persian(Iran).
Please update the source code snd also add fa-IR to searx's interface languages.

Also, please update the searx's version number, so other instances get the language update.

**Comment by kvch** [comment]
Persian language has been released in v0.15.0.
