### ISSUE TITLE
Google Play search results too much inappropriate

### ISSUE THREAD

**Issue by aurora-anon** [searx/searx#1003]
Search results  from Google Play in the 'files' section is way inappropriate.

**Comment by dalf** [comment]
Where it should be ? Application category ?

**Comment by aurora-anon** [comment]
No, the results are very inappropriate.
Whatever you search, you just see some results that aren't what you wanted.
try it out.

**Comment by kvch** [comment]
Can you give us an example? I tried different search terms, but to me none of the results seemed inappropriate. Do you want to retrieve "family-friendly" content?

**Comment by aurora-anon** [comment]
Compare search results from Google Play with searx.
When it doesn't find anything near what you've searched, it will show you results too far from what you meant.

Just like the Google itself.
