### ISSUE TITLE
add Open Collective backers & sponsors

### ISSUE THREAD

**Issue by piamancini** [searx/searx#1005]
Hi @asciimoo we tried to make a PR to your reamde to add your collective's backers and sponsors but it is in a different format than the one we have automated. 
Please go [here](https://github.com/opencollective/opencollective/wiki/Github-banner) to have a look at how we do it. 
An example [here](https://github.com/aksonov/react-native-router-flux/pull/1989/files)

**Comment by asciimoo** [comment]
@piamancini thank you, added. Commit 8dfc02a can be a good base if you plan to support `rst` format in the future.
