### ISSUE TITLE
Where are the html files located?

### ISSUE THREAD

**Issue by nixoye** [searx/searx#1010]
I can only find the html files in the template section which doesn't seem to be what is called for the actual html. I'm trying to edit the Oscar theme to add some links on the navbar.

**Comment by kvch** [comment]
Links of the navbar are in `searx/templates/oscar/navbar.html`.

**Comment by nixoye** [comment]
I tried changing this but it wouldn't update the website

**Comment by asciimoo** [comment]
@NIXOYE restart searx after changing template files.
