### ISSUE TITLE
Strict mode does not work

### ISSUE THREAD

**Issue by ThraaxSession** [searx/searx#1012]
Hi,

sadly I find a lot of dirty results for harmless searches. Is this problem known?

Best regards
Gino

**Comment by dalf** [comment]
Do you know which engine gives harmful results ?

Some technical details,  an engine can return : 
* potential harmful result (we just don't know if it will be the case, no way to filter) 
* harmful result is safe mode = 0
* harmless result is safe mode = 1
* harmless result what ever the request

The current implementation has an issue : 
* if an engine (the implementation in searx) supports content filtering, it will be filtered according to the user request. Good.
* if an engine (the implementation in searx) doesn't support content filtering, it won't filtered. But the engine (the one which gives the result) can gives harmful results even if the searx user asks for filtered results. Not good.

In my opinion, for each engine, the implementation in searx must describe : 
* potential harmful results but no implementation in searx
* potential harmful results with implementation in searx
* harmless results.

**Comment by ThraaxSession** [comment]
Hi Alexandre,

I will tell you in evening, right now I don't remember which engine it was. 

Best regards
Gino

**Comment by unixfox** [comment]
Duplicate of https://github.com/searx/searx/issues/1012
