### ISSUE TITLE
Have to hit search multiple times to get results from Google

### ISSUE THREAD

**Issue by webworker01** [searx/searx#1013]
On my private instance, in the past few days, when I search it will return no results found until I refresh the search multiple times and results are shown. Any tips on how to debug?

**Comment by asciimoo** [comment]
@webworker01 try to turn on debug messages in `settings.yml`.

**Comment by webworker01** [comment]
Thank you, I did that and nothing appeared in the browser. Where would the log be generated?

**Comment by misnyo** [comment]
Either try to run it manually, (eg python searx/webapp.py) and you can see it in standard output, or you should see in the uwsgi logs or similar depending on your setup.
My guess would be that the requests are timing out for the first few times, so another way to debug it is to increase the timeout in settings.yml and see if it works.

**Comment by webworker01** [comment]
Thank you again, I found the logs in /var/log/uwsgi/app/searx.log

`WARNING:searx.search:engine timeout: google
ERROR:searx.search:engine google : HTTP requests timeout(search duration : 30.0335729122 s, timeout: 30.0 s) : ReadTimeout`

Seems that this still happens after setting timeout to 30 seconds.   Hangs for one request, then seems to work fine for others.  Any way to get more verbose logging? I just set in settings.yml > general : debug : true

**Comment by misnyo** [comment]
You should find something like this in the debug log:
`DEBUG:requests.packages.urllib3.connectionpool:https://www.google.com:443 "GET /search?q=searx&start=0&gws_rd=cr&gbv=1&lr=&ei=x HTTP/1.1" 200 None`
Try to reproduce it with curl and a proper user agent, and find out how long the request takes and if there is an error in the result.
It is hard to find the problem at this point, it could be a networking error, ISP or QoS. Best practice is to run searx in a server environment, not on a desktop for reliable networking.

**Comment by webworker01** [comment]
I do have a server instance running at a hosting provider. 

A simple curl returns results fine and consistently

`curl -A "Mozilla/5.0" "https://www.google.com/search?q=test+1234"`

I modified gen_useragent() in utils.py to always `return "Mozilla/5.0"` and seems better so far. Not sure if it might be network reliability like you said though.

**Comment by webworker01** [comment]
Nevermind, that didn't fix anything :)

**Comment by misnyo** [comment]
Does only google search take that long?(you might try it with !go [searchterm] to only use that one)
Do you have enough memory in the server?(if not, it might happen that the application goes into swap, but I don't think it is the issue here)
If the http(s) query timeouts, it most likely have nothing to do with the code itself imo, I have no better idea than checking if everything is ok with the environment.

**Comment by misnyo** [comment]
Also, you might try an alternate dns server, but that's just a hard guess.

**Comment by Carl-Robert** [comment]
The default time limit (2 seconds or so) is way too short usually for my private instance. Try to increase that (put something like 20 seconds to be on the safe side) in the settings.yml under google or globally.

Should stop the refreshing, though can sometimes be a bit slow (less than ten seconds though).
