### ISSUE TITLE
[Request] FindX

### ISSUE THREAD

**Issue by heresjonny1** [searx/searx#1026]
FindX is a continuation of Gigablast that has been forked for privacy and has it's own index. It would make a nice addition to the current engines.

Site: https://www.findx.com/
Source: https://github.com/privacore/open-source-search-engine

**Comment by dimqua** [comment]
findx is already available: https://searx.me/?q=!fx%20findx

**Comment by Pofilo** [comment]
Thanks for the reminder :)

**Comment by jfowl** [comment]
according to https://privacore.github.io/:
> Goodbye – Findx is shutting down
It is over – before it really started. Findx is shutting down.

Card https://github.com/asciimoo/searx/projects/3#card-10987305 could be removed

**Comment by somedevreally** [comment]
looks like they are still here
 https://www.findx.com/
