### ISSUE TITLE
Ability for results in 2 languages.

### ISSUE THREAD

**Issue by Achaean** [searx/searx#1030]
**Hi!** :-)

Any possibility for Searx, to present results in 2 languages?

For being more specific, if you search on Google for a term, it presents you results both in English language (the default) and your local - native one.

In Searx you have to do 2 searches. One in English lang and one in your native one.

**Comment by KwadroNaut** [comment]
I was looking on to do this in Searx as well. Ideally there should be the 'all' or 'any' option, *and* the option to set your preferences to several search languages, 2 is too limited.

**Comment by alexis-** [comment]
This would be a tremendously useful feature !
As far as I'm concerned, it is the only thing missing in Searx as it is, and I would then recommend it to my friends (who all use this feature) without any hesitation as the best alternative to Google for privacy concerns.

Thanks again for all the effort going into this project.

**Comment by ilf** [comment]
I would also find this incredibly useful. And I can report that friends that tried searx stopped using it, because results would only be in one language (mostly English).

While on this, I would love for this to be passed via URL parameter like `https://searx.me/?language=en,fr&q=test`, so I don't have to set a cookie via preferences.

**Comment by asciimoo** [comment]
I had a discussion with other maintainers and we could not find a good way to implement this feature. Very few engines has native support for multiple languages and handling this feature in other engines is quite problematic. As I see, the only way is to use multiple requests in each language which can lead to service abuse.
Closing this issue for now, but feel free to reopen if there are any better ideas about the implementation.
