### ISSUE TITLE
Remove reliance on closed source DOCKER

### ISSUE THREAD

**Issue by hulekgre** [searx/searx#1032]
We need an alternative for this. Otherwise there's no point in searx at all.

**Comment by dalf** [comment]
Docker is one way to install searx among others : 
* [git clone](https://asciimoo.github.io/searx/dev/install/installation.html)
* [debian package](https://packages.debian.org/sid/main/searx)
* arch package
* [yunohost](https://github.com/abeudin/searx_ynh)

So is your request to remove the docker image ?

**Comment by hulekgre** [comment]
I installed it with python, but 'images' doesn't work. And it constant 505 error.
What dependencies are needed, or I can't use it with just python?

**Comment by misnyo** [comment]
@hulekgre what installation method have you followed?
https://asciimoo.github.io/searx/dev/install/installation.html this one?
What OS do you use?

**Comment by hulekgre** [comment]
@misnyo After downloading the .zip I installed 'setup.py' with python, and called dependencies through pip. To execute it: c:/python webapp.py. Your link's instructions are gnu-linux only.

I'm on Windows 7, and it does work. But it's slow, and I can't unselect engines otherwise it gives me 505 until the default preferences is set. Search on images, videos, news etc. is not working either with the default or not.

**Comment by misnyo** [comment]
Honestly I've never tried it on windows, and am not aware of anybody else, but I might give it a shot during the weekend. What you can also try in the meantime is to install it on a virtual machines with some linux, that's more preferred afaik.

**Comment by hulekgre** [comment]
With python3 I have this problem now:
https://pastebin.com/JHLuyzdG
```
"Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\yaml\reader.py", line 89, in peek
    return self.buffer[self.pointer+index]
IndexError: string index out of range"
```

```
"    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1235: cha
racter maps to <undefined>"
```

**Comment by micah** [comment]
docker isn't closed source...

**Comment by dalf** [comment]
https://www.docker.com/components-licenses
