### ISSUE TITLE
Hooktube.com on private instance of searx instead of youtube?

### ISSUE THREAD

**Issue by Carl-Robert** [searx/searx#1033]
Hey!

I host the searx instance to myself, so I am able to mess around freely.

Basically hooktube works as replacing "youtube.com" on the URL with "hooktube.com", so the replacement shouldn't be too difficult to do locally?
I do realize this ain't a support forum, but didn't find information on how to manipulate the search-results from certain services. 

Of course hooktube.com could also be added as a separate search-plugin, if that's possible.

**Comment by misnyo** [comment]
Hi, you can find more info about how the engines work at https://asciimoo.github.io/searx/dev/engine_overview.html
Basically the first you could try is copying the file, and changing this line: https://github.com/asciimoo/searx/blob/master/searx/engines/youtube_noapi.py#L23

**Comment by Carl-Robert** [comment]
Thank you! Actually had to change the line number 35 to make it work (queries Youtube for results, but replaces the link with Hooktube, not perfect, but at least works).


Adding for those looking to achieve this:
Change the URL on line https://github.com/asciimoo/searx/blob/master/searx/engines/youtube_noapi.py#L32 to `//hooktube.com/embed/{videoid}`
Also change https://github.com/asciimoo/searx/blob/master/searx/engines/youtube_noapi.py#L35 to `https://www.hooktube/watch?v=`for the full site, or `https://www.hooktube.com/embed/`for just the video.
Now it queries youtube.com for the results, yet presents the embed link on the searx page with hooktube.com version, and clicks go to either hooktube.com full version (needs javascript) or just the video.

**Comment by cy8aer** [comment]
+1 - just saw hooktube on boingboing. What about  a patch?

**Comment by theel0ja** [comment]
Replace it with [invidio.us](https://invidio.us), hooktube just shows iframes.

**Comment by theel0ja** [comment]
https://github.com/asciimoo/searx/issues/1372

**Comment by allendema** [comment]
Can this issue be closed then?
