### ISSUE TITLE
Help setting up searx with morty and filtron

### ISSUE THREAD

**Issue by RaspyVotan** [searx/searx#1038]
Hi,
managed to set up searx stand/alone (without morty and filtron), but would like enhance the installation. Saw previous issues and your documentation ( #543 and #744), but would be great to get some more help:

- I think the reverse proxy nginx to filtron is easy and well documented - any chance to get some info on how to debug this? I am simply not sure if it is working or not.
- How is filtron supposed to be running? Should it be the same user or a separate user? Startup via systemd? CRON? Other solutions?
- How does the reverse proxy filtron -> uswgi work? Seems this was discussed in #543 by user @cy8aer but I do not understand the solutions there. From the description of filtron, I would assume that filtron directly writes on port 8888 and the only requirement is that uwsgi listens on 8888 - but how would I get this done?
- How would you start morty? Again as systemd script?

Overall: Some more documentation how the overall system should work may answer any of the above problems right away.

Appreciate any help, great project and thanks a lot for your time.
RaspyVotan__

**Comment by cy8aer** [comment]
Just morty, uwsgi/debian-stretch is 2.0.14 should work now, but I need to check it again...
[Update] I just have Problems with http error 429. Cannot find the right timings/limits so empty pages every second or third click...

Morty

[Unit]
Description=Morty Reverse Proxy
After=network.target

[Service]
ExecStart=/usr/local/bin/morty --key yourkeyyourkeyyourkey

[Install]
WantedBy=multi-user.target


searx settings.yml

result_proxy:
    url : https://yoururl/morty/
    key : yourkeyyourkeyyourkey

... and some proxying for morty like apache:

ProxyPass /morty/ http://127.0.0.1:3000/
ProxyPassReverse /morty/ http://127.0.0.1:3000/

**Comment by knyfe** [comment]
I also would appreciate more detailed instruction about setting up filtron with searx. I've referred to [How to protect an instance](https://asciimoo.github.io/searx/admin/filtron.html), the [filtron project page](https://github.com/asciimoo/filtron), and the threads @RaspyVotan mentions. Best I've managed is HTTP 429 errors in the browser and `Response error: dial tcp4 127.0.0.1:8888: getsockopt: connection refused HTTP/1.1 200 OK Server: fasthttp` from filtron, no matter what rate limits I set. My main objective here is to prevent google captcha blocking in searx.

**Comment by asciimoo** [comment]
Filtron is just a middleware between nginx and searx. 

> I think the reverse proxy nginx to filtron is easy and well documented - any chance to get some info on how to debug this? I am simply not sure if it is working or not.

You can debug the whole chain with `curl`. First try to get searx directly (e.g. `curl 127.0.0.1:8888`), then try through filtron (e.g. `curl 127.0.0.1:4004`) then with nginx (`curl 127.0.0.1`)

> How is filtron supposed to be running? Should it be the same user or a separate user? Startup via systemd? CRON? Other solutions?

It's your decision.

> How does the reverse proxy filtron -> uswgi work? Seems this was discussed in #543 by user @cy8aer but I do not understand the solutions there. From the description of filtron, I would assume that filtron directly writes on port 8888 and the only requirement is that uwsgi listens on 8888 - but how would I get this done?

Filtron cannot use wsgi protocol so you have to add the following line to your `uwsgi.ini` if you use searx with uwsgi:
```
http = 127.0.0.1:8888
```

**Comment by asciimoo** [comment]
@scroom awesome, thanks for the great article. We already have a small documentation section about filtron and I'd appreciate it if you could extend it with details from your article: https://asciimoo.github.io/searx/admin/filtron.html

**Comment by scroom** [comment]
@asciimoo How can I do so? Is it some part of github?

**Comment by asciimoo** [comment]
@scroom https://asciimoo.github.io/searx/dev/contribution_guide.html#documentation

**Comment by r4dh4l** [comment]
> Filtron cannot use wsgi protocol so you have to add the following line to your uwsgi.ini if you use searx with uwsgi:

> `http = 127.0.0.1:8888`

@asciimoo thank you very much but shouldn't this be part of https://asciimoo.github.io/searx/admin/filtron.html ?
