### ISSUE TITLE
[Engine] CORE in category science

### ISSUE THREAD

**Issue by jibe-b** [searx/searx#1044]
[CORE](https://core.ac.uk/) aggregates 8 million Open Access scientific publications and notices of 80 millions closed access publications.

There is an API with authentication. I discussed with the CORE team about the use of API keys by Searx instances.

One of the wishes from the CORE team is to write a testimonial of use of CORE by Searx, as is done by others at

https://core.ac.uk/about/endorsements

Here is a proposition:

> Users searching in the scientific literature need to access a large number of publications but it shouldn't stop at finding notices. As CORE aggregates full-text of scientific publications whenever possible, it is a source index of high interest for a meta-search engine like Searx.

@asciimoo, @kvch does it reflect well enough the concepts of Searx that deserve to be spread?

I am writing the core engine and when it will be merged, this text would appear on https://core.ac.uk/about/endorsements

**Comment by kvch** [comment]
I like your idea, but I have a few concerns regarding the authentication and API keys.

Does CORE worth it to leak that you are using a searx instance for searching?
How would the API keys be distributed? Would we have one for all of the instances or a key for every instance? If one is available for all of the instances, the key would be leaked, so their authentication would be useless. However, if every instance has one key, the instance is leaked to CORE. Also it raises more questions on distributing the keys.

**Comment by asciimoo** [comment]
@jibe-b, I can search on core.ac.uk without api key, which is the most privacy aware method of fetching data.

Demonstration: `curl -X POST -d '{"basicQuery":{"count":10,"searchCriteria": "[SEARCH_QUERY]","offset":0,"sortByDate":false},"facetMap":{}}' https://core.ac.uk/search/api/search`

**Comment by jibe-b** [comment]
The point made by @asciimoo solves the question for CORE (I'll make it a non authenticated engine).

@kvch 

> Does CORE worth it to leak that you are using a searx instance for searching?

I consider that CORE would have been worth the compromise, as they are non-profit and working to increase availability to full-text Open Access scientific publications. This should indeed be debated.

Yet, whenever there is a leak of privacy (activating in preferences an engine with an API key for example), there should probably be a banner on the Searx instance, so that users know such engines are activated.

However, I will raise the question again for other possible engines returning scientific publications. The biggest and most used indexes require authentication to access to their results. Although I don't agree with their policies, having these engines available as Searx engines may increase the usage of Searx in the scientific community.




>How would the API keys be distributed? Would we have one for all of the instances or a key for every instance?

This is a question I asked to the CORE team. The engine won't be authenticated in the end, so we don't need to answer it. I had ideas but I should test them before presenting them.

>If one is available for all of the instances, the key would be leaked, so their authentication would be useless.

I don't realize at which point the key would be visible to users. Can you help me?

> However, if every instance has one key, the instance is leaked to CORE. Also it raises more questions on distributing the keys.

Somehow, the API key would duplicate the already available information carried by the IP of the Searx instance.

**Comment by jibe-b** [comment]
The unauthenticated access to the data might be a bug.

**Comment by uderecife** [comment]
Any developments on this? It would be nice to have https://core.ac.uk/ as an additional engine for science.

**Comment by allendema** [comment]
Issue can be closed.

Engine added as of [Yesterday](https://github.com/searx/searx/commit/6513a5606431b5ab4fbe6eefb70510ba47ab5e04)
