### ISSUE TITLE
Disable Bing and Yahoo engines by default

### ISSUE THREAD

**Issue by ghost** [searx/searx#1055]
In engines > general , from "general" search engines Bind and Yahoo are enabled by default in addition to Google. Since both seem to consistently give inferior search results when compared to Google and [have nearly identical results](https://github.com/asciimoo/searx/issues/869), I ask you to disable Bing and Yahoo by default to improve experience for new users.

**Comment by ghost** [comment]
@asciimoo Reason?

**Comment by asciimoo** [comment]
@07416 see #869

**Comment by ghost** [comment]
@asciimoo Will you disable Bing or Yahoo by default?

**Comment by asciimoo** [comment]
@07416 i disabled yahoo in commit e2afc1c
