### ISSUE TITLE
Yacy results crash

### ISSUE THREAD

**Issue by songproducer** [searx/searx#1064]
Getting:
Engines cannot retrieve results:
yacy (unexpected crash)

> ERROR:searx.search:engine yacy : exception : 'url'
> Traceback (most recent call last):
>   File "/home/leo/searx/searx/search.py", line 118, in search_one_request_safe
>     search_results = search_one_request(engine, query, request_params, start_time, timeout_limit)
>   File "/home/leo/searx/searx/search.py", line 110, in search_one_request
>     return engine.response(response)
>   File "/home/leo/searx/searx/engines/yacy.py", line 80, in response
>     results.append({'url': result['url'],
> KeyError: 'url'

**Comment by kvch** [comment]
I tried reproducing your issue with a local YaCy instance. But everything works as expected. Which instance are you using?

**Comment by michaelschefczyk** [comment]
I have the same issue for more than a month now. I also use a local YaCy instance. You can reach it from the outside at https://yacy.schefczyk.net/

**Comment by kvch** [comment]
@michaelschefczyk thanks for sharing the URL of your instance.

**Comment by michaelschefczyk** [comment]
Dear Noémi Ványi,
you are most welcome. I would only wish that yacy was able to deliver a higher ratio of meaningful results. The idea here is to pass searx searches to the instance to trigger more targeted searches. Despite all the resources consumed by running yacy, that does not really seem to improve quality all too much.
Regards,
Michael Schefczyk
