### ISSUE TITLE
Dark theme (suggestion)

### ISSUE THREAD

**Issue by jugi1** [searx/searx#1070]
Can you please add dark theme style ?
(similar to duckduckgo)

**Comment by asciimoo** [comment]
@jugi1 this would be definitely a useful addition. As an alternative solution there are dark themes available on userstyles.org: https://userstyles.org/styles/browse/searx

**Comment by jugi1** [comment]
Thank you!

PS
Please also add SERBIAN language sr-SR.

**Comment by kvch** [comment]
Serbian language has been added. Feel free to translate.

**Comment by jugi1** [comment]
Where is it ?
I can't find it.

**Comment by asciimoo** [comment]
@jugi1 https://www.transifex.com/asciimoo/searx/language/sr/

**Comment by jugi1** [comment]
Done with translation!
https://www.transifex.com/asciimoo/searx/language/sr/

It should be:   Српски  (СРПСКИ)
It would be good if someone else check, correct and maybe propose better translation.

**Comment by aesthicc** [comment]
I second this. White burns my retinas at night. DuckDuckGo's appearance customization is wonderful.

**Comment by dalf** [comment]
see commit 46fb0d860e35a45658969c4e2ac306a1072bc331

**Comment by kvch** [comment]
Closing as dark version of oscar is available. Feel free to reopen if needed.
