### ISSUE TITLE
Put a "list of other Searx instances" page on searx.me

### ISSUE THREAD

**Issue by ghost** [searx/searx#1071]
This way it can be easier for people to discover other Searx instances without having to go to Github.

**Comment by ghost** [comment]
@kvch But it links to Github and not a page hosted on searx.me... (which was my proposal)

**Comment by kvch** [comment]
We don't want to have a list of searx instances in git. See in https://github.com/asciimoo/searx/issues/1113#issuecomment-351151611
I think it is an acceptable compromise between the two requirements.
