### ISSUE TITLE
Make HTTPS Everywhere rulesets for searx instances

### ISSUE THREAD

**Issue by ghost** [searx/searx#1072]
I already made a PR for some, hope someone else can continue the work:

- [x] searx.me.xml  - https://github.com/EFForg/https-everywhere/pull/13383
- [x] Framabee.org.xml  - https://github.com/EFForg/https-everywhere/pull/13383
- [x] Tonton_Roger.org.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] Trouvons.org.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] opengo.nl.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] rubri.co.xml  - https://github.com/EFForg/https-everywhere/pull/13383
- [x] search404.io.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] searchx.mobi.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] s3arch.eu.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] searx.at.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] searx.ch.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] searx.dk.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] searx.info.xml - https://github.com/EFForg/https-everywhere/pull/13383
- [x] searx.com.au - https://github.com/EFForg/https-everywhere/pull/13383
- [x] www.heraut.eu/search/ - https://github.com/EFForg/https-everywhere/pull/13383
- [x] perfectpixel.de/searx/ -  https://github.com/EFForg/https-everywhere/pull/13383
- [x] www.mercurius.space - https://github.com/EFForg/https-everywhere/pull/13383
- [x] pigtown.news/searx - https://github.com/EFForg/https-everywhere/pull/13383
- [x] p9e.de.xml - https://github.com/EFForg/https-everywhere/pull/13615
- [x] searxes.danwin1210.me - Preloaded.
- [x] suche.elaon.de - Preloaded.
- [x] search.notoriousdev.com - Preloaded.
- [x] roflcopter.fr - Preloaded
- [x] search.disroot.org - Pending inclusion for the preload list.
- [ ] searx.fi.xml - Needs PR.
- [ ] searx.abenthung.it  - Needs PR.
- [ ] searx.good.one.pl - Needs PR.
- [x] search.stinpriza.org - Needs PR.
- [ ] search.rubbeldiekatz.info - Needs PR.
- [ ] suche.ftp.sh - Needs PR.
- [ ] search.datensturm.net - Needs PR.
- [ ] searx.gotrust.de - Needs PR.
- [ ] search.gibberfish.org - Needs PR.
- [ ] searx.prvcy.eu - Needs PR.
- [ ] searx.apply55gx.com - Needs PR.
- [ ] searx.nulltime.net - Needs PR.
- [ ] searx.laquadrature.net - Needs PR.
- [ ] searx.oe5tpo.com - Needs PR.
- [ ] search.kujiu.org - Needs PR.
- [ ] searx.new-admin.net  - Needs PR.
- [ ] search.homecomputing.fr - Needs PR.
- [ ] searx.potato.hu  - Needs PR.
- [ ] searx.32bitflo.at  - Needs PR.
- [ ] search.jpope.org - Needs PR.
- [ ] searx.fossencdi.org  - Needs PR.
- [ ] search.koehn.com  - Needs PR.
- [ ] searx.ng0.infotropique.org - Needs PR
- [ ] searx.drakonix.net - Needs PR
- [ ] search.4ray.co - Needs PR
- [ ] search.alecpap.com - Preloaded.
- [ ] searx.aquilenet.fr - Needs PR
- [ ] search.azkware.net - Needs PR
- [ ] searx.techregion.de - Needs PR
- [ ] search.st8.at - Needs PR
- [ ] search.r3d007.com - Needs PR
- [ ] search.kosebamse.com - Needs PR
- [ ] search.paviro.de - Needs PR
- [ ] searx.infini.fr - Needs PR
- [ ] search.hzsogood.net - Needs PR
- [ ] searx.kvch.me - Needs PR
- [ ] searx.fr32k.de - Needs PR
- [ ] searx.remote-shell.net - Needs PR
- [ ] s.matejc.com - Needs PR
- [ ] searx.mrtino.eu - Needs PR
- [ ] win8linux.nohost.me - Needs PR
- [ ] searx.itunix.eu - Needs PR
- [ ] searx.impstyle.com - Needs PR
- [ ] searx.targaryen.house - Needs PR
- [ ] searx.steinscraft.net - Needs PR
- [ ] searx.antirep.net - Needs PR
- [ ] searx.glibre.net - Needs PR

-----

Note: Preloaded sites aren't to be included as rulesets for HTTPS Everywhere.

**Comment by ghost** [comment]
As a side note, it may also be worthwhile to promote HTTPS Everywhere so that searx users get its security benefits. Indeed, many searx instances don't have HSTS.

**Comment by ghost** [comment]
@janit Are you the operator of searx.fi? If so, you can see that it throws a 401, can you take a look at it?

**Comment by janit** [comment]
There was some traffic that looked malicious so I put it behind a password. In general are there incidents of robots crawling searx instances with terms such as:

"Alawar Crack 2017"
"Sayonara Umihara Kawase game"
"Bursa Otelleri 178 Otelde En Uygun Fiyat Neredekalco"
"richi youtube"
"Link Central SandWEB"
"contactscontract.commondatakinds.phone.contact_id"
