### ISSUE TITLE
Faster Searx (suggestion)

### ISSUE THREAD

**Issue by jugi1** [searx/searx#1077]
I would like to see option where users can quickly select several speed options,
so that Searx can search:

- **FAST** (minimal search engines selected for speed)
- **NORMAL** (standard default search engines selected)
- **TOTAL** (maximum all search engines selected - slower speed)

**Comment by jibe-b** [comment]
I really like this idea!

Please ping me if nobody advances on this within three weeks please.

**Comment by hook321** [comment]
@jibe-b

**Comment by CaffeinatedTech** [comment]
Yeah, I just started using searx, self-hosted.  It's taking 4 to 6 seconds of blank screen before the results appear.  I'd like a faster option also.  I assume that it is waiting for all engines to either return a result, or timeout.  I suppose the 'Fast' option could just set much lower timeouts, then on the results page give us a 'Search Harder' type button to either try a more relaxed timeout, or just re-sort the results including the results that came back late.

I haven't looked at the code, but here are two theoretical options:
- Fast search sets short timeouts, then on the results gives us a chance to do the full search
- Fast search just shows results sooner, then tells us when the rest of the results come in with a button to include them. This will no doubt re-order the page, so we don't want it to happen automatically.

**Comment by Pofilo** [comment]
Well, taking 1 or 4 or 6 seconds depends on the machine you use and your internet speed. Having a searx instance on a Raspberry Pi on a small home internet connection doesn't seem to be a good idea for example. 

What is your current configuration ?

**Comment by CaffeinatedTech** [comment]
My Searx instance is running in docker on my FX6300 machine behind 100Mbit down 40Mbit up connection.  The issue is more that I'm in AU, so it takes longer to talk to most of the search engines.

Turning off certain engines obviously makes it go fast, because its not waiting for them.  It'd be nice if I could make the default search be fast, then have it take a longer look if I need it, without going in and changing the selected engines all the time.

**Comment by dalf** [comment]
The speed of one engine may change over time (wikidata seems slower than before, for example).

I've implemented a timeout limit per request. See #1640 for the syntax & parameter. Feedback is welcome.

**Comment by CaffeinatedTech** [comment]
That looks cool @dalf 
A setting in settings.yml to set the default timeout_limit might be handy.  I could set the default to 2 seconds for instance, then if I want to do a more thorough search I can use the URL parameter. "<2000" for example ( I think that is 20 seconds looking at your code. )

**Comment by dalf** [comment]
> A setting in settings.yml to set the default timeout_limit might be handy.

What about :
https://github.com/asciimoo/searx/blob/cfcbc3a5c344037fb5423c14223e72578170a234/searx/settings.yml#L37 ?

**[EDIT]**
See https://github.com/asciimoo/searx/blob/99d1b796545cfeecf8d3d1a7edd707bbcfabdc3e/searx/search.py#L431
The maximum is 20 seconds, actually I don't know which value do you use ?

>  if I want to do a more thorough search I can use the URL parameter. "<2000" for example 

Yes. The split between second and centisecond can be at 20 : 
<20 = 20 seconds.
<21 = 210 milliseconds.
But it is more confusing.

**Comment by CaffeinatedTech** [comment]
Oh its already there, sorry.  My engine stats show certain engine times longer than that 2.0 seconds in my settings file.

I guess the individual engine timeouts override the request_timeout?  If I turn off reddit and wikidata it speeds up pretty well.

**Comment by dalf** [comment]
BTW have look to PR #1637 : you can see the response per engine (total time, load time = HTTP request time).

**Comment by virtadpt** [comment]
@CaffeinatedTech I usually set them all to 30 seconds, just to have enough time.

**Comment by dalf** [comment]
@CaffeinatedTech 

> I guess the individual engine timeouts override the request_timeout? If I turn off reddit and wikidata it speeds up pretty well.

Yes, searx takes the maximum between individual engine timeouts and ```settings.yml:outgoing.request_timeout```

I've updated the PR: the effective timeout will be minimum between the above value and the one asked by the user. 

Purpose: avoid potential deny of service by sending multiple queries with long timeouts.

So the use case would be: 
* set a long timeout in settings.yml (because it's your private searx instance and/or don't mind some downtime)
* when needed, ask for a quick answer using "<[num]" or the timeout_limit parameter.

**Comment by dalf** [comment]
See https://github.com/asciimoo/searx/pull/1640#issuecomment-517227357

**Comment by kvch** [comment]
I am closing this issue as now it is possible to configure timeout both by request using the syntax `<{number}` and globally using the `max_request_timeout` in `settings.yml`. Feel free to reopen this issue, if these options are not sufficient.
