### ISSUE TITLE
quoted string search finds partial matches

### ISSUE THREAD

**Issue by ghost** [searx/searx#1080]
**current behavior**
When searching for `"Error invalid CA certificate getting chain"` (literally with quotes included), results include instances where those words are scattered about.

**expected behavior**
A quoted string should first match literal exact occurances, treating the whole string as if it were one atomic word.

The searx instance used here was http://o2jdk5mdsijm2b7l.onion

**Comment by kvch** [comment]
I tested your example using Google and it returns 
> No results found for "Error invalid CA certificate getting chain".

Below this message it shows the results for the query without quotes.

The correct query is sent to search services including `"`. But if there are no results, these services usually return results for the unquoted query. That is why you see those words scattered about in the results.

**Comment by ghost** [comment]
Ok, thanks.  I wondered about that.  I think I saw that among the sites with partial matches, the full string was present, but perhaps the full string just didn't get indexed for some reason.
