### ISSUE TITLE
copyright status of searx/static/themes/simple/js/searx_src/autocomplete.js

### ISSUE THREAD

**Issue by josch** [searx/searx#1091]
Hi,

I'm about to package version 0.13 of searx and I noticed the file `searx/static/themes/simple/js/searx_src/autocomplete.js` which contains a line with 852 characters. I wanted to confirm with you the copyright of that file because it doesn't seem like a line with 852 characters is the preferred form of modification but instead was copypasted from something that was minified from other sourcecode. That the variable names in this long line are only one character each hardens this suspicion.

So could you please clarify the original source of this file and what its copyright status is?

Thanks!

cheers, josch

**Comment by asciimoo** [comment]
@dalf could you fix this?

@josch  I'm preparing a new release (0.13.1) with other fixes, so perhaps it would be good to wait for 0.13.1 with packaging.

**Comment by josch** [comment]
Thanks for the quick response and the heads-up!

I'd also appreciate clarification about the copyright of other material from the simple theme. For example `searx/static/themes/simple/magnet.svg` contains the information that it was created by Dmitry Baranovskiy but I cannot find any information about its license anywhere.

And then there is the directory `searx/static/themes/simple/fonts/` which contains files that claim to be generated using grunt-webfont (but from what?) and an svg that claims being created by a person named alexandre but again without any copyright information.

Thanks!

cheers, josch

**Comment by dalf** [comment]
Some details. 

The original is written in typescript :
https://github.com/autocompletejs/autocomplete.js/blob/2.6/src/autocomplete.ts

The current searx master contains a modified   Javascript version.

The font is subset of ionicons as you can see gruntfile.js. See http://ionicons.com
There is one exception : magnet.svg

**Comment by josch** [comment]
Hi,

okay... this lets me assume that `./searx/static/themes/simple/less/autocomplete.less` is also from the autocomplete.js project?

Do you know of any other files from the simple theme for which you do not have the copyright so that we can correctly attribute the original authors together with the correct license?

Also, you say that autocomplete.js is a modified version. Do you plan to regularly update autocomplete.js and apply your patches on top? It might make more sense to suggest your changes to the autocomplete maintainers so that you do not need to carry a patched version of the code. Are your changes truly necessary for the functionality of the simple theme or are they purely cosmetic?

What is the copyright situation of magnet.svg if it doesn't belong to ionicons?

Thanks!

cheers, josch

**Comment by dalf** [comment]
Yes autocomplete.less is also part of the autocomplete.js project.

About autocomplete.js : I've made contributions to the project, but the author didn't gave answer in time, that's why I ended up in this solution.

I will make a full review of the copyrights of the simple theme files tonight (Europe time) or tomorrow night.

**Comment by josch** [comment]
Thanks for your work! There is of course no rush. In the very worst case, if you don't find time, then we can also just release 0.13 without the simple theme.

Could you point me to the issue that you filed with the autcomplete.js maintainers? Edit: you are probably talking about https://github.com/autocompletejs/autocomplete.js/issues/43 It seems the autocomplete.js maintainer is waiting for you to allow enabling and disabling the component according to user preference.

Which tool can one use to convert a typescript file into javascript? Then I can verify the path from the autocomplete.ts to the autocomplete.js myself. Edit: found the answer to my question. It's the tsc tool from the node-typescript package.

**Comment by dalf** [comment]
package.json describe the imported NPM packages : 
- https://www.npmjs.com/package/grunt-webfont(MIT license : https://github.com/sapegin/grunt-webfont/blob/master/License.md )
- https://www.npmjs.com/package/ionicons-npm (MIT license : https://github.com/ionic-team/ionicons/blob/master/LICENSE )
- https://www.npmjs.com/package/jslint ( BSD 3-clause license : https://github.com/reid/node-jslint/blob/master/LICENSE )
- https://www.npmjs.com/package/less-plugin-clean-css ( Apache License 2.0 license : https://github.com/less/less-plugin-clean-css/blob/master/LICENSE ) 
- grunt and related tools ( main tool : https://github.com/gruntjs/grunt/blob/master/LICENSE )

These packages are not in the searx code base tree with the exception of ionicons-npm : it's a webfont, a subset is maded using grunt-webfont (see https://github.com/asciimoo/searx/blob/master/searx/static/themes/simple/gruntfile.js#L79 ) 
The results is under the fonts directory (all the files here are the result of grunt-webfont, there is also ./less/ion.less file produced by grunt-webfont)
Of course there is an exception : madnet.svg found : https://thenounproject.com/term/magnet/5022/ the website says " Creative Commons CCBY".
What should be done ? remove it ? modify the files to add a reference to the website ?

About autocomplete.js, my list of contributions : 
- https://github.com/autocompletejs/autocomplete.js/pull/47
- https://github.com/autocompletejs/autocomplete.js/issues/46
- https://github.com/autocompletejs/autocomplete.js/issues/40
- https://github.com/autocompletejs/autocomplete.js/issues/39
- and opened one : remaining https://github.com/autocompletejs/autocomplete.js/pull/48

Honestly I need time to compare the version in searx and in autocomple.js .
There is still a lot of work to do for the simple theme but it is more than usable now ( https://github.com/asciimoo/searx/issues/1025 )

The file list : 

```
./.jshintignore
./img/favicon.png               <-- copy/paste from oscar theme
./img/logo_searx_a.png          <-- copy/paste from oscar theme
./img/searx.png                 <-- copy/paste from oscar theme
./img/loader.gif                <-- copy/paste from oscar theme
./img/searx_logo.svg            <-- copy/paste from oscar theme
./package.json			<-- describe the NPM packages to build the simple theme.
./gruntfile.js                  <-- describe how to build the content of css, fonts, and searx.js, searx.min.js
./magnet.svg			<-- see above
./leaflet/leaflet.js		<-- there is the copyright inside (the version could be updated BTW...)
./leaflet/images                <-- either copy from oscar theme or from the leaflet archive
./leaflet/images/marker-icon-orange.png	
./leaflet/images/marker-icon-2x.png
./leaflet/images/marker-icon-2x-green.png
./leaflet/images/marker-icon-2x-red.png
./leaflet/images/marker-icon-red.png
./leaflet/images/marker-icon-green.png
./leaflet/images/marker-icon-2x-orange.png
./leaflet/images/layers.png
./leaflet/images/marker-shadow.png
./leaflet/images/marker-icon.png
./leaflet/images/layers-2x.png
./leaflet/leaflet.css           <-- from the leaftlet project
./css/searx.css                 <-- compiled by gruntfile.js from ./less/searx-rtl.less and the referenced files (all under ./less)
./css/searx-rtl.css             <-- compiled by gruntfile.js from ./less/searx.less and the referenced files (all under ./less )
./css/searx.min.css		<-- minified version searx.css
./css/searx-rtl.min.css         <-- minified version searx.min.css
./fonts/ion.ttf
./fonts/ion.woff
./fonts/ion.css
./fonts/ion.svg
./fonts/ion.woff2
./fonts/ion.eot
./fonts/ion.html
./less/style-rtl.less
./less/ion.less                         <-- build with grunt-webfont
./less/autocomplete.less                <-- from the autocomple.js project
./less/toolkit.less
./less/index.less
./less/code.less                        <-- copy/paste from oscar theme
./less/definitions.less
./less/normalize.less                   <-- MIT license
./less/style.less
./less/search.less
./less/mixins.less
./less/preferences.less
./less/stats.less
./js/searx.js                           <-- concatenation of the files inside searx_src build with grunt
./js/searx.min.js.map                   <-- built with grunt too
./js/searx_src
./js/searx_src/searx_search.js
./js/searx_src/autocomplete.js          <-- see above
./js/searx_src/searx_mapresult.js
./js/searx_src/searx_imageresult.js     <-- from http://trinhtrunganh.com/2014/09/12/google-image-layout/
./js/searx_src/00_searx_toolkit.js
./js/searx_src/searx_results.js
./js/searx_src/searx_keyboard.js	<-- heavily modified version of https://github.com/asciimoo/searx/blob/master/searx/static/plugins/js/vim_hotkeys.js
./js/searx.min.js                       <-- minified version searx.js
```

**Comment by josch** [comment]
Hi,

thanks for your detailed analysis. The licenses of grunt related tools or jslint and clean-css are irrelevant though. This is only about the copyright of the content that *you* distribute.

grunt-webfont is not packaged for Debian so we cannot bundle the svgs to the searx-specific ion.woff. But this is a Debian-specific problem and nothing you should worry about. We have to solve this in Debian.

The CC-BY 3.0 liense of magnet.svg is fine for Debian. And even if it were not, this would not be a problem that *you* have to care about but something that we in Debian have to find a solution for. :)

Though I would really recommend that you put information about individual file licensing *somewhere* in your git. For example the file `./searx/static/themes/simple/less/autocomplete.less` doesn't contain any information that it comes from the autocomplete.js project. The autocomplete.js author distributes their software under the MIT license which only has one condition:

    The above copyright notice and this permission notice shall be included in all copies or substantial     portions of the Software.

If you are not doing that, then you are violating their license terms.

Thanks a lot for your detailed analysis!

**Comment by dalf** [comment]
Note : searx doesn't need grunt-webfont except at the build time to create the fonts which are commited into the git tree. 

I haven't found a easy way to replace the ```
Created by FontForge 20120731 at Fri May 26 22:22:55 2017
 By alexandre,,,
```
by something more appropriate in the SVG. I can give a try to 
https://github.com/bdukes/grunt-xmlpoke
But the problem still exist with the other font formats : the metadata doesn't contains a reference to the ionicons original font.

**Comment by josch** [comment]
As far as I'm concerned this bugreport is fixed. I just needed to know the copyright so that I can add the appropriate copyright notices or remove the respective material. In case of the embedded ionicons I just removed them from the Debian package because we unfortunately do not yet have grunt-webfonts in Debian so there is no way to build the webfont from source. I will reintroduce the ionicons font once grunt-webfonts is in Debian.

This is btw also why you might want to ship your own Debian packages (if you care about that) because then you don't have to abide by the strict rules of the Debian distribution and can instead ship whatever you see fit to distribute to your users. :)

**Comment by dalf** [comment]
As I can see the python3-searx package (in sid) contains references to the fonts (ion.ttf, ion.eot, etc..) in searx.min*.css
It will create  404 errors on the HTTP server

Worse it will make the theme not usable (the preference icon is displayed only using this font for instance).

Possible workaround : use the unmodified ionicons downloaded directly from https://github.com/ionic-team/ionicons (the dependency to grunt-webfont is removed)

Quick workaround : remove the simple theme.

**Comment by josch** [comment]
Downloading the unmodified ionicons is not a solution because that one will not include magnet.svg.

This is a Debian specific problem and thus I suggest that we continue this discussion to find a good solution in the Debian bugtracker:   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882847

You can reply to the bug by sending an email to 882847@bugs.debian.org.

**Comment by josch** [comment]
@dalf: Another thing that you might be interested in relates to the magnet.svg. The website where you have it from says: https://thenounproject.zendesk.com/hc/en-us/articles/200509928-How-do-I-give-creators-credit-in-my-work-

> If you choose to give creator credit to download an icon for free, then you need to follow these requirements: 
> 
> The format should be “Icon name” by Creator Name, from the Noun Project. The icon name must be hyperlinked to the original source. If you can’t hyperlink in the medium you’re using the icon, then type out thenounproject.com as the source. This attribution must be listed next to the icon, below the icon, or somewhere on the project you create to properly reference the icon. 

I believe such a credit notice is not yet included anywhere in the simple theme.
