### ISSUE TITLE
donation button

### ISSUE THREAD

**Issue by ghost** [searx/searx#1092]
I've started getting lots of queries. An awful amount of queries. If my bandwidth wouldn't be completely without limit (on the basis of fair share and community service), I would really have to consider to put an monthly limit to the searx part of my server.

While the service will always remain Free Software with the ability to selfhost, what do you think about
adding a donation button / option to the themes?
One case in the wild I know of where this happened in late development is the social network software Diaspora.

**Comment by Pofilo** [comment]
You can simply add this button to your instance on the main page.
And if you want (you should) to upgrade your instance, you just have to make a merge (you should never see any conflicts).

Even if it is an option, it will quite be never used, so it is more complicated to add it (like which donation system should we use (paypal, patreon ...)).

But you can still add it and try to make a pull request, just my opinion :)
