### ISSUE TITLE
Reformat dates into ISO 8601

### ISSUE THREAD

**Issue by ghost** [searx/searx#1095]
I'm not sure if this is anything that you can control, But I've noticed that in some search results the date can vary.

Here's an example for when I search for "Mama Luigi"

> 10 sept 2011

> 3-7-2006

[https://en.wikipedia.org/wiki/ISO_8601](here) is the page explaining the format incase you don't know.

**Comment by kvch** [comment]
In engines which parse published date, all of them are shown in the same format under the title of the result. See: `!news mama luigi`

Your example is part of the content of a result. In those cases where no date is parsed, only passed from the source service, it is possible to have differences. The format could be controlled if those engines parsed the dates of the results.
