### ISSUE TITLE
duckduckgo definition resturns garbled messages when trying to extract itunes info

### ISSUE THREAD

**Issue by tinyboxvk** [searx/searx#1097]
Try searching "we bare bears", and on the right side panel there will be something like
Instance of {u'entity-type': u'item', u'id': u'Q581714', u'numeric-id': 581714}
which should've been the itunes information.

**Comment by dalf** [comment]
Q581714 is the wikidata id : [animated series](https://www.wikidata.org/wiki/Q581714)
Getting the name from the id requires an additional HTTP request to wikidata.

**Comment by asciimoo** [comment]
Then we have three options:
 - Do another request to fetch these information
 - Exclude it from the infobox
 - Create a link from it which points to wikidata

The third option is the preferred solution to me. It doesn't require another request and doesn't hide information.
