### ISSUE TITLE
How to remember the preferences ?

### ISSUE THREAD

**Issue by devwww** [searx/searx#1100]
Hi there, 

I'm using Framabee instance for my search engine. I have defined my language, the search engines where I want to look for, my plugins,... everything, and I save it.
Maybe this is stored in a cookie ? I don't know, but after a few days, I have to reconfigure it from scratch... Nothing is remembered :(
I know the topic is not to store datas of the user, but there it's not very useful if I need to set up the preferences each week.
Is it possible to define an unique url, with all the options stored, that we can put in bookmarks, and call it when we use the search engine ? If it's anonymously, it would be a good privacy, and there the preferences would be kept. I don't remember who is using the method, maybe DDG, or Starpage ? But it was easy to use.
Or anything else, whatever, something to avoid to redefine all again and again :)

Thank you for your work.

**Comment by kvch** [comment]
Preferences are stored in cookies if you save them. After the save a search URL is generated of those preferences. So if you want to, you can save that URL in your browser and search using that URL.

**Comment by devwww** [comment]
Hi kvch, thanks for your answer.
I check it, after saving the preferences, I have not url which could save it.
I use Framabee instance, maybe it's a different way than Searx.
The preferences are at [https://framabee.org/preferences](https://framabee.org/preferences)
When I save, I return to [https://framabee.org](https://framabee.org), nothing else is mentioned.

**Comment by Pofilo** [comment]
Try it on searx.me or other instances (with a more recent version than framabee).

**Comment by Pofilo** [comment]
In the file ` searx/searx/templates/simple/preferences.html` why don't we have

```
<p style =" margin:20px 0;">{{ _('Search URL of the currently saved preferences') }} <small class="text-muted">({{ _('Note: specifying custom settings in the search URL can reduce privacy by leaking data to the clicked result sites.') }})</small>:<br/>
          <input readonly="" class="form-control select-all-on-click cursor-text" type="url" value="{{ url_for('index', _external=True) }}?preferences={{ preferences_url_params|e }}{% raw %}&amp;q=%s{% endraw %}">
</p>
```

as in the oscar template ?

Otherwise, there is no way to have the url to save the settings using the simple theme.

**Comment by dalf** [comment]
@Pofilo it's on the TODO list see : #1025 
Feel free to make a PR.

**Comment by MilkManzJourDaddy** [comment]
@devwww , have a look at #1087 as it seems to fit your use-case.

**Comment by devwww** [comment]
@MilkManzJourDaddy 
Ok thanks. It seems it not yet supported by Framabee. I'll wait for that :)

**Comment by AyoungDukie** [comment]
Can someone clarify for me the way this works currently? I would be happy to help add a wiki/documentation entry for this process, however I currently seem to be missing something (ie maybe this is still WIP?):

1. I configured one browser with my desired preferences, and pressed save.

2. I re-navigated to Preferences, then I highlighted and copied the URL listed at the bottom of the page

3. I opened an un-configured browser, pasted in this URL a couple different ways to attempt to fetch the new cookies and overwrite the existing.

    - First I pasted raw, unchanged URL from the generated field (complete with `&q=%s`)
    - Next I tried replacing the `%s` portion with something generic (ie `TEST`) .
    - Finally I removed `&q=%s` completely, which broght up the main search page.

In each case, the default cookies were used, ignoring the preferences called out by the url. 

Is there a step that I am missing? I tried to see if there was anywhere I could paste the URL in settings and press save, but there did not appear to be something here (the URL "field" there is for the existing preferences only, right? I cannot simply paste over it with a new set of settings?).

Any clarifications would be much appreciated.

**Comment by MilkManzJourDaddy** [comment]
"[@jtflynnz](https://github.com/jtflynnz) It's simple, really as I highlight in the issue for which this is a duplicate, #1087 [See https://github.com/asciimoo/searx/issues/1087#issuecomment-351580996



.  `↵↵¶`

**Comment by MilkManzJourDaddy** [comment]
[@jtflynnz](https://github.com/jtflynnz) It's simple, really as I highlight in the issue for which this is a duplicate, #1087 [See this comment](https://github.com/asciimoo/searx/issues/1087#issuecomment-351580996).

**Comment by farvardin** [comment]
> Can someone clarify for me the way this works currently? I would be happy to help add a wiki/documentation entry for this process, however I currently seem to be missing something (ie maybe this is still WIP?):
> 
>     1. I configured one browser with my desired preferences, and pressed save.
> 
>     2. I re-navigated to Preferences, then I highlighted and copied the URL listed at the bottom of the page
> 
>     3. I opened an un-configured browser, pasted in this URL a couple different ways to attempt to fetch the new cookies and overwrite the existing.
>        
>        * First I pasted raw, unchanged URL from the generated field (complete with `&q=%s`)
>        * Next I tried replacing the `%s` portion with something generic (ie `TEST`) .
>        * Finally I removed `&q=%s` completely, which broght up the main search page.
> 
> 
> In each case, the default cookies were used, ignoring the preferences called out by the url.
> 
> Is there a step that I am missing? 


I've search it a bit until I understood the right way of doing it:

when you paste the ``https://searx.be/?preferences=eJxtVk/.../&q=%s`` into the address bar, it will replace the ``?preference`` by ``search?preference=``  and you won't be able to save the cookie.

Just copy the URL from the preference page, paste it into a text editor, add preferences before the ?preferences (it will become ``preferences?preferences``) and remove the ``&q=%s`` part.

Then you'll get the preferences panel with your options preconfigured, and you can save the cookie.

It's not very obvious nor user friendly, the preferences option should give the correct URL to save preferences into a new browser, instead of this "search" link which won't work for 99% of the people (it will return a search for "%s")

**Comment by unixfox** [comment]
> > Can someone clarify for me the way this works currently? I would be happy to help add a wiki/documentation entry for this process, however I currently seem to be missing something (ie maybe this is still WIP?):
> > ```
> > 1. I configured one browser with my desired preferences, and pressed save.
> > 
> > 2. I re-navigated to Preferences, then I highlighted and copied the URL listed at the bottom of the page
> > 
> > 3. I opened an un-configured browser, pasted in this URL a couple different ways to attempt to fetch the new cookies and overwrite the existing.
> >    
> >    * First I pasted raw, unchanged URL from the generated field (complete with `&q=%s`)
> >    * Next I tried replacing the `%s` portion with something generic (ie `TEST`) .
> >    * Finally I removed `&q=%s` completely, which broght up the main search page.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In each case, the default cookies were used, ignoring the preferences called out by the url.
> > Is there a step that I am missing?
> 
> I've search it a bit until I understood the right way of doing it:
> 
> when you paste the `https://searx.be/?preferences=eJxtVk/.../&q=%s` into the address bar, it will replace the `?preference` by `search?preference=` and you won't be able to save the cookie.
> 
> Just copy the URL from the preference page, paste it into a text editor, add preferences before the ?preferences (it will become `preferences?preferences`) and remove the `&q=%s` part.
> 
> Then you'll get the preferences panel with your options preconfigured, and you can save the cookie.
> 
> It's not very obvious nor user friendly, the preferences option should give the correct URL to save preferences into a new browser, instead of this "search" link which won't work for 99% of the people (it will return a search for "%s")

Can you open a separate github issue for that?
