### ISSUE TITLE
instant search results while typing?

### ISSUE THREAD

**Issue by waldenn** [searx/searx#1101]
Is there a way to setup AJAXy instant search results while typing with Searchx?

I know this takes a lot of resources (network and CPU), but it would help search usability a lot for our specific use case.

Thanks, keep up the good work!

**Comment by waldenn** [comment]
Ah.. I did not realize it doesn't do its own indexing, so I guess instant-search is not an option.

**Comment by dalf** [comment]
may be Qwant/Instant-Answers ...
