### ISSUE TITLE
Time range filter doesn't work on Chrome browser

### ISSUE THREAD

**Issue by svofusihan** [searx/searx#1102]
on Chrome browser nothing happens when changing value of this filter

**Comment by kvch** [comment]
Have you clicked on the search button? Time range filters only work after you push that button.

**Comment by svofusihan** [comment]
Okay, right. But on Firefox, or even Edge, there is no need to click on the search button, the page is automatically reloaded and the results updated.

**Comment by dalf** [comment]
Which theme do you use? Which instance?`

**Comment by svofusihan** [comment]
Default settings. So Oscar theme.
Instance searx.me. But also tried others, same behaviour.
Don't you reproduce it?

**Comment by kvch** [comment]
I am able to reproduce it. I just did not know that searx had this feature. :D

**Comment by kvch** [comment]
But according to git history I am the person I added time range search to the script which enables search on selecting something from a search drop down.
