### ISSUE TITLE
Nginx failed with default or simplest settings

### ISSUE THREAD

**Issue by TT-SWP13** [searx/searx#1104]
Hi all,

I am followed the [basic installation steps ](https://asciimoo.github.io/searx/dev/install/installation.html#basic-installation). I have often repeated these steps in the last two days, but i allways got the same issue with Nginx. [System: Raspbian Jessie on Raspberry 3B]

With Lynx i can access the Webpage from python searx/webapp.py (http://localhost:8888).
But Nginx do not want start with the default settings (yes i change the server name).
Several Domains already run with nginx successfully on this server. 

## Nginx** Error (Main-Issue):
1. Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.

### Errors during the installation of searx (Check with **python searx/webapp.py**):
1. WARNING:searx:You are using an old openssl version(OpenSSL 1.0.1t  3 May 2016), please upgrade above 1.0.2!
- but the command **openssl version** say "_OpenSSL 1.0.2m  2 Nov 2017_"
2. CRITICAL:searx.webapp:The pyopenssl package has to be installed.
- but **pip install pyopenssl** say "_Requirement already satisfied_"

Is the above (pip install pyopenssl) needs to be done using the virtualenv's pip? (ImportError: cannot import name HashMissing)

**Output** of systemctl status nginx.service:
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled)
   Active: failed (Result: exit-code) since Do 2017-11-30 12:49:52 CET; 8s ago
  Process: 2246 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

**Output** of journalctl -xn
● No journal files were found.

**Comment by dalf** [comment]
I think this is a problem with virtualenv : when you install pyopensll I guess it's inside a virtualenv. When searx starts as a service, it may use another virtualenv or not at all.

You may wish to try the searx package in sid : 
https://packages.debian.org/sid/web/searx

**Comment by TT-SWP13** [comment]
Thank you very much! I will try it on an several system.
