### ISSUE TITLE
morty key not working

### ISSUE THREAD

**Issue by joshu9h** [searx/searx#1108]
if i set the morty key in settings.yml

 key: key123

morty -key key123 -listen 127.0.0.1:3080 it works oke
but also without key with leaving settings.yml as it was
morty -listen 127.0.0.1:3080 it works also oke

also if you fill in
 key 123456
It gives a internal server error

**Comment by asciimoo** [comment]
@joshu9h `123456` is interpreted as an integer in yaml, put quotes around it: `key: "123456"`

**Comment by joshu9h** [comment]
Thanks asciimoo with quotes it's working
now i also see the morty hash link
I see how it is working
This issue can be closed

**Comment by andrescolmenarez96-lgtm** [comment]
Hola

**Comment by andrescolmenarez96-lgtm** [comment]
Es gratis
