### ISSUE TITLE
document location of instances

### ISSUE THREAD

**Issue by scarejar** [searx/searx#1115]
When I used searx.me , there's a pretty noticeable delay and I thought it was searx being slow but after switching to one locally in my area, it got way more snappier.

**Comment by Pofilo** [comment]
You can find lists of instances [here](https://github.com/asciimoo/searx/wiki/Searx-instances) or [here](http://stats.searx.oe5tpo.com/) (it uses [this tool](https://github.com/pointhi/searx_stats) but [this one](https://github.com/dalf/searx-stats2) is more recent).

Searx is not used to be slow, you should try an instance closer to where you live :)

**Comment by unixfox** [comment]
https://searx.space
