### ISSUE TITLE
google (unexpected crash: CAPTCHA required) with searx 0.13.1

### ISSUE THREAD

**Issue by ghost** [searx/searx#1117]
And problem occurs again. searx - 0.13.1 -> google (unexpected crash: CAPTCHA required)

How can i debug this any further?

thanks and cheers

**Comment by prolibre** [comment]
For more than a week... impossible for me to get out of it.
Depuis plus d'une semaine... impossible pour moi d'en sortir.

**Comment by ghost** [comment]
Yeah. As discussed in https://github.com/asciimoo/searx/issues/1089#issuecomment-351942306 it doesn't seem to be the fault of searx.

**Comment by ghost** [comment]
Switching to another VM with another IP solves the problem for now. Lets see for *how* long.
