### ISSUE TITLE
Logicodev dark style glitch with Falkon

### ISSUE THREAD

**Issue by ghost** [searx/searx#1129]
When the style is set to Logicodev dark this styling error occurs on the first search result when using web browser Falkon (tested with Brave & Waterfox and this does not occur):

![screenshot_2017-12-22_15-09-27](https://user-images.githubusercontent.com/15079776/34311198-39a98ac4-e72a-11e7-9e86-3a19fba88fbc.png)

Application version 2.1.99 (8f542a6e) & QtWebEngine version 5.9.3
https://phabricator.kde.org/source/falkon/

**Comment by asciimoo** [comment]
probably related to #1141

**Comment by coaxial** [comment]
FWIW, I cleared my cache in Firefox and it went away. I couldn't reproduce using private mode so I figured it could be cached CSS maybe.

**Comment by ghost** [comment]
Hm.  Seems to have fixed itself (I no longer have the issue).
