### ISSUE TITLE
Is this some bad joke from Bing's API maintainers?

### ISSUE THREAD

**Issue by ghost** [searx/searx#1131]
<img width="827" alt="screen shot 2017-12-27 at 12 28 12 am" src="https://user-images.githubusercontent.com/9938439/34367065-97130660-ea9d-11e7-90bb-a5ff7b9a0b7e.png">

WARNING: don't go to the website on the first result! For those wondering it's a picture of some zombie-looking woman with high-pitched screaming sounds at max volume.

Trust me it's no fun to be listening to nice music at 80% volume and get that crap. My heart was beating really fast for a good 10 minutes due to the effect of surprise, and my ears still hurt.
Why is that website the first result?

I tried the same query directly on bing.com since it is mentioned as the source, with and without safe search enabled, and I never got that on the first page.

**Comment by kvch** [comment]
Does it show up for other search querys, too? I haven't been able to reproduce the issue with several instances and searching for a few times.

**Comment by ghost** [comment]
Well no I don't get the website with other queries (unless it's just the problematic query with changed orders of words).

I even tried with searx.me on Tor Browser and I still get that.

-------- Original Message --------

**Comment by hiragashi** [comment]
I get it here too - scared the bejeezus out of me. it's an old site, a bit like a rick roll. There are no site meta tags or anything. It's gotta be someone at Bing frigging around

**Comment by Silent-Hunter** [comment]
Appears to be fixed, I tried the same search string as yassinei and that site wasn't in the results.

**Comment by r1bnc** [comment]
I tried it with my own instance and I got it but not on the first result.
