### ISSUE TITLE
Preserve URL param preferences when selecting categories

### ISSUE THREAD

**Issue by smithfred** [searx/searx#1138]
At the moment, specifying the GET method pref via a param (e.g. https://searx.instance/?method=GET&q=blah) causes searx to continue to use GET when for example clicking through to page 2 (https://searx.instance/?category_general=1&q=blah&pageno=2&time_range=None&language=en-US).

However, clicking on a category, e.g. "Images", causes it to revert to POST (or at least the URL reverts to https://searx.instance/). Instead this should work the same as pagination, and result in a URL of e.g. https://searx.instance/?method=GET&categories=images&q=blah

**Comment by capiscuas** [comment]
We installed a recent instance of searx and one of the first petitions from users was that they couldn't copy paste the search request from the url, it is true that shows up in a right box like here:
![image](https://user-images.githubusercontent.com/515154/48671472-16974900-eb29-11e8-8045-8339c6f38e9d.png)

but would be great if it can change the url everytime performing a search. Is there any admin preferences to make this happen or it hasn't been implemented yet?
