### ISSUE TITLE
"!yt" returns results only a fraction of the time

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [searx/searx#1140]
edit : it seems that using GET instead of POST gets rid of the issue. Does that mean that my setup could be the source of the issue ?

Hi,
I seem to have found a pretty obvious bug with searx. It doesn't seem to come from me or my setup though. I don't understand why it happens and searx seems to be the problem since I've had it on at least two different instances (both running 0.13.1, and one being https://searx.me/).

Basically the issue seems to be that youtube send results only a portion of the time. (about half in my case)

STEPS TO REPRODUCE :
* type `!yt keyword` in searx
* wait for some results to load
* refresh the page/redo you search severall times...
* ...until you see the error `Sorry! we didn't find any results. Please use another query or search in more categories.`

I also don't know if this happens with some other *!bangs* or *!qwicks*

What can I provide you to help you replicate or locate the issue ?

**Comment by Pofilo** [comment]
Still happens sometimes on 0.14.0.

**Comment by asciimoo** [comment]
Cannot reproduce with the current youtube engine.
