### ISSUE TITLE
Logicodev dark + vim mode = white highlights

### ISSUE THREAD

**Issue by coaxial** [searx/searx#1141]
If I enable the logicodev dark theme and enable the vim key bindings for navigation, the highlighted search result is retina scorching white instead of a darker colour. I believe this is unintentional as the contrast is too harsh. Maybe a grey highlight would be easier on the eyes?

Here is a screenshot, notice how the highlighted (third) result is white.

![screenshot from 2018-01-12 22-09-47](https://user-images.githubusercontent.com/2927869/34902241-8a4ca09e-f7e5-11e7-9915-11b7d6245ba8.png)

**Comment by asciimoo** [comment]
It works for me on searx.me and on searx.kvch.me with both firefox and chromium.

**Comment by coaxial** [comment]
Clearing my cache fixed it. Thanks!
