### ISSUE TITLE
Requirements error Ubuntu 17.10

### ISSUE THREAD

**Issue by songproducer** [searx/searx#1147]
> sudo apt-get install python-pybabel
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package python-pybabel is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'python-pybabel' has no installation candidate
>

**Comment by xinomilo** [comment]
python-babel package replaces it. python-pybabel was a transiotional package for some time, it's now removed in newer ubuntu & debian versions. same error in debian stretch. maybe the installation guide needs to change in https://asciimoo.github.io/searx/dev/install/installation.html#installation
