### ISSUE TITLE
commande api to create a json

### ISSUE THREAD

**Issue by astrowalker2013** [searx/searx#1153]
Hi 

For a project I want to catch all result of the searchmoteur. 

Is it possible via commande API to do a search and send all search in a json files. 

exemple 
`curl -XGET  "https://searx.com/?q=Trump=general"  `

and i want to retrive all data result in a json files.

Thanks in advence for your answer
Best Regard

**Comment by ghost** [comment]
> Is it possible via commande API to do a search and send all search in a
> json files.

Yes, use `-F` to specify the query and the format:

```
$ curl -F q=Searx -F format=json https://www.lhorn.de/searx/
```

**Comment by astrowalker2013** [comment]
Thanks 
it's OK however the json doesn't contain all result in  my serverer 
the returne json give 
number_of_results | 19309
but the query display are 18 url find
Is it possible to catch all result in one json.

I see that it possible to retrive page by page with
` '-F pageno= `
for the moment my only solution is to do a boocle with the 10 first page and concatenate the json.
is it only solution ?

**Comment by ghost** [comment]
Am 20.01.18 um 23:05 schrieb astrowalker2013:
> but the query display are 18 url find
> Is it possible to catch all result in one json.

I don't know how to do this but

    curl -F q=Searx -F pageno=2 -F format=json https://www.lhorn.de/searx/

will give you the second page.
