### ISSUE TITLE
search in darkweb with Searx

### ISSUE THREAD

**Issue by astrowalker2013** [searx/searx#1155]
Hi 

Is it possible to add in the metasearch a new section to search in darkweb ? I'd like to add amia or other search darkweb search. 

if the metasearch are connected with a tor routeur ?

Best

**Comment by MarcAbonce** [comment]
I've been working on this for a while in #565.
You can currently try out that branch in http://jiwfbtg2kfkadjku.onion
Sometimes Google will block with Captcha and sometimes if the relays are too slow the engines may reach timeout. But it's otherwise usable.

**Comment by astrowalker2013** [comment]
Thanks a lot 
now I have other question to add in my searx instance , tor search ?
i see that in engine /repetory all search instance, but I don't know how to create like the instance http://jiwfbtg2kfkadjku.onion an onion category.
Best

**Comment by MarcAbonce** [comment]
If you are using [my branch](https://github.com/MarcAbonce/searx/tree/onions), you have to uncomment [the proxy lines in the settings.yml file](https://github.com/MarcAbonce/searx/blob/onions/searx/settings.yml#L38). This assumes Tor is currently running in your server and listening to port 9050.

**Comment by unixfox** [comment]
You can look for Searx instances hosted on tor on https://searx.space/
