### ISSUE TITLE
Youtube-api crash with "videoid"

### ISSUE THREAD

**Issue by Carl-Robert** [searx/searx#1157]
Hey!

I'm trying to use the api version with my own api-key, but I get the following errors in the log:
ERROR:searx.search:engine youtube : exception : 'videoid'
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/usr/local/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/usr/local/searx/searx/engines/youtube_api.py", line 54, in response
    videoid = result['id']['videoid']
KeyError: 'videoid'

And the query shows 200 none http error.

So, what I'm doing wrong/what to change in the youtube-api engine?

**Comment by asciimoo** [comment]
Seems the api has changed. Could you print the `result` variable before the above assignment and post the output here?

**Comment by Carl-Robert** [comment]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.googleapis.com
DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /youtube/v3/search?part=snippet&q=test&maxResults=20&key=myapikeyhere&relevanceLanguage=en HTTP/1.1" 200 None
ERROR:searx.search:engine youtube : exception : 'videoid'
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/usr/local/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/usr/local/searx/searx/engines/youtube_api.py", line 54, in response
    videoid = result['id']['videoid']
KeyError: 'videoid'

I'm sorry, but this is all the debug-log shows me. I don't see any further information on it.

Or is there some way to get it to log more?

**Comment by asciimoo** [comment]
> Or is there some way to get it to log more?

Yes, if you add it manually to `youtube_api.py`. Please place a `print(result)` line right above line 54. Then restart your searx and perform a search with this engine.

**Comment by Carl-Robert** [comment]
Alright, this is what it says now:

DEBUG:urllib3.connectionpool:https://www.googleapis.com:443 "GET /youtube/v3/search?part=snippet&q=test&maxResults=20&key=myapikeyhere&relevanceLanguage=en HTTP/1.1" 200 None
{u'snippet': {u'thumbnails': {u'default': {u'url': u'https://i.ytimg.com/vi/_nfREkI7Nsk/default.jpg', u'width': 120, u'height': 90}, u'high': {u'url': u'https://i.ytimg.com/vi/_nfREkI7Nsk/hqdefault.jpg', u'width': 480, u'height': 360}, u'medium': {u'url': u'https://i.ytimg.com/vi/_nfREkI7Nsk/mqdefault.jpg', u'width': 320, u'height': 180}}, u'title': u'MAKE THE HARDEST CHOICE EVER. PERSONALITY VIDEO TEST', u'channelId': u'UCYenDLnIHsoqQ6smwKXQ7Hg', u'publishedAt': u'2017-10-19T18:08:47.000Z', u'liveBroadcastContent': u'none', u'channelTitle': u'#Mind Warehouse', u'description': u"BRAIN TIME\u25bb https://goo.gl/tTWgH2 We're sure you've always wanted to know your true personality, the real one. Not the one that smiles to its colleagues and neighbors. And neither the one..."}, u'kind': u'youtube#searchResult', u'etag': u'"g7k5f8kvn67Bsl8L-Bum53neIr4/_80iqfXYbkSSuBdA1u6m600pjpI"', u'id': {u'kind': u'youtube#video', u'videoId': u'_nfREkI7Nsk'}}
ERROR:searx.search:engine youtube : exception : 'videoid'
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/usr/local/searx/searx/search.py", line 87, in search_one_request
    return engine.response(response)
  File "/usr/local/searx/searx/engines/youtube_api.py", line 55, in response
    videoid = result['id']['videoid']
KeyError: 'videoid'

**Comment by asciimoo** [comment]
As I see your code has been modified. Youtube sends `videoId` and the codebase of searx also contains `result['id']['videoId']` (https://github.com/asciimoo/searx/blob/master/searx/engines/youtube_api.py#L54) but in your code `result['id']['videoid']` is all lower case and that causes the error.

**Comment by Carl-Robert** [comment]
Oh, that's certainly peculiar, since I don't remember modifying it. Anyways, glad it got solved and apologies for wasting time for some typing error.

**Comment by fuzunspm** [comment]
i'm getting the same error with/wo lowercase
