### ISSUE TITLE
additional files to .gitignore for development

### ISSUE THREAD

**Issue by trankmichael** [searx/searx#1160]
Would it be reasonable to add settings.yml and the virtual environment to the .gitignore? Currently going off the docs for development guidlines they are located at `searx-ve/` and `searx/settings.yml`.

**Comment by asciimoo** [comment]
@trankmichael `searx/settings.yml` is part of the repo, so i don't think adding it to the projects gitignore would be a good solution, but I agree on `searx-ve`, it could be included to searx's gitignore.

**Comment by Pofilo** [comment]
`searx/settings.yml` could be replaced by `searx/settings.example.yml` and then we can add `searx/settings.yml` to the `.gitignore`.

The downside is for updating searx according to [the documentation](https://asciimoo.github.io/searx/dev/install/installation.html#how-to-update).

This means it will not be possible to add engines with the current `git stash apply` which merge both files.

**Comment by asciimoo** [comment]
> searx/settings.yml could be replaced by searx/settings.example.yml and then we can add searx/settings.yml to the .gitignore.

This can be done without modifications. Copy `settings.yml` to e.g. `prod_settings.yml` and start searx with `SEARX_SETTINGS_PATH="searx/prod_settings.yml" python searx/webapp.py`.

**Comment by asciimoo** [comment]
added in #1162, thanks @trankmichael.
