### ISSUE TITLE
How to set searx as default search engine on firefox?

### ISSUE THREAD

**Issue by zer09** [searx/searx#1161]
hmmm, sorry for this question, but is there any official add-on for firefox that can make searx as a default search engine?

Thanks.

**Comment by ghost** [comment]
Firefox recognizes searx as a possible search engine. The looking glass icon in the Firefox search box has a small plus icon which allows you to add searx as a search engine. Then navigate to `about:preferences#search` to make searx your default search engine.

**Comment by DeadNumbers** [comment]
Go https://searx.me/about and scroll page down

**Comment by ghost** [comment]
More general: Goto https://the-searx-instance-you-use/about, scroll down, follow the directions in the "How to add to firefox?" section.

**Comment by zer09** [comment]
Ohh thanks.
