### ISSUE TITLE
existing engines is incomplete in the docs

### ISSUE THREAD

**Issue by trankmichael** [searx/searx#1165]
https://github.com/asciimoo/searx/wiki/existing-engines does not have the full list of engines, for example the WolframAlpha and Flickr engines are not listed.

**Comment by kvch** [comment]
Yes, indeed. Unfortunately, it's not maintained. If you feel like it, you can update it. :)

**Comment by unixfox** [comment]
It should be complete: https://searx.github.io/searx/admin/engines.html
