### ISSUE TITLE
Forum or Mailing list?

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1167]
Greetings All,

I am wondering if there is a SearX forum or mailing list?

Cheers,
Lonnie

**Comment by kvch** [comment]
GitHub is the main platform for development and reporting bugs. If you have any feedback for the project, you should open an issue.
There is a mailing list for instance admins: searx-instances@autistici.org

**Comment by kvch** [comment]
I meant  that this platforms is intended for the development of searx including sharing ideas.
The mailing list is for admins who run searx instances. The list is not for development details, but for operational topics.

**Comment by Outstep** [comment]
I see.

So then who might I be able to ask about the DB usage within SearX?

I am trying to find out if it clears its internal DB before each query or does it cache the query results from the external search engines and try to use them again if a query calls for some of these results?

I'm not trying to change SearX at the moment, but am just trying to find out how the database is used and if queries are cached for later re-use. The documentation is not clear on this question.

Thanks again,
Lonnie
