### ISSUE TITLE
help setting up filtron with apache

### ISSUE THREAD

**Issue by r1bnc** [searx/searx#1169]
I have configured morty but I have problems with filtron. I have a searx instance on a subdirectory install and I use apache, the docs are using nginx. So how do I set up  filtron. Here are my configurations:
I have a site on a custom port and installed searx to 
https://mysite:port/searx
My apache config file for that port is this: the relevant parts only
```
..
# i access searx to https://mysite:port/searx/
.
.
#filtron on a searx with subdirectory install not working?
ProxyPass "/searx/" "http://127.0.0.1:4004/"
.
.
.
# morty start
ProxyPass "/searx/morty/" "http://127.0.0.1:3000/"
ProxyPassReverse "/searx/morty/" "http://127.0.0.1:3000/"
# morty end
.
.
.
#searx start
<Location /searx>
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>
.
.
.
#morty is working but filtron does not
```
edited _uwsgi.ini_ and added _http = 127.0.0.1:8888_
The filtron rules.json is based on the wiki example.  https://asciimoo.github.io/searx/admin/filtron.html

I need help in the proxypass in apache settings since the wiki is using nginx

**Comment by asciimoo** [comment]
Remove the following section:
```
#searx start
<Location /searx>
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>
```

It overwrites `ProxyPass "/searx/" "http://127.0.0.1:4004/"`. Also, you can test filtron on the local machine with `curl http://127.0.0.1:4004/`. If it returns correct response, then the error is in the webserver config, otherwise filtron/searx isn't configured properly.

**Comment by r1bnc** [comment]
I've removed this
```
#searx start
<Location /searx>
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>
```
and only added `ProxyPass "/searx" "http://127.0.0.1:4004/"`
but the User interface of searx now has missing assets it is like a html only no images and  whenever I input at the search box it just redirect to my root url: http://mysite:port/ not going through http://mysite:port/srx

I can access from the localhost that searx is running the curl 127.0.0.1:4004 I will try to change my searx port to somewhere other than the subdirectory install later.

UPDATE: So I changed/added another port for searx in another apache2 sites file and it worked (I can access the searx filtron protected using another port in my server https://mysite:anotherport). Is there any configuration that will allow to run fitron on subdirectory install of searx (eg. https://mysite:port/searx/ and not on https://mysite:port)
