### ISSUE TITLE
Non-standard port number missing in /opensearch.xml

### ISSUE THREAD

**Issue by GitHubGeek** [searx/searx#1173]
Hello,

Thank you for building this great service. I'm amazed at how fast search results are generated. Well done!

Found a small issue with `/opensearch.xml`. I'm running from docker and using nginx to proxy HTTPS to port 8888 from a non-standard port (1443). In `/opensearch.xml` the port is missing in both `template` attribute and the `<Image>` tag:

```xml
<?xml version="1.0" encoding="utf-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>searx</ShortName>
  <Description>a privacy-respecting, hackable metasearch engine</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image>https://foobar.example.com/static/themes/oscar/img/favicon.png</Image>
  <LongName>searx metasearch</LongName>
    <Url type="text/html" method="post" template="https://foobar.example.com">
        <Param name="q" value="{searchTerms}" />
    </Url>
</OpenSearchDescription>
```

Should be `<Image>https://foobar.example.com:1443/static/themes/oscar/img/favicon.png</Image>` and `template="https://foobar.example.com:1443/"` (with trailing slash as well)

**Comment by asciimoo** [comment]
@GitHubGeek set your custom url (e.g. `https://foobar.example.com:1443/`) as `base_url` in `settings.yml`: https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L14.
