### ISSUE TITLE
Adding searx as an browser address bar search engine?

### ISSUE THREAD

**Issue by paul1149** [searx/searx#1174]
I use vivaldi and slimjet, both are chromium derivatives. It looks like searx uses POST for its searches, and I don't see a way to get a search url string from that. Is there any way to do it?

Thanks.

**Comment by Nickfost** [comment]
![screenshot_1](https://user-images.githubusercontent.com/1572453/35787842-c30869cc-09f6-11e8-9526-54d3c320a4d5.png)

**Comment by paul1149** [comment]
Beautiful. Thanks!
