### ISSUE TITLE
Error when trying to add an private searx instance

### ISSUE THREAD

**Issue by sven-hash** [searx/searx#1175]
When I'm trying to add an search engine with Firefox 58.0.1 (64-bit). I've this error: ``Firefox could not install the search engine from: https://searx.rouvinez.me/opensearch.xml`` and if I'm going to https://searx.rouvinez.me/opensearch.xml I've this: 
```
XML Parsing Error: not well-formed
Location: https://searx.rouvinez.me/opensearch.xml
Line Number 1, Column 1:
```

Thanks fow what you're doing!

**Comment by asciimoo** [comment]
I guess searx is behind a webserver which automatically compresses `opensearch.xml` - probably because of the `.xml` ending.
The solution should be the same as in #532 .
