### ISSUE TITLE
Make the results page clearer, easier to read

### ISSUE THREAD

**Issue by xan2622** [searx/searx#1176]
Hello

I think that the results page could be easier to read with space between results.
Adding a 15 px margin-bottom bellow the .external-link would make the page less confusing.

> .external-link {  margin-bottom: 15px; }

Currently:

![capture](https://user-images.githubusercontent.com/1732773/35845430-b47ddce4-0b12-11e8-832e-e156dbfc0d39.PNG)

With a 15px margin-bottom:

![capture2](https://user-images.githubusercontent.com/1732773/35845431-b4a007a6-0b12-11e8-929b-03261eca5734.PNG)

**Comment by asciimoo** [comment]
As I see from the number of up votes, this is a desired mod, so I'm going to implement it soon. Thanks for the contribution and for all the feedback.
