### ISSUE TITLE
[ENHANCEMENT] no way yet to temporarily activate a search engine

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [searx/searx#1177]
Hi,

Let me explain, say I have activated 6/10 engines, but not activated Faroo for example.

*If I type `test` I will have results from the 6/10 engines and no Faroo.
*If I type `!fa test` I will only have Faroo results and not one from the 9/10.

So there is no way to search using (6+Faroo)/10, or to put it in other words : there is no way to aggregate results from 1 (or more) more engines in addition to the default engines for just one search.

In my opinion `+!fa test` should show results from the 6 activated engines + faroo. That seems quite intuitive too.

I'll let you decide what you think of that :) good day to you !

**Comment by asciimoo** [comment]
@thiswillbeyourgithub it can be achieved using the `?` operator (e.g. `?fa test`). You can find the search syntax documentation here: https://asciimoo.github.io/searx/user/search_syntax.html
