### ISSUE TITLE
Adding an Youtube-Api-Key leads to an internal server

### ISSUE THREAD

**Issue by scroom** [searx/searx#1182]
Hallo,

yesterday I've set up an instance of searx. Today I wanted to add an API-Key for Youtube. So I requested one and changed the settings.yml. But when I'm restarting the uwsgi.service I get an internal server error.

**Comment by Pofilo** [comment]
If you remove the API-Key and restart the service, the server is running well again ?
(to be sure this is the cause of the bug)

**Comment by scroom** [comment]
Yes, if I switch back to noapi, everything is running well again.

**Comment by scroom** [comment]
Maybe I've added the wrong API-Key? I've added an Youtube APIv3 Key. Is it the right one?

**Comment by kvch** [comment]
I tested the engine YouTube Data API v3. I enabled the API and requested an API key. Then configured it as the following:

```yaml
  - name : youtube
    shortcut : yt
    api_key: {{my-key}}
    engine : youtube_api
```

I could not reproduce the issue you had seen. Please reopen the issue, if the problem is still occurs.
