### ISSUE TITLE
[Feature Request] Add a link to the startpage "Add searx.tld to the browser"

### ISSUE THREAD

**Issue by scroom** [searx/searx#1185]
As described above. It seems to be quite hard to add the searx instance as search engine to the browser. Therefor it would be great if there would be a link, with which one could add the instance as search engine to the browser.

On startpage.com they are using such a link.

**Comment by Pofilo** [comment]
In the `/about` page, in the FAQ, there is a link to install in Firefox.
For example here: [https://searx.me/about](https://searx.me/about)

We can maybe add a link for "most used" browsers.

**Comment by scroom** [comment]
This link isn't working for me on my instance. I will file a new bug report for this issue.

**Comment by allendema** [comment]
This issue is already fixed on newer relases.
Can this issue be closed?
