### ISSUE TITLE
Category tabs issue: hints don't see category tabs [qutebrowser]

### ISSUE THREAD

**Issue by voidervoid** [searx/searx#1187]
Tabs for switching between categories and all tabs of this type are not supported by qutebrowser (and probably here is same thing for other keyboard-driven browsers) - hints don't see them. 
_[Because, i think, they are something like inside-content reference than just a common url link. I actually don't know any of programming languages, so that just my assumption]_
If you know a solution, please make changes about those tabs and don't use constructions like this in the future. Keyboard-driven community would be thankful for you. With respect.

**Comment by unixfox** [comment]
A lot of time and changes in the code base have passed since the creation of this issue, unfortunately with our low number of active developers we cannot test every single browser existing on the planet.

I'm closing this issue in hope that it got fixed for your browser but if not feel free to reopen this issue.

**Comment by bencollerson** [comment]
I have a patch that fixes the link hinting issue for me. If I could get some feedback from other people affected by this issue on my patch that would be great.

https://github.com/bencollerson/searx/commit/e69187b61e8fb4ee52e48cea0fec4ab3b6090704

**Comment by bencollerson** [comment]
I tried to clean up my patch a bit. It now also works on all the themes. I am not a front-end dev but I got it to look kind-of okay. Not sure what the policy is on pull requests, so not making one unless my patch looks acceptable to someone else.
