### ISSUE TITLE
About page is not translated

### ISSUE THREAD

**Issue by scroom** [searx/searx#1188]
As decribed above. I think for the user it would be better if the about page would be translated to the users language as other parts of searx. 

I would like to help translating the about page, if this possibility would become real.

**Comment by dalf** [comment]
Technical detail: 
the English version is here :
https://github.com/asciimoo/searx/blob/master/searx/templates/__common__/about.html

Is Transiflex still a good solution for a long text?
Would it be better to use Markdown and then convert it to HTML?

**Comment by scroom** [comment]
@dalf Haven't worked with Transiflex before but will give it a try.

**Comment by scroom** [comment]
@dalf Do I really have to install the client as described here: https://www.transifex.com/asciimoo/searx/

Or is it possible to translate in the browser?

**Comment by kvch** [comment]
Translation can be done from your browser. However, I don't think the text is translatable now.

**Comment by scroom** [comment]
@kvch OK, I've already entered the german translation team. If the about page will become translatable I would like to help.

**Comment by erdmark** [comment]
I translated the about page yesterday so it is no final version, you can see it here: https://suche.ftp.sh/about

**Comment by scroom** [comment]
@erdmark That's great!
@dalf Will the about page as a whole become translatable so that it can be translated into many other languages and displayed in the respective user language?

**Comment by allendema** [comment]
Already translated.
Can this issue be closed?
