### ISSUE TITLE
Project offer for Filipino translation

### ISSUE THREAD

**Issue by vinzruzell** [searx/searx#1191]
HI. I would like to apply for a Filipino or cebuano translation project. Thank you.

**Comment by scroom** [comment]
@vinzruzell If I understand correctly, the translation of searx is done on Transiflex:

https://www.transifex.com/asciimoo/searx/

**Comment by kvch** [comment]
I have added Filipino to the language list. You can start translating here: https://www.transifex.com/asciimoo/searx/language/fil/
Thanks for translating searx.

**Comment by r1bnc** [comment]
Filipino has 8 major dialects:  Bikol, Cebuano, Hiligaynon (Ilonggo), Ilocano, Kapampangan, Pangasinan, **Tagalog**, and Waray 
please specify which dialect in the transifex. Tagalog is widely being taught and english.

**Comment by vinzruzell** [comment]
Hi. I want the Tagalog Translation ot cebuano.

**Comment by r1bnc** [comment]
@kvch please add cebuano to the translation (transifex), and change filipino (transifex) to tagalog

**Comment by kvch** [comment]
Cebuano is not supported by Transifex. Or at least I haven't been able to add it to the languages.
Tagalog is available: https://www.transifex.com/asciimoo/searx/language/tl/
Is it enough?

**Comment by r1bnc** [comment]
@vinzruzell  Tagalog is available here: https://www.transifex.com/asciimoo/searx/language/tl/
Filipino is also available: https://www.transifex.com/asciimoo/searx/language/fil/
You can login to transifex using your github account

**Comment by kvch** [comment]
Filipino is added as is from Transifex in the new release.
