### ISSUE TITLE
[UI][REQUEST]Add Basic UI and text browser friendly

### ISSUE THREAD

**Issue by r1bnc** [searx/searx#1193]
I browse searx using Links2, Elinks and Lynx but I find it difficult to search. Searx should have an offer to search as basic html like what duckduckgo does. This is only a feature request.

**Comment by asciimoo** [comment]
Oscar and legacy themes are usable with lynx/w3m. What are your exact issues?

**Comment by r1bnc** [comment]
No problems, closing the issue now.
