### ISSUE TITLE
CAPTCHA required message?

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1195]
Hello,

What is this message really mean?

--------------------------------

Engines cannot retrieve results:

google (unexpected crash: CAPTCHA required)
-----------------------------------

**Comment by kvch** [comment]
It means that Google refuses to send results until you resolve the CAPTCHA it sends you.
Sometimes it disappeares without any action.

**Comment by Outstep** [comment]
I see.   Now I seem to be getting results coming in.  I never was able to answer the CAPTCHA as it was the message from SearX (master latest build, v0.13.1 is what I think is the latest) when it could not get results from Google recently.

Thanks for the information.

**Comment by Outstep** [comment]
solved.

**Comment by Pofilo** [comment]
When you mean solved, you mean how ?

Did you find a solution to the captcha problem which leads in the google engine working well ? Did you disable the google engine ?

**Comment by Outstep** [comment]
Hello,

Not sure completely on the solution, but I upgraded to the latest SearX 0.14 and it stopped showing.

It may reappear as I think that it is on the Google side and if so then I will look for a better solution for which I will post.

Cheers and have a good day.
