### ISSUE TITLE
Adding more search engines?

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1196]
Hello,

I would like to add more search engines like.

One is similar to Gigablast, and some others might be Dogpile and Metacrawler, plus some others.

I know that I have to a new driver in:

searx/searx/engines/

searx/searx/settings.yml

but where else in SearX do I need to make changes?

Also, in the settings.yml there are engine designations like:

  - name : gigablast
    engine : gigablast
    shortcut : gb
    timeout : 3.0
    disabled: True

How is the "shortcut" designation determined and used?

Any help would be greatly appreciated.
Thanks

**Comment by kvch** [comment]
If you are adding only a search engine, you need to edit files under engines and add it in `settings.yml`.
There is no need to edit anything else.

Shortcuts can be whatever letters you come up with. The only requirement is it has to be unique. It is advised to be short and easy to remember.

Is there anything I can help you with?

**Comment by Outstep** [comment]
Thanks for responding to my inquiry.

Currently, I am looking to install the first engine and if all goes well, I want to try and add more. I am coming more from a C/C++ background than Python which I do not know too well, but am going to try to add this one. 

On, a second note, I am also needing to learn more about the SearX plugin system as I seem to understand that it has hooks for before and after the call with the results list. I want to be able to do an action after the query with the results collected and send them to another program as well as back to the user.

I might like to ask for you help if I get stuck on some of this.
Thanks again.

**Comment by kvch** [comment]
There is laconic documentation on plugins: https://asciimoo.github.io/searx/dev/plugins.html

**Comment by Outstep** [comment]
I have partially figured this out and am working on adding more engines.
