### ISSUE TITLE
Template language and variables for new theme?

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1197]
Hello,

Is there any documentation on the Template language or variables list?

I want to do some work on a new theme, more to be like the Google and Bing theme but would like to get a list of all of the available variables in the Template language.

I'm not really a web developer, but would like to see about trying to cobble together a theme like theirs if possible.

Any web developers around here that know how to do this?

Cheers and have a great day,

**Comment by kvch** [comment]
The templating language used by searx is Jinja2. It dumping its variables doesn't seem straightforward.

You could try adding `print(kwargs)` to this line: https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L390
It would print all variables passed to render a page.

**Comment by Outstep** [comment]
Will look that up, thanks
