### ISSUE TITLE
ddgr like script for searx

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#1198]
https://github.com/jarun/ddgr is a python3 based script for quering duckduckgo from the terminal. Such a script would be nice for searx too (with options for selecting the searx server of course)

**Comment by dalf** [comment]
There is https://github.com/asciimoo/searx/blob/master/utils/standalone_searx.py
which could be improved.

**Comment by unixfox** [comment]
Duplicate of https://github.com/searx/searx/issues/915
