### ISSUE TITLE
Changing default search

### ISSUE THREAD

**Issue by ghost** [searx/searx#1202]
Hello,

Due to the current google captcha problem I would like to change my default search.
I was wondering how I can add "StartPage" and "DuckDuckGo" to my default search and temporarily remove "Google" from it, until the problem got fixed? At the moment I have just "bing" which isn't the best...

Thanks for your help!

**Comment by Pofilo** [comment]
`yourinstanceofsearx.com/preferences`

Then go to the engines and configure them.
