### ISSUE TITLE
searX is not starting correctly

### ISSUE THREAD

**Issue by ghost** [searx/searx#1204]
Hello,

I am having the problem that my searX is mostly not starting correct. After a fresh installation it works but once I restart it with `sudo service uwsgi restart` it istn't coming up again.
I think there is something wrong with my uwsgi. Besides that I am using it with Apache.
Attached I will share with you my log, which might help:

> Tue Feb 20 10:49:54 2018 - SIGINT/SIGQUIT received...killing workers...
> Tue Feb 20 10:49:55 2018 - worker 1 buried after 1 seconds
> Tue Feb 20 10:49:55 2018 - worker 2 buried after 1 seconds
> Tue Feb 20 10:49:55 2018 - worker 3 buried after 1 seconds
> Tue Feb 20 10:49:55 2018 - goodbye to uWSGI.
> Tue Feb 20 10:49:56 2018 - *** Starting uWSGI 2.0.12-debian (64bit) on [Tue Feb 20 10:49:56 2018] ***
> Tue Feb 20 10:49:56 2018 - compiled with version: 5.4.0 20160609 on 31 August 2017 21:02:04
> Tue Feb 20 10:49:56 2018 - os: Linux-4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018
> Tue Feb 20 10:49:56 2018 - nodename: searX
> Tue Feb 20 10:49:56 2018 - machine: x86_64
> Tue Feb 20 10:49:56 2018 - clock source: unix
> Tue Feb 20 10:49:56 2018 - pcre jit disabled
> Tue Feb 20 10:49:56 2018 - detected number of CPU cores: 4
> Tue Feb 20 10:49:56 2018 - current working directory: /
> Tue Feb 20 10:49:56 2018 - writing pidfile to /run/uwsgi/app/searx/pid
> Tue Feb 20 10:49:56 2018 - detected binary path: /usr/bin/uwsgi-core
> Tue Feb 20 10:49:56 2018 - setgid() to 1001
> Tue Feb 20 10:49:56 2018 - setuid() to 1001
> Tue Feb 20 10:49:56 2018 - chdir() to /var/www/searx/searx/
> Tue Feb 20 10:49:56 2018 - your processes number limit is 47922
> Tue Feb 20 10:49:56 2018 - your memory page size is 4096 bytes
> Tue Feb 20 10:49:56 2018 - detected max file descriptor number: 1024
> Tue Feb 20 10:49:56 2018 - lock engine: pthread robust mutexes
> Tue Feb 20 10:49:56 2018 - thunder lock: disabled (you can enable it with --thunder-lock)
> Tue Feb 20 10:49:56 2018 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/searx/socket fd 3
> Tue Feb 20 10:49:56 2018 - Python version: 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
> Tue Feb 20 10:49:56 2018 - Set PythonHome to /var/www/searx/searx-ve/
> Tue Feb 20 10:49:56 2018 - *** Python threads support is disabled. You can enable it with --enable-threads ***
> Tue Feb 20 10:49:56 2018 - Python main interpreter initialized at 0x10ac460
> Tue Feb 20 10:49:56 2018 - your server socket listen backlog is limited to 100 connections
> Tue Feb 20 10:49:56 2018 - your mercy for graceful operations on workers is 60 seconds
> Tue Feb 20 10:49:56 2018 - mapped 291072 bytes (284 KB) for 3 cores
> Tue Feb 20 10:49:56 2018 - *** Operational MODE: preforking ***
> Tue Feb 20 10:49:56 2018 - added /var/www/searx/ to pythonpath.
> Tue Feb 20 10:49:56 2018 - WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x10ac460 pid: 4144 (default app)
> Tue Feb 20 10:49:56 2018 - spawned uWSGI master process (pid: 4144)
> Tue Feb 20 10:49:56 2018 - spawned uWSGI worker 1 (pid: 4155, cores: 1)
> Tue Feb 20 10:49:56 2018 - spawned uWSGI worker 2 (pid: 4156, cores: 1)
> Tue Feb 20 10:49:56 2018 - spawned uWSGI worker 3 (pid: 4157, cores: 1)

**Comment by asciimoo** [comment]
The above log doesn't contain errors as I see. Try to restart/reload apache too after the uwsgi restart. Maybe the error is between apache and uwsgi.

**Comment by ghost** [comment]
Great, good to know. Thank you @asciimoo! 

I would have another question. Is it somehow possible to change the style of theme in the settings.yml?

**Comment by asciimoo** [comment]
https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L21

**Comment by ghost** [comment]
Isn't that just the Theme? I wanted to change the style as well. In my case I would like to use oscar and style pointhi. Am I able to adjust that in that line as well?

**Comment by asciimoo** [comment]
You have to change the following line if you want to change the default style of the oscar theme: https://github.com/asciimoo/searx/blob/master/searx/templates/oscar/base.html#L19 . E.g. replace `logicodev.min.css` with `logicodev-dark.min.css`.

**Comment by ghost** [comment]
That worked, thanks a lot @asciimoo!
