### ISSUE TITLE
Search language to Automatic/Default language 

### ISSUE THREAD

**Issue by ghost** [searx/searx#1205]
Hello,

On a couple of searx instances I saw the default setting for Search language be: Default language / Automatic. In my case its in English. Anybody knows how I can change that so that the engine changes the results depending on the GEO location?

Thanks!

**Comment by gruessung** [comment]
+1

**Comment by aurora-anon** [comment]
+1

**Comment by aurora-anon** [comment]
similar to <a href="https://github.com/asciimoo/searx/issues/1256">issue 1256</a>

**Comment by ghost** [comment]
+1

**Comment by phlinhng** [comment]
Has this be implemented yet? I've tried to set `default_lang : "all" ` but it seemed didn't work.

**Comment by return42** [comment]
Already implemented.
