### ISSUE TITLE
manage.sh is actually bash script

### ISSUE THREAD

**Issue by josch** [searx/searx#1206]
The shebang line of `manage.sh` suggests that the content of the file is a POSIX compliant shell script. Unfortunately, the script contains several bashisms:

 - line 8: `$_` is bash-only and not POSIX
 - line 59: echo is used with a backslash (not portable)

The echo problem is easy to fix by just using printf instead. But according to the stackoverflow link at the top of `manage.sh` there seems to be no POSIX compliant way to detect whether a script is being sourced. This I guess, that unless these lines are removed from the script, the only fix is to make this script bash-only.

**Comment by josch** [comment]
I also don't think that the check is correct. The script currently uses:

    if [ $_ != $0 ]; then

but this is problematic when the script is called with `bash ./manage.sh`. The proper way to do this (also described in that stackoverflow post) is to do:

    if [[ $0 != "$BASH_SOURCE" ]]; then

Is there really enough utility in this functionality for such a fragile solution?

**Comment by dalf** [comment]
related to https://github.com/asciimoo/searx/pull/1127
Let's remove the sourced feature.

**Comment by kvch** [comment]
#1127 is merged, the issues should be fixed on master
