### ISSUE TITLE
Please update requirements.txt

### ISSUE THREAD

**Issue by yurivict** [searx/searx#1207]
For example, pygments is missing.
And selenium is listed but is not used.

----

Please also avoid using ```==``` in requirements list, because it makes it very difficult to install as a package. Please use ```>=``` instead, expect dependencies be backwards-compatible.

**Comment by asciimoo** [comment]
> For example, pygments is missing.

it is in the requirements file: https://github.com/asciimoo/searx/blob/master/requirements.txt#L6

>  And selenium is listed but is not used.

It's only a development dependency: https://github.com/asciimoo/searx/blob/master/requirements-dev.txt#L11

> Please also avoid using == in requirements list, because it makes it very difficult to install as a package. Please use >= instead, expect dependencies be backwards-compatible.

Use virtualenv: https://asciimoo.github.io/searx/dev/install/installation.html#basic-installation
