### ISSUE TITLE
Timeouts with version 0.14.0

### ISSUE THREAD

**Issue by josch** [searx/searx#1210]
Hi,

with version 0.14.0 I consistently get timeouts from every search provider:

    WARNING:searx.search:engine timeout: wikipedia
    WARNING:searx.search:engine timeout: wikidata
    WARNING:searx.search:engine timeout: google
    WARNING:searx.search:engine timeout: bing
    WARNING:searx.search:engine timeout: piratebay
    WARNING:searx.search:engine timeout: torrentz

when I downgrade to 0.13.1 then everything works again. I am not changing my `settings.yml` between version changes and I don't change anything else about my server configuration. So the problem must come somewhere from the searx codebase. Also notable is, that when I try it locally, then I do not see any timeouts. The timeouts also happen when I set `request_timeout` to 20 seconds.

I don't see anything that changed in the code between 0.13.1 and 0.14.0 that could explain my observations, so as a next step I will bisect the git commits between these two versions to find the culprit. I just wanted to post this here already to maybe find others experiencing similar issues and for hints of how to better debug this issue.

Thanks!

cheers, josch

**Comment by josch** [comment]
I'm a bit further. The timeouts did not happen on my local machine because there I used searx-run. Only when using nginx and uwsgi does the timeout problem occur with version 0.14.0.

**Comment by josch** [comment]
Okay, I successfully bisected the commit range between 0.13.1 (good) and 0.14.0 (bad) and it seems that the commit that introduces this regression with uwsgi is 2f69eaeb2fb76a14d9c3f2a67a9e404b066049ba

**Comment by josch** [comment]
I can also confirm that reverting commit 2f69eaeb2fb76a14d9c3f2a67a9e404b066049ba on top of 0.14.0 fixes the regression. So the culprit is indeed this commit.

**Comment by asciimoo** [comment]
This is interesting.. I cannot reproduce it. What is your uwsgi version/config? Do you have uwsgi logs?

**Comment by josch** [comment]
I created fresh containers of Debian Stretch (stable) and Debian Buster (testing) and was able to reproduce my observations. It's important to note, that while the Debian packages exhibit the same issue, I am *not* using the Debian packages but a git clone to make sure that this is no packaging issue.

Which operating system are you using?

I see several ways for you to reproduce this. Either you follow the steps that I took, which would be:

```
$ sudo debootstrap stretch debian-stretch
$ sudo chroot debian-stretch
```

and then inside the chroot:

```
$ apt install nginx uwsgi uwsgi-plugin-python3 git
$ cd /var/www
$ git clone https://github.com/asciimoo/searx.git
$ chown -R www-data:www-data searx
```

Or, I can also share a tarball of the resulting chroot environment with you.

One way to test the result is using `systemd-nspawn`:

    sudo systemd-nspawn -bD ~/debian-stretch

If you want to setup the container manually, I attached the relevant config files for searx, nginx and uwsgi.

[searx settings.yml](https://github.com/asciimoo/searx/files/1751513/settings.txt)
[uwsgi.ini](https://github.com/asciimoo/searx/files/1751516/uwsgi.txt)
[nginx config](https://github.com/asciimoo/searx/files/1751519/nginx.txt)

The issue remains the same:

 - the front page loads fine
 - search queries create timeouts for all search providers
 - reverting commit 2f69eae magically fixes the problem
 - searx-run is unaffected and works either way

So maybe this is an uwsgi problem but I tried versions 2.0.14 (from Debian Stretch) as well as 2.0.15 (from Debian Buster).

**Comment by asciimoo** [comment]
Try to add `enable-threads = true` to your uwsgi config.

**Comment by josch** [comment]
If I do that, then not even the front page loads. Here is the relevant part from my uwsgi log after starting it with `enable-threads = true` and trying to access the front page:

```
Fri Feb 23 21:21:37 2018 - *** Starting uWSGI 2.0.15-debian (64bit) on [Fri Feb 23 21:21:37 2018] ***
Fri Feb 23 21:21:37 2018 - compiled with version: 7.3.0 on 10 February 2018 00:06:24
Fri Feb 23 21:21:37 2018 - os: Linux-4.13.0-1-amd64 #1 SMP Debian 4.13.4-2 (2017-10-15)
Fri Feb 23 21:21:37 2018 - nodename: hoothoot
Fri Feb 23 21:21:37 2018 - machine: x86_64
Fri Feb 23 21:21:37 2018 - clock source: unix
Fri Feb 23 21:21:37 2018 - pcre jit disabled
Fri Feb 23 21:21:37 2018 - detected number of CPU cores: 4
Fri Feb 23 21:21:37 2018 - current working directory: /
Fri Feb 23 21:21:37 2018 - writing pidfile to /run/uwsgi/app/searx/pid
Fri Feb 23 21:21:37 2018 - detected binary path: /usr/bin/uwsgi-core
Fri Feb 23 21:21:37 2018 - dropping root privileges as early as possible
Fri Feb 23 21:21:37 2018 - setgid() to 33
Fri Feb 23 21:21:37 2018 - setuid() to 33
Fri Feb 23 21:21:37 2018 - chdir() to /var/www/searx
Fri Feb 23 21:21:37 2018 - your processes number limit is 46775
Fri Feb 23 21:21:37 2018 - your memory page size is 4096 bytes
Fri Feb 23 21:21:37 2018 - detected max file descriptor number: 1024
Fri Feb 23 21:21:37 2018 - lock engine: pthread robust mutexes
Fri Feb 23 21:21:37 2018 - thunder lock: disabled (you can enable it with --thunder-lock)
Fri Feb 23 21:21:37 2018 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/searx/socket fd 3
Fri Feb 23 21:21:37 2018 - dropping root privileges after socket binding
Fri Feb 23 21:21:37 2018 - Python version: 3.6.4+ (default, Feb 12 2018, 08:25:03)  [GCC 7.3.0]
Fri Feb 23 21:21:37 2018 - Python main interpreter initialized at 0x55aa9aeb6050
Fri Feb 23 21:21:37 2018 - dropping root privileges after plugin initialization
Fri Feb 23 21:21:37 2018 - python threads support enabled
Fri Feb 23 21:21:37 2018 - your server socket listen backlog is limited to 100 connections
Fri Feb 23 21:21:37 2018 - your mercy for graceful operations on workers is 60 seconds
Fri Feb 23 21:21:37 2018 - mapped 145536 bytes (142 KB) for 1 cores
Fri Feb 23 21:21:37 2018 - *** Operational MODE: single process ***
Fri Feb 23 21:21:37 2018 - added /var/www/searx/ to pythonpath.
Fri Feb 23 21:21:38 2018 - WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55aa9aeb6050 pid: 140 (default app)
Fri Feb 23 21:21:38 2018 - dropping root privileges after application loading
Fri Feb 23 21:21:38 2018 - spawned uWSGI master process (pid: 140)
Fri Feb 23 21:21:38 2018 - spawned uWSGI worker 1 (pid: 153, cores: 1)
```

**Comment by josch** [comment]
Got it!

So, this was a uwsgi problem after all. But the necessary option was not `enable-threads = true` but `lazy-apps = true`. After inserting the latter searx works fine again. Even with `enable-threads = false`.

**Comment by josch** [comment]
If searx requires the `lazy-apps = true` option when used with uwsgi, maybe it could document that somewhere? Maybe in form of an example uwsgi ini file?

**Comment by asciimoo** [comment]
It is mentioned in the setup guide: https://asciimoo.github.io/searx/dev/install/installation.html#uwsgi .

**Comment by josch** [comment]
Funny, I thought I had copied that when I included the uwsgi config. Seems I missed that.

**Comment by josch** [comment]
Are the sources of those docs hosted somewhere? Then I could check whether any of these instructions change over time and adapt the Debian package accordingly.
