### ISSUE TITLE
Problems with openstreetmap-search engine

### ISSUE THREAD

**Issue by scroom** [searx/searx#1220]
Just updated to the new version 14.0 (btw I had to reinstall because I had problems to update) and realized that there are problems with the openstreetmap engine. If I'm searching something in the Map-Tab I get the following error shown:

```
Die folgenden Suchmaschinen können die Ergebnisse nicht empfangen:

openstreetmap (unexpected crash: 'osm_id')
```

**Comment by asciimoo** [comment]
@scroom it works for me on searx.me . Which instance do you use and what is your search query?

**Comment by kvch** [comment]
What problems did you face during update?
