### ISSUE TITLE
Interesting Error

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1224]
Hello All,

I am running the 0.14 version and have come across this error:

--------------------
```
~/searx/builds/searx-0.14-20180302a$ python searx/webapp.py 
ERROR:searx.webapp:search error
Traceback (most recent call last):
  File "searx/webapp.py", line 492, in index
    result_container = search.search()
  File "/home/lonnie/searx/builds/searx-0.14-20180302a/searx/search.py", line 432, in search
    plugins.call(self.ordered_plugin_list, 'on_result', self.request, self, result)
  File "/home/lonnie/searx/builds/searx-0.14-20180302a/searx/plugins/__init__.py", line 74, in call
    ret = getattr(plugin, plugin_type)(request, *args, **kwargs)
  File "/home/lonnie/searx/builds/searx-0.14-20180302a/searx/plugins/outstep_sender.py", line 86, in on_result
    response = requests.get(sendurl, params='')
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
----------------------------------------

Exception happened during processing of request from ('127.0.0.1', 60404)
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```
-------------------

I'm not sure what it means or how to fix it.

Any ideas?

**Comment by Outstep** [comment]
Also, I do not know why when I post to the SearX issues that it bolds and makes larger my information as this is not meant to yell or anything. I just do not know why it does that as I do not put in any special characters.

Sorry if it offends and I'll try to find a better way to post the information.

**Comment by dalf** [comment]
The error is related to /home/lonnie/searx/builds/searx-0.14-20180302a/searx/plugins/outstep_sender.py

There is no outstep_sender.py in the[ searx source code](https://github.com/asciimoo/searx/tree/master/searx/plugins).
* If possible (license and all), can you post the content of this file? 
* Where and how did you downloaded searx ?

**Comment by Outstep** [comment]
Hi,

I may have narrowed down the problem a bit.  Actually the outstep_sender.py is a small plugin that I have been trying to develop for SearX that would use the "on_results" function.

What I wanted to do was to send each external URL that was collected out to another program via a small API call, but I think that the error is showing up because the the outstep_sender.ph is slowing down the system. I had noticed significant timeouts when trying to run it with the plugin

**Comment by dalf** [comment]
Yes, there is a global timeout on each request: if a plugin is slow, there will be more timeout or no result at all.

The solution is my opinion is to process the results asynchronously : 
- either with a dedicated thread, and [Queue](https://docs.python.org/2/library/queue.html). 
- either using [Celery](http://www.celeryproject.org/)

Be careful, in production there will be more than one thread processing the searx requests (see uwsgi configuration).

**Comment by Outstep** [comment]
You know, I was just thinking about something.

Maybe the "on_result" function is not the proper place to be doing this
function since I would guess that once the results have been aggregated
then there is a "list", which is normally send back to the user and
displayed. I am wondering if perhaps that list could be sent to a thread in
the "post_search" hook. Then the thread could send out the URL's via the
API call as it process the inbound queue of URL's.

This might be more skill with SearX and Python than I can do an may have to
try and find someone that might be able to help or get a developer for it.
Still trying to figure out the best and quickest way to move forward but I
thank you again.

**Comment by asciimoo** [comment]
@lonnieOST here's an example plugin which saves results asynchronously:

```python
import threading

name = 'Save results'
description = 'Save results'
default_on = True


def save_results(results):
    # TBD..
    print(results)


def post_search(request, search):
    results = search.result_container.get_ordered_results()
    threading.Thread(target=save_results, args=(results,)).start()
    return True
```

**Comment by asciimoo** [comment]
@dalf I'm not sure if this is really a bug in our plugin architecture. Plugin handling now blocks the execution which makes the plugins able to change variables which affect the search. And, the current behavior allows a plugin to be async as the above example shows.

**Comment by Outstep** [comment]
Thanks again for all of the help and I will try to use the above code to
re-write my plugin to see if it will perform better.

Great project!!!

**Comment by dalf** [comment]
@asciimoo right now, all plugins adds new features.

Add UX/UI using javascript / css :
* vim
* infinite scroll
* search on category select
* open results in new tab (actually dead code?) 

Modify URL :
* OA DOI rewrite
* Tracker remover
* HTTPS rewrite

The call in search.py
```
plugins.call(self.ordered_plugin_list, 'on_result', self.request, self, result)
```
Could be done in ResultContainer to speed up the process. 

[EDIT] : in search.py the duplicated results are already merged. In ResultContainer they won't.
One way to avoid duplicate processing by plugins is to add a cache in ResultContainer : 
```python
class ResultContainer(object):
  def __init__(self):
    ...
    self.processedUrl = dict()

    def extend(self, engine_name, results):
        for result in list(results):
            result['engine'] = engine_name
            if 'url' in result:
                result['url'] = self.processUrl(result['url'])
            # process other URLs (images, etc...) ?
            ...

    '''
       should be thread safe?
       is not, the same URL may be processed multiple time
       (should not be a problem)
    '''
    def processUrl(url):
        if url in self.processedUrl
            # self.ordered_plugin_list and self.request, self.search must be initialized.
            self.processedUrl['url'] = plugins.call(self.ordered_plugin_list, 'on_result', self.request, self.search, url)
        return self.processedUrl['url']
```
