### ISSUE TITLE
move searx/searx to searx/searx-old and move asciimoo/searx to searx/searx

### ISSUE THREAD

**Issue by Neustradamus** [searx/searx#1228]
First, it is possible to move searx/searx to searx/searx-old (or searx/searx-archives)
and move asciimoo/searx to searx/searx

It will be better, I do not understand the fork ;)

**Comment by Pofilo** [comment]
I think it's too late, too many forks and stars ..

As @asciimoo is active, there is no pb (for merging PR ..). I don't know if @dalf or @kvch can merge PR too.

**Comment by Neustradamus** [comment]
Nothing is lost!

**Comment by Neustradamus** [comment]
"Fork" has based on this: 394
"Watch" and "Star" are separated but you can look the difference, it is better here: 180 / 2725 vs a very very little
-> It is the best solution to move :)

**Comment by Neustradamus** [comment]
Hi guys,

Any news about this request?

@asciimoo, @dalf, @kvch, @Pofilo

**Comment by Neustradamus** [comment]
@asciimoo, @dalf, @kvch, @Pofilo https://help.github.com/articles/about-repository-transfers/

**Comment by Pofilo** [comment]
Thanks for the link, it's up to @asciimoo to choose this kind of stuff I think.
The day @asciimoo will choose to stop the development of Searx (or if he don't have time anymore), it will be necessary to do that (otherwise, someone will have to make "an official fork"). However, I don't think it's really important to do it now (even if I understand your concern).

_TLDR: Up to @asciimoo and thanks for the link :)_

**Comment by Neustradamus** [comment]
@asciimoo, @dalf, @kvch, @Pofilo Why when the development will be stopped?
The main repository is here.
It is easy to do it right now without lost...

**Comment by Neustradamus** [comment]
Any news?
@asciimoo, @dalf, @kvch, @Pofilo

**Comment by Neustradamus** [comment]
Any news?
@asciimoo, @dalf, @kvch, @Pofilo

**Comment by Pofilo** [comment]
@Neustradamus what are the real benefits of doing that ?
Searx is not a company but a free and open source software mostly developed by @asciimoo, it's normal that the repository is on his account.

**Comment by Neustradamus** [comment]
@asciimoo, @dalf, @kvch, @Pofilo Better with the main project in an organization and it is not needed to be a company.
And there is already an organization and searx/searx (which mix people), easy to rename searx-archives and move it to searx/searx to be perfect.
No lost.

**Comment by Neustradamus** [comment]
Yes all asciimoo/searx links will be redirected to searx/searx links.
Of course in first, you must to move searx/searx to searx/searx-old (or searx/searx-archives)
No lost.

**Comment by Neustradamus** [comment]
@asciimoo, @dalf, @kvch, @Pofilo: Happy new year guys!
Any news about this ticket?

**Comment by Neustradamus** [comment]
@asciimoo, @dalf, @kvch, @Pofilo: Any news?

**Comment by nerzhul** [comment]
if you move a project, github will redirect old project to new project (302) and forks are kept.

Look at this project for example: https://github.com/nerzhul/ocsms

**Comment by Neustradamus** [comment]
More one year after? Any news for this?

**Comment by Neustradamus** [comment]
Any news?
Time to do it?
@asciimoo, @dalf, @kvch, @Pofilo https://help.github.com/articles/about-repository-transfers/

**Comment by rachmadaniHaryono** [comment]
hi, i hope this repo can be moved to organization so others can add more maintainer to work on this project.

currently this repo have 439 issue and 73 pr. some can be closed/merged, others need confirmation. with more maintainer maybe we can lower the issue/pr number.

in contrast, this repo have 4845 star and 246 watcher. with these numbers there are a lot of potential to make this repo more active.

other things:

- document some question/pr/issue into faq, because there are some question that asked multiple time.
- issue and pr template, this make search easier also avoid duplicate
- separate searx instance and searx issue. it can be addressed to above point
- remove python 2.7 because it is reaching eol
- organize current issue/pr. maybe make it into one big todo list
- update/change package

i can make some of those feature on my own fork but i believe it is better that i can address it on main repo  so other can also benefit from my work

this may take some time because usually the repo activity is slow and current maintainers are busy irl

things we can do while waiting response

- work on other fork from other user, who is more active. i don't recommend this because this will create fragmentation and maybe there will be problem merge it upstream
- work on one big pr that solve above problem. this have chance not to merge but this is the best method i can think of.

i would love to hear any response. i also will be on irc this weekend (2019-06-22, gmt+8) if anyone want to discuss this

**Comment by Neustradamus** [comment]
@rachmadaniHaryono: Thanks a lot for your comment! :)
Hope that @asciimoo, @dalf, @kvch, @Pofilo can release this change more one year after this request.
- https://help.github.com/articles/about-repository-transfers/

**Comment by rachmadaniHaryono** [comment]
there is update to #1561, which point me to https://github.com/searx?type=source

maybe there is development here

**Comment by dalf** [comment]
For information, the [searx/searx](https://cloud.docker.com/repository/docker/searx/searx/) Docker image is made from https://github.com/searx/searx which will synchronized from https://github.com/asciimoo/searx from time to time.

**Comment by Neustradamus** [comment]
@dalf: Why do not move https://github.com/searx/searx to https://github.com/searx/searx-old and https://github.com/asciimoo/searx to https://github.com/searx/searx?
Easy, no lost... more pro... several projects have been it.

"Used by", "Watchers", "Stars", "Forks" from old main repository will be moved, no lost.
https://github.com/asciimoo/searx will be redirected to https://github.com/searx/searx...

And after the move, you can archive the https://github.com/searx/searx-old.

cc: @asciimoo, @kvch, @Pofilo, @rachmadaniHaryono, @nerzhul

**Comment by rachmadaniHaryono** [comment]
just quick question, who can make this happen? is it only asciimoo or other invited maintainer can do it too?

**Comment by Neustradamus** [comment]
@rachmadaniHaryono: Searx project have 3 public admins and maybe other hidden: https://github.com/orgs/searx/people.
There are several right possibilities in project administration.
But all steps need to be the same day, one after one.
For move the last step https://github.com/asciimoo/searx to https://github.com/searx/searx, yes @asciimoo needs to do it.
Not easy to sync people? The steps can be done in 5 minutes less.

cc: @asciimoo, @dalf, @kvch, @Pofilo, @rachmadaniHaryono, @nerzhul

**Comment by Neustradamus** [comment]
@asciimoo, @dalf, @kvch, @Pofilo, @rachmadaniHaryono, @nerzhul, @rachmadaniHaryono: Any news?

**Comment by kvch** [comment]
@Neustradamus What are the benefits of moving the repo to searx/searx?
I am not against it, I just don't understand why you are so keen on moving the repo.

**Comment by Neustradamus** [comment]
It is better to have searx/searx or asciimoo/searx?

You have already the answer ;)

**Comment by kvch** [comment]
Sorry if I missed your reasoning, can you show me exactly which comment you mean?

**Comment by Neustradamus** [comment]
@asciimoo, @dalf, @kvch, @Pofilo, @rachmadaniHaryono, @nerzhul, @rachmadaniHaryono: You can see that searx/searx is a fork of asciimoo/searx?

It is better to have the main repository searx/searx no?

Project management, right administrations, ...

**Comment by Pofilo** [comment]
Searx is not an organization. It is just a software where people give their time to make it work.
The owner is @asciimoo, but some other people also have the rights to push so the project is not blocked or whatever.

> It is better to have the main repository searx/searx no?
> Project management, right administrations, ...

What are the real benefits ? You didn't answer the question.

**Comment by kvch** [comment]
I agree with @Pofilo. I was looking for a technical/management benefit behind your request. But to me it seems that it is a personal preference. Is that correct?

**Comment by Neustradamus** [comment]
It is better to promote a software with a good space: searx/searx is a fork of this, what is the goal?
It is not a personal preference, it is a logic.
For a team management, organisation is better than personal account.

Recall: 2 points:
- searx/searx by default (move...)
- personal account to orgization account

**Comment by Pofilo** [comment]
Searx/searx is a fork but the real repo is here and nobody use searx/searx.
I understand your point for a company, not for small project done on free time.

The only thing is if @asciimoo stop using the project, this day (if it happens) it could make sense. Today, there is no need to do such a thing. Do you see an organisation for every project on Github/gitlab ... ? No.

**Comment by Neustradamus** [comment]
It is possible to remove the fork if no people use it?

**Comment by Neustradamus** [comment]
@asciimoo, @dalf, @kvch, @Pofilo, @rachmadaniHaryono, @nerzhul, @rachmadaniHaryono: It is possible to delete the fork if no people use it?

**Comment by Pofilo** [comment]
@Neustradamus I close the issue, there is no need to use searx/searx neither to delete the fork.

There is so much usefull things to do than arguing for something that will not make the world (neither Searx) better.

**Comment by Neustradamus** [comment]
Hello all, @asciimoo, @dalf, @kvch, @unixfox, @Pofilo, @rachmadaniHaryono, @nerzhul, @rachmadaniHaryono,

Happy New Year 2021 to all!

Congratulations, after a very long time, I see that my request has been done.

To recall, it was asciimoo/searx and it has been moved to searx/searx.

**Comment by Neustradamus** [comment]
Oh, I see another one!

You can do same with searx-checker.

Steps:
- In the organization, create a temporary searx-checker-issues repo to transfer all https://github.com/searx/searx-checker issues to searx-checker-issues
- Merge all branches from https://github.com/searx/searx-checker into https://github.com/kvch/searx-checker
- Remove https://github.com/searx/searx-checker
- Transfer https://github.com/kvch/searx-checker into https://github.com/searx organization
- Transfer all issues from searx-checker-issues into searx-checker
- Remove searx-checker-issues repo

It will be perfect :)

**Comment by dalf** [comment]
@Neustradamus see https://github.com/searx/searx/pull/2419 : the searx-checker project will be archived, the feature will be integrated into searx.
