### ISSUE TITLE
Image builds on Docker Hub

### ISSUE THREAD

**Issue by angristan** [searx/searx#1232]
Would it be possible for you to setup automated builds on the Docker Hub, so that we don't have to build the image ourselves ?

Thanks!

**Comment by i5heu** [comment]
this is an really quick set up with docker hub.
please provide a trustable docker image <3

**Comment by Pofilo** [comment]
A new docker repo can help you: https://github.com/searx/searx-docker.
Feel free to reopen the issue if needed.
