### ISSUE TITLE
SearX API calls

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1234]
Hello,

Is is possible for SearX to act as a headless server so that you could send a query string to a SearX Search API and get back json results?

**Comment by dalf** [comment]
As a server (pick the instance you want or install yours), there is an API: https://asciimoo.github.io/searx/dev/search_api.html

If you want to use it as a standalone program (command line interface rather than HTTP interface) : https://github.com/asciimoo/searx/blob/master/utils/standalone_searx.py
(JSON output, can be easily hack to the output you want).

**Comment by Outstep** [comment]
Thanks for the information and this is a real help for my target goals.

In looking things over it seems that I would still need to implement something like Python Flask to answer the API calls and add a bit for a JSON return.

I would run this as a completely independent server and just send a query along with a category and return format (of course there might be some pagination stuff to be added)

Would this be about right?

Thanks again :)

**Comment by Outstep** [comment]
Hi Again,

I actually just tried to test it from the searx directory:

~/searx/builds/searx$ python utils/standalone_searx.py --category general spacex

and got this error:

```
Traceback (most recent call last):
  File "utils/standalone_searx.py", line 103, in <module>
    sys.stdout.write(dumps(result_container_json, sort_keys=True, indent=4, ensure_ascii=False, encoding="utf-8", default=json_serial))
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "utils/standalone_searx.py", line 84, in json_serial
    raise TypeError ("Type not serializable")
TypeError: Type not serializable
```

**Comment by Outstep** [comment]
Hello,

I was just trying to run the standalone_searx.py with Python3 and am now getting:
~/searx/builds/searx$ python3 utils/standalone_searx.py spacex
Traceback (most recent call last):
  File "utils/standalone_searx.py", line 59, in <module>
    "categories":args.category.decode('utf-8'),
AttributeError: 'str' object has no attribute 'decode'

Any ideas on how to get this program to run as I am not having much luck so far?
Thanks in advance.

**Comment by virtadpt** [comment]
@lonnieOST It's pretty straightforward to do that.  You can make Searx return search results as JSON documents by specifying the format.  I do it like this: http://localhost:8888/?q=this%20search%20term&categories=general&format=json&lang=en&time_range=day

You can also have Searx return CSV or RSS for searches.

As for algorithmically interacting with Searx, here's some code I wrote that does that: https://github.com/virtadpt/exocortex-halo/blob/master/web_search_bot/web_search_bot.py#L419

**Comment by Outstep** [comment]
@virtadpt Thanks You so very much.  This is AWESOME and exactly what I needed since I will be calling Searx from another server!!!!

If I would have known this then I would not have commissioned a freelance developer to try and work on a server daemon using Sanic (https://github.com/channelcat/sanic) which is much faster than Flask and the Searx (standalone_searx.py) CLI version. As my Python skills are not that strong yet and I needed a working daemon as part of a larger project that this will feed data into.

I also just tried adding "&pageno=1" to a local Searx server that I have running and it also works great.

Do you by chance, know where I can get a list of all the available URL parameters that I can pass in this call?

Thanks again

**Comment by asciimoo** [comment]
@lonnieOST you can find the search API documentation here: https://asciimoo.github.io/searx/dev/search_api.html as @dalf mentioned. It contains all the available URL parameters.

**Comment by Outstep** [comment]
Hi Again,

Just one more question about the SearX API and JSON return.

I did an test with:
curl "http://localhost:8888/?q=solar%20panels&categories=general&format=json&lang=en&pageno=1"| python -m json.tool

past of the JSON output shows:

            "positions": [
                10
            ],
            "pretty_url": "http://www.freesunpower.com/solarpanels.php",
            "score": 0.1,
            "title": "Basic Tutorials: Solar Panels for Solar \u2026",
            "url": "http://www.freesunpower.com/solarpanels.php"
        }
    ],
    **"suggestions": [],**
    "unresponsive_engines": [
        [
            "yacy",
            "request exception"
        ],
        [
            "gigablast",
            "unexpected crash: No JSON object could be decoded"
        ]
    ]

and the web interface has:
![screenshot from 2018-03-13 18-40-28](https://user-images.githubusercontent.com/24719646/37373716-27268f06-26ee-11e8-96e5-3b959ce9db1a.png)

Actually, I do not know if image will come through, but on my we interface it does come through with some "SUGGESTIONS" in that section.

My question is as to why does the json "suggesions" not have the text for the suggestions that we web interface has since I would like to get that data as well, if possible.

Thanks again and it seems that I am almost there as far as having a metasearch engine that works really good.

Cheers,
Lonnie





The JSON return has most of the information, but I noticed that the "suggestions : []" was blank

**Comment by Outstep** [comment]
@virtadpt I have a small API question.

In the past, you told me about how to access SearX via curl:

--------------------

You can make Searx return search results as JSON documents by specifying the format. I do it like this: http://localhost:8888/?q=this%20search%20term&categories=general&format=json&lang=en&time_range=day

-----------------------

and all works great, I must say first of all.

The only question is in changing the categories. I basically know how to use images, vodeos, etc.... but the "social media" category is 2 words and I did not know how to include this in the curl statement.

I tried
http://localhost:8888/?q=this%20search%20term&categories=social%20media&format=json&lang=en&time_range=day
but that does not seem to work. 

The documentation is also not very clear on this:
https://asciimoo.github.io/searx/dev/search_api.html

Am, I missing something here?

Thanks

**Comment by virtadpt** [comment]
I did a little tinkering, and I think this is how you'd make the API call:

http://localhost:8888/?q=this%20search%20term&categories=social+media&language=en-US&format=json&time_range=day

When you specify the category, it would be `social+media` (plus), not `social%20media`.

**Comment by NightMachinery** [comment]
[**@dalf**](https://github.com/dalf) commented on [Mar 11, 2018, 8:45 PM GMT+3:30](https://github.com/searx/searx/issues/1234#issuecomment-372131864 "2018-03-11T17:15:53Z - Replied by Github Reply Comments"):
> As a server (pick the instance you want or install yours), there is an API: [asciimoo.github.io/searx/dev/search\_api.html](https://asciimoo.github.io/searx/dev/search_api.html)
> 
> If you want to use it as a standalone program (command line interface rather than HTTP interface) : [https://github.com/asciimoo/searx/blob/master/utils/standalone\_searx.py](https://github.com/asciimoo/searx/blob/master/utils/standalone_searx.py?rgh-link-date=2018-03-11T17%3A15%3A53Z)  
> (JSON output, can be easily hack to the output you want).

I get 
```
❯ curl 'http://localhost:4004/search?q=orange&format=json'
Rate limit exceeded
```

Update: Using port 8888 works, but I like to change the ratelimit on the filtron instance ...

Update 2: The rules can be edited by `sudo vim '/etc/filtron/rules.json'`. It's also possible to bypass some of them easily, e.g., by faking the useragent.
