### ISSUE TITLE
searx and the terms of service of used search engines

### ISSUE THREAD

**Issue by ghost** [searx/searx#1237]
Does searx agree with the terms of service of the default search engines used? Could the answer to that please be included in settings?

**Comment by asciimoo** [comment]
@riesnerd What is the purpose of this request?

**Comment by stef** [comment]
does a user ever have to agree to terms of services when 1st time using google or any other search engine?

**Comment by Yetangitu** [comment]
I guess what he means is whether searx gives consent for all those things which sites like Google ask you to give consent to (use of cookies etc.). Given the way searx works this is more or less impossible as the whole point of the exercise is to avoid the things which you're supposed to give consent to.

Another possibility is whether searx violates the terms of service of search engines which it uses to gather results. The answer to that is 'probably', see e.g. Google's terms of service:

http://www.google.com/intl/en/mobile/xhtml/terms_of_service.html
```
No Automated Querying

You may not send automated queries of any sort to Google's system...
...
- "meta-searching" Google;
...
```
As always it is up to the user to decide what to do but keep in mind that many of the countermeasures used by 'savvy' users of sites like Google (dropping or scrambling cookies, blocking access to resources, removing redirects, etc.) can also be construed as being against the terms of service. Pick your poison.

**Comment by stef** [comment]
i think you are asking the wrong people. first of all this question is something that could only concern people running searx instances. if do run your own instance you should ask your local lawyer specializing in internet related cases. and then the answer depends on a lot of things like:

 - the level of fascism[1] in your jurisdiction vs respect of human rights,
 - the local level of respect for rule of law and US interests,
 - anti-competition/anti-trust aspects,
 - the non-commercial nature of your instance,
 - the enforcability of terms of use that have never been actively accepted by anyone involved,
 - the affinity of google for being in the press with headlines like: "US kraaken bullies small, non-profit privacy-enhancing free software project",
 - the size and material of your balls ;)
 - etc

so someone running a searx instance in st petersburg distributing malware with every result and doing some blackhat seo as a side-business could probably get away with all this, but some rich freedom-hating misogynist  running an instance with lots of advertising in San Francisco could probably probably have a few lawyers up his neck.

Decentralization of searx instances helps a lot here i believe, the magic is to not become too big to be a target for google, but at the same time to be big enough to have a reasonable anonymity set to hide among.

[1] fascism: authoritarian corporatism

**Comment by unixfox** [comment]
Now that there is no official Searx instance anymore (searx.me), it's up to the maintainer of a Searx instance to know the consequences of hosting one.
