### ISSUE TITLE
searx 0.14.0 doesn't start on debian 9.4

### ISSUE THREAD

**Issue by HLeithner** [searx/searx#1247]
I tried to update to searx 0.14.0 and found out that the commit https://github.com/asciimoo/searx/commit/2f69eaeb2fb76a14d9c3f2a67a9e404b066049ba#diff-507e4cefa628e712970da95ed51f569bR233 breaks uwsgi on my debian 9.4 with python 2.7.13

it seams that it only returns an internal server error or a timeout when I add the 'engine_name, ' to the for loop.

**Comment by timscha** [comment]
I have the same problem.

**Comment by asciimoo** [comment]
Isn't this related to https://github.com/asciimoo/searx/issues/1210 ?

**Comment by timscha** [comment]
Yes, you're right @asciimoo! I added "lazy-apps = true" to /etc/uwsgi/apps-available/searx.ini and searx is working again. Thank you!
