### ISSUE TITLE
[improvement] Add automatic search language detection

### ISSUE THREAD

**Issue by aurora-anon** [searx/searx#1259]
Just the way every search engine works.
The engine detects the language automatically.

Make this process automatic but also let users define their first and second search languages and so on.

**Comment by sachaz** [comment]
+1

**Comment by unixfox** [comment]
Currently, when visiting Searx, it will switch to the language provided by the browser. If it's not the desired feature that you want, feel free to reopen this issue and explain a bit more what you want.

**Comment by Malmik** [comment]
I think I understand what author was thinking about. In vanilla Google, if you enter phrase into search bar that is for example in spanish language, browser will return results in spanish language. If then, user would enter query in english, results would be returned also in english language. In SearX, you can set language of results in preferences, so If I set it to spanish, results will be in spanish, no matter which language was query entered in. This is unfavourable as vast majority of people uses internet in their native language and english side to side. SearX is tedious in this use case, as you have to switch results language manualy each time.

@unixfox please reopen

**Comment by unixfox** [comment]
> I think I understand what author was thinking about. In vanilla Google, if you enter phrase into search bar that is for example in spanish language, browser will return results in spanish language. If then, user would enter query in english, results would be returned also in english language. In SearX, you can set language of results in preferences, so If I set it to spanish, results will be in spanish, no matter which language was query entered in. This is unfavourable as vast majority of people uses internet in their native language and english side to side. SearX is tedious in this use case, as you have to switch results language manualy each time.
> 
> @unixfox please reopen

Switch the language to "default language" and the google engine will function exactly like you explained.

-------

Duplicate of https://github.com/searx/searx/issues/1236

**Comment by Malmik** [comment]
I see, thanks!
