### ISSUE TITLE
Saved settings URL not working

### ISSUE THREAD

**Issue by BorbingoBoy** [searx/searx#1261]
It appears that the cookie-free, incognito mode isn't ideal for using searx. Uppon entering a saved settings URL and a query, the default settings load instead of custom settings.

**Comment by peter-w-remote** [comment]
Same problem here. I'm using a browser which deletes all cookies by default when closed.
The settings URL is not working as described above.
Every time I close the browser all settings are gone.

Would be great if it was possible to store all the settings in a config file.

**Comment by peter-w-remote** [comment]
Being able to store all settings in a config file would enhance privacy as well as usability.
Because websites would not be able to read those cookies if there weren't any.
Furthermore users running there own instance could store different profile files with different settings.
