### ISSUE TITLE
Image results appear stretched if using mobile mode

### ISSUE THREAD

**Issue by BorbingoBoy** [searx/searx#1262]
Images get stretched vertically if viewing image results from a mobile browser in portrait mode.

**Comment by aurora-anon** [comment]
Just look at the way how other search engines solved this issue.

**Comment by dalf** [comment]
The problem is solved if you use the simple theme.

The implementation is here :
https://github.com/asciimoo/searx/blob/master/searx/static/themes/simple/js/searx_src/searx_imageresult.js

**Comment by dalf** [comment]
Technical note to implement this feature in the oscar.

This file (searx_imageresult.js) could be moved to searx/static/js and be used by simple and oscar theme without modification (I haven't tried)

In simple theme : 
```javascript
    searx.image_thumbnail_layout = new searx.ImageLayout('#urls', '#urls .result-images', 'img.image_thumbnail', 200);
    searx.image_thumbnail_layout.watch();
```

For oscar theme : 
```javascript
    searx.image_thumbnail_layout = new searx.ImageLayout('#main_results', '#main_results .result-images', 'img.image-thumbnail', 200);
    searx.image_thumbnail_layout.watch();
```

**Comment by aleferov** [comment]
I do not understand what needs to be done. Help me please. In which file do I need to change the code?
