### ISSUE TITLE
"last year" returning no results

### ISSUE THREAD

**Issue by dixonge** [searx/searx#1263]
I first ran into this issue on searx.site - switched to searx.me, but now this has started happening here as well. It is reproducible on *all* searches. Unrestricted search has results from within the last year, but setting "last year" under the time drop-down shows nothing.

Firefox 59.0.2
Windows 10

**Comment by dixonge** [comment]
Just tested in MS Edge - works fine with searx.me, not with searx.site

When I get no results, I am getting this message from searx:

"Sorry! we didn't find any results. Please use another query or search in more categories. "

**Comment by Hronom** [comment]
Same here https://searx.nulltime.net/ also not work, how to solve this problem? I'm using search through rest api.

Here is my REST api call:
```
https://searx.nulltime.net/search?q=Word of Warcraft&categories=news&time_range=year&language=en&format=json
```

Returned result is next:
```
{
    "number_of_results": 0,
    "corrections": [],
    "query": "Word of Warcraft",
    "infoboxes": [],
    "suggestions": [],
    "results": [],
    "answers": [],
    "unresponsive_engines": []
}
```

**Comment by dimqua** [comment]
@kvch Startpage supports it, but it doesn't work in searx.

**Comment by kvch** [comment]
Yes, time range support has not been added to startpage engine.

**Comment by dixonge** [comment]
closing this as generally abandoned.
