### ISSUE TITLE
[improvement] Add the ability to dynamically exclude search engines that are offline or returning error

### ISSUE THREAD

**Issue by aurora-anon** [searx/searx#1266]
That happens many times about a few search engines like The Pirate Bay.

**Comment by prolibre** [comment]
+1
a dynamic blacklist (for a certain number of hours) of engines in error (for example google !)
___
+1
une blacklist dynamique (pour un certain nombre d'heures) des moteurs en erreur (pour exemple google !)

**Comment by asciimoo** [comment]
This is actually implemented but the duration of the ban is only 5s currently. Every engine has a ban counter which is increased by the ban duration on every error.
Perhaps, we should make the fail ban duration configurable.

**Comment by dalf** [comment]
I don't know if piratebay wikidata page is updated. If yes something similar to
https://gitlab.com/Flockademic/whereisscihub
Could be used.
