### ISSUE TITLE
Consider stop being just a meta search engine

### ISSUE THREAD

**Issue by maverick74** [searx/searx#1269]
Ok, i'll admit i don't have a very clear clue about how technical this might be, but i would like to start a discussion among those who have!

I think it would be great to stop being just a meta search engine and, beside that, starting to also be a "normal" search engine, like Google or Bing.

i understand that requires crawlers, and resources, but it does have to start somewhere and searx is, imho, one of the few meta search engines that might have a shot at this...

**Comment by maverick74** [comment]
Yes, but that requires you install it. In a public service, for example, you won't be able to access it unless it was already installed.
So, while i like the fact that it is an open _distributed_ search engine, that leaves it out of the deck for now.

**Comment by asciimoo** [comment]
I agree with @LuccoJ searx can be used as a frontend for any kind of search backend. Good example is #1257 or the yacy engine.

**Comment by dimqua** [comment]
Gigablast.

**Comment by maverick74** [comment]
Thank you!
