### ISSUE TITLE
Can not install on raspberry pi

### ISSUE THREAD

**Issue by popeyesfx** [searx/searx#1281]
Hi
I have been trying to follow the step by step install for a raspberry pi ruling stretch, but when i run
`sudo apt-get install git build-essential libxslt-dev python-dev python-virtualenv python-babel zlib1g-dev libffi-dev libssl-dev`

i get the following error

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libxslt-dev
E: Package 'python-virtualenv' has no installation candidate
E: Unable to locate package python-babel
E: Unable to locate package libffi-dev
E: Unable to locate package libssl-dev`

not sure why, i have watched a vid on youtube and the guy installs on a pi no problem.

any ideas

thanks

**Comment by Pofilo** [comment]
Well I have it on Jessie. But according to the [official debian website](https://packages.debian.org/search?searchon=names&keywords=virtualenv) it is also available on Stretch as `python3-virtualenv`.
Is this package available to you ?

I just found [that](https://packages.debian.org/stretch/python-virtualenv) so I don't really understand ..

**Comment by popeyesfx** [comment]
Well I have installed jessie and still get the same issue
`cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
`

`sudo apt-get install git build-essential libxslt-dev python-dev python-virtualenv python-babel zlib1g-dev libffi-dev libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python

E: Unable to locate package libxslt-dev
E: Package 'python-dev' has no installation candidate
E: Package 'python-virtualenv' has no installation candidate
E: Unable to locate package python-babel
E: Unable to locate package libffi-dev
E: Unable to locate package libssl-dev`

so not sure what is going on here. Unless the default install line is now incorrect.
I have python3.4.2 and 2.7.9 installed on a pi 3 so as far api can see it should work.

what version of jessie are you using, should i run something before i start or have i just missed something

**Comment by Pofilo** [comment]
Well, I have:
```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

Did you make a `sudo apt-get update` before trying to install the packages ?

If the `apt-get update` doesn't make it work, what are the content of `/etc/apt/sources.list` and `/etc/apt/sources.list.d/raspi.list`.
I have:
```
deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspbian.org/raspbian/ jessie main contrib non-free rpi
```
and
```
deb http://archive.raspberrypi.org/debian/ jessie main ui
# Uncomment line below then 'apt-get update' to enable 'apt-get source'
#deb-src http://archive.raspberrypi.org/debian/ jessie main ui
```

And does `apt-cache search python-virtualenv` return `python-virtualenv - Python virtual environment creator` ?
