### ISSUE TITLE
Starting searX with apache2 ,does not load, page not available

### ISSUE THREAD

**Issue by popeyesfx** [searx/searx#1286]
I have followed the instructions on the wiki and have uwsgi and apache2 running
`pi@hades:/usr/local/searx $ sudo systemctl status uwsgi
● uwsgi.service - LSB: Start/stop uWSGI server instance(s)
   Loaded: loaded (/etc/init.d/uwsgi)
   Active: active (exited) since Sun 2018-04-29 16:23:30 BST; 39min ago

Apr 29 16:23:27 hades systemd[1]: Starting LSB: Start/stop uWSGI server ins.....
Apr 29 16:23:30 hades uwsgi[583]: Starting app server(s): uwsgi -> . done.
Apr 29 16:23:30 hades systemd[1]: Started LSB: Start/stop uWSGI server inst...).
Hint: Some lines were ellipsized, use -l to show in full.
`
and

`pi@hades:/usr/local/searx $ sudo systemctl status apache2
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─forking.conf
   Active: active (running) since Sun 2018-04-29 16:46:23 BST; 17min ago
  Process: 1763 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 1787 ExecStart=/etc/init.d/apache2 start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/apache2.service
           ├─1804 /usr/sbin/apache2 -k start
           ├─1805 /usr/sbin/apache2 -k start
           └─1806 /usr/sbin/apache2 -k start

Apr 29 16:46:23 hades apache2[1787]: Starting web server: apache2AH00558: a...ge
Apr 29 16:46:23 hades apache2[1787]: .
Apr 29 16:46:23 hades systemd[1]: Started LSB: Apache2 web server.
Hint: Some lines were ellipsized, use -l to show in full.
`

however sears does not run as far as ai can see

i have used
`<Location />
        Options FollowSymLinks Indexes
        SetHandler uwsgi-handler
        uWSGISocket /run/uwsgi/app/searx/socket
</Location>

`
at the bottom of the apache2.conf file.

should the Location be /usr/local/searx
is there any way to check that searx is running using systemctl or some other method.

thanks

**Comment by r1bnc** [comment]
have you tried visiting the searx instance in your own server, (eg. using links/lynx/elinks visit the  127.0.0.1 port 8888 if you can see the searx interface then uwsgi searx is running if not then it is not).

double check your searx configurations. uwsgi should be in  active (running)

**Comment by Pofilo** [comment]
@popeyesfx have you try @gr01d troubleshot ?

You can find the same troubleshot with screenshots here: https://github.com/asciimoo/searx/issues/686#issuecomment-396155336

Please, close the issue if the problem is solved.

**Comment by popeyesfx** [comment]
The problem wasn't solved as such, i just used a service and build a work around
