### ISSUE TITLE
Create Json format the search error

### ISSUE THREAD

**Issue by Jul10l1r4** [searx/searx#1287]
The response **Rate limit exceeded**, error 429

**Comment by Pofilo** [comment]
Can you explain how to reproduce the bug ? In a specific configuration ?
For example if I want to reproduce the bug on [https://searx.me/](https://searx.me/), how do I proceed ?

**Comment by asciimoo** [comment]
@Jul10l1r4 this is not a bug. Public instances often limit non-human output formats like JSON/RSS (E.g. on searx.me only two JSON/RSS requests are allowed per minute to reduce bot traffic). Try to use an own instance if you'd like to search with scripts.
