### ISSUE TITLE
How does this *work* when run locally?

### ISSUE THREAD

**Issue by keeganjk** [searx/searx#1291]
I download this and installed it locally but didn't understand how it worked without going through a server. How does this work?

*Sorry, my lack of knowledge is an issue. Also, you may want to add this info to Docs/Wiki.*

**Comment by kvch** [comment]
Flask provides a development server which is used by searx in `run`: https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L878
How the dev server works: http://flask.pocoo.org/docs/0.12/server/#in-code
