### ISSUE TITLE
DSGVO data privacy statement

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#1292]
Does anyone in the EU think about some DSGVO stuff for searx in the about-page? IMHO this page should be prepared for data privacy statements

**Comment by dalf** [comment]
I don't think that searx stores personal data, actually that's the whole point of searx: Stateless.
So there is no right to be forgotten, no access to personal records, etc...

[EDIT] Actually we have to ensure that the IPs are not logged.

**Comment by erdmark** [comment]
Ip addresses are considered to be personal data so except those engines that are run as a hidden service we have to process ip addresses in order to respond to search questions.
Additionally many hosters store logs with at least shortened Ip-addresses and urls with timestamps in it.
Based on datenschutz-generator.de I created a privacy statement and adapted it for the use with my hoster Uberspace.
[about20180518.txt](https://github.com/asciimoo/searx/files/2016514/about20180518.txt)

When copying something into about.html be sure to use "normal" ASCII Characters, things like "ö" or "ß" are not supported by Searx. After that restart Searx.

**Comment by stef** [comment]
yeah, these statements need to be created by the people running searx instances, there is no generic statement that fits all. for those who do not log ip addresses at all, there's not much to state, besides no logging happening and the cookies also do not contain anything. so there is not much to do. but for those who log there is. you cannot make a statement for your hoster, that is up to the hoster to make such a statement, if they indeed log ip addresses - in which case you might want to look for a more privacy respecting hoster anyway.

**Comment by cy8aer** [comment]
Ok, I built one for myself and prepared `searx/templates/__common__/about.html`. But now there is another (technical) issue: When updating searx from git this file is overwritten. It needs to be reinstalled after git reset. It would be nice to have a path where you can put your about.html and it is included from the theme's about.html. Is this possible with jinja2 (if file exist: include else include __common_/about.html)?

**Comment by Pofilo** [comment]
>  When updating searx from git this file is overwritten. 

How do you update from git ? A `git pull` will not erase your additional files (and merge the modfied ones).

**Comment by cy8aer** [comment]
What about an `{% include "__common__/aboutextend.html" ignore missing %}` at the end of `searx/templates/__common__/about.html`? This would extend the original file with your special extension if exists. `aboutextend.html` is not in the git repository and everything will be fine... Comments?

**Comment by Pofilo** [comment]
Sounds good to me :)

Can you send a PR ?
If you can't, I can do it this evening (CEST time in 9 hours from this post) so just tell me.

**Comment by cy8aer** [comment]
Stand by - let's see who is faster...

**Comment by der-jannik** [comment]
To fullfill the DSGVO it is actually required to have the privacy policy directly accessible from every site AFAIK, thus, every site should contain a direct link to the privacy policy. Moreover, I think it's not just legally reasonable to have the privacy policy accessible easily - it is also for the benefit of the users, as individual Searx instances can have major differences when it comes to webserver log policies and default settings.

So my suggestion would be to provide a config option where one can link to the privacy policy of their respective website. This link could be displayed in every template in the footer, where the links to the searx source code, issue tracker and public instance list already are.
