### ISSUE TITLE
Gigablast crash

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1293]
Greetings,

I have been experimenting with SearX lately and have been seeing this message:

"
Engines cannot retrieve results:

gigablast (unexpected crash: No JSON object could be decoded)
"

Seems like something is wrong with the Gigablast driver but I am not sure how to fix it.

I'm using:  searx - 0.14.0 

Thanks

**Comment by Outstep** [comment]
Hello,

Can you please clarify. Was this fixed?
Thanks,

**Comment by kvch** [comment]
Yes. Does it crash again?

**Comment by Outstep** [comment]
Yes,

I still get the same message:


*Error!* Engines cannot retrieve results.

gigablast (unexpected crash: No JSON object could be decoded)

Thanks,

**Comment by kvch** [comment]
Have you pulled the latest changes?

**Comment by Outstep** [comment]
Hi,

I just now did:

git clone https://github.com/asciimoo/searx.git

started it up and went to localhost:8888

and then

/searx$ python searx/webapp.py
ERROR:searx.search:engine gigablast : exception : No JSON object could be
decoded
Traceback (most recent call last):
  File "/home/lonnie/yacy-susper-susi-qs/test/searx/searx/search.py", line
104, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/home/lonnie/yacy-susper-susi-qs/test/searx/searx/search.py", line
87, in search_one_request
    return engine.response(response)
  File
"/home/lonnie/yacy-susper-susi-qs/test/searx/searx/engines/gigablast.py",
line 82, in response
    response_json = loads(resp.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by kvch** [comment]
Yes, I see now. It works locally, but on https://searx.kvch.me it's deployed and I get the same message.

**Comment by zero77** [comment]
https://searx.me/?q=1&categories=general
i am getting the same error hear.

**Comment by atomGit** [comment]
can confirm this on searx.me

**Comment by atomGit** [comment]
on second thought, i would vote to remove gigablast - it's old, unmaintained and i suspect it doesn't offer anything other indexes don't ??? just a thought
