### ISSUE TITLE
Docker built searx sending and receiving tcp packets from some Amazon cloud server 

### ISSUE THREAD

**Issue by ghost** [searx/searx#1302]
I have[ installed searx with docker](https://github.com/asciimoo/searx/wiki/Installation) and for security I checked what kind of packets my searx docker image is  transmitting. I have noticed that when loading the homepage of searx on startup its sending some packets to aws cloud servers.

whois 

```
OrgName:        Amazon.com, Inc.
Address:        Amazon Web Services, Inc.
Address:        P.O. Box 81226
City:           Seattle
StateProv:      WA
PostalCode:     98108-1226
Country:        US
Comment:        For details of this service please see
Comment:        http://ec2.amazonaws.com/
```

**Comment by asciimoo** [comment]
It's the soundcloud engine. It performs an initial request on startup to gather a token, and soundcloud is hosted on aws.

**Comment by ghost** [comment]
The thing which bothers me is that why sound-cloud transmitting packets even though I didn't carried out any searches at all.

**Comment by asciimoo** [comment]
If it bothers you, you can remove that engine from `settings.yml`. It performs just a single front page download, so I don't think it leaks much information.

**Comment by ghost** [comment]
Should I remove this line

```
  - name : soundcloud
    engine : soundcloud
    shortcut : sc
```

I try to rebuild the docker without sound cloud and test once more

**Comment by asciimoo** [comment]
yes, and there is another engine which performs a HTTP request on startup: wolframalpha, perhaps you want to disable it too.
