### ISSUE TITLE
[feature-request] 

### ISSUE THREAD

**Issue by GambaJo** [searx/searx#1308]
From other search engines I'm used that already visited links are shown in a different color, so I can see, that I visited this link already.
maybe searx can do this too.

**Comment by Pofilo** [comment]
Well, it is already implemented !

For example in the oscar theme:
![image](https://user-images.githubusercontent.com/7527594/40626679-66e654f2-62ba-11e8-9e51-9cabc3521a69.png)

Or maybe you mean the green color ?

**Comment by GambaJo** [comment]
Ah, ok. I used oscar theme too, but logicodev dark.
Ok, then I have to use only logicodev without dark.

**Comment by asciimoo** [comment]
Well, then this is a bug in logicodev dark, I'll fix it. Thanks.
