### ISSUE TITLE
Pass morty key as bytes object to hmac

### ISSUE THREAD

**Issue by josch** [searx/searx#1310]
Currently, the example for `settings.yml` contains:

```
# searx supports result proxification using an external service: https://github.com/asciimoo/morty
# uncomment below section if you have running morty proxy
#result_proxy:
#    url : http://127.0.0.1:3000/
#    key : your_morty_proxy_key
```

This means that the `key` parameter is stored as a `str` Python object. But the `hmac()` function requires a `bytes` object instead:

https://docs.python.org/3/library/hmac.html#hmac.new

When following the example as it is written above, searx will throw the following error:

```
[...]
  File "/usr/lib/python3/dist-packages/searx/webapp.py", line 284, in proxify
    hashlib.sha256).hexdigest()
  File "/usr/lib/python3.5/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.5/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key
).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```

One possible workaround is to tag the key with `!!binary` in `settings.yml` like so:

```
    url : http://127.0.0.1:3000/
    key : !!binary |
      eW91cl9tb3J0eV9wcm94eV9rZXk=
```

The string `eW91cl9tb3J0eV9wcm94eV9rZXk=` is a base64 encoded version of `your_morty_proxy_key`. So if morty is started with `-key your_morty_proxy_key` then the above searx setting will work.

Please adapt the example in `settings.yml` to reflect this requirement of supplying the `key` parameter as binary data.

**Comment by mdosch** [comment]
@josch I am getting desperate now as I tried it several times with your workaround but I always get:
> error: invalid "mortyhash" parameter

Is this workaround still working for you?

**Comment by rachmadaniHaryono** [comment]
i just get notified about this

i made pr for new_hmac function here #1602 where it can receive either byte or string secret key

related issue #1600
