### ISSUE TITLE
h7jwxg5rakyfvikpi.onion Searx Instance Incrrectly Labeled

### ISSUE THREAD

**Issue by NicWow** [searx/searx#1315]
The instance "h7jwxg5rakyfvikpi.onion" is unresponsive. I have tried several exit nodes and it won't load. It also redirects to "7jwxg5rakyfvikpi.onion" when clicked on.

**Comment by kvch** [comment]
Could you please fix the link in the wiki page?

**Comment by unixfox** [comment]
The instance list got moved to searx.space.
@dalf I think you can close this issue.
