### ISSUE TITLE
Q: Installation in a different dir ? 

### ISSUE THREAD

**Issue by ronenrozner** [searx/searx#1317]
I run my own server (Debian 9/ Apache2), and I would like to install Searx in a different directory:
/Home/webadm/searx

/Home/webadm  is my server's root directory. I used the "classic" install, run as daemon with uwsgi, but when I access from another browser, I get searx's PAGE NOT FOUND, and the links (SEARX, about, preferences, go to to search page ) direct to myserver.com/Home/webadm/searx , instead of myserver.com/searx.

I created all the entries in Apache, as well as an Alias: /searx /Home/webadm/searx.

![screenshot_20180608_142304](https://user-images.githubusercontent.com/12706908/41181686-8846efa6-6b27-11e8-9e4a-81dc204727de.png)

am I missing something ?

**Comment by Pofilo** [comment]
Duplicate https://github.com/asciimoo/searx/issues/686.
