### ISSUE TITLE
Support for Open Semantic Search Integration

### ISSUE THREAD

**Issue by ghost** [searx/searx#1318]
We use Open Semantic Search, which is arguably the best free & open source intranet search engine out there. Adding a plugin that gets the results from the users local Open Semantic Search instance (for those who host a searx instance only I assume) would be of tremendous value. We are willing to sponsor the task, if necessary and there is interest. Thanks a lot.

**Comment by allendema** [comment]
This has been marked as done on v1.0.0 Milestone.

[https://github.com/searx/searx/projects/5](https://github.com/searx/searx/projects/5)
