### ISSUE TITLE
Engines cannot retrieve results

### ISSUE THREAD

**Issue by lewistapetest** [searx/searx#1319]
Hi
i made a private instance on digitalocean http://159.65.26.202:5000/
On science category i got error when i make a search
Engines cannot retrieve results:
microsoft academic (unexpected crash: 'results'), openairepublications (unexpected crash: name 'basestring' is not defined), crossref (unexpected crash: name 'basestring' is not defined), base (unexpected crash: cannot use a string pattern on a bytes-like object), openairedatasets (unexpected crash: name 'basestring' is not defined)

**Comment by lewistapetest** [comment]
openairepublications (unexpected crash: name 'basestring' is not defined), crossref (unexpected crash: name 'basestring' is not defined),openairedatasets (unexpected crash: name 'basestring' is not defined) is not fixe

**Comment by Pofilo** [comment]
Did you try with last commit ?

@asciimoo made https://github.com/asciimoo/searx/commit/f82ead3e303d75ba63a370dc038311e172e1330d while closing this issue.

**Comment by lewistapetest** [comment]
Yeah it solve base engine but i still get error on other engine
