### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by qu3stbaby** [searx/searx#1324]
I am following every step of [this](https://asciimoo.github.io/searx/dev/install/installation.html#with-apache).
Why am I getting this?
<img width="815" alt="1" src="https://user-images.githubusercontent.com/30405267/41525219-d04fc0e6-7312-11e8-8d53-694836f63f02.png">

**Comment by qu3stbaby** [comment]
I am using Apache2 on Ubuntu 16.04

**Comment by Pofilo** [comment]
Duplicate https://github.com/asciimoo/searx/issues/686.

**Comment by qu3stbaby** [comment]
uh,thank you @Pofilo
