### ISSUE TITLE
Closing issues

### ISSUE THREAD

**Issue by Pofilo** [searx/searx#1325]
There is right now 349 issues on Searx. A lot of them are already solved or even forgotten by the author (meaning we won't be able to fix or help him).

It would be nice to be efficient to close all those issues. This way, we will see the real issues (bug fixes, adding of engines or enhancement.

I'm a volunteer to make this job (reviving potential good issues by asking to the author and closing old issues if there is no answer after 2-3 weeks), however I don't have the rights to do that, maybe I can ping @asciimoo to close issues which need to be closed but it's not really relevant/efficient.

What do you think about that ? If we continue this way, we'll have more and more issues and it won't mean a lot of things ..

**Comment by dessalines** [comment]
There are also 42 open pull requests.

**Comment by asciimoo** [comment]
@Pofilo I added you as a collaborator, so from now you can close issues. Thank you for your helpful work on searx. =] <3

**Comment by Pofilo** [comment]
I'm sorry not to be able to work more on this project. Not enough time these days ...
