### ISSUE TITLE
Searx.me Footer Issue

### ISSUE THREAD

**Issue by ghost** [searx/searx#1326]
I want to let you know that on Searx.me the home page is taller than necessary and thus you have to scroll down to see the entire footer.

I checked other instances of Searx and this doesn't happen on them.

I am reporting this purely for the benefit of Searx.me.

**Comment by Pofilo** [comment]
This is due to the last line:

> Support the development and maintenance of searx

You're right reporting this, @asciimoo should fix this easily ! (and the hidden line is quit important for him I suppose !)

**Comment by asciimoo** [comment]
Fixed, thanks!

**Comment by asciimoo** [comment]
@infosisio could you provide a better fix for this issue?

**Comment by ghost** [comment]
@asciimoo I can put it on my to-do list.
