### ISSUE TITLE
rethink bangs

### ISSUE THREAD

**Issue by dessalines** [searx/searx#1327]
Instead of bangs searching the metasearch engines, it would be wonderful if bangs were **redirects** to use that sites own search engine. Duckduckgo has ~12k bangs... this is something that wouldn't be feasible or necessary for a metasearchengine.

You could simply added a json file that looks something like:

```
site: [
{
  name: "amazon",
  shortcuts : ["a", "amazon"],
  url: "https://www.amazon.com/s/?url=search-alias%3Daps&field-keywords=%s"
  ...
},
```

I'm switching from duckduckgo, and there are many bangs that I can no longer use now: `!idope` or `!tpb` for torrents, `!w` for wikipedia, `!yt` for youtube, `!a` for amazon, `!gh` for github...

The nice thing is that users could just add new urls to this json file in a clean way. 

edit: Also the list of bangs should all be in one place, right now its spread across many, I had no idea `!stackoverflow` worked until I randomly tried it.

**Comment by dessalines** [comment]
I'm going to close this and post my comments there.

**Comment by virtadpt** [comment]
What does that do to those of us who use the search API extensively?  Getting a redirect to a site means that we don't get search results from that search engine, which pretty much hoses everything.

**Comment by dessalines** [comment]
> Getting a redirect to a site means that we don't get search results from that search engine

What? Completely wrong. Try this search, and you'll find that yes, it does give you search results from that engine: https://duckduckgo.com/?q=!so+best+sorting+algorithm

**Comment by virtadpt** [comment]
Wait a minute.  You said that it would be a good idea to send a redirect to a site when a !search is used.  That would, if I'm reading you correctly, the search API would return a redirect link instead of search results.  Is that what you meant?
