### ISSUE TITLE
 duckduckgo (timeout)

### ISSUE THREAD

**Issue by SearxDuck** [searx/searx#1334]
Since a few days DDG doesn't give results, probably because they changed things.

Correct search url is https://duckduckgo.com/html?q={query]
Currently it is without q= (https://github.com/asciimoo/searx/blob/master/searx/engines/duckduckgo.py) and doesn't give results.

Also, browsers without JS directly use the html version, previously you had to manually redirect to it. (don't know if that matters)

Hope this can be solved!

**Comment by Pofilo** [comment]
Well, the URL is formatted after the function you see in `duckduckgo.py`.
You can verify it by yourself adding some logs.

The request done for *test* is in my case like this:
`https://duckduckgo.com/html?q=test&kl=us-en&s=0&dc=0`

If I copy it in my browser, it does work (the result are given).
If you try this request with a wget or curl, you will never get any answer.

The same happens with `https://duckduckgo.com/html?q=test`.

Do you have some info about a change of DuckDuckGo ?

**Comment by MarcAbonce** [comment]
I think it's related to the HTTP headers being sent. If so, then #1330 or #933 should fix this.
At least that made it work in a local test.

**Comment by josch** [comment]
From my log:

```
WARNING:searx.search:engine timeout: duckduckgo
[pid: 198|app: 0|req: 1/1] 10.0.0.1 () {50 vars in 1377 bytes} [Tue Aug  7 07:29:25 2018] GET /search?q=test => generated 49608 bytes in 6568 msecs (HTTP/1.1 200) 2 headers in 82 bytes (1 switches on core 0)
ERROR:searx.search:engine duckduckgo : HTTP requests timeout(search duration : 18.096888065338135 s, timeout: 6.0 s) : ConnectTimeout
```

But I have another funny observation. When I run on the same host that searx is installed:

```
$ curl --verbose --connect-timeout 30 'https://duckduckgo.com/search?q=test'
*   Trying 79.125.105.113...
* TCP_NODELAY set
* After 14986ms connect time, move on!
* connect to 79.125.105.113 port 443 failed: Connection timed out
*   Trying 176.34.155.23...
* TCP_NODELAY set
* After 7377ms connect time, move on!
* connect to 176.34.155.23 port 443 failed: Connection timed out
*   Trying 46.51.179.90...
* TCP_NODELAY set
* After 3688ms connect time, move on!
* connect to 46.51.179.90 port 443 failed: Connection timed out
* Failed to connect to duckduckgo.com port 443: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to duckduckgo.com port 443: Connection timed out
```

But when I run the same command from my home network then everything is fine.

Maybe duckduckgo added my host to a blacklist?
