### ISSUE TITLE
Open Access DOI resolver option outputs malformed URL

### ISSUE THREAD

**Issue by e01c-dat10** [searx/searx#1335]
outputs 
oadoi.org##.####/…
instead of
https://oadoi.org/##.####/…

**Comment by Pofilo** [comment]
Is your `searx/settings.yml` configured like that ?

```
    oadoi.org : 'https://oadoi.org/'
    doi.org : 'https://doi.org/'
    doai.io  : 'http://doai.io/'

default_doi_resolver : 'oadoi.org'
```

**Comment by Popolon** [comment]
I have the same issue. This part of the settings.yml is the default one, and I have :

```
doi_resolvers :
  oadoi.org : 'https://oadoi.org/'
  doi.org : 'https://doi.org/'
  doai.io  : 'http://doai.io/'

default_doi_resolver : 'oadoi.org'
```

**Comment by Popolon** [comment]
By disabling "Avoid paywalls by redirecting to open-access versions of publications when available" in Preferences => plugins => Open Access DOI rewrite, the url work correctly on http://dx.doi.org/xx.xxx/... So the problem seem to be only present in the case of default oadoi.

**Comment by Popolon** [comment]
I'm don't know well python, but error seems to be in get_doi_resolver function (searx/plugins/oa_doi_rewrite.py)

If i replace return in this function like this, it works fine:
```
#    return doi_resolver
    return 'https://aodaoi.org/'
```

**Comment by dalf** [comment]
I'm not sure it will solve anything, but can you try this : 
- replace ```doi_resolvers = settings['default_doi_resolver']```
- by ```doi_resolver = settings['default_doi_resolver']```
in searx/plugins/ao_doi_rewrite.py (and keep ```return doi_resolver``` )

**Comment by Popolon** [comment]
I was wrong in the previous comment (and edited it) fir the name of the plugin, that's oa_doi_rewrite.py, not ao_doi_rewrite.py. I tried your trick it doesn't work, same result. Need to understand more deeply the structure and functions used in this one.
