### ISSUE TITLE
Allow Cross-Origin Resource Sharing

### ISSUE THREAD

**Issue by MrNuggelz** [searx/searx#1336]
Could you add support for Cross-Origin Resource Sharing? I'm creating a custom startpage in javascript and want to make searches by querying searxs json api.

**Comment by arthurmougin** [comment]
its not a searx issue, but the choise of hosters to allow or not the use of their hosted version by others...
Maybe your request should be to add a list of Cross origin ressources sharing public instances :) that's something that could be done there.

edit : you can use curl php to overpass the cors issue,
in your situation, you call the php file on your server, the file do the curl request and return you the search result

**Comment by asciimoo** [comment]
I agree with @arthurmougin

**Comment by zicjin** [comment]
@arthurmougin @asciimoo If you do not enable cors in this project code, such as using flask_cors. How can hosters be configured to support cross-domain access?

**Comment by arthurmougin** [comment]
@zicjin the only way I know is this one : https://enable-cors.org/server_apache.html
I didn't know about flask_cors :/
