### ISSUE TITLE
Change Searx Proxy

### ISSUE THREAD

**Issue by astrowalker2013** [searx/searx#1339]
Hi,

I haved blocked by google when i search with google search
google (unexpected crash: CAPTCHA required)

how to workaround this issue, for me i want to change manualy the proxy.
In my infra the proxy is used with user password.

I see in the setting.yml : 
# proxies :  ...
how to use that
how to change in fly when we used docker.

**Comment by ghost** [comment]
I will second this.. Can some one explain how to use proxies or make the whole process simple in searx?

**Comment by Pofilo** [comment]
If you wanna use the Morty proxy, the doc is here:
[https://asciimoo.github.io/searx/admin/morty.html](https://asciimoo.github.io/searx/admin/morty.html)

If you wanna use a "classic" proxy, as shown in the comments of `searx/settings.yml`, the doc is here:
[http://docs.python-requests.org/en/latest/user/advanced/#proxies](http://docs.python-requests.org/en/latest/user/advanced/#proxies)

The only things you may configure should be in `searx/settings.yml`.

**Comment by Pofilo** [comment]
A new docker repo can help you: https://github.com/searx/searx-docker.
Feel free to reopen the issue if needed.
