### ISSUE TITLE
[Engine] Unsplash.com - Image search

### ISSUE THREAD

**Issue by ghost** [searx/searx#1340]
This is a great source of no strings attached quality photographs. They have a huge collection and there's no restrictions on them (free for personal or for profit). All they ask is that, if you desire, credit be given to the photographer.

https://unsplash.com/developers
https://unsplash.com

**Comment by dadosch** [comment]
https://unsplash.com/search/photos

**Parameters**
`query` 	Search terms.
`page`	Page number to retrieve. (Optional; default: 1)
`per_page` 	Number of items per page. (Optional; default: 10)
`collections` 	Collection ID(‘s) to narrow search. If multiple, comma-separated.
`orientation` 	Filter search results by photo orientation. Valid values are landscape, portrait, and squarish.


From: https://unsplash.com/documentation#search-photos

**Comment by Venca24** [comment]
Actually implemented in PR #1412

**Comment by allendema** [comment]
Could be closed as the issue is solved.
