### ISSUE TITLE
Searx.me Person Information Missing Picture 

### ISSUE THREAD

**Issue by ghost** [searx/searx#1341]
I noticed recently that if you search for example "Bill Gates" or another famous person, if you check the right area where there is Wikipedia info and a picture at the top, the picture is missing, it is corrupted.

**Comment by bourrel** [comment]
Indeed I have the same problem on a v14 instance but [laquadrature](https://searx.laquadrature.net/) doesn't have this problem and is currently running searx v13.1.

After a quick look it might come from [this line](https://github.com/asciimoo/searx/blob/e5def5b0191a36315d300457cdfdf68aebbc9a4c/searx/engines/wikidata.py#L40). I think the `filename` variable is incorrect, it should stop after the type (`.jpg`in my test) but seems to be a bit longer and contains some metadata about the image.

I'll try to take a deeper look later.
