### ISSUE TITLE
Google SafeSearch via fixed IP

### ISSUE THREAD

**Issue by ghost** [searx/searx#1343]
Hi,
I use searx.me and noticed that safe search is not supported for google (and many other search engines). I think Safe Search is a really cool feature for wide deployment and engines like Google seem to do it pretty accurately.

As an enhancement, Google provides an IP address, through which all search queries are forced with the safe search option. The IP is 216.239.38.120 (for more info see [here](https://support.opendns.com/hc/en-us/articles/227986807-How-to-Enforcing-Google-SafeSearch-YouTube-and-Bing)). Please note that Bing provides a similar functionality.

Can searx be setup so that search queries to Google are sent to this IP, when the SafeSearch feature is turned on?

**Comment by unixfox** [comment]
Safe search is supported in Searx.
