### ISSUE TITLE
how to get JSON data using wget?

### ISSUE THREAD

**Issue by waldenn** [searx/searx#1347]
I was wondering why eg. this JSON requesting URL:
  https://searx.eu/search?q=water&pageno=1&format=json

Returns the JSON data perfectly fine, but when I use that same URL in wget (or some other non-browser client), I get HTML results.

These are the HTTP headers for a good request:

> https://searx.eu/search?q=water&pageno=1&format=json
> 
> GET https://searx.eu/search?q=water&pageno=1&format=json
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en
> 
> HTTP/1.1 200 OK
> Server: nginx/1.10.3 (Ubuntu)
> Date: Mon, 16 Jul 2018 15:08:02 GMT
> Content-Type: application/json
> Content-Length: 10308
> Connection: keep-alive
> X-Cache-Status: HIT

I'm probably overlooking setting some obvious HTTP headers, but which ones?

Thanks for an awesome project!

**Comment by asciimoo** [comment]
It works for me. `curl https://searx.eu/search\?q\=water\&pageno\=1\&format\=json` produces the desired results.

**Comment by waldenn** [comment]
Yes, for me too. However, I really want to do a fetch() in JS (from a CORS proxy) and am seeing the same issue there as with Wget. Which is why I referenced it (I had not tested with Curl though).

I would like to understand why Wget is failing and Curl succeeding. Something seems weird when the exact  same GET returns different results. What is the difference here?

**Comment by asciimoo** [comment]
Wget gives me the same output (`wget https://searx.eu/search\?q\=water\&pageno\=1\&format\=json -O -`). What is that "CORS proxy"?

**Comment by waldenn** [comment]
Oh it seems to be a character escaping issue. Wget works when you escape the characters. Thanks! Closing this :)
