### ISSUE TITLE
Error Images searx

### ISSUE THREAD

**Issue by sachaz** [searx/searx#1348]
google images (unexpected crash: No JSON object could be decoded), 500px (unexpected crash: 'photos')

**Comment by gr01d** [comment]
confirming on 0.14.0: Engines cannot retrieve results:
google images (unexpected crash: No JSON object could be decoded), 500px (unexpected crash: 'photos')

**Comment by r1bnc** [comment]
https://github.com/asciimoo/searx/issues/1338

**Comment by sachaz** [comment]
sorry for already reported issue

**Comment by Pofilo** [comment]
Duplicate #1338.
