### ISSUE TITLE
yacy search with more than 1 searchword fails

### ISSUE THREAD

**Issue by viisauksena** [searx/searx#1349]
reproducable, 
i guess its because the generated link has white spaces instead of + signs or %20 

in my yacy search mashine log i can see the request (and that it takes only milliseconds) 
working examples:
... yacysearch.html?query=fritten+und+crypto
http://5.9.118.78:8090/yacysearch.html?query=fritten%20und%20crypto&resource=local
also in yacy not working, but processed in searx

one word searches works like a charm

**Comment by kvch** [comment]
I cannot reproduce this with my local yacy instance. What is the error you see?
I had to wait quite long to get results. I set engine timeout to 25.0, so I could get the same results as yacy shows. But for single word searches the default 3.0 is enough.
