### ISSUE TITLE
[Searx.me] Certificates expired

### ISSUE THREAD

**Issue by memorable111** [searx/searx#1350]
THE CERTS HAVE EXPIRED
FIX  IT
DO IT NOW

**Comment by macleod-ee** [comment]
The https certs on the hosted instance of searx on serx.me have expired. If the owner of the website needs to update check out LetsEncrypt, just in case they haven't stayed in the loop as well as others. Open sourced by the EFF if I remember correctly. 

tl;dr **https certificates on the hosted instance of searx.me have expired, nothing is wrong with the code itself**

**Comment by Pofilo** [comment]
@memorable111 caps lock is not necessary. Especially when you use a free and open-source software. Thanks !

As long as the certs are no longer valid, you can still use one of the multiple instances available here:
[https://github.com/asciimoo/searx/wiki/Searx-instances](https://github.com/asciimoo/searx/wiki/Searx-instances)

**Comment by asciimoo** [comment]
Thanks for the kind notification, it's fixed =)
