### ISSUE TITLE
socket.error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by AdamDenoon** [searx/searx#1356]
I'm attempting to run searx via Docker.

### Steps to reproduce:

Run:
`git clone https://github.com/asciimoo/searx.git`
` cd searx`
`vim searx/settings.yml` <-- Changed secret key, port to 80, debug to True, saved/closed vim
`vim docker-compose.yml`

My docker-compose.yml is as follows:

```yml
version: '2'
services:
    searx:
        build:
            context: .
        container_name: searx
        environment:
            - BASE_URL="https://mydomain.tld"
```
(saved/closed vim)

`vim Dockerfile` <-- Changed EXPOSE to 80, saved and closed vim
`docker-compose up -d`

(Wait for image to build and container to start)

`docker container logs -f searx` <-- yields the below output:

```
DEBUG:searx:read configuration from /usr/local/searx/searx/settings.yml
INFO:searx:Initialisation done
INFO:searx.plugins.https_rewrite:29 rules loaded
DEBUG:searx.webapp:static directory is /usr/local/searx/searx/static
DEBUG:searx.webapp:templates directory is /usr/local/searx/searx/templates
DEBUG:searx.webapp:starting webserver on 80:0.0.0.0
 * Serving Flask app "webapp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "searx/webapp.py", line 929, in <module>
    run()
  File "searx/webapp.py", line 883, in run
    threaded=True
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 795, in run_simple
    s.bind(get_sockaddr(hostname, port, address_family))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied
```

Then container dies.

Is there any way to get more information on what is breaking? Are there any ideas on what to change?

**Comment by dalf** [comment]
The port 80 is not allowed to be used because only root can use ports <1024, and searx runs with a dedicated user inside the docker instance. 

You should keep using port 8888 inside the docker instance, and map the port 80 from the host to the port 8888 of the docker instance when you start the instance.

But the most usual use case is to have different searx docker instance with nginx /apache as a reverse proxy.

**Comment by AdamDenoon** [comment]
I'm using nginx (docker companion) as a reverse proxy. I will use its VIRTUAL_PORT environment variable to get it to listen on 8888. Thanks, and I'll let you know :)

**Comment by AdamDenoon** [comment]
That was the issue 👍 I changed 80 back to 8888 in both places and added 8888 as the virtual port in my reverse proxy, and it came up perfectly. You rock!
