### ISSUE TITLE
Show search results only in single language

### ISSUE THREAD

**Issue by dimqua** [searx/searx#1358]
Can you please make it possible to view the results only in user-defined language? If selected search engine supports it.

Besides that would be nice to have a possibility to limit a list of search engines used for searching in selected language. For example, Yandex is usually better for search in Russian and not as great for other languages. DuckDuckGo is not so great for all languages either, since it mostly uses Bing and Yandex. Qwant has its own index only for French websites and uses Bing for others.

**Comment by return42** [comment]
> Can you please make it possible to view the results only in user-defined language? If selected search engine supports it.

discussed in https://github.com/asciimoo/searx/issues/1838

> Besides that would be nice to have a possibility to limit a list of search engines used for searching in selected language.

If interested any longer please open a separate issue / thanks!
