### ISSUE TITLE
The following engines don't work

### ISSUE THREAD

**Issue by dimqua** [searx/searx#1361]
* etymonline
* gigablast (#1293)

**Comment by Pofilo** [comment]
For dictzone and mymemory translated, try `en-fr search`.
I don't know for the others.

**Comment by dimqua** [comment]
Am I correct that `archive.is` and `etymonline` engines are already removed from [master tree](https://github.com/asciimoo/searx/tree/master/searx/engines)? If so, please close this issue.

**Comment by stef204** [comment]
duckduckgo and qwant also seem to have stopped working. i see in the most recent settings.zml that both are disabled by default.  any idea is this can be addressed and fixed?

**Comment by kvch** [comment]
No, they are not removed from the engines.
Archive.is seems to work for me with the following queries: `"asciimoo.github.io"` and `"fsf.org"`.
Etymonline doesn't work for me either.
