### ISSUE TITLE
Cannot connect to proxy

### ISSUE THREAD

**Issue by songproducer** [searx/searx#1362]
I followed the guide https://github.com/asciimoo/searx/wiki/How-to-create-and-configure-SSL

but now whenever I search for anything I get a bunch of stacktraces like this:
It shows this error:

> Error! Engines cannot retrieve results.
> 
> google (request exception), wikidata (request exception), wikipedia (request exception), duckduckgo (request exception), startpage (request exception), reddit (request exception) 

and

> Traceback (most recent call last):
>   File "/var/www/searx/searx/search.py", line 104, in search_one_request_safe
>     search_results = search_one_request(engine, query, request_params)
>   File "/var/www/searx/searx/search.py", line 83, in search_one_request
>     response = send_http_request(engine, request_params)
>   File "/var/www/searx/searx/search.py", line 67, in send_http_request
>     return req(request_params['url'], **request_args)
>   File "/var/www/searx/searx/poolrequests.py", line 147, in post
>     return request('post', url, data=data, **kwargs)
>   File "/var/www/searx/searx/poolrequests.py", line 109, in request
>     response = session.request(method=method, url=url, **kwargs)
>   File "/home/leo/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/leo/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/leo/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
>     raise ProxyError(e, request=request)
> requests.exceptions.ProxyError: HTTPSConnectionPool(host='startpage.com', port=443): Max retries exceeded with url: /do/search (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))

**Comment by asciimoo** [comment]
Seems you have network errors (`RemoteDisconnected('Remote end closed connection without response')`. Check your proxy or your proxy config.

**Comment by unixfox** [comment]
@songproducer Do you still have an issue with configuring a proxy on Searx? If not then can you close this issue?

**Comment by unixfox** [comment]
Proxy issue, closing the issue because I cannot replicate the problem.
