### ISSUE TITLE
[query] One instance served at multiple domains

### ISSUE THREAD

**Issue by lofidevops** [searx/searx#1364]
Is it possible to run one instance of Searx, accessible at multiple domains? For example, searches at searx.example.com and searx.example.org are both processed by the same instance (and the user remains at their original domain for the duration of their session).

**Comment by asciimoo** [comment]
You have multiple options:
 - Domain redirect to the main host
 - HTTP redirect to the main host
 - Webserver configuration which forwards the actual hostname to searx (similar to https://asciimoo.github.io/searx/dev/install/installation.html#from-subdirectory-url-searx)
 
Probably setting the `base_url` in `settings.yml` to `/` also handles the domain differences, but it isn't tested.
