### ISSUE TITLE
DDG and Qwant no longer working

### ISSUE THREAD

**Issue by stef204** [searx/searx#1365]
duckduckgo and qwant also seem to have stopped working. iI see in the most recent settings.zml that both are disabled by default.  Any idea is this can be addressed and fixed?

**Comment by dalf** [comment]
- duckduckgo seems ok
- qwant : the API seems to have changed.

https://github.com/asciimoo/searx/blob/master/searx/engines/qwant.py#L31
should be replaced by
```python
url = 'https://api.qwant.com/api/search/{keyword}?count=10&offset={offset}&f=&{query}&t={keyword}&uiv=4'
```

**Comment by ghost** [comment]
Yeah I also noticed they changed the lite page. Most likely they did some major changes.

**Comment by stef204** [comment]
@dalf Thanks for feedback.  The new url you propose does not work for me.
Can you please check the url again, make sure it is correct?

**Comment by stef204** [comment]
@dalf 
The new url fixes Qwant, thanks.
DDG still broken here.

**Comment by asciimoo** [comment]
Qwant is fixed (thx @dalf) and ddg works well for me on my local instance and on searx.me too.
