### ISSUE TITLE
Public Instance EC2 Problems

### ISSUE THREAD

**Issue by masterzebra** [searx/searx#1367]
Hello
I want setting up a public instance on Amazon EC2, whith the free options.
I done the steps on wiki
But when i wrote:      (searx-ve) $ python searx/webapp.py
I recived this:
 * Serving Flask app "webapp" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

Any solution??
Or any help to install the public instance, steps or videos?

And other question, trying  $sudo sed -i -e "s/debug : True/debug : False/g" searx/settings.yml
i recived : [sudo] password for searx:
but any password that i have tryed fail, what password could be?

Thank u soo much

**Comment by bourrel** [comment]
This is not a problem, searx is just in development mode.

To change for production just replace line 2 in settings.yml with : `debug: False`.

**Comment by masterzebra** [comment]
Hi, thank u soo much for ur help

Im going to install with docker (i did with classic) and take the correct configuration on settings.yml

Any suggestion to run a public instance it will be welcome ;)

Thanks again

**Comment by masterzebra** [comment]
Well
I have done with dockers and run perfect, i have used hoellen/docker.

Now i continue traying to run a public instance

I suppose that i must install nginx, isnt it?

And other question, i have read some about morty and filtron... i should install one of them too? With nginx or with out nginx?

Thanks for help, im not a expert

**Comment by Pofilo** [comment]
A new docker repo can help you: https://github.com/searx/searx-docker.
Feel free to reopen the issue if needed.
