### ISSUE TITLE
[engine] Invidio.us

### ISSUE THREAD

**Issue by dimqua** [searx/searx#1372]
Invidious is similar to what [HookTube](https://hooktube.com/) used to be, but doesn't use the YouTube API. It's also open source (AGPLv3).

https://www.invidio.us/

**Comment by atomGit** [comment]
https://invidious.snopyta.org/ is another instance of Invidious

snopyta.org offers a bunch of cool and privacy-enhanced services for those interested

**Comment by cy8aer** [comment]
https://github.com/omarroth/invidious/wiki/API
