### ISSUE TITLE
YouTube and Subtitleseeker engines don't work

### ISSUE THREAD

**Issue by dimqua** [searx/searx#1373]
They do not provide any results. :-(

**Comment by dimqua** [comment]
There is [subtitleseeker.gq](https://subtitleseeker.gq/), at least. But it seems like a clone of more popular [subscene.com](https://subscene.com/).

**Comment by theel0ja** [comment]
`subtitleseeker.gq` is down. subscene.com still works.

**Comment by dalf** [comment]
YouTube engine has been fixed by PR #1544
