### ISSUE TITLE
Ecosia  adding 

### ISSUE THREAD

**Issue by ghost** [searx/searx#1377]
Ecosia  adding  https://www.ecosia.org/

**Comment by dimqua** [comment]
Why not use Bing engine instead?

**Comment by dalf** [comment]
Using searx, the Ecosia ads won't be shown which defeat the purpose of Ecosia : 
https://en.wikipedia.org/wiki/Ecosia#Search_engine

see #880

**Comment by asciimoo** [comment]
I agree with @dalf.
