### ISSUE TITLE
Rss Feed Search

### ISSUE THREAD

**Issue by themushmouth** [searx/searx#1379]
Is it possible to get a rss search engine feed search for searx?

**Comment by asciimoo** [comment]
Do you mean getting the search results in RSS format? If so, it's implemented, just use `format=rss` search parameter: https://yoursearx.tld/?q=!wp%20searx&format=rss

**Comment by yphil-dev** [comment]
This used to work, but now produces a EPROTO error. Maybe a choice on the instances network infra. but all of them at the same time?

**Comment by unixfox** [comment]
Already implemented.
