### ISSUE TITLE
[Suggestion] docker-public-instance

### ISSUE THREAD

**Issue by masterzebra** [searx/searx#1382]
Hi

I was thinking that could be a great idea to expand searx use, make a docker to run public instances.

With all necesaries element, seax engine, nginx, morty, filtron... inside one or more docker.

To be honest its soo hard install all elements if u arent a expert in this specific area, and this idea could help other people to run their public instances and increase searx use.

Thanks

**Comment by Pofilo** [comment]
A new docker repo can help you: https://github.com/searx/searx-docker.
Feel free to reopen the issue if needed.
