### ISSUE TITLE
KDE Krunner support

### ISSUE THREAD

**Issue by rawlife56** [searx/searx#1383]
Krunner is one of the most powerful search feature in Linux DE world. I've tried to add searx shortcut but it simply fails to search. All other search engines work well. Anybody using it or have predefined addresses for it work ?
 Instances tried- searx.me, searx.xyz

**Comment by asciimoo** [comment]
What is required to be able to search with KDE Krunner?
Searx has opensearch support, and you can use the URL `https://searx.me/search?q={searchTerms}` as a base search URL.

**Comment by dadosch** [comment]
For me, it works fine with my own instance. I use `https://myinstance.tld/searx?q=\{@}` (It's in a subfolder)
