### ISSUE TITLE
Enhancement: update url with query for every search

### ISSUE THREAD

**Issue by doronbehar** [searx/searx#1393]
Most web search engines (Google, DuckDuckGo..) update the URL when a user hits the search button (or when he performs a search through his browser address bar as well. I'm talking about the URL with the `?q=...&` noted under the *Links*  `<div>` at the bottom right which works fine but doesn't show itself by default when performing a search.

It could be useful when one wants to copy and paste his search - it's much easier to do so from the browser's address bar (keyboard shortcuts) then from the web page itself.

Making the URL change automatically could remove the need for the *Links* div since one can just copy and paste the URL from one browser (or tab) to another, again - just like with every web search engine.

Besides that, great software you made here, thanks a lot!

**Comment by dalf** [comment]
The fact the URL does not change is on purpose : your browser history won't contain the different queries you have made.

But you can revert to the usual behaviour : go to the preferences, and change the Method parameter to GET.

**Comment by atomGit** [comment]
you can just change `"method": "POST",` to `"method": "GET",` in your browser search config as well - if you're using Firefox, check out [mozlz4-edit](https://addons.mozilla.org/en-US/firefox/addon/mozlz4-edit/)

**edit:** note however that using GET raises a potential privacy issue

**Comment by unixfox** [comment]
Use method GET if you want to keep the queried search term.
