### ISSUE TITLE
Please make searx compatible with python3

### ISSUE THREAD

**Issue by yurivict** [searx/searx#1396]
FreeBSD disabled ```searx``` for python3 with ```py-searx is not compatible with python3``` note.

Please make sure it works with python3.

**Comment by kvch** [comment]
Do you have an exact error which shows up when running with Python 3?
In v0.12.0 we added support for Python 3 and stayed compatible with Python 2.

**Comment by yurivict** [comment]
The port was labeled as py27-only due to some dependency, not due to errors in searx.
Closing.

**Comment by kvch** [comment]
Thank you for figuring it out!
