### ISSUE TITLE
Small mistake in install instructions, nginx path.

### ISSUE THREAD

**Issue by tmikaeld** [searx/searx#1403]
Create the configuration file /etc/nginx/sites-**available**/searx with this content:

Should be:

Create the configuration file /etc/nginx/sites-**enabled**/searx with this content:

Otherwise, only Welcome to Nginx! will show if following the install to the letter.

**Comment by Pofilo** [comment]
The documentation is correct (and is similar for apache), if I search `enable vhost nginx`, the first link I find is this one, it is well explained !

[https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04)

**Comment by tmikaeld** [comment]
The problem is that the sites are **not enabled** when they are in /sites-available/ and you can see in the tutorial that you linked to, that he symlinks from the sites-available towards sites-enabled to enable the sites.

![image 2018-09-26 at 10 39 20 pm](https://user-images.githubusercontent.com/907195/46107936-0b850400-c1dd-11e8-8b53-8e29d504b86f.png)


So if that's what you want for searx, then:

`sudo ln -s /etc/nginx/sites-available/searx /etc/nginx/sites-enabled/searx`

Should be added to the instructions.

**Comment by tmikaeld** [comment]
There is also different install instructions on github readme than on the github pages.

I'm specifically talking about this one:

https://asciimoo.github.io/searx/dev/install/installation.html#installation

That is linked from here: https://asciimoo.github.io/searx/index.html

**Comment by Pofilo** [comment]
I agree the file needs to be in `enabled` at the end (directly or with a link), but it is a good practice to put it in `available` and make a link into `enabled`.

I suggest you to read the *PS* of this post: [https://serverfault.com/a/870618](https://serverfault.com/a/870618) :)

**Comment by tmikaeld** [comment]
@Pofilo Interesting discussion. So we can conclude that:

`sudo ln -s /etc/nginx/sites-available/searx /etc/nginx/sites-enabled/searx`

Should be added to the docs.

**Comment by kvch** [comment]
@tmikaeld do you mind opening a PR with that change to branch `gh-pages`? :)

**Comment by tmikaeld** [comment]
@kvch Done.

**Comment by return42** [comment]
FWIW: PR #1803 is a revise of the installation instructions: https://return42.github.io/searx/admin/index.html
