### ISSUE TITLE
"search error"

### ISSUE THREAD

**Issue by slackyman76** [searx/searx#1405]
Hi,

(SORRY FOR MY POOR ENGLISH)

sometimes I see an error message "**search error**" (I'm from Italy and I get "**errore di ricerca**", so I guess that the English equivalent is "search error" or something like this). It happens whatever I try to search. Usually, the problem is solved within one minute, but in some cases it can be annoying. 
This happens if I use searx.me. If I use an alternative instance it usually works. Can it be a searx.me overloading problem?

This is the link to the screenshot: **https://ibb.co/jtDHPK**

Since I am at it, I noticed that some "offline" instances are working, e.g. searx.ch. Is it possible to have an updated list?

Thank you! :-)

**Comment by antonio-antuan** [comment]
I've got the same error; 500 on http request.
Here is form data:
category_general=on&language=en-US&q=inoreader&time_range=

**Comment by kvch** [comment]
@slackman76 what was your query? have you experienced this problem with the same query on a different instance?

**Comment by kvch** [comment]
@slacykman76 what was your query? have you experienced this problem with the same query on a different instance?

**Comment by slackyman76** [comment]
Hi Noémi,

thank you for answering.

I don't remember my queries... I tried several keywords for several
searches, but for about one or two minute(s) *searx.me <http://searx.me>*
refused to give me results, displaying that error message. Then it started
to work again but sometimes it happens that I have to switch to a different
instance. Not a big issue, but I would like to know if that issue can be
related to a *searx.me <http://searx.me>* overload.

Cheers,

Bert

Il giorno mar 9 ott 2018 alle ore 22:58 Noémi Ványi <
notifications@github.com> ha scritto:

**Comment by unixfox** [comment]
This issue is kinda old and searx.me doesn't seems to still have this issue right now when I tested it.
@kvch @dalf What do you think about closing this issue?

**Comment by Pofilo** [comment]
You are right, thanks.
