### ISSUE TITLE
search error should repeat the search query on the text box

### ISSUE THREAD

**Issue by fauno** [searx/searx#1407]
whenever there's a search error, you get shown a red alert box saying "Error! search error" and the search box is empty, making you re-type the query.  would it be possible to show the search query again instead?  it's annoying :P

**Comment by mrozo** [comment]
can you describe the problem? how to reproduce it?

**Comment by Pofilo** [comment]
It should let the request, at least I have it. Which version of searx and which browser are you using ?

**Comment by fauno** [comment]
i wouldn't know how to reproduce it because it's an internal error, but
these are the steps:

* go to searx.me
* enter a search query
* searx.me fails with "error"
* search box is empty

it's a POST request so the query isn't part of the URL
