### ISSUE TITLE
Porn too high on your ranking list

### ISSUE THREAD

**Issue by WiseWomanVP** [searx/searx#1410]
When I type in "this little light motions" in order to find the motions for the church song "This little light of mine", I get  pornhub.com in first place. I've seen this with a lot of other searches. And so many searches turn up pinterest, that I can't use without signing up. Anyway I can restrict sites for my searches? I've found lots of places to tweak, but no place to keep pornhub and pinterest out of the solutions.

**Comment by veloute** [comment]
in the top right corner click preferences, then turn on safe search to either moderate or strict and see if that fixes your problem.

**Comment by kvch** [comment]
Which engine returns these results?

**Comment by WiseWomanVP** [comment]
Engine: https://searx.me/
Good, moderate is good enough to reduce the porn hits to just one (at the top), strict makes them all go away. Now I get lots of dictionary suggestions at the top :) Thanks!

**Comment by veloute** [comment]
no problem, glad to help. :+1:

**Comment by unixfox** [comment]
@WiseWomanVP Can you still reproduce the bug? I used the google engine and I can't find any porn results when searching for "this little light motions".

**Comment by unixfox** [comment]
Enable safe-search in the settings if you don't want to have porn results.
