### ISSUE TITLE
File search gives error.

### ISSUE THREAD

**Issue by ghost** [searx/searx#1415]
Error message:

```
 Error! Engines cannot retrieve results.

piratebay (timeout)

Please, try again later or find another searx instance.
```

I hope it quits after a single failure or only searches piratebay. Havent glanced the code though.

If it only searches piratebay, adding some other torrent and file search sites may fix the problem.

**Comment by ZEROF** [comment]
Same error here, once when clicked on "File" search.

**Comment by wonnetz** [comment]
In Preferences/Engines/files, the default file search engines are PirateBay and Torrentz. These websites frequently go down and thus the file search option will fail. 

You can change the Search Engine Preferences for Files to a couple different other things. I added the Google Play Search engine and tested to see if it would search for Clash Royale and it worked.

**Comment by unixfox** [comment]
Thepiratebay works if you set it to a working instance. I unfortunately cannot paste a URL here because it would be illegal but just search for "thepiratebay proxy" if you are interested.
