### ISSUE TITLE
unexpected crash: CAPTCHA required

### ISSUE THREAD

**Issue by stemy2** [searx/searx#1425]
Hello,

My usual instance is unusable because instead of search results, i have this error message.

**Comment by Pofilo** [comment]
Is it happening with google as engine ?
If yes, it is a duplicate of a lot of other issues ;)

**Comment by stemy2** [comment]
Yes.

**Comment by miicha** [comment]
duplicate of https://github.com/asciimoo/searx/issues/729
Also see my comment there https://github.com/asciimoo/searx/issues/729#issuecomment-433948084
You can find a nice overview with load times and SSL ratings here: https://stats.searx.xyz/

**Comment by micah** [comment]
@miicha - I'm wondering how you were able to determine that filtron was not working? Is there a log somewhere that was showing you that this particular filter was bugged?

**Comment by miicha** [comment]
@micah - I set very strict rules with different error messages for blocked reqests - something like:
```
"name": "IP limit",
        "interval": 60,
        "limit": 2,
        "stop": true,
        "aggregations": ["Header:X-Forwarded-For"],
        "actions": [
            {"name": "log",
             "params": {"destination": "stderr"}},
             {"name": "block",
             "params": {"message": "IP-Blocked"}}
        ]
```
Then I tried the site and did not get the "IP-Blocked" message after the second attempt. After some changes it was finally working...
