### ISSUE TITLE
add Metager

### ISSUE THREAD

**Issue by T4eus** [searx/searx#1427]
https://metager.org/
https://metager.de/

**Comment by drakex90** [comment]
Would definitely be a good addition.

**Comment by jfowl** [comment]
I would like to question the usefulness of this, as metager is also a meta-search engine. It also combines different searches into one result list.
Plus side: Servers in Germany (GDPR land).

**Comment by return42** [comment]
Just want to leave a link to the metager project: https://gitlab.metager.de/open-source/MetaGer.git

>  would like to question the usefulness of this, as metager is also a meta-search engine

Nearly all common search engines we use are meta-search engines, to name just the most known one: DuckDuckGo

**Comment by Singustromo** [comment]
As it seems it has not been added yet. Here's a currently working config:

```
  - name : metager
    engine : xpath
    paging : False
    search_url : https://metager.org/meta/meta.ger3?eingabe={query}
    url_xpath : //div[@class="result-subheadline"]/a/@href
    title_xpath : //div[@class="result-headline"]/h2/@title
    content_xpath : //div[@class="result-description"]/text()
    categories : general
    shortcut: mg
```

**Comment by unixfox** [comment]
@Singustromo feel free to open a PR if you think it's working great :)

**Comment by asciimoo** [comment]
The only thing needed after adding metager to searx is to implement a searx engine in their side --> infinite metasearching =]

**Comment by allendema** [comment]
> The only thing needed after adding metager to searx is to implement a searx engine in their side --> infinite metasearching =]

Yupp, on its way.
https://gitlab.metager.de/open-source/MetaGer/-/merge_requests/1885
