### ISSUE TITLE
logicodev-dark as default

### ISSUE THREAD

**Issue by Perflyst** [searx/searx#1428]
How can I set logicodev-dark as default?
I tried with `logicodev-dark` `logicodev_dark` and `logicodev dark`. I also tried with `"` and with `'`.

```
ui:
    default_theme : oscar # ui theme
    theme_args :
        oscar_style : logicodev # default style of oscar
```

**Comment by Pofilo** [comment]
```
    theme_args :
        oscar_style : logicodev-dark
```

It works fine on my instance. Did you have the correct indentation in the file ? Did you restart searx ?

**Comment by Perflyst** [comment]
I think I have the correct indentation. In front of `theme_args` are 4 spaces. In front of `oscar_style` are 8 spaces.
I also restarted nginx and uwsgi. Browser cache was cleared too.

Other settings, like default engines, are working.

/edit: I also tried this on another server with apache2. Not working...

**Comment by massimilianoLe** [comment]
Hi there,
I have the same exact issue as @Perflyst

**Comment by Pofilo** [comment]
And if you try to change another parameter (like `default_theme`), does it changes the theme ?
Just to see if a change in configuration is taken in consideration.

Also, what is the version of your searx instance ? Are you on a tag, on master (if yes which commit) ?

**Comment by Perflyst** [comment]
`default_theme : legacy` is working without any issues. I am on `v0.14.0` with commit `3ac578c0a8ea7d32c5f6302760c86d232ff29fa8`.

**Comment by SitiSchu** [comment]
Same issue here tried with quotes as well to no avail. Got this in the logs though:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f2413b96950>
```
(Its not really helpful but its all there is)

If I set the debug key to True it suddenly works so I can't provide the debug output.

**Comment by SitiSchu** [comment]
Ok this can be fixed by installing the npm dependencies and building the styles. Then it works with `logicodev-dark` and debug mode turned off.

**Comment by massimilianoLe** [comment]
After i added the lines 267-269 of this file https://github.com/asciimoo/searx/blob/master/searx/preferences.py
it worked :-)

**Comment by Perflyst** [comment]
This solution is not working here. For others on the issue, we diff'd settings.yml and preferences.py

My debug log:
```
[2018-12-31 15:31:46,455] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/usr/local/searx/searx/webapp.py", line 404, in pre_request
    preferences = Preferences(themes, list(categories.keys()), engines, plugins)
  File "/usr/local/searx/searx/preferences.py", line 261, in __init__
    'theme': EnumStringSetting(settings['ui']['default_theme'], choices=themes),
  File "/usr/local/searx/searx/preferences.py", line 37, in __init__
    self._post_init()
  File "/usr/local/searx/searx/preferences.py", line 67, in _post_init
    self._validate_selection(self.value)
  File "/usr/local/searx/searx/preferences.py", line 62, in _validate_selection
    raise ValidationException('Invalid value: "{0}"'.format(selection))
ValidationException: Invalid value: "logicodev-dark"
```

**Comment by Perflyst** [comment]
Seems like this works now with v0.15.0, I changed nothing in the config from theme settings.
@SitiSchu can you try again, please?

**Comment by agnelvishal** [comment]
If it still doesn't work, delete the theme_args and oscar_style line and paste the one at https://github.com/asciimoo/searx/issues/1428#issuecomment-434744253

**Comment by gkaklas** [comment]
Sorry for bumping, is this still an issue? :thinking: (I have seen instances with the dark theme set by default, and it seems like the original author has managed to make this work as well)

**Comment by asciimoo** [comment]
AFAIK this is fixed. Feel free to reopen in case it doesn't work.

**Comment by 825i** [comment]
Mentioning here too, as this theme doesn't seem to ship by default in 1.1.0-27-bf0a583f
