### ISSUE TITLE
Docker build failing

### ISSUE THREAD

**Issue by ceptonit** [searx/searx#1437]
Been building searx successfully for docker weekly for a year now but this week, the build failed.

Using:
```
git clone https://github.com/asciimoo/searx.git
cd searx
docker build -t searx .
```

After step 46/46, here's what I'm getting:

```
Collecting cryptography>=2.2.1 (from pyopenssl==18.0.0->-r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/d2/5f/6ed3135eb1e775187f7ecd4e7713f1415516725365e51f9786143f36e024/cryptography-2.4.1.tar.gz (468kB)
  Could not find a version that satisfies the requirement cffi!=1.11.3,>=1.7 (from versions: )
No matching distribution found for cffi!=1.11.3,>=1.7
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c echo "@commuedge http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories  && apk -U add     build-base     python     python-dev     py-pip     libxml2     libxml2-dev     libxslt     libxslt-dev     libffi-dev     openssl     openssl-dev     ca-certificates     tini@commuedge  && pip install --no-cache -r requirements.txt  && apk del     build-base     python-dev     libffi-dev     openssl-dev     libxslt-dev     libxml2-dev     openssl-dev     ca-certificates  && rm -f /var/cache/apk/*' returned a non-zero code: 1
```

**Comment by pExeen** [comment]
It seems like the syntax `cffi!=1.11.3,>=1.7` that `cryptography` uses is not supported by pip 10.0.1.

In the `Dockerfile` file you can replace the line `  && pip install --no-cache -r requirements.txt \` (line 38) with `  && pip install --upgrade pip && pip install --no-cache -r requirements.txt \`

**Comment by ceptonit** [comment]
> It seems like the syntax `cffi!=1.11.3,>=1.7` that `cryptography` uses is not supported by pip 10.0.1.
> 
> In the `Dockerfile` file you can replace the line ` && pip install --no-cache -r requirements.txt \` (line 38) with ` && pip install --upgrade pip && pip install --no-cache -r requirements.txt \`

That did the trick, thanks man!

**Comment by Pofilo** [comment]
Should we open a merge request to add this quick fix ? Or maybe adding it to the doc as it is an upgrade of pip.

**Comment by ceptonit** [comment]
> Should we open a merge request to add this quick fix ? Or maybe adding it to the doc as it is an upgrade of pip.

The merge request would be the cleanest way.
I'm not sure how to do that though.

**Comment by bmagic** [comment]
I make a pull request with your solution. 
https://github.com/asciimoo/searx/pull/1449

**Comment by unixfox** [comment]
@dalf @pofilo I think you can close this issue now that https://github.com/asciimoo/searx/pull/1450 has been merged.

**Comment by dalf** [comment]
You can build the Docker image using
```
./manage.sh docker_build
```

It is built and pushed automatically with [travis](https://github.com/asciimoo/searx/blob/master/.travis.yml): 
https://travis-ci.org/searx/searx

The Docker image is published here:
https://hub.docker.com/r/searx/searx

See also:
https://github.com/searx/searx-docker
