### ISSUE TITLE
engine google : exception : CAPTCHA required

### ISSUE THREAD

**Issue by GyanP** [searx/searx#1441]
I intregated searx in my application, all search engine works fine but since after few days ago, we are facing the google search results. application request didn't any search results response.
I updated all user agnet and added other headers param.

Please track the below exception, what we are facing.

> engine google : exception : CAPTCHA required
Traceback (most recent call last):
  File "/home/ubuntu/myproject/metaengine/searx/search.py", line 105, in search_one_request_safe
    search_results = search_one_request(engine, query, request_params)
  File "/home/ubuntu/myproject/metaengine/searx/search.py", line 88, in search_one_request
    return engine.response(response)
  File "/home/ubuntu/myproject/metaengine/searx/engines/google.py", line 223, in response
    raise RuntimeWarning(gettext('CAPTCHA required'))
RuntimeWarning: CAPTCHA required

**Comment by ixti** [comment]
Pretty same I see on https://searx.xyz/:

![image](https://user-images.githubusercontent.com/94782/49258865-3f77e200-f437-11e8-82ea-82d3ada34c02.png)

**Comment by jfowl** [comment]
> I updated all user agnet and added other headers param.

According to my experience, this does not help very much. After a certain amount of illegitimate searches (e.g. the ones via searx), Google puts your whole IP behind a captcha lock. I would recommend to use some proxies to avoid these issues in the future.

**Comment by micah** [comment]
I'm currently there. At this point, searx is no longer usable at all,
and I'm going to have to shut it down if there is no way to work around this.

**Comment by dimqua** [comment]
@micah why not use startpage engine instead?

**Comment by Pofilo** [comment]
> 
> I'm currently there. At this point, searx is no longer usable at all, and I'm going to have to shut it down if there is no way to work around this.

There is a lot of other engines. If you think Google will give you better results than others, it's because they have you profile and they can adapt theirs responses. So using Google through Searx is similar than using others engines.

To be sure to avoid those CAPTCHA errors, you can disable all google engines in the config file.

**Comment by dalf** [comment]
See #729
