### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by josch** [searx/searx#1442]
Hi,

I'm the Debian maintainer of searx and we are still shipping version 0.14.0 of searx because there has not been a more recent release since February.

Unfortunately, we see a number of services that do not work anymore with 0.14.0 but which are fixed in git. Would it be possible to make a release soon?

The last commit to the repository was back in August. Is the project still alive? Debian plans to release its next stable version soon and we should not include searx if it's not maintained anymore.

Thanks!
cheers, josch

**Comment by prolibre** [comment]
https://github.com/asciimoo/searx/issues/1409 :-)

**Comment by immanuelfodor** [comment]
Maybe he could appoint/ask for co-maintainers to the repo who can merge, test and fix the many pull requests. This project should be kept alive, many people uses it and its everyone's best interest to protect our privacy.

**Comment by FrostKnight** [comment]
Yes, I agree with this, he needs co-maintainers if he busy.

**Comment by immanuelfodor** [comment]
@asciimoo would an unofficial searx fork with the same name be okay for you, Adam? We/some of the guys here or at #1409 would test and merge many of the existing PRs, and then create one _huge_ PR for you to merge as 15.0? How is that sound to ease up the maintaining process for you? I'm/we're asking it with all due respect for your work so far and in the name of keeping this project alive, useful and prosperous.

**Comment by kvch** [comment]
I will try to pick up the missing PRs and create a new release this weekend. Sorry for keeping you waiting.

**Comment by immanuelfodor** [comment]
Works great in Docker, thanks for the weekend's efforts! :)
