### ISSUE TITLE
[Feature] Add Google-like UI Option

### ISSUE THREAD

**Issue by asddsaz** [searx/searx#1445]
**Feature**: Add [Google](https://www.google.com/)/[Ecosia](https://www.ecosia.org/)/[StartPage](https://www.startpage.com/)/[DuckDuckGo](https://duckduckgo.com/)-like UI
**Why**? People are used to these UIs and I believe that if SearX could mimic them it would help keep users.
**How**? Some of these engines front-ends are free software like [loklak_search](https://github.com/harshit98/loklak_search).
Maybe someone can elaborate more on this?

___________________
Want to back this issue?[ Post a bounty on it!](https://www.bountysource.com/issues/66626312-feature-add-google-like-ui-option) We accept bounties via [Bountysource](https://www.bountysource.com/).

**Comment by aliceinwire** [comment]
what is wrong with the default [searx](https://searx.site/) UI?
I think is pretty similar

**Comment by dalf** [comment]
Have a look to the theme ```simple```.

**Comment by maverick74** [comment]
`simple`should be the default theme ;)

**Comment by asddsaz** [comment]
@Pofilo I'm not a "UI" expert but look at Google:

<img width="1280" alt="screen shot 2018-12-14 at 2 33 59 pm" src="https://user-images.githubusercontent.com/42685606/50028677-b374c700-ffad-11e8-9bee-e1540f44b93d.png">

<img width="1280" alt="screen shot 2018-12-14 at 2 33 51 pm" src="https://user-images.githubusercontent.com/42685606/50028678-b374c700-ffad-11e8-862b-db9386f32ddb.png">

It looks very welcoming

Now look at DuckDuckGo:

<img width="1280" alt="screen shot 2018-12-14 at 2 34 42 pm" src="https://user-images.githubusercontent.com/42685606/50028709-d010ff00-ffad-11e8-9638-da083b82aa5f.png">

<img width="1280" alt="screen shot 2018-12-14 at 2 34 37 pm" src="https://user-images.githubusercontent.com/42685606/50028710-d010ff00-ffad-11e8-9d6c-79152d588c0b.png">

Again, very welcoming (just me?)

Now look at SearX:
 
<img width="1280" alt="screen shot 2018-12-14 at 2 34 22 pm" src="https://user-images.githubusercontent.com/42685606/50028747-ecad3700-ffad-11e8-862f-304ea1a2096c.png">

<img width="1280" alt="screen shot 2018-12-14 at 2 34 15 pm" src="https://user-images.githubusercontent.com/42685606/50028748-ed45cd80-ffad-11e8-8d4a-e265deb75955.png">

It is very dark, and to most people unfamiliar.
I would say this is why search engines like DuckDuckGo are so popular.

I'm not saying to duplicate Google, I just think SearX is very unfamiliar to new users and may persuade them from not using it.

**Comment by gjhklfdsa** [comment]
@asddsaz @Pofilo Jive Search (a free software SearX competitor) has a similar UI to google.
Jive Search: https://github.com/jivesearch/jivesearch

**Comment by Madis0** [comment]
For people still looking for this - oscar's subtheme Pointhi looks the closest while keeping all options at the same place.

**Comment by return42** [comment]
@asddsaz wrote:

> It is very dark, and to most people unfamiliar.

?!?! Take off your sunglasses and you will see that almost the entire screen is white.

> I'm not saying to duplicate Google, I just think SearX is very unfamiliar to new users and may persuade them from not using it.

?!?? Empty page with one search field where you type your search term in .. if you can't do this, you should better avoid the Internet completely.
