### ISSUE TITLE
gitea search engine

### ISSUE THREAD

**Issue by markuman** [searx/searx#1447]
simply hacked ...based on the github engine

https://git.osuv.de/m/dotfiles/src/branch/master/docker/searchx/gitea.py

**Comment by markuman** [comment]
@aliceinwire the official site of gitea is https://gitea.io
but there is no official public hosted gitea service like gitlab.com. everyone can host gitea itself. therefore, you must replace https://git.osuv.de with your gitea domain.

**Comment by aliceinwire** [comment]
would be nice if the hostname is not hardcoded.
p.s. your https://git.osuv.de/m/dotfiles/src/branch/master/docker/searchx/gitea.py is giving me 500 internal server error

**Comment by markuman** [comment]
@aliceinwire 

> p.s. your https://git.osuv.de/m/dotfiles/src/branch/master/docker/searchx/gitea.py is giving me 500 internal server error

My mariadb was not available because I needed to fix some other errors on my host. :)

> would be nice if the hostname is not hardcoded.

I have no Idea if it's possible to pass a variable from `settings.yml` to the engine file `gitea.py`. Do you know if it is possible?

**Comment by dimqua** [comment]
I doesn't work for me with your instance (timeout), but it works with other gitea and gogs instances.

**Comment by markuman** [comment]
Indeed. My gitea instance in running in a docker container in docker swarm mode behind a caddy proxy. For some reason, this setup results into a timeout. Butinternally my searx instance (also running in a docker container in the same swarm) uses the internal docker network. That works.
