### ISSUE TITLE
Seems that startpage and ixquick enignes are not working anymore on Searx

### ISSUE THREAD

**Issue by SirTerrific** [searx/searx#1454]
Hello and thanks for the works.

I tried on my searx and on other instance like searx.me...  but It's not working.

How could we fix that?

Thanks.

**Comment by drakex90** [comment]
bumping this as it has been quite sometime these two haven't been working.

**Comment by miicha** [comment]
you can test the fix at https://finden.tk

**Comment by veloute** [comment]
> you can test the fix at https://finden.tk

doesn't seem to be working anymore?

**Comment by miicha** [comment]
startpage introduced captchas, therefore it's broken at the moment
