### ISSUE TITLE
Weird result priority

### ISSUE THREAD

**Issue by ghost** [searx/searx#1455]
I've noticed the quality of the results I'm getting is sub-par, even though individual engines give me good results. Here's an example:

My results:

![2018-12-01-234830_1920x1080_scrot](https://user-images.githubusercontent.com/6775354/49335882-7cbdaa80-f5c4-11e8-9066-f947f5170c0a.png)

Public instance results:

![2018-12-01-234833_1920x1080_scrot](https://user-images.githubusercontent.com/6775354/49335885-85ae7c00-f5c4-11e8-9c3f-e9aed9c19aec.png)

Why is wikipedia not the first result as most people would expect it to be?

Looking into my config the only difference is that I deprioritized bing (notice how the first result is from multiple engines on the public instance). If I remove the negative weight, or disable the engine completely, it works!

So question is, why would searx deprioritize results from multiple engines if just one of them is low priority? The final search result weight should be a `max()` of the engines that found it, not `avg()` or whatever is used right now.

Running latest searx from master branch.

**Comment by return42** [comment]
> If I remove the negative weight, or disable the engine completely, it works!

For me, it is not clear if a negative weight is valid.  Can't find a hint in the documentation. So I guess weight should be a positive value. For less priority I use floats < 1 (e.g. 0.5 or 0.2) and for me it seems to work .. but may I am wrong.

**Comment by unixfox** [comment]
Unfortunately Searx have little to no control on that. Based on the location of the instance and the enabled engine the results can vary a lot.

I'm closing this issue because Searx cannot do much about that.
