### ISSUE TITLE
qwant api fix

### ISSUE THREAD

**Issue by joshu9h** [searx/searx#1459]
file qwant.py
line 13
When adding q= 
url = 'https://api.qwant.com/api/search/{keyword}?count=10&offset={offset}&f=&q={query}&t={keyword}&uiv=4'

It's working again
Sorry figuring out how to push this

Regards Jos

**Comment by joshu9h** [comment]
for startpage i see it send the request and receive the response with the results but it doesn't show the 
final results it looks like the xpath variable is not correct but i don't know the correct one

**Comment by dimqua** [comment]
Don't mind if I push this fix for you? Then we can close the issue.

**Comment by Pofilo** [comment]
The fix does'nt change anything for me. I still don't have any results from qwant. Is it working on your side ?

**Comment by dimqua** [comment]
@Pofilo No. :-(

**Comment by joshu9h** [comment]
It''s working fine here!

**Comment by jfowl** [comment]
Working here too, @Pofilo were you able to fix it on your side?

**Comment by vuori** [comment]
I spent a while looking at qwant problems today. It seems that they check the User-Agent very carefully and have a hair-trigger graylisting if there are too many failures:

  * Old Firefox versions (60.0) etc. almost always fail, current versions (70.0, 71.0) work.
  * Versions that probably don't exist (70.0.1 and such) always fail.
  * Looks like they compare the UA to the TCP fingerprint. Windows UA from Linux always fails, Linux UA from Linux (with current FF version) works.

So far looks like setting a good User-Agent keeps things working pretty well. The parser should check for `error` key in the response JSON and show a failure in the UI so Qwant failures can be diagnosed easier. It seems that error code 1701 means "user agent check failed" and code 24 is "greylisted" (web ui shows captcha).

**Comment by bqv** [comment]
Ditto #1300, I think this has resurfaced?

**Comment by unixfox** [comment]
@bqv Qwant still works for me.
![2020-11-13_19-22](https://user-images.githubusercontent.com/4016501/99101658-cd254b80-25d4-11eb-98ca-1b3ab5548406.png)

**Comment by bqv** [comment]
Example: https://searx.fmac.xyz/?q=%21qw%20ok&categories=none&language=en-GB

Is this due to qwant blacklisting by ip?

**Comment by return42** [comment]
I guess your searx instance is abused by bots / [google is also blocked](https://searx.fmac.xyz/?q=%21google%20ok&categories=none&language=en-GB)

**Comment by vuori** [comment]
FWIW Qwant randomly starts requiring a captcha for me on an instance with demonstratably no outside users. Launching a browser and solving the captcha makes it work again for a month or two again. Seems like their monitoring is just very trigger-happy.

**Comment by bqv** [comment]
Marvellous...
