### ISSUE TITLE
Out-of-Topic-Observation: The 2018_12_23 Version of the GitHub API blocks/censors this Project

### ISSUE THREAD

**Issue by martinvahi** [searx/searx#1470]
The 

https://api.github.com/users/asciimoo/repos

should return structured text that contains the name of this project, the "searx", but if one hits Ctrl-f and tries to find the "searx", without the quotation marks, then at least at the time of the making of the archival copy

https://archive.is/oWRdD 

there is no such string at the output of the GitHub API function that is supposed to return information about all repositories of a given GitHub user account. I filed the "bug report" to GitHub already, so hopefully they have fixed it by the time You read this, but it is still possible to verify my such observation by looking at the archival copy of the GitHub API function output. Cloning URLs of repositories are stored to a field named "git_url". The "git_url" also contains the repository name. If the string "searx" is absent, then the respective "git_url" field must also be absent.

If it's not a genuine bug, then the fact that the Microsoft owns both, the GitHub and the 

https://www.bing.com/

starts to smell a bit like the Halloween Documents. 

https://en.wikipedia.org/wiki/Halloween_documents

**Comment by rla** [comment]
This is not a bug. The GitHub API responses are paginated and the current repository happens to be on non-first page. You can try: <https://api.github.com/users/asciimoo/repos?per_page=50&page=2>

**Comment by martinvahi** [comment]
My mistake. Sorry. I also received same kind of explanation from the GitHub support. I thought that it's like SQL, where by default everything is returned and if one wants to avoid crashing due to lack of RAM, one explicitly describes a limit, "count", as part of the query, but it seems that the GitHub API uses an opposite approach.

Well, at least it's not explicit censorship and that's a really nice thing to know. As it turns out, the 

https://api.github.com/user/20240/repos?page=2

contains the string "searx".

Sorry. My mistake. Also I thank everybody, including the GitHub support, for pointing out my mistake.
