### ISSUE TITLE
Drop Python 2 support ?

### ISSUE THREAD

**Issue by om26er** [searx/searx#1471]
Whats the plan on dropping Python 2 support for searx, PY2 will go EOL in just a year, so maybe its time to consider dropping its support ?

It seems this project have only a handful of places that would need to be changed, so I can do that if required.

**Comment by kvch** [comment]
I am all for dropping Python 2 support. Our main intention was to keep as many users happy as possible.

**Comment by nfk** [comment]
Hi,

On spot project we have done the full move to [python3](https://gitlab.e.foundation/e/cloud/my-spot/commit/2cc4bf3eaa5cbab007b56ad4ac287d56fc57f5ae) from searx 0.15.0. Maybe we can plan to move that work on searx upstream?  The main diff on spot is about the cache which is made with redis database.

**Comment by gkaklas** [comment]
Can this closed, since 2cc4bf3 has been merged? :thinking:
