### ISSUE TITLE
What is the secret key here in settings.yml ? be used for?

### ISSUE THREAD

**Issue by gorlapraveen** [searx/searx#1473]

**Comment by kvch** [comment]
It is used in two places:
1. Flask, the web framework we use, requires a secret key for session handling. See more: http://flask.pocoo.org/docs/1.0/quickstart/#sessions
2. When image proxy is enabled, the instance downloads images for you from the search service. To authenticate the request (to make sure that the request is coming from the UI of the instance) a HMAC is generated using the secret key.

**Comment by kvch** [comment]
Closing due to lack of response.
