### ISSUE TITLE
BUG : Adding a question mark to search results show error in image search

### ISSUE THREAD

**Issue by ghost** [searx/searx#1484]
Here are the images
https://mega.nz/#F!zux2gCyJ!dgt-g_qpkhkM7k4prV52Sg
If you want to know anything else about the problem.I will be happy to help
:smiley: 
Edit:I was using an instance of searx hosted by disroot.org
The web app being search.disroot.org
The custom search URL is :
http://search.disroot.org/?preferences=eJx1VE1v2zAM_TXzxeiwrYedfBg2DCswoMWS7irQEu0QlkVXkpP4349K_KG03SEOLJPvPT5S9BhGG4NipxyeVIS6-gk2YGGYlMfA9oi-YpDXj-zbwoJrR2ixQnf3vCssa7BYFYYC1BaNGuzYkgvVX-rvLHWoDhw7nMKHL98fB3QJUviUJdetpLXnU0CfyFPcg2vIUUQVtGdrl8xvWmMI6sfjg4CcvAQU1IsSNXg-T9Xej1jAGFlzP1iMIipAgwHB60P1qYgH7LHioMEX6G7F7tA2SmjZ9xCJXVKx96A7EfX857fw9Sw2yOmv_f5pt_DL--4CnwrRELFlP6mAFnXcHEEnHBiqjnQHUoBqyGJiaDxiGbiJJ_BYGvKSlgAURfl6ZIhKBdYEtuzREMghOVDqSAY5AXg0ht4GtcytxXKwMJUwDBmj1vouHjOElloRCUFAWnTowWaw0poUA6ELEbHPQxrjmcwG7CYQYZd2pFcz6i79Ws6TVgM2-kxpPwbSSl3-5NMEzuD5PVnbSYvYReoxzJZdVSwIhto6_o-Mj4S5ks_nTH5ANANK71cslgH0OHDm5Rb0ph-bD1cJSwrKnCfXMh_BM69OH6D2kB5zPWm06IglhTynpliLtxjnqAkOfONz4-VyEehMSORu4sjhwB24rayZfkvFOPXs5HJifnr1dS2zn3q5D34qowcXrMz9TU10fhml0_mRJSlMEtJJuK3m5QTupqnb7JRX-e825nbwlrdXZa6K5z4sZb8KWzt6ohC0rKKcUYPzZYh-1HH0SUzQhE7jRU1qkGaDZXrM7chQtqI-399_Pd_cu2ihXjIi-DikTZbbYNrS4GURpoX07j261LMus2XPFD3GA5vq6XG3L-atJMNezQD_AFmMPYE=&q=%s

**Comment by muppeth** [comment]
Disroot admin here. Just did a quick check and seems like searx.me is not affected by it and on disroot it breaks when searching images. I will have a look into it, but if someone knows  right away what the issue may be, feel free to enlighten me :P

*Update:* 
Quickly checked few other instances and some of them have the same issue. Seems like the ones runniing version 0.15 are free of the issue.

**Comment by slakedavid2** [comment]
I will close this thread then
