### ISSUE TITLE
Language "all" not selectable, many search engines do not work

### ISSUE THREAD

**Issue by DD8372812** [searx/searx#1486]
Hello,

on my 0.14.0 instance lots of search engines are not supported regardless of the selected language. E.g. I am not able to get startpage running (supported). I can choose whatever language I want, it doesn't work. On other instances (older?) I can see that all search engines are supported with language "all" resp. "standard language". I do not have a dropdown selection "all" or "standard language".

Is there something I do not understand or is this normal behaviour? How can I get startpage working with e.g. en or de?

**Comment by joshu9h** [comment]
When you update searx to version 0,15 startpage is working again!

**Comment by xinomilo** [comment]
yes, startpage is working with 0.15.0, tested in 2 instances with 2 different search languages.

in your instance, maybe you should check out the errors first to figure out the problem... if you run apache/nginx + uwsgi setup, you can look up the uwsgi log for any errors regarding startpage or other engines.

as far as i recall, there was never an "all" dropdown selection. just a "default" or lang "en", "de" etc..

**Comment by DD8372812** [comment]
Hello @joshu9h @xinomilo ,

thanks for your answers.

I am running 0.14.0 in Docker container wonderfall/searx.

Now I tried hoellen/searx, it's on 0.15.0. Startpage runs now although it's marked still as "not supported". But: I'm running searx through a TOR proxy, SOCKS5. In wonderfall/searx it worked but not in hoellen/searx :( it seems searx ignores the proxy settings (I see regular internet connections on my firewall on 443). Need to ask for that in hoellen/searx board.

**Comment by kvch** [comment]
@DD8372812 I've just merged the PR which adds support for setting proxy configuration in Docker images: https://github.com/asciimoo/searx/pull/1485

**Comment by return42** [comment]
Issue seems solved, please close / thanks!
