### ISSUE TITLE
How to change make searx work on domain.com:80?

### ISSUE THREAD

**Issue by Freeland3r** [searx/searx#1487]
Hi there,

I am pretty new to python, was able to install searx on the VPS, however i have hard time figuring out how to make it work on the domain.com, because Searx only displays on domain.com:8888

Thank you in advance

**Comment by Freeland3r** [comment]
I have done it the classic way, ok will check out the uwsgi and webserver instructions

**Comment by Freeland3r** [comment]
systemctl status uwsgi.service tells me searx is invalid user

**Comment by Pofilo** [comment]
Did you follow the instructions on [https://asciimoo.github.io/searx/dev/install/installation.html](https://asciimoo.github.io/searx/dev/install/installation.html) ?
You should have done a `sudo useradd searx -d /usr/local/searx` which creates the searx user.

**Comment by Freeland3r** [comment]
yep i did the user has been created

**Comment by Freeland3r** [comment]
btw what is the password for the user searx?
