### ISSUE TITLE
Google: add "No results found for", "Results for <search term> (without quotes)" to Searx results

### ISSUE THREAD

**Issue by ghost** [searx/searx#1489]
Google supports searching for the exact phrase when the search term is enclosed in quotes. When no results are found Searx doesn't inform the user; for example the search term `"generates revenue of copyrighted work"` produces no exact hits and Google clearly tells this:

> No results found for "generates revenue of copyrighted work".
> Results for generates revenue of copyrighted work (without quotes):

**Comment by kvch** [comment]
I'm sorry, I am not sure I follow you. What is the issue you see? Or is it an enhancement request?
Right now searx notifies the user when no engine has found anything. Do you want to get notified if nothing is returned by engine?

**Comment by return42** [comment]
works perfect: https://darmarit.org/searx/?q=%21go%20%22generates%20revenue%20of%20copyrighted%20work%22&categories=none&language=en-US

**Comment by ghost** [comment]
> 
> 
> works perfect: https://darmarit.org/searx/?q=%21go%20%22generates%20revenue%20of%20copyrighted%20work%22&categories=none&language=en-US

This thread has now appeared in Google results... Search for any randomly generated term such as `https://darmarit.org/searx/?q=%21go%20%227FgD8Ct9qbmDz7Bs2dhA14IJy%22&categories=none&language=en-US`

But there's now a warning, thankfully:

> Sorry! we didn't find any results. Please use another query or search in more categories.

**Comment by unixfox** [comment]
> > 
> > 
> > works perfect: https://darmarit.org/searx/?q=%21go%20%22generates%20revenue%20of%20copyrighted%20work%22&categories=none&language=en-US
> 
> This thread has now appeared in Google results... Search for any randomly generated term such as `https://darmarit.org/searx/?q=%21go%20%227FgD8Ct9qbmDz7Bs2dhA14IJy%22&categories=none&language=en-US`
> 
> But there's now a warning, thankfully:
> 
> > Sorry! we didn't find any results. Please use another query or search in more categories. 

It's probably due to the Searx instance blocked by Google for a few hours. Now it's returning results.
