### ISSUE TITLE
doesn't display pages but offers to download them

### ISSUE THREAD

**Issue by georg-mayer** [searx/searx#1491]
Hi,

I came back from a docker (wonderfall) installation to the regular uwsgi way of running searx. 

system: debian 4.9.0-8-amd64

webserver: apache2

did a clean installation, followed every tstep of the installation guide here https://asciimoo.github.io/searx/dev/install/installation.html.

I also rebooted the system several times, re-started uwsgi/apache several times and also did not find anything in the logs. 

Problem: regardless which browser (firefox, chormium, chrome) I used, the html-pages are offered to me for download (dialog opens, asking if I want to save the file) rather than being displayed in the browser.

Thanks for your help!

Cheers,
Georg

**Comment by jfowl** [comment]
Which pages are offered for download? The results? or even the searx interface itself?
Can you upload the resulting file here?

**Comment by georg-mayer** [comment]
Hello,

I'm extremely sorry that I did not close this issue properly. I solved it a few days after posting, but forgot how. 

Thanks for your help!

Cheers,
Georg

**Comment by jfowl** [comment]
No problem, you can do so now ;)
