### ISSUE TITLE
Searx stops after terminal is closed

### ISSUE THREAD

**Issue by Freeland3r** [searx/searx#1493]
Hi there,

I have installed searx, all works fine.

However, when i close the terminal, searx stops being available. What do i need to do?

**Comment by Pofilo** [comment]
This is the second time you open an issue because you didn't follow the installation guide. Please read it more carefully. 
Of course, we can improve it !

**Comment by kvch** [comment]
@Freeland3r Feel free to open a PR to the branch `gh-pages` if anything is missing from the installation docs.
