### ISSUE TITLE
Official up to date docker image please?

### ISSUE THREAD

**Issue by Ryonez** [searx/searx#1495]
Is there any chance we could have an up to date docker image please?

The one linked in the documentation(`wonderfall/searx`) is out of date.
The only other one that says it's version 15, isn't actually version 15: https://github.com/angristan/docker-searx

An officially maintained docker image would be really appreciated.

**Comment by micressor** [comment]
I confirm that `docker build -t searx .` is running (in master and v0.15.0 tag) on an error:

```
[...]
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.2.1->pyopenssl==18.0.0->-r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/usr/lib/python2.7/site-packages/pip/_internal/wheel.py", line 886, in build
    assert have_directory_for_build
AssertionError
[...]
```

**Comment by Ryonez** [comment]
I'd just like to point out what I'm after is a docker image. The server I use(unRaid) makes building an image locally an unideal job.

This build error probably explains why the image that was meant to be on version 15 isn't though.

On 25 January 2019 8:43:16 PM NZDT, Marco Balmer <notifications@github.com> wrote:
>I confirm that `docker build -t searx .` is running (in master and
>v0.15.0 tag) on an error:
>
>```
>[...]
>Collecting pycparser (from
>cffi!=1.11.3,>=1.8->cryptography>=2.2.1->pyopenssl==18.0.0->-r
>requirements.txt (line 7))
>Downloading
>https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
>(158kB)
>Exception:
>Traceback (most recent call last):
>File
>"/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py",
>line 176, in main
>    status = self.run(options, args)
>File
>"/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py",
>line 346, in run
>    session=session, autobuilding=True
>File "/usr/lib/python2.7/site-packages/pip/_internal/wheel.py", line
>886, in build
>    assert have_directory_for_build
>AssertionError
>[...]
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/asciimoo/searx/issues/1495#issuecomment-457484148

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kvch** [comment]
@micressor The issue you are experiencing is a `pip` problem according to GH.
https://gist.github.com/dmulter/38330962002d28533d7dd7c1a70ee4f5
I am looking into it right now.

**Comment by Wonderfall** [comment]
Just so you know, I recently updated my Docker image (`wonderfall/searx`).
Searx 0.15 + Python 3. I'm planning on making a PR for the official Dockerfile.

**Comment by unixfox** [comment]
@dalf can this be closed now that we have https://github.com/searx/searx-docker?

**Comment by dalf** [comment]
@Ryonez> as @unixfox said, see https://github.com/searx/searx-docker

If you want to use the Docker image without the other Docker images, see:
* https://github.com/searx/searx/blob/fbe40001d35ea5cf74c92f35d76c642a480a5c9f/dockerfiles/docker-entrypoint.sh#L25
* https://github.com/searx/searx-docker/blob/master/docker-compose.yaml#L48
