### ISSUE TITLE
Add info about workaround for using 2 languages simultaneously to FAQ

### ISSUE THREAD

**Issue by Tobi823** [searx/searx#1508]
Thank you @asciimoo (and all other) for this great project. I'm using searx (on my own server) for some months but I had trouble with the quality of the search result. I'm (as a german native speaker) used to ask google german and english questions without using any special prefixes etc.

Using the `:en` or `:de` prefix on my smartphone is quite diffcult due to the `:`-character. Moreover, its very unusual for me to first specify the language and then enter my question. 

I discovered a workaround for my problem - can you add it to the FAQ (https://searx.me/about)? I've searched for hours before I discover this (quite simply) workaround and maybe someone else has the same problem. My solution:

- Set the default language to "de"
- Add a new search engine (engine: google + only english)

settings.yml:
```
search:
    language : "de"
    ...
                         
engines:                 
  - name : google english
    engine : google
    language : english
    ...
```

**Comment by rototom** [comment]
Thank you very much!

**Comment by dimqua** [comment]
Thanks!

**Comment by unixfox** [comment]
Feel free to create a pull request for this workaround :).

**Comment by Tobi823** [comment]
Done https://github.com/searx/searx/pull/2479

**Comment by unixfox** [comment]
Just reopening this issue. It will get closed when your PR will be merged.

**Comment by dimqua** [comment]
Wow, the solution was so simple!
