### ISSUE TITLE
[Request] APKMirror

### ISSUE THREAD

**Issue by CaptainFrosty** [searx/searx#1511]
A bang shortcut for APKMirror like DuckDuckGo has would be extremely helpful for Android users. Thanks for your work.

**Comment by jfowl** [comment]
APKMirror does not have a search API, so this is a bit of work.
- Search: `https://www.apkmirror.com/?post_type=app_release&searchtype=apk&page={pageno}&s={query}`
- Results: actually not that unintuitive: in `div#content` are `.approw`s with the actual results:
```html
<a class="fontBlack" href="{relative result link}">{result title}</a>
```
A thumbnail is also available.

**Comment by jfowl** [comment]
@CaptainFrosty This has now been implemented, you may update your instance and close this issue ;)

**Comment by CaptainFrosty** [comment]
Appreciated.
