### ISSUE TITLE
Update Public Searx instances

### ISSUE THREAD

**Issue by ghost** [searx/searx#1519]
Related to issue #1440, I want you to mark any instance with [Clouflare] string so I can avoid them.

Example:
```
[Cloudflare] yyy.zz - Issuer: Cloudflare
```

[Problem with CloudFlare](https://github.com/privacytoolsIO/privacytools.io/issues/374#issuecomment-460077544)
[General problem with Cloudflare's MITM attack on the Internet](https://trac.torproject.org/projects/tor/ticket/24351)
[What you can do to resist Cloudflare?](https://notabug.org/themusicgod1/cloudflare-tor/src/master/what-to-do.md)

**Comment by ghost** [comment]
It's certainly a good idea to tag the CF sites.  I'm not sure why you opened a ticket when it's a wiki that you can easily edit yourself.  If the idea is to discuss and reach agreement, this is my take on it--

Simply writing "(Cloudflare)" is insufficient because searx is becoming more popular among people who have no clue what CloudFlare is.  So I have two suggestions:

1. Rename "*Running with an incorrect SSL certificate*" to "*Running with anti-features*", and then mark each record with "(bad SSL cert)" or "(uses CloudFlare)"

1. Reformat the whole list as a table.  The table can have columns for uptime, cloudflare, etc.

If some time passes and there is no objection to these ideas, I may act on them.

**Comment by unixfox** [comment]
@return42 this issue can be closed because it has been implemented in the wiki: https://github.com/asciimoo/searx/wiki/Searx-instances#running-in-exclusive-private-walled-gardens
