### ISSUE TITLE
better merging of search results

### ISSUE THREAD

**Issue by atomGit** [searx/searx#1521]
one of the huge benefits with searx is the ability to pull results from multiple engines, however i think there's a significant problem in the way results are displayed - for example, if one enables the google, google's results essentially drown out all of the other results which largely defeats the purpose of enabling multiple engines

i would really like to stress my perceived importance of this issue - what's the point in being able to query multiple engines when the first 5, 10 or 20 pages are all (or virtually all) google results?

please [my comment here](https://github.com/asciimoo/searx/issues/1521#issuecomment-481257565) in which i suggested using a tabbed interface to solve the problem

**Comment by dalf** [comment]
What I understand is that you prefer the google results.

One way without code : configure searx to use only google, wikidata, wikipedia in the general category (it will work whatever the instance). I guess this is not what you want.

Another way : set a the bigger priority on the google results (or whatever engine). In settings.yml, it is possible to set the ```weight``` attribute to a value higher than one. Example : 
```yaml
  - name : google
    engine : google
    shortcut : go
    weight: 5
```

One way to set the value on the client side : set value in the preferences and store the values using cookies (as it is already the case for the other preferences).

**Comment by atomGit** [comment]
> Can you give me an example (an URL or an screenshot) ?

the returned results seems quite dependent upon what search terms are used and what engines the user has selected and perhaps the specific Searx instance and whether they re-weighted the engines, but this doesn't really address the issue i'm trying to raise

in your first example, and when i preform my own searches using that instance, the results are quite mixed and this is acceptable, however what happens if you disable bing and amazon and enable other, smaller meta engines?

in my case with my personal settings for https://search.disroot.org/, a search for pink-elephants lists results from only 2 engines (google, ddg) on the 1st page even though i have 11 engines enabled and the 2nd page is entirely google results - i can't go beyond the 2nd page because "rate limit exceeded" which further amplifies the problem of finding results for other engines, but that's largely a separate issue

if there were something like a tabbed interface, then one could view results from any of their selected engines without having to page through piles of results in order to find the "faroo" results for example - along with that, there could be one tab that provides mixed results (all enabled engines) similar to what all the Searx instances provide now, but i think there really needs to be better way to leverage Searx's ability to use multiple engines

**Comment by return42** [comment]
Many words here .. the only I have understood is "I want better result merge".

@dalf asked you to play with the  `weight:` setting .. did you ever test it?

If not, do so and report your experience and what you missed.  Or even better: send your PR.

> in my case with my personal settings for https://search.disroot.org/, a search for pink-elephants lists results from only 2 engines (google, ddg) 

Seems no longer valid .. is this issue solved? .. then please close it .. if I look into your history it seems to me, that you never close Issues you opened .. could it be?

**Comment by return42** [comment]
Since there was no further feedback, the issue seems to be fixed .. if not, ask for reopen.
