### ISSUE TITLE
can searx provide xml results?

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1524]
Hello,

I am able to make a call with searx to get back JSON results:

curl "http://localhost:8888/?q=SpaceX&categories=general&format=json&lang=en&pageno=1"| python -m json.tool 

But I am wondering if there is an option to have:

format=xml
instead of
format=json

The json works well, and the results come back less cluttered, but I am just wondering on this part.

Also, what is the tag needed to add for "SafeSearch={none, moderate, strict}" as I tried to add 

safesearch=moderate

and that does not work?

Any help would be greatly appreciated.
Cheers,

**Comment by jfowl** [comment]
I had a look at the [Code](https://github.com/asciimoo/searx/blob/master/searx/search.py#L228-L240) and it says:
```python
    # get safesearch
    if 'safesearch' in form:
        query_safesearch = form.get('safesearch')
        # first check safesearch
        if not query_safesearch.isdigit():
            raise SearxParameterException('safesearch', query_safesearch)
        query_safesearch = int(query_safesearch)
    else:
        query_safesearch = preferences.get_value('safesearch')

    # safesearch : second check
    if query_safesearch < 0 or query_safesearch > 2:
        raise SearxParameterException('safesearch', query_safesearch)
```
So maybe go with 0 (none), 1 (moderate) and 2 (strict).


XML would be https://searx.de/?q=test&format=rss.

**Comment by Outstep** [comment]
Thanks for the information on this. Very helpful.
