### ISSUE TITLE
Installation and upgrade documentation

### ISSUE THREAD

**Issue by Cqoicebordel** [searx/searx#153]
I have an issue with the documentation :
I followed the wiki tutorial to install searx, using Apache. Everything was almost perfect, except for the configuration (shouldn't it be before we use virtual-env ? or maybe should it tell us to modify the settings.yml inside the virtual-env folder `/usr/local/searx/searx-ve/lib/python2.7/site-packages/searx-0.5.0-py2.7.egg/searx/`)

I'm a newbie in packaging and deployment of python app, so using Apache was useful for me because that something that I know, can control, and was already running for others stuffs.

Anyway. My problem was at upgrade time. Here is what I did : 
1. Look in the wiki -> Nothing
2. See the Readme, and try what was in "Upgrading" -> Of course, it wasn't applicable.
3. So I tried a mixture between what was in "Upgrading" and "Installing" in the wiki.
- git stash
- git pull ...
- sudo -u searx -i
- cd /usr/local/searx
- virtualenv searx-ve
- . ./searx-ve/bin/activate
- pip install -r requirements.txt
- python setup.py install -> Here was an error "Impossible to copy gruntfile.underscore, file not found" (the name is from memory, but it was something like that)
- touch of that file (in case it would solve everything -> No.

4 I'm a bit on edge, so I delete everything in /usr/local/searx, and install from the start (following the wiki). It works.

I'm just trying to describe my user point of view, and UX.

My point is :
- Why put the installation not supported in first
- What is the difference between Alternative Installation, Development and Deployment ?
- What is the right way of upgrading if we follow the tutorial in the wiki ?
- To develop, I try my modifications in `/usr/local/searx/searx-ve/lib/python2.7/site-packages/searx-0.5.0-py2.7.egg/searx/` and then copy/paste those in my personnal git repository which is located in an user folder (not system). Is there a better way of doing things ?

I think all those questions need to be addressed somewhere in the doc, and maybe more of those. 
Also maybe I just don't have the correct workflow. Or maybe I'm just too much of a newbie on those tech to understand the doc properly.

**Comment by asciimoo** [comment]
done: https://asciimoo.github.io/searx/dev/install/installation.html , https://github.com/asciimoo/searx/blob/master/manage.sh
