### ISSUE TITLE
Interface language set zh_TW but return zh_Hant_TW

### ISSUE THREAD

**Issue by bestpika** [searx/searx#1532]
1. Goto `/preferences`
1. Set interface language to 國語
![image](https://user-images.githubusercontent.com/5698157/54087987-d851be00-4393-11e9-927c-ba2080691046.png)
1. Save
1. Goto `/preferences`
![image](https://user-images.githubusercontent.com/5698157/54088008-12bb5b00-4394-11e9-82d4-08a277d4ebfe.png)

searx | 0.15.0

----

This return `zh_Hant_TW` but list only have `zh_TW`

https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L169
https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L787

**Comment by dalf** [comment]
Most probably related to https://github.com/flask-admin/flask-admin/issues/403

**Comment by dalf** [comment]
This issue has been fixed by the PR #1654.
