### ISSUE TITLE
how to submit instance on stats.searx.xyz

### ISSUE THREAD

**Issue by chinapao** [searx/searx#1534]
Hi I have created a searx public instance and been running for a while.  How can i submit or add my instance to the stats.searx.xyz page?

Cheers

**Comment by ghost** [comment]
Add it to the https://github.com/asciimoo/searx/wiki/Searx-instances using the same format as everyone and they'll update it from there.

**Comment by chinapao** [comment]
> Add it to the https://github.com/asciimoo/searx/wiki/Searx-instances using the same format as everyone and they'll update it from there.

Done.  Thank you very much.
