### ISSUE TITLE
Unclear instructions re autocomplete and add to browser search engines

### ISSUE THREAD

**Issue by vasyugan** [searx/searx#1537]
At https://github.com/asciimoo/searx/wiki/Installation it says:
### Optional
_Add to browser search engine options._

_This differs from browser to browser but the proper format for search is as follows_

 `https://domain.tld/search?q=%s`

_The format for auto complete is as follows_

`https://domain.tld/autocompleter?q=%s`

It does not say, which file has to be modified and what the names of the options are.

**Comment by TheFrenchGhosty** [comment]
You need to use this (for Firefox-based browsers) : https://github.com/nohamelin/xseei

**Comment by dalf** [comment]
With Firefox, you can go to the about page, and click on "Install" (below the title "How to add to firefox?") 

About page of searx.me instance : https://searx.me/about

**Comment by unixfox** [comment]
The about page now stipulate how to add searx as a search engine.
