### ISSUE TITLE
Error when installing letsencrypt certificate

### ISSUE THREAD

**Issue by agnelvishal** [searx/searx#1540]
I am using debian 9 and apache.
I get the following error when I run `sudo certbot --apache`

` Failed authorization procedure. searx.world (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://searx.world/.well-known/acme-challenge/iUSPeATtS3C9smjnDWKcIITUIXeckzMewNlvzQCFafQ [134.209.231.175]: "<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\" />\n    <met", www.searx.world (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.searx.world/.well-known/acme-challenge/8ZLl98_TxULlCIBdYbYUmiVHgjMsGDFiQKtTHmtmnN4 [134.209.231.175]: "<!DOCTYPE html>\n<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\" />\n    <met"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: searx.world
   Type:   unauthorized
   Detail: Invalid response from
   http://searx.world/.well-known/acme-challenge/iUSPeATtS3C9smjnDWKcIITUIXeckzMewNlvzQCFafQ
   [134.209.231.175]: "<!DOCTYPE html>\n<html
   xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\"
   xml:lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\" />\n    <met"

   Domain: www.searx.world
   Type:   unauthorized
   Detail: Invalid response from
   http://www.searx.world/.well-known/acme-challenge/8ZLl98_TxULlCIBdYbYUmiVHgjMsGDFiQKtTHmtmnN4
   [134.209.231.175]: "<!DOCTYPE html>\n<html
   xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\"
   xml:lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\" />\n    <met"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

`

**Comment by agnelvishal** [comment]
[http://searx.world](http://searx.world) works well. It has been 5 days since the dns records have been changed

**Comment by dalf** [comment]
The instance seems to be okay using CloudFlare. Be aware that CloudFlare is de facto a man in the middle.
