### ISSUE TITLE
Improve HTTP security headers

### ISSUE THREAD

**Issue by emanruse** [searx/searx#1549]
Simple tests show some improvement can be made:

https://securityheaders.com/?q=searx.me&followRedirects=on

https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsearx.me%2F%3Fq%3Dtest

**Comment by unixfox** [comment]
CSP is now a criterion on searx.space and searx.me is not a Searx instance anymore so I think this issue can be closed.

**Comment by dalf** [comment]
Duplicate of https://github.com/asciimoo/searx/issues/715 (schedule for the release 1.0).
