### ISSUE TITLE
Does searx reveal the IP address to the 3rd party search engines?

### ISSUE THREAD

**Issue by emanruse** [searx/searx#1550]
Does searx share/forward/otherwise disclose the IP address of  the host on which the search is performed with the search engines which show up in SERP? IOW: Does Google know my IP address when I use searx.me?

**Comment by dalf** [comment]
No. Your browser sends a request to the searx instance : so the searx instance knows your IP.
Then the searx instance sends requests to the search engines (google, etc...).

The search engines see the searx instance IP, not your IP. 

The results follow the way back. 

Of course, if you are the only person to use a searx instance, a search instance may infer that you are only one person using a proxy (searx).

Feel free to reopen the issue.

**Comment by emanruse** [comment]
Thanks.
