### ISSUE TITLE
Proxify image search for better privacy

### ISSUE THREAD

**Issue by emanruse** [searx/searx#1551]
Currently searx shows image results by directly exposing searcher to the 3rd party hosting the image. This happens through the `src` attribute of `img` tags.

It would be much better privacy-wise if searx serves as a proxy, without doing the above. The suggestion is to convert this:

```
<a href="http://example.com/image.jpg" ...>
    <img src="http://example.com/image.jpg" />
</a>
```
into this:
```
<a href="http://example.com/image.jpg" ...>
    <img src="http://<searx_instance>/proxy/image/image.jpg" />
</a>
```
There is no need for the searx instance to cache/host the image. It will simply do an internal (backend) redirect to the original, thus not exposing the searcher directly to the 3rd party. Then it is up to the searcher whether to expose himself to the 3rd party (by clicking the link). If he doesn't click - the 3rd party won't know anything about the searcher.

**Comment by dalf** [comment]
It is implemented.

There are two implementations :
- Either set the boolean to ```True``` here : https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L17 ( server.image_proxy )
- Either use [Filtron](https://github.com/asciimoo/filtron), and the URL in the ```result_proxy``` in [settings.yml](https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L17)

See https://www.21x9.org/en/searx.html and https://asciimoo.github.io/searx/dev/install/installation.html#installation

(Later, I think the best thing would a docker-compose.yml file to set up everything automaticaly including the Let's Encrypt certificate using Traefik or Caddy or whatsever)

**Comment by emanruse** [comment]
Then it should be enabled by default.
Currently I can't find any searx instance which has it enabled.

**Comment by dalf** [comment]
You can activate the image proxy in the preferences, General tab, image proxy.

For example, this instance has the default proxy activated by default (without going to the preferences).

The current proxy on searx.me has an issue.

Technical detail : IHMO , the default proxy (not Filtron), could be improved see #934.

**Comment by emanruse** [comment]
What do you mean by "this instance"?

I understand there is a preference but it is a cookie, so

- clearing cookies
- having cookies disabled by default (as a privacy aware user would)
- using incognito (as a privacy aware user would)

makes this preference futile and thus reduces privacy.

Would you kindly consider making the more private setting default? Non-privacy should always be an opt-in, not an opt-out.
