### ISSUE TITLE
Feature request: naver.com?

### ISSUE THREAD

**Issue by r4dh4l** [searx/searx#1553]
Hi,

would it be possible to add https://www.naver.com/ (which is a very popular search engine in South Korea)?

However: Thank you so much for searx!

**Comment by r4dh4l** [comment]
I've just upgraded to searx 0.18.0 and wanted to try naver (which I activated on default) with `!nvr South Korea` but got:

> Sorry! we didn't find any results. Please use another query or search in more categories. 

![Screenshot_2021-02-06_22-21-06](https://user-images.githubusercontent.com/44623983/107129970-a2901980-68c9-11eb-9eb3-5c62441984ad.png)

Did I make something wrong?

**Comment by unixfox** [comment]
Maybe the engine broke. Check the logs for any errors.

**Comment by return42** [comment]
It seems that the xpath selectors are no longer valid / it is a bug.

@r4dh4l do you like to open a new issue / thanks!
