### ISSUE TITLE
Feature request: Browser language dection for "language" similar to "default_locale"?

### ISSUE THREAD

**Issue by r4dh4l** [searx/searx#1554]
Hi,

is it possible to let detect Searx the browser language to set the search language?

I already tried to set `language : "en-US"` similar to

```
default_locale : "" # Default interface locale - leave blank to detect from browser information or use codes from the 'locales' config section
```

(so `language : ""`) but this causes an Internal Server Error.

What I would like to have is that someone with, for example, italian system/browser language automatically searches in italian language opening my searx node for the first time so that the user does not need to manually set the search language in the upper right corner. It would be nice to set "Default language" as default there, not a specific language.

**Comment by nfk** [comment]
Hello, probably the same issue that #844
