### ISSUE TITLE
Elasticsearch Engine Possibilities

### ISSUE THREAD

**Issue by Outstep** [searx/searx#1556]
Hello All,

I am working with an Elasticsearch engine as a core part of a search engine and I am wondering what it might take to setup a SearX engine that can query it as well?

Has there been any SearX search engine modules for Elasticsearch developed?  

If  so, then what problems were encountered?

Any information would be greatly appreciated.
Thanks and have a great day

**Comment by dalf** [comment]
searx is a proxy to existing search engine (a metasearch engine).

An engine is basically split into two methods : 
* The ```request``` function prepares the parameters to make an HTTP request.
* The ```response``` function creates the searx results from the HTTP response.

Inside a thread (with the GIL issues), searx : 
* call the ```request``` function 
* makes the HTTP requests
* call the ```response``` function the get the results.
* merge the results from the different engines.

See 
* https://asciimoo.github.io/searx/dev/engine_overview.html
* https://github.com/asciimoo/searx/blob/master/examples/basic_engine.py
* https://github.com/asciimoo/searx/tree/master/searx/engines

I guess you want to create a specific engine for your data and data model.

ElasticSearch has an HTTP API, but also some python package(s).

If you can make only HTTP request, then you can integrate ElasticSearch directly (implement the ```request``` function to set ```request_params['url']``` ).

If you need to use an Python package like elasticsearch-py, then you can hack [searx/search.py, function search_one_request](https://github.com/asciimoo/searx/blob/master/searx/search.py#L70) : 
* check if the functions ```request``` and ```response``` exist, if not call the ```process``` function which take the ```request_params``` as parameter and returns the results. (```process``` or whatever name you want) .

the PR #797 may interrest you.

**Comment by dalf** [comment]
I close the issue, feel free to re-open if you need more information.
