### ISSUE TITLE
Embedded searx-checker

### ISSUE THREAD

**Issue by dalf** [searx/searx#1559]
I've updated searx-checker to produce an html output, see https://searx.space
Source code based on work of @kvch : https://github.com/searx/searx-checker

It shows which engines currently doesn't work (warning : some engine may work / not work from time to time).

The thing that would be nice is to be able test the different searx instances.
Example : the first instance in https://stats.searx.xyz/ is https://searx.at
This instance answers quickly with the last version searx and good security configuration. 
But this instance doesn't work : whatever the engine is, whatever the query is, it always shows the same error message. It would be nice to show this information on stats.searx.xyz

Using searx-checker doesn't work : most the searx engines disable and severly limit json output.

A solution is to embed searx-checker inside searx. 
Every day searx makes a self test of all the configured engines. It can be done easily if each engine contains a list of queries that are supposed to provide answers (with a default one is not configured).
The result would be available on a /status URL : see https://searx.space/output/localhost.json for an example.

Then stats.searx.xyz can display a sum up of this information : 
* on the current view : number of working engine per instance (perhaps with a detail per category).
* another view (to create) : number of working instance per engine.

**Comment by unixfox** [comment]
That's a good idea! I often want to know which engine is not working on my instance. 
Meanwhile why not making instead a program written with a browser engine framework like selenium or puppeteer to check the availability of each engine on a searx instance?
I know it would take much longer and consume more ram and processor but that's the only way currently to avoid the json output restriction and other restrictions as well.

**Comment by kvch** [comment]
@dalf I really like the interface you have put together. Are you planning to add it to upstream?

@unixfox I think "integrating" searx-checker is a better idea. There is no need to use the JSON output of searx. All you need is a module which calls the `request` functions of every engine and check the results. Searx-checker only uses the JSON output, as it's an external tool. But once it's integrated, enabling JSON output is not required.

**Comment by dalf** [comment]
@kvch Thanks! 
Simple answer: I don't know when, but yes it would be great (no more searx-checker project, only searx).

For now, I've made a quick an dirty integration as you may have seen : 
* https://github.com/searx/searx-docker/blob/master/docker-compose.yaml
* https://github.com/searx/searx-checker/blob/master/loop.sh 
* result here: https://myinstance/status (access even by external javascript).

Nice to have : an API endpoint to get by engine
* the status (give response or not)
* the error rate (the engine may work but not always)
* the response time ( BTW https://github.com/asciimoo/searx/blob/master/searx/search.py#L77 should return False to avoid wrong response time for the current engine and some others).

So stats.searx.xyz (or something else) could display all these results, and chose an searx instance would be easier.
