### ISSUE TITLE
About stats.searx.xyz

### ISSUE THREAD

**Issue by dalf** [searx/searx#1560]
Is the code public and / or open source ?

For example it shows that the instances searx.kvch.me and www.search404.io have invalid certificates, but according to Firefox and Chrome there is no issue.

**Comment by Pofilo** [comment]
And we also don't know where are the tests executed. America, Europe ? It could be interesting to host it at multiple place for the `Response Time` field. This field is important I guess for newcomers.
I can host one instance at Paris.

**Comment by dalf** [comment]
Another point : it would be nice to display the certificate issuer because some intances are using CloudFlare ( adoll.ml and searx.lavatech.top for example).

**Comment by dalf** [comment]
Another feature request : use puppeteer to load the front page then make a basic search. Purpose : see if external links are loaded (see https://github.com/asciimoo/searx/issues/1572#issuecomment-483893979 ).

Note : it won't prevent someone to actually modify searx on the server to record everything.

**Comment by dalf** [comment]
Another thing to test : are the links modified by Javascript ? 
Example : 
```
var els = document.querySelectorAll("a[href^='https://www.amazon.com']");
for (var i = 0, l = els.length; i < l; i++) {var el = els[i];url = new URL(el.href);url.searchParams.append('tag','xxxxxx');el.href=url;}
```

See https://github.com/asciimoo/searx/issues/1241#issuecomment-488531620

It can be done at the last second, when the user clicks on the link : 
```javascript
link.addEventListener( 'click', function() {
    link.setAttribute("href","something else");
});
```

I'm not sure how to deal with that.

Either with puppeteer or just downloads the pages and make a diff (with html, js, css, everything).
Most probably this method requires a review, because some instance just modify the logo, and it's not a privacy problem.

[EDIT] One solution : make a list of reviewed instances. When a new instance is added, it is not displayed publicly until someone reviews the modifications. A fingerprint of the modifications is done. Later, any additional modifications require another review.

**Comment by unixfox** [comment]
[cloudquery](https://github.com/t9tio/cloudquery) could be used with the combination of the huge amount of regions provided by [zeit](https://zeit.co/docs/v2/platform/regions-and-providers) to test each searx instance from different locations and we wouldn't be blocked by most of the instances because cloudquery use puppeteer internally.

**Comment by nfk** [comment]
Hi @dalf, do you have more information about that subject? I would know how the version is fetched from stats.searx.xyz.

**Comment by dalf** [comment]
@nfk a search for "searx" is sent, output format HTML. Most probably the meta tag "generator" is used. Look at file rules.json in searx-docker project too.

**Comment by nfk** [comment]
@dalf thank you for your feedback it works well :)

Another point is about the CSP settings, do you have some advice or recommendation to setup the `Content-Security-Policy` with the right settings to keep auto-completion, image display etc...

Edit: ok there is a lot of information about CSP here https://github.com/asciimoo/searx/issues/715

**Comment by dalf** [comment]
@nfk  look here about CSP: https://github.com/searx/searx-docker/blob/master/Caddyfile#L32
You won't have "A+" but everything will work as intended.

The PR https://github.com/asciimoo/searx/pull/1647 will allow to have an "A+".

**Comment by fgossel** [comment]
Hi, I'm wondering who is maintaining the stats.searx.xyz site. I would like to remove one of mine old instance from the list which is currently marked as offline. Thanks.

**Comment by kvch** [comment]
AFAIK it's @dalf

**Comment by dalf** [comment]
https://stats.searx.xyz/ is hosted by https://21x9.org/en (see https://21x9.org/en/searx.html )

As I understand :
* https://github.com/asciimoo/searx/wiki/Searx-instances is scrapped, and all instances are automatically added to stats.searx.xyz (many times per day).
* the response time is the one of this query .../?q=searx (with default search engines for the general category), the queries comes from the IP 2a01:4f8:161:542e::2 or 5.9.58.49
* SSL and CSP columns seems to be updated once every day.

I host this website : https://searx.space/ updated once every day with the last commit of https://github.com/asciimoo/searx/ (master branch).
The code : https://github.com/searx/searx-checker

So to answer the question: to remove the instance from https://stats.searx.xyz the solution is to remove the instance from https://github.com/asciimoo/searx/wiki/Searx-instances

**Comment by fgossel** [comment]
> So to answer the question: to remove the instance from https://stats.searx.xyz the solution is to remove the instance from https://github.com/asciimoo/searx/wiki/Searx-instances

Thanks for your answer. 
My instance is not listed on the github instances list page anymore (search.tuxcloud.net) so I cannot remove it from that stats page. 

It looks like the stats page is generated with new instances only but not removing removed ones.

**Comment by ghost** [comment]
> cloudquery could be used with the combination of the huge amount of regions provided by zeit

I'm more than a bit late on this, but with the rollout of Zeit's new version of Now, you are no longer able to run puppeteer because of the 50mb limit. This was gotten around with cloudquery by using [@serverless-chrome/lambda](https://github.com/t9tio/cloudquery/blob/master/package.json), but serverless chrome was also recently blocked from working on Zeit as it is missing a required system dependency. 

As Zeit no longer supports any version of chrome, cloudquery would not run on Zeit. As far I know, serverless chrome still works on these platforms:

- Google Cloud Serverless
- AWS Lambda
- Azure Functions
- Cloudflare workers?

**Comment by dalf** [comment]
@evanmn , thank you for the information.

Since this issue was opened, [searx-stats2](https://github.com/dalf/searx-stats2) has been coded and deployed here: https://searx.space.

https://github.com/dalf/searx-stats2/issues/1 suggets to get response time from different location.

See the comments, I was thinking about AWS to run searx-stats2: create an intance / run searx-stats2 / stop the instance. But clearly open to any suggestions.

I close this issue, since searx.space has replaced stats.searx.xyz.

Thank you to the team who has run and maintain stats.searx.xyz.
