### ISSUE TITLE
create a new searx instance in five minutes using a docker-compose.yml

### ISSUE THREAD

**Issue by dalf** [searx/searx#1561]
The current recipe to have a fully working searx instance : 
* install searx is a [Flask](http://flask.pocoo.org/) application, so it fits the Python universe with uwsgi and (nginx|httpd|whatever).
* install [Morty](https://github.com/asciimoo/morty) to have better privacy on the image category.
* install [Filtron](https://github.com/asciimoo/filtron) to protect the instance from abusing robots and scripts.
* install a reverse proxy (nginx, httpd, whatever)
* make sure the HTTP headers, the certificate are setup and updated.

The current documentation provides detail about the [first](https://asciimoo.github.io/searx/dev/install/installation.html#installation) and [second](https://asciimoo.github.io/searx/admin/morty.html) steps. There are some details about the last step (reverse proxy), but not everything.

An idea : create Docker images for searx, filtron, morty and create a docker-compose.yml to install a new searx instance very quickly. The reverse could be [traefik](https://traefik.io) or [caddy](https://caddyserver.com) since they take care of the LetsEncrypt certificate. [searx-admin](https://github.com/kvch/searx-admin) can be included to easily configure searx (it requires some tunings to fit into Docker ecosystem).

[Watchtower](https://github.com/containrrr/watchtower) can be use to automatically update to the last version. [ Edit : there is [Ouroboros](https://medium.com/better-programming/automatically-update-docker-containers-f2ccc79f4313) ]

The purpose of this docker-compose.yml would be install a searx instance on blank DNS domain (no mydomain.com/searx, no customization of the themes), but I think it would help a lot of people.

Some of the work is already done see : https://www.21x9.org/en/searx.html

----

A completly different path to solve "the easy to install" quest : improve the packaging (example : create the httpd configuration according to the debian standard, etc...), it is a lot work for some distribution.

A crazy path : rewrite searx in golang and create one standalone executable (static binary).

[EDIT] Add searx-admin.

**Comment by dalf** [comment]
See https://github.com/searx/searx-docker

**Comment by dalf** [comment]
@asciimoo , @kvch : where the docker images should be published ?

Also see https://github.com/searx/searx-docker/issues/1

**Comment by dalf** [comment]
A first version is here : https://github.com/searx/searx-docker

The installation should be simple. Feel free to report bugs / issues or add a comment.

**Comment by masterofobzene** [comment]
The problem is that you asumed we are all on linux and you didn't explain how to do this on windows.
You just asumed all and gave strange commands without explaining anything.
