### ISSUE TITLE
Engines cannot retrieve results: wikidata (timeout), google (unexpected crash: CAPTCHA required) 

### ISSUE THREAD

**Issue by brand0nv1nc3nt** [searx/searx#1569]
Same as #1285, except /again/. I've observed this bug across all instances of searx that I could find including searx.me and searx.xyz All results are bing and duckduckgo.

I have attempted playing around with the languages and have deleted all cookies associated with the site, let me know if you need more info or need logs/version numbers.

Firefox 65.0.1 on linux Mint 18.3
Also installed are uBlock origin and HTTPS everywhere

**Comment by allyouaskfor** [comment]
Also having this issue and no results beyond the first page. s.cmd.gg and searx.me

**Comment by dalf** [comment]
### about the google engine

Long story short : for now, there is no solution to fix google Captcha problem.

Note : The google engine seems to work on the https://searx.info/ instance.

Your OS and browser configuration (cookie, extension, etc...) has no impact on this problem : on purpose, to keep your privacy, Searx makes a HTTPS request by itself :
```
👤 [ your browser ] ---> [ searx ] ---> [ google server ]
```

Please see #729

### about the wikidata engine

How often do you have this problem ?

**Comment by emanruse** [comment]
> Note : The google engine seems to work on the https://searx.info/ instance.

No results from Google. Most are from DDG, a few from bing and startpage.

**Comment by mawiwillme** [comment]
On https://searx.me it only gives results from bing, from https://searx.info I only see startpage, DDG, and bing. No results from Google on all instances I've checked.

**Comment by ghost** [comment]
This seems like a pretty significant issue, I would assume that most people are trying to get google results specifically. Is there no way to fix this unless google changes how their captcha works? I also can't get google results on any of the instances.

**Comment by brand0nv1nc3nt** [comment]
The wikidata problem seems to have resolved itself, the main focus was that google results are not appearing. As jmauss commented, it's pretty much the biggest reason people are using Searx, and I have a big feeling this problem was intentionally caused by google. 9/10 times the link I'm looking for is provided by google, so without those results I turn to Google itself. IMO this problem needs to be the #1 most focused issue.

**Comment by dalf** [comment]
About searx.info : if you go to https://searx.info/preferences you will see that the google engine is disabled by default. After I enabled it, I get results from google.

Without going to the preferences : use ```!google ....```

A workaround to the Google engine : you can use the startpage engine which gives the same results.

I close this issue, continue on #729

**Comment by emanruse** [comment]
> About searx.info : if you go to https://searx.info/preferences you will see that the google engine is disabled by default.

I see a checkbox next to google showing that it is allowed but that doesn't give results from google. But `!google` works indeed.
The question is: why this discrepancy.

> A workaround to the Google engine : you can use the startpage engine which gives the same results.

You mean the same startpage.com which doesn't work without JavaScript and pretends to be "the world's most private search engine"? :)
