### ISSUE TITLE
Let's Encrypt with Apache - .well-known/acme-challenge

### ISSUE THREAD

**Issue by ghost** [searx/searx#1573]
Hey all,

although searx works well with Nginx I prefer to run it with Apache which is basically no problem. Alas, I am not getting Let's Encrypt to work as somehow the document root (usr/local/searx in the specific vhost-config) isn't recognized when trying to get a certificate.

Domain: xxx.my.tld
   Type:   unauthorized
   Detail: Invalid response from
   http://xxx.my.tld/.well-known/acme-challenge/bff33der13_FZkf3f0IMf80iHHgdsdsL_lHU8zKmw4nQ

I know that this file therefore cannot be accessed by the Let's Encrypt bot so I think it must have something to to with the webroot. Did anyone of you encounter a similar issue or even managed to get it working?

Thanks in advance,

Oliver

**Comment by dalf** [comment]
Does these links help (use of [certbot](https://certbot.eff.org/) ) : 
* Apache : https://www.digitalocean.com/community/tutorials/how-to-set-up-let-s-encrypt-with-nginx-server-blocks-on-ubuntu-16-04
* Nginx : https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04

?

**Comment by ghost** [comment]
Thanks for the links, but the problem simply focuses on the searx-vhost. All other ones work well as they have "real" webroots residing at /var/www - no problems with these so far ;) !

Switching to Nginx with creating a certificate worked out like a charm so I think it's still the best way to serve the webfiles for searx!
