### ISSUE TITLE
HELP:

### ISSUE THREAD

**Issue by ctkqiang** [searx/searx#1578]
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/easy_install.py'
Consider using the `--user` option or check the permissions.

**Comment by patrick-othmer** [comment]
You are trying to install the package to a system folder which you don't have permissions to write to.

You could setup a virtual env. or try to use the docker version.

**Comment by ctkqiang** [comment]
> You are trying to install the package to a system folder which you don't have permissions to write to.
> 
> You could setup a virtual env. or try to use the docker version.

THANK YOU BROTHER!!!!!!IT WORKED!
