### ISSUE TITLE
Add support for Voat.co

### ISSUE THREAD

**Issue by SearchVoat** [searx/searx#1581]
I run the [SearchVoat.co](https://searchvoat.co) search engine for social media news aggregator [Voat.co](https://voat.co) and have received a request to ["Support Voat on Searx"](https://voat.co/v/voatdev/3175580).

What do I need to do?

**Comment by ghost** [comment]
**This URL may give some information on what you'll need to do:**
https://asciimoo.github.io/searx/dev/engine_overview.html

**Comment by kvch** [comment]
Voat is already part of searx. But I think the XPATH has changed in the results page, so it is not returning any results.

**Comment by SearchVoat** [comment]
Can you point me to that reference so I can try to fix it up?

**Comment by dalf** [comment]
https://github.com/asciimoo/searx/blob/a84caa22cf947e973c10aa968d35fb2bdda6d048/searx/settings.yml#L691

Starting from  line 691, there are the XPaths, and URL.
