### ISSUE TITLE
is searx able to exclude adult results?

### ISSUE THREAD

**Issue by chinapao** [searx/searx#1583]
Hi, 
For the legal reason, I would like to exclude the adult results from my searx instance.  I turned the safesearch to "Strict" but still there are lots of adult results.  I am using engine: google, bing, duckduckgo, wikipedia and startpage.  And all of them returns results of adult sites under the Strict mode.
Thank you very much for the help.
David

**Comment by kvch** [comment]
Not all engines implement safe search. You can check which one supports it by looking at the list of engines of an instance.
