### ISSUE TITLE
Startpage nows errors every few searches

### ISSUE THREAD

**Issue by ghost** [searx/searx#1601]
**Steps to reproduce:** 
- Searx v0.15, 
- Startpage enabled
- Language: EN (not EN-us or EN-ca)
- Search keywords like "soy bueno"
![image](https://user-images.githubusercontent.com/49014564/58292716-5ec14d80-7d90-11e9-9861-0437e1099a64.png)

**NOTE:** The issue does not always happen and the contents of the unknown string format varies. I've tested the issue on multiple instances.

**Comment by rachmadaniHaryono** [comment]
can you post the error traceback?

**Comment by ghost** [comment]
> 
> 
> can you post the error traceback?

I do not host any instance myself, I use public instances listed on the project's wiki.

**Comment by c33s** [comment]
i used to search directly with startpage but after selling startpage to a "data" company, i was looking for alternatives and found searx.

maybe relevant for this issue:

i noticed in the last, i think 2-3 weeks, that searching on startpage  leads to no results. most of the time pressing the searchbutton again leads to a result but sometimes it requires  pressing the button 2-3 times.

**Comment by virtadpt** [comment]
Startpage got sold to a data collection company.  They've undoubtedly changed their site in incompatible ways.  It might be time to DV and del that engine in Searx.
