### ISSUE TITLE
[Question] Storage usage

### ISSUE THREAD

**Issue by SuperSandro2000** [searx/searx#1604]
This project sounds quite interesting and ambitious. I can imagine that a metasearch engine uses quite a lot of disk storage, CPU and bandwidth. Am I right with this assumption? The docs are a bit lacking and I could not find answers to my questions.

**Comment by rachmadaniHaryono** [comment]
i have been using this for days now. there maybe more usage of bandwidth because on each search you put request to multiple search engine

but there is no database or storage usage other than installed files

**Comment by SuperSandro2000** [comment]
Thanks for the quick answer. Bandwidth is a concern for me so this could be a bit tricky to selfhost.

**Comment by kvch** [comment]
Searx can run on a RaspberryPi without any issues.
