### ISSUE TITLE
Handle parsing of the new Google UI

### ISSUE THREAD

**Issue by unixfox** [searx/searx#1609]
In a previous issue #1596 we talked about Google forcing the new UI to every  Searx instance thus breaking the current parser and having no results when doing a search. This has been temporally fixed by changing the user agent to Internet Explorer on this PR #1597.

But this might not work/break in the future if Google decide for example to drop the support for Internet Explorer or if they found a way to make their new UI compatible with Internet Explorer.

So we need to rework the `google.py` by introducing a new parser that can handle the new Google UI.
A PR #1603 has been opened but it's still in work in progress (see [this review](https://github.com/asciimoo/searx/pull/1603/files/481b0de121bc4519530143633d299e52060836f1)).

**Comment by rachmadaniHaryono** [comment]
hi, i am the one who made #1603 pr. this case is not often happen to me so i have difficulties to test it

if anyone want to help me, you can put these code on that pr

<original code removed>

```python
def response(resp):
    ...
    from datetime import datetime
    dts = datetime.now().strftime('%Y%m%d_%H%M%S')
    is_new_parser = False
    if not results:
        is_new_parser = True
        with open('google_{}.html'.format(dts), 'w') as f:
            f.write(resp.text)
        ...
    ...
    # return results
    if is_new_parser:
        import yaml
        with open('google_{}.yaml'.format(dts), 'w') as f:
            yaml.dump(results, f)
    return results
```

what this will do is to create html and yaml file from the engine. this can be used on #1606 to compare it with different result set

e: ~~yaml part is optional. you can skip it and generate yaml later. or you can change the code above so it will only write yaml if no result given from first parser.~~

e3: remove original code and fix the second one
