### ISSUE TITLE
Is it searx, searX, or Searx

### ISSUE THREAD

**Issue by comradekingu** [searx/searx#1611]
Needed the correct spelling, found different results.
https://searx.me/about all searx
https://github.com/asciimoo/searx all searx too, (but then everything else is lowercase)
https://en.wikipedia.org/wiki/Searx all Searx
https://searx.me/ looks a lot like searX though that is stylized (?)

**Comment by kvch** [comment]
The preferred version is searx. Confusion started to spread when the logo with a big X was introduced on upstream. But I consider that just a design element, not actual uppercase X.
With regard to the Wikipedia page, I have no idea who and why he/she wrote Searx.

**Comment by comradekingu** [comment]
@kvch Thank you :)

**Comment by ghost** [comment]
Big capital letter at the start is normal on Wikipedia and you have to use DISPLAYTITLE to have the title set to searx instead of Searx if you type in searx so big S there is simply an artifact of the MediaWiki CMS.

**Comment by gkaklas** [comment]
Sorry for bumping; has your question been answered, is there a need for any action/decision (e.g. editing something to make it more clear)? Can this be closed? :thinking:
