### ISSUE TITLE
[Feature Request] Standard right-click and add to browser

### ISSUE THREAD

**Issue by Dr-Flay** [searx/searx#1616]
Most search engines make it possible for browsers to detect that the search box is a search box, so that when you right-click in it you can add it to your browser with all the correct info needed.
This will work for all browsers so no special links are needed, just the right info in the code.
I wanted to be more useful and provide a link, but alas I was informed by a friend how it works but not the specifics.

Mind you, I would note that if a user cannot work out how to add searx manually, it is probably not the right search engine for them ;)

**Comment by AldisOzols** [comment]
I can't work out how to add searx to Chrome manually, but I still would like to use it.

I've tried 
searx.me/searchterm
searx.me/?searchterm
searxme/?=searchterm
seatrx.me/?="searchterm"

None of them worked.

**Comment by rachmadaniHaryono** [comment]
based on the default search, it should be

```https://searx.me/?q=%s&category_general=on&time_range=&language=en-US```

e: other alternative is to use duckduckgo's bang

```https://duckduckgo.com/?q=!searx+%s&t=canonical&ia=web```

**Comment by AldisOzols** [comment]
Thank you!

I'll try it.

**Comment by Dr-Flay** [comment]
@AldisOzols This is a "Feature request" thread for something that is not manual installation.
How to add searx manually is already clearly explained in a previous issue.

**Comment by AldisOzols** [comment]
I apologise.

I am new to both searx and GitHub.

When I searched the issues page for "add to browser", this was the first entry that came up and from the title it seemed relevant.

**Comment by Dr-Flay** [comment]
No problem.
There are a few similar issues opened, and it may seem natural to go for the most recent, but it is worth reading the old ones first to see if your own issue was mentioned.
You did try to do it correctly so you did look. Often people don't look for an existing thread and just post a new one.

**Comment by guidot** [comment]
Mozilla [documents](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#Autodiscovery_of_search_plugins) what's necessary for this to work. It's called  [OpenSearch](https://github.com/dewitt/opensearch) autodiscovery. Works in all major browsers.
The  `<head>`-element needs this
```
<link rel="search"
      type="application/opensearchdescription+xml"
      title="Searx"
      href="pluginURL">
```
added, where `pluginURL` points to an XML-file that contains
```
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                       xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>[SNK]</ShortName>
  <Description>[Search engine full name and summary]</Description>
  <InputEncoding>[UTF-8]</InputEncoding>
  <Image width="16" height="16" type="image/x-icon">[https://example.com/favicon.ico]</Image>
  <Url type="text/html" template="[searchURL]">
    <Param name="[key name]" value="{searchTerms}"/>
    <!-- other Params if you need them… -->
    <Param name="[other key name]" value="[parameter value]"/>
  </Url>
  <Url type="application/x-suggestions+json" template="[suggestionURL]"/>
  <moz:SearchForm>[https://example.com/search]</moz:SearchForm>
</OpenSearchDescription>
```
The terms in brackets are placeholders. See the description in the linked docs.

**Comment by return42** [comment]
Sorry for the late reply .. OpenSearch is already supported by searx.

I haven't checked all instructions:

- Firefox: https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox
- Microsoft Edge: https://support.microsoft.com/en-us/help/4028574/microsoft-edge-change-the-default-search-engine
- Chrome based browsers: are a bit [grumpy](https://support.google.com/chrome/forum/AAAAP1KN0B0Po1hHSjkaZA/?hl=en&gpf=%23!topic%2Fchrome%2FPo1hHSjkaZA) / the `<link re="search" ..>` has to be at the root URL to be autodiscovered by Chrome / [Chromium only adds sites that the user navigated to without a path. For example http://mysite.com, but not http://mysite.com/foo.](https://www.chromium.org/tab-to-search)

**Comment by AldisOzols** [comment]
Thank you!

I wasn't expecting any more replies, so please don't feel sorry!

I'm grateful that you took the time to reply at all. I'll save your reply
so I can find it if I need it.

In the meantime, I worked out how to do it myself. :)

But I appreciate your help anyway.

Can I help you too?

Could searx use a small donation?

You don't have to tell me. I'll find out. I know where to search! :)

Regards

Aldis
