### ISSUE TITLE
enhanced stats-functions

### ISSUE THREAD

**Issue by pointhi** [searx/searx#162]
I'm not sure if this feature would be good for searx, but it would be interresting adding an enhanced stats-site.

I'm thinking of things like `searchquerys/day or hour`. Things which are interesting, but nothing which is decreasing the privacy of the users. (General stats over all users)

This is only an idea, no "must have" :-).

**Comment by asciimoo** [comment]
I agree, a better stat/status page would be useful, but it's a hard question that the displayed data is sensitive or not. E.g. you can estimate the usage of the searx instances from the `query/time` information

**Comment by dalf** [comment]
Some ideas : 
- Record and count the number of category combination. Purpose : adapt or not the UI / UX to the most common use cases.
- Record the server and browser response time (using the Navigation Timing API). Purpose : find the bottleneck in the response time (engines, searx code, javascript).
- Create a time out counter in addition to the error counter. (Note :  the current implementation handles the Read timed out exception has any other exception).

**Comment by dalf** [comment]
I have created a metrology branch with more detail statistics : fa4a795982ef6d25e204661c4a3423efeeb1de75

This allow to see that the callback takes sometimes far more time than the HTTP request.

It doesn't solve the issue #199

**Comment by dalf** [comment]
About the issue #199 , if there is one process and many threads it seems to solve the problem. I don't know how it's scale.

uwgi configuration :

```
# Number of workers
#workers = 16
processes = 1
threads = 16
```

Yes 16 threads because of the image proxy.

**Comment by asciimoo** [comment]
@dalf very cool stat enhancements.
I'm not sure, that searx is fully thread safe, we need to check it. With twisted it's guaranteed.

**Comment by dalf** [comment]
About thread safety :  http://flask.pocoo.org/docs/0.10/quickstart/ look at the "Accessing Request Data" section.

About global variables, it requires some changes : http://flask.pocoo.org/docs/0.10/appcontext/

Or may be, in some cases, we can implement thread safety by yourself (statistics for example ?) 
Or we can think about Twisted.

**Comment by dalf** [comment]
I'm working on a new version of the stats page : 
![prototype](http://oi57.tinypic.com/2uz5xcn.jpg)

It is based on [jqplot](http://www.jqplot.com), I don't know if this is good choice.

**Comment by Cqoicebordel** [comment]
Whaou !

**Comment by dalf** [comment]
Commit in https://github.com/dalf/searx/tree/metrology but still unfinished.

**Comment by pointhi** [comment]
It look good to me. I'm not sure, but probably we should display Errors in a procentual way (at least the scaling)

Otherwise, engines which always thrown an error, but are less used would look better as engines which are allways used, but only throw partly errors.

**Comment by dalf** [comment]
I've updated the metrology branch. Here an example : 
https://al-f.net/stats

New things : 
- errors count are displayed as a percentage of the total request count for an engine.
- in the "Page loads" section, you can click on an engine to display the different quartiles.
- new section "Search page", which display the average and the quartiles for the main search page.

These charts and stats can help to reduce response time as we can see
- which engine is slow, how often.
- how slow is the rendering code.

But obviously it reduces privacy : below 100 requests (per engine or globally), you can guess how many requests have been sent.

So, it's bring me to some questions : why stats ? for who ?

From user point of view, the score and the page loads section can help to choose the right balance between the response time and useful responses.

In this case, the response time and the score should be displayed in the "preference" page, where the user can disable a search engine.

From the developer point of view, I think all these details can be helpful.

May be, the stats page should be display to the administrator and no one else. 
But the administrator is not necessarily a developer...

**Comment by asciimoo** [comment]
@dalf it's very impressive and contains a lot of useful info about how to optimize/tweak engines. Way better than the current one for these purposes.
And the question is also good - who is the target of the stats view?
This detailed view is mostly useful for developers/administrators and leaks some info as you mentioned, but the engine response times and result numbers/scores can help the users to configure their engine settings. So maybe a hybrid solution could work, where there is a simple stat page for users and a detailed (maybe only in debug mode?) for devs/admins.

**Comment by return42** [comment]
5 years later .. is there anything we can do? .. if so, please reopen the issue.
