### ISSUE TITLE
Thoughts on Baidu, Sogou, Yandex via searx?

### ISSUE THREAD

**Issue by dm17** [searx/searx#1622]
I'm guessing this is the list of search engines searx can currently use as sources:
https://github.com/asciimoo/searx/wiki/possible-search-engines

"Possible" throws me off a bit; not sure if that means they can be used now because at the top it says, "which could be useful as engine and waiting for an implementation." So potentially unimplemented?

Anyway, I'd like to look into adding Baidu, Sogou, and Yandex. Thoughts?

**Comment by rachmadaniHaryono** [comment]
i create yandex image but only tested for first page here

https://github.com/rachmadaniHaryono/searx/blob/master/searx/engines/yandex_images.py

i have no idea how to get next page

also there is also thread here https://github.com/asciimoo/searx/issues/430

**Comment by virtadpt** [comment]
Those are indeed possible search engines, and not necessarily implemented at this time.  If you want to see an up-to-date list of the search engines supported by Searx, check out the settings.yml file: https://github.com/asciimoo/searx/blob/master/searx/settings.yml

**Comment by jackTaw88** [comment]
@virtadpt I could not understant this topic. I can search on searx via yandex. How you say that is not implemented?

**Comment by rachmadaniHaryono** [comment]
yandex image and yandex video are still not implemented yet

**Comment by dalf** [comment]
Baidu : this issue is related to https://github.com/asciimoo/searx/issues/1432 : it is not possible to implement this engine because all links are encrypted. Yes searx can proxy the encrypted linked, but searx merges links between different search engine, and this step won't be possible for the Baidu engine.

Sogou : same as Baidu. Note : The encrypted links can't be compared with the one provided by Baidu.

**Comment by dalf** [comment]
I close this issue: 
* Baidu / Sogou : look at comment https://github.com/asciimoo/searx/issues/1432#issuecomment-511137295
* Yandex : https://github.com/asciimoo/searx/issues/430
