### ISSUE TITLE
Search engines settings are not set with URL

### ISSUE THREAD

**Issue by jackTaw88** [searx/searx#1632]
Hi,

I am copying the URL which writes on settings. After I clean my browser history/cookies and go this URL, my search engines are getting default. not my settings (enabled search engines) getting back. 

I try this on 3-4 searx instances.. All have the same bug.

Is there anything I miss? Or this is a bug or un-implemented feature?

Is there any way/trick to get my search engines back after cookies are deleted?

Thank you

**Comment by rachmadaniHaryono** [comment]
might be related to https://github.com/asciimoo/searx/issues/1598

**Comment by unixfox** [comment]
I cannot reproduce the bug. I created a custom preferences one year ago, and I used the same one now, and it still works with the same URL.

**Comment by lfom** [comment]
I had the same problem, and maybe this is a workaround: get the preferences URL and remove the ending that is used for searching (`&q=%s`) and point the URL to the settings page by replacing the site address with one that point to the preferences page, then open the modified URL (optional: check the settings to make sure your configuration was applied actually) and hit **save** at the bottom of the page. Your custom settings should remain now.

For instance, the saved preferences URL is:
`https://searx/?preferences=HUGE_HASH&q=%s`

Then use this one instead to save it to another browser:
`https://searx/preferences?preferences=HUGE_HASH`
