### ISSUE TITLE
About searx instances wiki

### ISSUE THREAD

**Issue by Pofilo** [searx/searx#1646]
Hello, 

I want to tell a problem about our [list of instances](https://github.com/asciimoo/searx/wiki/Searx-instances) in the wiki:

Is github providing tools to moderate this wiki ?

My concerns is about the fake instances added in the list. For example @insoxin added twice his instance [isoyu.com](http://isoyu.com/) and I had to revert it twice ([here is a link](https://github.com/asciimoo/searx/wiki/Searx-instances/_compare/058cba8%5E...058cba8) of the changes he made)

3 concerns:

- first, the simplest one: the website is not in `https`, he is lying about saying that there is a Let's Encrypt certificate.
- second, all the results are in chinese, I don't thinking we should accept an instance (in the list) that only return chinese results.
- third, we have to think about it a bit more. 

The [welcome page](http://isoyu.com/) is changed, this is not a problem, however the [about page](http://isoyu.com/about/Index20.html) is exactly the same as the [Qwant one](https://about.qwant.com/fr/). All the Qwant website has been copied, look at the [legal notices](http://isoyu.com/about/Index17.html), the same as the [Qwant one](https://about.qwant.com/legal/legal-notices/). As a conclusion, all the Qwant website has been copied. 

@insoxin will add his link again and again, I don't know if we have a way to deal with that ...
He can do what he wants with Searx as long as he respects the license. Let's talk about this license, it means that all changes made to the code must be documented, and it's not. Finally, accepting a link to his instance means that we agree and we accept what he is doing (copying the Qwant website), and I don't think we should accept this kind of things.

What do you think about that ?

I also send a message to Qwant to warn them about this copy.

**Comment by insoxin** [comment]
*Bonjour, laissez-moi répondre en premier.
1.http / ssl existe en même temps, mais je n’ai aucune restriction obligatoire, vous pouvez ajouter manuellement https pour accéder à
Dans ma base d’utilisateurs, les navigateurs de certaines personnes ne prennent pas en charge le ssl, j’ai besoin de bien prendre en compte
2. Vous n'acceptez pas une seule langue, nous fournissons également d'autres langues dans les paramètres, telles que le français.
Mais vous ne pouvez pas prendre une langue pour ouvrir une raison distincte, cela me met en colère.
3. Quant à la copie de la page d'accueil,
Je peux vous répondre avec le compte twitter officiel.
Bien sûr, vous pouvez également afficher les commentaires avec Ctrl + U ou F12.
Discussion rationnelle, merci
                                                                                 ----- La traduction française vient avec Google*

---
Hello, let me answer first.

1.http/ssl exists at the same time, but I have no mandatory restrictions, you can manually add https to access

In my user base, some people's browsers do not support ssl, I need to fully consider

2. You don't accept a single language, we also provide other languages in the settings, such as French

But you can't take a language to open a separate reason. It makes me angry.

3. As for the welcome page copy,

I can reply you with the official twitter account.

Of course, you can also view comments with Ctrl+U or F12.

Rational discussion, thank you, I unsubscribed this issue, I hope you get a satisfactory answer

**Comment by Pofilo** [comment]
1. This morning, the https was not provided on your instance, plus, you were telling it was **Let's Encrypt** , right now, it is by **TrustAsia Technologies, Inc**.

2. If you can't even do a research in english, I don't think you can tell yourself as a searx instance.

3. Funny you changed all pages. Okay you delete the pages copied from Qwant. Why did you forget the FAQ page (it still links to a copied Qwant logo) ? And please, @insoxin don't say I'm a layer and you never copied anything from Qwant, Internet never forgets.

I just ask you to not add your instance to the searx instance as it is not one. And don't forget about Licenses, you should provide all modifications mades to the code.

**Comment by kvch** [comment]
What if we add the list of instances to the repository? If someone wants to add his/her own, he/she opens a PR and we can validate that the information provided is correct.

We should add a disclaimer that we are not saying that specific instance can be trusted. 

We could check from time to time the instances maybe using searx-checker to see if they are still healthy and usable.
