### ISSUE TITLE
https://unmonito.red/ fails with ERR_HTTP2_PROTOCOL_ERROR/ERR_SPDY_PROTOCOL_ERRORs

### ISSUE THREAD

**Issue by sysfu** [searx/searx#1648]
ERR_HTTP2_PROTOCOL_ERROR. Occurs with IE 11, Edge and Edge Dev.

SSLLab server test does not show any immediate problems. https://entrust.ssllabs.com/analyze.html?d=unmonito.red&s=94.130.34.40&hideResults=on

Vivaldi and Brave have the same no connect problem but slightly different error.

ERR_SPDY_PROTOCOL_ERROR

Reproduced on two different Windows 10 and Windows Server 2016 systems.

**Comment by sysfu** [comment]
Accidentally posted on wrong project, pls delete

**Comment by sysfu** [comment]
I've been unable to connect to https://unmonito.red/ for weeks now. Everytime I get redirected there from https://searx.neocities.org it's a search fail. Was unable to find any contact information for the web site operator. Can this site be removed from the search pool until they resolve the connectivity issues?

**Comment by dalf** [comment]
https://searx.neocities.org/ is not maintained by this project. 

You can contact the author using the email in this web page:
https://searx.neocities.org/changelog.html

I understand that's may be confusing.

**Comment by sysfu** [comment]
Thanks @dalf . I will take this up with the Neocities contact. 

If you are able to locate the contact information for the admin running the https://unmonito.red/ site, please share.

Perhaps unmonito.red should be removed from the wiki's [list of running instances](https://github.com/asciimoo/searx/wiki/Searx-instances) for the meantime.

**Comment by unixfox** [comment]
An issue https://github.com/searx/searx/issues/1972 is opened for allowing to specify a contact information in order to get in touch with the maintainer of the specific instance.

For now, I'm closing this issue because unfortunately the Searx project can't control the individual instances.
