### ISSUE TITLE
Results fetched from docmentation sites are shown as raw HTML

### ISSUE THREAD

**Issue by etanot** [searx/searx#1649]
Search results which are fetched from [git-scm](https://git-scm.com) is in HTML language.

![git2](https://user-images.githubusercontent.com/28824347/61836998-5362cf00-ae72-11e9-9a23-a83ec69fad69.png)

Whereas, on [git-scm](https://git-scm.com/docs/git-add) result is shown as follows

![git-scm](https://user-images.githubusercontent.com/28824347/61837439-5363ce80-ae74-11e9-943d-b8b24dd355a8.png)

Search any query related to git (like git add, git commit, etc), if it's fetched from git-scm, it should be in HTML language, inside the info box.

**Edit:**

Seems like, problem is not only with git-scm; but with most of the documentation site related to programming language. For instance try these searches:

* Python3 docs: [!ddd python math.sqrt](https://searx.me/?q=%21ddd%20python%20math.sqrt&categories=none&language=en-US)
* Nodejs docs: [!ddd node repl](https://searx.me/?q=%21ddd%20node%20repl&categories=none&language=en-US)
* Cppreference: [!ddd c sqrt](https://searx.me/?q=%21ddd%20c%20sqrt&categories=none&language=en-US)

**Comment by dalf** [comment]
URL to reproduce the bug (doesn't happen with the simple theme):
https://searx.me/?q=!ddd+git+add&language=en-US&time_range=&category_general=on&safesearch=0&theme=oscar

Most probably, line 8 on infobox.html, missing ```| safe```:
* https://github.com/asciimoo/searx/blob/master/searx/templates/oscar/infobox.html#L8
* https://github.com/asciimoo/searx/blob/master/searx/templates/simple/infobox.html#L5

**Comment by etanot** [comment]
@dalf, Can I make a pull request for this issue?
