### ISSUE TITLE
Add PeerTube-Index.net in Video section

### ISSUE THREAD

**Issue by Popolon** [searx/searx#1662]
Peertube-index is an engine specialised in search of PeerTube instances.

https://peertube-index.net

**Comment by jibe-b** [comment]
There now is free&opensource PeerTube search index which indexes the 500+ PeerTube instances referenced by Framasoft https://sepiasearch.org/ (source code: https://framagit.org/framasoft/peertube/search-index )

**Comment by Popolon** [comment]
As PeerTube engine is now already integrated in SearX #2109, I believe that this ticket can be closed.

**Comment by Popolon** [comment]
Looking a bit more to the the current engine for peertube, I see it is stuck to https://www.peertube.live instance. There is no option to change it, so sepia is perhaps a  complementary search engine, or/and the possibility to change the peertube instance used for research. some instance choose to not peer with some others. having multiple entries has does sepia is probably a more wide search method.
