### ISSUE TITLE
Timeout limit breaks moving between pages

### ISSUE THREAD

**Issue by aveao** [searx/searx#1664]
Timeout limits introduced on https://github.com/asciimoo/searx/commit/72029d27ded8d93ab891c616d6bffbe8d3a67dd2 cause pressing "next page" button to cause in a search error.

Returning back to commit 2179079a9173b33b81e1084fc1e8e181c19ef8e9 fixes this problem.

![](https://elixi.re/i/7q0l9w8t.png)

```
ERROR:searx.webapp:search error
Traceback (most recent call last):
  File "searx/webapp.py", line 510, in index
    search_query, raw_text_query = get_search_query_from_webapp(request.preferences, request.form)
  File "/home/ave/Projects/searx/searx/search.py", line 285, in get_search_query_from_webapp
    raise SearxParameterException('timeout_limit', raw_time_limit)
SearxParameterException: Invalid value "None" for parameter timeout_limit
```

edit; for some reason, it seems like it doesn't happen now as I'm testing, but I will wait until I figure out why it happened in the first place to close it.

**Comment by aveao** [comment]
It seems like timeout_limit is returned as None in some cases, which is what causes this issue:

![](https://elixi.re/i/3nhez50p.png)

No clue yet why it happens though.

**Comment by aveao** [comment]
Setting a default limit in

https://github.com/asciimoo/searx/blob/72029d27ded8d93ab891c616d6bffbe8d3a67dd2/searx/webapp.py#L632

in place of `None` seems to fix the problem, though there's likely a more elegant fix for this.

**Comment by dalf** [comment]
Thank you for the detailed report.
Can you try the PR #1665 ?
