### ISSUE TITLE
Searx Doesn't Start Debian 10

### ISSUE THREAD

**Issue by SubstituteR** [searx/searx#1670]
After following the installation guide 
https://asciimoo.github.io/searx/dev/install/installation.html
and confirming that everything works when starting searx manually with

> python searx/webapp.py

And checking my nginx reverse proxy.
Doing it this way works 100%, however when I attempt to use uwsgi to demonize the process it doesn't actually start.
My uwsgi log shows 

> Tue Aug  6 04:10:59 2019 - added /usr/local/searx/ to pythonpath.
Tue Aug  6 04:10:59 2019 - spawned uWSGI master process (pid: 31839)
Tue Aug  6 04:10:59 2019 - spawned uWSGI worker 1 (pid: 31846, cores: 1)
Tue Aug  6 04:10:59 2019 - spawned uWSGI worker 2 (pid: 31847, cores: 1)
Tue Aug  6 04:10:59 2019 - spawned uWSGI worker 3 (pid: 31848, cores: 1)
Tue Aug  6 04:10:59 2019 - spawned uWSGI worker 4 (pid: 31850, cores: 1)
Tue Aug  6 04:11:01 2019 - WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55def990df50 pid: 31846 (default app)
Tue Aug  6 04:11:01 2019 - WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55def990df50 pid: 31848 (default app)
Tue Aug  6 04:11:01 2019 - WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55def990df50 pid: 31847 (default app)
Tue Aug  6 04:11:01 2019 - WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55def990df50 pid: 31850 (default app)

and my nginx error log shows

> 2019/08/06 04:10:13 [error] 31469#31469: *1 connect() failed (111: Connection refused) while connecting to upstream, client: {removed}, server: localhost, request: "GET /searx/ HTTP/1.1", upstream: "http://127.0.0.1:8888/searx/", host: "{removed}"

This leads me to believe it's an issue directly related to uwsgi.

For now I will use a work-around by putting the process into tmux, however I would like to figure out why uwsgi is failing.

**Comment by Flunkyball** [comment]
I got the same issue and found a solution for that:

in /etc/uwsgi/apps-available/searx.ini change

`http = 127.0.0.1:8888` to `http-socket = 127.0.0.1:8888`

For some reason with "http" only uwsgi did not open any port.

**Comment by SubstituteR** [comment]
I'll give that a try @Flunkyball , thanks for the find. 😄

**Comment by return42** [comment]
Closed due to inactivity.

BTW: Linux distros ship old searx versions .. its recommended to install searx according to our installation instructions.
