### ISSUE TITLE
backport from my-spot

### ISSUE THREAD

**Issue by dalf** [searx/searx#1674]
May be these commits are interesting to backport into searx:
* https://gitlab.e.foundation/e/cloud/my-spot/commit/812bac9d9649b5ba53a97a43c15b739692706afa
* https://gitlab.e.foundation/e/cloud/my-spot/commit/a9e2a3a01c19dfcb340c211a6590fe4948301803
* https://gitlab.e.foundation/e/cloud/my-spot/commit/6e676cc0d25c38106e0256e406d9b3e9041f6dfd
* https://gitlab.e.foundation/e/cloud/my-spot/commit/2cc736bdea21aab0c7b1680622df9c1496526411

**Comment by rachmadaniHaryono** [comment]
https://gitlab.e.foundation/e/cloud/my-spot/commit/6e676cc0d25c38106e0256e406d9b3e9041f6dfd

i am interested on that commit will create pr with minimal change later

**Comment by dalf** [comment]
* commit https://gitlab.e.foundation/e/cloud/my-spot/commit/812bac9d9649b5ba53a97a43c15b739692706afa
fixed by https://github.com/searx/searx/commit/678699beaf97184a9059b0c6514b1a51c7e6dfd0
* commit https://gitlab.e.foundation/e/cloud/my-spot/commit/a9e2a3a01c19dfcb340c211a6590fe4948301803 fixed by https://github.com/searx/searx/commit/1022228d950c2a809ed613df1a515d9a6cafda7c

**Comment by dalf** [comment]
* commit https://gitlab.e.foundation/e/cloud/my-spot/commit/6e676cc0d25c38106e0256e406d9b3e9041f6dfd : see https://github.com/searx/searx/pull/1675#issuecomment-621165598
* commit https://gitlab.e.foundation/e/cloud/my-spot/commit/2cc736bdea21aab0c7b1680622df9c1496526411 : see PR #2244 and PR #2246
