### ISSUE TITLE
duckduckgo engine: paging is not working

### ISSUE THREAD

**Issue by dalf** [searx/searx#1677]
The "without JS"  ddg UI uses the POST method on the second page, not sure if it is related.

**Comment by luckrill** [comment]
duckduckgo html mode

try
https://duckduckgo.com/html?q=readmorejoy&s=0&dc=0
https://duckduckgo.com/html?q=readmorejoy&s=30&dc=30
https://duckduckgo.com/html?q=readmorejoy&s=60&dc=60

the result is the same.

**Comment by luckrill** [comment]
I develop enjoysearch project:
https://search.readmorejoy.com/
https://github.com/luckrill/enjoysearch

it's same with meet duckduckgo pagedown issue. 
My method: 
kv = {'q':key, 's':s, 'dc':dc, 'v':'l', 'o':'json', 'api':'/d.js'}

now pagedown can work now.
