### ISSUE TITLE
[Engine] Startpage stop working

### ISSUE THREAD

**Issue by joshu9h** [searx/searx#1679]
Startpage gives noresults on searx

**Comment by unixfox** [comment]
which searx instance? searx.me?
If that's the case you may find another searx instance here that would work with startpage: https://github.com/asciimoo/searx/wiki/Searx-instances

**Comment by joshu9h** [comment]
@unifox i have tried couple of searx instance also searx.me
also the same 
!sp test
show no results

**Comment by unixfox** [comment]
ok I just tested and I confirm that I can reproduce the bug on my own searx instance.

**Comment by scottwallacesh** [comment]
Same for me.

**Comment by ghost** [comment]
Yes, it stopped working at that time.

Oh yeah, pretty sure Bing isn't working either.

**Comment by joshu9h** [comment]
https://github.com/asciimoo/searx/pull/1683/commits/9f6d041fe5bb308837afa2440777dd36a6835fea
Has fix the problem
THx

**Comment by unixfox** [comment]
Why closing the issue if the pull request is not merged yet?
