### ISSUE TITLE
Installation guide does not work with Debian Buster

### ISSUE THREAD

**Issue by sven222** [searx/searx#1684]
In the current installation guide (https://asciimoo.github.io/searx/dev/install/installation.html) for Debian/Ubuntu is missing some installation files, if running on Debian 10 Buster. For running system you should add the following to the apt-get install line in part Basic Installation:
virtualenv python-requests python-yaml python-pygments python-werkzeug python-flask python-flask-babel python-lxml python-dateutil
With this added, I had a working searx engine.

**Comment by hmrhkr** [comment]
With my Debian Buster instance i had no problem with following the standard instalation guide (https://asciimoo.github.io/searx/dev/install/installation.html) worked like a charm for me

**Comment by ghost** [comment]
Is this link still working?

**Comment by return42** [comment]
No, .. since PR #1803 is merged into master, this issue make no longer sense / I will close it.
