### ISSUE TITLE
Fix info box: Data fetch from Wikipedia page isn't showing properly inside the info-box

### ISSUE THREAD

**Issue by etanot** [searx/searx#1685]
Data fetch from Wikipedia page isn't showing properly inside the info-box.

* **Ambiguous Pages:** For some search results it only show title matched to searched keyword nothing else (try these keywords: [ip](http://search.disroot.org/?q=ip&categories=general&language=en-US), [tcp](http://search.disroot.org/?q=tcp&categories=general&language=en-US) etc).

![ip](https://user-images.githubusercontent.com/28824347/63648783-211fe800-c724-11e9-9073-be69ef7ebee4.png)

see there are two info-boxes one with empty content other with only one line in it.

* **Pronunciation:** If fetched content have pronunciation within it, either show it inside parenthesis or drop it like DDG's [info-box](https://duckduckgo.com/?q=git+wiki&t=ffab&ia=web).

![git](https://user-images.githubusercontent.com/28824347/63648824-b9b66800-c724-11e9-9fdf-4d1c53f48420.png)

see there is an empty parenthesis inside the info-box but, on wiki page it contents pronunciation of git. (searched keyword: [git](http://search.disroot.org/?q=git&categories=general&language=en-US))

**Comment by return42** [comment]
fixed by #1686
