### ISSUE TITLE
Need help to run searx on VPS @a2Hosting

### ISSUE THREAD

**Issue by JOduMonT** [searx/searx#1692]
Hi;

I try to install searx with python3 on a VPS which support python (a2Hosting).

![image](https://user-images.githubusercontent.com/5204724/64515342-9db2e900-d316-11e9-8fbd-6c23388c3905.png)

#### I ran successfully via the web *Execute command*

```
pip3 install -r /home/srxglbr/searx/requirements.txt
python3 /home/srxglbr/searxsearx/webapp.py
```

and I'm able to access it via SSH
![image](https://user-images.githubusercontent.com/5204724/64517542-bae9b680-d31a-11e9-8585-80e88d4e5501.png)

and a bunch of module were installed
![image](https://user-images.githubusercontent.com/5204724/64518045-a5c15780-d31b-11e9-84f6-345f8273cc6b.png)

#### I could see it's running
```
srxglbr   981530  0.0  0.0  10524   436 ?        S    16:57   0:00 /usr/sbin/proxyexec -c cagefs.sock srxglbr hdjkS9Vx7z7B2R97 /home/srxglbr CAGEFS_ENTER 981485 /bin/bash -c source /home/srxglbr/virtualenv/searx/3.5/bin/activate && python3 /home/srxglbr/searx/searx/webapp.py
srxglbr   981535  0.0  0.0 113672  1536 ?        S    16:57   0:00 /bin/bash -c source /home/srxglbr/virtualenv/searx/3.5/bin/activate && python3 /home/srxglbr/searx/searx/webapp.py
srxglbr   981536  0.2  0.0 439168 60972 ?        S    16:57   0:02 python3 /home/srxglbr/searx/searx/webapp.py
```

### They use LiteSpeed with WGI
I know it LiteSpeed is 100% compatible with Apache syntax
but what about WGI vs USWGI ?
- they using **passenger_wsgi.py**

I tried to run with a **WSGI file location** pointing to `~/etc/searx.ini` without success
```
[uwsgi]
# Who will run the code
uid = srxglbr
gid = srxglbr

# disable logging for privacy
disable-logging = true

# Number of workers (usually CPU count)
workers = 4

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpretor config
single-interpreter = true
master = true
plugin = python
lazy-apps = true
enable-threads = true

# Module to import
module = searx.webapp

# Virtualenv and python path
virtualenv = /home/srxglbr/virtualenv/searx/3.5/
pythonpath = /home/srxglbr/searx/
chdir = /home/srxglbr/searx/searx/
```
So I don't know
Do someone have an idea ?

**Comment by JOduMonT** [comment]
@immanuelfodor thank for your reply but I don't really understand your suggestion, my VPS don't support Docker

**Comment by immanuelfodor** [comment]
Oh, sorry, when I read you're on a VPS, I assumed it has Docker support, like the 5 USD DigitalOcean Droplet as I'd not take the hassle to set it up manually without a container. I can help you with the Docker install if you ever give it a try at another provider but I don't know what's wrong with your current setup.

**Comment by return42** [comment]
FYI: may you find some help in the searx-next docs:  https://return42.github.io/searx/admin/installation.html
