### ISSUE TITLE
[Duckduckgo Definitions] Cannot fetch cheat sheet information

### ISSUE THREAD

**Issue by etanot** [searx/searx#1695]
**Type :** Bug

### Description

Cannot fetch cheat sheet information, only `Cheat Sheet` title is shown. Try this query [!ddd gnome cheatsheet](https://searx.be/?q=%21ddd%20gnome%20cheatsheet&categories=none&language=en-US) with any Searx instance.

![ddd cheatsheet](https://user-images.githubusercontent.com/28824347/64908722-471d2480-d6f3-11e9-8def-55a07a03e317.png)

Whereas, searching same keyword [gnome cheatsheet](https://duckduckgo.com/?q=gnome+cheatsheet&t=ffab&ia=cheatsheet) on DDG show this result

![ddg](https://user-images.githubusercontent.com/28824347/64908765-a24f1700-d6f3-11e9-8434-04f17f138479.png)

### Additional Info
Curl output for the [!ddd gnome cheatsheet](https://search.disroot.org/?q=%21ddd%20gnome%20cheatsheet&categories=none&language=en-US&format=json) query:

<strike>

```
user@local~$ curl "https://searx.me/?q=%21ddd%20gnome%20cheatsheet&categories=none&language=en-US&format=json"
Rate limit exceeded
```

</strike>

```
$ curl "https://search.disroot.org/?q=%21ddd%20gnome%20cheatsheet&categories=none&language=en-US&format=json"
{"number_of_results": 0, "corrections": [], "query": "gnome cheatsheet", "infoboxes": [], "suggestions": [], "results": [], "answers": ["Cheat Sheet"], "unresponsive_engines": []}
```

**Comment by etanot** [comment]
I was wrong, `Rate Limit Exceeds` is a protection against bot abuse. @kvch I've modified the bug report, now can you add tags for this issue?

**Comment by allendema** [comment]
This is because the API request in [engines/ddg_definitions.py](https://github.com/searx/searx/blob/ee86a6355635ee22579c04e05c73cd54c6175d6a/searx/engines/duckduckgo_definitions.py#L29+L30) returns no such results. [1]

Most likely these are some type of spices. [2]

[1] https://api.duckduckgo.com/?q=gnome%20cheatsheet&format=json&pretty=0&no_redirect=1&d=1
[2] https://github.com/Snazzah/duck-duck-scrape/tree/master/src/spices

**Comment by unixfox** [comment]
We don't support the infobox from duckduckgo anymore because duckduckgo lite doesn't return them: https://lite.duckduckgo.com/lite/
