### ISSUE TITLE
Invalid JSON output

### ISSUE THREAD

**Issue by lorenzoromani1983** [searx/searx#1696]
I noticed that the JSON output is not valid Json.
Too bad, because it would really be a great thing if I could pull data from Searx.
Any idea to fix it?

**Comment by unixfox** [comment]
I just tried on multiple JSON validator website and according to them the JSON is valid.
![image](https://user-images.githubusercontent.com/4016501/103548320-8863b580-4e9d-11eb-9770-83149322bf24.png)
