### ISSUE TITLE
No results found when Google presents a captcha 

### ISSUE THREAD

**Issue by nateshmbhat** [searx/searx#1697]
https://searx.me/?q=Flutter%20list%20widget%20out%20of%20screen&categories=general&language=en-US

When I searched using above query it showed no results and presented an error from Google which required captcha. Even then its supposed to show search results from other search engines isn't it?

This is the error in the error message box 
 ```
Error! Engines cannot retrieve results.

google (unexpected crash: CAPTCHA required)

Please, try again later or find another searx instance.
```

**Comment by zhlavinka-cricut** [comment]
Any luck with this? Looking at search engine options for a project we're working on and just ran into this exact issue this evening.

**Comment by return42** [comment]
This task is already discussed in #729 / lets continue there / since 2016 we have many issues related to google's CAPTCHA / spreading the knowledge is not helpful for solutions / can we please close this issue / thanks!

**Comment by unixfox** [comment]
@return42 duplicate of #729, this issue can be closed.
