### ISSUE TITLE
Proposal: Offline engines

### ISSUE THREAD

**Issue by kvch** [searx/searx#1698]
This issue is a proposal for adding offline engines to searx. I had discussions with @asciimoo about how to add support for such engines. Now the proposal is mature enough to share it with you.

First of all, we would like to share it with you to get feedback about the idea. However, as I would like to implement the support soon, please keep in mind that the issue is only going to be open until Thursday (26 Sept). Also, as our resources are limited we cannot satisfy all needs. I would rather iterate on the code quickly to get usable/testable user interfaces, than bikeshedding before writing a single line of code. 

I am open to improvements to this feature. But after closing this issue, please open a separate issue as in case of other enhancement requests.

Furthermore, this is not a final design document. A documentation page is coming after offline engines are added to searx.

Let me know your thoughts on the topic!

@asciimoo @dalf @Pofilo @josch

#### What is an offline engine?

An offline engine is an engine which does not need Internet connection to perform a search. It either looks for results on the host machine or on private network. E.g local file search, or a local Elasticsearch instance.
It does not mean that the search service cannot be available publicly. For example it is possible to query an Elasticsearch instance under a public URL.

#### Security 

To limit the access to offline engines, if an instance is available publicly, admins can set token(s) for each private engine. If a query contains a valid token, then searx performs the requested offline/private search. If not, requests from an offline/private engines return errors.

#### User interface

Offline engines are listed in the available engines list under the appropriate category.

If an engine has advanced settings, it can be configured after clicking on "Advanced settings". 

#### Administering offline engines

If an offline engine depends on an external tool, searx does not install it by default. When an administrator configures such engine and starts searx, the process returns an error with the list of missing dependencies. It might be a uncomfortable in the beginning, but it only has to be done once when enabling a type of offline/private engine. Also, required dependencies will be added to the comment/description of the engine, so admins can install packages in advance.

If an offline engine has to be private, administrators can provide tokens for the authorized users. When a token is sent to searx with a query to an offline engine, search is performed as described in the section "Security".

##### `init`

All offline engines can have their own `init` function to setup the engine before accepting requests. The function gets the settings from `settings.yml` as a parameter. This function can be omitted, if there is no need to setup anything in advance.

##### `search`

Each offline engine has a function named `search`. This function is responsible to perform a search and return the results in a presentable format. (Where presentable means presentable by the selected result template.)

The return value is a list of results retrieved by the engine.

##### `available_params`

The third function required is `available_params`. This function has to be implemented if the engine has some advanced setting to be configured from the "Advanced settings" section. If the engine does not have such options, return an empty list.

#### Engine representation in `/config`

If an engine is offlne, the attribute `offline` is set to `True`.

**Comment by virtadpt** [comment]
This.  Searx is really useful as a unified search REST API provider in and of itself, and it would be really useful to be able to hook some local stuff in, too.

**Comment by kvch** [comment]
Proposal moved to: https://github.com/asciimoo/searx/wiki/Offline-engines
