### ISSUE TITLE
duckduckgo images - no results found

### ISSUE THREAD

**Issue by useronegit** [searx/searx#1699]
First of all, I'm sorry for my English, most of it is from a translator.

.
**Well, I can't do a search with "duckduckgo images". It doesn't find any results, no error message appears. Only it can't find any results. I tried a simple word "test", but he doesn't find anything.**
.

This is my first entry since the history of the universe, I use the first time Github as a registered user. Sorry if I did something wrong.

**Comment by unixfox** [comment]
Duckduckgo images is working great in local for me:
![image](https://user-images.githubusercontent.com/4016501/93886458-1dc3ab00-fcee-11ea-896e-d40f32fb1d6a.png)

I'm going to close this issue, feel free to reopen it if you are still experiencing the problem.
