### ISSUE TITLE
Searx v1.0.0

### ISSUE THREAD

**Issue by asciimoo** [searx/searx#1703]
At first, I'd like to say a huge thank you to the searx community and especially to the maintainers for taking care about searx in the past two years while I was mostly inactive.
In the past years I worked on other OSS projects like GoColly (https://github.com/gocolly) and ParlTrack (https://github.com/parltrack , https://parltrack.org/) which has been fully rewritten nearly from scratch.

Focusing on the future, I'd like to announce that in the next 5-6 months I'm working full time on searx to be able to release its first stable release. Big thanks to NLNet (https://nlnet.nl) which makes it possible.
The plan is the following:
As the first milestone (starting from Monday) I'd like to fix all engines and prioritize our current issues mainly focusing on bug/core/security/ui labeled issues. In this part I'd like to ask for your help to collect the most important issues and assign priorities to them. Please list every issue you'd like to be the part of the v1.0.0 release or if an issue is already in the comment thread vote for it with a :+1: .
After the issues are collected I'm creating a dedicated searx project (https://github.com/asciimoo/searx/projects) where the whole development can be followed.
As the second milestone I'm addressing the UI related tasks, and the backend related tasks will form the third milestone.
The last (4.) milestone will consist of a full release test and the standard release process.
If you have any questions, ideas or suggestions, feel free to comment.

Thanks, happy searxing.

**Comment by dimqua** [comment]
Bugs:
* Fix Google Images engine #1687
* Startpage nows errors every few searches #1601

Do you accept feature requests, such as new engine requests?

**Comment by kvch** [comment]
DuckDuckGo paging issue: https://github.com/asciimoo/searx/issues/1677

**Comment by kvch** [comment]
Broken XPATH in Voat: https://github.com/asciimoo/searx/issues/1581

**Comment by kvch** [comment]
Infobox merging with multiple languages of wikipedia: https://github.com/asciimoo/searx/issues/669
Other merging: https://github.com/asciimoo/searx/issues/1685

**Comment by dimqua** [comment]
Qwant Images, News and Social engines don't work.

**Comment by kvch** [comment]
Tracker URL remover produces incorrect URLs sometimes: https://github.com/asciimoo/searx/issues/722

**Comment by kvch** [comment]
@dimqua Is there an open issue for that?

**Comment by kvch** [comment]
Clicking on suggested search query does not keep search settings in query: https://github.com/asciimoo/searx/issues/1314

**Comment by dimqua** [comment]
@kvch Probably related to #1459, but the general engine works for me.

**Comment by kvch** [comment]
Issue with images.html template on Windows: https://github.com/asciimoo/searx/issues/1074

**Comment by kvch** [comment]
Support setting of default oscar style from settings.yml: https://github.com/asciimoo/searx/issues/683

**Comment by kvch** [comment]
Returning results in multiple languages: https://github.com/asciimoo/searx/issues/1030

**Comment by dimqua** [comment]
@kvch isn't this a duplicate of https://github.com/asciimoo/searx/issues/1344?

**Comment by kvch** [comment]
Indeed. TBH I am not sure if this works correctly now by setting it in the search query. I tried testing with `:en :hu ember` (ember means man in hungarian). I only got result for the last selected language, in hungarian.

**Comment by josch** [comment]
I'm maintaining searx in Debian. From our perspective it would also be much appreciated if there would be a release before the 1.0.0 release which just fixes some important bridges which are broken right now. Since you list fixing the backends as your first milestone it would maybe make sense to make a release before tackeling the second milestone?

Thank you for working on searx again!

**Comment by asciimoo** [comment]
@josch okay, then I'm going to create a smaller release after the engine fixes.

**Comment by unixfox** [comment]
Handle parsing of the new Google UI: #1609
(needed because Google will likely going to stop support their old UI, more info about that in the issue)

**Comment by r4dh4l** [comment]
Browser language dection for "language" similar to "default_locale"? [#1554](https://github.com/asciimoo/searx/issues/1554)

**Comment by asciimoo** [comment]
> Qwant Images, News and Social engines don't work.

it works for me from a local instance

**Comment by Neustradamus** [comment]
It is possible to move searx before the 1.0 release?

**Comment by Perflyst** [comment]
I wonder if you also want to prevent abuse by default in searx which is currently done via filtron? E.g. not doing more than X requests to remote search engines?

**Comment by Neustradamus** [comment]
@asciimoo: What is the progress to move asciimoo/searx to searx/searx for improve the visibility of Searx and do not mix with users/devs?

**Comment by ralfi** [comment]
Its possible to integrate filtron function in searx?

**Comment by dimqua** [comment]
fix startpage engine https://github.com/asciimoo/searx/pull/1683

**Comment by FrostKnight** [comment]
> fix startpage engine #1683

Startpage is no longer as private as it used to be...

http://techrights.org/2019/11/16/startpage-is-not-dutch/

http://techrights.org/wiki/index.php/Startpage

and this:

https://blog.privacytools.io/delisting-startpage/

**Comment by return42** [comment]
@FrostKnight  see my comment on PR https://github.com/asciimoo/searx/pull/1683#issuecomment-559560002

BTW: this is one reason more for our users to prefer searx instances over startpage or any other (meta) search engine :)

**Comment by ghost** [comment]
[https://nibblehole.com](https://nibblehole.com) - v0.16.0, 
Thank you!

**Comment by nfk** [comment]
Here my 2 cents, maybe we can think to improve the searx stack with some new libraries, step-by-step of course. 2 goals here, it is fun to use a modern python stack for current and next contributors/maintainers, then I am sure it can improve Searx performance.

below some ideas:

* flask -> [fastapi](https://github.com/tiangolo/fastapi)
* jinja -> [svelte](https://svelte.dev/)
* requests -> [httpx](https://github.com/encode/httpx)
* engine API with [pluggy](https://github.com/pytest-dev/pluggy/)
* [black](https://github.com/psf/black)/[flake8](https://flake8.pycqa.org/en/latest/) as code guideline
* unittest -> [pytest](https://docs.pytest.org/en/latest/)
* sphinx -> [mkdocs](https://www.mkdocs.org/)

**Comment by josch** [comment]
> Here my 2 cents, maybe we can think to improve the searx stack with some new libraries, step-by-step of course. 2 goals here, it is fun to use a modern python stack for current and next contributors/maintainers, then I am sure it can improve Searx performance.
> 
> below some ideas:
> 
>     * flask -> [fastapi](https://github.com/tiangolo/fastapi)
> 
>     * jinja -> [svelte](https://svelte.dev/)
> 
>     * requests -> [httpx](https://github.com/encode/httpx)
> 
>     * engine API with [pluggy](https://github.com/pytest-dev/pluggy/)
> 
>     * [black](https://github.com/psf/black)/[flake8](https://flake8.pycqa.org/en/latest/) as code guideline
> 
>     * unittest -> [pytest](https://docs.pytest.org/en/latest/)
> 
>     * sphinx -> [mkdocs](https://www.mkdocs.org/)

Please have a better rationale than "fun to use a modern python stack" when you switch out components. Neither fastapi, nor svelte, nor httpx, nor mkdocs are packaged in Debian or Ubuntu. Introducing libraries that are "new and shiny" but not much used yet will make it harder to package searx in distributions.

**Comment by dalf** [comment]
@nfk, I think this issue is about consolidating the existing architecture / choice.
So, what you describing is another issue.

But have a look here: https://github.com/asciimoo/searx/pull/1724
Quart has been chosen because the migration is straightforward.

**Comment by nfk** [comment]
@josch, @dalf Indeed you are totally right, I did know that searx was packaged for Debian and Co. (I am a pip/docker user)

Also I forgot to explain the final goal. The mainly aim is to improve the timing response for the user experience. Currently, to get the first result on searx page we have to wait the response of all engines or the max timeout. With some async call to the back end we could provide to the user the first results instead of a blank page. That why I suggest library like fastapi to have a better backend and responsive api and svelte as front-end to get a reactive UI. As you said my comment is unrelated to this issue. I will expose my idea in another ticket or in an existing one.

**Comment by guidot** [comment]
Teach searx to offer itself to browsers as a search engine using OpenSearch: #1616

**Comment by kvch** [comment]
I am closing this as searx v1.0.0 was released months ago.
