### ISSUE TITLE
Results change with every "search" command.

### ISSUE THREAD

**Issue by ran88dom99** [searx/searx#1721]
Every time I search with the same query string the results are very different. !bi usually yields 6 and occasionally 40 results while bing itself gives 800. Often no results too. I tried this on 10 highest https://stats.searx.xyz/. ecloud.global is consistent but seems to miss so many features. Why and what to do about it?

**Comment by kvch** [comment]
What do you mean by very different? I tried searching for multiple search term (e.g hello, realistic, rolling stones) on my searx instance, on searx.me and on a local searx instance. But the results were pretty consistent every time. Once or twice one result ended up at a different position in the list. But no significant changes.

If you are comparing different public instances, it is possible that different engines are configured. Thus, different results are returned. It is also possible that the instance administrator configured a weight for an engine, so those results are merged differently into the list than in other instances.

**Comment by ran88dom99** [comment]
on searx.me using string !bi polar H7
attempt 1
 Sorry! we didn't find any results. Please use another query or search in more categories. 
attempt 2
https://support.polar.com/en/support/H7_heart_rate_sensor
https://www.polar.com/us-en/products/accessories/h10_heart_rate_sensor
https://www.polar.com/
https://www.youtube.com/watch?v=jLnqBQJaSTo
... next page
https://support.polar.com/en/support/H7_heart_rate_sensor
https://www.polar.com/us-en/products/accessories/h10_heart_rate_sensor
https://www.polar.com/
... next page is the same
attempt 3 repeats attempt 2
now always all pages identical 
https://searx.me/?q=%21bi%20polar%20H7&categories=none&pageno=2&language=en-US
https://searx.me/?q=%21bi%20polar%20H7&categories=none&pageno=4&language=en-US
JSON only gives the same ten items

At the same time bing.com gives
https://www.amazon.com/Polar-Bluetooth-Sensor...
https://www.polar.com/us-en/products/accessories/h...
https://support.polar.com/.../H7_heart_rate_sensor
https://www.pcmag.com/review/350243/polar-h7-heart...
https://www.heartratemonitorsusa.com/products/...
...

**Comment by ran88dom99** [comment]
https://searx.tuxcloud.net/?q=%21bi%20polar%20h7&categories=none&language=en-US
first attempt 
https://www.amazon.com/Polar-Bluetooth[...]h-Sensor-Fitness-Tracker/dp/B00NOHWTO6
https://www.polar.com/us-en/products/accessories/h10_heart_rate_sensor
https://www.polar.com/us-en/products/accessories
https://www.consumerreports.org/produc[...]-h7-heart-rate-sensor-220331/overview/
https://support.polar.com/us-en/suppor[...]ility_of_polar_h6_h7_heart_rate_sensor
https://support.polar.com/en/support/H10_heart_rate_sensor
... 10 total results
attempt 2
same first page
 Sorry! we didn't find any results. Please use another query or search in more categories.  on second page
and originally claimed 200k results
attempt 3 repeats attempt 2
attempt 4 via direct link at top of this post only 8 results
https://www.amazon.com/Polar-Bluetooth[...]h-Sensor-Fitness-Tracker/dp/B00NOHWTO6
https://www.polar.com/us-en/products/accessories
https://www.consumerreports.org/produc[...]-h7-heart-rate-sensor-220331/overview/
https://www.polar.com/
https://support.polar.com/us-en/suppor[...]ility_of_polar_h6_h7_heart_rate_sensor
https://support.polar.com/en/support/H10_heart_rate_sensor
https://www.amazon.com/Polar-90050534-[...]nt-V650-Cycling-Computer/dp/B00MTDA1XC
https://www.youtube.com/watch?v=H7_JeoIIB64

**Comment by kvch** [comment]
Indeed, these are issues. But AFAIK searx.me is a bit behind of master. I've tried the same queries on my local instance with master. I got consistently the same results from bing and searx. Sometimes I had to refresh the page to get results, but it is not unexpected.

**Comment by ran88dom99** [comment]
Problem replicated on netcafe computers. Once managed to get page#2 though. !gos !arx and I would guess science in general seem to have far less of these problems.  https://searx.win/?q=%21gos%20polar%20h7&categories=none&pageno=3&language=en-US

**Comment by kvch** [comment]
The issue you see is not in the software. Searx is a meta-search engine meaning it collects results from external search services. Sometimes those search services don't return results, so there is nothing to present. If you refresh the page, results appear.

It makes no sense to compare the results of an unknown instance with what you see on your local computer. The instance hides your information, and only send the minimum required request to the search service. (The instance you are using might not even be on the same continent as you.) Thus, the service returns a generic result list, as it has no data for "personalization". However, when you send queries directly to the external search service (in this case Bing) you are sending all the personal info (cookies, your ip, etc.), so they can tailor the results to you.

Searx.me was updated a few hours ago, so the links you shared are working again. The issue you showed where the two result list were identical has been resolved.

Also, note that not all engines support paging. So it is possible that the search service is capable of returning more results than searx is able to query.

**Comment by ran88dom99** [comment]
Searx needs a slow and careful mode to get more results even if process takes much longer.
