### ISSUE TITLE
Multiple source_ips: How to check if it's working?

### ISSUE THREAD

**Issue by shellshocker** [searx/searx#1735]
I configured two additional source ips in settings.yml:
```
source_ips:
         - 1.2.3.10
         - 1.2.3.20
```
What is the best way to check if searx is using these ips?

**Comment by eggercomputerchaos** [comment]
Hello to all ,
same question here, 
any news about that?

**Comment by asciimoo** [comment]
Configure an engine with a host that you own and check its server logs.
