### ISSUE TITLE
Filtering results in a plugin (on_result hook) possible?

### ISSUE THREAD

**Issue by arendjantetteroo** [searx/searx#1737]
I'm working on a plugin that is supposed to filter the results from the engines based on certain criteria i can check in the plugin.

I use the on_result hook, which works fine for changing results as seen in the remove_tracker plugin, but it seems i can not remove certain results in this hook. 

Is there a way to make this happen i did not see?  
It would be nice if we could just add a `result['filtered'] = True` or do a `return null` in the `on_result` hook to let results disappear from the results page. 

I currently solved it with a workaround by specifying a different template with a "filtered" = true on the result, which if it's true is not shown by this template. However, this means that my plugin needs to provide a template for each theme there is in searx to let this work for all themes. 

Any hints? 

Current prototype code is here: https://github.com/thegreenwebfoundation/searx/pull/1/files

**Comment by arendjantetteroo** [comment]
@asciimoo I tried to use post_search but i'm not sure how i can update the results_container. Can you give me a hint

The following doesn't work. (just trying to remove all elements to get an idea how to do this)
```
def post_search(request, search):
    results = search.result_container.get_ordered_results()

    for result in results:
        search.result_container.remove(result)
```

**Comment by asciimoo** [comment]
Here's an example plugin which removes every result thats url contains letter 'e':
```python
name = 'Test'
description = 'Test plugin'
default_on = True


def post_search(request, search):
    for i, result in enumerate(list(search.result_container._merged_results)):
        if 'e' in result.get('url', ''):
            result = search.result_container._merged_results[i]
            print('deleting result:', result)
            del(search.result_container._merged_results[i])
    return True
```
