### ISSUE TITLE
Sorry, searx, I'm leaving you.

### ISSUE THREAD

**Issue by prolibre** [searx/searx#1739]
I reluctantly stop my instance this day but it has been several months since it became gradually unusable.
At first it was google (with this capcha problem) but now my instance is more and more unstable: repetitive timeout etc.
I liked this project very much but I fear that it will be more and more difficult to maintain.
Thank you very much to everyone who worked on it.

Anthony

**Comment by tgc12** [comment]
This is not the the place nor the way to rant.
If you want to help explain your concrete problems and provide logs and data.

**Comment by asciimoo** [comment]
Thank you for your feedback

**Comment by prolibre** [comment]
@tgc12 I'm sorry, but there must be a problem of comprehension because of the translation. 
"This is not the place nor the way to rant" was never my intention. I had been using searx for years and I wanted to explain why I am leaving... quite simply. These are not just simple bugs (I've encountered and fixed a lot of them and that's normal). For me searx is no longer usable.
Thanks again to the developers.
