### ISSUE TITLE
DuckDuckGo Definition crashes unexpectedly

### ISSUE THREAD

**Issue by etanot** [searx/searx#1741]
Getting **unexpected crash** error with `DuckDuckGoDefinition`. This problem is consistent with some instances (like https://search.disroot.org, https://search.privacytools.io); and for others, it can be reproduced after hitting search icon, at least 3-4 times.

**Error message:**

```
Engines cannot retrieve results:
ddg definitions (unexpected crash: No JSON object could be decoded)
```

**Search terms:** `wikipedia`, `duckduckgo` etc.

**Persistent Instances**
1.) https://search.disroot.org

https://search.disroot.org/?q=%21ddd%20wikipedia&categories=none&language=en-US

![search disroot org](https://user-images.githubusercontent.com/28824347/68644012-902f0080-050b-11ea-8b3a-ed0c191f56a8.png)

2). https://search.privacytools.io

https://search.privacytools.io/?q=%21ddd%20wikipedia&categories=none&language=en-US

![privacytools io](https://user-images.githubusercontent.com/28824347/68644167-0f243900-050c-11ea-9ac2-0a32f53db9ff.png)

**Non-persistance Instances**

1). https://searx.me

https://searx.me/?q=%21ddd%20wikipedia&categories=none&language=en-US

![searx me](https://user-images.githubusercontent.com/28824347/68644164-0cc1df00-050c-11ea-8340-36f65fc3fd0e.png)

2). https://www.searxs.eu

https://www.searxs.eu/?q=%21ddd%20wikipedia&categories=none&language=en-US

![www searxs eu](https://user-images.githubusercontent.com/28824347/68644181-19463780-050c-11ea-9138-d2fc20c5009e.png)

**Steps to reproduce:**

For those instances, if you're page looks like below screenshot, click on `search icon` at least 3-4 times.
![not an error](https://user-images.githubusercontent.com/28824347/68644537-34657700-050d-11ea-89eb-b4893201beb1.png)

**Comment by return42** [comment]
> Getting unexpected crash error with DuckDuckGoDefinition. This problem is consistent with some instances; and for others, it can be reproduced after hitting search icon, at least 3-4 times.

FWIW: I can confirm this issue, hitting 3-4 times will result in an empty string in the response and this will cause  the error message .. I can't remeber where, but have seen this also with other engines.  Haven't had time to dig yet.

**Comment by asciimoo** [comment]
I cannot reproduce anymore.
