### ISSUE TITLE
Redirect from www.searx.me to searx.me

### ISSUE THREAD

**Issue by wuniversales** [searx/searx#1746]
As the title says ...
I think this is better, since sometimes people configure one domain, and not the other, 2 different configurations are generated for one domain and another ....
Better unify everything in searx.me

**Comment by unixfox** [comment]
@asciimoo

**Comment by kvch** [comment]
Searx.me is a landing page for searx now. Also, if you type www.searx.me in the browser, it redirects you to searx.me.
