### ISSUE TITLE
[Request] Engines test on stats.searx.xyz

### ISSUE THREAD

**Issue by smnthermes** [searx/searx#1747]
It would be useful a test on stats.searx.xyz to check which engines are working.

**Comment by unixfox** [comment]
Probably better to build a new stats.searx.xyz clone from scratch because it is getting old and lacks of quite of lot of various tests (using cloudflare, external trackers found, IPv6 support and so on).

**Comment by unixfox** [comment]
It's now implemented on searx.space in the "Engines" tab.
@dalf you can close this issue

**Comment by dalf** [comment]
The "Engines" tab still has some issues, but it is better than nothing.

Moved to https://github.com/dalf/searx-stats2/issues/17
