### ISSUE TITLE
Engines cannot retrieve results: google (unexpected crash: CAPTCHA required) 

### ISSUE THREAD

**Issue by TheEmbracedOne** [searx/searx#1751]
Getting the above error when searching. Is this a configuration issue on my end or ?

**Comment by unixfox** [comment]
No it's not. This issue has been discussed several times primarily here: https://github.com/asciimoo/searx/issues/729.
If my comment answered your question can you close this issue?

**Comment by return42** [comment]
@TheEmbracedOne  seems absent, can one of the maintainer please close this issue / thanks!

**Comment by unixfox** [comment]
@return42 can you close this issue?

**Comment by return42** [comment]
If someone else comes here, please take a look at @unifox's [antibot](https://github.com/asciimoo/searx/issues/729#issuecomment-511997511) comment / thanks!
