### ISSUE TITLE
How to force Google to use IPV4?

### ISSUE THREAD

**Issue by h0cheung** [searx/searx#1753]
My VPS's IPV6 Address has been blocked by Google while IPV4 address works normally. But searx only use the IPV6 address to connect to Google and show `google (unexpected crash: CAPTCHA required)`

**Comment by unixfox** [comment]
You will most likely be blocked by Google in IPv4 too if you fallback to IPv4.
If you are running a public Searx instance you should read this issue, there are tons of people that encountered the same issue as you (even me): https://github.com/asciimoo/searx/issues/729
But if it's a private one you may try to change VPS or use a proxy/VPN on your VPS or change the IPv6 address of your VPS(if your provider allow it)

**Comment by return42** [comment]
Update: old UI is dead https://github.com/asciimoo/searx/issues/1748#issuecomment-562549293 / lets close this issue and continue at issue https://github.com/asciimoo/searx/issues/729 / thanks!

**Comment by unixfox** [comment]
@return42 you may close this issue too
