### ISSUE TITLE
Ubuntu Installation

### ISSUE THREAD

**Issue by DrrAld** [searx/searx#1759]
Hello team. Great and very necessary code here. However, I've pointed a few Ubuntu people in the direction of the installation instructions (https://asciimoo.github.io/searx/dev/install/installation.html) and each has failed to successfully install locally with the abiliy to enable, start and/or stop with systemd (the standard protocol). It took a few goes myself. Any idea when an updated, non-docker, instruction will be made available? Thanks in advance.

**Comment by return42** [comment]
I have one [handsOn searX](https://return42.github.io/handsOn/searx.html) .. the description is only in german :o .. but the shell examples should be understandable for those knowing bash.  The installation there is following the official [instrutions to install](https://asciimoo.github.io/searx/dev/install/installation.html) except it is focused on a installation that is behind a apache under the application URL (path) ```/searx```.  _Hope that helps._

**Comment by DrrAld** [comment]
> I have one [handsOn searX](https://return42.github.io/handsOn/searx.html) .. the description is only in german :o .. but the shell examples should be understandable for those knowing bash. The installation there is following the official [instrutions to install](https://asciimoo.github.io/searx/dev/install/installation.html) except it is focused on a installation that is behind a apache under the application URL (path) `/searx`. _Hope that helps._

Thank you for the response. In case this doesn’t work for others, I found the Docker installation to be much more streamlined and would recommend that route until direct install procedures are more clearly articulated.

**Comment by return42** [comment]
Correct, my documentation from handsOn is not really suitable for user who do not use the handsOn.

IMO the documentation of searx is a mess, we have some docs in the gh-branch others are found in the wiki. ATM I'm working on documentation.  My first step is to [make documentation more accessible](https://github.com/asciimoo/searx/pull/1760) if this PR (and my  [boilerplate](https://github.com/asciimoo/searx/pull/1756) ) will be accepted, things get much easier. After, I can fix & add documentation (ubuntu will be the first to add, cause its my major platform) and with the boilerplate, it will also be easier to implement routines for build and install.

But this depends on what the maintainers ( @asciimoo & @dalf ) think, which way they wanted to go.

May you like to reopen this issue?

**Comment by DrrAld** [comment]
Reopened. And thank you for the update. Hopefully official instructions will be updated soon.

**Comment by DrrAld** [comment]
@asciimoo any updates on documentation?

**Comment by return42** [comment]
@darrenallendunn   patience you must have my young padawan :)

First we need to merge #1767  .. after I hope I have time to write.

**Comment by return42** [comment]
FWIW: when updating the docs, we also need to consider https://github.com/asciimoo/searx/issues/1792#issuecomment-570208244

**Comment by return42** [comment]
closed by PR #1803 / see docs at: https://asciimoo.github.io/searx/admin/installation.html
