### ISSUE TITLE
adding maintainers

### ISSUE THREAD

**Issue by return42** [searx/searx#1761]
This project is great, but in absence of maintenance it gets more and more a mess. We have PR from the community solving long standing issues .. but no one merge these bugfixes.

It's not a reproach, who always has time for that? Often its the same to me.  But I would  recommend to extend the list of maintainers. And of course I offer myself for  .. ;)

**Comment by return42** [comment]
Bump .. sorry for beeing impatient, but I have time now ... not next year.

Even a "no" would be a helpful feedback for me / thanks!

**Comment by unixfox** [comment]
sending an email to asciimoo is probably a better idea than creating an issue that will most likely receive no response from him.

**Comment by return42** [comment]
Good point .. contacted Adam via eMail / thanks for the hint.

**Comment by asciimoo** [comment]
@return42 I already thought about asking you to be one of the maintainers. Your work on searx is super useful and the way you approach problems represents the same values that we believe in. 
Thank you for both of your work and for the offer to spend more time making searx great. =)

I'm going to send you an email about some minor details of maintaining the project.
