### ISSUE TITLE
Default interface language

### ISSUE THREAD

**Issue by julpec** [searx/searx#177]
Hello

I would like to know if it's possible to change the default interface language for a new user.

There is no way to do that in settings.yml and I would like to have my searx installation in french.

Thanks

**Comment by dalf** [comment]
May it is related to #77 ?

**Comment by julpec** [comment]
No, I don't need to change the default **results** language (location). I just want to change the default **interface** language (theme's language).

**Comment by Cqoicebordel** [comment]
What I can gather from the code (and my personnal experience), is that the default locale of the searx instance is the user's browser locale.
So, when I install searx and use it in a new browser (no cookie), it's already in french...

It may be also possible to alter the order of the proposed locale language by changing it at the end of settings.yml, but I'm probably mistaken (haven't checked this)

Also, as stated in #77 you can directly provide a 'french url' by adding `?locale=fr` at the end of the searx url like `http://127.0.0.1:8888/?locale=fr`

Au final, normalement, ça devrait fonctionner tout seul ;)

**Comment by asciimoo** [comment]
@julpec  currently searx doesn't support it, but can be easily implemented, i'll add an option to settings today/tomorrow

**Comment by asciimoo** [comment]
done ^^^

**Comment by julpec** [comment]
Yeah !!! Excellent !
Thank you very much asciimoo !

@Cqoicebordel : no, for me it didn't detect the browser default locale (iceweasel 31.3). I just tried witch chromium and you're right, the french local is detected…

Whatever, for interoperability, it's good to have a configurable option on the server
