### ISSUE TITLE
https://searxes.eu.org removed?

### ISSUE THREAD

**Issue by emanruse** [searx/searx#1770]
I notice that https://searxes.eu.org/ and its [.onion instance](http://searxes.nmqnkngye4ct7bgss4bmv5ca3wpa55yugvxen5kz2bbq67lwy6ps54yd.onion) were removed from the instance list in Sept.2019. What is the reason for this? (they still work fine)

**Comment by return42** [comment]
Sorry, I don't know why. Did you looked at history: https://github.com/asciimoo/searx/wiki/Searx-instances/_history

**Comment by fgossel** [comment]
This happened to my instance as well. After quick look it seems to me like it has been renamed from tuxcloud to tuxbutt :/   with this commit > 
https://github.com/asciimoo/searx/wiki/Searx-instances/510e6b8eac6fb6cebf8c53257bc7bb1eb1e32264

**Comment by unixfox** [comment]
@fgossel I guess someone wanted to rename cloudflare to buttflare but only used the keyword `cloud` to make the change.

@emanruse Feel free to add it again. Due to the fact that the wiki can be modified by anyone some people want harm the wiki by removing instances.

**Comment by return42** [comment]
Here is the diff https://github.com/asciimoo/searx/wiki/Searx-instances/_compare/f29513b3abf54ea885a01243f387d81bec837582...510e6b8eac6fb6cebf8c53257bc7bb1eb1e32264

@fgossel do you like to fix the wiki? Would be a great help / thanks!

**Comment by fgossel** [comment]
@return42 Yes, I don't mind to help.

**Comment by emanruse** [comment]
> Did you looked at history:

Yes.

> Feel free to add it again.

No time for that, sorry.

> Due to the fact that the wiki can be modified by anyone some people want harm the wiki by removing instances.

The this needs better monitoring of changes and limiting of permissions.

**Comment by emanruse** [comment]
Why did you close this without even considering to fix it?

**Comment by return42** [comment]
Then please fix it and we can close ..

**Comment by emanruse** [comment]
> Then please fix it and we can close ..

I already told you - I don't have the time for this, sorry. I have reported the issue which doesn't mean I am the one to do correct the errors of others.

Someone else may want to do it and to prevent that from happening again. Ideally - the one who messed things up. Otherwise - anyone who cares enough. Personally I have that instance bookmarked, so it is not an issue to me.

Up to you.

**Comment by unixfox** [comment]
searxes.eu.org has been added back: https://github.com/asciimoo/searx/wiki/Searx-instances/502fbf54074f69ec00a08339eccc3a28717f1869
I think this issue can be closed.

**Comment by return42** [comment]
OK, now I know why one has dropped searxes.eu.org from the wiiki ...

I observed a very strange behavior when I click on the 'searxes.eu.org' entry from the searx instances wiki [1].

This entry is linked to "https://searxes.eu.org" so I would expect it opens the URL.  But when I click the link it routes me to codeberg.org [2]

When I type the "https://searxes.eu.org" in the URL bar it opens the correct URL and does not route to [2] .. strange to me.

When I test with curl, I got a bad gateway:

    $ curl https://searxes.eu.org
    <html>
    <head><title>502 Bad Gateway</title></head>
    ...

searxes.eu.org is a subdomain [3], could that be the reason for the strange behavior?  If so, how can we trust in subdomain-ing?

[1] https://github.com/asciimoo/searx/wiki/Searx-instances
[2] https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README.md 
[3] https://eu.org

**Comment by return42** [comment]
Today a got a mail over secmali.pro which helps to clarify.  Here is the mail and my answer ...

> Dear Searxes #PRV,
> 
>      sorry for the mess on searx, we have to tidy up our lists
> 
> ATM every github user has the rights to change the list of searx
> instances without leaving any hints why some entries are changed.
> 
> This is a big problem and we addressed this issue [PR-1785].  I
> will work on this issue in the next days.  At searx we are always
> under-resourced.  That is why many things have not been
> maintained or have only been inadequately maintained. I am new at
> searx and want help to tidy up things.  I apologize for the
> mistakes in the past and hope I can help in the future.
> 
> On the other hand; please be fair .. at [46448] is a wrong citation saying:
> 
>    return42: "I just add it as normal Searx instance"
> 
> I never said this.  Anyway, thanks for your clarifying mail.
> 
> [46448] https://codeberg.org/crimeflare/cloudflare-tor/issues/53#issuecomment-46448
> [PR-1785] https://github.com/asciimoo/searx/issues/1785


> @secmail.pro:
>> Dear Mr. Markus Heiser,
>>
>> Thank you for raising attention.
>> We kindly ask you to read below message and take appropriate action.
>>
>> Sincerely,
>> Searxes #PRV
>>
>> -----
>>
>> PUBLIC NOTICE
>>
>>
>> This is not Searx at all. This is Meta-Searx with other engines.
>>
>> You can either [Move it to "Meta-searx instances" section (Be friends
>> again)] or [Just remove it from your Microsoft Github (Really, we don't
>> mind)].
>>
>> If you do want to fix relationship with us, do consider reverting it to
>> this one and we'll unlock this notification.
>>
>> https://github.com/asciimoo/searx/wiki/Searx-instances/2fa034fa5f1575fbc59c8ab8742204a329354bf3 
>>
>>
>> Also read:
>> https://codeberg.org/crimeflare/cloudflare-tor/issues/53#issuecomment-22466
>>

**Comment by return42** [comment]
FYI: the Meta-searx instances are now listed here https://asciimoo.github.io/searx/user/public_instances.html .. includes searxes.eu.org
