### ISSUE TITLE
private.sh - new engine request

### ISSUE THREAD

**Issue by somedevreally** [searx/searx#1774]
is it good search engine to be added?

**Comment by dalf** [comment]
About https://private.sh/how-it-works.html : "The search provider" knows the request, so it's just a way to hide your IP.

After some digging, private.sh seems to be a proxy to gigablast : 
* https://gigablast.com/search?c=main&qlangcountry=en-us&q=ifconfig.me
* https://private.sh/ (I can't copy paste the "ifconfig.me" query)

The results are the same, the description of the first result contains an IP which belongs to gigablast.

searx is also a proxy to different search engines including [gigablast](https://github.com/asciimoo/searx/blob/master/searx/engines/gigablast.py).

If you trust a searx instance, there is no need to use private.sh

May be I'm wrong. 

The website says : 
> Our website and extension is built with open source technologies and can easily be audited and improved through our open source program (coming soon!).

**Comment by somedevreally** [comment]
thanks for the info, my mind is at peace now 😁
