### ISSUE TITLE
move info box at top of the page (in mobile devices)

### ISSUE THREAD

**Issue by etanot** [searx/searx#1777]
#### Affected Theme
* Oscar

#### Description
In low width (for example mobile) devices, `Info Box` is at bottom of the page, which should be at top, with an expansion icon which expands the `info box` to its original size, if user wants to see more detailed info box.

<img alt="searx me" src="https://user-images.githubusercontent.com/28824347/71150084-4c28cd00-2228-11ea-8ecc-056c769d7b59.png" width=350>

**Fig 1:** Screenshot is taken on Android device for [radix sort](https://searx.me/?q=radix%20sort&categories=general&language=en-US) search term.

In contrast, we can look at other search engines result page, for example DDG engine:

<img alt="ddg-without-expansion" src="https://user-images.githubusercontent.com/28824347/71150825-54820780-222a-11ea-9d16-e180c0bcbb89.png" width=350>

<img alt="ddg" src="https://user-images.githubusercontent.com/28824347/71150833-5cda4280-222a-11ea-93c0-dec1cdbbd7ba.png" width=350>

**Fig 2:** Screenshot taken on same device for same search term, but on DDG engine.

#### Steps to reproduce
* Search from low width device on any Searx instance. For example, search this "[radix sort](https://searx.me/?q=radix%20sort&categories=general&language=en-US)" term.
* Scroll to the bottom of the page.

You'll see the info box is at bottom of the page.

**Comment by return42** [comment]
What is the requirement of this issue?

> it would be nice, if we could make UI responsive for better user experience.

if a new theme is the requirement, send us your PR adding a new theme and we will be happy.

Or do you want to see a theme changed? ..

> Info Box at bottom of the page

Then feel free to reopen this issue and name the theme and its malfunction / Thanks!

**Comment by etanot** [comment]
> What is the requirement of this issue?

Sorry, for mixing everything (feature request and bug report) in the same issue.

> Then feel free to reopen this issue and name the theme and its malfunction / Thanks!

Mainly, in this issue, I want to report a bug in `Oscar` theme and change the issue description and title, accordingly.

**Comment by dalf** [comment]
@finn0 give a try to the "simple" theme if not already done.

**Comment by etanot** [comment]
> try to the "simple" theme if not already done.

Thanks, it works for `Simple` as well as `Legacy` theme, but not for `Oscar`; @dalf, is this intentional behavior of **Oscar** theme?

**Comment by dalf** [comment]
I don't think this is intentional, just not tested with a mobile device.

### Technical note
(may not work)

See https://getbootstrap.com/docs/3.3/css/#grid-column-ordering

1. Move this div https://github.com/asciimoo/searx/blob/b0177847f8e04d0465489b9c906b485c6c7d8018/searx/templates/oscar/results.html#L18
2. After this div https://github.com/asciimoo/searx/blob/b0177847f8e04d0465489b9c906b485c6c7d8018/searx/templates/oscar/results.html#L95

Result with col-sm-push & col-sm-pull :
```html
<div class="col-sm-4 col-sm-push-8" id="sidebar_results">
...
</div>
<div class="col-sm-8 col-sm-pull-4" id="main_results">
...
</div>
```

**Comment by etanot** [comment]
@dalf
> (may not work)

Thanks for the suggestion, it pretty much works. But, I don't like those boxes, `Suggestion Box` and `Link Box` at the top of the page. In my humble opinion moving them to bottom of the page would be good idea. What do you think?

Here, currently Oscar themes looks like this on low width devices.

<img alt="oscar-theme-fix" src="https://user-images.githubusercontent.com/28824347/71249433-0695fe00-2315-11ea-8047-e807fea1c00d.png">

I guess, I can fix that.

**Comment by etanot** [comment]
@dalf,

When I try to optimize UI for mobile, it becomes creepy for desktop and vice versa. I cannot find a balanced solution, so for now, I've opened a MR. Can you review it, please?
