### ISSUE TITLE
Empty suggestion box

### ISSUE THREAD

**Issue by etanot** [searx/searx#1782]
### Description
Getting an empty `Suggestion Box`

### Steps to reproduce it
- On a Searx instance
  - Enter [git add](https://searx.be/?q=git%20add&categories=general&language=fr-BE) query on [searx.be](https://searx.be) instance.

![searx be](https://user-images.githubusercontent.com/28824347/71315412-ac03bb80-2454-11ea-8d4b-b8ce38c3a411.png)
Fig 1: Searx.be instance

- On master branch
  * Clone master branch
  * Run Searx instance, locally
  * Open Searx web interface and enter `!ddd git add` query in the search bar and hit enter

![locally](https://user-images.githubusercontent.com/28824347/71315416-c0e04f00-2454-11ea-810d-d1cf0807035e.png)
Fig 2: Local instance

![locally-json](https://user-images.githubusercontent.com/28824347/71315417-c342a900-2454-11ea-83c7-52ab617756d4.png)
Fig 3: JSON output of the local instance

### Actual behavior
Empty **Suggestion Box**.

### Expected behavior
Don't show **Suggestion Box**, if it's empty.

### Additional info
This behavior is only reproducible on searx.be instance, may be because Searx.be is running latest commit directly from master branch. So it might be chance that bug is appeared due to a commit which is committed after v0.15.0 tag.

**Comment by MarcAbonce** [comment]
I included a fix for that in #1686, but maybe it could be a separate PR if that one is not merged.
The actual fix is very simple as shown here: 7829b25.

**Comment by etanot** [comment]
@MarcAbonce Thanks for MR. Can mention about this issue in MR description, so that this issue will automatically close when MR is accepted?

**Comment by return42** [comment]
Fixed by #1686
