### ISSUE TITLE
Second Page the same es Page one

### ISSUE THREAD

**Issue by Happyfeet01** [searx/searx#1789]
Hello,

I use searx and I’m happy, but I found an bug.
The search results on Page 2 are the same as on Page 1.

**Comment by unixfox** [comment]
Can you give more details like which engine you use, which searx instance you used?

**Comment by Happyfeet01** [comment]
Yes sure.

My instance: https://suche.dasnetzundich.de

My settings: https://paste.dasnetzundich.de/view/4557ef81 

Von meinem iPhone gesendet

**Comment by return42** [comment]
I tried to run a local instance with your settings file but the one you pasted is broken. E.g. see line 431 and others where title_xpath  & content_xpath in one line .. may be a C&P typo?

**Comment by Happyfeet01** [comment]
Typo error

https://paste.dasnetzundich.de/view/4c0b5f55

Von meinem iPhone gesendet

**Comment by return42** [comment]
Again same typos .. and some new .. thats annoying.  

Clean up your mess and then come back.
