### ISSUE TITLE
information regarding FedSearx?

### ISSUE THREAD

**Issue by chaosmonk1** [searx/searx#1794]
After reading the [v1.0.0 announcement](https://github.com/asciimoo/searx/issues/1703) I looked up NLnet, and found [this page](https://nlnet.nl/project/FedSearx/).  It seems to refer to plans to federate Searx instances, which is an exciting idea, but it is not specific about the status of this or who if anyone is working on it.  I then searched the wiki and issue tracker for "fedsearx" and "federation" and found only [this issue](https://github.com/asciimoo/searx/issues/39) which hasn't seen activity in a while.  Is such a feature being worked on, and if so is there any documentation or roadmap from which I could learn more about it?  Thanks.

**Comment by return42** [comment]
I can speak only for my self. There are a lot of old articles out, pushing searx fantasies. Meshing up searx instances is more a question of organization and trust then technology.  We at searx have a lot of open issues & bugs which are real and I want to prioritize these.

**Comment by chaosmonk1** [comment]
>  We at searx have a lot of open issues & bugs which are real and I
>  want to prioritize these. 

Makes sense, thanks!
