### ISSUE TITLE
Documentation: enforce filtron

### ISSUE THREAD

**Issue by dalf** [searx/searx#1795]
Currently, the [documentation](https://asciimoo.github.io/searx/admin/installation.html) (even if it requires a huge update), describes how to setup:
```[reverse proxy]-->[uwsgi]-->[searx]```

I think:
- this should be removed to avoid unsafe installations (because it is vulnerable to bots), or at least put aside with a warning.
- Filtron should be a first citizen, not an [optional layer](https://asciimoo.github.io/searx/admin/filtron.html). The documentation should explain how to setup step by step
```[reverse proxy]-->[filtron]-->[uwsgi]-->[searx]```

[EDIT] Here I have pick [filtron](https://github.com/asciimoo/filtron) as bot shield, but there is also [antibot-proxy](https://github.com/unixfox/antibot-proxy).
Also the comments of https://github.com/asciimoo/searx/pull/1771

**Comment by return42** [comment]
I like to add a hint to https://github.com/asciimoo/searx/issues/1634

**Comment by return42** [comment]
closed by PR #1803 / see docs at: https://asciimoo.github.io/searx/admin/index.html
