### ISSUE TITLE
Run a master build of Searx instance

### ISSUE THREAD

**Issue by etanot** [searx/searx#1797]
Is it good idea to run a Searx instance which runs a master build? In my opinion these are the following advantages of running a master build of Searx instance:

- We can more easily detect and fix a bug currently present in master branch if it's introduced by some latest commit.
- Better testing of master branch. We may miss some edge test cases while we're testing our newly implemented feature or fix a bug, locally.
- ...

I asked this because many projects runs an instance of project which runs latest master branch commit for developers, so they can test and play with code. So, isn't good idea to run a such instance for Searx also? For example, dev.searx.me instance for developers. Probably we can do this with help of some scripts.

**Comment by return42** [comment]
> Is it good idea to run a Searx instance which runs a master build? .. Better testing of master branch.

It is always better to test before commit, so I prefer our Makefile solution over a CI solution (which always checks after commit).

You can test your master or even your feature branch locally just by typing:

    make run

See https://asciimoo.github.io/searx/dev/makefile.html#make-run

**Comment by etanot** [comment]
> It is always better to test before commit

Indeed, but it would be still nice to have an instance which runs latest master commit because it's been while since Searx releases a stable version, so running a latest version encourage developers to use that instance for general purpose also, so there will be high probability of fixing some bugs which appears due to some latest commits and stops them from appearing it in next stable release; and adding some new feature, that's why most projects host a beta version of project.

PS: From yesterday, seems like https://searx.me is also running latest master commit. Is it for temporary?

**Comment by return42** [comment]
> Indeed, but it would be still nice to have an instance which runs latest master commit because 

Seems to me, that you did not understand what `make run` does?

**Comment by bauruine** [comment]
The well maintained instances have to run on master because engines constantly break. @return42 has wrote something about it a few days ago https://github.com/asciimoo/searx/issues/1792#issuecomment-570203111.
