### ISSUE TITLE
Engine code: describe which XPath can fail, which must not.

### ISSUE THREAD

**Issue by dalf** [searx/searx#1802]
In the result parsing, engines parse the HTML using lxml (most of the time). If an XPath request doesn't return at least one result, it may be fine or trigger an error later. In the later case, it is difficult to know exactly what is going on without looking at the downloaded HTML.

This issue suggests:
* to add new exception classes.
* to add two optional parameters to [eval_xpath](https://github.com/asciimoo/searx/blob/85b37233458c21b775bf98568c0a5c9260aa14fe/searx/utils.py#L465) function to check the result count.

It may help to know when an engine starts to be broken if the engine codes says which XPath request should not fail (?).

I'm not sure if it is useful and /or a privacy problem if searx makes statistics about broken XPath ?

### Class hierarchy

```
SearxException
	SearxParameterException
	SearxEngineException
		SearxEngineCaptchaException (instead of RuntimeWarning in google.py)
		SearxEngineXPathException
```

### eval_xpath
```python	
def eval_xpath(element, xpath_str, eq=None, gte=None):
    xpath = get_xpath(xpath_str)
    result = xpath(element)
    # new code: check result count now
    if eq is not None and len(result) != eq:
	raise SearxEngineXPathException(xpath, eq=eq)
    if gte is not None and len(result) < gte:
	raise SearxEngineXPathException(xpath, gte=gte)
    return result
```

#### extract_url
https://github.com/asciimoo/searx/blob/master/searx/engines/xpath.py#L53
```python
def extract_url(xpath_results, search_url):
    if xpath_results == []:
        raise Exception('Empty url resultset')	
```
--> Make the check before calling extract_url

#### bing engine
```python
	...
    for result in eval_xpath(dom, '//div[@class="sa_cc"]'):
        link = eval_xpath(result, './/h3/a', eq=1)[0]
	...
    for result in eval_xpath(dom, '//li[@class="b_algo"]'):
        link = eval_xpath(result, './/h2/a', eq=1)[0]
	...
```

#### google engine
```python
	title = extract_text(eval_xpath(result, title_xpath, eq=1)[0])
	url = parse_url(extract_url(eval_xpath(result, url_xpath, eq=1), google_url), google_hostname)
```
The huge try/catch to ignore all the parsing errors would be able to display the XPath in the logs.

Another way without try/catch and without modification to the eval_xpath function:
```python
	title_xpr = eval_xpath(result, title_xpath)
	url_xpr = eval_xpath(result, url_xpath)
	if len(title_xpr) > 0 and len(url_xpr) > 0:
		title = extract_text(title_xpr[0])
		url = parse_url(extract_url(url_xpr, google_url), google_hostname)
		...
```

The eq and gte parameters can't help much for the [result count](https://github.com/asciimoo/searx/blob/4cddb829f9f3718933f16346383fe989effc07e3/searx/engines/google.py#L228-L233).

Using eq:
```python
    try:
        results_num = int(eval_xpath(dom, '//div[@id="resultStats"]//text()', eq=1)[0]
                          .split()[1].replace(',', ''))
        results.append({'number_of_results': results_num})
    except:
        pass
```

Without eq, with more checking:
```python
	results_num_xpath = eval_xpath(dom, '//div[@id="resultStats"]//text()')
	if len(results_num_xpath) > 0:
		results_num_text = results_num_xpath[0]
		results_num_text_first = results_num_text.split()[1].replace(',', '') 
		try:
			results_num = int(results_num_text_first)
			results.append({'number_of_results': results_num})
		except ValueError:
			pass
```

**Comment by asciimoo** [comment]
This is a good idea, i like it a lot.

**Comment by dalf** [comment]
Some fun with Python, I'm not sure this is practical everywhere. For sure there is some overhead.

Currentl arxiv.py response function:
https://github.com/searx/searx/blob/2fc3b17c85512280173bb47f449cc2faa64b0501/searx/engines/arxiv.py#L41-L76

What it could be:
```python
def response(resp):
    results = []

    dom = html.fromstring(resp.content)

    for entry in dom >> '//entry' >> IsList:
        content = '{doi_content}{abstract_content}'.format(
            doi_content=entry >> './/link[@title="doi"]' >> (0, EmptySpan) >> Text,
            abstract_content=entry >> './/summary' >> 0 >> Text)

        if len(content) > 300:
            content = content[0:300] + "..."

        results.append({'url': entry >> './/title' >> 0 >> Text,
                        'title': entry >> './/id' >> 0 >> Text,
                        'publishedDate': datetime.strptime(entry >> './/published' >> 0 >> Text,
                                                           '%Y-%m-%dT%H:%M:%SZ'),
                        'content': content})

    return results
```


see https://gist.github.com/dalf/f8dfc5878b1130be22ed8bdef3820018

Perhaps a more robust alternative for a DSL: https://lxml.de/2.0/extensions.html
