### ISSUE TITLE
Vote: Abandon py2?

### ISSUE THREAD

**Issue by asciimoo** [searx/searx#1807]
Py2 is no longer supported officially. Do you want to discontinue the support of py2 compatibility in searx?
Please vote with :+1: to abandon and :-1: to keep it

**Comment by rachmadaniHaryono** [comment]
which version does searx support?

setup.py's classifier doesn't mention this

travis.yml have 2.7, 3.5, & 3.6

**Comment by MarcAbonce** [comment]
I'm pretty sure there are some instances that still run on py2, so it would be nice to release a final py2 supporting version with a very noticeable deprecation warning (both in the logs and in the release notes) so there's no surprises when we actually deprecate it.

**Comment by rachmadaniHaryono** [comment]
> good point, if version support is clarified we have to add python_requires argument to setup call.

because nobody mentioned it yet, from that link given there is warning

> Support for this feature is relatively recent. Your project’s source distributions and wheels (see Packaging your project) must be built using at least version 24.2.0 of setuptools in order for the python_requires argument to be recognized and the appropriate metadata generated.

> In addition, only versions 9.0.0 and higher of pip recognize the python_requires metadata. Users with earlier versions of pip will be able to download & install projects on any Python version regardless of the projects’ python_requires values.

checking setuptools can be done before running setup. but checking if setup file run with pip is harder

other alternative to this method is just check python version before running setup and print warning (or quit) if python version don't meet minimum requirement

**Comment by return42** [comment]
> checking setuptools can be done before running setup. but checking if setup file run with pip is harder

In practice i guess this is nothing we need to handle. pip encourages its users to always use a recent version of pip  (and setuptools).

**Comment by asciimoo** [comment]
Thanks for your feedback, seems the results are quite straight forward: We are dropping the support of py2.

**Comment by return42** [comment]
Fine .. but we schould pay attention to @MarcAbonce https://github.com/asciimoo/searx/issues/1807#issuecomment-575877050 remark about deprecation warning.

Should we add a deprecation warning in a searx v0.16? .. and drop py2 with searx v1.0?

**Comment by asciimoo** [comment]
> Should we add a deprecation warning in a searx v0.16? .. and drop py2 with searx v1.0?

Good idea, lets do this.

**Comment by return42** [comment]
> Should we add a deprecation warning in a searx v0.16? .. and drop py2 with searx v1.0?

FWIW: python 2 support is slowly slipping away from us. Little by little we had to remove the first (unit & lint) tests for Py2.

We don't need a deprecation warning, Python itself and the libraries themselves spit out enough.

I would suggest that we do nothing at all and let the support gradually expire.

**Comment by virtadpt** [comment]
The final Python 2.x release was yesterday.  As far as can be told, they're killing that line off.  I think we should help them by making Python 3 the officially supported version for Searx.
