### ISSUE TITLE
Image preview issue in Oscar

### ISSUE THREAD

**Issue by Cqoicebordel** [searx/searx#181]
I have a bit of trouble reproducing this, and I don't seem able to find the source :

In oscar, when you make a query like `!fl test` and try opening the image in the preview window, there is a bug with some images, and depending on browsers, where the image does not display, and nothing get displayed (in Opera 12) or the image in text form is displayed (like if you opened an image with `cat`)(Firefox and Chromium).

If you have an idea...

**Comment by Cqoicebordel** [comment]
Seriously ?! It was only that !
So, if we use the wrong url, flickr sends the images, but with the wrong mime-type I suppose. Kind of weird.

**Comment by asciimoo** [comment]
@Cqoicebordel it is weird indeed. I can't imagine whats the motivation behind it

**Comment by dalf** [comment]
I still have an issue with "!flick test", the fourth image.

**Comment by dalf** [comment]
I found another weird case.

How to reproduce : 
- search for `!500px big bang theory`
- click on each image
- in case all images are displayed correctly, refresh the page

I can reproduce the bug on PC and on searx.me

**Comment by Cqoicebordel** [comment]
Did you try with another browser ? I can't reproduce it on chrome and opera 12.  
It may be a cache issue locally.

**Comment by dalf** [comment]
I can't be sure if I have tested with two browsers.
Now I can't reproduce the case with Chrome and FF (before and after clearing the cache).
May be I didn't apply http://cdn.meme.am/instances/500x/57076520.jpg
