### ISSUE TITLE
searx support for Google's featured snippets

### ISSUE THREAD

**Issue by sriramnpkt** [searx/searx#1811]
When I look for something like 'ooo meaning' in Google, it says 'Out Of Office' with further definition. This gives information explicitly and minimises the time spent on that. Can searx instances support such a feature ? If it exists already, please let me know. In case of keywords like stopwatch, instead of redirecting to another website, Google brings up a stopwatch, if this feature can be implemented, I will be very excited to use searx more. I have attached images below regarding this. PFA.

![ooo_google_Screenshot from 2020-01-24 14-37-32](https://user-images.githubusercontent.com/26897463/73058185-1cb95000-3eb9-11ea-831c-9a59a0c57c41.png)
![ooo_searx_Screenshot from 2020-01-24 14-37-00](https://user-images.githubusercontent.com/26897463/73058186-1d51e680-3eb9-11ea-9f33-815658924dc7.png)
![stopwatch_searx_Screenshot from 2020-01-24 14-36-29](https://user-images.githubusercontent.com/26897463/73058187-1d51e680-3eb9-11ea-97b9-0009faa074ba.png)
![stopwatch_google_Screenshot from 2020-01-24 14-35-51](https://user-images.githubusercontent.com/26897463/73058188-1d51e680-3eb9-11ea-9fe8-8221101f446f.png)

**Comment by unixfox** [comment]
If you have some experience into web development feel free to open a pull request for that. You could use the [wikipedia engine](https://github.com/asciimoo/searx/blob/master/searx/engines/wikipedia.py#L111) as an example for that because it displays a small infobox when a request match their database:
![](https://i.imgur.com/LxSfVc1.png)

**Comment by dalf** [comment]
This PR https://github.com/asciimoo/searx/pull/1329 parses some of the Instant Answer.

IHMO, it's a very long work to parse the different featured snippets especially when it involves javascript (an perhaps, the javascript has been transpile from clojure). This work that can break at anytime when Google updates its servers.

It would be better to implement your own thing, or fork an existing project.
I understand that it is an huge task, and may be it should be different project that searx uses as any other engines.

**Comment by unixfox** [comment]
Implemented as Searx infobox.
Working demo: https://searx.be/search?q=ooo+meaning&category_general=on&time_range=&language=en-US

**Comment by seniorm0ment** [comment]
Does this include maps listingd?
I can make a new issue if you wish, didn't want to spam though.

If you search "the white house dc" on Google, it fetches their resultbfor The White House Washing DC, with a phone number, address, NHL. Description, artworks, reviews, social media, directions, website, etc.

For stores it also grabs business hours, etc.

This is really amazing, as currently when using searx, you have to rely on sites like yelp for this information, especially just for an address, phone number, and directions link.'

It would be very nice to be able to pull these from google.

**Comment by unixfox** [comment]
@grravity 

It only fetches the infobox at the top of the page:
![](https://user-images.githubusercontent.com/26897463/73058185-1cb95000-3eb9-11ea-831c-9a59a0c57c41.png)

Not the one on the right side which what you are describing by "maps listing".

Feel free to open a new feature request (this time by choosing "Feature request" instead of creating a blank issue).

**Comment by seniorm0ment** [comment]
Ah, is it a template issue? Fasthub doesn't grab templates for some reason. I'll open a new issue from my browser, sorry!

**Comment by unixfox** [comment]
> Ah, is it a template issue? Fasthub doesn't grab templates for some reason. I'll open a new issue from my browser, sorry!

Yes it's a template issue. Seems like Fasthub should display the templates: https://github.com/k0shk0sh/FastHub/issues/2852
