### ISSUE TITLE
anti-captcha.com

### ISSUE THREAD

**Issue by unixfox** [searx/searx#1812]
This is a follow up of my comment in the issue 729: https://github.com/asciimoo/searx/issues/729#issuecomment-563988747.

------------------------

## Why
anti-captcha.com is a solution dedicated to automatically solve captcha especially Google Recaptcha. In searx this solution is useful for resolving Google Recaptcha that are used by Google to block an instance that do too many requests from the same IP to their servers and thus render the Google engine usable again on public Searx instances.

## Cost of using anti-captcha

According to @Perflyst when he talked about it in the issue https://github.com/omarroth/invidious/issues/886 the cost of deploying a solution like this is around $8.76 per year which is pretty cheap. These numbers are specific when doing requests to Youtube, I still don't know if the amount would be lower or higher when doing requests to Google Search.

What does everyone think about that? Is this a good thing to implement into the core of Searx? Would you be favorable to work on it?

## How to implement it?

I already talked about it with @dalf and he is okay with this solution.
The challenge according to him is to make the solving working in a uWSGI environment because each individual process cannot talk directly and easily between each other to announce that a Google Recaptcha has been solved.

What I'm suggesting for this implementation is a loop that would check every 5 minutes if the instance is blocked by a Google Recaptcha then submit a task to anti-captcha to solve the Google Recaptcha.
A separate file would be used to persistently store the whitelist cookie ([more details about this cookie here](https://github.com/omarroth/invidious/issues/957#issuecomment-576424042), it's the second type of recaptcha).
In a uWSGI environment the processes would watch for this file changes and "reload" the Google engine with the new cookie.

An ability to customize the URL of the anti-captcha API is also preferred because I actually found a way to automatically solve a Google Recaptcha without using anti-captcha and thus rendering the cost to zero. I implemented the same API backend as anti-captcha to make it easier to implement into Searx and if one day I'm solution isn't working anymore the real anti-captcha will be still usable instead.
I'll talk about it after the implementation lands into Searx because it is kinda too big of a flaw to directly publicly release the details (if you are really interested contact me by email).

## Documentation
- anti-captcha API documentation: https://anti-captcha.com/apidoc/recaptcha

**Comment by unixfox** [comment]
Meanwhile, I developed a temporary proxy which can be plugged into Searx by using the `proxies` parameter into the `settings.yml` like so:
````yml
outgoing: # communication with search engines
    request_timeout : 2.0
    useragent_suffix : ""
    pool_connections : 100
    pool_maxsize : 10
    proxies :
        http : http://127.0.0.1:8081
        https: http://127.0.0.1:8081
````

Then it's needed to launch Searx with the environment variable `CURL_CA_BUNDLE` so that the SSL verification doesn't fail:
````shell
export CURL_CA_BUNDLE=/path/to/proxy-sorry-google-recaptcha/ca/certs/ca.pem
````

Link to the project (with how to set up it): https://github.com/unixfox/proxy-sorry-google-recaptcha (skip the 4 & 5 steps).

**Comment by asciimoo** [comment]
This is a brilliant solution, however as I understand, it establishes an active cookie based session to google that allows them to track the instance and personalize results. These are harmful from a privacy aspect. Do I understand correctly?

**Comment by unixfox** [comment]
The cookie is only used to be able to be whitelisted from the rate limit system for 2 hours. After that the cookie is invalid and then the program needs to renew the cookie (thus a new content in the cookie).

It could be used for tracking but let's be honest they could already do it with the IP (because most of the public Searx instance have a fixed IP) and I think they would prefer to use their current tracking method instead because it's more efficient.
I don't think they would start tracking an instance based on a randomized & only valid for 2H cookie.

**Comment by asciimoo** [comment]
> It could be used for tracking but let's be honest they could already do it with the IP 

Tracking by IP isn't reliable, so AFAIK google doesn't do it. There can be thousands of computers behind a public IP (yaay NAT) so it isn't the right way to track users. Session cookie is an explicit unique string that identifies an existing browser session, IP is far from this.

**Comment by unixfox** [comment]
> Tracking by IP isn't reliable, so AFAIK google doesn't do it. There can be thousands of computers behind a public IP (yaay NAT) so it isn't the right way to track users.

This anti-captcha solution is targeted towards public Searx instances and not private Searx instances. Most if not all of them have a static fixed public IP.
If Google really wants to display or restrict public Searx instances they could have done it a long time ago using the IP.

I do not expect anyone that host a private instance to use this solution, again this solution will only be used by owners of public Searx instances which receive a couple of hundreds requests per day.

**Comment by asciimoo** [comment]
> This anti-captcha solution is targeted towards public Searx instances and not private Searx instances.

Why does it matter if the instance is public or private? Google can only see that they received a request with a random user agent even if there is a public searx instance running on that IP. They can't distinguish between a request coming from searx or coming from a real browser while there are no session cookies. So they can't assume that requests coming from a single IP means that requests coming from a single user/application - while there is no session cookie.

> Most if not all of them have a static fixed public IP.

What is the point here? This static IP can route a whole company/city/etc or it can provide a VPN service even if it has a publicly available searx service. Google has no clue who did the request, they know only the public IP but cannot connect two requests together just because the IP is the same, Requests can come from any number of totally distinct devices even if the public IP is static. That's why they use cookie based sessions to be able to identify users/browsers and to be able to connect individual requests together to build profiles.

>  If Google really wants to display or restrict public Searx instances they could have done it a long time ago using the IP.

They don't want to restrict, they want to track.

I still think that this feature can compromise privacy and supports the filter bubble. An alternative solution can be a proxy service that provides bunch of IPs that searx can rotate if google throws a captcha.

**Comment by unixfox** [comment]
> An alternative solution can be a proxy service that provides bunch of IPs that searx can rotate if google throws a captcha.

This isn't viable, IPs that aren't blocked by Google Search are very rare and cost too much for a public Searx instance maintainer.
![2020-01-29_02-29](https://user-images.githubusercontent.com/4016501/73320306-c2ace780-4236-11ea-9540-adfe1792f486.png)
Screenshot from SSLProxies: https://www.sslproxies.org/#pricing

> They don't want to restrict, they want to track.
> I still think that this feature can compromise privacy and supports the filter bubble.

I completely agree with you that they want to track their users but I don't think they will do it based on a temporary cookie used only for distinguish the clients that are whitelisted on their rate limiting system and Google could have done it a long time ago here is why:
In the current Google engine implementation we already send enough data for Searx to be recognizable from a normal browser and being tracked/restrict/filter:
- the IP (fixed IP for public Searx instance)
- the cookie `GOOGLE_ABUSE_EXEMPTION` with the value "x": https://github.com/asciimoo/searx/blob/master/searx/engines/google.py#L189
- the `Accept-Language` header very different from a normal browser: https://github.com/asciimoo/searx/blob/master/searx/engines/google.py#L198. A common `Accept-Language` header from every major browser ends with "q=0.5"
- the user agents sent to Google are old: https://github.com/asciimoo/searx/blob/master/searx/data/useragents.json
- all the missing headers that a normal browser send

> Why does it matter if the instance is public or private? Google can only see that they received a request with a random user agent even if there is a public searx instance running on that IP. They can't distinguish between a request coming from searx or coming from a real browser while there are no session cookies. So they can't assume that requests coming from a single IP means that requests coming from a single user/application - while there is no session cookie.

A private Searx instance won't enable this solution because it isn't blocked by Google due to the low amount of requests made to the Google servers. That's why I said that this solution is targeted towards public instances.

Something that I forgot to say, the anti-captcha feature has to be **optional and not by default**. Mainly because it's up to the maintainer of the Searx instance to use it and buy credits on anti-captcha to have its own API key.

----------------

Can you reopen this issue? We have the solution to make the Google engine working again for public Searx instances and really there aren't any other viable alternatives. On invidious they have this solution working for over two months and it works great for them. @omarroth is probably for guarantee the privacy of the users of invidio.us, if deploying an anti-captcha solution would have compromise the privacy he wouldn't have implemented it.

**Comment by Pofilo** [comment]
Ethically speaking, [anti-captcha.com](http://anti-captcha.com/) is a solution which may not be acceptable. Poor people are underpaid to resolve our captchas ...

**Comment by asciimoo** [comment]
> Something that I forgot to say, the anti-captcha feature has to be optional and not by default.

This sounds better. It would be good to compare the results of an instance with solved google captcha and another instance which isn't blocked by google to see if it uses these cookies to create filter bubble.

> This isn't viable, IPs that aren't blocked by Google Search are very rare and cost too much for a public Searx instance maintainer.

After a quick search I found quite a lot proxy providers with pretty reasonable prices, eg.: https://luminati.io/pricing - they even have mobile IPs.

> In the current Google engine implementation we already send enough data for Searx to be recognizable from a normal browser and being tracked/restrict/filter:

It isn't important, google and everyone else use session cookies to track user sessions even if some of the requests have rare attributes.
Google doesn't want to act against searx, of course if they would want they could do it easily, but that's not the case currently. They want to establish as many sessions as possible to build as many profiles as possible.

> the cookie GOOGLE_ABUSE_EXEMPTION with the value "x"

Yeah, we should send them a generated random string for every request.

> We have the solution to make the Google engine working again for public Searx instances and really there aren't any other viable alternatives.

One of the unique features of searx is that it can be hosted by everyone. My opinion is that it's better if someone hosts a private instance than adding features that might reduce privacy of public instances.

**Comment by unixfox** [comment]
> Ethically speaking, anti-captcha.com is a solution which may not be acceptable. Poor people are underpaid to resolve our captchas ...

That's why I also brought my help to provide an API which the same backend as anti-captcha but doesn't use the actual anti-captcha.com. (More details about it in the end of my first message.)

-----------------

> After a quick search I found quite a lot proxy providers with pretty reasonable prices, eg.: luminati.io/pricing - they even have mobile IPs.

It's way pricier than SSLProxies.
It's around $10/GB, a public Searx instance use around 3 GB of traffic if not more with Google images and so on. Also, their Residential (also the mobile) service expect you to pay a minimum of $500: 
![2020-01-29_11-51](https://user-images.githubusercontent.com/4016501/73350603-42fa3980-4285-11ea-88b8-c74e34d02e1b.png)

Let's be real, this solution isn't viable...

> This sounds better. It would be good to compare the results of an instance with solved google captcha and another instance which isn't blocked by google to see if it uses these cookies to create filter bubble.

I'm still going to test it on my own instance so for sure I can in a few months come back in this issue with some results about a potential filter bubble but I'm pretty sure that this won't happen and my instance will receive the same results as the few other instances which have working Google results.

> One of the unique features of searx is that it can be hosted by everyone. My opinion is that it's better if someone hosts a private instance than adding features that might reduce privacy of public instances.

Not everyone wants to host their own instance, it requires knowledge and time because the code of Searx changes so often that if someone doesn't keep up with the new commits their instance will likely stop working for some search engines or worst break: https://github.com/asciimoo/searx/pull/1661#issuecomment-570832817
Like I said in my previous message, it's up to the public instance owner to decide to activate this solution. We don't force anything, if the owner decide that it's bad for its users then he won't use it.
But at least let's provide a way for public instances owners to have a working Google engine if they decide that it's worth the *trade off*.

**Comment by m4teh** [comment]
> Ethically speaking, [anti-captcha.com](http://anti-captcha.com/) is a solution which may not be acceptable. Poor people are underpaid to resolve our captchas ...

Absolutely nonsense comment lacking any free market economic understanding. The service actually helps poor people by providing them a job they otherwise wouldn't have. Nobody is forcing them to do it. Your logic is why poor people stay poor. The same logic as minimum wage laws. You'd rather people have no employment over some employment.

**Comment by Pofilo** [comment]
I deleted a comment and lock this issue as it is going off the topic.
We are not here to discuss political issues. @m4teh You can contact me directly if you want.
