### ISSUE TITLE
Alert!: searx.me links to a scammer web as first search result

### ISSUE THREAD

**Issue by soulhash** [searx/searx#1814]
Estimated asciimoo

searx.me, at any public instance, links to a scammer web:

                https://aliexpi.com/90CZ

 as first search result, official website of: 

               https:// aliexpress.com
 

I think my alert is only an isolate isuue, 
at any manner  thank's a lot for your terrific search engine.

Regards

**Comment by dalf** [comment]
This is the searx.me page I have:
```
Sorry, this searx instance is down due to infrastructure issues. Please find another instance or setup your own.

Thank you for your understanding
```

With links to:
* https://asciimoo.github.io/searx/user/public_instances.html
* https://asciimoo.github.io/searx/admin/installation.html

**Comment by soulhash** [comment]
Hi dalf 
  
 You could test any active public instance of searx.me at:

 https://asciimoo.github.io/searx/user/public_instances.html

Sadly, all of them link to the fake aliexpress page : https://aliexpi.com/90CZ
as "Oficcial page"and first search ressult.

Overall I think is an isolated isuue..., 
by the way searx.me is a fantastic metasearch engine.

**Comment by unixfox** [comment]
Did you test on another browser?
Your browser could have been comprised because I don't see any "fake aliexpress" page on any Searx instance.

If that's not the case please link the exact URL where you see this "fake aliexpress" link.

**Comment by Happyfeet01** [comment]
Which Searchresult links to the Fakesite?

**Comment by unixfox** [comment]
Maybe this issue can be closed? We haven't heard anything from the author for almost 2 weeks.
