### ISSUE TITLE
Move WolframAlpha from "Science" to "General"

### ISSUE THREAD

**Issue by geckolinux** [searx/searx#1815]
Hi there, first of all, many thanks for SearX, it's really impressive thus far.

I would appreciate it if WolframAlpha could be moved from "Science" to "General". This is because it is extremely good at giving "instant answers" in general searches (conversions, facts, trivia, translations, etc.) But when I enable the Science category by default it clutters up my results with a lot of whitepapers that usually aren't relevant. So for now I just disabled all the other options under "Science" except WolramAlpha. But it would be nice to be able to do Science searches too without re-configuring the engines.

Another related improvement would be to maybe include a separate category for "Instant Answers" and put things like WolframAlpha and Wikifacts there.

Thanks a lot!

**Comment by geckolinux** [comment]
https://github.com/asciimoo/searx/pull/1834/commits/f758a4374a8911ecbf840d0f21beda2805b918c0

**Comment by return42** [comment]
Hi @geckolinux  can we close this issue?
