### ISSUE TITLE
Apache reverse proxy setup with subpath (http://myhost.xx/searx)

### ISSUE THREAD

**Issue by return42** [searx/searx#1819]
I have setup searx as uwsgi service at `http = 127.0.0.1:8888` and a apache mod_proxy with `ProxyPath` to a filtron service listening on `127.0.0.1:4004` (target is searx at port `:8888`).

The setup works fine when I use the root URL as public URL `http://myhost.xx/`:

    ProxyPass "/" "http://127.0.0.1:4004/"
    ProxyPassReverse "/" "http://127.0.0.1:4004/"

Now I want to move my searx instance to a subpath in the public URL, e.g. `http://myhost.xx/searx`:

    ProxyPass "/searx" "http://127.0.0.1:4004/"
    ProxyPassReverse "/searx" "http://127.0.0.1:4004/"

With I got a pure "HTML page" which tries to load resource relative from root URL `/` instead from `/searx/`

I read this article https://blog.macuyiko.com/post/2016/fixing-flask-url_for-when-behind-mod_proxy.html and I found similar in our sources https://github.com/asciimoo/searx/commit/6ef7c3276c308ba12b80e22068de422247fdb4b9 so I tried also:

    ProxyPass "/searx" "http://127.0.0.1:4004/"
    ProxyPassReverse "/searx" "http://myhost.xx/searx"

But this does not change anything, the HTML page from searx always try to load resources from the root URL.  .. where is my mistake?

**Comment by unixfox** [comment]
Why would you want to do that? I mean nowadays SSL/TLS certificates are free even for subdomains. There is no real reason to serve another service in a subpath.

**Comment by return42** [comment]
@unixfox sorry if I was not clear I was asking about ProxyPass and subpath .. I have found my mistake and will post the solution ..

**Comment by return42** [comment]
I forgot to set request header `X-Script-Name` here is my final apache site

**Updated: Jan, 31 2020** ...

```apache
ProxyPreserveHost On

<Location /searx >

    Require all granted
    Order deny,allow
    Deny from all
    #Allow from fd00::/8 192.168.0.0/16 fe80::/10 127.0.0.0/8 ::1
    Allow from all

    ProxyPass http://127.0.0.1:4004
    RequestHeader set X-Script-Name /searx

    # In Apache it seems, that setting HTTP_HOST header direct here does have no
    # effect.  I needed to set 'ProxyPreserveHost On' (see above).  HTTP_HOST is
    # needed by searx to render correct *Search URL* in the *Link* box and
    # *saved preference*.

    # RequestHeader set Host myhost.xx

</Location>
```
