### ISSUE TITLE
No Search Results Info for Startpage Engine

### ISSUE THREAD

**Issue by etanot** [searx/searx#1825]
Type: Bug report

**Steps to reproduce**:
- Add `!sp` bang command in any search term

For example: [!sp searx](https://searx.be?q=%21sp%20searx&categories=none&language=en-US)

**Actual result**:
Unlike other engines, Startpage results only contains title and URL, no info.

![startpage](https://user-images.githubusercontent.com/28824347/73602144-d920af00-4566-11ea-9e80-ee36496c36a2.png)
**Image 1: Startpage search results**
`Source`: https://searx.be?q=%21sp%20searx&categories=none&language=en-US

![qwant](https://user-images.githubusercontent.com/28824347/73602173-2735b280-4567-11ea-923a-a12f555ede35.png)
**Image 2: Qwant search results**
`Source` :  https://searx.be?q=%21qw%20searx&categories=none&language=en-US

**Expected result**:
Like other engines, Startpage results should also contain info about search results.

**Comment by unixfox** [comment]
It was a specific issue to searx.be. Just fixed now. You can close this issue.

**Comment by etanot** [comment]
@unixfox, If you don't mind, what was the issue? That only happens with Startpage engine, only.

**Comment by unixfox** [comment]
I forgot that I had an old startpage code engine from a previous PR that at that time wasn't merged yet because I wanted to bring startpage working again.
