### ISSUE TITLE
Hiding timeout error for one engine

### ISSUE THREAD

**Issue by sevospl** [searx/searx#1828]
Is it possible to hide/disable timeout error for one engine?

**Comment by unixfox** [comment]
Just set the default timeout to a large number?

**Comment by sevospl** [comment]
> Just set the default timeout to a large number?

The thing is I want to decrease the timeout as much as possible to make my searching even faster. There are some engines that are irrelevant to me and I'd be ok with "hit or miss", but the whole timeout thingy is annoying.

**Comment by virtadpt** [comment]
It might make more sense to disable the search engines you don't care about in the searx/searx/settings.yml file.

**Comment by sevospl** [comment]
> It might make more sense to disable the search engines you don't care about in the searx/searx/settings.yml file.

Yeah, I disabled some but there are some that I'd rather keep with "hit or miss" :)

**Comment by virtadpt** [comment]
Okay, that makes sense.

**Comment by andrew6838** [comment]
> Is it possible to hide/disable timeout error for one engine?

when I use new IP address, and make a search , then I get timeout error, and then I make a search again, it can work without any errors.....

Why is it happened on new IP?

**Comment by unixfox** [comment]
> > Is it possible to hide/disable timeout error for one engine?
> 
> when I use new IP address, and make a search , then I get timeout error, and then I make a search again, it can work without any errors.....
> 
> Why is it happened on new IP?

First you are again going off topic in an issue that is unrelated to your real problem. Please stop doing that.

Secondly, the new IP may not be fully operational. The thing is when having a new IP all the TCP connections that Searx made are dropped and Searx doesn't have a mechanism for automatically retrying again so that's why when you search again it works.
