### ISSUE TITLE
Update pypi.org with the latest version 

### ISSUE THREAD

**Issue by hubertbanas** [searx/searx#1829]
It would be beneficial to have https://pypi.org/project/searx/ updated on every release.

**Comment by asciimoo** [comment]
It is added: https://pypi.org/manage/project/searx/release/0.16.0/ .

**Comment by rachmadaniHaryono** [comment]
> .../manage/project/...
> access denied

it seem link above is for owner/maintainer

here is another link https://pypi.org/project/searx/0.16.0/
