### ISSUE TITLE
Any way to force POST request (instead of GET) to avoid parameters logging?

### ISSUE THREAD

**Issue by sevospl** [searx/searx#1839]
Hi!

I'm using Searx with my shared hosting provider that supports Python. Unfortunately they log everything with Nginx - when I saw access.log, every query was logged (incl. IP addresses etc.). 

The question is.. is there any workaround to solve this problem? Firefox and Vivaldi both support POST and it's possible to use this method by default but I'd rather keep using Brave as I just like this browser.

Any idea?

**Comment by unixfox** [comment]
Even if you force POST requests some browser will still do requests using GET. For example chrome doesn't support post requests from the search bar.

**Comment by kvch** [comment]
You can configure the HTTP method to use on the Preferences page of searx. The setting is under General tab (in the Oscar theme) and named Method.
