### ISSUE TITLE
opensearch.xml malformed

### ISSUE THREAD

**Issue by julpec** [searx/searx#184]
I tried to add searx to my firefox's (iceweasel) search bar and it didn't "found" the opensearch.xml file.

It say that it couldn't download the search plugin from http://mysearxurl/opensearch.xml

I tried to access to the file with my browser and I have this error : 

```
Erreur d'analyse XML : mal formé
Emplacement : http://searx.cortecs.org/opensearch.xml
Numéro de ligne 1, Colonne 1 :￿
```

I tried to download with chromium and the file seems corrupted : 

```
ĀP�N�w>΍k{B������+��]��F��f���x�Hb����S�rS=�S��6maM}��$�L���ȋ?�7���,��xC�cI��m��a/�����v2d�L�#��Cl<1@���5u�6/3�th�(�j1(ߺdQkB�"7�\�
��`/�]��z~�^ x��˔HO^���]
                             �p
```

I tried to download the file with wget and the file is perfectly normal :

```
<?xml version="1.0" encoding="utf-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>searx</ShortName>
  <Description>Search searx</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <LongName>searx metasearch</LongName>

    <Url type="text/html" method="post" template="http://searx.myurl/">
        <Param name="q" value="{searchTerms}" />
    </Url>


</OpenSearchDescription>
```

What's wrong ? Something with browser access, cookies, uwsgi ?

**Comment by asciimoo** [comment]
interesting, could you check it again on the fixed version?

**Comment by julpec** [comment]
Still the same problem !

But I have test another param : yesterday, I have installed searx on another device and I didn't had the idea to test on it… it's working !

So, the problem come from the other one which is a ARM-base device (cubox-i4pro).

I don't have the knowledge to test from which package the problem is coming.

**Comment by asciimoo** [comment]
I have no idea and i can't reproduce it (tried on an ARM based cubieboard).

**Comment by julpec** [comment]
Ok, nevermind… hopefully, I have to change this device so I think I will not have this problem in the next install.
By the way, I was a Jessie version of Debian…

**Comment by brihx** [comment]
I have the same problem with my server : 
https://searx.brihx.fr/opensearch.xml

It's an Ubuntu 14.04.3 LTS

**Comment by dalf** [comment]
I think that apache (or nginx) give a gzip version of the file, but firefox for some reason doesn't decompress it. If I remember correctly @pointhi already had a similar issue.

Perhaps try something like that (for apache) :

```
<FilesMatch opensearch\.xml$>
SetEnv no-gzip 1
</FilesMatch>
```

It's a workaround, but if it can help.

**Comment by brihx** [comment]
Thanks dalf your workaround solve my issue !
