### ISSUE TITLE
Feature suggestion: Add Wordnik

### ISSUE THREAD

**Issue by geckolinux** [searx/searx#1844]
Hi there, would it be possible to add Wordnik? This is where DuckDuckGo gets its definitions from, and they're much better than Wikipedia/Wiktionary. It would be nice to have this for instant answers on the sidebar, with top priority above other services that offer definitions, such as Wikipedia and Wolfram|Alpha. Thanks!

**Comment by plague-doctor** [comment]
This! I am missing those handy definitions so much. 
Just type `define: feature` and get back:
```
 feature
    n.    Any of the distinct parts of the face, as the eyes, nose, or mouth.
    n.    The overall appearance of the face or its parts.
```
Preferably in the little frame on the right had side.

**Comment by unixfox** [comment]
@plague-doctor Feel free to contribute to the Searx code if you want a faster implementation. Currently, unfortunately we don't have the amount of developers needed for working on non-important features.
