### ISSUE TITLE
[NOT A BUG] Searx highest ranked in large comparison test of search engines

### ISSUE THREAD

**Issue by geckolinux** [searx/searx#1847]
Hey, I just wanted to congratulate everyone who has helped make Searx. I finally finished an extensive test of all the current options in search engines, both major ones and obscure ones, and Searx beats them all. :-) Here's the (long) article:
https://libretechtips.gitlab.io/detailed-tests-of-search-engines-google-startpage-bing-duckduckgo-metager-ecosia-swisscows-searx-qwant-yandex-and-mojeek/

**Comment by Pofilo** [comment]
Hello !
You can even use this link https://searx.space/ for the list of instances.
This list is maintened here: https://github.com/dalf/searx-instances
Have a nice day :)

**Comment by geckolinux** [comment]
Awesome, thank you! Just changed the link.

**Comment by return42** [comment]
Want to leave my thanks for sharing your brilliant work!

Did you know that [startpage got sold](https://darmarit.org/searx/?q=startpage%20got%20sold&categories=general&language=en-US)?

**Comment by geckolinux** [comment]
> Want to leave my thanks for sharing your brilliant work!

Thanks a lot for saying "thanks"! Glad you liked it.

> Did you know that startpage got sold?

Yes, doesn't exactly inspire confidence.
