### ISSUE TITLE
Settings.yml on docker image

### ISSUE THREAD

**Issue by Happyfeet01** [searx/searx#1848]
Hello,

I use the searx Docker Image. I mount the settings.yml with read only into the image. Would this prevent from overwriting at image Update? 
https://suche.dasnetzundich.de

**Comment by dalf** [comment]
Starts the docker searx/searx image without the ```-f``` argument: https://github.com/asciimoo/searx/blob/2485d41bdd59fb820241241769ea9ad833ea470c/dockerfiles/docker-entrypoint.sh#L29-L30

If you use searx/searx-docker, comment this line:
https://github.com/searx/searx-docker/blob/3878f0d51ab7dff3af4f89b7c5ad82a5fd7e0406/.env#L10

**Comment by Happyfeet01** [comment]
Okay thanks. I update with watchtower, works this also with these options? 
Maybe this the the better way?

```
volumes:
      - ./searx:/etc/searx:ro 
```

**Comment by dalf** [comment]
Without ```-f```, searx won't touch your ```settings.yml```, and if there is a new version, searx will create a ```settings.yml.new``` file.

But I guess ``` - ./searx:/etc/searx:ro``` will works. In this case, for time to time, check searx git repository to get settings.yml updates.
