### ISSUE TITLE
Slight confusion when adding searx to Firefox

### ISSUE THREAD

**Issue by beermad** [searx/searx#1849]
Having set up a local instance of searx, I was attempting to add it to Firefox as the default search engine.
Although pointing my browser at localhost:8888 worked fine, after adding it to Firefox, the browser insisted on trying to use the default port 80, so went to localhost.
After much digging about, I fell upon the solution. In settings.yml, I had defined:

`base_url : http://antwerp # Set custom base_url. Possible values: False or "https://your.custom.host/location/"` (where antwerp is my local hostname).
Under the assumption that the port defined above this line was "taken as read". However, in order for Firefox to use the correct port, the line needs to be:
`base_url : http://antwerp:8888 # Set custom base_url. Possible values: False or "https://your.custom.host/location/"`

My suggestion: either the generated xml file should be created automatically with the port appended, or the comments in the default settings.yml file should make it clear that it needs to be added, to save other users having this problem.

**Comment by geckolinux** [comment]
I have also noticed that many of the SearX public instances appear to not have that configured correctly, because the Firefox **...** menu in the address bar offers the Add New Search Engine option for some instances but not others.

**Comment by beermad** [comment]
Another "feature" I'd forgotten about. Before setting the port in base_url, saving settings in the browser _also_ then takes a user to the default port. Another reason to configure this correctly.

**Comment by colinner** [comment]
I used a public instance and the "Install" link in the Searx /about page does nothing for me. The solution I found at StackOverflow for manually adding search engines is to use a site like http://ready.to/search/en which allows to set URL suffix and prefix manually that the browser will use to send your query. You could probably specify any port you like using this.

**Comment by return42** [comment]
Searx supports OpenSearch, read my comment at https://github.com/asciimoo/searx/issues/1616#issuecomment-627280695

Is there anything more we can do for this issue?

**Comment by colinner** [comment]
Ah, I see it now, it seems the Firefox UI has changed since those screenshots were made.

I would suggest improving the procedure on the "/about" page under the heading "How to set as the default search engine?" for adding the search engine to Firefox. Maybe just explain that you click on the "..." in address bar. Currently, the "Install" link does nothing for me.

**Comment by return42** [comment]
> I would suggest improving the procedure on the "/about"

PR is already waiting for a review: https://github.com/asciimoo/searx/pull/1950

A [preview](https://darmarit.org/searx/about) is available from my [searx-next branch](https://github.com/return42/searx/tree/searx-next) including #1950.
