### ISSUE TITLE
Searx instance: Engines without self-check

### ISSUE THREAD

**Issue by gloschtla** [searx/searx#1850]
on your website searx.space I click on "engines", and I see only one line with green check marks in the line of a.searx.space 

All the other instances say: 🟡 - No self-checking, the engine has returned results since the searx instance has started. Maybe it doesn't work anymore.

**Comment by unixfox** [comment]
It's better to open an issue here: https://github.com/dalf/searx-stats2/issues

**Comment by dalf** [comment]
See https://github.com/dalf/searx-stats2/issues/21

**Comment by gloschtla** [comment]
Tank you, @dalf
