### ISSUE TITLE
Show Instances that have a Morty or other Proxy

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [searx/searx#1852]
Unfortunately we're up against CloudFlare™️ and that is a problem, especially if we use Tor; so a proxy is needed.  Some of the instances offer i.e. Morty, but many do not, and instances have been disappearing lately, or at least their Tor Hidden Services.  So it would be nice to have a list of instances that offer a proxy.

Thanks.  🍻

**Comment by unixfox** [comment]
Is this feature request related to searx.space? If so then please open an issue on the correct repository: https://github.com/dalf/searx-stats2

**Comment by MilkManzJourDaddy** [comment]
Closing to move to: dalf/searx-stats2#22

**Comment by return42** [comment]
From my POV all instances should have filtron and morty installed.  Have you seen my  #1803 ?

The [aim](https://github.com/asciimoo/searx/pull/1803#issuecomment-585085507) of #1803 is to replace the old instructions description by a set of scripts that cover all aspects of a searx infrastructure (and with lxc on all platforms we support).

Its a long task, hopefully finished in the next month or two ...
