### ISSUE TITLE
python webapp.py not working

### ISSUE THREAD

**Issue by sanikava** [searx/searx#1854]
### I have got this error

Traceback (most recent call last):
  File "webapp.py", line 50, in <module>
    from werkzeug.middleware.proxy_fix import ProxyFix
ImportError: No module named middleware.proxy_fix

**HOW I CAN FIX IT**

**Comment by return42** [comment]
Seems your Flask (werkzeug) installation is damaged .. try to reinstall with pip, may it helps.

How did you installed serax?
