### ISSUE TITLE
No results after setting 1-year filter

### ISSUE THREAD

**Issue by gloschtla** [searx/searx#1857]
I would like to get search results in any language for a specific German term, which appeared in past 12 months. But as soon as I set the time-filter it returns no results. Example: 
https://search.fossdaily.xyz?q=rundfunk&categories=general&time_range=year

**Comment by return42** [comment]
Only a few engines support time-range searches / take a look at "preferences".  If I test the same search term on my instance: [rundfunk](http://darmarit.cloud/searx/?q=rundfunk&categories=general&time_range=year&language=de) .. I got only hits from google.  Google is disabled by default at your instance .. enable google in the preferences and search again .. does it work?

**Comment by return42** [comment]
google has been fixed / time range works: https://darmarit.org/searx/?q=rundfunk&categories=general&time_range=year&language=de
