### ISSUE TITLE
"search error" - TypeError: 'dict_keys' object does not support indexing

### ISSUE THREAD

**Issue by jonaharagon** [searx/searx#1858]
I just installed Searx and I'm getting an " Error! search error" message on every query. uwsgi is logging the following:

```
ERROR:searx.webapp:search error
Traceback (most recent call last):
  File "/usr/local/searx/searx/webapp.py", line 536, in index
    result_container = search.search()
  File "/usr/local/searx/searx/search.py", line 545, in search
    results = self.result_container.get_ordered_results()
  File "/usr/local/searx/searx/results.py", line 336, in get_ordered_results
    self.order_results()
  File "/usr/local/searx/searx/results.py", line 293, in order_results
    res['category'] = engines[res['engine']].categories[0]
TypeError: 'dict_keys' object does not support indexing
```

This is a new installation using python3.6. Any thoughts?

**Comment by return42** [comment]
Strange, how did you installed searx?

**Comment by jonaharagon** [comment]
I followed [these instructions](https://asciimoo.github.io/searx/admin/installation.html#basic-installation), but instead of:

```
(searx)$ virtualenv searx-ve
(searx)$ . ./searx-ve/bin/activate
(searx)$ ./manage.sh update_packages
```

I ran this, [as instructed here](https://asciimoo.github.io/searx/blog/python3.html):

```
virtualenv -p python3 venv3
. ./venv3/bin/activate
pip3 install -r requirements.txt
```

And then I added `plugin = python36` to `/etc/uwsgi/apps-enabled/searx.ini`. This is on Ubuntu 18.04.

**Comment by jonaharagon** [comment]
Hmm I think I've figured it out. When I had engines using `searx_engine` enabled it wouldn't work. I'm just disabling them, that engine has never worked for me anyways for some reason :(

**Comment by return42** [comment]
Don't do the latter one ..it is an old blog article you have found. Follow the installation instruction!

For a quick test you can run a developer [instance:](https://asciimoo.github.io/searx/dev/makefile.html#make-run)

     make run
