### ISSUE TITLE
Have 1337x in "Files" as well as in "Videos"

### ISSUE THREAD

**Issue by tbergeron** [searx/searx#1864]
Since 1337s is a tracker not only for videos I'd suggest adding it to the "Files" tab as well. Because at the moment I use the "Videos" tab to search through 1337x which is a little bit counter-productive.

I never contributed to this project but I'll do my best to provide a pull request concerning this issue. Just wanted to put it out there to see if anyone else's want that.

**Comment by tbergeron** [comment]
Ah so it seems to be a minor tweak that needs to be made to https://github.com/asciimoo/searx/blob/09f4e2cd3138f7f19aa52c974729c791e48c20b2/searx/settings.yml so I guess people who hosts existing mirrors would have to alter their own configs for everybody to get that change right?

**Comment by return42** [comment]
Correct, you can add the engine to the [categories](https://asciimoo.github.io/searx/admin/settings.html?highlight=category#engine-settings)

Normally the [settings.yml](https://github.com/asciimoo/searx/blob/master/searx/settings.yml) is balanced to give best results with best timeouts .. _to provide best UX_ .. whatever this means ..  if you think its improvable send your PR, but keep in mind that it should be a good solution for _all_.
