### ISSUE TITLE
Is Twitter engine still working as expected? (Never get any results)

### ISSUE THREAD

**Issue by tbergeron** [searx/searx#1867]
I can't seem to fetch any results at all using Twitter. I tried searching for a few keywords that should get results no matter what but it seems that nothing gets found yet no errors get shown either.

**EDIT:** Just clicked on my links and saw a request exception coming from Twitter. Refreshed and it went away. 🤔 

i.e. search syntax 😉 for obvious queries that should fetch results IMO
- [!tw joe rogan](http://darmarit.cloud/searx/?q=%21tw%20joe%20rogan&categories=none&language=en)
- [!tw twitter](http://darmarit.cloud/searx/?q=%21tw%20twitter&categories=none&language=en)
- [!tw jack](http://darmarit.cloud/searx/?q=%21tw%20jack&categories=none&language=en)

Am I doing something wrong? I tried on multiple instances and same results.

~~Bonus unrelated question: what kind of specs should I use to build my own instance? CPU/Memory wise. Any documentation or guidelines of good practice concerning deployment?~~

**EDIT:** Just read the ABOUT document and found everything I needed.

Once again, thanks for your patience with newcomers :D I appreciate it much!

**Comment by tbergeron** [comment]
Workaround: Using Qwant social is a really good alternative at finding tweets! 😄

**Comment by tbergeron** [comment]
I now get results from Twitter when using the social tab directly but not when using `!tw` though. But the engine seems to work!

**Comment by unixfox** [comment]
Twitter engine got removed in https://github.com/searx/searx/pull/2372
