### ISSUE TITLE
Openstreetmap: problems with umlauts

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#1869]
- search for "Köln" in maps
Expected: openstreetmap and photon results are shown
Actual behavior: photon is shown and Error: openstreetmap (unexpected crash: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128))

- search for "Hamburg" in maps
-> openstreetmap and photon results are shown

**Comment by cy8aer** [comment]
python3.7, Version 6a3ef5561ba48e287f0b9c03a0b6d2f13b703077

**Comment by return42** [comment]
Hm strange, I can't reproduce (even if I select english)  http://darmarit.cloud/searx/?q=K%C3%B6ln&categories=map&language=en

Does anyone else observe these encoding errors?

**Comment by return42** [comment]
May it has to do with the location of your instance? .. can you give us a link at hand / thanks?

**Comment by cy8aer** [comment]
```
search:
    language : "en-US"
```
tried out `de-DE` as well, I use "Deutsch - de" as language setting on my web site. Changing this does not matter either.

https://searx.g3la.de (should put it into the global list as well...)

**Comment by return42** [comment]
Seems there is something wrong in your instance .. the same query in my instance work

  https://darmarit.cloud/searx/?q=K%C3%B6ln&categories=map&language=de-DE

In my instance I use the default settings.yml / Can you please screw back your changes in settings.yml file and repeat the test?

**Comment by cy8aer** [comment]
hm, same with vanilla settings. I just did a `manage.sh update_packages` in the environment to be sure that I am on the actual module set. I also checked up with a vanilla browser setting without cookie. I am really sure this worked some versions ago but cannot tell when the new behavior occured :-(

**Comment by return42** [comment]
Can you try a local test with a developer instance

     make run 

see https://asciimoo.github.io/searx/dev/makefile.html#make-run

**Comment by cy8aer** [comment]
Please stand by. I need a development machine at home...

**Comment by return42** [comment]
Its very simple to setup, see https://github.com/asciimoo/searx/issues/1838#issuecomment-590998937

update: or see here https://asciimoo.github.io/searx/dev/makefile.html#make-run

**Comment by cy8aer** [comment]
Yep, but I need to clone the whole stuff from the provider's server to a local machine and run it there - but cannot do it at work ;-)

**Comment by cy8aer** [comment]
local instance with `make run` works.

**Comment by return42** [comment]
OK, thanks for verifying this .. now we have to check, how searx is integrated in the HTTP server on the provider side.  May be, there went something wrong and the searx process runs in a python2 environment? How is it integrated into the HTTP Server?

**Comment by cy8aer** [comment]
This is a dedicated root server running Debian Buster. Own user `searx`. I explicitely rebuild the py3 environment (with no positive effect). uwsgi config:

```
[uwsgi]
uid = searx
gid = searx

# disable logging for privacy
disable-logging = true

workers = 4
chmod-socket = 666

single-interpreter = true
master = true
plugin = python37

module = searx.webapp
virtualenv = /usr/share/searx/searx-ve.py3
pythonpath = /usr/share/searx/
chdir = /usr/share/searx/
callable = app

lazy-apps = true
enable-threads = true
```
Frontend is an apache with proxy_uwsgi configured:

```
KeepAlive ON

MaxKeepAliveRequests 100

KeepAliveTimeout 300

<Location />
        Options FollowSymLinks Indexes
</Location>

ProxyPass / unix:/run/uwsgi/app/searx/socket|uwsgi://searx/
ProxyPassReverse / unix:/run/uwsgi/app/searx/socket|uwsgi://searx/
```
Yes, I swapped from py2 to py3 some weeks ago. And I just tried it with my python2 environment (uwsgi config nearly the same but - guess - plugin python2 and pointing to an py2 venv searx-ve.py2 ;-) ) - same problem.

**Comment by return42** [comment]
Looks all not as bad to me .. except some things that I would avoid  ..

the uwsgi python plugin:

    plugin = python37

Is it really a python37 plugin? .. never seen 37 suffix before.

What I know is that some distros (archlinux) use name `python` for the py3-plugin and `python2` for the py2-plugin. Ubuntu, debian on the opposite use `python` for py2-plugin and `python3` for the py3-plugin. I have never seen a `python37` plugin before .. where does it comes from / which distro is it? .. Can you try to change to `python3` and/or `python` .. may python2 is a fallback value for unknown `python*` plugin names .. I don't know, I can only guess .

Another question, what is 

    callable = app

did you have something special here? Normal y the app is something like 

    module = searx.webapp
    pythonpath = /usr/share/searx/
    chdir = /usr/share/searx/

BTW it is a little inconvenient having the venv below a pythonpath and the dotted name is also not as good.

Here is, what I do .. https://return42.github.io/searx/admin/installation.html#uwsgi

**Comment by cy8aer** [comment]
hm, crazy, crazy. Welcome to the world of systemd: I now took your advices and corrected the uwsgi configuration including moving the venv out of the pythonpath and cleaned all old stuff. Then I found out that systemd made the old "I say that I kill but I don't" game. An old job was running. After cleaning this up - I now have: #968 
But this line in log:
```
  File "/usr/lib/python3.7/hmac.py", line 49, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
```

does not look like the venv is used but vanilla python though virtualenv is set. Need to investigate.

**Comment by return42** [comment]
> hm, crazy, crazy.

welcome in the club :) 

> Need to investigate.

come back if you think I can help .. if you found the solution, please leave a note here for others coming around  .. good luck :)

**Comment by cy8aer** [comment]
... vanilla reinstall, hmac error. This needs a bit more time... stand by

**Comment by cy8aer** [comment]
Ok, reinstall fixed this problem. Now: Setting of morty cache in python3 makes another hmac error. 
Close this bug (but open another one soon)
