### ISSUE TITLE
Startpage parser breaks on Spanish date format

### ISSUE THREAD

**Issue by Nutomic** [searx/searx#1870]
To reproduce, follow these steps:

1. open searx.info (or another instance)

2. search for a spanish term, eg "madrid tiempo ahora"

This results in an error like the following:
```
Los motores no pueden obtener resultados: (english: engines cant obtain results)

startpage (unexpected crash: ('Unknown string format:', '22 Ene 2020'))
```

**Comment by bauruine** [comment]
Could you please try again on searx.info? I deployed a fix but I'm not sure if it worked and i can't reproduce it even if i set the search and interface language to Spanish.

**Comment by Nutomic** [comment]
I also can't reproduce it anymore, guess your fix worked. Thanks!
