### ISSUE TITLE
[Infobox] Missing symbols in big notation of algorithm

### ISSUE THREAD

**Issue by etanot** [searx/searx#1873]
**Type**: Bug

### Description

Some symbols are missing in big notation of algorithm (time and space complexity).

![A* cleaned](https://user-images.githubusercontent.com/28824347/75579200-31ab7500-5a5d-11ea-9c7b-ad80fc7596b6.png)
Fig1: Search results for "A* search"

![A*-wiki cleaned](https://user-images.githubusercontent.com/28824347/75579202-32440b80-5a5d-11ea-97e7-919cc6643648.png)
Fig2: Wikipedia page of "A* search Algorithm"

![dfs](https://user-images.githubusercontent.com/28824347/75579204-33753880-5a5d-11ea-8bc7-f3555fbae1a7.png)
Fig3: Search results for "DFS"

**Edited**

### Steps to reproduce
- Search name of any algorithm with `!ddd` as prefix, for which info-box likely to contain big notation.

Examples: [A* search](https://searx.be/?q=%21ddd%20A%2A%20search&categories=none&language=en-US), [Depth first search](https://searx.be/?q=%21ddd%20depth%20first%20search&categories=none&language=en-US)

**Comment by kvch** [comment]
I cannot reproduce this issue. I have also tried with bubble sort and binary search, but no "luck". @finn0 Is this still a problem? Could you provide alternative terms so I can find the issue in the code?

**Comment by etanot** [comment]
@kvch, sorry for not reporting bug properly, I've edited steps to reproduce section.

I've digged deeper the issue, and found that, there is an issue with parsing search results of `DuckDuckGo Definitions` engine, may be similar to #1695.

> I have also tried with bubble sort and binary search, but no "luck".

Yes, you're right, I also won't be able to reproduce this behavior with [bubble sort](https://search.disroot.org?q=%21ddd%20bubble%20sort&categories=none&language=en) and [binary search](https://search.disroot.org?q=%21ddd%20binary%20search&categories=none&language=en). But I can reproduce this issue on most of graph related algorithms, like [breadth first search](https://search.disroot.org?q=%21ddd%20breadth%20first%20search&categories=none&language=en), [depth first search](https://search.disroot.org?q=%21ddd%20depth%20first%20search&categories=none&language=en), [A* search](https://search.disroot.org?q=%21ddd%20A%2A%20search&categories=none&language=en) algorithm etc. See below JSON output of `!ddd bubble sort` and `!ddd depth first search`, in latter case time and space complexity aren't represented, correctly.

```
$ curl "https://search.disroot.org?q=%21ddd%20bubble%20sort&categories=none&language=en&format=json"
{"number_of_results": 0, "corrections": [], "query": "bubble sort", "infoboxes": [{"infobox": "Bubble sort", "content": "Bubble sort, sometimes referred to as sinking sort, is a simple sorting algorithm that repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order. The pass through the list is repeated until the list is sorted. The algorithm, which is a comparison sort, is named for the way smaller or larger elements \"bubble\" to the top of the list. This simple algorithm performs poorly in real world use and is used primarily as an educational tool. More efficient algorithms such as timsort, or merge sort are used by the sorting libraries built into popular programming languages such as Python and Java.", "img_src": "https://duckduckgo.com/i/72c9797f.png", "urls": [{"url": "https://en.wikipedia.org/wiki/Bubble_sort", "title": "Wikipedia"}], "relatedTopics": [], "attributes": [{"value": "Sorting algorithm", "label": "Class"}, {"value": "Array", "label": "Data structure"}, {"value": "O(n^2) comparisons, O(n^2) swaps", "label": "Worst-case performance"}, {"value": "O(n) comparisons, O(1) swaps", "label": "Best-case performance"}, {"value": "O(n^2) comparisons, O(n^2) swaps", "label": "Average performance"}, {"value": "O(n) total, O(1) auxiliary", "label": "Worst-case space complexity"}, {"value": {"numeric-id": 181593, "id": "Q181593", "entity-type": "item"}, "label": "Instance of"}], "engine": "ddg definitions", "id": "https://en.wikipedia.org/wiki/Bubble_sort", "entity": "algorithm"}], "suggestions": ["Sorting algorithms", "Comparison sorts", "Stable sorts"], "results": [], "answers": [], "unresponsive_engines": []}
```
```
$ curl "https://search.disroot.org?q=%21ddd%20depth%20first%20search&categories=none&language=en&format=json"
{"number_of_results": 0, "corrections": [], "query": "depth first search", "infoboxes": [{"infobox": "Depth-first search", "content": "Depth-first search is an algorithm for traversing or searching tree or graph data structures. The algorithm starts at the root node and explores as far as possible along each branch before backtracking. A version of depth-first search was investigated in the 19th century by French mathematician Charles Pierre Tr\u00e9maux as a strategy for solving mazes.", "img_src": "https://duckduckgo.com/i/eb667d3c.png", "urls": [{"url": "https://en.wikipedia.org/wiki/Depth-first_search", "title": "Wikipedia"}], "relatedTopics": [], "attributes": [{"value": "Search algorithm", "label": "Class"}, {"value": "Graph", "label": "Data structure"}, {"value": "O(", "label": "Worst-case performance"}, {"value": "O(", "label": "Worst-case space complexity"}, {"value": {"numeric-id": 4443425, "id": "Q4443425", "entity-type": "item"}, "label": "Instance of"}], "engine": "ddg definitions", "id": "https://en.wikipedia.org/wiki/Depth-first_search", "entity": "algorithm"}], "suggestions": ["Tree traversal", "Iterative deepening depth-first search", "Search algorithms", "Breadth-first search", "Search games"], "results": [], "answers": [], "unresponsive_engines": []}
```

Edit:
But it's a different issue with, [Dijkstra's](https://search.disroot.org?q=%21ddd%20dijkstra%27s%20algorithm&categories=none&language=en), [Bellman-ford](https://search.disroot.org?q=%21ddd%20Bellman%20ford%20algorithm&categories=none&language=en), [Floyd-Warshall](https://search.disroot.org?q=%21ddd%20floyd%20warshall%20algorithm&categories=none&language=en) algorithm.

![Dijkstra algorithm](https://user-images.githubusercontent.com/28824347/83838272-3a5cb880-a6e8-11ea-9e60-2184da495d5f.png)

**Comment by etanot** [comment]
May be this happened because of `|` character in notation. Most of graph algorithm's time and space complexity notation contain, |V| and |E| with them. See search result for [Iterative Deepening A*](https://search.disroot.org?q=%21ddd%20Iterative%20deepening%20A%2A&categories=none&language=en) algorithm.

**Comment by kvch** [comment]
Unfortunately, DuckDuckGo is returning incorrect results. Try searching for the algorithms you have mentioned. For example: [Dijkstra's algorithm](https://duckduckgo.com/?q=dijkstra%27s+algorithm&t=ht&ia=web&iai=r1-0&page=1&sexp=%7B%22v7exp%22%3A%22a%22%2C%22rgiexp%22%3A%22b%22%2C%22fexp%22%3A%22c%22%7D)

Their UI is also showing the broken result: 
![image](https://user-images.githubusercontent.com/3876218/84693158-5ca3d100-af47-11ea-9611-154bd393ef2a.png)

As there is nothing we can do about it, I am closing the issue. When they fix the result in DDG, it will work in searx automatically.

Feel free to reopen this issue, if you have to.
