### ISSUE TITLE
ImportError: No module named middleware.proxy_fix

### ISSUE THREAD

**Issue by virse** [searx/searx#1874]
Hey there,

after upgrading my instance via git today, I am not able to restart UWGSI/Searx.
The Apache2 log shows me:

> Sat Feb 29 20:02:40 2020 - *** Starting uWSGI 2.0.15-debian (64bit) on [Sat Feb 29 20:02:39 2020] ***
> Sat Feb 29 20:02:40 2020 - compiled with version: 7.3.0 on 28 September 2018 15:41:15
> Sat Feb 29 20:02:40 2020 - os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
> Sat Feb 29 20:02:40 2020 - nodename: mail.domain.de
> Sat Feb 29 20:02:40 2020 - machine: x86_64
> Sat Feb 29 20:02:40 2020 - clock source: unix
> Sat Feb 29 20:02:40 2020 - pcre jit disabled
> Sat Feb 29 20:02:40 2020 - detected number of CPU cores: 4
> Sat Feb 29 20:02:40 2020 - current working directory: /
> Sat Feb 29 20:02:40 2020 - writing pidfile to /run/uwsgi/app/searx/pid
> Sat Feb 29 20:02:40 2020 - detected binary path: /usr/bin/uwsgi-core
> Sat Feb 29 20:02:40 2020 - dropping root privileges as early as possible
> Sat Feb 29 20:02:40 2020 - setgid() to 1001
> Sat Feb 29 20:02:40 2020 - setuid() to 1001
> Sat Feb 29 20:02:40 2020 - chdir() to /usr/local/searx/searx/
> Sat Feb 29 20:02:40 2020 - your processes number limit is 15529
> Sat Feb 29 20:02:40 2020 - your memory page size is 4096 bytes
> Sat Feb 29 20:02:40 2020 - detected max file descriptor number: 1024
> Sat Feb 29 20:02:40 2020 - lock engine: pthread robust mutexes
> Sat Feb 29 20:02:40 2020 - thunder lock: disabled (you can enable it with --thunder-lock)
> Sat Feb 29 20:02:40 2020 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/searx/socket fd 3
> Sat Feb 29 20:02:40 2020 - uwsgi socket 1 bound to TCP address 127.0.0.1:8080 fd 5
> Sat Feb 29 20:02:40 2020 - dropping root privileges after socket binding
> Sat Feb 29 20:02:40 2020 - Python version: 2.7.17 (default, Nov  7 2019, 10:07:09)  [GCC 7.4.0]
> Sat Feb 29 20:02:40 2020 - Set PythonHome to /usr/local/searx/searx-ve/
> Sat Feb 29 20:02:40 2020 - Python main interpreter initialized at 0x55922f464320
> Sat Feb 29 20:02:40 2020 - dropping root privileges after plugin initialization
> Sat Feb 29 20:02:40 2020 - python threads support enabled
> Sat Feb 29 20:02:40 2020 - your server socket listen backlog is limited to 100 connections
> Sat Feb 29 20:02:40 2020 - your mercy for graceful operations on workers is 60 seconds
> Sat Feb 29 20:02:40 2020 - mapped 218304 bytes (213 KB) for 2 cores
> Sat Feb 29 20:02:40 2020 - *** Operational MODE: preforking ***
> Sat Feb 29 20:02:40 2020 - added /usr/local/searx/ to pythonpath.
> Sat Feb 29 20:02:40 2020 - dropping root privileges after application loading
> Sat Feb 29 20:02:40 2020 - spawned uWSGI master process (pid: 7354)
> Sat Feb 29 20:02:40 2020 - spawned uWSGI worker 1 (pid: 7356, cores: 1)
> Sat Feb 29 20:02:40 2020 - spawned uWSGI worker 2 (pid: 7357, cores: 1)
> Traceback (most recent call last):
>   File "/usr/local/searx/searx/webapp.py", line 51, in <module>
>     from werkzeug.middleware.proxy_fix import ProxyFix
> ImportError: No module named middleware.proxy_fix
> Sat Feb 29 20:02:43 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
> Sat Feb 29 20:02:43 2020 - *** no app loaded. going in full dynamic mode ***
> Sat Feb 29 20:02:43 2020 - --- no python application found, check your startup logs for errors ---
> Traceback (most recent call last):
>   File "/usr/local/searx/searx/webapp.py", line 51, in <module>
>     from werkzeug.middleware.proxy_fix import ProxyFix
> ImportError: No module named middleware.proxy_fix
> Sat Feb 29 20:02:43 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
> Sat Feb 29 20:02:43 2020 - *** no app loaded. going in full dynamic mode ***

I already tried to reinstall Flask (werkzeug) as mentioned in this post: #python webapp.py not working #1854 

But still the same error. #New release of Werkzeug 1.0.0 breaks searx startup #1830 says that the problem should be fixed with a new release of werkzeug. But as mentioned, this is a git-upgrade from today.

Any help is appreciated on that issue.

Thx a lot, mike

**Comment by return42** [comment]
Can you please try to rebuild your python environment .. and give us a feedback / thanks!

hint: #1830  changed [ requirements.txt](https://github.com/asciimoo/searx/pull/1831/files#diff-b4ef698db8ca845e5845c4618278f29aR3)

**Comment by joshp23** [comment]
Same error. `$ git checkout v0.16.0` got me back working.

**Comment by return42** [comment]
@joshp23 can you please retry to build the python environment, I asked for / thanks.

update: checking out v0.16 is not an update!

**Comment by return42** [comment]
@joshp23 you gave a thumbs-up .. what does it mean? .. did you rebuild the virtualenv and it works?

I really need a feedback .. to fix documentation or whatever.

**Comment by joshp23** [comment]
apologies, only confirming that I will do that suggested fix.

**Comment by virse** [comment]
Hey there,

this is what I did:

> root@mail:/usr/local/searx# cd /usr/local/searx
> root@mail:/usr/local/searx# sudo -H -u searx -i
> $ . ./searx-ve/bin/activate
> (searx-ve) $ pip install -r requirements.txt
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Requirement already satisfied: certifi==2019.3.9 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2019.3.9)
> Requirement already satisfied: babel==2.7.0 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (2.7.0)
> Requirement already satisfied: flask-babel==1.0.0 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.0.0)
> Requirement already satisfied: flask==1.0.2 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (1.0.2)
> Requirement already satisfied: idna==2.8 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (2.8)
> Requirement already satisfied: jinja2==2.10.1 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (2.10.1)
> Requirement already satisfied: lxml==4.3.3 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (4.3.3)
> Requirement already satisfied: pygments==2.1.3 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (2.1.3)
> Requirement already satisfied: pyopenssl==19.0.0 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 9)) (19.0.0)
> Requirement already satisfied: python-dateutil==2.8.0 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 10)) (2.8.0)
> Requirement already satisfied: pyyaml==5.1 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 11)) (5.1)
> Requirement already satisfied: requests[socks]==2.22.0 in ./searx-ve/lib/python2.7/site-packages (from -r requirements.txt (line 12)) (2.22.0)
> Requirement already satisfied: pytz>=2015.7 in ./searx-ve/lib/python2.7/site-packages (from babel==2.7.0->-r requirements.txt (line 2)) (2018.9)
> Requirement already satisfied: itsdangerous>=0.24 in ./searx-ve/lib/python2.7/site-packages (from flask==1.0.2->-r requirements.txt (line 4)) (1.1.0)
> Requirement already satisfied: Werkzeug>=0.14 in ./searx-ve/lib/python2.7/site-packages (from flask==1.0.2->-r requirements.txt (line 4)) (0.14.1)
> Requirement already satisfied: click>=5.1 in ./searx-ve/lib/python2.7/site-packages (from flask==1.0.2->-r requirements.txt (line 4)) (7.0)
> Requirement already satisfied: MarkupSafe>=0.23 in ./searx-ve/lib/python2.7/site-packages (from jinja2==2.10.1->-r requirements.txt (line 6)) (1.1.0)
> Requirement already satisfied: six>=1.5.2 in ./searx-ve/lib/python2.7/site-packages (from pyopenssl==19.0.0->-r requirements.txt (line 9)) (1.12.0)
> Requirement already satisfied: cryptography>=2.3 in ./searx-ve/lib/python2.7/site-packages (from pyopenssl==19.0.0->-r requirements.txt (line 9)) (2.5)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./searx-ve/lib/python2.7/site-packages (from requests[socks]==2.22.0->-r requirements.txt (line 12)) (3.0.4)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./searx-ve/lib/python2.7/site-packages (from requests[socks]==2.22.0->-r requirements.txt (line 12)) (1.23)
> Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in ./searx-ve/lib/python2.7/site-packages (from requests[socks]==2.22.0->-r requirements.txt (line 12)) (1.6.8)
> Requirement already satisfied: ipaddress; python_version < "3" in ./searx-ve/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl==19.0.0->-r requirements.txt (line 9)) (1.0.22)
> Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./searx-ve/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl==19.0.0->-r requirements.txt (line 9)) (1.12.1)
> Requirement already satisfied: asn1crypto>=0.21.0 in ./searx-ve/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl==19.0.0->-r requirements.txt (line 9)) (0.24.0)
> Requirement already satisfied: enum34; python_version < "3" in ./searx-ve/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl==19.0.0->-r requirements.txt (line 9)) (1.1.6)
> Requirement already satisfied: pycparser in ./searx-ve/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyopenssl==19.0.0->-r requirements.txt (line 9)) (2.19)
> (searx-ve) $ pull origin master
> (searx-ve) $ git pull origin master
> Von https://github.com/asciimoo/searx
>  * branch              master     -> FETCH_HEAD
> Bereits aktuell.
> (searx-ve) $ ./manage.sh update_packages
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Requirement already up-to-date: pip in ./searx-ve/lib/python2.7/site-packages (20.0.2)
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Requirement already up-to-date: setuptools in ./searx-ve/lib/python2.7/site-packages (44.0.0)
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> Requirement already up-to-date: certifi==2019.3.9 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 1)) (2019.3.9)
> Requirement already up-to-date: babel==2.7.0 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 2)) (2.7.0)
> Requirement already up-to-date: flask-babel==1.0.0 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 3)) (1.0.0)
> Requirement already up-to-date: flask==1.0.2 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 4)) (1.0.2)
> Requirement already up-to-date: idna==2.8 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 5)) (2.8)
> Requirement already up-to-date: jinja2==2.10.1 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 6)) (2.10.1)
> Requirement already up-to-date: lxml==4.3.3 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 7)) (4.3.3)
> Requirement already up-to-date: pygments==2.1.3 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 8)) (2.1.3)
> Requirement already up-to-date: pyopenssl==19.0.0 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 9)) (19.0.0)
> Requirement already up-to-date: python-dateutil==2.8.0 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 10)) (2.8.0)
> Requirement already up-to-date: pyyaml==5.1 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 11)) (5.1)
> Requirement already up-to-date: requests[socks]==2.22.0 in ./searx-ve/lib/python2.7/site-packages (from -r /usr/local/searx/requirements.txt (line 12)) (2.22.0)
> Requirement already satisfied, skipping upgrade: pytz>=2015.7 in ./searx-ve/lib/python2.7/site-packages (from babel==2.7.0->-r /usr/local/searx/requirements.txt (line 2)) (2018.9)
> Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in ./searx-ve/lib/python2.7/site-packages (from flask==1.0.2->-r /usr/local/searx/requirements.txt (line 4)) (1.1.0)
> Requirement already satisfied, skipping upgrade: Werkzeug>=0.14 in ./searx-ve/lib/python2.7/site-packages (from flask==1.0.2->-r /usr/local/searx/requirements.txt (line 4)) (0.14.1)
> Requirement already satisfied, skipping upgrade: click>=5.1 in ./searx-ve/lib/python2.7/site-packages (from flask==1.0.2->-r /usr/local/searx/requirements.txt (line 4)) (7.0)
> Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in ./searx-ve/lib/python2.7/site-packages (from jinja2==2.10.1->-r /usr/local/searx/requirements.txt (line 6)) (1.1.0)
> Requirement already satisfied, skipping upgrade: six>=1.5.2 in ./searx-ve/lib/python2.7/site-packages (from pyopenssl==19.0.0->-r /usr/local/searx/requirements.txt (line 9)) (1.12.0)
> Requirement already satisfied, skipping upgrade: cryptography>=2.3 in ./searx-ve/lib/python2.7/site-packages (from pyopenssl==19.0.0->-r /usr/local/searx/requirements.txt (line 9)) (2.5)
> Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in ./searx-ve/lib/python2.7/site-packages (from requests[socks]==2.22.0->-r /usr/local/searx/requirements.txt (line 12)) (3.0.4)
> Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./searx-ve/lib/python2.7/site-packages (from requests[socks]==2.22.0->-r /usr/local/searx/requirements.txt (line 12)) (1.23)
> Requirement already satisfied, skipping upgrade: PySocks!=1.5.7,>=1.5.6; extra == "socks" in ./searx-ve/lib/python2.7/site-packages (from requests[socks]==2.22.0->-r /usr/local/searx/requirements.txt (line 12)) (1.6.8)
> Requirement already satisfied, skipping upgrade: ipaddress; python_version < "3" in ./searx-ve/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl==19.0.0->-r /usr/local/searx/requirements.txt (line 9)) (1.0.22)
> Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in ./searx-ve/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl==19.0.0->-r /usr/local/searx/requirements.txt (line 9)) (1.12.1)
> Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in ./searx-ve/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl==19.0.0->-r /usr/local/searx/requirements.txt (line 9)) (0.24.0)
> Requirement already satisfied, skipping upgrade: enum34; python_version < "3" in ./searx-ve/lib/python2.7/site-packages (from cryptography>=2.3->pyopenssl==19.0.0->-r /usr/local/searx/requirements.txt (line 9)) (1.1.6)
> Requirement already satisfied, skipping upgrade: pycparser in ./searx-ve/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyopenssl==19.0.0->-r /usr/local/searx/requirements.txt (line 9)) (2.19)
> (searx-ve) $ exit
> root@mail:/usr/local/searx# service uwsgi restart

But still the same error:

> Internal Server Error

UWSGI-Log:
> Sun Mar  1 13:10:08 2020 - SIGINT/SIGQUIT received...killing workers...
> Sun Mar  1 13:10:09 2020 - worker 1 buried after 1 seconds
> Sun Mar  1 13:10:09 2020 - worker 2 buried after 1 seconds
> Sun Mar  1 13:10:09 2020 - goodbye to uWSGI.
> Sun Mar  1 13:10:10 2020 - *** Starting uWSGI 2.0.15-debian (64bit) on [Sun Mar  1 13:10:09 2020] ***
> Sun Mar  1 13:10:10 2020 - compiled with version: 7.3.0 on 28 September 2018 15:41:15
> Sun Mar  1 13:10:10 2020 - os: Linux-4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
> Sun Mar  1 13:10:10 2020 - nodename: mail.domain.de
> Sun Mar  1 13:10:10 2020 - machine: x86_64
> Sun Mar  1 13:10:10 2020 - clock source: unix
> Sun Mar  1 13:10:10 2020 - pcre jit disabled
> Sun Mar  1 13:10:10 2020 - detected number of CPU cores: 4
> Sun Mar  1 13:10:10 2020 - current working directory: /
> Sun Mar  1 13:10:10 2020 - writing pidfile to /run/uwsgi/app/searx/pid
> Sun Mar  1 13:10:10 2020 - detected binary path: /usr/bin/uwsgi-core
> Sun Mar  1 13:10:10 2020 - dropping root privileges as early as possible
> Sun Mar  1 13:10:10 2020 - setgid() to 1001
> Sun Mar  1 13:10:10 2020 - setuid() to 1001
> Sun Mar  1 13:10:10 2020 - chdir() to /usr/local/searx/searx/
> Sun Mar  1 13:10:10 2020 - your processes number limit is 15529
> Sun Mar  1 13:10:10 2020 - your memory page size is 4096 bytes
> Sun Mar  1 13:10:10 2020 - detected max file descriptor number: 1024
> Sun Mar  1 13:10:10 2020 - lock engine: pthread robust mutexes
> Sun Mar  1 13:10:10 2020 - thunder lock: disabled (you can enable it with --thunder-lock)
> Sun Mar  1 13:10:10 2020 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/searx/socket fd 3
> Sun Mar  1 13:10:10 2020 - uwsgi socket 1 bound to TCP address 127.0.0.1:8080 fd 5
> Sun Mar  1 13:10:10 2020 - dropping root privileges after socket binding
> Sun Mar  1 13:10:10 2020 - Python version: 2.7.17 (default, Nov  7 2019, 10:07:09)  [GCC 7.4.0]
> Sun Mar  1 13:10:10 2020 - Set PythonHome to /usr/local/searx/searx-ve/
> Sun Mar  1 13:10:10 2020 - Python main interpreter initialized at 0x5633faf4d890
> Sun Mar  1 13:10:10 2020 - dropping root privileges after plugin initialization
> Sun Mar  1 13:10:10 2020 - python threads support enabled
> Sun Mar  1 13:10:10 2020 - your server socket listen backlog is limited to 100 connections
> Sun Mar  1 13:10:10 2020 - your mercy for graceful operations on workers is 60 seconds
> Sun Mar  1 13:10:10 2020 - mapped 218304 bytes (213 KB) for 2 cores
> Sun Mar  1 13:10:10 2020 - *** Operational MODE: preforking ***
> Sun Mar  1 13:10:10 2020 - added /usr/local/searx/ to pythonpath.
> Sun Mar  1 13:10:10 2020 - dropping root privileges after application loading
> Sun Mar  1 13:10:10 2020 - spawned uWSGI master process (pid: 18523)
> Sun Mar  1 13:10:10 2020 - spawned uWSGI worker 1 (pid: 18530, cores: 1)
> Sun Mar  1 13:10:10 2020 - spawned uWSGI worker 2 (pid: 18531, cores: 1)
> Traceback (most recent call last):
>   File "/usr/local/searx/searx/webapp.py", line 51, in <module>
>     from werkzeug.middleware.proxy_fix import ProxyFix
> ImportError: No module named middleware.proxy_fix
> Sun Mar  1 13:10:12 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
> Sun Mar  1 13:10:12 2020 - *** no app loaded. going in full dynamic mode ***
> Traceback (most recent call last):
>   File "/usr/local/searx/searx/webapp.py", line 51, in <module>
>     from werkzeug.middleware.proxy_fix import ProxyFix
> ImportError: No module named middleware.proxy_fix
> Sun Mar  1 13:10:12 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
> Sun Mar  1 13:10:12 2020 - *** no app loaded. going in full dynamic mode ***
> Sun Mar  1 13:10:15 2020 - --- no python application found, check your startup logs for errors ---
> Sun Mar  1 13:10:18 2020 - --- no python application found, check your startup logs for errors ---

Greets mike

**Comment by return42** [comment]
>  root@mail:/usr/local/searx# sudo -H -u searx -i

remove the old virtualenv away

    mv ./searx-ve ./searx-ve-backup

and create a new one https://asciimoo.github.io/searx/admin/installation.html#basic-installation

    (searx)$ virtualenv searx-ve
    (searx)$ . ./searx-ve/bin/activate
    (searx)$ ./manage.sh update_packages

**Comment by virse** [comment]
Thx return42,

my instance is up and running again with your advice. Thx a lot for your help!

BTW: As python 2.7 is deprecated, is is better to change to python 3?
And when how it is possible to do that?

Greets mike

**Comment by return42** [comment]
> my instance is up and running again with your advice. Thx a lot for your help!

feel welcome and thanks for your feedback .. helps me to classify the issue.

> BTW: As python 2.7 is deprecated, is is better to change to python 3?

Yes py3 .. new documentation is on the way .. for the interim take mine https://return42.github.io/searx/admin/installation.html

**Comment by return42** [comment]
To summarize for those coming around here with the `ImportError: No module named middleware.proxy_fix` exception ..

This issue occurs sometimes when updating an old virtualenv / drop the virtualenv and rebuild a new.

Use https://asciimoo.github.io/searx/admin/installation.html#basic-installation or if you want to switch to python3 use this [preview](https://return42.github.io/searx/admin/installation.html)  of the documentation from PR #1803

**Comment by joshp23** [comment]
EST here. I was passing out earlier in this thread. Happy there is a fix. About to give it a go!

**Comment by joshp23** [comment]
@return42 , I was able to get up and running with python2 by rebuilding the virtualenv according to your advice. 

Also, I tried to get python3 going according to your instructions. After running

`(searx)$ echo 'source ~/searx-pyenv/bin/activate' > ~/.profile`

and then logging out and back into the searx bash, I could not get rid of the error 

`-sh: 1: source: not found`

I'll open a separate issue if you would like.

**Comment by return42** [comment]
> I could not get rid of the error

aargh, my fail .. I have forgotten to update the documentation.

> I'll open a separate issue if you would like.

No, please do not open issues for a PR.  The PR is in progress and discussed at https://github.com/asciimoo/searx/pull/1803

The problem you reported was already reported .. I apologize for all the unnecessary work I've put you through.  .. I will update the docs and come back ..

**Comment by return42** [comment]
It seems there is some trouble with Flask & Werkzeug ..

- https://github.com/pallets/flask/issues/3490
- https://github.com/pallets/flask/issues/3493

May we need to open a new issue to handle this .. I'm just gonna re-open this one.

**Comment by return42** [comment]
@joshp23 I updated the documentation of #1803 / for a preview see https://return42.github.io/searx/admin/installation.html

**Comment by virse** [comment]
Hey return42,

thx for your hard work and your support *thumpsup*

I've read your new installation guide for Searx with Python3. A lot of chances with all the filtron and/or morty stuff ;o)

I guess I will wait with an upgrade to py3 til all your hard work is offically merged into to master branch.

Is there any timetable, when this merging will be the case.

Thx and greets, mike

**Comment by return42** [comment]
> Is there any timetable, when this merging will be the case.

Not really a timeline but I want to finish this PR in march.

**Comment by virse** [comment]
Great. Thx! I will wait til then.

mike

**Comment by return42** [comment]
closed by PR #1803 / see docs at: https://asciimoo.github.io/searx/admin/installation.html
