### ISSUE TITLE
torrentz broken

### ISSUE THREAD

**Issue by unixfox** [searx/searx#1875]
Torrentz is now broken because they are serving a Cloudflare protected page:
![image](https://user-images.githubusercontent.com/4016501/75625213-d63fcb00-5bb3-11ea-9bd1-50f537d33deb.png)

I found a script that bypass the Cloudflare protected page but it requires load of dependencies: https://github.com/Anorov/cloudflare-scrape to work.
**EDIT**: I submitted an issue to `cloudflare-scrape` because the library doesn't seem to work on torrentz2.eu: https://github.com/Anorov/cloudflare-scrape/issues/333

**Comment by unixfox** [comment]
I used https://github.com/VeNoMouS/cloudscraper and it seems to work pretty good.

**Comment by qbitroot** [comment]
![Screenshot from 2020-08-04 12-19-38](https://user-images.githubusercontent.com/66268477/89277328-60053000-d64d-11ea-929d-9bf0e6f4f8ca.png)
Torrentz2.eu down now. New URL is https://torrentz2proxy.xyz/

**Comment by unixfox** [comment]
This PR https://github.com/asciimoo/searx/pull/2101 fixes the issue.

**Comment by rasos** [comment]
Also https://torrentz2proxy.xyz/ is down. 

### Alternatives

activate in `settings.yml` solidtorrents:

```
  - name : solidtorrents
    engine : solidtorrents
    shortcut : solid
    timeout : 3.0
    disabled : False
```
Or we try to provide an engine for https://www.limetorrents.pro or https://search.torrends.to
