### ISSUE TITLE
Installation Wiki for opensuse / sles

### ISSUE THREAD

**Issue by asteriosos** [searx/searx#1877]
Hello there,

is it possible to make an Installation wiki for opensuse / sles like the one for centos ?
i don't get it working.

Thank you.

**Comment by return42** [comment]
In the long run, we will drop the wiki and replace it with documentation.  

ATM I am working #1803 it serves installation script for common platforms .. a preview of the documentation is shown here https://return42.github.io/searx/admin/installation.html (don't bookmark) .. not yet Suse but feel welcome to contribute.

**Comment by unixfox** [comment]
Meanwhile, you can use Docker which works with opensuse: https://github.com/searx/searx-docker

**Comment by asteriosos** [comment]
Hi there,
so i tried some things to install searx in opensuse 15.1.

First i tried the new way with searx-docker, but i got some errors wit caddy: morty rc 1 ...
So i tried the "old" docker way.

i run it with this:
docker run --restart always -d --name searx -p 8080:8080 -e IMAGE_PROXY=True -e BASE_URL=https://my.secret.domain/searx/ searx

So i allowed the tcp/8080 port with firewalld.

On this URL: http://my.secret.domain:8080 i can get the correct searx page.

After that "now" i tried to reverse proxy my apache2 with this conf in vhosts:

`<IfModule mod_ssl.c>
<VirtualHost *:443>
  DocumentRoot /srv/www/htdocs
  ServerName my.secret.domain
  RewriteEngine On
  ProxyRequests Off
    ProxyPreserveHost On
    AddDefaultCharset utf-8
    HostnameLookups off
    UseCanonicalName off
    ProxyBadHeader Ignore
    KeepAlive off
  ProxyPass /searx http://127.0.0.1:8080/
  ProxyPassReverse /searx  http://127.0.0.1:8080/

SSLCertificateFile /etc/letsencrypt/live/my.secret.domain/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/my.secret.domain/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
`
On https://my.secret.domain/searx i now get a very text based version from searx.
There is something wrong with the url handling.

![searx](https://user-images.githubusercontent.com/44438259/76158956-c710ce00-611b-11ea-8246-49af3e07478e.png)

When i configure

 apache with this:

`
  ProxyPass / http://127.0.0.1:8080/
  ProxyPassReverse /  http://127.0.0.1:8080/
`
I get the correct searx site with all features, but all my "normal" sites are gone.

I tried a lot but now i have got no ideas anymore, maybe someone here can help.

thank you... ;-)

**Comment by asteriosos** [comment]
okay, i found it ....
this was missing in the apache configuration:

RequestHeader set X-Script-Name /searx

**Comment by JialuZhang** [comment]
In your configuration,
```
<VirtualHost *:443>
DocumentRoot /srv/www/htdocs
ServerName my.secret.domain
RewriteEngine On
ProxyRequests Off
ProxyPreserveHost On
AddDefaultCharset utf-8
HostnameLookups off
UseCanonicalName off
ProxyBadHeader Ignore
KeepAlive off
ProxyPass /searx http://127.0.0.1:8080/
ProxyPassReverse /searx http://127.0.0.1:8080/

SSLCertificateFile /etc/letsencrypt/live/my.secret.domain/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/my.secret.domain/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
```
has two silent misconfigurations.
First, the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
Second, <VirtualHost *:443> needs a closed statement </VirtualHost>.
