### ISSUE TITLE
Engines silently fail?

### ISSUE THREAD

**Issue by geckolinux** [searx/searx#1883]
Hi there, it appears that many times certain engines silently fail? For example, I enable DuckDuckGo and Mojeek and Startpage in addition to Google, but on many instances it only returns Google results, even when the query is very easy. For example, on two different instances with the exact same engines enabled:

![Screenshot_20200305_094613](https://user-images.githubusercontent.com/2692138/75992635-4016e800-5ec6-11ea-84a5-fb1f05dbf5c0.png)

-----------------------------

![Screenshot_20200305_094548](https://user-images.githubusercontent.com/2692138/75992645-43aa6f00-5ec6-11ea-9e94-7271361d303b.png)

**Comment by unixfox** [comment]
I can replicate the same bug and this started only one/two months ago for a reason that I don't know. The error message is still displayed in the logs though.

**Comment by return42** [comment]
I "feel" sometimes the same .. when I dig deeper, mostly it is about timeouts. But it was not really clear because the experiences a very divergent and mostly my time was limited. It is hard to dig, e.g. the bing_video was very buggy because the rotating  user-agent signatures we use (#1882).

Do you have any more precise information that might clarify the dust a bit more for me?

>  The error message is still displayed in the logs though.

What error message?

**Comment by unixfox** [comment]
> > The error message is still displayed in the logs though.
> 
> What error message?

Depends on the engine, if it's Google then it's CAPTCHA error or if another instance like torrentz2 it's 503 error.

**Comment by return42** [comment]
Please don't mix the CAPTCHA error with experience @geckolinux describes .. the solution for CAPTCHA is definitely filtron!   Since I use filtron and after a short time of tare the filter rules I have no more google CAPTCHA error seen (since 2 month).

**Comment by unixfox** [comment]
I'm not talking about that specific CAPTCHA error... but about the error that should be displayed on the user screen rather than just in the logs of the owner of the searx instance.

**Comment by return42** [comment]
> if another instance like torrentz2 it's 503 error.

When I have no results for some engines I do not see any error message .. I guess that is also what @geckolinux addressed.

**Comment by return42** [comment]
> but about the error that should be displayed on the user screen rather than just in the logs of the owner of the searx instance.

ah, ok, thanks for clarify .. and sorry that I hit the close button :)

**Comment by unixfox** [comment]
Closing in favor of https://github.com/searx/searx/issues/2053.
