### ISSUE TITLE
accept the Ca Terms of letsencrypt

### ISSUE THREAD

**Issue by Happyfeet01** [searx/searx#1887]
Hello,

i have change the settings and would do an docker-compose up -d 
but it failed:

`caddy            | Your sites will be served over HTTPS automatically using Let's Encrypt.
caddy            | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
caddy            |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
caddy            | Do you agree to the terms? (y/n): 2020/03/07 10:29:36 [ERROR] Making new certificate manager: user must agree to CA terms (attempt 1/3)
caddy            | 
caddy            | 
caddy            | Your sites will be served over HTTPS automatically using Let's Encrypt.
caddy            | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
caddy            |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
caddy            | Do you agree to the terms? (y/n): 2020/03/07 10:29:36 [ERROR] Making new certificate manager: user must agree to CA terms (attempt 2/3)
caddy            | 2020/03/07 10:29:36 user must agree to CA terms
caddy            | 
caddy            | 
caddy            | Your sites will be served over HTTPS automatically using Let's Encrypt.
caddy            | By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
caddy            |   https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
caddy            | Do you agree to the terms? (y/n): 2020/03/07 10:29:36 [ERROR] Making new certificate manager: user must agree to CA terms (attempt 3/3)
caddy            | exit status 1
caddy exited with code 1`

how can i accept the CA Terms?

**Comment by unixfox** [comment]
If it's related to [searx-docker](https://github.com/searx/searx-docker) then please open an issue there.
