### ISSUE TITLE
Installing a public instance

### ISSUE THREAD

**Issue by bluttle** [searx/searx#1894]
I could not quite catch the documentation of installing searx on a public server. Anyone could describe of how to do so?? is it possible to do it on windows and what is kali linux?
Thanks in advance.

**Comment by unixfox** [comment]
Based on your knowledge you shouldn't do a public instance yet but a private one because you aren't experienced enough with managing a server.
You may use searx-docker on windows by installing docker: https://github.com/searx/searx-docker

**Comment by bluttle** [comment]
Hey but still anyway there

**Comment by return42** [comment]
Hi @Arijit265 sorry for harsh closing your issue, but it is like @unixfox already mentioned.

We don't recommend to install searx without a base of fundamental knowledge, believe me, you won't be happy with.  If it is to hard to understand our [installation instructions](https://asciimoo.github.io/searx/admin/installation.html)   (or the new I'am currently working on [preview](https://return42.github.io/searx/admin/installation.html) ) you are more a user than an admin.

For common user (non admin, non developer) we recommend to use a public instance, feel welcome to use my instance https://darmarit.cloud/searx or any of the instances listed on https://searx.space

**Comment by unixfox** [comment]
If you really want to have your own Searx on windows then learn how to launch a python program on windows: https://docs.microsoft.com/en-us/windows/python/beginners then git clone the searx repository, install pip if it's not already installed: https://www.liquidweb.com/kb/install-pip-windows/ and finally launch searx using this command:
```
python searx/webapp.py
```

If you encounter an issue just search the issue on your favorite searx engine (Searx, Google, dgg, ...), there are plenty of tutorials explaining how to launch a python program. You won't be lost.
