### ISSUE TITLE
What kind of cloud hosting to upload on?

### ISSUE THREAD

**Issue by bluttle** [searx/searx#1896]
Hello guys I now know how to upload a public instance. I was just not reading the docs properly but I just have a question what type of hosting should I choose to upload a public instance. Should it be shared hosting, VPS hosting or Cloud hosting? Or somethimg else

**Comment by bluttle** [comment]
Pls tell which one will you prefer

**Comment by return42** [comment]
Most users have VPS .. about PI .. I don't know a PI hoster :) .. beside joking, I do not have any  searx experience on a PI.

**Comment by unixfox** [comment]
We should really have a gitter or IRC because these simple questions unrelated to Searx and that can be answered easily through a search on a search engine are getting quite annoying.

**Comment by asciimoo** [comment]
We have IRC channel @ freenode (and @ ircnet too). It is mentioned in the readme.
