### ISSUE TITLE
Provide an easier way to change the Source Code and related links

### ISSUE THREAD

**Issue by caribpa** [searx/searx#1897]
As noted in the issue https://github.com/dalf/searx-instances/issues/23, there are some modified public instances listed in [searx.space](https://searx.space/) that don't provide a link to their source code, violating the AGPLv3.

The first issue here is that there is no mention in any of the installation/getting started/README.md documents/wiki of the importance of correctly making your Searx instance's code public if you modified it, nor any reference to where you should place the link with your code for it to appear in your instance's main page.

I had to clone the repo and do a search with my editor to find the appropriate variable hidden in [docs/dev/makefile.rst](https://github.com/asciimoo/searx/blob/master/docs/dev/makefile.rst), but the description fails to mention that you must link your project's code if you modified anything excluding non-essential secrets. Currently the **GIT_URL** variable in the [Makefile](https://github.com/asciimoo/searx/blob/master/Makefile#L3) is the responsible for setting up the _Source Code_ link that appears at the bottom of the main page after the Searx instance is built.

Once the instance is built, there is no way for changing this variable easily unless the instance is rebuilt again or tampering with unnecessary code. There is another problem though, the processing of the variable assumes (example: [conf.py](https://github.com/asciimoo/searx/blob/master/docs/conf.py#L38)) that your instance's code is going to be hosted on a git website/domain. Thus preventing people from, for example, creating a `tar.xz` of the project to save space on their server.

Maybe a better approach would be to define these variables in [settings.yml](https://github.com/asciimoo/searx/blob/master/searx/settings.yml) next to `instance_name` and have conf.py (and others) retrieve the appropriate links from there.

If having such variables in the Makefile is mandatory for now, I'd also suggest to rename **GIT_URL** to **CODE_URL** (same with other **_URL** variables) and automatically add to the settings.yml template an `instance_code` entry in the _General_ section with the specified URL.

This would also allow to maybe automatically add next to the _Source Code_ link a link to the original project (in the spirit of: _forked from \<url\>_) if the `instance_code` value is different from the original (thus the need to also have a `original_instance` entry as maybe a _modified instance_ was used as a base for our own modifications instead of _vanilla Searx_).

**Comment by return42** [comment]
The intention of the Makefile is to support *brands*, this concept is not implemented to its end, but it works. E.g. take a look at my https://return42.github.io/searx/ documentation which was build by modifying the variables you mentioned. In the upper left you see the link to the "Sources" of my PR branch.

> There is another problem though, the processing of the variable assumes (example: conf.py) that your instance's code is going to be hosted on a git website/domain. 

If your brand (fork) is not hosted on github and your git-hoster does not provide the URL schema

     '/blob/master/%s'

you can change this variable in your fork. It is the maximum on flexibility we can maintain at this point.

BTW: [Searx has two prime directives, privacy-by-design and hackability](https://return42.github.io/searx/dev/contribution_guide.html?highlight=hacking#prime-directives-privacy-hackability) and I did not have seen any serious abuse right now.  

I really want to see people hacking and as long as there is no abuse I don't see the need to bother them with the fulfilment of a  licenses .. a link, nobody will ever follow, sorry but this is really a kind of bikeshedding no one needs.

**Comment by caribpa** [comment]
Sure, modifying the **GIT_URL** changes the _Source Code_ URL as expected, same as hacking the code, but that was not my point.

My point is that there is no fool-proof way for changing the _Source Code_ link after the instance has been built.

Bikeshedding or not there is a point in choosing a license for a project, and you cannot choose any license that won't be honored or some people won't simply trust you. If handwaving the license is OK for the sake of having people hacking the code I think that changing the license to a more permissive one is the proper way to go.

**Comment by return42** [comment]
> My point is that there is no fool-proof way for changing the Source Code link after the instance has been built.

What is the use case behind this request? The build includes the build of docs & links, you can tar after (to pick your example) .. we do not maintain options to change "this or that" in any state. Just build and go.

> Bikeshedding or not there is a point in choosing a license for a project, and you cannot choose any license that won't be honored or some people won't simply trust you.

Its natural to open source projects, that you can change the code in any matter you want and its also known that changing the licences string is not what "hacking" means ..may you misunderstand what I mean with hacking?

**Comment by dalf** [comment]
@Caribpa the link in this [line](https://github.com/asciimoo/searx/blob/master/searx/templates/oscar/base.html#L89) should not be hard coded ?

**Comment by caribpa** [comment]
> What is the use case behind this request?

For example today I have my public instance hosted in X, my source code is in github, but tomorrow I migrate all my code to gitlab. How do I easily change the references to my source code on my public instance? If I can't or don't want to rebuild everything for some reason, my only option is to do a search and replace of the old url with the new one and I may even miss some case depending on the tools and time I have.

> we do not maintain options to change "this or that" in any state. Just build and go.

This is not true, for example you can modify the instance's name and the secrets without rebuilding in [settings.yml](https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L3)

> Its natural to open source projects, that you can change the code in any matter you want and its also known that changing the licences string is not what "hacking" means ..may you misunderstand what I mean with hacking?

With "hacking the code" I meant "changing the code badly" like in the example I described above for just updating the link to the source code of your instance.

**Comment by caribpa** [comment]
@dalf yes, this is the other part of the issue. Even if I set the **GIT_URL** variable to my modified code, some of the default templates don't take it into account.

**Comment by return42** [comment]
> For example today I have my public instance hosted in X, my source code is in github, but tomorrow I migrate all my code to gitlab. How do I easily change the references to my source code on my public instance?

Change the variables you mentioned, rebuild and deploy.

> This is not true, for example you can modify the instance's name and the secrets without rebuilding in settings.yml

Correct, this is for those who do not want to create a fork (brand). May we have a different meaning about the concepts behind.  You can go the simple way, just installing searx without any change and on the other hand you can fork searx to implement your own brand. The licences is always the same.

> With "hacking the code" I meant "changing the code badly" like in the example I described above for just updating the link to the source code of your instance.

May I misunderstood you, why should it be bad hacking, if you point in your instance to the fork your instance is build from?

**Comment by return42** [comment]
> some of the default templates don't take it into account.

if so it is a bug, please open another  issue.

**Comment by caribpa** [comment]
> Change the variables you mentioned, rebuild and deploy.

Not as trivial as simply modifying `instance_code` in settings.yml. I can change my instance name almost on the fly, _only_ restarting searx is needed.

> Correct, this is for those who do not want to create a fork (brand). May we have a different meaning about the concepts behind. You can go the simple way, just installing searx without any change and on the other hand you can fork searx to implement your own brand. The licences is always the same.

Yes, the licenses stays the same as they should, but the problem is that the license is violated if I modify something in my instance and I don't publicly share such modified version.

Let's say I want to go the _simple way_ to create a public Searx instance but with the option to experiment:
```sh
docker pull searx/searx
docker run -d -p 8081:8080 --name searx searx/searx:latest
# I can actually edit the dockerized searx instance name
docker exec -it searx vi /etc/searx/settings.yml
# and the changes appear after restarting the container
docker restart searx
# Long-term changes goes in the default searx folder
docker exec -it searx vi ./searx/settings.yml
# I can also save the changes to the same image (or any other)
docker commit searx searx/searx
# So any new container has those changes from the beginning
docker run -d -p 8082:8080 --name searx_other searx/searx
# Even save them to a file
docker save searx/searx | gzip > searx.tar.gz
# to resume elsewhere with what I modified
gzip -cd searx.tar.gz | docker load
docker run -d -p 8083:8080 --name searx_elsewhere searx/searx
# And the full source code is easy enough to retrieve to make it public
docker export searx_elsewhere | tar --strip-components=2 -xf - usr/local/searx
# If only changing the default Source Code link was that easy...
docker exec -it searx_elsewhere make  # exec: "make": executable file not found in $PATH
```

Btw there are far better ways of editing files inside docker from the localhost or remotely (exposing them with volumes, or with ssh multi-hops if your editor supports it).

> May I misunderstood you, why should it be bad hacking, if you point in your instance to the fork your instance is build from?

Maybe it is my fault that I didn't mention that there are cases where using `make` is not an option (like in the docker example). With this in mind what "bad hacking" means is having to search all the references of **GIT_URL** and inside the html files of the themes to be sure that you updated every single link so they point to your source code.

All of this could have been prevented by having a harmless entry in settings.yml for easy changing the source code link.

**Comment by caribpa** [comment]
What I wanted to say with those docker commands is that what seems to be the _simple way_ may also be the best way for building your own _brand_ because you don't have to bother fighting with apache/nginx and other dependencies for just starting up to experiment. In fact, it would be really interesting to see how many of the current public instances in searx.space are using docker.

**Comment by return42** [comment]
You do not want to understand the concepts of build and deploy software and the flexibility searx brings. INstead you believe that what seems simple to you is the only right solution  ..  You construct problems that do not exist. BTW I already mentioned that your license talking is useless bikesheeding.  

I am out!

**Comment by caribpa** [comment]
> You do not want to understand the concepts of build and deploy software and the flexibility searx brings. INstead you believe that what seems simple to you is the only right solution .. You construct problems that do not exist. BTW I already mentioned that your license talking is useless bikesheeding.

Sadly I don't know from where you are getting that impression, I showed before how easy is to build and deploy with docker.

Honestly I don't understand why you are getting that offended and calling *useless bikesheeding* the license issues that DO currently exists in the majority of modified public instances in searx.space. Violating a license is basically breaching a contract, which is quite severe.

To help prevent (and easily correct) those license issues, once an instance has been built and deployed into limited environments, my proposal is to add more entries in the *[General]* section of settings.yml, and I suggested that the entry called `instance_code` would be the one responsible for correctly changing all the *Source Code link references* in your instance, thus increasing even more the flexibility searx brings.

I honestly don't know why there is such pushback without actual arguments when currently you can change many things like the name of your instance (`instance_name`), debug options, engines, etc, once your instance has been built and deployed just by editing the settings.yml.

**Comment by return42** [comment]
> Sadly I don't know from where you are getting that impression, I showed before how easy is to build and deploy with docker.

Docker is a container, you can run make in containers, if you need. But this is not the intention of such a container.  Such a container is for easy deployment.

If you want to change the code, you have to fork .. and this is what developers normally do. Even if you develop a PR you have to fork .. or did you ever called github to change their git based workflows in a mess of tar?

Please understand the base concepts of SCM, git was made for. No maintainer is interested in maintaining several concepts dealing with 'individual handmade' workflows .. this what we have seen all the years before git.

Learn SCM workflows, there are excellent tutorials on the WEB (e.g. [this fork workflow description](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) ).

You can host your git repo wherever you want, github, gitlab or even on your own git server.  But when you don't want to use git, you end in the problems you tried to discuss here. Please don't take this the wrong way, but discussions like this and the academical view on licences just sucks.

**Comment by dalf** [comment]
An partial technical implementation of what I guess is requested.

1. Add searx/data/external_links.json (so no change of settings.yml) :
```json
{
	"Public instances": "https://searx.space/",
	"Source code": "https://github.com/asciimoo/searx",
	"Issue tracker": "https://github.com/asciimoo/searx/issues",
}
```


2. Same [useragents.json](https://github.com/asciimoo/searx/blob/85b37233458c21b775bf98568c0a5c9260aa14fe/searx/utils.py#L52-L53), load external_links.json

3. Add ```kwargs['external_links'] = EXTERNAL_LINKS``` for to the [render](https://github.com/asciimoo/searx/blob/85b37233458c21b775bf98568c0a5c9260aa14fe/searx/webapp.py#L307) function  

4. Then instead of copy / paste links, templates can use values from EXTERNAL_LINKS.

* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/simple/base.html#L53-L56
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/oscar/base.html#L88-L91
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/legacy/github_ribbon.html#L1
*  https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/courgette/github_ribbon.html#L1
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/__common__/about.html#L10
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/__common__/about.html#L25
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/__common__/about.html#L32

---

Other links:
```
	"installation and setup": "https://github.com/asciimoo/searx/wiki/Installation",
	"settings.yml": "https://raw.github.com/asciimoo/searx/master/searx/settings.yml",
```

See 
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/__common__/about.html#L51-L52
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/__common__/about.html#L57

---

* over engineering is not good.
* Keep it stupid simple is good. 
* but / and / or avoid copy /paste is good too.

**Comment by caribpa** [comment]
> Please don't take this the wrong way, but discussions like this and the academical view on licences just sucks.

I 100% agree that the discussions about licenses suck, but they are not limited to academics, they are mostly defined/revised by lawyers. Licenses is what prevent certain software to be used in a system, workflow, project, etc. I have already encountered this issue several times in the companies I worked for. This is the reason I also suggested changing the AGPLv3 license to a more permissive one if these kinds of discussions are being seeing as bikeshedding and ultimately they are handwaived, because currently there are violations of the chosen license in the public instances in searx.space.

> If you want to change the code, you have to fork .. and this is what developers normally do. Even if you develop a PR you have to fork .. or did you ever called github to change their git based workflows in a mess of tar?
>
> Please understand the base concepts of SCM, git was made for. No maintainer is interested in maintaining several concepts dealing with 'individual handmade' workflows .. this what we have seen all the years before git. 

I understand quite well how workflows work, and I agree that nobody wants to maintain a mess of a tar when you can use workflows. The `docker | tar` was an example of how *easy* (not convenient on the long term) was to retrieve the source code of your modifications inside docker. As I said, a better way to do changes inside docker is either exposing to the host the container files using docker volumes (you can leverage git this way) or accessing the docker filesystem from the host with ssh (and leverage git again). But those ways are not as simple as the oneliner `docker | tar` I showed.

In fact one can even refrain from storing the source code anywhere and just generating it on the fly whenever somebody requests it, which for sure would require a hackish setup with calls from the container to the host to perform `docker | tar`, 99% of the times not worth it considering the alternatives mentioned before, but it would still comply with the AGPLv3 license.

> Docker is a container, you can run make in containers, if you need. But this is not the intention of such a container. Such a container is for easy deployment.

In my experience docker is an amazing tool for developing, specially fast prototyping, and ultimately easy deployment. There are many images of searx in [hub.docker](https://hub.docker.com/search?q=searx&type=image) that are forks of others, probably they did it the way I showed before. And as I also said: it would be really interesting to see how many of the current public instances in searx.space are using docker.

Anyways, the point of this issue is not docker nor git workflows, the point is that there is no actual reason for not having a `instance_code` variable (and some others present only in the Makefile) inside settings.yml. When such variables make your life easier for correcting searx features, and if `instance_name` is there, why is there no variable that helps you changing the source code public links of your instance to comply with the AGPLv3 license?

**Comment by caribpa** [comment]
@dalf using `searx/data/external_links.json` is actually a smarter approach than using settings.yml because, as you showed, it would allow a dumb-easy way for changing both the links and the text. Hats off to you 👍

**Comment by caribpa** [comment]
Then what would happen with the **GIT_URL** and related variables specified in the `Makefile`?

**Comment by return42** [comment]
> Add searx/data/external_links.json (so no change of settings.yml) :

I feel like Don Quixote .. where should this link point to? .. to a public repository with a fork. This is what works right now using SCM and make.

We do not support tar archives., We support simple and native workflows. 

If this does not match the needs of one, he is free to create a fork (with or without a SCM) where he can do whatever he wants (except changing the licences).

If someone wants to see a variable added to settings.yml he is free to send us a PR.

> In my experience docker is an amazing tool for developing, 

.. for windows developer .. linux user are developing on the host OS and test and deploy in containers driving different OS.

I have said everything a I can say about .. now I out really out.

**Comment by return42** [comment]
> Then what would happen with the GIT_URL and related variables specified in the Makefile?

Did you hear the bells?

**Comment by dalf** [comment]
As far I know, the themes do not use GIT_URL, the https://github.com/asciimoo/searx URL is hard coded ([example](https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/oscar/base.html#L88)).

If I'm not wrong, that's mean that even if GIT_URL is changed, the HTML footer won't show the GIT_URL value.

Perhaps it doesn't make any sense to show GIT_URL value in the html footer. Perhaps I miss something about GIT_URL.

**[EDIT]** I didn't not answer the question "where should this link point to?".
It should contains the GIT_URL value, note: it is a change compare to the current code base (I'm may be wrong).

**Comment by return42** [comment]
If you see an error, please open an issue. I will fix it.

**Comment by dalf** [comment]
For example, in this line:
https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/oscar/base.html#L88-L88
```https://asciimoo.github.io/searx/``` should not be hard coded, it should be the GIT_URL value.

I'm not sure how to do that without adding a setting or file since GIT_URL is an environment variable declare in Makefile.

**Comment by return42** [comment]
Please, add a issue .. I will find a solution for.

**Comment by Caribpa** [comment]
@return42 what's up with that attitude of yours? why are you being so hostile with newcomers to the project that show legitimate issues and interest towards it? I haven't checked but do you react this way also with other people?

Maybe it is an issue with the wording you use, maybe is a culture thing, or not enough emojis, but don't you realize that this harms you and puts away some people from working with you and in the projects you are?

To put it simple what you did:
* You closed the issue right away without even understanding fully what I was presenting.
* Labeled as "bikeshedding" legitimate license violations.
* Reopened the issue when I basically repeated what I said in the OP (with an example requested by @dalf), and closed it again right after you concluded that I should open another issue without truly understanding what I was talking about.
* Concluded that people should just hack a little of the code to do trivial but essential changes in their configuration that can be automated, like changing the default value of a simple link.
* Made a lot of poor assumptions about me personally, and software practices that are plainly wrong without second thoughts.
* Marked the thread as resolved and locked it because you were "really out", preventing me from commenting.
* Unlocked it again after @dalf showed the same concerns I pointed out and you ignored.

I don't know what @dalf and other members of the team think but this behavior is simple unacceptable.

I raised up the license issue because I was interested in this project, disclaimer: I am not anymore thanks to you. The first thing I did, like I do whenever somebody in my team at work suggests using a software for the project, is go and see the license, because this is crucial in a professional environment, like it or not you cannot ignore the licenses if you are a professional. Then I noticed that some public searx instances were not following the chosen license, so I raised an issue and suggested changes, you know, to test the waters before putting work in a project were I might not be welcomed, and glad that I did because then you happened.

Also, as far as I can see this issue is NOT resolved and should be reopened.

And if you believe that docker is for Windows users you are wrong again. After almost 15 years working exclusively in many flavors of Linux, Docker gives me the chance to experiment with software without wasting 1 second on their dependency trees. Maybe after that time on the job you will change your mind and also learn manners on the way.

PS: It goes without saying that you should apologize.
