### ISSUE TITLE
templates: use the GIT_URL value instead of https://asciimoo.github.io/searx/

### ISSUE THREAD

**Issue by dalf** [searx/searx#1898]
In the templates, ```https://asciimoo.github.io/searx/``` should not be hard coded, it should use the [GIT_URL](https://github.com/asciimoo/searx/blob/master/Makefile#L3) value.

I'm not sure how to do that without adding a setting or file since GIT_URL is an environment variable declare in Makefile.

Related to https://github.com/asciimoo/searx/issues/1897

Lines in the templates:
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/simple/base.html#L53-L56
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/oscar/base.html#L88-L91
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/legacy/github_ribbon.html#L1
*  https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/courgette/github_ribbon.html#L1
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/__common__/about.html#L10
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/__common__/about.html#L25
* https://github.com/asciimoo/searx/blob/9a2f26d915ee05d933a18c31bca2121658aa7ffd/searx/templates/__common__/about.html#L32

**Comment by MarcAbonce** [comment]
I actually agree with both #1897 and this issue. In fact I wanted to do this a while ago, but I had forgotten about it.
I'm just started to work on this, but I think I'll have it by tomorrow.

**Comment by return42** [comment]
I assigned this error to mine .. the solution will be a "project" target I mentioned in https://github.com/asciimoo/searx/issues/1882#issuecomment-595079268

**Comment by return42** [comment]
closed by https://github.com/asciimoo/searx/pull/1900
