### ISSUE TITLE
Search engine request: Torrent Paradise

### ISSUE THREAD

**Issue by virtadpt** [searx/searx#1902]
https://torrent-paradise.ml

**Comment by Quix0r** [comment]
The problems with such torrent search engines are:
1. They are most closed-source
2. They are infested with ads (user can still block them)
3. They spread "illegal" content (unauthorized distribution of copyrighted materials, I'm not a fan of such words, too! But I do support good actors/actresses.)
4. searx administrators and the searx project itself may become a target of DMCA (I don't like that, again) requests.

So far I have not received such letters as I'm the owner of a public searx instance. It would be nice (for some restrictive countries) to have a way to fully exclude torrent search engines allowing such content being tracked there. So every admin (and end-user can see it in `settings` page) can decide it independently from searx' decision.

So it has pros and cons to have such engines in. E.g. you might better want to have torrent trackers in that track only OSS/FLOSS to spread the good word about trorrents.

**Comment by unixfox** [comment]
We already have loads of search engines like that in the code base for a long time: TBP, torrentz2, 1337x, kickass, nyaa, seedpeer.
I don't think another one will make the difference and you are free to disable the engines that you don't want on your own public instance.
Moreover Searx is a still a niche project and the law enforcement target popular websites not a small website used by only 200 visitors by day.

**Comment by return42** [comment]
If it helps, we should document the [xpath engine](https://github.com/asciimoo/searx/blob/master/searx/engines/xpath.py) and add some code snippets (examples) to that docs.

**Comment by julianfairfax** [comment]
It has shutdown now so this should be closed
