### ISSUE TITLE
Searching images for "hey" on any searx instance reporting 0.16.0-63-9a2f26d9 will cause a 500.

### ISSUE THREAD

**Issue by ghost** [searx/searx#1904]
To clarify on the title, this is an issue with all searx instances reporting version 0.16.0-63-9a2f26d9 (I assume those who use a prebuilt docker image), and some instances reporting 0.16.0 but not all. 

To reproduce:

- Go to any searx instance reporting 0.16.0-63-9a2f26d9
- Type "hey" with any capitalization (other three letter strings do not work)
- You can be using either GET or POST, and you can either search in general and click over to images, or search for images directly.
- Get error.

Here is a short [video](https://lbda.net/9FQ.mp4) of this being performed on 4 instances reporting 0.16.0-63-9a2f26d9 on [searx.space](https://searx.space).

**Comment by unixfox** [comment]
I can't reproduce the bug on the instances reporting "9a2f26d9" and your video doesn't exist.

**Comment by ghost** [comment]
Sorry about the video link. I have re-uploaded it elsewhere, and updated the original post.
[Re-uploaded Video (https://lbda.net/9FQ.mp4)](https://lbda.net/9FQ.mp4)

**Comment by unixfox** [comment]
I didn't test in the "images" section before. Just tried now on searx.dev by typing "hey" in the "images" section and I'm able to reproduce the bug.
Oddly enough this doesn't happen on instances that doesn't have the tag "9a2f26d9" though.

~~@dalf https://a.searx.space produce the same bug, maybe you could look at the logs of your instance?~~

**Comment by ghost** [comment]
My bad, I forgot to include that in the reproduction steps. While it dosen't happen on most instances not reporting "9a2f26d9", it does happen on some. I ran through about 20 and found that it happened on:

- https://searx.be/ (Caddy)
- https://searx.decatec.de/ (Nginx)
- https://search.snopyta.org/ (Nginx)
- https://spot.ecloud.global/ (Unknown, always returns 307)
- https://searx.pwoss.org/ (nginx)
- https://zoek.anchel.nl/ (Unknown)
- https://searx.hlfh.space/ (nginx/1.17.7)
- https://search.privacytools.io/ (down right now)
- https://darmarit.cloud/searx/ (Apache)

But not, 

- https://occusearch.de/ (Apache)
- https://wtf.roflcopter.fr/searx/ (Apache)
- https://search.stinpriza.org/ (Apache)
- https://searx.canox.net/ (Nginx)
- https://searx.win/ (Nginx)
- https://seeks.hsbp.org/ (nginx)
- https://searx.sunless.cloud/ (nginx)
- https://searx.dojocasts.com/ (nginx)
- https://search.disroot.org/ (nginx)
- https://search.mdosch.de/ (Unknown)
- https://searx.tuxcloud.net/ (nginx)
- https://searx.info/ (Nginx)
- https://searx-anon.duckdns.org/ (i81b4u) (Nginx compiled with [this](https://github.com/i81b4u/tlsv1.3-nginx/blob/3f0ed16565e0fd313b8ea69c7e32fc1aa60f5ea9/nginxcompile.sh#L207) script
- https://searx.pofilo.fr/ (Apache)


I was unable to find a public difference between these groups. I assumed that it might be using the Caddy server as that is what is packaged with all the searx-docker images, but I was also unable to find a correlation there. My instance (searx.dev) runs Traefik and Caddy.

**Comment by unixfox** [comment]
It doesn't happen when setting the language to "English - en" instead of "English (United States) and the bug is related to the engine "flickr".
This issue is a duplicate of #1832.

**Comment by ghost** [comment]
You are right. I will close the issue.
