### ISSUE TITLE
[OUR BIG ISSUE] Vain & Vulgar Results

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#1907]
I encourage everyone to correct me, where I'm wrong...

### First Problem
I often get to see meaningless results that don't even have a single keyword of the given search, sometimes it would be the Landing Page of a website, which, to me, it the most meaningless type of result that can be.

Why this happens?
I suspect that some of the search engines from which a searx instance obtains result, intentionally send useless result.

### Second Problem
_I'm not seeing myself contributing code for the project development or for the feature mentioned below, so excuse me for being so blatant to request such feature, but it is critical_

We don't have a mechanism to filter adult content, so you might lookup for an automobile manufacturer and you would also find results and also (thanks to wikidata) a big entry of an adult model (See [Porshe - Gruble](https://www.gruble.de/?q=Porshe&categories=general&language=en-US)).

Yes, I know what it means, it means more CPU load on a searx instance to filter such contents, and I know that this type of functionality it not cheap.

In any way, I'm not referring to the minors, I'm thinking as to what new users, of any adult age, would think of the quality of searx.

### Conclusion
To me, it seems that 3rd parties are detecting searx instances and **intentionally** feeding them with low quality results and also (excessive adult-only contents) in order to put us down.

**Comment by GreenLunar** [comment]
Similar issues #407 #636

**Comment by kvch** [comment]
Your conclusion seems far fetched. What is your proof?

95% of the time when I search using my local searx instance and do a search using web browser in incognito mode directly on the site I am getting identical results. How come that searx instance is not detected?

Also, the other issue does not need any filtering from searx. Most of them can be resolved by adding support for safe search in every engine. It is true, we should do a better job at making sure safe search is supported. I can see it can be disturbing to see inappropriate content.

**Comment by GreenLunar** [comment]
> Your conclusion seems far fetched. What is your proof?
I have posted a link to a search query to realize my argument.

> 95% of the time when I search using my local searx instance and do a search using web browser in incognito mode directly on the site I am getting identical results.

I don't know of identical results, because I don't and didn't compare, not recently and not in a long time. But, to me, results are good 95% of the time.

> How come that searx instance is not detected?
I didn't understand this question.

The problem, by my humble opinion, is that we have a little bit more Vain & Vulgar results than other search engines.

##### The following realization is crucial, and I firmly believe it should guide us.
Google, before it went public, has locked any way to get pornographic contents through its search engine.

_Back then, if you wanted to search for pornographic media or contents (e.g. videos), you had to resort to Yahoo!, when search engines have crawled for raw video files (i.e. ```.mkv```, ```.mp4```, ```.ogg```, ```.wmv``` etc.), and that was before the video sharing websites._

Why any way to look up for pornographic content was blocked?
My guess, is that it would have damaged Google's IPO.

**Comment by GreenLunar** [comment]
> Your conclusion seems far fetched. What is your proof?

I have posted a link to a search query to realize my argument.

> 95% of the time when I search using my local searx instance and do a search using web browser in incognito mode directly on the site I am getting identical results.

I don't know of identical results, because I don't and didn't compare, not recently and not in a long time. But, to me, results are good 95% of the time.

> How come that searx instance is not detected?

I didn't understand this question.

---

The problem, by my humble opinion, is that we have a little bit more Vain & Vulgar results than other search engines.

##### The following realization is crucial, and I firmly believe it should guide us.
Google, before it went public, has locked any way to get pornographic contents through its search engine.

_Back then, if you wanted to search for pornographic media or contents (e.g. videos), you had to resort to Yahoo!, when search engines have crawled for raw video files (i.e. ```.mkv```, ```.mp4```, ```.ogg```, ```.wmv``` etc.), and that was before the video sharing websites._

Why any way to look up for pornographic content was blocked?
My guess, is that it would have damaged Google's IPO.

**Comment by GreenLunar** [comment]
Another way to examine this: Look up for MD5, SHA1, and Blockchain transactions, and you would see Top-Level Domains (i.e. Landing Pages) of the web giants (social networks and search engines) listed on the first results page.

They must be doing something to cause this.  These particular results of type don't make any sense.

**Comment by kvch** [comment]
> > Your conclusion seems far fetched. What is your proof?
> 
> I have posted a link to a search query to realize my argument.
> 
> > 95% of the time when I search using my local searx instance and do a search using web browser in incognito mode directly on the site I am getting identical results.
> 
> I don't know of identical results, because I don't and didn't compare, not recently and not in a long time. But, to me, results are good 95% of the time.
> 
> > How come that searx instance is not detected?
> 
> I didn't understand this question.

Your conclusion is that search services are providing bad results to searx on purpose. What makes you say that? How do the services figure out that the search request is sent by searx?

My experience with searx tells me, if I am getting irrelevant results is either due to the fact that searx does not send any personal data to the service. Thus, the results returned are generic. For example if I look up "coffee shop" using searx I am getting the Wikipedia page for coffeeshops in the Netherlands, coffee shops from Stockholm, etc. However, if I use Google, I am get information about the local coffee shops. 

Another possible reason for getting irrelevant results is that you need to adjust your searx configuration to fit your own needs.

**Comment by GreenLunar** [comment]
> Your conclusion is that search services are providing bad results to searx on purpose. What makes you say that? How do the services figure out that the search request is sent by searx?

Perhaps by sending a random string and locate a searx instance IP.  Another way is by headers which may include handing of tar/gz archives, fonts, canvas hash and whatnot...

> My experience with searx tells me, if I am getting irrelevant results is either due to the fact that searx does not send any personal data to the service. Thus, the results returned are generic. For example if I look up "coffee shop" using searx I am getting the Wikipedia page for coffeeshops in the Netherlands, coffee shops from Stockholm, etc. However, if I use Google, I am get information about the local coffee shops.

I agree.

> Another possible reason for getting irrelevant results is that you need to adjust your searx configuration to fit your own needs.

In what way?

**Comment by unixfox** [comment]
Closing in favor of similar issues #407 #636.
