### ISSUE TITLE
branding: should searx/brand.py and utils/brand.env be commited ?

### ISSUE THREAD

**Issue by dalf** [searx/searx#1909]
Since the ```buildenv``` Make target is dependency of all other targets, should  searx/brand.py and utils/brand.env be commited ?

**Comment by return42** [comment]
I vote for versioning theses files .. if you want to run shell or python scripts without calling a Makefile target you need this files. E.g. when you directly call `python ./setup.py`

**Comment by dalf** [comment]
It makes sense.

---

About the docker build: as described in this comment https://github.com/asciimoo/searx/pull/1905#issuecomment-607094469 :  on the [searx/searx](https://github.com/searx/searx/), ```make buildenv``` creates two not commited files during the build process because:
  * searx/brand.py and utils/brand.env are already in the git repository  
  * and GIT_URL is different

so [```./manage.sh docker_build```](https://github.com/asciimoo/searx/blob/master/manage.sh#L123-L127) adds ```-dirty``` to the tag name. Current tag : [```0.16.0-94-8189e18d-dirty```](https://hub.docker.com/r/searx/searx/tags).

So here different options:
* A hack to ignore these two files: change https://github.com/asciimoo/searx/blob/8189e18d91e55388cec48d73a9d7648b1c148d0b/manage.sh#L125 for :
```sh
if [ ! -z "$(git diff-index --name-only HEAD -- | grep -v 'searx/brand.py' | grep -v 'utils/brand.env' )" ]; then
```
  Good point: commits are the same between asciimoo/searx and searx/searx
* A new uniq commit on searx/searx for the branding, then rebase that commit to keep the commit id from asciimoo/searx.

I'm going to create a PR about this.
