### ISSUE TITLE
"Firefox can’t establish a connection to the server at 127.0.0.1:4004"

### ISSUE THREAD

**Issue by razkal** [searx/searx#1919]
hi,

i have set [](https://occusearch.de/) as my default search engine in Firefox 74.0.1.
when i search something in firefox address bar i am getting the error "Firefox can’t establish a connection to the server at 127.0.0.1:4004".

any suggestions?

**Comment by dalf** [comment]
Are you using your own instance ? 
* if yes, how do you install it ? on which platform ? which operating system ?
* if no, which instance are you using ?

**Comment by razkal** [comment]
hi, i am using occusearch.de
windows 10.
i have this issue when searching through the address bar.
the search in occusearch.de is ok.

**Comment by unixfox** [comment]
It's an issue from occusearch, they configured their settings incorrectly: `view-source:https://occusearch.de/opensearch.xml`
We can't do anything about it. You should contact the owner if you can.
