### ISSUE TITLE
[feature request]: displaying number of search hits

### ISSUE THREAD

**Issue by Rik44444** [searx/searx#1922]
dear all,
thank you for this amazing search engine, i use it daily both for work and for personal stuff. 
I have a feature request (i think, unless it is already possible): 
to display the number of hits that the search has generated, as Google does. I find this very useful to determine how popular a certain search term is. 
![afbeelding](https://user-images.githubusercontent.com/42555414/79303963-819ca900-7ef0-11ea-83cd-7d0bca09e268.png)

**Comment by Snapy** [comment]
See #443 and #600 (tldr: not possible). Also if you want popularity you should look at google search trends or autocomplete suggestions as number of search results is irrelevant for many queries (single word queries for definitions, common words and other zero click results). For Searx itself, you would need some logging (has privacy implications) possibly across the many public instances and if you self host a private instance, you're the only one using it so pretty much pointless.

**Comment by Rik44444** [comment]
thanks, no the logging is not a good idea i agree, i meant pulling the nr of search results from Google etc. When you use "quotation marks" on Google, it does give an accurate result for number of hits, because it then searches for the exact phrase. In my experience it's a good indication of popularity. From your links, i understand that it may be possible to draw in the results from a specific search engine, like Google, right? Perhaps there can be an option in the Searx settings to turn on "indicate nr of search results" and to then be able to choose for which engine you want that displayed, like you can choose which engine you want to use for autocomplete?

**Comment by Snapy** [comment]
> it does give an accurate result for number of hits

Still stays _About_ except if there are very few results (["the brink od extinction"](https://www.google.com/search?q=%22the+brink+of+extinction%22) says About 2,400,000).

Also Google says that half of search queries are zero click (source [1](https://searchengineland.com/49-of-all-google-searches-are-no-click-study-finds-318426) and [2](https://searchengineland.com/now-more-50-of-google-searches-end-without-a-click-to-other-content-study-finds-320574)) and 15% are unique daily ([source](https://www.blog.google/products/search/search-language-understanding-bert/)) down from 25% a decade ago.

Now on the technical side, if you have non compatible search engines enabled you either have a fake number displayed or you have a setting conflict. What would you suggest then from a UI/UX point of view?

**Comment by Rik44444** [comment]
hm OK so it's not that accurate- i'll look into alternatives
i still think there may be value in displaying some sort of volume indicator. eg "no results" can sometimes be really informative. 
re UI/UX i don't think there needs to be a conflict, as long as you mention it, eg "2.000.000 results on ...". Same for autocomplete right, i can select eg a Google autocomplete, even when i don't search using Google?

**Comment by return42** [comment]
>  i can select eg a Google autocomplete, even when i don't search using Google?

right

> hm OK so it's not that accurate- i'll look into alternatives

I will close this issue as long as we do not have a idea of counting results .. if you find a alternative, please ask for reopening or create a new issue / thanks!
