### ISSUE TITLE
CentOS 7 Installation Help

### ISSUE THREAD

**Issue by jeffshead** [searx/searx#1925]
I followed these instructions (https://github.com/asciimoo/searx/wiki/Installation-on-RHEL-7---CentOS-7) but I get a 500 server error. Are those instructions up to date and complete? 

I changed 'disable-logging' to false but I don't see where a log file was created.

Can someone please help me troubleshoot this? I don't know where to begin.

I installed SearX on an pre-existing VPS that already had Apache and let's encrypt with an existing website.

**Comment by return42** [comment]
Hi @jeffshead, the wiki entry is old.  The installation instruction will be completely rewritten in PR #1803.  A **preview** of the documentation is here:

  https://return42.github.io/searx/admin/installation.html

**Comment by return42** [comment]
closed by PR #1803 / see RHEL  at: https://asciimoo.github.io/searx/admin/installation.html
