### ISSUE TITLE
[question] Shall we re-add Findx engine, add Givero or none?

### ISSUE THREAD

**Issue by HLFH** [searx/searx#1927]
Hi,

I quote [Darius on Twitter](https://twitter.com/dwrk76/status/1183343566149554178):

> Findx was rebooted. It's now a proxy search engine using Bing, instead of being it's own, with it's own index. Fun fact.. The exposed IP Will tell you to go to Givero, so...
Findx by Privacore = Givero by Givero ApS

It seems Findx has been removed because it was discontinued at the time: https://github.com/asciimoo/searx/pull/1452

Findx is now a proxy search engine using Bing. It is now also a lightened version of Givero search engine. 

Compare search and layout:

 - https://www.findx.com/search?q=searx
 - https://www.givero.com/search?q=searx

Thanks,
HLFH

**Comment by unixfox** [comment]
Sorry for the late reply to your question, but I personally don't know.

If you think we should add it back then feel free to open an issue as an engine request for that.

**Comment by HLFH** [comment]
@unixfox Ok no problem. Thank you. I have set up a searx private instance. 

There is no need to create an engine request issue. The priority is to get the [checker running within searx](https://github.com/searx/searx/pull/2419), and to test more the current search engines that have been implemented.
