### ISSUE TITLE
Clearing the data

### ISSUE THREAD

**Issue by bluttle** [searx/searx#1928]
Hey guys I want to make a public instance of searx. Now if I dont want the navbar in the page so if I just clear the navbar.html and make it an empty file, will it work. Will this work on preferences.html or should I use transform: scale (0)

**Comment by dalf** [comment]
> Now if I dont want the navbar in the page

May I ask why ?

**Comment by bluttle** [comment]
I like the logicodev theme very much but I dont like the navbar on top of it.

**Comment by return42** [comment]
It seems that you want to change some details we do not support .. I recommend to create a fork of searx and patch like you want .. with you can merge from searx's master branch to get last patches.

update: If yo do so, don't forget to change the [setup (aka brand)](https://asciimoo.github.io/searx/dev/makefile.html?highlight=brand#id6) in the Makefile of your fork.

**Comment by bluttle** [comment]
Any documentation on this ?

**Comment by bluttle** [comment]
Thanks and is there any link to such examples? Like anyone has ever tried

**Comment by return42** [comment]
> Any documentation on this ?

https://help.github.com/en/github/getting-started-with-github/fork-a-repo

>  Like anyone has ever tried

Everyone how sends a PR  has been forked first.

**Comment by bluttle** [comment]
So after I have forked the repository I can do any changes I want? Right
And yes I also need to change the brand.

> Everyone how sends a PR has been forked first

Sorry to say but I couldnt understand your grammar. Could you explain this point

**Comment by return42** [comment]
PR means pull-request .. do you have any experience with git and github? .. if not I am very sorry, I can't teach you all these requirements. 

update: https://help.github.com/en
