### ISSUE TITLE
Just a help

### ISSUE THREAD

**Issue by bluttle** [searx/searx#1929]
So I want to make a pr on searx. As I want to edit it a little. So firstly I should fork searx and them edit it. Will that be enough? Or should I just download the repo and edit it on my PC and upload it to a server

**Comment by unixfox** [comment]
If you want to contribute you should learn how to use Git(hub) before.
Actually GitHub has a bunch of tutorials available on their documentation: https://guides.github.com/activities/hello-world/ and even videos: https://www.youtube.com/githubguides. Watch/Read them then come back contributing to Searx :)
