### ISSUE TITLE
Branding of searx

### ISSUE THREAD

**Issue by bluttle** [searx/searx#1930]
I just have a question
 Why is it important to chamge the branding of searx?

**Comment by return42** [comment]
I close this .. see https://github.com/asciimoo/searx/issues/1929#issuecomment-617257329

**Comment by dalf** [comment]
For now it is not important, at first learn git, github, the different tools as return42 and unixfox have said.

I don't know your background, but if you don't know Python / HTML, there are online tutorial too.
