### ISSUE TITLE
Branding and more

### ISSUE THREAD

**Issue by bluttle** [searx/searx#1931]
I know about github and I have been using it. I asked the person to explain what he said because he used wrong english grammar. How never comes as a 2nd word in a sentence. (I dont aim to hurt anyone so sorry). My question is that why is branding important. And yes I am a dev and I ahve worked with programming before.

**Comment by unixfox** [comment]
Please stop creating new issues for the same subject. If you want to reply to the previous one just reply to it.

**Comment by bluttle** [comment]
I asked the 2nd question to just know the fasteat way. I know what is a fork and what is clone. I have worked with eclipse theia and jet brains intellij IDEA (Community edition) before on github

**Comment by return42** [comment]
https://asciimoo.github.io/searx/dev/makefile.html?highlight=brand#id6

The templates are using this variables.

**Comment by bluttle** [comment]
Thanks now i wont @return42
