### ISSUE TITLE
thepiratebay engine is broken

### ISSUE THREAD

**Issue by unixfox** [searx/searx#1935]
When trying "piratebay" engine on an old version of thepiratebay (because the new version returns no results) I get this parse error:
```
ERROR:searx.search:engine piratebay : exception : list index out of range
Traceback (most recent call last):
  File "/tmp/searx/searx/search.py", line 156, in search_one_http_request_safe
    search_results = search_one_http_request(engine, query, request_params)
  File "/tmp/searx/searx/search.py", line 97, in search_one_http_request
    return engine.response(response)
  File "/tmp/searx/searx/engines/piratebay.py", line 60, in response
    link = result.xpath('.//div[@class="detName"]//a')[0]
IndexError: list index out of range
```

The pirate bay proxy used: https:// pirateproxy dot live (the URL is intentionally broken because I don't want to directly share website with potential "pirated content" on the repository).

**Comment by virtadpt** [comment]
I don't know if it's ever worked.  Not since I've started using it, anyway.

**Comment by unixfox** [comment]
This issue is not really about discussing if it worked in the past but more about fixing the engine :)

**Comment by virtadpt** [comment]
Yes, I get that.  I'm talking about how long it's been broken.
