### ISSUE TITLE
Editing the git source

### ISSUE THREAD

**Issue by bluttle** [searx/searx#1937]
I know that this might not be right but can I just remove the git link in the makefile. Cos i dont want it to link to the searx repo. If not I will make a private repo although :)

**Comment by return42** [comment]
For this you should change the GIT_URL to point to your repository and run:

    make buildenv

this is what we call a _brand_ .. did you got it now?

**Comment by bluttle** [comment]
@return42 no no I meant that can i just remove the option of git repository and make one wuthout any links

**Comment by MarcAbonce** [comment]
That would probably go against the [AGPL license](https://github.com/asciimoo/searx/blob/master/LICENSE), specifically:
> If your software can interact with users remotely through a computer
network, you should also make sure that it provides a way for users to
get its source.  For example, **if your program is a web application, its
interface could display a "Source" link that leads users to an archive
of the code.**

**Comment by bluttle** [comment]
Thanks I never knew about it sorry😊

**Comment by return42** [comment]
> I never knew about it sorryblush

Have you never paid attention to the file named LICENSE? .. can't believe it .. anyway .. now its time to read:

https://github.com/asciimoo/searx/blob/master/LICENSE
