### ISSUE TITLE
socks proxy

### ISSUE THREAD

**Issue by ghost** [searx/searx#1939]
Hello there,

I was just wondering : how can I be sure that all my requests are going through my socks proxy ? I mean I setup a local tor socks and I expected my requests to take far longer to complete. 

Which is why I wanted to know if I can know for sure if all is correctly "proxified".

Thanks btw

**Comment by unixfox** [comment]
Enable the debug in the settings.yml then look for the loading time for each request that searx make.

**Comment by ghost** [comment]
tbh im not sure where I could find such hint : 
https://pastebin.com/HCQ23dtb

**Comment by return42** [comment]
There is something wrong with your installation .. did you see the traceback starting at line 24?

     File "/usr/local/searx/searx/engines/__init__.py"

update: the two different paths are OK  but the traceback itself is not OK

**Comment by unixfox** [comment]
Can this issue be closed?

**Comment by bauruine** [comment]
> how can I be sure that all my requests are going through my socks proxy?

I would recommend to use a iptables rule which only allows the user under which searx runs to connect to the socks proxy. Something like https://www.cyberciti.biz/tips/block-outgoing-network-access-for-a-single-user-from-my-server-using-iptables.html

```
iptables -A OUTPUT -o ethX -m owner --uid-owner {USERNAME} -p tcp --dport {socksport} -j ACCEPT
iptables -A OUTPUT -o ethX -m owner --uid-owner {USERNAME} -j DROP
```
