### ISSUE TITLE
"Rate limit exceeded" on some searx instances with Android webkit browsers

### ISSUE THREAD

**Issue by Rochey** [searx/searx#1940]
I've got an issue with some searx instances, when using my Android phone and a webkit browser e.g. OH Broswer or Naked Browser. 
When I try to search, instead of getting results back I get a webpage with the words "Rate limit exceeded" at the top. If I try the exact same searx instance on my Android phone using Chrome then the search works.
These are the searx instances I'm having issues with:
searx.ninja             0.16.0-63-9a2f26d9
searx.be                0.16.0

I haven't tried them all, these are the ones that I thought would be good to use.
This searx instance does work using a webkit browser:
search.disroot.org  0.16.0

I thought it might be a version issue but as you can see two instances are both running 0.16.0, one that works and one that doesn't. I asked in the OH browser support forum for other users to try and see if it worked on their phones and they told me that they are seeing the same "rate limit exceeded" error.

Does anyone know if this might be a bug?
Or could this be how the website is setup?
Or any idea how to work round the issue?

This should be easy to replicate as I think you only need to install OH browser from the play store and try the instances above.

If you need anything from me to help resolve the issue please let me know.

**Comment by return42** [comment]
If you see this message, the instance is [protected](https://asciimoo.github.io/searx/admin/filtron.html) and your browser is a  _false positive_ match

**Comment by return42** [comment]
Debug the headers your browsers are using and you will see, there is a difference .. I can only guess: may be your OH Browser does not send a `Accept-Language` header?

**Comment by unixfox** [comment]
Thank you for your feedback @Rochey!
This message is displayed by a program (called filtron) which filter bots but unfortunately sometimes there are some false positives and your comment really help finding them.
I just tested Naked Browser and indeed I can replicate the issue. I'm going to investigate what's causing the block and resolve that as soon as possible on searx.be.

**Comment by return42** [comment]
@Rochey I do not have a android at hand .. do you like to test my searx instance http://darmarit.cloud/searx/?q=foo and give me a short feedback / Thanks

**Comment by Rochey** [comment]
@return42 I've just tried several searches from your instance, using both OH browser and Naked Browser and they worked every time. No issue seen there.

**Comment by unixfox** [comment]
I found what's causing the block and I'm going to fix that in around 30 minutes.

**Comment by unixfox** [comment]
I fixed the block on https://searx.be. I just tested on Naked Browser and it works.
Could you please confirm that @Rochey?

**Comment by Rochey** [comment]
@unixfox I've tested 5-10 searches on searx.be and I've had results returned every time, which is awesome! I haven't had any "rate limit exceeded" errors.
What was the issue?
Do we need to let other instance owners know how to fix this issue?

**Comment by return42** [comment]
> I've just tried several searches from your instance, using both OH browser and Naked Browser and they worked every time. No issue seen there.

Thanks a lot .. your feedback helps me a lot .. shows me that my filtron setup ([preview, don't bookmark](https://return42.github.io/searx/utils/filtron.sh.html#filtron-sh)) from #1803 is on a good way .. / thanks!

Is there anything else we can do about your issue? ..

**Comment by unixfox** [comment]
@Rochey Android webkit doesn't support brotli and I opened a PR on the corresponding repository where this rule exist to have a fix for the other search engines: https://github.com/searx/searx-docker/pull/32. If this resolve your issue please close it.

@return42 your rules are too weak, as a searx public instance owner I can assure you that I'll never use them because they don't stop enough bots to maintain a good experience for the real visitors.

**Comment by return42** [comment]
> your rules are too weak, as a searx public instance owner I can assure you that I'll never use them because they don't stop enough bots to maintain a good experience for the real visitors.

No one has to use it. They are better than nothing and should be a first start, improvements are always welcome. I have been using these rules for 3 months and have been quite satisfied with them so far, but I also know: my searx-instance is not representative. That's why I would be happy if we could improve the filtron rules after a merge of PR #1803.

**Comment by unixfox** [comment]
@return42 I think you can close this issue because first it's not related to the actual source code of Searx and secondly I opened a PR on the corresponding repository in order to fix the issue.

**Comment by Rochey** [comment]
I'm happy to close this now you guys know what the issue is and how to resolve it. 
Super quick resolution! Awesome work!
Thank you

**Comment by return42** [comment]
@Rochey thanks!
