### ISSUE TITLE
Add support go-cyber

### ISSUE THREAD

**Issue by ghost** [searx/searx#1945]
https://github.com/cybercongress/go-cyber#why https://github.com/cybercongress/go-cyber/issues/505
```
https://ipfs.io/ipfs/QmceNpj6HfS81PcCaQXrFMQf7LR5FTLkdG9sbSRNy3UXoZ
```

**Comment by return42** [comment]
Thanks for your hint.  Do you know more about this project and how we can make use of? .. If I try their search page I only get a black screen.

**Comment by ghost** [comment]
@return42 i don't know, just test it `https://cyber.page/search/test`

**Comment by return42** [comment]
OK, I'm closing this issue because there's no concept / anyway, thanks for your hint!

If there comes the day one have a concept we can reopen this issue.

> i don't know, just test it https://cyber.page/search/test

This is what I mean, I have opened their page and only get a black screen .. also tested with tor browser ..

**Comment by serejandmyself** [comment]
Hey @return42 

You can find the docs here: https://cyber.page/brain/docs

The thing is, cyber.page is an app, not a website. You may find usability guides here: https://github.com/cybercongress/congress/blob/master/ecosystem/Cyber%20Homestead%20doc.md#using-cyber-the-very-basics-of-becoming-a-master

And the FAQ of the project, that explains how it works here: https://github.com/cybercongress/congress/blob/master/ecosystem/ELI-5%20FAQ.md

**Comment by serejandmyself** [comment]
The FAQ also explains the concept in simple terms

**Comment by serejandmyself** [comment]
Thanks for pointing this @KonoromiHimaries

**Comment by return42** [comment]
@serejandmyself thanks for your hints ..

> The thing is, cyber.page is an app, not a website.

OK, that's why I cant open the `https://cyber.page` ..  

> And the FAQ of the project, that explains how it works here ..

Thanks, my question about a concept is more: _.. and how can the meta search engine searx participate from?_

**Comment by serejandmyself** [comment]
@return42 you should be able to open it easily. Can you please let me know what browser / device you are using? (Currently, we have trouble with Safari and some of the smaller browsers)

That is a good question! TBH, I only found out about searx a few hours ago. Let me please take some time to have a look into what you guys do and see if I have an answer for you!

**Comment by return42** [comment]
> @return42 you should be able to open it easily. 

I am using up-to-date FFox. In the console I see the message:

    Error: no WebRTC support

**Comment by unixfox** [comment]
> > @return42 you should be able to open it easily.
> 
> I am using up-to-date FFox. In the console I see the message:
> 
> ```
> Error: no WebRTC support
> ```

The page is working for me (Firefox stable 76) so you probably have disabled WebRTC using an extension or through `about:config` page.
You may test on this page if WebRTC works for you: https://test.webrtc.org

**Comment by return42** [comment]
> so you probably have disabled WebRTC 

correct! ..like many other stuff I don't want to use, when visiting _normal_ WEB sites.

I don't want to be a part of a network, I just wanted to read some descriptions about; what this network is and how we can make use of.

**Comment by unixfox** [comment]
> > so you probably have disabled WebRTC
> 
> correct! ..like many other stuff I don't want to use, when visiting _normal_ WEB sites.
> 
> I don't want to be a part of a network, I just wanted to read some descriptions about; what this network is and how we can make use of.

Might have been better to include that in your previous message instead of blaming the author of the website by saying "up-to-date Firefox"...

Even if it's kinda off-topic: WebRTC is not a bad technology, projects like [Jitsi](https://github.com/jitsi/jitsi-meet/blob/master/README.md) allows using WebRTC in order to secure (end-to-end encryption) our video conferences instead of using a bad app like [Zoom that send data to China](https://www.businessinsider.com/china-zoom-data-2020-4).

Anyway, I don't see why the hate about WebRTC... just remember to [disable the component that leaks your private & public IP address](https://addons.mozilla.org/en-US/firefox/addon/webrtc-leak-shield/) (or check `Prevent WebRTC from leaking local IP addresses` in the settings of Ublock origin) and that's it.

**Comment by return42** [comment]
> blaming the author of the website by saying "up-to-date Firefox"...

Thanks for your hints & links, very helpful .. and sorry for my misleading words: was not about blame someone or a technology ..

Its my first time, I visit a WEB page where WebRTC is needed.  Its very uncommon for me .. and I don't want to change my setup just to read something about a network and how I can participate from.  _"Cyber is a decentralized google."_ sounds interesting for me and I think, its not only me, stopping at this point.

Anyway, my question is:

>> Thanks, my question about a concept is more: .. and how can the meta search engine searx participate from?

and the answer until now was ...

> That is a good question! 

:)

**Comment by serejandmyself** [comment]
Yes. Sorry. It took me time to research what searx does...

So, here is what we do in a gist: the idea of cyber is to rebuild the semantics core of the internet using blockchain, cyberlinks (our simple semantics construction between 2 content addresses IDs, where 1 is the content, and the other is a search word) and other technology. 

Basically what we do (or rather what the users do) is creating a decentralized knowledge graph which is computed by validators under a certain consensus (you can partially imagine a WIki with no censorship and a lot more functions). All of the content is ranked in pretty much life-time, using Merkle trees. 

Right now we use IPFS as the protocol which allows us to implement such mechanics (the above is a very high-level description), however, we can use any stateless or stateful protocol (dat, git, bitcoin, ethereum, etc). The interesting thins is that by opening up the semantics core with blockchain, economic incentives and by adding sybil resistance, we create numerous use-cases (but not about them now).

All of this means that on one hand cyber doesn't track you, however, the transactions are not anonymous. They are pseudo-anonymous, just like in BTC. Meaning that hashes of everything get written down to a DB, which is, in this case, a public blockchain. With cyber users actually fully control their data and fully control the mechanics of the semantics core. This means that in comparison to other search engines, there are no intermediary opinions. What is created in the core, is subjectively relevant to the users and is provable in terms of that core (Merkle trees). Users may, of course, create personal knowledge graphs. After all, there can be more than one graph, I presume even closed graphs that can still interact with the public once while keeping to the consensus rules.

How can searx take advantage? Well for one, if it adds support to cyber, it means that it will be able to find info that isn't traceable and is user-driven. I.E. what is in cyber isn't traced.

For two, I guess the 2 are very separate things. One is a web2 architectured search engine, still build on the same architecture and principles as the rest of the web (not a bad thing, it's just is). The other is build with a completely different, experimental(!!!), principle (which is still to be proven by time to be a working idea). It is rather hard to see how they can be connected. Other than the first point. But that would require some kind of gateway to interact with I assume. Cyber works in web3 paradigm. The idea of content ranging, indexing, etc is entirely different to what a conventional search engine does (yet, at its core, it does the same trick, just tries to perform this in a decentralised manner). 

I would strongly suggest to check out this [descritpion of what cyber is](https://github.com/cybercongress/congress/blob/master/ecosystem/ELI-5%20FAQ.md#what-is-cyber), not as educational material, yet out of curiosity to how it works. 

Back to how we can connect them. I can only see one option, that is described above, yet I might be wrong. I would be glad for any feedback, comments, general ideas (with regards or regardless to the above-mentioned topic). 

PS. @unixfox yes, thank you, you are absolutely correct there. We will try to implement something like npjms (detectRTC) and if webRTC is disabled not to turn on the node. Should do the trick. Thanks!
