### ISSUE TITLE
(Request) Add cliqz.com as a Search Engine

### ISSUE THREAD

**Issue by allendema** [searx/searx#1946]
This engine is in evelopment but it gives very fast results,
but their site connects to trackers and, if searched for images - to 3rd party domains.
So, it would be good to have it as a search option in Searx.

**Comment by return42** [comment]
[Dear Cliqz friends, on April 29, 2020 we’ve announced with a heavy heart the Cliqz story is over.](https://cliqz.com/en/magazine/farewell-from-cliqz) .. _"SAD!"_
