### ISSUE TITLE
Save settings button does not redirect

### ISSUE THREAD

**Issue by lou-bi** [searx/searx#1952]
This is a trivial issue, but the button "save settings" does not redirect to main page on Chrome and Brave (chromium based browser I suppose ?) while it does on Firefox.
![image](https://user-images.githubusercontent.com/29218400/81868660-fb1ccb00-9572-11ea-8aa8-21ec479b3c13.png)
It does not seems to be related to settings as just clicking on it while not changing anything will do it anyway.

**Comment by unixfox** [comment]
It's a specific issue with the instance that you are using and not an issue with Searx itself. It's due to a misconfiguration of the Content Security Policy on the server.
For example on my instance I can't replace the bug : https://searx.be

**Comment by lou-bi** [comment]
Oh ok ! Can i do something in the repo to help or is it an issue of the server hosting the instance ?

**Comment by return42** [comment]
hi @bnlo 

> Oh ok ! Can i do something in the repo to help or is it an issue of the server hosting the instance ?

no, as @unixfox already said ..

> It's a specific issue with the instance that you are using and not an issue with Searx itself. It's due to a misconfiguration of the Content Security Policy on the server.

@unixfox : are you sure it's CSP .. what me irritates: The form from HTTPS sends to HTTP: 

    Refused to send form data to 'http://searx.pofilo.fr/'

**Comment by unixfox** [comment]
> @unixfox : are you sure it's CSP .. what me irritates: The form from HTTPS sends to HTTP:
> 
> ```
> Refused to send form data to 'http://searx.pofilo.fr/' 
> ```

I was on the phone when I read the issue, so I didn't take attention to the error CSP message itself. You are right, it's not a CSP misconfiguration but a misconfiguration of Searx because it thinks that the links are in plain HTTP.

----------------------------

> Oh ok ! Can i do something in the repo to help or is it an issue of the server hosting the instance ?

Not really. If you plan to use this Searx instance then you will have to wait until @Pofilo fixes the issue on his instance.
Meanwhile, you can safely close this issue.

**Comment by Pofilo** [comment]
@bnlo I'll take a look on that this weekend.
In the meantime, you can use another instance: https://searx.space/
