### ISSUE TITLE
Pix-art is broken

### ISSUE THREAD

**Issue by lou-bi** [searx/searx#1953]
# Results are not displayed
![image](https://user-images.githubusercontent.com/29218400/81867575-33bba500-9571-11ea-9ba5-a72224e4a5f5.png)
# Results are slow
## With pix-art
![image](https://user-images.githubusercontent.com/29218400/81867843-a0cf3a80-9571-11ea-866a-2d0f318af9dd.png)
## With oscar:
![image](https://user-images.githubusercontent.com/29218400/81868045-f4418880-9571-11ea-9678-31cf014fd535.png)

Plus, looking at the results in the dom, they seems to be different between pix-art and oscar. Is that normal ?

**Comment by unixfox** [comment]
This one I'm able to replicate it on another Searx instances.
I haven't test it on a local instance though.

**Comment by allendema** [comment]
This theme is nowdays removed by default.
