### ISSUE TITLE
(Request) Add whaleslide.com as a Search Engine

### ISSUE THREAD

**Issue by K-mikaZ** [searx/searx#1955]
### Request structure:
`https://whaleslide.com/search/web/{query}?p={pageno}`
### Language support too.
Example in FR ( yes, I am french ^^ ):
`https://whaleslide.com/search/web/{query}?p={pageno}&locale=fr-FR`
### Example in practice:
[https://whaleslide.com/search/web/searx?p=1&locale=en-US](https://whaleslide.com/search/web/searx?p=1&locale=en-US)
### Support also for secure search parameters on the search page 'TOOLS option' (but I did not find how to include it in command line)

**Comment by K-mikaZ** [comment]
### It's appears they have an api...
... where secure search, time and the number of pages can also be configured.
From `chrome > console > network`
Request URL: `https://search.whaleslide.com/api/v1/quicksearch_v2/web/?q=searx&num=10&api_token=f8OhUDEYKUICHDnIxEgI7Cb4uYyTBqT4nO8iueNbfTO3devS24yElGqM7nCm&&filter[safe_search]=off&filter[freshness]=day&filter[locale]=fr-FR`
### Maybe it works like this?
[https://whaleslide.com/search/web/searx?p=1&num=10&locale=fr-FR&safe_search=off&time=day](https://whaleslide.com/search/web/searx?p=1&num=10&locale=fr-FR&safe_search=off&time=day)

**Comment by allendema** [comment]
Here is my try of the autocompleter, which works fine.

```bash

#!/usr/bin/python3


from json import loads
import requests

query = "what"


headers = {
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'de-DE,en-US;q=0.5',
    'Accept': "application/json, text/plain, */*",
	'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0',
}


# whaleslide.com autocompleter

# There is an option for an API Key or sorting by freshness or locale
# Retuns max 10 suggestions in JSON

url = "https://search.whaleslide.com/api/v1/suggestions/get?q=" + query + "&num=5"

print(url)

r = requests.get(url, headers=headers)

print(r.status_code)


data = loads(r.text)

for i in data:
	print(i)

```

**Comment by allendema** [comment]
The results are also working, just need some adjusting to make it like other engines, 
and somehow edit out the <b> Tags.

```bash

#!/usr/bin/python3


from json import loads
import requests

query = "what"


headers = {
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'de-DE,en-US;q=0.5',
    'Accept': "application/json, text/plain, */*",
	'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0',
}


# whaleslide.com JSON engine with API Key
	
url = "https://search.whaleslide.com/api/v1/quicksearch_v2/web/?q=" + query + "&api_token=f8OhUDEYKUICHDnIxEgI7Cb4uYyTBqT4nO8iueNbfTO3devS24yElGqM7nCm"


r = requests.get(url, headers=headers)

print(r.status_code)


data = loads(r.text)

# Print the URL and Abstract of results

for i in data["results"]["web"]:
	print(f' \n {i["url"]} \n {i["abstract"]}')
```

**Comment by allendema** [comment]
Added this to ``` searx/settings.yml ```
It works.

The downside is that it cannot do paging.

```bash
  - name : whaleslide
    shortcut : whale
    engine : json_engine
    search_url : https://search.whaleslide.com/api/v1/quicksearch_v2/web/?q={query}&api_token=f8OhUDEYKUICHDnIxEgI7Cb4uYyTBqT4nO8iueNbfTO3devS24yElGqM7nCm
    url_query : url
    title_query : title
    content_query : abstract
    categories : general
    disabled : False
    about:
      website: https://whaleslide.com/
      wikidata_id: #
      official_api_documentation: false
      use_official_api: false
      require_api_key: false
      results: JSON
```
