### ISSUE TITLE
FIX search engine Gigablast exception : extra param expired, please reload (and requests for some extras)

### ISSUE THREAD

**Issue by K-mikaZ** [searx/searx#1960]
#### Replace:
```
def parse_extra_param(text):
    global extra_param
    param_lines = [x for x in text.splitlines() if x.startswith('var url=') or x.startswith('url=url+')]
```
and `&langcountry={lang}`

#### With:
```
def parse_extra_param(text):
    global extra_param
    param_lines = [x for x in text.splitlines() if x.startswith('var uxrl=') or x.startswith('uxrl=uxrl+')]
```
and `&qlangcountry={lang}`
#### According from: [view-source:https://www.gigablast.com/search?c=main&q=searx&qlangcountry=en-us](view-source:https://www.gigablast.com/search?c=main&q=searx&qlangcountry=en-us)
```
var uxrl='/search?c=main&q=searx&qlangcountry=en-us&rand=1589813557381&u';
uxrl=uxrl+'nch=3181505909';
client.open('GET', uxrl );
client.send();
```

### A question: is this setting useful ?
`&n={number_of_results}` => the default is 25 why don't let `&n=25`

> In my case when `& n = {number_of_results}` is set, I have no results from Gigablast.
> And when I delete it, Gigablast provides me with results.
> 

#### For localization improvement:
`&qlangcountry: xx-zz` => any contry
`&onlylang: fr` => All documents returned will be in this language.
#### Others (for results improvement):
`&hacr=1` => Only display at most one result per site.
`&dr=1` => Should similar search results be removed?

**Comment by unixfox** [comment]
Feel free to open a PR for that.

**Comment by K-mikaZ** [comment]
> Feel free to open a PR for that.

I wish I could, but I don't know how to do that.

**Comment by K-mikaZ** [comment]
> > Feel free to open a PR for that.
> 
> I wish I could, but I don't know how to do that.

Ok I found and I did it.

**Comment by return42** [comment]
FYI: PR #1974 is a revise of the gigablast engine
