### ISSUE TITLE
Google News is broken on my instance

### ISSUE THREAD

**Issue by TheFrenchGhosty** [searx/searx#1968]
Google News is the only source of news on my instance (by default), however someone noticed that it was always reporting that it didn't find any result ( Sorry! we didn't find any results. Please use another query or search in more categories. ).

I checked and the server isn't blocked from accessing Google News (and SearX seems okay with that since it's not reporting that it's blocked).

The user that reported me the issue tried a search on Google News via SearX using a localhost instance and it worked.

I have absolutely no idea what could be the issue.

Running 0.16.0

Config file: https://github.com/TheFrenchGhosty/PussTheCat.org-Configs/blob/master/Services/SearX/settings.yml

Instance here: https://searx.pussthecat.org/

**Comment by unixfox** [comment]
How did you test that your instance can access to Google News?

There is a high probability that you can't access to Google News because your instance is blocked by Google:
![image](https://user-images.githubusercontent.com/4016501/82760861-e0a1e780-9de5-11ea-8f96-720966b86b39.png)

**Comment by TheFrenchGhosty** [comment]
I opened a browser on Google News and made a search.

**Comment by unixfox** [comment]
Try to do it with curl with HTTP1 because your browser uses HTTP2 and Searx use HTTP1. For an unknown reason Google only blocks on a specific HTTP protocol and not the other one.

**Comment by TheFrenchGhosty** [comment]
I did curl what I think is what's sent when doing a search:


The last one:

![screenshot](https://user-images.githubusercontent.com/47571719/82761458-2eb8ea00-9dea-11ea-9d8f-a231278c9d90.png)

This is the output, is that right? If not what should I curl?

```
)]}'

103
[["er",null,null,null,null,405,null,null,null,9]
,["di",7]
,["af.httprm",6,"7815171960837680298",5]
]
26
[["e",4,null,null,140]
]
```

**Comment by unixfox** [comment]
Searx use the HTML so you have to curl the page.
Also use `curl --http1.1`

**Comment by TheFrenchGhosty** [comment]
I do use ```curl --http1.1``` 

>Searx use the HTML so you have to curl the page.

Which page?

**Comment by unixfox** [comment]
Here is an example: `curl --http1.1 -A "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0" "https://www.google.com/search?q=ok&tbm=nws"`

**Comment by TheFrenchGhosty** [comment]
Oh, so you don't want a curl on a news specific url?

```
$ curl --http1.1 -A "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0" "https://www.google.com/search?q=ok&tbm=nws"
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dok%26tbm%3Dnws&amp;q=[REDACTED]">here</A>.
</BODY></HTML>
```

```
$ curl --http1.1 -A "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0" "https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dok&amp;q=[REDACTED]"
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://www.google.com/search?q=ok</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<div style="font-size:13px;">
Our systems have detected unusual traffic from your computer network.  Please try your request again later.  <a href="#" onclick="document.getElementById('infoDiv0').style.display='block';">Why did this happen?</a><br><br>
<div id="infoDiv0" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may see this page if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div><br>
</div>
</div>
</body>
</html>
```

**Comment by unixfox** [comment]
I was right, your instance is blocked by Google. That's why you don't see any results on Searx when choosing Google News as an engine.

**Comment by TheFrenchGhosty** [comment]
Google News block are the same a Google itself?

**Comment by unixfox** [comment]
Yes because it's under the same "Google Search interface".

**Comment by TheFrenchGhosty** [comment]
Good to know thanks.

Closing I guess.
