### ISSUE TITLE
the search filters need improvement

### ISSUE THREAD

**Issue by aleex5** [searx/searx#1969]
the search filters need improvement, they are somewhat useless, you should separate the language and country filter, the languages filter needs improvement, because a language salad appears in the searches and it is as if the filter really does not exist
the search filter by date, most of the time it does not give results

**Comment by return42** [comment]
Searx is a metasearch engine, filters are passed through to the origin search engines like goolge and others.

Most of the search engines do not support, all filters.  However, it may also be that some of our adapters have errors or the searx instance is not up to date.

To improve the adapters we need to know what engines you test and which instance you are using.

**Comment by return42** [comment]
I close this issue due to inactivity .. ask for reopen if you have more details for us / thanks!
