### ISSUE TITLE
Requests does not follow on an HTTP 301

### ISSUE THREAD

**Issue by Cqoicebordel** [searx/searx#197]
We had already an issue when kickass redirected from https to http I seem to remember. Or it was on another engine. And the request wasn't followed so we had an empty response with status_code 301 in the engine.

Anyway, that is still the case in kickass if we try to perform a search when the query contains capitalized letters.

So why isn't 301 followed ? Is there a way to force it ?

**Comment by dalf** [comment]
Seems strange since it was the case for the google engine : #193
There is an allow_redirects parameter for the Requests

**Comment by Cqoicebordel** [comment]
Yes, I know, and it is set at True (it is set in poolrequest). But in some cases, it doesn't follow.

**Comment by asciimoo** [comment]
@Cqoicebordel could you show a reproducable example?

**Comment by Cqoicebordel** [comment]
Works : http://searx.me/?q=%21ka+22+jump+street&category_general=on
Doesn't work : http://searx.me/?q=%21ka+22+Jump+street&category_general=on

The only difference is the capitalized J.
Kickass tolower() it to put it in URL. And so, does a redirection in the second case, returning a 301 that is not followed.

**Comment by asciimoo** [comment]
seems, it's fixed, thanks @pointhi =)

**Comment by Cqoicebordel** [comment]
Uh ? Where ?

**Comment by asciimoo** [comment]
ah, right, it isn't..

**Comment by Cqoicebordel** [comment]
This issue wasn't Kickass specific, so I don't think it should be closed until there is actually the wrapper.

(Unless you plan to do the wrapper shortly. I just don't want us to forget about this issue)
