### ISSUE TITLE
SUGGESTION: Contacting the instance's maintainer(s)

### ISSUE THREAD

**Issue by TheEvilSkeleton** [searx/searx#1972]
Hello, so I use searx, but I personally think that there should be any way to contact the maintainer(s) of a public instance (email for example). It is harder to trust this awesome service if there is no way to contact the maintainer(s).

**Comment by return42** [comment]
> It is harder to trust this awesome service if there is no way to contact the maintainer(s).

I see it the same way, but unfortunately we cannot force our users to do so.

The public instances are managed in the https://github.com/dalf/searx-instances project, one option would only be to register instances that also give an indication of the operator.

May you like to move this issue to https://github.com/dalf/searx-instances ? / Thanks!

**Comment by SamantazFox** [comment]
Maybe an optional config that allow the maintainer to give an email address or a place for contacting them ? And when this config is set, a "contact" link is added in the footer.

**Comment by TheEvilSkeleton** [comment]
> > It is harder to trust this awesome service if there is no way to contact the maintainer(s).
> 
> I see it the same way, but unfortunately we cannot force our users to do so.
> 
> The public instances are managed in the https://github.com/dalf/searx-instances project, one option would only be to register instances that also give an indication of the operator.
> 
> May you like to move this issue to https://github.com/dalf/searx-instances ? / Thanks!

Just did, thank you

**Comment by TheEvilSkeleton** [comment]
> Maybe an optional config that allow the maintainer to give an email address or a place for contacting them ? And when this config is set, a "contact" link is added in the footer.

yeah, I like this idea, but I would personally prefer it to be obligated so there is *at least* one way to contact them

**Comment by unixfox** [comment]
That's a good idea.
The ability to add an address email to the `settings.yml` so that it gets displayed on Searx.

**Comment by TheEvilSkeleton** [comment]
I'm glad you guys liked it

**Comment by return42** [comment]
FYI: I left this issue open as ["enhancement"](https://github.com/asciimoo/searx/issues/1972#issuecomment-634718073)

**Comment by TheEvilSkeleton** [comment]
> > It is harder to trust this awesome service if there is no way to contact the maintainer(s).
> 
> I see it the same way, but unfortunately we cannot force our users to do so.
> 
> The public instances are managed in the https://github.com/dalf/searx-instances project, one option would only be to register instances that also give an indication of the operator.
> 
> May you like to move this issue to https://github.com/dalf/searx-instances ? / Thanks!

btw, in case you weren't aware, it is possible to do it yourself: https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

**Comment by TheEvilSkeleton** [comment]
...hello?
