### ISSUE TITLE
Google results not available?

### ISSUE THREAD

**Issue by nezia1** [searx/searx#1975]
So I set up a new Searx instance on my DigitalOcean droplet, and I noticed that I can't toggle some search engines regardless of the language I use because it tells me that the language is not supported. Am I doing something wrong or is it an actual issue with searx?

[Screenshot](https://i.imgur.com/rQW9PNb.png)

**Comment by return42** [comment]
Some engines (i.e. the xpath adapters) do not support languages.

>  noticed that I can't toggle some search engines

really? .. activate engines is not related to languages.  Did you disabled JS?

**Comment by nezia1** [comment]
I don't think I did. I still have the default settings, but I can't seem to toggle Google for instance.

**Comment by return42** [comment]
Is the instance public? .. could you give me a link?

**Comment by nezia1** [comment]
It is public. http://134.209.17.119:8888

**Comment by return42** [comment]
Works like a charm ;) Just click on the button (no slice) .. does it help?

**Comment by nezia1** [comment]
What button do you mean?

**Comment by return42** [comment]
Do I misunderstood you?  You asked:

> I noticed that I can't toggle some search engines

I thought you mean, you can not active/deactivate a engine in the preferences .. I am wrong?

**Comment by nezia1** [comment]
I can active them, but the results don't show up when i search something using those search engines.

**Comment by return42** [comment]
Ah, OK .. sorry for the confusion .. if you want to test a engine explicit, you can use  "!" notation / e.g for google use [!go foo](http://134.209.17.119:8888/?q=%21go%20foo&categories=none&language=en-US)   ([see search syntax](https://asciimoo.github.io/searx/user/search_syntax.html)).

>  but the results don't show up when i search something

Enable debug in the settings and restart to see whats going wrong. May you are blocked by google [captcha](https://github.com/asciimoo/searx/search?q=captcha&type=Issues) / other engines are OK (e.g. yahoo: [!yh foo](http://134.209.17.119:8888/?q=%21yh%20foo&categories=none&language=en-US))

**Comment by nezia1** [comment]
It might actually be because my instance is not https.

**Comment by return42** [comment]
No.

**Comment by nezia1** [comment]
I can't find the debug setting for some reason?

**Comment by return42** [comment]
Mostly a view into the docs helps: https://asciimoo.github.io/searx/admin/settings.html

**Comment by nezia1** [comment]
Thanks, I'm gonna check what's happening and I'll come back with details.
