### ISSUE TITLE
[QUESTION]What instance do you guys like?

### ISSUE THREAD

**Issue by daemonspudguy** [searx/searx#1977]
There are many different instances of searx. Which instance do you guys recommend?

**Comment by return42** [comment]
Can't speak for others, but I prefer my own ;) [searx-next branch](https://github.com/return42/searx/tree/searx-next)

- [searx-next instance](https://darmarit.org/searx)
- [searx-next docs](https://return42.github.io/searx/)
- [searx-next merged PRs](https://github.com/return42/searx/projects/1)

**Comment by unixfox** [comment]
Personally I prefer my own instance: https://searx.be.

It has Google, Bing, Duckduckgo and yahoo results working everytime compared to others instances because the requests get rotated through multiple proxies in order to avoid being blocked by these search engines.

Moreover, recently I fixed the torrentz2 engine on my instance and it's the only searx instance that has it working because I have a program that "bypass" the cloudflare anti bot.

Finally, my instance is almost never down because it is replicated on multiple Linux servers and I get notified if it gets down. I really care about my visitors.

Sorry if you didn't want a self promoting comment :smiley:.

**Comment by return42** [comment]
> Moreover, recently I fixed the torrentz2 engine on my instance and it's the only searx instance that has it working because I have a program that "bypass" the cloudflare anti bot.

Sorry for being OT: can you give me some links about / Thanks!

**Comment by unixfox** [comment]
> > Moreover, recently I fixed the torrentz2 engine on my instance and it's the only searx instance that has it working because I have a program that "bypass" the cloudflare anti bot.
> 
> Sorry for being OT: can you give me some links about / Thanks!

I created a program for that: https://github.com/unixfox/pupflare and after that I just changed the URL in the torrentz2 engine from `https://torrentz2.eu` to `http://localhost:3000/?url=https://torrentz2.eu`.

**Comment by daemonspudguy** [comment]
@unixfox Your instance has a Belgian tld but has an Italian IP address. What's all that about? Also, Bonjour/Goedendag!

**Comment by unixfox** [comment]
> @unixfox Your instance has a Belgian tld but has an Italian IP address. What's all that about? Also, Bonjour/Goedendag!

Bonsoir :smiley:.

Just because my instance has a Belgian TLD doesn't mean that I need to host it on a server in Belgium :smiley:.
I'm Belgian but I chose to host it in Italy because I picked a good VPS offer from a Italian provider.

**Comment by daemonspudguy** [comment]
I like your instance Mr. unixfox. Although I'm curious where in Belgium you're from? Either Waloonia or Brussels.

**Comment by unixfox** [comment]
> I like your instance Mr. unixfox.

Thank you I appreciate your feedback!

> Although I'm curious where in Belgium you're from? Either Waloonia or Brussels.

I'm from Wallonia. You are also Belgian?

-----------------

I love how this issue is going in so many off topics :smile:.

**Comment by daemonspudguy** [comment]
No. I'm from the US state of Ohio. I just really like the recent history of the various European nations and the way they function. (or sometimes don't, like the Belgian constitutional crisis a few years back)

**Comment by gkaklas** [comment]
Hi @daemonspudguy! :smile: Has your question has been answered, can you close this issue?

**Comment by daemonspudguy** [comment]
Yes!
