### ISSUE TITLE
bing_news can't parse other languages date

### ISSUE THREAD

**Issue by Cqoicebordel** [searx/searx#198]
When searching for french article, the time is noted as "Il y a 5 minutes", and so, doesn't match for the regex `"^[0-9]+ minute(s|) ago$"`.

Do you see a way to internationalize this detection ?

**Comment by pointhi** [comment]
probably `"^.*[0-9]+\s*minute(s|).*$"`?

**Comment by Cqoicebordel** [comment]
It won't work in russian or every other languages...

**Comment by pointhi** [comment]
I think there is only the possibility of adding a dictionary, because otherwise we couldn't differ between minutes and hours, if the number is to low (<24)

**Comment by Cqoicebordel** [comment]
I agree with you.
I just hoped there was a python librairy I didn't know about that could do that ;)

**Comment by pointhi** [comment]
one other (stupid) idea:

we know that hours can only be displayed between 0-23, so numbers above that are automatic minutes. If we parse all dateobjects, from a site, it should be possible to find the exact phrase, in which minutes/hours are displayed, as long one value is above 23. :)

**Comment by Cqoicebordel** [comment]
I like that !
But wait, there are days too...

But it may be not so stupid.
Or maybe, there is a way to have the bing interface in english while the results are in any other language...
