### ISSUE TITLE
Results page: having text cursor still in search field is annoying

### ISSUE THREAD

**Issue by DNied** [searx/searx#1984]
If the search field is focussed (active) in the results page, any attempt to scroll down one page using the spacebar results in typing a space in the search field instead. None of the other search engines I use do that, and it's rather counter-intuitive.

**Comment by return42** [comment]
Use [TAB] to leave the autofocus  / further read: https://github.com/asciimoo/searx/pull/1971

Do you know a better solution for the concurrency of "autofocus" and "scroll" we can implement?

**Comment by DNied** [comment]
Yes: have the search field auto-focussed in the home page, but not in the results page. That seems to be what the other search engines do.

**Comment by return42** [comment]
This is what we had before #1971 / me and some other prefer not to have a mouse click while the hands are on the keyboard. The workaround for "scroll" is to use the [TAB] once before scrolling.

**Comment by DNied** [comment]
What mouse click? I honestly don't get what you are saying...

**Comment by return42** [comment]
> What mouse click? I honestly don't get what you are saying...

When you are on the result page .. how do you enter a new search term?

Test it here: https://darmarit.org/searx/?q=foo&categories=general&language=en-US

**Comment by DNied** [comment]
Usually, when I'm on the results page, the first thing I want to do is read the results -- not add a new search term right away (that's for later, maybe).

**Comment by return42** [comment]
> usually

.. is different for all of us, why should we prefer your workflow beyond others?

**Comment by patosullivan** [comment]
I don't see why searx should use a different convention than every other search engine for this. It's very annoying.

**Comment by heyitscassio** [comment]
> I don't see why searx should use a different convention than every other search engine for this. It's very annoying.

+1, I find this really annoying, this should have a option to toggle this behaviour.
