### ISSUE TITLE
(question) requests vs urllib3 - speed of execution.

### ISSUE THREAD

**Issue by K-mikaZ** [searx/searx#1988]
My question is related to the speed of execution.
In requirements, you use `requests[socks]`.
Why not use `urllib3[socks]` ([https://urllib3.readthedocs.io/en/latest/advanced-usage.html#proxies](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#proxies)) ?
`urllib3` is faster than `urllib.request` which itself is faster than `requests`, I am wrong?

**Comment by return42** [comment]
Can't say anything about performance, but [requests](https://github.com/psf/requests/) is build up on [urllib3](https://github.com/psf/requests/blob/master/setup.py#L47)
