### ISSUE TITLE
Typo in the website

### ISSUE THREAD

**Issue by B0pol** [searx/searx#1989]
https://github.com/asciimoo/searx/blob/gh-pages/admin/settings.html#L123
https://github.com/asciimoo/searx/blob/gh-pages/_sources/admin/settings.rst.txt (search for default_locale, second occurrence).

It's written Aearx instead of Searx.

**Comment by unixfox** [comment]
Feel free to open a pull request for that :).

**Comment by B0pol** [comment]
I don't know which one to edit: rst, html or both files.
I don't know either how to build the website and see changes locally.

Therefore I opened this issue because I don't know how to fix.
Such information should be mentioned in README or CONTRIBUTING somewhere (master or gh-pages branch, I don't know).

**Comment by return42** [comment]
Sending PRs would be great, but open issues is also OK. If you are interested in; we have a [reST primer](https://asciimoo.github.io/searx/dev/reST.html) and a [live build](https://asciimoo.github.io/searx/dev/contribution_guide.html#documentation).

**Comment by unixfox** [comment]
This issue was fixed in https://github.com/asciimoo/searx/commit/3fe78c64c6eade9a6f24c87ff411f598c6922dac
@dalf or @return42 you can close this issue :)
