### ISSUE TITLE
Inaccurate statistics

### ISSUE THREAD

**Issue by dalf** [searx/searx#199]
the /stats URL shows different numbers when the page is refreshed.

Explanation (I guess) : the statistics are calculated per process (with uwsgi at least).

It's not a big issue except (perhaps ?) for the error counts.

**Comment by pointhi** [comment]
I think we can fix that if we are using a database instead local variables to store the stats.

Furthermore, a restarted searx-engine can build on the previous data like `score`.

**Comment by asciimoo** [comment]
Collect stats related improvements/ideas to #162
