### ISSUE TITLE
Change about.html

### ISSUE THREAD

**Issue by jesperh1** [searx/searx#1994]
Hi, i was gonna change the about page on my instance, to include contact information, and i have change ```/searx/templates/__common/about.html``` but to no effect.

What would be the right file to change?

**Comment by return42** [comment]
What we support is:

In your branch, change environment variables to your needs [see Setup (brand)](https://asciimoo.github.io/searx/dev/makefile.html#setup) and run the make targets

````sh
$ make buildenv
$ make themes
````
