### ISSUE TITLE
Library Genesis links shifted by 1

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#1998]
- Search for e. g. "!lg albert einstein" (search language Deutsch- Deutschland, every time)
- list shows: 
  - Einsteins miraculous year (link http://bookfi.net/)
  - Grundzuege der Relativitaetstheorie (link http://bookfi.net/md5/215C8AFD90F104B04F32E75CE5CC02F9)
  - Relativity: the special and general theory (link http://bookfi.net/md5/68070CD9CA89403379544EA6549E89BF)
- click on first entry (miraculous year): no entry occurs
- click on second entry (Grundzuege): Einsteins miraculous year appears
- click on third entry (Relativity): Grundzuege is shown.

**Comment by unixfox** [comment]
Please be more descriptive in your issue. Why is it an issue to have the links shifted by 1?

**Comment by linuxmue** [comment]
I've debugged the issue and found a fix:

In /etc/searx/settings.yml
replace
  - name : library genesis
    engine : xpath
    search_url : http://libgen.rs/search.php?req={query}
    url_xpath : //a[contains(@href,"bookfi.net")]/@href
    title_xpath : //a[contains(@href,"book/")]/text()[1]
    content_xpath : //td/a[1][contains(@href,"=author")]/text()
    categories : general
    timeout : 7.0
with
  - name : library genesis
    engine : xpath
    search_url : http://libgen.rs/search.php?req={query}
    url_xpath : //a[contains(@href,"bookfi.net/md5")]/@href
    title_xpath : //a[contains(@href,"book/")]/text()[1]
    content_xpath : //td/a[1][contains(@href,"=author")]/text()
    categories : general
    timeout : 7.0

It works now (for me) with these xpath settings.

**Comment by return42** [comment]
@linuxmue thanks a lot sharing your fix / I prepared PR #2248 for.
