### ISSUE TITLE
Page not Found - New Install

### ISSUE THREAD

**Issue by ArtMason** [searx/searx#2003]
Hello!

I did a new install of searx today on a Linode VPS under Debian 9. I am also using Apache 2 as the web server. 

I did the install as per instructions with no errors.

When I access the site from my domain I get a page not found error unless I amend /search to the URL. All search give a page not found error. However the preferences and about page work fine.

I have read and made suggested changes from a previous post "686" marked as closed.

However it made no difference. I get no errors.

Any ideas? 

Thank yu for any help!

Art

**Comment by return42** [comment]
> I did the install as per instructions with no errors.

Sorry that I can't help with any details, but the installation instructions are very old, PR #1803 is a revise of the installation instructions. A preview is available from here https://return42.github.io/searx/admin/index.html .. hope it give you some hints.

**Comment by ArtMason** [comment]
Thanks, I will have a look through this information. My guess is it is apache related.

**Comment by return42** [comment]
> My guess is it is apache related.

See detailed apache setup at: https://return42.github.io/searx/admin/installation-apache.html

**Comment by ArtMason** [comment]
I got it! Thanks!
There was an issue with the document root in the enable sites in apache

Thanks again!
