### ISSUE TITLE
Set searx as the default search engine? doesn't work

### ISSUE THREAD

**Issue by joshu9h** [searx/searx#2007]
Can't set searx as default search engine firefox
If in the about on install click nothing happens.

**Comment by return42** [comment]
PR #1950 is on the way, in the meantime read "How to set as the default search engine?" from [my about page](https://darmarit.org/searx/about).

**Comment by joshu9h** [comment]
Thanks for the workaround it works now!

**Comment by return42** [comment]
FYI: only the description in the about page was buggy .. The method is always the same, even for older instance (with misleading about page) / Thanks for your feedback!
