### ISSUE TITLE
reset button next to search button doesn't work - does nothing

### ISSUE THREAD

**Issue by idkline** [searx/searx#2009]
The search button works, but the reset button does nothing. I've tried this in several browsers (Chromium, Chrome, Firefox, & Opera) on both Linux machines and windows 10. Same experience on all - reset button does not work. When I say it doesn't work, it does not clear the search input field.

**Comment by B0pol** [comment]
the reset button works in the homepage, but doesn't in search page. 

It was introduced in the search page with commit https://github.com/searx/searx/commit/2621c24cc7992a7c6968d5ce389364c3bf4cc7e2#diff-b247bdace15d8948df63e3acf0267b7971e1d0ed4cd42724051477845eeac629

**Comment by pierrechtux** [comment]
Sometimes, the "x" reset button does something in the main search page (searx/templates/oscar/search.html):
1. if there is already some text in the text area, clicking on the button doesn't do anything;
1. but if one types some text in the text area and then clicks on the "x" reset button, the text area is set back to the status it previously had in stage 1.

After some tests, it appears that the "x" reset button seems to have the same effect as pressing "Ctrl-Z" with the focus in the text area.

**Comment by unixfox** [comment]
It seems like it only works on the home page but not on the search page.

**Comment by GazoilKerozen** [comment]
Just changed the button type and added js function in `searx/static/themes/oscar/js/searx_src/element_modifiers.js` 
it seems to work on Firefox / Linux :)

**Comment by idkline** [comment]
Thanks!
    I will check that
          out...
    
    ----------
      
      ID Kline
      
      
      
        
          
            This transmission is intended exclusively for the individual
            or entity to which it is addressed.
          
          
        
      
      
        This communication may contain information that is confidential,
        proprietary, privileged or otherwise exempt from disclosure. If
        you are not the named addressee, you are NOT authorized to read,
        print, retain, copy or disseminate this communication, its
        attachments or any part of them. If you have received this
        communication in error, please notify the sender immediately and
        delete this communication from all computers.
      
      
        
          
            This communication does not form any contractual obligation
            on behalf of the sender, the sender's employer, or the
            employer's parent company, affiliates or subsidiaries.
          
        
      
      
    
    On 11/8/20 3:35 PM, GazoilKerozen
      wrote:
    
    
      
      Just changed the button type and added js function in searx/static/themes/oscar/js/searx_src/element_modifiers.js
        it seems to work on Firefox / Linux :)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/searx/searx/issues/2009#issuecomment-723662147",
"url": "https://github.com/searx/searx/issues/2009#issuecomment-723662147",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
