### ISSUE TITLE
Advice admins to better proxy image engines

### ISSUE THREAD

**Issue by allendema** [searx/searx#2010]
## Issue
Tested a lot of instances and seems like ~80% of them connect to other potentially tracking domains when category images is selected. Here are a few examples:

bing.net
qwant.com
staticflickr.com
live.staticflickr.com
wixmp.com
## Idea
When this happens it kinda misses the whole point of Searx, so in order to overcome this maybe warn admins that they are using not the “best” possible settings in a readme-like file.

**Comment by return42** [comment]
> When this happens it kinda misses the whole point of Searx, 

You hit the nail on the head! Setting up a _"privacy protecting"_ service is more than installing some python packages .. as you said, an image proxy (and a bot blocker / see all the google CAPTCHA issues) is also needed.

@asciimoo has developed all the needed components; for (image) proxy, we have morty and to protect the searx instance he implemented filtron .. both are very simple but also very efficient (IMO filtron is a kind of swiss army knife, I really like it).

A service made up of these three components deserves the name _"privacy protecting"_.

We have all these components and we have a huge knowledge how combine and balance them. What we lack is a detailed description of how to install these services on the various Linux distributions.

PR #1803 close this gap. It is a revision of the installation instruction and also implements scripts to install the services quiet easy.  The PR is in review and I hope we can merge in the next days.

If you are interested in, here is a preview: https://return42.github.io/searx/admin/index.html

**Comment by allendema** [comment]
That's great. I really like morty too.
I don't have deep knowledge on this matter, but
as i saw PR1803 is gonna get merged soon, so hopefully is going to help maintainers in the future.
Ty for your quick response.

**Comment by return42** [comment]
FYI: PR #1803 (and more) is already merged into [searx-next branch](https://github.com/return42/searx/tree/searx-next), see [searx-next merged PRs](https://github.com/return42/searx/projects/1).

You can build your instance from this branch but I recommend to wait until PR gets merged into `master` and  for the interim you can use my [searx-next instance](https://darmarit.org/searx).

**Comment by return42** [comment]
FYI: #1803 is merged into master: https://asciimoo.github.io/searx/admin/installation.html

**Comment by allendema** [comment]
That's wonderful.
