### ISSUE TITLE
Theme not loading

### ISSUE THREAD

**Issue by karthink** [searx/searx#2013]
I installed Searx on a VPS following the instructions for the script installation in the [docs page](https://asciimoo.github.io/searx/admin/installation.html#installation). Once I start the uwsgi service, I can access the site but the no theme loads:
![2020-06-21-023334_721x269_scrot](https://user-images.githubusercontent.com/8607532/85221307-b5b89e00-b367-11ea-8d11-cd88b058022c.png)

The theme section in `/etc/searx/settings.yml` is unchanged from the defaults:
```
ui:
    static_path : "" # Custom static path - leave it blank if you didn't change
    templates_path : "" # Custom templates path - leave it blank if you didn't change
    default_theme : oscar # ui theme
    default_locale : "" # Default interface locale - leave blank to detect from browser information or use codes from the 'locales' config section
    theme_args :
        oscar_style : logicodev # default style of oscar
```

The installation produced no errors except this one:
```
  |searx| ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /usr/local/searx
```

Any idea what I did wrong?

**Comment by return42** [comment]
> The installation produced no errors except this one:

Thanks for your issue, what exactly have you done? .. I mean, did installed all including morty and filtron? .. Did you  installed apache or nginx?  What is the URL you opened ..?

>   |searx| ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /usr/local/searx

How did you start utils/searx.sh .. as sudo, as described in the docs you linked?

update: or did you tried to update an existing installation?

**Comment by karthink** [comment]
Sorry about the ambiguity. I did not install `filtron` or `morty` yet. As root on the VPS, I did:

```
$ cd ~/Downloads
$ git clone https://github.com/asciimoo/searx searx
$ cd searx
$ ./utils/searx.sh install all
```
Which installed `searx` and `uwsgi` but with the above mentioned error. Next I went into `/etc/searx/settings.yml` and replaced `ultrasecretkey` with the output of `openssl rand -hex 16`.

I already had `nginx` installed, so I created `/etc/nginx/sites-available/searx` and symlinked it to `/etc/nginx/sites-enabled/` with this content:

```
server {
        include /etc/nginx/default.d/*.conf;
	root /usr/local/searx/searx-src;
	index index.html index.htm index.nginx-debian.html;
	server_name searx.mydomain.com www.searx.mydomain.com;

	location /static {
	}

	location / {
		include uwsgi_params;
		uwsgi_pass unix:/run/uwsgi/app/searx/socket;
	}
}
```

(where mydomain is replaced with my domain.)

Then I ran `certbot --nginx` and generated a certificate for `searx.mydomain.com`, which added a bunch of lines to the above file. Finally I ran
```
$ systemctl restart uwsgi
$ systemctl restart nginx
```
>>   |searx| ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /usr/local/searx
>
> How did you start utils/searx.sh .. as sudo, as described in the docs you linked?
I did it as root. Not sure if that makes a difference.

**Comment by return42** [comment]
Thanks for additional infos ..there is something going wrong with your markup .. anyway, @dalf and me have seen issues with root ...

> I did it as root. Not sure if that makes a difference.

It matters! .. it is about the access rights  [The scripts are creating a searx, a filtron and a morty user. These user do not have read access to /root and /root/searx folder](https://github.com/asciimoo/searx/pull/1803#issuecomment-618313334).

Can you please deinstall all and reinstall from a normal user with sudo access .. does it work, there should no more ERROR messages shown. If it works, should I add a note to the docs?](https://github.com/asciimoo/searx/pull/1803#issuecomment-618551125)

Thanks for your report!

**Comment by karthink** [comment]
When I ran it as root earlier, I made sure to set `chmod a+rx` on the path to the cloned searx repo so new users like searx and filtron can use it. In any case, I did `./utils/searx.sh remove all`, then ran the install as a normal user with sudo.  I get the same error. So I can't figure it out.

Some more information:
```
$ uname -a
Linux abode 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
```

```
$ su searx
(searx-pyenv) $ cd ~/searx-src
(searx-pyenv) searx@abode:~/searx-src$ python --version
Python 3.7.3
```

**Comment by karthink** [comment]
Ok, the nginx server logs helped me figure out the problem:
```
2020/06/21 18:04:29 [error] 24942#24942: *15 open() "/usr/local/searx/searx-src/static/themes/oscar/img/favicon.png" failed (2: No such file or directory), client: 98.171.160.254, server: searx.mydomain.com, request: "GET /static/themes/oscar/img/favicon.png HTTP/1.1", host: "searx.mydomain.com"
```
It is looking for assets in `.../searx-src` when the assets are actually in `.../searx-src/searx`. I changed the root in the nginx configuration file and it works fine now. Sorry for the trouble!
