### ISSUE TITLE
Broken link when using Morty proxy

### ISSUE THREAD

**Issue by angoodcitizen** [searx/searx#2015]
I have enabled Morty with searx and it works fine, but in the results now there's the word proxied next to chached. You can press that word and it sends you to 127.0.0.1:3000, that is, where morty runs in localhost. But this is a public instance and that adress is unavailabe and shouldn't be seen. 

Where could i disable that link? I attach some images to show the issue better

### 
![ex1](https://user-images.githubusercontent.com/67105584/85277846-9444d880-b473-11ea-92e5-aa4bb760e783.png)
The link I refer to

![ex2](https://user-images.githubusercontent.com/67105584/85277857-99098c80-b473-11ea-98a7-6f260a3606f8.png)
Which is a link to nowhere since this is a public instance and obviously return not find

**Comment by return42** [comment]
Did you read our new installation instructions? --> https://asciimoo.github.io/searx/admin/installation.html

In the settings file, replace the http://127.0.0.1:3000/ URl wit the URL of your public morty instance (see https://asciimoo.github.io/searx/admin/morty.html#searx-morty).

 if you do not have any special preferences, its recommend to use the Docker installation or the Installation scripts from our tooling box, visit https://asciimoo.github.io/searx/admin/installation.html

**Comment by angoodcitizen** [comment]
Thank you very much!

Yes, i did, altough my instalation was previous to the changes and as i run my instance in a raspberry pi 2b searx-docker is not supported. 
I should try again in the rasp with the new scripts, it is fully compatible?

Thank you again for your time!

**Comment by return42** [comment]
> I should try again in the rasp with the new scripts, it is fully compatible?

pew .. scripts have debian support .. but can't promise you anything on a debian pi.

Give it a try .. feedback is welcome / thanks!

**Comment by angoodcitizen** [comment]
I will try running the scripts in my rasp and post any error i find :)

I'm very noob, but i'll try helping anyway i can, i love this project!

Thanks!

**Comment by angoodcitizen** [comment]
By the way i have resolved the problem simply changing the proxy url in settings.yml, i am not sure if it is working properly, but at least it seems so

**Comment by SuperSandro2000** [comment]
I had a similar problem and just changed the proxy url a bit around.

Debian on the Pi should be the same as amd64 except that some python packages have no prebuilt wheels.

**Comment by angoodcitizen** [comment]
Well, seems working although i don't know how it works exactly if the proxy url is not localhost:3000 which is where the service is listening.

**Comment by return42** [comment]
> Well, seems working although 

"What" seems to work? ... all 3 scripts searx.sh, filtron.sh and morty.sh as describde here https://asciimoo.github.io/searx/admin/installation.html ?

>  i don't know how it works

If you are asking about [morty.sh script](https://asciimoo.github.io/searx/utils/morty.sh.html), take a look at https://github.com/asciimoo/searx/blob/master/utils/morty.sh#L241 .. but don't go to deep ;)

**Comment by angoodcitizen** [comment]
Oh sorry, I was meaning about the solution @SuperSandro2000 gived. I solved my problem about that broken link;)

Regarding the scripts in the rasp (model 2b+), here are my results using Raspberry Pi OS (32-bit) Lite 10 (Buster), following [https://asciimoo.github.io/searx/admin/installation.html](url) :

1. Install searx service

- First and biggest error i get

   ![1](https://user-images.githubusercontent.com/67105584/85397429-0fc18b00-b543-11ea-8b91-888e29ae13d4.png)

- I attach the log of the rest which is easier and more precise (i don't know if this is the proper way of logging, any feedback's welcomed)
   [searx.log](https://github.com/asciimoo/searx/files/4818998/searx.log)



I will also test myself the scripts in Debian Buster in a virtual machine and searx-docker in 
order to test migrating my instance to a more cleaner and secure installation. Any problems or bugs i may find i will post them if they may be useful ;)

Here to help in any way i can as a noob i am:)

**Comment by return42** [comment]
> First and biggest error i get

[It seems not to be recognized as debian](https://github.com/asciimoo/searx/blob/master/utils/lib.sh#L6). Can't say if there are more problems .. it is not supported / thanks for your test!

> I will also test myself the scripts in Debian Buster in a virtual machine 

May be, for testing  you are also interested in linux containers and how we use [LXC](https://asciimoo.github.io/searx/utils/lxc.sh.html) and the [searx-suite](https://asciimoo.github.io/searx/utils/lxc.sh.html#searx-suite) for tests and buildhosts.

**Comment by return42** [comment]
>  Oh sorry, I was meaning about the solution @SuperSandro2000 gived. I solved my problem about that broken link;)

Thanks for the feedback! .. I close this issue now ...

**Comment by angoodcitizen** [comment]
I will be around here in case i have problems/feedback ;)

I will try LXC as you suggest

Thank you very much!

**Comment by return42** [comment]
> I will try LXC as you suggest

If you are interested, I wrote a blog post about  "Developing in Linux containers" #2024 .. a preview of the article is here: https://return42.github.io/searx/blog/lxcdev-202006.html
