### ISSUE TITLE
MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING at searx.space

### ISSUE THREAD

**Issue by pkoziol** [searx/searx#2018]
I cannot open https://searx.space/ due to some TLS issues using Firefox 77.0.1 on MacOS Catalina.

> Secure Connection Failed
>
> An error occurred during a connection to searx.space. A required TLS feature is missing.
>
> Error code: MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

**Comment by SuperSandro2000** [comment]
OCSP stapling issue. Which could mean the server may was restarted shortly before this happend and could not fetch the certificate correctly or the cache was missing somehow. Ref https://support.mozilla.org/en-US/questions/1149911

This means that the server configuration may be incorrect and OCSP stapling needs better persistent cache settings.

**Comment by pkoziol** [comment]
OK, I turned off Zscaler proxy and it works. I guess answer is that:
> Your zscaler device actually does a man-in-the-middle attack on the ssl connections and unfortunately it messes it up - so that the ocsp reply from the server doesn't reach the client and generates this error message.
> https://access.redhat.com/discussions/2408091#comment-1243961

Thanks @SuperSandro2000 !
