### ISSUE TITLE
Yahoo engine: crash list index out of range

### ISSUE THREAD

**Issue by HLFH** [searx/searx#2020]
Related to: https://github.com/asciimoo/searx/pull/1966, https://github.com/asciimoo/searx/pull/1961#issuecomment-635484390

Yahoo engine is not working at all as seen on https://searx.space/.

**Comment by SuperSandro2000** [comment]
Can confirm this on a private instance 
![image](https://user-images.githubusercontent.com/7258858/85567663-5a213580-b631-11ea-86d7-22ac06430fb5.png)

**Comment by return42** [comment]
Yes this bug is reproduce able [!yh foo](https://darmarit.org/searx/?q=%21yh%20foo&categories=none&language=en-US).

I will prepare a PR when PR #1985 gets merged.

**Comment by return42** [comment]
Fixed in PR #2026 / preview: https://darmarit.org/searx/?q=%21yh%20foo&categories=none&language=en-US
