### ISSUE TITLE
eTools engine: "no result" because of blocked AS/IP

### ISSUE THREAD

**Issue by HLFH** [searx/searx#2021]
Weirdly enough, eTools engine only works well on [search.0xcb.dev](https://search.0xcb.dev/search?q=!etools%20time&theme=oscar&language=en) instance.

Other than that, other instances only provide "no result" error.

@Conor-Burns
@piplongrun

Any ideas?
Thanks!

**Comment by dalf** [comment]
I have results for these instances:
* searx.privatenet.cf
* zoek.anchel.nl
* search.0xcb.dev
* seeks.hsbp.org
* searx.ir
* searx.dojocasts.com
* suche.dasnetzundich.de
* searx.feneas.org
* search.gougeul.org
* search.privacytools.io
* www.finden.tk
* searx.run

I went in the engine tab of searx.space, the click on each "?", "❌", "✔️" for the eTools engine

**Comment by unixfox** [comment]
eTools is probably rate limiting the requests on popular Searx instances.
It's better to run Searx locally instead of relying on external instances and enable the debug mode then report the logs in the issue instead of just saying "no results".

**Comment by Conor-Burns** [comment]
@HLFH my instance runs on a dedicated server - that's why the rate limit kicks in later

**Comment by HLFH** [comment]
@Conor-Burns I am using a dedicated server as well from Scaleway Dedibox. Yours looks [more professional](https://synlinq.de/). Thank you.

@unixfox I will try this week-end to test searx locally, enable the debug mode, and add the rotating IP proxy. And check if that works better.

**Comment by HLFH** [comment]
My IP is blocked at the AS level by etools.ch at least. I have tried with *curl* to debug.

I have just contacted comcepta.com.

> <h1>AS Access Denied </h1>
<p>Sorry, your IP address <span class="ip">MYIPADDRESS</span> originating from <a href="https://en.wikipedia.org/wiki/Autonomous_system_(Internet)" target="_blank" rel="noopener">AS</a> <span class="appendix">12876 (Online S.a.s.)</span> is denied for this service.<br /> This may happen if our system gets many automated requests from the same AS.</p>
<p class="space-top">Please <a href="mailto:contact AT comcepta.com">contact us</a> if you think this is an error or want to use our product <i><a title="Federated Search Solution" href="https://www.comcepta.com/en/enterprise-metasearch.html" target="_blank" rel="noopener">EnterpriseMetasearch</a></i><sup>&#174;</sup> or our search service commercially.</p>
<p class="foot"><a href="/search.do" title="eTools.ch - The Transparent Metasearch Engine from Switzerland">eTools.ch</a> - &#169;1999-2020 <a title="Comcepta AG: IT-Consulting and Solutions" href="https://www.comcepta.com/">Comcepta&#160;AG</a></p>

**Comment by unixfox** [comment]
I've doubts that we will be able to fix this issue if eTools ban the IP of the Searx instance and without giving the choice of solving a CAPTCHA in order to be unbanned.

Should we close this issue if it works locally and we can't provide a fix for the public Searx instances?

**Comment by HLFH** [comment]
@unixfox You are right.

Related to: https://github.com/dalf/searx-instances/pull/77

I am now using a private instance running on Ubuntu 20.04 on top of macOS thanks to [multipass](https://github.com/canonical/multipass). 

<img width="632" alt="Screenshot 2020-08-11 at 15 37 39" src="https://user-images.githubusercontent.com/2359059/89910862-a5df6c80-dbe8-11ea-8eaa-c68069dee12d.png">
