### ISSUE TITLE
(Bug) DDG ignores Time Range

### ISSUE THREAD

**Issue by allendema** [searx/searx#2028]
## Issue
DDG doesn't correctly respond to desired Time Range.
Lets say for one week it returns results from last month or older.

## Example
[https://search.0xcb.dev/?q=%21go%20%21yh%20%21ddg%20site%3Apastebin.pl%20code&categories=none&time_range=week&language=de](https://search.0xcb.dev/?q=%21go%20%21yh%20%21ddg%20site%3Apastebin.pl%20code&categories=none&time_range=week&language=de)

**Comment by asciimoo** [comment]
I've checked, we send the correct time filter attributes to ddg and it has the same results if you use their site.
