### ISSUE TITLE
Add documentation on removing searx completely

### ISSUE THREAD

**Issue by thansk** [searx/searx#2029]

**Comment by return42** [comment]
Depends on how you installed searx and what you installed.  If you installed a docker image, just remove it, if you used the scripts from https://asciimoo.github.io/searx/admin/installation.html#installation-scripts and used the command `install all`, there is also the option to run theses script using the command `remove all`

- https://asciimoo.github.io/searx/utils/searx.sh.html#overview
- https://asciimoo.github.io/searx/utils/filtron.sh.html#overview
- https://asciimoo.github.io/searx/utils/morty.sh.html#overview

it might be worth to add a note about. If we do so, I would add a link to https://github.com/asciimoo/searx/issues/2017

**Comment by unixfox** [comment]
If someone finds this issue. If you used the official wiki then remove Searx with `sudo -H ./utils/searx.sh remove all`.
For the other possible installations, we cannot cover all of them so there is no universal way of removing Searx.
