### ISSUE TITLE
Broken image preview

### ISSUE THREAD

**Issue by sanpii** [searx/searx#203]
Hello,

With [this search](https://searx.0x2a.tk/?q=%21images%20dmenu&pageno=1&category_images) on firefox 35, click on the [4th image](https://farm4.staticflickr.com/3223/2707637070_f893a83424_z.jpg?zz=1) displays a strange preview:

![2015-01-26-183802_1676x975_scrot](https://cloud.githubusercontent.com/assets/113045/5904746/1c425198-a58b-11e4-9d63-1221287452cc.png)

**Comment by Cqoicebordel** [comment]
Same as #181

**Comment by asciimoo** [comment]
@sanpii thanks the detailed report, it'll be fixed soon
