### ISSUE TITLE
Problematic Language in Documentation

### ISSUE THREAD

**Issue by rhamnousia** [searx/searx#2031]
Today I discovered searx, and I was very pleased that such a federated service exists. However I was disappointed in some of the language used in the documentation. I noticed this problem on [this page](https://github.com/asciimoo/searx/blob/master/docs/user/own-instance.rst) in particular, although there might be others in which this problem crops up:

> If someone uses a public instance, he/she has to trust the administrator of that instance. This means that the user of the public instance does not know whether his/her requests are logged, aggregated and sent or sold to a third party.

Notice anything? It's that exclusive language: "he/she" and "his/her." It would be much more representative of the userbase of this software if gender-neutral terms (such as "they" and "their" in this instance) were used instead. So I figured that I would call this to the attention of the community in an issue before I went ahead and made changes, as to scope out the prevailing sentiments on this matter.

**Comment by return42** [comment]
Thanks for your remarks. Please take into account: We are diverse, our community includes people with different talents from around the world. We will not force anyone to do anything. We will not refuse an improvement just because the wording does not do everyone justice.

**Comment by kvch** [comment]
@rhamnousia Thank you for raising the issue. Please forgive me for the wording. I am not a native English speaker. :) I've opened a PR to address the problem: https://github.com/asciimoo/searx/pull/2032

In the future I don't think it is necessary to open a separate issue. Just go ahead and submit a PR if you find anything inappropriate.
