### ISSUE TITLE
Duplicate feature: result in a new tab.

### ISSUE THREAD

**Issue by dalf** [searx/searx#2037]
## Core feature "result on new tab": 
* https://github.com/asciimoo/searx/blob/6163bd671bbf71a9eae3a6a9b1019e2a701c4946/searx/preferences.py#L366-L374
* https://github.com/asciimoo/searx/blob/6163bd671bbf71a9eae3a6a9b1019e2a701c4946/searx/templates/oscar/preferences.html#L114-L121
* https://github.com/asciimoo/searx/blob/6163bd671bbf71a9eae3a6a9b1019e2a701c4946/searx/templates/oscar/macros.html#L11-L18
* ![image](https://user-images.githubusercontent.com/1594191/86147361-93f2b000-baf9-11ea-819a-2054c8635dbb.png)

## Plugin "result on a new tab": 
* https://github.com/asciimoo/searx/blob/6163bd671bbf71a9eae3a6a9b1019e2a701c4946/searx/static/plugins/js/open_results_on_new_tab.js#L1-L3
*  ![image](https://user-images.githubusercontent.com/1594191/86147456-b4bb0580-baf9-11ea-88e9-27d3591dab6c.png)

**Comment by return42** [comment]
Wow .. haven't realized until you pointed it out.

What do you suggest, should we git revert ab6a7601?

**Comment by dalf** [comment]
> What do you suggest, should we git revert ab6a760?

Yes, I think so.
