### ISSUE TITLE
Running "python searx/webapp.py" works, running via uwsgi doesn't

### ISSUE THREAD

**Issue by tjharman** [searx/searx#2041]
Hi,

I'm new to this, so I'm probably doing something really dumb. Apologies in advance if I'm time wasting.

I've installed Searx in a Ubuntu 20.4 Container (running under Proxmox)

All's gone well, except if I try to access my site, I get an Internal Server Error.

Looking into the /var/log/uwsgi/app/searx.log file I see

```
Sat Jul  4 17:19:29 2020 - setgid() to 998
Sat Jul  4 17:19:29 2020 - setuid() to 998
Sat Jul  4 17:19:29 2020 - Python version: 3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
Sat Jul  4 17:19:29 2020 - PEP 405 virtualenv detected: /usr/local/searx/searx-pyenv
Sat Jul  4 17:19:29 2020 - Set PythonHome to /usr/local/searx/searx-pyenv
Sat Jul  4 17:19:29 2020 - Python main interpreter initialized at 0x55595f83fc40
Sat Jul  4 17:19:29 2020 - python threads support enabled
Sat Jul  4 17:19:29 2020 - your server socket listen backlog is limited to 100 connections
Sat Jul  4 17:19:29 2020 - your mercy for graceful operations on workers is 60 seconds
Sat Jul  4 17:19:29 2020 - mapped 218760 bytes (213 KB) for 2 cores
Sat Jul  4 17:19:29 2020 - *** Operational MODE: preforking ***
Sat Jul  4 17:19:29 2020 - added /usr/local/searx/searx-src/ to pythonpath.
Sat Jul  4 17:19:29 2020 - spawned uWSGI master process (pid: 24971)
Sat Jul  4 17:19:29 2020 - spawned uWSGI worker 1 (pid: 24977, cores: 1)
Sat Jul  4 17:19:29 2020 - spawned uWSGI worker 2 (pid: 24978, cores: 1)
Sat Jul  4 17:19:29 2020 - spawned uWSGI http 1 (pid: 24979)
Traceback (most recent call last):
  File "/usr/local/searx/searx-src/searx/webapp.py", line 74, in <module>
    from searx.search import SearchWithPlugins, get_search_query_from_webapp
  File "/usr/local/searx/searx-src/searx/search.py", line 32, in <module>
    from searx.external_bang import get_bang_url
  File "/usr/local/searx/searx-src/searx/external_bang.py", line 13, in <module>
    for bang in json.load(json_file)['bang']:
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31341: ordinal not in range(128)
Sat Jul  4 17:19:30 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
Sat Jul  4 17:19:30 2020 - *** no app loaded. going in full dynamic mode ***
Traceback (most recent call last):
  File "/usr/local/searx/searx-src/searx/webapp.py", line 74, in <module>
    from searx.search import SearchWithPlugins, get_search_query_from_webapp
  File "/usr/local/searx/searx-src/searx/search.py", line 32, in <module>
    from searx.external_bang import get_bang_url
  File "/usr/local/searx/searx-src/searx/external_bang.py", line 13, in <module>
    for bang in json.load(json_file)['bang']:
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31341: ordinal not in range(128)
Sat Jul  4 17:19:30 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
Sat Jul  4 17:19:30 2020 - *** no app loaded. going in full dynamic mode ***
Sat Jul  4 17:19:36 2020 - --- no python application found, check your startup logs for errors ---
Sat Jul  4 17:19:38 2020 - --- no python application found, check your startup logs for errors ---
Sat Jul  4 17:21:37 2020 - --- no python application found, check your startup logs for errors ---
```

The thing is, if I go through troubleshooting and do this:

```
# start webapp
$ sudo -H -u searx -i
(searx)$ cd /usr/local/searx/searx-src
(searx)$ export SEARX_SETTINGS_PATH=/etc/searx/settings.yml
(searx)$ python searx/webapp.py
```

searx works perfectly and I can browse/search and get results.

What have I done wrong thus that uwsgi can't serve the Python app?

Thanks!

**Comment by tjharman** [comment]
Just FYI I have installed from this git commit

commit 4829a76aae8fa6af8d3f814ff780dc6e792b84e5

**Comment by return42** [comment]
I don't know why, but it seems that your uwsgi process has problems with the file [/searx/data/bangs.json](https://github.com/asciimoo/searx/blob/master/searx/data/bangs.json). I have to test it under ubu20.04 ..

**Comment by return42** [comment]
I tested in a ubu2004 LXC / for thus who want to see how I build the container and suite: 

     sudo -H ./utils/lxc.sh build searx-ubu2004
     sudo -H ./utils/lxc.sh install suite searx-ubu2004

     INFO:  (eth0) filtron:    http://n.n.n.n:4004/ .. 

In such a LXC container I do not see this issue when I open the (filtron) URL at 4004.

In general we should not have a issue with ubu2004, did you have any more information about your installation procedure?

**Comment by tjharman** [comment]
Hmmm I didn't do it that way, I just followed the install instructions [here](https://asciimoo.github.io/searx/admin/installation.html#installation-scripts)

I created a "normal" user, gave him sudo rights, then ran those scripts one by one.  Everything seemed to go fine.

I am using Proxmox, and using it I installed a Ubuntu 20.4 container.  It was from within that container I did the above (created new user, went through the install scripts one by one)

I seem to have Filtron running OK on 4004

```
tim@searx:~$ telnet localhost 4004
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
hi
HTTP/1.1 400 Bad Request
Server: fasthttp
Date: Sat, 04 Jul 2020 07:19:05 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 26
Connection: close

Error when parsing requestConnection closed by foreign host.
```

**Comment by return42** [comment]
> Hmmm I didn't do it that way, I just followed the install instructions here

You have done everything right, following the installation instruction .. I posted a test-scenario for those of us not having a ubu20.04 system (Sorry if this was misleading for you).

> It was from within that container I did the above (created new user, went through the install scripts one by one)

That is right way .. everything seems OK with the installation / your `# start webapp` shows me that the installation of searx itself works .. ATM I do not have a clue what the difference is when the searx process is started by uwsgi.

````
 return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31341: ordinal not in range(128)
````

The json file I linked above contains unicode (at position 31341 / compare with the message above).

So the question is, why is this file opened/read as unicode file when running manually and when searx is started via uwsgi it is opened/read using ASCII.  We had such encoding problems in the past when python 2 vs python 3 comes into play, but the uwsgi process is using python 3 ...

````
File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
````

That makes me think, something has to be different in the environment of the WSGI process. So I tested ubu20.04, but the problem does not exists in my test-scenario / in the process of elimination: ubuntu 20.04 seems not the  cause.

We have to dig deeper around the WSGI environment, ATM I do not have a clue.

**Comment by return42** [comment]
I guess I found the problem: the default encoding of [json.load](https://docs.python.org/3/library/json.html#json.load) depends [on the platform](https://bugs.python.org/issue25028) .. I would have expected utf-8 as default for json but this is not the case.  We have to set the encoding explicit.

I prepared a patch in #2043 

@theel0ja can you please test the patch? / Thanks!

**Comment by tjharman** [comment]
I've just tested the patch and sadly, it hasn't helped, though the error has changed slightly:

```
Sat Jul  4 21:31:54 2020 - spawned uWSGI http 1 (pid: 1546)
Traceback (most recent call last):
  File "/usr/local/searx/searx-src/searx/webapp.py", line 74, in <module>
    from searx.search import SearchWithPlugins, get_search_query_from_webapp
Traceback (most recent call last):
  File "/usr/local/searx/searx-src/searx/search.py", line 32, in <module>
  File "/usr/local/searx/searx-src/searx/webapp.py", line 74, in <module>
    from searx.external_bang import get_bang_url
  File "/usr/local/searx/searx-src/searx/external_bang.py", line 13, in <module>
    from searx.search import SearchWithPlugins, get_search_query_from_webapp
    for bang in json.load(json_file, encoding='utf-8')['bang']:
  File "/usr/local/searx/searx-src/searx/search.py", line 32, in <module>
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    from searx.external_bang import get_bang_url
  File "/usr/local/searx/searx-src/searx/external_bang.py", line 13, in <module>
    for bang in json.load(json_file, encoding='utf-8')['bang']:
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31341: ordinal not in range(128)
Sat Jul  4 21:31:55 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
Sat Jul  4 21:31:55 2020 - *** no app loaded. going in full dynamic mode ***
    return loads(fp.read(),
  File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31341: ordinal not in range(128)
Sat Jul  4 21:31:55 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
Sat Jul  4 21:31:55 2020 - *** no app loaded. going in full dynamic mode ***
```

**Comment by dalf** [comment]
Perhaps the open function : https://docs.python.org/3/library/functions.html#open

> In text mode, if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding. (For reading and writing raw bytes use binary mode and leave encoding unspecified.)

I suspect the locale of the docker image to not be utf (I can't check right now).

**Comment by tjharman** [comment]
Ok, thanks for the pointers both @return42 and @dalf 

It would appear that my container didn't have a UTF language properly setup.

I set the following in ```/etc/uwsgi/apps-enabled/searx.ini```
```
env = LANG=en_NZ.UTF-8
env = LANGUAGE=en_NZ.UTF-8
env = LC_ALL=en_NZ.UTF-8
```

And now I'm starting up fine (with the patch above reverted)

So yes, this appears to be a problem when the user doesn't properly have UTF setup, which was the case because I've installed this version of Ubuntu via Promox's LXC system, not a true Ubuntu install.

Thanks and I'm sorry for wasting YOUR time on MY problem.

**Comment by return42** [comment]
@tjharman thanks a lot for your feedback!

But I really wondering that  `json.load(json_file, encoding='utf-8')` does not help. _i will never understand python encoding_ :-o

> I set the following in /etc/uwsgi/apps-enabled/searx.ini

Thanks for the hint / I mark this issue as bug and will send another PR later, adding env to the searx.ini.

Thanks again for your cooperation, it was very helpful for me.

**Comment by return42** [comment]
@tjharman I changed the patch and forced push to #2043 

If you have time to test, it would be a great help / thanks!
