### ISSUE TITLE
Still keep getting could not download the search plugin from .../opensearch.xml

### ISSUE THREAD

**Issue by rparree** [searx/searx#2042]
I know there's an issue for this (#532) with some links to related issues. I was wondering what the status is of this error and what possible solutions are. I'm using a docker instance (`searx/searx:latest`) behind traefik 2.0 with let's encrypt and a basic auth password. 

When i click the little green icon in Firefox's search bar to add searx to  my search engines, it reports back with *Firefox could not download the search plugin from ...*

I tried running `window.external.AddSearchProvider("…")` but i believe firefox no longer supports this method. 

How can i add my instance to firefox search engines?

tx.,

**Comment by return42** [comment]
Did you setup your own instance or did you use a public instance (which)?

**Comment by return42** [comment]
@dalf do you have a clue?

**Comment by dalf** [comment]
It is difficult to know what is happening. 

As a backup solution you can use : https://www.tobtu.com/customsearch.php 

Can you try this: ```curl -v <your instance URL>/opensearch.xml```

And check if:
* there is no error
* an output similar to this:

```
< HTTP/2 200 
< date: Sun, 05 Jul 2020 13:05:19 GMT
< content-type: application/opensearchdescription+xml; charset=utf-8
< content-length: 637
< server-timing: total;dur=1.775
< strict-transport-security: max-age=15724800; includeSubDomains; preload
< server: hide
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1
< content-security-policy: upgrade-insecure-requests; default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; font-src 'self'; frame-ancestors 'self'; base-uri 'self'; connect-src 'self' https://overpass-api.de; img-src 'self' data: https://*.tile.openstreetmap.org; frame-src 'self' https://www.youtube-nocookie.com https://player.vimeo.com https://www.dailymotion.com https://www.deezer.com https://www.mixcloud.com https://w.soundcloud.com https://embed.spotify.com
< feature-policy: accelerometer 'none';ambient-light-sensor 'none'; autoplay 'none';camera 'none';encrypted-media 'none';focus-without-user-activation 'none'; geolocation 'none';gyroscope 'none';magnetometer 'none';microphone 'none';midi 'none';payment 'none';picture-in-picture 'none'; speaker 'none';sync-xhr 'none';usb 'none';vr 'none'
< referrer-policy: no-referrer
< x-robots-tag: noindex, noarchive, nofollow
< 
<?xml version="1.0" encoding="utf-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>Searx Belgium</ShortName>
  <Description>a privacy-respecting, hackable metasearch engine</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image>https://searx.be/static/themes/oscar/img/favicon.png</Image>
  <LongName>searx metasearch</LongName>
    <Url rel="results" type="text/html" method="post" template="https://searx.be/">
        <Param name="q" value="{searchTerms}" />
    </Url>
    <Url rel="suggestions" type="application/json" template="https://searx.be/autocompleter"/>
</OpenSearchDescription>
```
* check if there is ```content-type: application/opensearchdescription+xml; charset=utf-8``` in your curl output.

**Comment by rparree** [comment]
The backup solution uses ` window.external.AddSearchProvider` which no longer works in FF (i tried running that from the console last week).

curl works and returns a similar XML file as in your post. I have also tried with authentication disabled. 

I did notice the server returns `Content-Type: text/plain; charset=utf-8` on `/opensearch.xml`. Might that be something?

**Comment by dalf** [comment]
> I did notice the server returns Content-Type: text/plain; charset=utf-8 on /opensearch.xml. Might that be something?

According to https://developer.mozilla.org/en-US/docs/Web/OpenSearch (Troubleshooting Tips section):
> Your server should serve OpenSearch plugins using Content-Type: application/opensearchdescription+xml.

So this is probably the issue.


For reference, the Flask app returns the right MIME type:
https://github.com/asciimoo/searx/blob/4829a76aae8fa6af8d3f814ff780dc6e792b84e5/searx/webapp.py#L964-L966

Most probably uwsgi too.

**Comment by rparree** [comment]
Sorry, forgot to provide credentials, the content-type is set correctly

```
HTTP/1.1 200 OK
Content-Length: 521
Content-Type: application/opensearchdescription+xml; charset=utf-8
```

**Comment by return42** [comment]
@rparree just to be able to rule it out: did you have (like me) a special prefs.js (syspref.js) or changed any special in the about:config in FFox?

**Comment by rparree** [comment]
I do have a few settings in "about:config". However i've just tried with a clean firefox profile, and same error.

**Comment by return42** [comment]
Is your instance public .. can you give us the URL?

**Comment by rparree** [comment]
it is public but normally protected with username/password i don't want to attract too much traffic to that server. I could email it to you and dalf (using the email addresses on your github accounts)

**Comment by return42** [comment]
OK, I understand .. if it is OK for you send a mail to markus.heiser@daramarit.de ..

**Comment by rparree** [comment]
i'm getting an "Undelivered Mail Returned to Sender" error on that address :(

```
<markus.heiser@daramarit.de>: Host or domain name not found. Name service error
    for name=daramarit.de type=A: Host not found
```

**Comment by return42** [comment]
Sorry there was a typo markus.heiser@darmarIT.de

**Comment by return42** [comment]
Thanks for your URL .. I made some tests, just to verify some of the remarks from above .. everything looks good to me .. but firefox says "can't load ..." 

I do not know why curl loads the XML (and showing correct headers) while FFox says it can't .. I don't have any ideas more ..

If I'm not totally wrong, It must be specific to your server .. what does the HTTP server log say when you download via curl and what does the log say when you press the button in FFox?

**Comment by dalf** [comment]
What does the FF console says ? Perhaps this URL (not the others) should not have an auth.

**Comment by rparree** [comment]
@dalf i disabled auth to this test (re-enabled now, after receiving email from Markus)

Nothing in the console. I tried also enabling logging `browser.search.log` in `about:config`, but nothing.

There's no access log in my searx container, i've enabled access log on my traefik:

```
"GET /opensearch.xml HTTP/2.0" 200 521 "-" "-" 19 "searx@docker" "http://192.168.80.8:8080" 16ms
```

**Comment by return42** [comment]
May be it is related to the HTTPS reverse proxy from traefik .. that it does not deliver out the response ... to be true; I don't know.

OT here but in general we do not recommend reverse proxies for privacy reasons / see comments beginning from https://github.com/asciimoo/searx/issues/1965#issuecomment-632100556 and issue https://github.com/asciimoo/searx/issues/1987

Sorry that I can't halp any more.

**Comment by rparree** [comment]
I did some more digging and found another log from firefox (i enabled 'browser.search.log' to in ` about:config`. Thought this would log to the Javascript console, but it logs to the "Browser Console")

(i changed the urls below to example.com)

```
getSubmission: In data: "dummy"; Purpose: "undefined"
getSubmission: Out data: "dummy"
getSubmission: In data: "dummy"; Purpose: "undefined"
getSubmission: Out data: "dummy"
SearchService.init
addEngine: Adding "https://search.example.com/opensearch.xml".
  SearchService.init
_setIcon: Setting icon url "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAABvFBMVEUAAAAAAAD7+/v8/PwAAAAAAAAAAAD+/v4AAAD///8AAAAAAAAAAAAAAAAAAAAAAA..." for engine "null".
  _initFromURIAndLoad: Downloading engine from: "https://search.example.com/opensearch.xml".
  loadListener: Starting request: https://search.example.com/opensearch.xml
loadListener: Stopping request: https://search.example.com/opensearch.xml
_init: Initing search plugin from https://search.example.com/opensearch.xml
_parseImage: Image textContent: "/static/themes/oscar/img/favicon.png"
OpenSearch image element must have positive width and height.
new EngineURL: template is not a valid URI!
_parseURL: failed to add search.example.com/ as a URL
_parse: failed to parse URL child: [Exception... "_parseURL: failed to add search.example.com/ as a URL"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/SearchUtils.jsm :: fail :: line 126"  data: no]
_parse: No name, or missing URL!
  _onLoad: Failed to init engine!
  [Exception... "_parse: No name, or missing URL!"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/SearchUtils.jsm :: fail :: line 126"  data: no]
addEngine: Error adding engine:
1
getSubmission: In data: "dummy"; Purpose: "undefined"
getSubmission: Out data: "dummy"
getSubmission: In data: "dummy"; Purpose: "undefined"
getSubmission: Out data: "dummy"
getSubmission: In data: "dummy"; Purpose: "undefined"
getSubmission: Out data: "dummy"
getSubmission: In data: "dummy"; Purpose: "undefined"
getSubmission: Out data: "dummy"
getSubmission: In data: "dummy"; Purpose: "undefined"
getSubmission: Out data: "dummy"
getSubmission: In data: "dummy"; Purpose: "undefined"
getSubmission: Out data: "dummy" 
```

This is the XML (obtained via cURL)

```
<?xml version="1.0" encoding="utf-8"?>
  <OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
    <ShortName>searx</ShortName>
    <Description>a privacy-respecting, hackable metasearch engine</Description>
    <InputEncoding>UTF-8</InputEncoding>
    <Image>/static/themes/oscar/img/favicon.png</Image>
    <LongName>searx metasearch</LongName>
    <Url rel="results" type="text/html" method="post" template="search.example.com/">
      <Param name="q" value="{searchTerms}" />
    </Url>
  </OpenSearchDescription>
```

**Comment by dalf** [comment]
Ok ! It shouldn't be ```search.example.com/```.

You have to set https://github.com/asciimoo/searx/blob/3227695b0b587782b931c6163f993f3dae0a6d31/searx/settings.yml#L16
to your instance URL.

**Comment by rparree** [comment]
The search.example.com in my posts was just an example (i did not want to use my domain name, because i don't want to attract traffic to my instance

However, i noticed my `BASE_URL` environment variable (i'm using docker), did not have the protocol (https).

Feel stupid :) Sorry to have wasted your time guys.

It's working now that i've added the URL scheme.

**Comment by return42** [comment]
>  did not have the protocol (https).

Facepalm .. I should have seen it in the curl response when I tested your URL / sorry for my inattention

OT: Anyway I recommend not to use reverse proxy providers.

**Comment by rparree** [comment]
I'm using my own Traefik reverse  proxy on my cloud server (with let's encrypt). Its fronts other services on my server.
