### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by cuppajoeman** [searx/searx#2044]
I was trying to setup an nginx search instance, and noticed the following: https://i.imgur.com/uW6tWz2.png on https://asciimoo.github.io/searx/admin/installation-nginx.html#nginx-searx-site. On the 3rd tab there is a similar directive with `alias` in the front, I'm not too knowledgeable about nginx, so I didn't try to change this myself, but I think `alias` should probably be added to the front.

Also just as a side note, an example nginx config would be great, as of right now I haven't been able to get it fully working on my server, wasn't sure what to put as `server_name`, `root` etc...

**Comment by unixfox** [comment]
@cuppajoeman Do you think you could open a PR in order to fix the documentation?
The documentation directory is here: https://github.com/asciimoo/searx/tree/master/docs but if you don't know how to edit it then @return42 may help you about that.

**Comment by unixfox** [comment]
@return42 What do think about this issue? Is there something needed to change in the docs?

**Comment by return42** [comment]
> @return42 What do think about this issue? Is there something needed to change in the docs?

Sorry for the late reply .. send https://github.com/searx/searx/pull/2223 to fix the alias typo.

> wasn't sure what to put as server_name, root etc...

Yes, you are not the first asking for .. but it is hard to give "one example that fits to all" .. a complete ngingx setup depends on your use-case and distro. I can only recommend to read our docs https://searx.github.io/searx/admin/installation-nginx.html#the-nginx-http-server and click on the distro tabs ... for more informations follow the links to the nginx "biginners guide" and the "nginx wiki".
