### ISSUE TITLE
[Question/Bug] Empty Results vs Using The Search Engine Directly For No Apparent Reason?

### ISSUE THREAD

**Issue by seniorm0ment** [searx/searx#2049]
When using Searx I notice the results I get are super spotty. Coming from using DuckDuckGo directly for example, there are terms I can type in on DuckDuckGo, that when I type in on Searx just give me zero results. I fail to understand why this is? Searx just scrapes from the engines, so if something comes through on DuckDuckGo, why would it not come through on Searx? Ontop of this, if I have multiple search engines added on Searx, it should be even more likely to pull a result. I fail to understand why I very often get no results with certain search terms, but readjusting my wording sometimes fixes it.
I have multiple search engines added so it should not be of issue?

**Comment by asciimoo** [comment]
Do you use a public instance or hosting your own?

**Comment by seniorm0ment** [comment]
I'm using Snopyta's

**Comment by HLFH** [comment]
As a reference: https://search.snopyta.org/

**Comment by unixfox** [comment]
Duplicate of #1883
