### ISSUE TITLE
[Feature req] Ability to append custom variables to search result like $currentdate

### ISSUE THREAD

**Issue by TicTac9k1** [searx/searx#2054]
This is a small feature request I think might be useful for searching for example job vacancies. This helps filter out dated items and only return recent results in conjunction with RSS feeds.

**Comment by return42** [comment]
Searx is a meta search engine, it is very hard to find a solution to scrap _custom variables_ from other engines / do you have any suggestion how this could be realized?

**Comment by TicTac9k1** [comment]
I'm no programmer by any means and will probably misuse a lot of programming terminology, but my intention was to add custom variables directly into Searx itself rather than scraping from other engines. These then can be appended to a search result, kind of like a custom operator (like google) that an external search engine normally wouldn't provide. But after thinking it through some more I realised I could've just taken a different search approach for my 'issue'.

**Comment by return42** [comment]
> But after thinking it through some more I realised I could've just taken a different search approach for my 'issue'.

If you think this is the solution for your problem, could you please close this entry? / thanks!
