### ISSUE TITLE
links/lynx text browser support

### ISSUE THREAD

**Issue by vandys** [searx/searx#2058]
(Very often useful for blind people, although I use it just because I'm a minimalist.)  The front page has a form which will accept a search term, and even accept the button click.  But then, rather than a search result, you are told "Something went wrong. Please go back and try again"  Seems like the input handling is really close to doing the right thing.

**Comment by asciimoo** [comment]
Interesting.. It works well using w3m.

**Comment by unixfox** [comment]
Searx works fine with lynx/links:
![Peek 04-01-2021 15-14](https://user-images.githubusercontent.com/4016501/103543961-4172c180-4e97-11eb-96be-4ed516dc8222.gif)
