### ISSUE TITLE
using language of result to process better ranking

### ISSUE THREAD

**Issue by pointhi** [searx/searx#206]
If someone has specified a search-language, we could improve ranking using the language of the result and rank it higher, if it is matching.

**for example: wikipedia**

the subdomain in the wikipedia-url is clearly showing what language the result has. So we can use it to rank wikipedia-results in the specified search-language higher as the "normal" english results.

**Comment by asciimoo** [comment]
Good idea, engines with language support could get a score multiplier if the search language is specified.

**Comment by bitwave** [comment]
+1 for this :D
