### ISSUE TITLE
Adding searX to Firefox

### ISSUE THREAD

**Issue by MatthK** [searx/searx#2060]
Hi

I just installed searx on my Synology NAS as a docker container. The search engine is running fine and so I thought I will add it to my Firefox as the default search engine.

When I click on the 3 dots in the address bar and select "Add search engine" I get a 

```
Download Error
Firefox could not download the search plugin from:
https://searx.domain.name/opensearch.xml
```

The opensearch.xml file exists, as when I download it manually I get the following content:

```
<?xml version="1.0" encoding="utf-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>searx</ShortName>
  <Description>a privacy-respecting, hackable metasearch engine</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image>/static/themes/oscar/img/favicon.png</Image>
  <LongName>searx metasearch</LongName>
    <Url rel="results" type="text/html" method="post" template="/">
        <Param name="q" value="{searchTerms}" />
    </Url>
</OpenSearchDescription>
```
How can I add this as my default engine? On Edge it worked just like a charm.

Firefox 78.0.1 (64-bit) on a Windows 10 machine.

**Comment by return42** [comment]
Did you set [`base_url`](https://asciimoo.github.io/searx/admin/settings.html)? / see https://github.com/asciimoo/searx/issues/2042#issuecomment-654238925 and https://github.com/asciimoo/searx/issues/2048

**Comment by MatthK** [comment]
The base_url was not set. I added the https://searx.domain.name/ (domain.name is replaced with the real name) and restarted the docker container. 

Same result, it can't add the searx engine.

I do have  similar setup like rparree in the other thread, my search engine is behind a nginx reverse proxy that has a Letsencrypt cert. When I tried curl -v https://searx.domain.name/opensearch.xml I got first a lot of TLSv1.3/SSL lines followed by 
```
> GET /opensearch.xml HTTP/1.1
> Host: searx.domain.name
> User-Agent: curl/7.68.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.18.0 (Ubuntu)
< Date: Sun, 12 Jul 2020 10:01:08 GMT
< Content-Type: application/opensearchdescription+xml; charset=utf-8
< Content-Length: 502
< Connection: keep-alive
< Server-Timing: total;dur=51.704
<
<?xml version="1.0" encoding="utf-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>searx</ShortName>
  <Description>a privacy-respecting, hackable metasearch engine</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image>/static/themes/oscar/img/favicon.png</Image>
  <LongName>searx metasearch</LongName>
    <Url rel="results" type="text/html" method="post" template="/">
        <Param name="q" value="{searchTerms}" />
    </Url>
* Connection #0 to host searx.domain.name left intact
```

I'm a bit surprised to see <Url rel="results" type="text/html" method="post" template="/"> the template as a simple "/". Shouldn't that show the full URL?

I also tried to add the search engine directly, without the reverse proxy by using the http://192.168.1.10:8888/. I get the same error and also the template shows a single "/"

**Comment by MatthK** [comment]
Anyone?

**Comment by return42** [comment]
Sorry for the late reply .. 

> I also tried to add the search engine directly, without the reverse proxy 

There should be no difference .. 

>  I'm a bit surprised to see the template as a simple "/". Shouldn't that show the full URL?

Yes, you should see https://searx.domain.name (the value you used for base_url).

I can't explain why that's not the case with you / dump question .. is there a typo?

**Comment by MatthK** [comment]
Where could there be a typo? 

I tried again with different versions of the BASE_URL, where I omitted the https:// but that didn't help either.

And there's not much else I could or should set, no?

**Comment by MatthK** [comment]
Ok, so I just double checked everything again and also checked if I missed something in the install process. I then noticed that your docker was wonderfall/searx while I had searx/searx installed.
When I tried with wonderfall/searx it worked immediately. Thanks for the help!!

**Comment by return42** [comment]
> I then noticed that your docker was wonderfall/searx while I had searx/searx installed.

Sorry, it was not clear that you are using docker installation ... searx/searx is a image without filtron and morty see: [For an easy to install, battery included setup: https://github.com/searx/searx-docker (include this image, Filtron, Morty and searx-checker)](https://hub.docker.com/r/searx/searx).

For others having problems with docker, please read https://asciimoo.github.io/searx/admin/installation-docker.html first, before blindly picking up images from docker hub.
