### ISSUE TITLE
Cannot set GET method by default

### ISSUE THREAD

**Issue by Pollockwar** [searx/searx#2068]
Hello,

I'm trying to select the GET method by default on my instance.
I tried adding this in preference.py :
	    'method': EnumStringSetting(
		settings['search']['method'] or 'POST',
	        choices=('GET', 'POST')
	    ),

and method = "GET" in settings.yml

The GET method is now displaying in the preferences and in the cookies, but the queries still use the POST method.

Can someone help me ?

Thanks

**Comment by return42** [comment]
> The GET method is now displaying in the preferences and in the cookies, but the queries still use the POST method.

Queries from the index.html page? Or queries from browser's default engine (URL bar).

If it is just only the case for queries from the  URL bar remove the searx entry from browser's search engines list, goto searx's preferences press "Reset Defaults" and then re-add searx to your browser's search engines list.

**Comment by unixfox** [comment]
I can't replicate the issue described.

Turning method to true in the settings.yml forces every requests to GET:
```yml
server:
  method: "GET"
```
