### ISSUE TITLE
strange issue with suggestions

### ISSUE THREAD

**Issue by lonnietc** [searx/searx#2070]
Hello,

I am running searx and testing some things here for which I may have made a change in the default settings.yml file, but now I do not seem to be getting "suggestions" after a query.

Is there a particular setting either in the preference or in the settings.yml file that I cold have gotten messed up?

Cheers

**Comment by unixfox** [comment]
Are you referring to the suggestions from the search bar of your browser or from the home page of Searx?

**Comment by lonnietc** [comment]
Hello,

Sorry for the confusion.

I was meaning for Searx when you make a search. It used to return some "suggestions" for example if I were to search for "SpaceX" then I would get some suggestions returned as well either via the web browser or API calls with  the JSON having some suggestions instead of being empty.

I am trying to determine if there is a particular engine in the preferences that tend to return suggestion and if that engine is turned off then no suggestions would be returned.

Thanks

**Comment by lonnietc** [comment]
I just did a fresh install of the latest SearX and it all seems to be working now.

Thanks again
