### ISSUE TITLE
RSS feed disabled: Why?

### ISSUE THREAD

**Issue by gloschtla** [searx/searx#2072]
I once saved the URL to fetch the RSS feed. But now it says: _Rate limit exceeded ..._ OR: _This feature is deactivated because of abuse._
Now, if you press on "RSS", then you don't get any URL to fetch it. 

When will we find a reliable alternative to Google Alerts? Is rss bridge the only one? https://rss-bridge.snopyta.org/#bridge-GoogleSearch

**Comment by unixfox** [comment]
The feed RSS is disabled by an external program on some Searx instances. This external program is called filtron.
RSS feed can't be disabled into Searx and you will be able to find Searx instances that still have it available on https://searx.space
