### ISSUE TITLE
Feature Req: Custom description length (default is 3 lines)?

### ISSUE THREAD

**Issue by extralight** [searx/searx#2075]
Is it possible to have an option in preferences for a customized description length?

**Comment by unixfox** [comment]
What do you mean by customized description length? Do you mean a description that should appear in the home page?
I don't understand your feature request, please be more descriptive.

**Comment by unixfox** [comment]
Closing as a lack of replies and clear description of the feature request.

Please reopen with a correct description of what you want.

**Comment by extralight** [comment]
![searx_20210114_customizable_description](https://user-images.githubusercontent.com/67835718/104630589-d72a0000-5692-11eb-8e73-8988909f6d44.jpg)

**Comment by extralight** [comment]
Also would it be possible to show how long it took you to return the results. Sometimes just 1 site may be responsible for making the search slow.

Inside preferences you do show that, but its not 'live'.

This can also be an option in preferences.

![searx_20210114_time_to_retrieve results](https://user-images.githubusercontent.com/67835718/104632820-2a518200-5696-11eb-8cc7-d278da5e1adb.jpg)

**Comment by unixfox** [comment]
There is no "longer description", Searx fetch the whole description of the engine (google or ddg or yahoo) and then display it to the user. Usually the description for Google is just 2 lines and that's it. We can't do much about it.

About the need of a description, well we can't do much about it because the API of the engine (ddg definitions and wikipedia) just don't return one.

**Comment by unixfox** [comment]
> Also would it be possible to show how long it took you to return the results.
> 
> ![searx_20210114_time_to_retrieve results](https://user-images.githubusercontent.com/67835718/104632820-2a518200-5696-11eb-8cc7-d278da5e1adb.jpg)

Please open a new issue if you are interested in that feature. I don't want to have a big issue with a lot of feature requests at the same time.

-----

I'm closing this issue because I think I answered to your initial question. Again if you want to have the time that it took for an engine to respond please open a new issue.

**Comment by extralight** [comment]
Wikipedia does return descriptions.

![searx_wikipedia_showing_description_20210115_000458](https://user-images.githubusercontent.com/67835718/104633724-7e109b00-5697-11eb-8a34-d0f08afe9927.png)

**Comment by unixfox** [comment]
> Wikipedia does return descriptions.
> 
> ![searx_wikipedia_showing_description_20210115_000458](https://user-images.githubusercontent.com/67835718/104633724-7e109b00-5697-11eb-8a34-d0f08afe9927.png)

No the description is from Google, Searx is just merging the results from all the engines into one. Do a search on Google and you will see the same description.

**Comment by extralight** [comment]
I understand. 
Since searx is a large organization, would the many wiki and other sites add new APIs if you request them to do so?

I feel its pretty important to have descriptions (longer the better too).

I almost always click on something only when I have confirmed that this is what I want (Something that happens unconsciously inside my head). And that is normally from the description.

**Comment by unixfox** [comment]
> I understand.
> Since searx is a large organization, would the many wiki and other sites add new APIs if you request them to do so?
> 
> I feel its pretty important to have descriptions (longer the better too).
> 
> I almost always click on something only when I have confirmed that this is what I want (Something that happens unconsciously inside my head). And that is normally from the description.

I don't think the Searx maintainers will ask directly to the concerned engines to expand the length of the description. We don't have that much time as you would think (we are just 2 active maintainers), and we prefer to spend on fixing bugs and adding popular features.

Also, most of the engines don't accept what Searx is doing, especially Google which try its best to block Searx. See https://github.com/searx/searx/issues/729 for that. So if in the first place the concerned engines don't want us then I don't think they will listen to us for new features like expanding the size of the description.

But you may try yourself to ask to engines that offer a proper API like Wikidata to offer a description in their API or expand the length of the description.
