### ISSUE TITLE
bangs.json is undistributable

### ISSUE THREAD

**Issue by josch** [searx/searx#2076]
Hi,

I was just packaging the new searx release 0.17.0 (thanks for that!) for the Debian distribution. I noticed that the file `bangs.json` contains several favicons as `data:image/png;base64,...`. I doubt that you have the copyright on those icons? What is the copyright situation on them? I suppose that they are not distributed under a free license?

Assuming the latter, we currently have to completely remove `bangs.json` from the Debian package because patching out the offending favicons would still be a copyright violation because the copyrighted material would then be part of the patch removing them.

Can you advise for a better solution than shipping an empty `bangs.json`?

Thanks!

cheers, josch

**Comment by return42** [comment]
@josch thanks a lot for your remark .. releasing THIS bangs.json file was to early.  We also have other doubt / see issue https://github.com/asciimoo/searx/issues/2045 

We are working on a solution / I mark this issue as "bug"

OT:  just for my interest .. 
> I was just packaging the new searx

can you show me some links to the packaging git-repos / thanks!

**Comment by dalf** [comment]
```grep -v "favicon" bangs.json``` ?

searx don't use them.

**Comment by return42** [comment]
> searx don't use them.

But we distribute them / this is the problem.  _We distribute "bloatware"_ :)

**Comment by josch** [comment]
> OT: just for my interest ..
> > I was just packaging the new searx
>
> can you show me some links to the packaging git-repos / thanks!

Sure! All the important stuff is linked from this page: https://tracker.debian.org/pkg/searx

For example on the right-hand-side you see the link to the packaging git: https://salsa.debian.org/debian/searx

Probably most interesting to you are the changes to searx we use in Debian which you can find in `./debian/patches`: https://sources.debian.org/src/searx/0.16.0+dfsg1-2/debian/patches/

Or how we build it, which can be found in `./debian/rules`: https://sources.debian.org/src/searx/0.16.0+dfsg1-2/debian/rules/

Or the stuff we remove because of copyright problems or because it's minified or otherwise not "source", as can be seen under `Files-Excluded` in `debian/copyright`: https://sources.debian.org/src/searx/0.16.0+dfsg1-2/debian/copyright/

Relevant issue: https://github.com/asciimoo/searx/issues/814

Generally speaking, my life would be made much easier, if searx would not ship stuff it dosen't have the copyright for (for example what this issue is about), stuff that it doesn't know the copyright about (see the issue I quote above this paragraph) or stuff that is the **output** of a build (like minified javascript) instead of just the sources.
