### ISSUE TITLE
cache control / cache backend

### ISSUE THREAD

**Issue by ghost** [searx/searx#2078]
Hi @asciimoo, @dalf and guys,

Hope you are all doing well !

I was wondering if there is a cache backend for searx ? like redis/memcache

And, is it possible to manage the cache control expiry date for json formatted responses ?

Thanks in advance for your insights and inputs about that.

Cheers,
X

**Comment by unixfox** [comment]
There is no built-in cache but Searx send an Etag that can be used by the client in order to cache the resource.

**Comment by dalf** [comment]
my-spot, a fork of searx, implements a redis cache: https://gitlab.e.foundation/e/cloud/my-spot/-/commit/ebd5dee0262db73b6a56c028ac9e88b832e2646f . I guess you can nearly cherry-pick the commit without trouble.
 
If you use redis and make the instance public, please provide this information when you register your instance.

There are ETag on the static files but not the search results.

(not sure if it is your question)

**Comment by ghost** [comment]
@dalf merci beaucoup !!! that's absolutely what I needed.

Why it is not merged into searx ? it is a must have for scalability.

Will have a try tomorrow, keep u updated

**Comment by unixfox** [comment]
> @dalf merci beaucoup !!! that's absolutely what I needed.
> 
> Why it is not merged into searx ? it is a must have for scalability.
> 
> Will have a try tomorrow, keep u updated

If you would like to have that merged into Searx then feel free to open a PR for that :).

**Comment by ghost** [comment]
too much pending PR for hoping to be merged...

**Comment by asciimoo** [comment]
> If you would like to have that merged into Searx then feel free to open a PR for that :).

Please don't open PR. This feature is problematic from multiple aspects.
First and most important is privacy: Storing previous searches can compromise privacy even more than logging.
Second, it brings up quite a lot technical difficulties which cannot be solved consistently. To mention just a few:
 - Cache invalidation can't be done right, there is no expiration info for each of the results
 - There is no way to get notified if there are new results exist in the remote search engines for a cached search so results can be inaccurate
 - Ranking of the results cannot change dynamically
 - Dead link checking requires other services which increases the complexity of searx and it can also reduce privacy

**Comment by ghost** [comment]
Thanks for the clarification.

@dalf are you french ? so am I ^^. Do you mind if I ask you some questions about the caching in a twitter DM so we do not pollute the searx's issues ? 

My handle is https://twitter.com/x0rzkov
