### ISSUE TITLE
bangs.json encoding='utf-8' error

### ISSUE THREAD

**Issue by meaz** [searx/searx#2083]
I've searx installed on a debian stretch Vagrant instance. I've updated it to master, and now, I have the exact same error as here: [https://github.com/asciimoo/searx/issues/2041](https://github.com/asciimoo/searx/issues/2041):
```
Traceback (most recent call last):
  File "/var/www/searx/searx/webapp.py", line 74, in <module>
    from searx.search import SearchWithPlugins, get_search_query_from_webapp
  File "/var/www/searx/searx/search.py", line 32, in <module>
    from searx.external_bang import get_bang_url
  File "/var/www/searx/searx/external_bang.py", line 12, in <module>
    with open(join(searx_dir, 'data/bangs.json'), encoding='utf-8') as json_file:
TypeError: 'encoding' is an invalid keyword argument for this function
```
So it doesn't seem to be fixed, whereas I found this: [https://github.com/asciimoo/searx/pull/2059](https://github.com/asciimoo/searx/pull/2059) so it should be...

`locale` gives me:
```
LANG=en_US.UTF-8
LANGUAGE=en_US.en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

What should I do to have it work?

**Comment by return42** [comment]
> and now, I have the exact same error as here: #2041:

sure? You have 

     TypeError: 'encoding' is an invalid keyword argument for this function

while #2041 has 

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31341: ordinal not in range(128)

> locale gives me:

is this the output from your normal user login or from the service under which searx is running.

How did you installed searx, I guess you have used apache but not uwsgi?

Did you read our manual https://asciimoo.github.io/searx/admin/installation.html ?

**Comment by dalf** [comment]
Debian stretch uses Python 2 by default. If I'm correct, can you try with python3 ?

**Comment by meaz** [comment]
I see that the installation process has changed a bit. I'm using an ansible role, so I guess the issue is that I need to update it now ;)

**Comment by return42** [comment]
python 2 is no longer supported.
