### ISSUE TITLE
"append" form parameter idea

### ISSUE THREAD

**Issue by resynth1943** [searx/searx#2084]
So, this idea encompasses a secondary form variable: `append`. Basically, the value of `append` would be directly appended to `q`, like so: `q + append`.

This would be **very** useful for site-search, where you need to append `site:example.com` to the query. Right now, this relies on unstable JavaScript hacks.

See below for a use case.

```html
<form method="POST" target="searx instance goes here">
  <input type="hidden" name="append" value=" site:example.com" />
  <input type="text" name="q" placeholder="Search example.com..."
</form>
```

If I remember correctly, Google implements a form parameter just for `site:...`, but `append` would be more universal. Not all the engines support `site:`, so this might be a better idea.

**Comment by unixfox** [comment]
Closing in favor of https://github.com/searx/searx/issues/1008
