### ISSUE TITLE
Is it possible instal searx on windows? 

### ISSUE THREAD

**Issue by SanitarDurkiBlya** [searx/searx#2085]
It's not really comfortable to open vm every time i want to search something

**Comment by unixfox** [comment]
It's possible to use the docker version of searx on Windows.

**Comment by unixfox** [comment]
@SanitarDurkiBlya did you succeed to install searx on Windows with the help of Docker?

**Comment by unixfox** [comment]
I'm going to close this for now but if you arrived here from a search engine then here is how to run searx on windows:
1. Install python from Microsoft Store or the official website: https://www.python.org/downloads/windows/
2. Download the searx source code: https://github.com/searx/searx/archive/master.zip
3. Extract it somewhere.
5. Open the command line and cd to the directory of the extracted .zip.
6. Run `pip install -r requirements.txt`
7. Then `python searx/webapp.py`.

You can also install [Docker](https://docs.docker.com/docker-for-windows/install/) and run the `searx/searx` Docker image. Here are the instructions for that: https://searx.github.io/searx/admin/installation-docker.html
