### ISSUE TITLE
On mobile, the Links box obscures results

### ISSUE THREAD

**Issue by resynth1943** [searx/searx#2086]
The Links are in the way of the real results, when they should be at the bottom of the page. On mobile, this obscures a lot of the real results.

![Screenshot_20200720-134215](https://user-images.githubusercontent.com/49915996/87938798-01f21d80-ca8f-11ea-9bed-f7fc9c461141.png)

**Comment by bat999** [comment]
> FYI, the "simple" theme hides the links are hidden on mobile.

Yes, that's a big improvement for mobile users. Though it could be better imho.
The Simple result for "yay" on smartphone has ten links with brief descriptions plus some other junk ("Suggestions").

When I set theme to Simple and "save" and set it as default search engine, it then gives Simple results when searching from URL window too.
That's OK, will probably need to be reset if I clear out the cookies in browser history.


For mobile users **DuckDuckGo LITE** is the tops.

Or **with regular DuckDuckGo set as default search engine** in Chrome do a search like this... `!lite yay`
What I get on smartphone is 24 links with brief descriptions.
Not much empty white space and no cruft.

That's the sort of thing that many mobile users prefer, think low-spec devices with small screens. ;-)

**Comment by bat999** [comment]
Hi
This is working very well for me now.
With "Simple" theme.
Better than DuckDuckGo LITE.

Stripped it down to only six engines...
bing
duckduckgo
gigablast
google
qwant
mojeek

It doesn't show any "Preferences" tab on the home page or results page.
Probably because the screen is so small.
So I have bookmarked the preference page.
example...
https://searx.info/preferences

**Comment by bat999** [comment]
> FYI, the "simple" theme hides the links are hidden on mobile.

Hi
When I use Simple theme with my smartphone it's a very good experience.

But at the top of the results page I get a lot of "Suggestions".

Maybe they are churned out by the search engines.

I don't think these are much use.

For the Simple theme with mobile probably it would be better if they are hidden too along with those links.

![suggestions](https://user-images.githubusercontent.com/640761/89064533-12917600-d362-11ea-801f-6d133315d14d.jpg)

**Comment by bat999** [comment]
**"Links should be at the bottom**"
This isn't such a good idea.

As somebody has said in a different post...
"**...if Infinite Scroll plugin is on... never gonna see boxes which are present at the bottom of the page, unless they exhaustively scroll to the bottom...**"

I think it would be useful to have extra options in "Preferences" something like this...

```
Enable/Disable "Infobox" in Search Engine Results Pages (SERPs)

Enable/Disable "Links" in Search Engine Results Pages (SERPs)

Enable/Disable "Suggestions" in Search Engine Results Pages (SERPs)
```

**Comment by resynth1943** [comment]
Perhaps we could make the `Links` box a `<details>` on mobile? See example:

<details>
  <summary>this is my title</summary>
  <p>hello world</p>
</details>
