### ISSUE TITLE
Error running searx due to recent cryptography update

### ISSUE THREAD

**Issue by WulftheNordicRanger** [searx/searx#2087]
I got an error when trying to install searx on a vps and after some poking, I believe it's due to a cryptography update that recently came out 
Here is the error message: 

/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
Traceback (most recent call last):
  File "searx/webapp.py", line 74, in <module>
    from searx.search import SearchWithPlugins, get_search_query_from_webapp
  File "/usr/local/searx/searx/search.py", line 32, in <module>
    from searx.external_bang import get_bang_url
  File "/usr/local/searx/searx/external_bang.py", line 12, in <module>
    with open(join(searx_dir, 'data/bangs.json'), encoding='utf-8') as json_file:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by return42** [comment]
same as #2083 / python 2 is no longer supported.

**Comment by HLFH** [comment]
@WulftheNordicRanger Please upgrade to Python 3.
