### ISSUE TITLE
how to start searx on boot laptop?

### ISSUE THREAD

**Issue by azamet90** [searx/searx#2088]
i did installed searx using this guide: https://asciimoo.github.io/searx/admin/installation-searx.html#installation-basic
what to do that it runs on every boot?

**Comment by unixfox** [comment]
You need to add a systemd service for that. Here is an example (not for searx): https://gist.github.com/danechitoaie/f2bb03fd0c2d6b803878

Maybe @return42 could add one on the installation guide.

**Comment by azamet90** [comment]
> You need to add a systemd service for that. Here is an example (not for searx): https://gist.github.com/danechitoaie/f2bb03fd0c2d6b803878
> 
> Maybe @return42 could add one on the installation guide.

thx for answer!
after i did these steps https://asciimoo.github.io/searx/admin/installation-uwsgi.html and make it run on boot but now i cannot change any settings?
i mean i cannot change any settings if i run it with **sudo -H service uwsgi start searx**

**Comment by return42** [comment]
What speaks against installing it as [recommended (incl. bot blocker & reverse proxy)](https://asciimoo.github.io/searx/admin/installation.html) in 5min by using the scripts / do you ave any special requirement?

> Maybe @return42 could add one on the installation guide.

I can do, but I don't think it really helps / most of the issues here are coming from individuals installing searx without a bot blocker and a reverse proxy. I think we should not support every individuals, the installation instructions are complex enough for our _reference_ installation. It might be better to add more distros to our installation routines.

**Comment by azamet90** [comment]
> What speaks against installing it as [recommended (incl. bot blocker & reverse proxy)](https://asciimoo.github.io/searx/admin/installation.html) in 5min by using the scripts / do you ave any special requirement?
> 
> > Maybe @return42 could add one on the installation guide.
> 
> I can do, but I don't think it really helps / most of the issues here are coming from individuals installing searx without a bot blocker and a reverse proxy. I think we should not support every individuals, the installation instructions are complex enough for our _reference_ installation. It might be better to add more distros to our installation routines.

Install searx service option on that link was giving me many errors so I did the step by step guide and mix it with another tutorial little bit because of the guide is not works on my kali Linux now it is installed but I only cannot change the settings and preferences if I run sudo -H service uwsgi start searx
I did tryed to change the owner from searx to my laptop user but result was same :( it was looks cool I still use it even if it's not works for me completely but it will be very nice if I can change the preferences from browser...

**Comment by return42** [comment]
> of the guide is not works on my kali Linux

Sorry I can't help .. may be others know more ..

update: add doc tag / may be there comes the day I have time to add KALI to the list of supported distros

**Comment by virtadpt** [comment]
@azamet90 I did what you want to do a while back with Searx.  I can copy-and-paste my systemd .service file for you.  It's for systemd-in-usermode.

**Comment by azamet90** [comment]
> @azamet90 I did what you want to do a while back with Searx. I can copy-and-paste my systemd .service file for you. It's for systemd-in-usermode.

i can now start it on boot my only problem is i cannot change preferences from web panel from searx

**Comment by unixfox** [comment]
@azamet90 is this still an issue? Did you solve your problem?

**Comment by unixfox** [comment]
The official scripts offer to install Searx as a service and make it to start as the same time as the computer boot.
