### ISSUE TITLE
Installing on a remote computer via ssh

### ISSUE THREAD

**Issue by ah1102** [searx/searx#2089]
I apologize for the stupid question. I am trying to install searX on a second computer via ssh protocol.

Instead of the ~ / Downloads folder, I created a ~ / searx folder, and when executing the sudo -H ./utils/searx.sh install all script, it gives an error:

![Снимок экрана 2020-07-21 в 17 58 26](https://user-images.githubusercontent.com/58341369/88071508-98e8d380-cb7c-11ea-9c28-5127ca5d42ed.png)

Installation comes from the root user.
What do I need to do for the installation to continue?

**Comment by return42** [comment]
see https://github.com/asciimoo/searx/issues/2017#issuecomment-647700327
