### ISSUE TITLE
Wikipedia crash on specific search query

### ISSUE THREAD

**Issue by onmyouji** [searx/searx#2090]
Instance: searx.be
Browser: Chrome Version 84.0.4147.89

Hello,

Not sure whether this is a bug, problem with the instance itself , or my browser, but when I search for certain query e.g. `port dover`, I get an error message:
```
Engines cannot retrieve results:
wikipedia (unexpected crash 'NoneType' object has no attribute 'replace')
```

![Image 6](https://user-images.githubusercontent.com/8424198/88169288-fc8b0380-cc45-11ea-98ea-c1b897b40273.png)

This error doesn't happen if I change the language to Deutsch, Espanol, or other language. Seems like it only happens with English language.  

![Image 2](https://user-images.githubusercontent.com/8424198/88170044-33154e00-cc47-11ea-8560-2711f8323bd6.png)

![Image 3](https://user-images.githubusercontent.com/8424198/88170063-3d374c80-cc47-11ea-9ad6-5bd75e1eaa18.png)

This error doesn't happen with other search query.

![Image 4](https://user-images.githubusercontent.com/8424198/88170309-ad45d280-cc47-11ea-85bc-e7ce87ba76a3.png)

I also test this on other searx instances and the results are mixed. 

No error:
https://searx.ninja
https://search.snopyta.org/
Both are still on 0.16.0

Same error:
https://searx.fmac.xyz
https://searx.xyz/

**Comment by return42** [comment]
> Not sure whether this is a bug, problem with the instance itself , or my browser ..

Its a problem of the instances.

**Comment by onmyouji** [comment]
Oh ok thanks

**Comment by return42** [comment]
> Oh ok thanks

No problem, feel welcome ..  if you are looking for well maintained instances .. you can use [searx.be from @unifox ](https://github.com/asciimoo/searx/issues/1977#issuecomment-636300719) or even mine [darmarit.org/searx](https://github.com/asciimoo/searx/issues/1977#issuecomment-636293224).

**Comment by onmyouji** [comment]
Seems like your instance also gives the same error. But no error when I change to other language.

![Image 5](https://user-images.githubusercontent.com/8424198/88175713-73c59500-cc50-11ea-8936-954c34d94103.png)

**Comment by return42** [comment]
> Seems like your instance also gives the same error. 

Wow, haven't seen this before (since I use de) / thanks for the hint!

I reopen the issue / if I have time, I will check twice what is going wrong here.

**Comment by MarcAbonce** [comment]
I broke this with #1686. The obvious solution would be to simply validate that `summary` is not `None`, which would cause searx to return the infobox with no error but also with no paragraph. That's because the [extract_first_paragraph](https://github.com/asciimoo/searx/blob/master/searx/engines/wikipedia.py#L52) function in the wikipedia engine is a mess. 
I'm going to check out the Wikipedia API again and try a bunch of tests, because I think in the last years they have fixed a lot of the issues that our code was working around.

**Comment by qbitroot** [comment]
Also search query "WSGI" crash wikipedia with same error: `Engines cannot retrieve results: wikipedia (unexpected crash 'NoneType' object has no attribute 'replace')`. I am using SearX on Ubuntu 18.04 on localhost installed with uWSGI. Using English as default language. Tried different themes, same result.

**Comment by qbitroot** [comment]
Made some research and figured out that sometimes wikipedia api don't return full info. For example, for query "wsgi" it returns this (`resp.text`):
`{"batchcomplete":"","query":{"normalized":[{"from":"wsgi","to":"Wsgi"}],"redirects":[{"from":"Wsgi","to":"Web Server Gateway Interface"}],"pages":{"1441500":{"pageid":1441500,"ns":0,"title":"Web Server Gateway Interface","extract":""}}}}`
Please note that `extract` is empty. I think Searx Wikipedia engine should follow redirects given from Wikipedia API.

**Comment by qbitroot** [comment]
Made an API request manually with Python, response is correct. Perhaps something is wrong with SearX html parser.
Edit: I discovered that for some reason function `search_one_http_request` (line 84, file `searx/search.py`) receives that empty response from API
