### ISSUE TITLE
Bing search engine doesn't seem to be working.

### ISSUE THREAD

**Issue by bat999** [searx/searx#2092]
Hi
It seems like Bing search engine isn't working.
Screenshot shows version 0.17.0-10-6e37255e from suche.uferwerk.

![bing](https://user-images.githubusercontent.com/640761/88254298-c2a11800-ccac-11ea-87d6-bf6357f0a0f5.jpg)

**Comment by unixfox** [comment]
Probably related to #2019

**Comment by bat999** [comment]
Yes, `!bi foo` works ok with searx.be
This comment ---> https://github.com/asciimoo/searx/issues/1933#issuecomment-617413748

**Comment by bat999** [comment]
https://github.com/asciimoo/searx/issues/1933#issuecomment-617413748
This comment explains it.
