### ISSUE TITLE
http://127.0.0.1:8888 not available / permission denied, searx.ini does not exist and uwsgi not implemented

### ISSUE THREAD

**Issue by el-cpu** [searx/searx#2095]
Trisquel 9 (based on Ubuntu 18.04)

Output of sudo -H ./utils/searx.sh install all

:~/searx$ sudo -H ./utils/searx.sh install all
ERROR: trisquel-9.0: nginx not yet implemented
ERROR: trisquel-9.0: apache not yet implemented
ERROR: trisquel-9.0: uWSGI not yet implemented
ERROR: trisquel-9.0: pkg_install LXC_BASE_PACKAGES not yet implemented

===================
searx@192.168.1.73 
===================

Install searx@192.168.1.73  (service)
=====================================

installation of packages
------------------------

package(s)::

Should packages be installed? [YES/no] 
Yes
** press any [KEY] to continue **

user searx
----------

useradd --shell /bin/bash --system  --home-dir "/usr/local/searx"  --comment 'Privacy-respecting metasearch engine' searx
useradd: user 'searx' already exists
mkdir "/usr/local/searx"
mkdir: cannot create directory ‘/usr/local/searx’: File exists
chown -R "searx:searx" "/usr/local/searx"
groups searx
-->|searx : searx
** press any [KEY] to continue **

Clone searx sources
-------------------

/usr/local/searx/.profile: line 1: /usr/local/searx/searx-pyenv/bin/activate: No such file or directory
INFO:  already cloned: /usr/local/searx/searx-src
  |searx| /usr/local/searx/.profile: line 1: /usr/local/searx/searx-pyenv/bin/activate: No such file or directory
cd "/usr/local/searx/searx-src"
git checkout -m -B "master" --track "origin/master"
git pull --all
  |searx| Reset branch 'master'
  |searx| Branch 'master' set up to track remote branch 'master' from 'origin'.
  |searx| Your branch is up to date with 'origin/master'.
  |searx| Fetching origin
  |searx| Already up to date.
  |searx| /usr/local/searx/.profile: line 1: /usr/local/searx/searx-pyenv/bin/activate: No such file or directory
cd "/usr/local/searx/searx-src"
git remote set-url origin https://github.com/asciimoo/searx
git config user.email "root@candra"
git config user.name "root"
git config --list
  |searx| core.repositoryformatversion=0
  |searx| core.filemode=true
  |searx| core.bare=false
  |searx| core.logallrefupdates=true
  |searx| remote.origin.url=https://github.com/asciimoo/searx
  |searx| remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
  |searx| branch.master.remote=origin
  |searx| branch.master.merge=refs/heads/master
  |searx| user.email=root@candra
  |searx| user.name=root
** press any [KEY] to continue **

Create virtualenv (python)
--------------------------

INFO:  create pyenv in /usr/local/searx/searx-pyenv
  |searx| /usr/local/searx/.profile: line 1: /usr/local/searx/searx-pyenv/bin/activate: No such file or directory
rm -rf "/usr/local/searx/searx-pyenv"
python3 -m venv "/usr/local/searx/searx-pyenv"
grep -qFs -- 'source /usr/local/searx/searx-pyenv/bin/activate' ~/.profile   || echo 'source /usr/local/searx/searx-pyenv/bin/activate' >> ~/.profile
  |searx| The virtual environment was not created successfully because ensurepip is not
  |searx| available.  On Debian/Ubuntu systems, you need to install the python3-venv
  |searx| package using the following command.
  |searx| 
  |searx|     apt-get install python3-venv
  |searx| 
  |searx| You may need to use sudo with that command.  After installing the python3-venv
  |searx| package, recreate your virtual environment.
  |searx| 
  |searx| Failing command: ['/usr/local/searx/searx-pyenv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
  |searx| 
INFO:  inspect python's virtual environment
  |searx| /usr/local/searx/.profile: line 1: /usr/local/searx/searx-pyenv/bin/activate: No such file or directory
command -v python && python --version
  |searx| /usr/bin/python
  |searx| Python 2.7.17
** press any [KEY] to continue **
INFO:  install needed python packages
  |searx| /usr/local/searx/.profile: line 1: /usr/local/searx/searx-pyenv/bin/activate: No such file or directory
pip install -U pip
  |searx| -bash: line 1: pip: command not found
pip install -U setuptools
  |searx| -bash: line 2: pip: command not found
pip install -U wheel
  |searx| -bash: line 3: pip: command not found
pip install -U -e .
  |searx| -bash: line 4: pip: command not found
cd /usr/local/searx/searx-src
pip install -e .
  |searx| -bash: line 6: pip: command not found
** press any [KEY] to continue **

/etc/searx/settings.yml
-----------------------

Diff between origin's setting file (+) and current (-):

--- /etc/searx/settings.yml	2020-07-23 16:09:41.666547049 -0400
+++ /usr/local/searx/searx-src/searx/settings.yml	2020-07-23 13:15:38.520934900 -0400
@@ -12,7 +12,7 @@
 server:
     port : 8888
     bind_address : "127.0.0.1" # address to listen on
-    secret_key : "51f1df0434d5631422f57419ec01eb9e" # change this!
+    secret_key : "ultrasecretkey" # change this!
     base_url : False # Set custom base_url. Possible values: False or "https://your.custom.host/location/"
     image_proxy : False # Proxying image results through searx
     http_protocol_version : "1.0"  # 1.0 and 1.1 are supported
Menu::
  1.) keep configuration unchanged [default]
  2.) use origin settings
  3.) start interactiv shell
What should happen to the settings file?  [1] 

INFO:  leave settings file unchanged
** press any [KEY] to continue **

Testing searx instance localy
-----------------------------

  |searx| /usr/local/searx/.profile: line 1: /usr/local/searx/searx-pyenv/bin/activate: No such file or directory
export SEARX_SETTINGS_PATH="/etc/searx/settings.yml"
cd /usr/local/searx/searx-src
timeout 10 python searx/webapp.py &
sleep 3
curl --location --verbose --head --insecure 127.0.0.1:8888
  |searx| [E] install pyyaml
  |searx| * Rebuilt URL to: 127.0.0.1:8888/
  |searx| *   Trying 127.0.0.1...
  |searx| * TCP_NODELAY set
  |searx|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  |searx|                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connect to 127.0.0.1 port 8888 failed: Connection refused
  |searx| * Failed to connect to 127.0.0.1 port 8888: Connection refused
  |searx| * Closing connection 0
  |searx| curl: (7) Failed to connect to 127.0.0.1 port 8888: Connection refused
** press any [KEY] to continue **

Install searx's uWSGI app (searx.ini)
-------------------------------------

INFO:  installing uwsgi ...

installation of packages
------------------------

package(s)::

Should packages be installed? [YES/no] 
Yes
INFO:  prepare (searx:searx)  /run/uwsgi/app/searx
mkdir: cannot create directory ‘’: No such file or directory
INFO:  install (eval=1): /searx.ini
ERROR: /home/candra/searx/utils/templates/searx.ini does not exists
ERROR: ... can't install /searx.ini
** press any [KEY] to continue **
ERROR: trisquel-9.0: uWSGI not yet implemented
INFO:  restart uWSGI service
ERROR: trisquel-9.0: uWSGI not yet implemented
INFO:  uWSGI app: searx.ini is installed
ERROR: URL http://127.0.0.1:8888 not available, check searx & uwsgi setup!

Do you want to inspect the installation? [NO/yes] 

Filtron successfully installed and works at port 4004. If I try to go to http://127.0.0.1:8888 it says page not found

Then if choose yes on last question:

Do you want to inspect the installation? [NO/yes] y

service status & log
====================

sourced .config.sh :

  PUBLIC_URL          : http://192.168.1.73/searx
  SEARX_URL_PATH      : /searx
  SEARX_INSTANCE_NAME : searx@192.168.1.73 
  SEARX_INTERNAL_HTTP  : 127.0.0.1:8888

INFO:  Service account searx exists.
ERROR: ~searx: python environment is not available!
INFO:  ~searx: Searx software is installed.
ERROR: trisquel-9.0: uWSGI not yet implemented
ERROR: uWSGI app searx.ini not enabled!
INFO:  public URL   --> http://192.168.1.73/searx
INFO:  internal URL --> http://127.0.0.1:8888
ERROR: uWSGI app (service) at http://127.0.0.1:8888 is not available!
[CTRL-C] to stop or [KEY] to continue
WARN:  Public service at http://192.168.1.73/searx is not available!
WARN:  Check if public name is correct and routed or use the public IP from above.

Enable searx debug mode? [NO/yes] y
WARN:  Do not enable debug in production enviroments!!
INFO:  try to enable debug mode ...
  |searx| mesg: ttyname failed: Inappropriate ioctl for device
cd /usr/local/searx/searx-src
sed -i -e "s/debug : False/debug : True/g" "/etc/searx/settings.yml"
INFO:  restart uWSGI service
ERROR: trisquel-9.0: uWSGI not yet implemented

// use CTRL-C to stop monitoring the log

and it does not answer anymore.

**Comment by return42** [comment]
read the first message ..

> ERROR: trisquel-9.0: nginx not yet implemented

trisquel not supported by the intall-scripts

**Comment by el-cpu** [comment]
Ok is there way now to uninstall it or to install nginx, uwsgi etc. needed things so Trisquel would pass? Right now I have filtron working and can't delete, can't kill process, it starts again and again. I have a load of new passwd users around and I don't know what to do with them all with this half-installation.
