### ISSUE TITLE
Get image button from the Google Images engine doesn't give the raw URL to the image

### ISSUE THREAD

**Issue by unixfox** [searx/searx#2103]
When searching for images using the "Google Images" engine, the "Get image" button doesn't give the raw URL (that usually ends with `.jpg` or `.png`) to the image of every result.
In fact the button gives the same exact URL as the button "View source".

On other engines (like Bing images) it gives the raw URL to the image.

Here is a screenshot explaining the issue:
![getimagegoogleimages](https://user-images.githubusercontent.com/4016501/88662178-e19f1000-d0d9-11ea-8893-a7fc9798b82c.png)

Here is a URL for testing the bug: https://darmarit.org/searx/?q=%21goi+ok&time_range=&language=en-US&category_images=on

@return42 Any thoughts about that?

**Comment by return42** [comment]
I have to look at that, I remember that I was a bit confused about the different result URLs at some time. May be I made a mistake .. unfortunately I have no time this week to clarify / hope next week I can have a eye on it.

**Comment by qbitroot** [comment]
+1, issue appears only with google images, while other engines, such as qwant, duckduckgo and bing... work properly

**Comment by qbitroot** [comment]
I found out how to get real image url from search page.
Enter query at google images (Searx already do it)
![Screenshot from 2020-08-01 17-57-18](https://user-images.githubusercontent.com/66268477/89104328-441d4680-d421-11ea-8062-bfce36b81de1.png)
Inspect element by clicking right mouse button on image (Searx already search image element in request) and find image parents property `data-tbnid` or `data-id` (Searx don't do this, it retrieves `data:url`):
![Screenshot from 2020-08-01 17-57-34](https://user-images.githubusercontent.com/66268477/89104411-f81ed180-d421-11ea-8df0-6f3b05fffe48.png)
Then search this id in `<script nonce>` tag (in chrome devtools it is done by going to Source tab then `Ctrl+F` and pasting id). A line below will contain image URL (for me it was fourth occurrence):
![Screenshot from 2020-08-01 17-59-35](https://user-images.githubusercontent.com/66268477/89104574-f1dd2500-d422-11ea-828e-dbca7c9e3a78.png)
As you can see it is not small thumbnail image:
![Screenshot from 2020-08-01 18-01-32](https://user-images.githubusercontent.com/66268477/89104584-04575e80-d423-11ea-85cd-489ce8f8e0bc.png)
All we need is to implement obtaining that `data-id` and searching this in source code. But this can slow down image search. Or google images searx engine can just go through all these URLs at `<script nonce>` and return it to user. There are all required info for image (full URL, webpage where it is and title) :thinking: ...

**Comment by unixfox** [comment]
@gangural do you mind creating a PR for that?

**Comment by qbitroot** [comment]
@unixfox ok, I will do it if I succeed.

**Comment by qbitroot** [comment]
Almost done :smiley: ! Have to fix some bug that was caused by my code, will do it tomorrow

**Comment by qbitroot** [comment]
Oh my pull request didn't passed checks because it have one line between functions instead of 2 and no space around plus :sweat_smile:. Will edit now

**Comment by return42** [comment]
> A line below will contain image URL

@gangural thanks a lot for your analysis of the JS `<script>` which I want to confirm.

> it have one line between functions instead of 2 and no space around plus sweat_smile. 

Yes, nowadays the pep8 test is questionable, but it is what we have and I guess it is better than nothing.

> But this can slow down image search. 

The alternative is a JS parser which would be much slower than the static code analyser you implemented in PR #2115 / this was the reason why I implemented static code analysis for the thumbs.

I commented your PR #2115 / if you could have a look [there](https://github.com/asciimoo/searx/pull/2115#pullrequestreview-460104746) .. thanks!

**Comment by qbitroot** [comment]
@return42 thank you for your review! Pulled your branch to PR and ready for merging to `master`.

> The alternative is a JS parser which would be much slower than the static code analyser

Yes, this is the slowest way to do this task. JS parser could be used only if URL at script was too obfuscated etc.
