### ISSUE TITLE
autocomplete in the browser URL doesn't work

### ISSUE THREAD

**Issue by dalf** [searx/searx#2105]
Scenario:
* I pick one instance
* in the searx preferences, I select one autocomplete provider, then save
* in Firefox, I add the new search engine
* in the Firefox preferences, I select this new search engine as the default one
* in the Search bar, I type a query
* there is no autocomplete

I've replaced
https://github.com/asciimoo/searx/blob/fc5d1c69cc01ec1c44e5d2d9644269b6b737fa5a/searx/templates/__common__/opensearch.xml#L16
by
```html
<Url rel="suggestions" type="application/x-suggestions+json" template="{{ host }}autocompleter?q={searchTerms}"/>
```

but I'm not sure it works on http://localhost:8888

**Comment by qbitroot** [comment]
Cannot make it work on localhost. Using Google Chrome (want to switch to Firefox though).

**Comment by unixfox** [comment]
I haven't change anything and it works on my instance: https://searx.be
I'm using Firefox desktop

**Comment by dalf** [comment]
https://searx.be doesn't work for me (FF 79).

**Comment by Nebukadneza** [comment]
Hi,

I have the very same problem, also on FF 79. I can confirm autocomplete was enabled and working on-site before adding the search engine. Firefox gets and correctly parses the `opensearch.xml`. In the end, firefox does send a autocomplete request, which leads to a searx internal server error

```
DEBUG:searx.webapp:default locale from browser info is `en`
DEBUG:searx.webapp:selected locale is `en`
!! query parts is [b'']
ERROR:searx.webapp:Exception on /autocompleter [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/searx/searx/webapp.py", line 758, in autocompleter
    raw_text_query.parse_query()
  File "/usr/local/searx/searx/query.py", line 76, in parse_query
    if query_part[0] == '<':
IndexError: index out of range
[pid: 14|app: 0|req: 3/5] 192.168.96.2 () {44 vars in 662 bytes} [Fri Aug  7 12:21:29 2020] GET /autocompleter => generated 290 bytes in 4 msecs (HTTP/1.1 500) 4 headers in 150 bytes (1 switches on core 0)
```

Where the query was a `GET /autocompleter` … GET without any query-string or anything else.

looking at the opensearch spec, maybe we either somehow (not sure how) specify we want to `POST` with a `q`, or append something like  `?q={searchTerms}` to the `suggestion` entry in the XML? I tried the latter, which didn’t work out of the box, but I need to investigate a bit further …

**Comment by Nebukadneza** [comment]
Hi,

I tinkered around a bit more, and i think i found the cause. First, I could not make firefox issue any `POST` suggestions queries whatever i did. So, switching `opensearch.xml` to `method="get"` and appending a `?q={searchTerms}` was my startingpoint.

Furthermore, here:
https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L793
the original query string is only prepended, as it seems Firefox requires it, if there is a `format=x-suggestions` query parameter. However, no matter how i formatted the `content-type` or `rel` attributes in the `opensearch.xml`, i could not get a `format` parameter in the query from Firefox.

I then tried a dirty hack, and formatted the result in L797 in the way that i assumed Firefox wanted:
```
    return Response(json.dumps([raw_text_query.query, results]),
                    mimetype='application/json')
```

And tadah, suggestions worked!

… I’m not firm with either firefox, nor searx. Thus, I need some feedback on what the best path forward is here.

Thanks for this great project ^_^

**Comment by qbitroot** [comment]
@Nebukadneza Thank you for research! Can you create pull request for that please (if it's not difficult for you of course)?

**Comment by Nebukadneza** [comment]
I’d love to, but the problem is two-fold:
- Uses GET instead of POST, may not be up to the strict privacy standards regarding logging of Searx(?)
- Breaks autocompletion on the web-page, since there, the additional wrapping with the search-term is not expected

In the quick time I couldn’t figure out how to fiddle the frontend to either supply a parameter which might be used as a differentiator, or in the request handler find out if it’s the browser making a suggestions-call … :(

**Comment by Nebukadneza** [comment]
I found a way that’s … a bit hackish and unclean, but gets the job done. Would be glad about feedback and reviews~

**Comment by unixfox** [comment]
Sorry I didn't read all the comments but I wanted to let everyone know I discovered after posting this comment
> I haven't change anything and it works on my instance: [searx.be](https://searx.be)
> I'm using Firefox desktop

that my Firefox was sending GET requests for the autocomplete so that's why I thought it worked for me.
