### ISSUE TITLE
[Question] What is Scopia?

### ISSUE THREAD

**Issue by bat999** [searx/searx#2114]
Hi
Sometimes I have used MetaGer search engine.
There is...
metager.de in German
metager.org in English

With the English site it shows results from Bing and Scopia.
Also with the German site it shows results "von Scopia" and others.

But I can't find any information about Scopia.
(Yes, I have googled it!)
There's a link here ---> https://www.webmasterworld.com/search_engine_spiders/4762960.htm

Maybe Scopia is a crawlerbot that MetaGer has developed.
Maybe Scopia is a third-party crawlerbot that they use.
Or maybe it's something completely different.

Any ideas what is Scopia?

**Comment by virtadpt** [comment]
Could this be it?

https://www.webmasterworld.com/search_engine_spiders/4762960.htm

I haven't found much information about it other than it seems to be a search engine other meta-search engines use, but I also haven't don a whole lot of digging yet.

**Comment by bat999** [comment]
> Could this be it?
> 
> https://www.webmasterworld.com/search_engine_spiders/4762960.htm
> 
That's exactly the same link that I posted, lol.

> ... it seems to be a search engine other meta-search engines use...
**Yes, that's what I meant when I suggested... 
" third-party crawlerbot"**

**Comment by virtadpt** [comment]
I'm sorry.  I'm a little distracted right now.
