### ISSUE TITLE
Add Ecosia.org

### ISSUE THREAD

**Issue by Singustromo** [searx/searx#2119]
https://www.ecosia.org/

I've already tried to add it this way but it only works partially.
Sometimes there is no description or the wrong one.
It also seems to determine the language by the ip-location. No query for that as it seems.

```
  - name : ecosia
    engine : xpath
    paging : False
    search_url : https://www.ecosia.org/search?q={query}
    url_xpath : //div[@class="result-body"]/div[@class="result-firstline-container"]/h2/a/@href
    title_xpath : //div[@class="result-body"]/div[@class="result-firstline-container"]/h2/a/text()
    content_xpath : //a[@class="result-snippet-link"]/p[@class="result-snippet"]/text()
    categories : general
    shortcut : eco
```

**Comment by unixfox** [comment]
Do you think you could write this engine in python and open a PR?

**Comment by MarcAbonce** [comment]
This was previously discussed in #880 and  #1377.
The main problem is that searching Ecosia through searx would bypass their ads which is how they get the money to plant trees.

**Comment by unixfox** [comment]
It's safe to close then?

**Comment by Singustromo** [comment]
I have overseen these Issues.
That totally defeats the purpose of ecosia haven't thought about that.

I would really love to contribute something but I've never done something in python let alone any networking.
Thank you for these fast answers. :)
