### ISSUE TITLE
Bing images show improper results

### ISSUE THREAD

**Issue by qbitroot** [searx/searx#2122]
I know, this is problem of Bing, not Searx. I offer to exclude Bing images from default image engines.
### How to reproduce
 **Warning: some results can be 18+**.
Search for "!bing_images double rainbow" on any searx instance that supports searching at bing images and see results. If everything is OK, click Next page several times and you will see unrelated results. It can be annoying.
You can read more about this here:
[https://www.howtogeek.com/367878/bing-is-suggesting-the-worst-things-you-can-imagine/](https://www.howtogeek.com/367878/bing-is-suggesting-the-worst-things-you-can-imagine/)
[https://www.theverge.com/2018/10/10/17959328/bing-yahoo-offensive-search-suggestions-racism-antisemitism](https://www.theverge.com/2018/10/10/17959328/bing-yahoo-offensive-search-suggestions-racism-antisemitism)

**Comment by return42** [comment]
You can use instances where safe_search is activated by default / e.g. [mine](https://darmarit.org/searx/) :)

But be warned "False positives" are inherent of all filters. We just using the "save--browsing" filters from the origin engines.

I guess this issue is related to:

- https://github.com/asciimoo/searx/pull/1985#discussion_r438104259
- #636
- #1907
- #1392
- #1410

**Comment by unixfox** [comment]
> You can use instances where safe_search is activated by default / e.g. [mine](https://darmarit.org/searx/) :)

Or any other instance because safe search can be enabled in the preferences.

**Comment by qbitroot** [comment]
@return42 thank you for reply. When I said "improper" I meant not only NSFW content, Bing images often show results that are just unrelated (and safe search doesn't change it).

**Comment by qbitroot** [comment]
Closing this issue as it happens not so often. And if I want I can exclude Bing images from engines on my instance or enable safe search
