### ISSUE TITLE
Add possibility for analytics tool

### ISSUE THREAD

**Issue by MatthK** [searx/searx#2126]
I have a private searx instance installed that is accessible from the outside world if you know the URL for ease of use.

As a sort of check if others might use my searx instance, I wanted to add it to my [Ackee analytics](https://github.com/electerious/Ackee) tool by adding the `<script async src="https://ackee.domain.org/tracker.js" data-ackee-server="https://ackee.domain.org" data-ackee-domain-id="xxxx"></script>` to the base.html. Unfortunately, the page throws an error in the console when the script is included and the analytics is not working.

I am aware that having an analytics tool is what searx wants to avoid, but Ackee is not showing much more then a page count. Is there a way to add this?

I don't know python at all, so I'm not quite sure why this triggered the error on the page.

The error in the console is: 

`Uncaught Error: Mismatched anonymous define() module: ` plus a lot more at "require-2.1.15.min.js:8".

**Comment by unixfox** [comment]
I've high doubts that someone here will help you tracking Searx users. You are on your own.
Moreover your tracking only works with JS and a lot of Searx users doesn't even have JS enabled.

**Comment by MatthK** [comment]
I definitely won't list that site publicly. The only user is myself.
The purpose of it is to sort of see, if others are using it. Then I'd have to block access to it, as the installation is not made for public use.

**Comment by unixfox** [comment]
Why aren't you relying on only the logs of the web server then?

**Comment by MatthK** [comment]
Where do I find those? And how do I "read" those to get a human understandable report?

**Comment by unixfox** [comment]
Depends on the web server that you are using. Usually it's in /var/log.
Also you could just look at the logs when launching Searx.

**Comment by MatthK** [comment]
I installed it using the docker version. There is a a uwsgi.log in /var/log/uwsgi but that does not seem to show any details to page views.

**Comment by dalf** [comment]
If you want to include external script, you have to modify the CSP header: https://github.com/searx/searx-docker/blob/master/Caddyfile#L83 (  ```script-src 'self'``` --> ```script-src 'self' https://ackee.domain.org```)

The purpose of searx is privacy, so there are multiple fences to avoid any external requests:
* the HTML is santized
* the HTTP referrer [should be disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer)
* CSP header (link above)
* (non-exhaustive list)

**Comment by MatthK** [comment]
Thanks for the reply and help. But I have no idea how I would adjust that content security policy.
It's not that important, I guess I let go of that idea.

**Comment by unixfox** [comment]
The docker version of Searx doesn't show the logs by default but you should be able to activate them for the web server "Caddy" by adding this line in the Caddyfile at the 110th line:
```
log
```
Then restart the containers using `./stop.sh` then `./start.sh`.
You should then be able to see the caddy logs by executing `docker-compose logs -f caddy`.

Do note that those modifications aren't supported by `searx-docker`.

**Comment by MatthK** [comment]
Where do I find that Caddyfile?

I guess without compromising searx I can see the number of page access by using [GoAccess](https://goaccess.io/) and checking the log files from the reverse proxy.

**Comment by SuperSandro2000** [comment]
https://github.com/searx/searx-docker/blob/master/Caddyfile

**Comment by MatthK** [comment]
I haven't explained it properly. I saw the file already in the link above, but I don't know where to find the file on my computer. I tried with `find / -name Caddy*` but that didn't bring any results.

**Comment by SuperSandro2000** [comment]
Clone the other repo. The file is not in this repo.

**Comment by MatthK** [comment]
Ahh, ok. Thanks.
I guess I will just forget this idea as explained. The main objective to see the number of page views/external access is achieved with the analysis of the log files of the proxy.
