### ISSUE TITLE
Allow server admins to choose default search method

### ISSUE THREAD

**Issue by msafadieh** [searx/searx#2129]
Currently, the default search method used by Searx is `POST` which breaks compatibility with Firefox containers. Since FF's query to `/opensearch.xml` does not include the cookies, the user's preferred method is not reflected and they're forced create a custom search engine with the correct URL formatting and method.

A good solution is to make the method parameter configurable in `settings.yml`. This was already mentioned in #703 and looks fairly easy to implement. Let me know if you want me to open a PR.

**Comment by dalf** [comment]
It makes sense for me.
