### ISSUE TITLE
Gigablast engine broken

### ISSUE THREAD

**Issue by qbitroot** [searx/searx#2141]
When I try to search for something using Gigablast engine, the following error appears:
```
gigablast (unexpected crash Expecting value: line 1 column 1 (char 0))
```
![Screenshot from 2020-08-12 17-20-42](https://user-images.githubusercontent.com/66268477/90026598-30df6600-dcc0-11ea-903d-de7a5955d1d1.png)
I tried to do that search at many instances, all of them showed an error. However, everything is right at https://a.searx.space/

**Comment by qbitroot** [comment]
Hi! Any updates about this issue?

**Comment by return42** [comment]
Can we tag this with 'bug' / thanks!

**Comment by asciimoo** [comment]
It works well for me on my instance.

**Comment by Elendil211** [comment]
I have the same issue, but it doesn't happen with every search. Sometimes it's working fine, and sometimes it doesn't work.

`/var/log/uwsgi/app/searx.log` is full with this error:
```
ERROR:searx.search.processor.online:engine gigablast : exception : Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 139, in search
    search_results = self._search_basic(query, params)
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 123, in _search_basic
    return self.engine.response(response)
  File "/usr/local/searx/searx-src/searx/engines/gigablast.py", line 93, in response
    response_json = loads(resp.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I pulled updates today. 
Raspbian on Raspberry Pi 4B

I observed the following behaviour:

1. I run
    ```
    sudo -H systemctl restart apache2
    sudo -H service uwsgi restart searx
    ```
2. First search fails with the error
3. Next few searches run well
4. After some time the error appears with every search. Repeat with step 1.
