### ISSUE TITLE
text encoding problem (cyrilic)

### ISSUE THREAD

**Issue by sashagra** [searx/searx#2146]
Ubuntu 64-bit, Firefox 79
![Screenshot_2020-08-14 МАПИд - searx](https://user-images.githubusercontent.com/45414622/90259670-14276780-de53-11ea-9c28-59dc58e1ec6d.png)

**Comment by asciimoo** [comment]
@sashagra could you provide a test query in text form and any special settings required to reproduce this issue?

**Comment by sashagra** [comment]
@asciimoo 
It is any Cyrillic query. There are no special settings
Test query: МАПИД

**Comment by sashagra** [comment]
Now I see some difference with request from address bar and from web page. Also I get other results in the private window where is other style of results page
I get this issue with address bar request and 
![image](https://user-images.githubusercontent.com/45414622/95762188-09a01780-0cb6-11eb-9250-f4b28a514c67.png)

**Comment by unixfox** [comment]
Is this still an issue?

**Comment by unixfox** [comment]
@sashagra I tried your test query, but I couldn't replicate the bug.

Reopen if you are still experiencing this issue.
