### ISSUE TITLE
Firefox on Android does not attempt to make a suggestions query

### ISSUE THREAD

**Issue by Nebukadneza** [searx/searx#2147]
Even with the recent fixes around `opensearch.xml`, Firefox for Android 68.11.0.… does not attempt to make a suggestions-query. Note that as long as the "defaults" google-engine is still in the list of search-engines, this is used for suggestions silently, even though the actual search is directed towards your default engine (searx).

I’m not sure whether this is a Firefox bug, or if something in `opensearch.xml` is still weird …. I couldn’t find a corresponding issue on the firefox-android bugtracker, though. So I’m now posting here to see if others observe the same problem … and maybe we can take it over to the firefox-android folks, if it’s really missing there.

**Comment by unixfox** [comment]
Now that the new Firefox for Android is out: Do you still want to keep this issue open or should we close it and wait for a proper `opensearch.xml` on the new Firefox for Android?

**Comment by Nebukadneza** [comment]
Thanks for the ping!

Good question, the new Firefox-for-Android (80.1.3 currently) does not seem to support interpreting `opensearch.xml` at all, and since the UI for entering search engines manually only allows entering a single search URL, suggestions are completely impossible now.

I’m for closing this one, but I’m going to leave it open for just one additional question: Do you think we should have an issue at `searx` to track this fact and possibly track opening an issue upstream at firefox?

**Comment by unixfox** [comment]
> I’m for closing this one, but I’m going to leave it open for just one additional question: Do you think we should have an issue at `searx` to track this fact and possibly track opening an issue upstream at firefox?

Why would we need to track that? Searx already did its job of implementing the opensearch standard. If new Firefox for Android is following the same implementation as the desktop one then everything should work as intended.

I think it would be better to wait for new Firefox for Android to start implementing the automatic discovery of opensearch and if it doesn't on Searx then open an issue for that.

**Comment by Nebukadneza** [comment]
Fair point indeed, thus closing. Thanks and sorry for the overhead!
