### ISSUE TITLE
Morty and Status page are broken

### ISSUE THREAD

**Issue by Happyfeet01** [searx/searx#2148]
Hello,

The morty Page and Status Page are broken. i get an 502 Nginx Error:

`2020/08/16 09:49:59 [error] 30908#30908: *31871 connect() failed (111: Connection refused) while connecting to upstream, client: 2003:f9:571a:cf00:3132:a53:b578:66a3, server: suche.dasnetzundich.de, request: "GET /mortyurl=https%3A%2F%2Fwww.merriam-webster.com%2Fdictionary%2Ftest&mortyhash=9d69e50cfb72fe558081a0737673778c67c636b34b249b871fde68a1d4f20af7 HTTP/2.0", upstream: "https://10.10.10.5:443/mortyurl=https%3A%2F%2Fwww.merriam-webster.com%2Fdictionary%2Ftest&mortyhash=9d69e50cfb72fe558081a0737673778c67c636b34b249b871fde68a1d4f20af7", host: "suche.dasnetzundich.de"`

i testet it with the Morty URL http://10.10.10.5:3000 and http://10.10.10.5

here my docker-compose.yml and settings.yml

https://paste.dasnetzundich.de/view/fcfaf127

and my Docker-compose.yml

https://paste.dasnetzundich.de/view/ccafa806

it don´t know what is wrong.

**Comment by dalf** [comment]
I'm _not_ sure if it is the cause, but look at https://github.com/searx/searx-docker/blob/4f5c3b5ee0b091bc6093b58fd4c9f531f5161e9d/docker-compose.yaml#L69-L72 (and https://github.com/searx/searx-docker/pull/51 )

The ```-listen 10.10.10.5:3000``` doesn't work for some reason.
But it is working using the ```MORTY_ADDRESS=0.0.0.0:3000``` environment variable.

**Comment by Happyfeet01** [comment]
I changed it and try it again

**Comment by Happyfeet01** [comment]
Okay,
i your the complete Docker-compose file edit the Path and it works! Thanks for your fast Help!
