### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by casmokey** [searx/searx#2156]
No matter which method I try the following error always shows up

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /usr/local/searx

Then it hangs on this line

Building wheel for lxml (setup.py): started

Any solution would be greatly appreciated

**Comment by unixfox** [comment]
How did you install Searx in the first place?

**Comment by unixfox** [comment]
@casmokey We haven't heard about you for 7 days. I'll close the issue but feel free to reopen it if you still encounter the problem.
