### ISSUE TITLE
Recommendation for Private Instance

### ISSUE THREAD

**Issue by dm17** [searx/searx#2157]
Say you run your own Searx instance for your organization. So I have search.myorg.com as my searx instance, but I don't want everyone online using it... I also want to make it easy for my organization members to use it... How do I password protect it? Perhaps there's another authentication method?
Thanks.

**Comment by dalf** [comment]
It depends how you want to install searx ? scripts ? docker ? custom solution ?

* Will it be available only on the internal network of the organization ?
* Is HTTP Basic Authentication enough ?
   * nginx: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
   * Caddy: https://caddyserver.com/docs/caddyfile/directives/basicauth

Alternative solution: 
* https://asciimoo.github.io/searx/blog/private-engines.html
* you add one unique token to all engine (you can add a one token per team/individual, but it breaks the privacy that searx provide).
* usual pitfall of this solution in this use case: a shared password ends up to be known by everyone. Workaround: change it every month/whatever.

Alternative solution:
* if all requests come from the IP range: just deny all request from elsewhere using 
   * iptable
   * https://caddyserver.com/docs/caddyfile/matchers#remote-ip or https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-tcp/

**Comment by dm17** [comment]
> It depends how you want to install searx ? scripts ? docker ? custom solution ?
> 
> * Will it be available only on the internal network of the organization ?
> * Is HTTP Basic Authentication enough ?
>   
>   * nginx: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
>   * Caddy: https://caddyserver.com/docs/caddyfile/directives/basicauth
> 
> Alternative solution:
> 
> * https://asciimoo.github.io/searx/blog/private-engines.html
> * you add one unique token to all engine (you can add a one token per team/individual, but it breaks the privacy that searx provide).
> * usual pitfall of this solution in this use case: a shared password ends up to be known by everyone. Workaround: change it every month/whatever.
> 
> Alternative solution:
> 
> * if all requests come from the IP range: just deny all request from elsewhere using
>   
>   * iptable
>   * https://caddyserver.com/docs/caddyfile/matchers#remote-ip or https://docs.nginx.com/nginx/admin-guide/security-controls/controlling-access-proxied-tcp/

Right, I was thinking of using HTTP auth using Traefik - but that means all users would have the same password basically... Which doesn't really bother me. I'll be using it in Docker, yes. It will not be internal but on the open web.

I don't quite understand how "private engines" work. Say you go into Firefox or Chromium - can you add the "private engine" there so it works like DDG or Google would?

Thanks!

**Comment by dalf** [comment]
>I was thinking of using HTTP auth using Traefik 

Some of the headers here might be useful: https://github.com/searx/searx-docker/blob/4f5c3b5ee0b091bc6093b58fd4c9f531f5161e9d/Caddyfile#L34-L56 (CSP, X-*).

> I don't quite understand how "private engines" work.

You can set password for some engines in settings.yml.

Then a user in ```/preferences``` has to set the same password to be able to use the engine, otherwise searx behave like the engine doesn't exist.

**Comment by dm17** [comment]
Yes, I did read that previously. My difficulty parsing your writing might just be my own :)

**Comment by dalf** [comment]
I wrote "password", it is "token", sorry.

An engine with a defined token in settings.yml won't work ; except if the user goes to the preferences, and set the token in the "engine tokens" field (see screenshot), and then save:
![image](https://user-images.githubusercontent.com/1594191/91057420-750b2880-e627-11ea-9fc2-31bf73e89dfa.png)

You can define the same token for all engines.

I think HTTP Basic Auth is way more simple for you: you change the traefik configuration, and just leave the searx configuration as it is.

**Comment by dm17** [comment]
Nothing wrong with a token... I just don't know how that would be specified on the user end (Chromium or Firefox). I tried searching for "search engine token" + "[browser name]" - but didn't return anything useful.

**Comment by Wonderfall** [comment]
> Right, I was thinking of using HTTP auth using Traefik - but that means all users would have the same password basically... Which doesn't really bother me. I'll be using it in Docker, yes. It will not be internal but on the open web.

[Authelia](https://www.authelia.com/) is perfect for your use case! That's what I use with Searx (Docker + Traefik v2).
[Once configured](https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html), just add a middleware to your Traefik dynamic configuration for Searx.

**Comment by dm17** [comment]
> > Right, I was thinking of using HTTP auth using Traefik - but that means all users would have the same password basically... Which doesn't really bother me. I'll be using it in Docker, yes. It will not be internal but on the open web.
> 
> [Authelia](https://www.authelia.com/) is perfect for your use case! That's what I use with Searx (Docker + Traefik v2).
> [Once configured](https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html), just add a middleware to your Traefik dynamic configuration for Searx.

So how do you add your search engine to your browser in your configuration? It has an option to add the supported authorization?

**Comment by Wonderfall** [comment]
> > > Right, I was thinking of using HTTP auth using Traefik - but that means all users would have the same password basically... Which doesn't really bother me. I'll be using it in Docker, yes. It will not be internal but on the open web.
> > 
> > 
> > [Authelia](https://www.authelia.com/) is perfect for your use case! That's what I use with Searx (Docker + Traefik v2).
> > [Once configured](https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html), just add a middleware to your Traefik dynamic configuration for Searx.
> 
> So how do you add your search engine to your browser in your configuration? It has an option to add the supported authorization?

Just add Searx to your browser as you normally would.
Once you're logged in, Authelia sets a cookie so your access remains. And if the cookie expires and you make a request, Authelia will just ask you to log in again (it would be at `auth.myorg.com` for instance), and then proceeds to redirect you to your search. I haven't had any issues with this setup on Chromium-based browsers so far.

**Comment by return42** [comment]
@dm17 is your question answered / if so can you please close your github-issue.
