### ISSUE TITLE
admin platform

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2158]
Hi everyone,

Is there any admin platform for edit easily?

https://github.com/kvch/searx-admin
I tried to install this but failed, anyone install it succesfully?

Thanks

**Comment by unixfox** [comment]
Unfortunately there is none, the only way is through the settings.yml. It's still quite easy to configure tho.

**Comment by andrew6838** [comment]
> Unfortunately there is none, the only way is through the settings.yml. It's still quite easy to configure tho.

https://github.com/kvch/searx-admin
do you try this? work?

**Comment by unixfox** [comment]
> > Unfortunately there is none, the only way is through the settings.yml. It's still quite easy to configure tho.
> 
> https://github.com/kvch/searx-admin
> do you try this? work?
> 

No I haven't because it's quite old, out of date and really not useful because it's quite easy to edit a `settings.yml` the documentation is here: https://searx.github.io/searx/admin/settings.html#global-settings

**Comment by unixfox** [comment]
Unfortunately settings.yml will stay the only place to modify any settings, and we don't plan to introduce an admin web interface for managing Searx but if a developer is interested then feel free to create a PR or link the project here.
