### ISSUE TITLE
Upgrade to 0.17.0-84-6f9aa0e2 - Suddenly not able to retrieve any results

### ISSUE THREAD

**Issue by MaestroJAL** [searx/searx#2163]
Upgraded to SearX 0.17.0-84-6f9aa0e2 and am no longer getting any results. Also, if enable any of the Categories in settings.yml, I get an Internal Server Error. Lastly, where did the image category go?  I did update the settings.new.yml and everything looks good. I'm using the Docker container version. Ideas?

**Comment by MaestroJAL** [comment]
Follow Up: After looking in my SearX preferences, there are no available engines listed.

**Comment by elixx** [comment]
I just experienced something similar, possibly the same thing, with my last two build attempts from the latest HEAD.

I thought it was me or something in my automation process that changed. Haven't investigated too much, but quickly rolled back.

**Comment by dalf** [comment]
I'm looking at the problem.

The asciimoo/searx repository has moved to searx/searx, and the travis configuration went away.

**Comment by dalf** [comment]
Most probably related to this commit https://github.com/searx/searx/commit/4fb3ed2c6335b68f6b28ebc68d5d22f2fd621648#diff-02503eba222466e11a3f7ae36debdc5cL1053

With uwsgi, the engines are not initialized.

**Comment by dalf** [comment]
Fixed in 0.17.0-86-b329058c ; can someone confirm ?

Sorry for the broken image.

**Comment by andrew6838** [comment]
always get this error  , "google (unexpected crash CAPTCHA required)"

**Comment by unixfox** [comment]
@andrew6838 
> always get this error , "google (unexpected crash CAPTCHA required)"

It's unrelated to this issue. Please check this issue instead: https://github.com/searx/searx/issues/729

**Comment by elixx** [comment]
Working for me, now! Thanks!

**Comment by MaestroJAL** [comment]
Works also for me! Thank you for the quick turn around!
