### ISSUE TITLE
not get google results

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2164]
Hi all,

Can I not get Google search results?
because there are many problems in it.  Like CAPTCHA, etc.

Can I only get DDG search results ?

Thanks

**Comment by dalf** [comment]
1. Go to into the Preferences (link on the upper right corner, except for the ```simple``` theme on mobile phone)
2. Select the "Engines" tab
3. Select the "General" catagory
4. Pick the engines you want
5. Save

**Comment by andrew6838** [comment]
> 1. Go to into the Preferences (link on the upper right corner, except for the `simple` theme on mobile phone)
> 2. Select the "Engines" tab
> 3. Select the "General" catagory
> 4. Pick the engines you want
> 5. Save

I mean in backend, does it make change in setting.yml? thanks

**Comment by dalf** [comment]
Just comment out the google engine in settings.yml (and any other engine you want to remove):

https://github.com/searx/searx/blob/b329058c1ad06fe9c1afd56c81e0ad27dbef06b8/searx/settings.yml#L318-L320

Alternative, you can add 
https://github.com/searx/searx/blob/b329058c1ad06fe9c1afd56c81e0ad27dbef06b8/searx/settings.yml#L74

So the engine is still available, but disabled by default.

See https://searx.github.io/searx/admin/settings.html#global-settings for more details.

**Comment by dalf** [comment]
I close the issue. Related to #2170
