### ISSUE TITLE
in setting.yml , autocomplete , what does it mean?

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2165]
Hi all,

in setting.yml , autocomplete , what does it mean?

autocomplete : "" # Existing autocomplete backends: "dbpedia", "duckduckgo", "google", "startpage", "swisscows", "qwant", "wikipedia" - leave blank to turn it off by default

Thanks

**Comment by dalf** [comment]
The user can go into the preferences, and select an auto-completion source.

By default there is autocomplete in searx user interface (this is the ```autocomplete : ""``` is settings.yml), but you can change this default.

**Comment by unixfox** [comment]
@andrew6838 Did dalf answered your initial question? If so then you can close this issue.

**Comment by dalf** [comment]
@andrew6838 , I close the issue. Feel free to reopen / add comment.

**Comment by andrew6838** [comment]
> The user can go into the preferences, and select an auto-completion source.
> 
> By default there is autocomplete in searx user interface (this is the `autocomplete : ""` is settings.yml), but you can change this default.

 if  I make change to autocomplete : "duckduckgo" , what does it mean by this?

Thanks

**Comment by dalf** [comment]
On duckduckgo.com, when you start to type a query into the input field, duckduckgo makes some suggestions without even pressing Enter.

You will have exactly the same suggestions in searx when you change autocomplete to ```duckduckgo``` in settings.yml
