### ISSUE TITLE
Misconfigured + expired certs...

### ISSUE THREAD

**Issue by canDry** [searx/searx#2166]
**On the latest Firefox using  searx.xyz:**

```
An error occurred during a connection to searx.xyz. The OCSP response contains out-of-date information.
Error code: SEC_ERROR_OCSP_OLD_RESPONSE

```

**Using https://searx.dojocasts.com/:**

```
The certificate for searx.dojocasts.com expired on 8/28/2020.
 Error code: SEC_ERROR_EXPIRED_CERTIFICATE

```

**Comment by SuperSandro2000** [comment]
This is the bug tracker for the software and not single instances. Please contact the administrators of those instances instead.

**Comment by unixfox** [comment]
@canDry Please only use working instances on https://searx.space. If some instances doesn't work anymore then the searx project is not responsible for that so please do not open an issue for that.

**Comment by dalf** [comment]
I close the issue.

As @SuperSandro2000 , this bug tracker is about searx as software.
As @unixfox said, look at https://searx.space for working instances.
