### ISSUE TITLE
Can I install Searx for public?

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2168]
Hi,

Can I install Searx for public?
is it allowed?
anything need to be noticed?

Thanks

**Comment by unixfox** [comment]
> Can I install Searx for public?
> is it allowed

Why wouldn't that be allowed? There are already a lot of Searx public instances available so yeah you can install that for the public...

> anything need to be noticed?

When offering a public Searx instance you will need to take into account for example that an anti bot protection (like filtron) will be necessary to be installed.

**Comment by andrew6838** [comment]
> > Can I install Searx for public?
> > is it allowed
> 
> Why wouldn't that be allowed? There are already a lot of Searx public instances available so yeah you can install that for the public...
> 
> > anything need to be noticed?
> 
> When offering a public Searx instance you will need to take into account for example that an anti bot protection (like filtron) will be necessary to be installed.

Like which instance?

**Comment by return42** [comment]
> Like which instance?

_You’re spoilt for choice_, I recommend to read [installation instructions](https://searx.github.io/searx/admin/installation.html).

**Comment by unixfox** [comment]
> > > Can I install Searx for public?
> > > is it allowed
> > 
> > 
> > Why wouldn't that be allowed? There are already a lot of Searx public instances available so yeah you can install that for the public...
> > > anything need to be noticed?
> > 
> > 
> > When offering a public Searx instance you will need to take into account for example that an anti bot protection (like filtron) will be necessary to be installed.
> 
> Like which instance?

All the instances listed on https://searx.space which is the main website linked on https://searx.me....

**Comment by dalf** [comment]
I close the issue, feel free to reopen / comment if your initial questions were not answered.
