### ISSUE TITLE
Is there any website of searx with high traffic?

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2169]

**Comment by unixfox** [comment]
Why are you asking that?

**Comment by andrew6838** [comment]
> Why are you asking that?

Because google will block if traffic go up. Is it?

**Comment by unixfox** [comment]
Yeah but you also have this kind of issue with a low traffic public instance.

**Comment by andrew6838** [comment]
> Yeah but you also have this kind of issue with a low traffic public instance.

Will have big traffic soon..lol

**Comment by unixfox** [comment]
> > Yeah but you also have this kind of issue with a low traffic public instance.
> 
> Will have big traffic soon..lol

I don't understand what you mean by that. If your main concern is the Google Recaptcha issue then please write your questions in this issue instead : https://github.com/searx/searx/issues/729 and close this current Github issue.

**Comment by dalf** [comment]
I close the issue,  feel free to specify your question.
