### ISSUE TITLE
Can i add new engine

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2171]
Hi all,

Can i add new engine ? How?

Thanks

**Comment by unixfox** [comment]
If the instance is very easy to add through a single xpath that will fetch the results then you just need to add another block in the engine section of settings.yml file: https://searx.github.io/searx/admin/settings.html#engine-settings

But if that's not the case then you need to write the new engine in python. You can take an engine from there: https://github.com/searx/searx/tree/master/searx/engines as an example. Unfortunately there is no perfect example, maybe @dalf could suggest you one.

In general the engine documentation is available here: https://searx.github.io/searx/dev/engine_overview.html

**Comment by dalf** [comment]
I don't have any special recommendation.

In addition to the exist documentation, note that there are (at least) two types of engine:
* engine dealing with HTML or XML: in this case the engine relies on [lxml](https://lxml.de/) to parse the HTML/XML page(s). See [digg.py](https://github.com/searx/searx/blob/master/searx/engines/digg.py) for an example.
* engine dealing with JSON: in this case the engine relies on [json](https://docs.python.org/3.8/library/json.html). See [github.py](https://github.com/searx/searx/blob/master/searx/engines/github.py) for an example.

**Comment by andrew6838** [comment]
> If the instance is very easy to add through a single xpath that will fetch the results then you just need to add another block in the engine section of settings.yml file: https://searx.github.io/searx/admin/settings.html#engine-settings
> 
> But if that's not the case then you need to write the new engine in python. You can take an engine from there: https://github.com/searx/searx/tree/master/searx/engines as an example. Unfortunately there is no perfect example, maybe @dalf could suggest you one.
> 
> In general the engine documentation is available here: https://searx.github.io/searx/dev/engine_overview.html

on setting.yml: 

- name : baidu
    engine : baidu
    shortcut : ba

I  copy someone's engine baidu.py and uploaded to engine folder

but it doesn't work. got 502 Bad Gateway

**Comment by dalf** [comment]
> I uploaded baidu.py

Which code ? Where ? Why not your instance ? How was it installed ?
BTW: how your code is different from https://github.com/entropage/mijisou/blob/devel/searx/engines/baidu.py ?

> but doesn't work.

Please please please, provide more context (errors messages, how do you get error, is it always / sometimes ?). _doesn't work_ can mean anything. Sometimes just trying to write a bug report you _may_ find what is wrong.

[EDIT] 502 Bad Gateway, it can be a problem about the instance, without more information, we can't help you.

**Comment by andrew6838** [comment]
> > I uploaded baidu.py
> 
> Which code ? Where ? Why not your instance ? How was it installed ?
> BTW: how your code is different from https://github.com/entropage/mijisou/blob/devel/searx/engines/baidu.py ?
its same..



> > but doesn't work.
> 
> Please please please, provide more context (errors messages, how do you get error, is it always / sometimes ?). _doesn't work_ can mean anything. Sometimes just trying to write a bug report you _may_ find what is wrong.
> 
> [EDIT] 502 Bad Gateway, it can be a problem about the instance, without more information, we can't help you.

**Comment by DitaAjiPratama** [comment]
I add python file for a new engine and place it in `/searx/engines` and restart uwsgi. What is the next step after that?
