### ISSUE TITLE
Website crawling has an issue

### ISSUE THREAD

**Issue by ghost** [searx/searx#2175]
We have setup a complete website as a search engine using Searx.
This website is for university students to search some educational contents; we want to create a sitemap for the same.
Since there are around 2000+ URLs; we want to create HTML sitemap by crawling the entire website.

Issue: When we start crawler it crawls about 60+ pages/links and suddenly stops with an error (this has been tested with multiple crawlers web based and system applications); for all the crawlers the end result is same (die/stops crawling after 60+ pages/links).

I think there is something in Searx script which is limiting the crawling based on IP/Action/Method.
Please help to resolve this issue.

**Comment by dalf** [comment]
> Issue: When we start crawler it crawls about 60+ pages/links and suddenly stops with an error (this has been tested with multiple crawlers web based and system applications); for all the crawlers the end result is same (die/stops crawling after 60+ pages/links).
> I think there is something in Searx script which is limiting the crawling based on IP/Action/Method.

Which searx instance are you using ?

**Comment by ghost** [comment]
version 0.17.0 on Ubuntu 20.04
no apache

Instance URL: https://thebankexam.com

**Comment by ghost** [comment]
Hi,
Can anyone help on this please?

**Comment by unixfox** [comment]
How did you deploy searx in the first place?

Using searx-docker? If that's the case then you need to remove filtron from the searx-docker deployment. @dalf may help you about that.

**Comment by ghost** [comment]
yes I have deployed it using searx-docker. yes I can see filtron here and it's json file.
@dalf can you please help me to stop/remove filtron.

**Comment by dalf** [comment]
About the instance:
* Cloudfront is the front-end: a lot of requests most probably trigger a limitation (captcha for example).
* in https://thebankexam.com/config ```version``` is ```0.17.0```, it doesn't match the value returned by the [searx/searx](https://hub.docker.com/r/searx/searx) docker image. I don't know how searx was modified (the theme is different, but I don't know if some other components have been modified).
* If this is your instance, please read the Searx license, the [GNU Affero General Public License v3.0](https://github.com/searx/searx/blob/master/LICENSE) :
  * _When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available._
  * In the thebankexam instance, all references to searx has been removed, the opposite direction.
  
I don't understand your problem: if the purpose is to send requests to different engines and if the code that generate the sitemap is written in Python, if would be better to call searx without the webapp. See https://github.com/searx/searx/blob/master/utils/standalone_searx.py

To remove filtron:
   * remove https://github.com/searx/searx-docker/blob/7ad4d4903d0ce41de4094d5fe0fecda156b41eaa/docker-compose.yaml#L23-L37
   * after https://github.com/searx/searx-docker/blob/7ad4d4903d0ce41de4094d5fe0fecda156b41eaa/docker-compose.yaml#L42 add 
```yaml
    ports:
      - "127.0.0.1:4040:8080"
```

**Comment by unixfox** [comment]
@amendertechnologies did you succeed with the help given by dalf?

**Comment by dalf** [comment]
@amendertechnologies : I close the issue, feel free to reopen / add new comment if the issue is not solved.

**Comment by ghost** [comment]
Hi,
Sorry for the late response. 
With @dalf help I could able remove filtron and add again as per the instructions. But that was also ended up with same issue.
Then I tried changing parameters in filtron config file, but no success. 
Then I stopped filtron completely, but still the same issue.

This site goes through cloudflare reverse proxy, but surely that's not an issue. Because I have another wordpress instance through cloudflare (hosted at aws) which gets crawled easily (tried crawling 5000+ pages in single attempt). 
I suspect on the server, it's created on DigitalOcean, not sure if they have any other security mechanism implemented in server or in their infra.

Any thoughts on this please.

**Comment by dalf** [comment]
@amendertechnologies will you publish the source code of your instance ?

**Comment by dalf** [comment]
I close this issue since the referenced website is no more a searx instance.
