### ISSUE TITLE
duckduckgo and other engines (timeout),

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2179]
Hi all,

duckduckgo and other engines (timeout),

when I get a new IP address and make a search , it will get this error, and then I  make a search again with same keyword, it work without any error, and all will good with this ip address.
once my ip is changed, the error come again at the first search.
its very strange.

Does Searx pass user ip address to engines to get search results?

**Comment by unixfox** [comment]
Are you sure it's not just your internet connection that it is not working for a couple of seconds?
Can you run `ping 8.8.8.8` continuously and check if ping is still responding during the moment where you have a new public IP address?

> Does Searx pass user ip address to engines to get search results?

Technically yes that's how a TCP packet works but it's not Searx that is doing it but more like the network library that Searx use.

**Comment by andrew6838** [comment]
> Are you sure it's not just your internet connection that it is not working for a couple of seconds?
> Can you run `ping 8.8.8.8` continuously and check if ping is still responding during the moment where you have a new public IP address?
> 
> > Does Searx pass user ip address to engines to get search results?
> 
> Technically yes that's how a TCP packet works but it's not Searx that is doing it but more like the network library that Searx use.

some friends make the first search and get only one search result, then search again with the same keyword, get thousands results...

to sum up, the new user or new IP address make the first search that will get one result only or get engines timeout error. after that, it will be fine, work good.

**Comment by andrew6838** [comment]
> Are you sure it's not just your internet connection that it is not working for a couple of seconds?

I am quite sure its not my internet connection problem. I have that network sense.

**Comment by dalf** [comment]
Can you make a screenshoot similar to this one:
<img width="1258" alt="server-timing" src="https://user-images.githubusercontent.com/1594191/61303313-96280580-a7e7-11e9-800d-156c91a9342b.png">

* press F12
* go into the Network tab
* make your initial request (no / one / few results)
* select the first line
* select the "Timing" tab
* make a screenshot

Repeat the same operation on the second request (the request that works).

?

**Comment by andrew6838** [comment]
> Can you make a screenshoot similar to this one:
> <img alt="server-timing" width="1258" src="https://user-images.githubusercontent.com/1594191/61303313-96280580-a7e7-11e9-800d-156c91a9342b.png">
> 
> * press F12
> * go into the Network tab
> * make your initial request (no / one / few results)
> * select the first line
> * select the "Timing" tab
> * make a screenshot
> 
> Repeat the same operation on the second request (the request that works).
> 
> ?

where can I get this software?

**Comment by dalf** [comment]
Basically any browser on Desktop: Firefox, Chrome, Edge, etc...

Safari: https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac

**Comment by andrew6838** [comment]
> > Can you make a screenshoot similar to this one:
> > <img alt="server-timing" width="1258" src="https://user-images.githubusercontent.com/1594191/61303313-96280580-a7e7-11e9-800d-156c91a9342b.png">
> > 
> > * press F12
> > * go into the Network tab
> > * make your initial request (no / one / few results)
> > * select the first line
> > * select the "Timing" tab
> > * make a screenshot
> > 
> > Repeat the same operation on the second request (the request that works).
> > ?
> 
> where can I get this software?

**Comment by andrew6838** [comment]
> Can you make a screenshoot similar to this one:
> <img alt="server-timing" width="1258" src="https://user-images.githubusercontent.com/1594191/61303313-96280580-a7e7-11e9-800d-156c91a9342b.png">
> 
> * press F12
> * go into the Network tab
> * make your initial request (no / one / few results)
> * select the first line
> * select the "Timing" tab
> * make a screenshot
> 
> Repeat the same operation on the second request (the request that works).
> 
> ?

I could't find where to open it at chrome..can you teach me please?

**Comment by dalf** [comment]
Chrome: just follow what is written.

Start by pressing F12.

**Comment by dalf** [comment]
I close the issue, feel free to re-open if your issue is not solved.
