### ISSUE TITLE
How to apply new settings ?

### ISSUE THREAD

**Issue by stemy2** [searx/searx#2180]
Hello,

I modified the file settings.yml, but i don't know how to apply the modification. The previous settings are still applied when i reload the page and there's no service linked to searx, so nothing to restart.

**Comment by unixfox** [comment]
How did you install searx in the first place?

**Comment by stemy2** [comment]
With yunohost, i though that it was not a platform-specific problem, so i posted here instead of the YNH app's repository.

**Comment by unixfox** [comment]
I think it's a platform specific problem because our official installation script has a service (systemd) for Searx and I don't know about your yunohost. In our official install script it's as simple as modifying the settings.yml and doing `sudo systemctl restart searx`.

**Comment by dalf** [comment]
FYI, the yunohost repository about searx is here: https://github.com/YunoHost-Apps/searx_ynh

**Comment by stemy2** [comment]
Found it. On YNh, the service is named uwsgi.
