### ISSUE TITLE
allow to place ads in searx ?

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2183]
Hi,

Is it allowed to place ads on Searx?

**Comment by andrew6838** [comment]
if it can, how can I add it to the search results on my searx ?

Here is the link where get the ads(like get the search results)

http://1977795.bdv.bidvertiser.com/BidVertiser.dbm?pid=829613&bid=1977795&Kterm=hosting&cip=66.66.66.65&maxcount=5&ownid=123&bvref=http%3A%2F%2Ftesturl.com&xml=1&u_agnt=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F52.0.2743.116%20Safari%2F537.36%20Edge%2F15.15063

First , parse it and make a bidvertiser.py like google.py, and then?
in setting.yml? - engine - bidvertiser , etc....
in webapp.py?  

any other files need to modifier?

Thanks a lot

**Comment by dalf** [comment]
From https://searx.github.io/searx/ :

> Searx is a free internet metasearch engine which aggregates results from more than 70 search services. **Users are neither tracked nor profiled. Additionally, searx can be used over Tor for online anonymity.**

I don't think ads are compatible with the above statement.

BUT, you are free to do it.

**Comment by andrew6838** [comment]
> From https://searx.github.io/searx/ :
> 
> > Searx is a free internet metasearch engine which aggregates results from more than 70 search services. **Users are neither tracked nor profiled. Additionally, searx can be used over Tor for online anonymity.**
> 
> I don't think ads are compatible with the above statement.
> 
> BUT, you are free to do it.

Why not?

Just like add a new engine.
its the same.

**Comment by unixfox** [comment]
You can add ads but nobody from the community will help you for that.

**Comment by dalf** [comment]
If you want to display some ads on a web page, you have to include some HTML / JS / CSS / Image from the ad network.

This will leak user data to the ad network (user IP, browser, habbits, etc...).  And actually the search engines do that too: harvest data from the user.

The precise purpose of searx is avoid that: to be able to search pages without loosing privacy (or at least try the best way we can): 
* The search engines doesn't know your user IP, your browser configuration, your location, etc...
* When you click on a result in a searx instance, the target website doesn't know you are coming from a searx instance.
* https://searx.space/ displays if an instance has unknow JS/CSS exactly in that that purpose: make sure there is no data leak outside the searx instance.

The list is long.

Ads break all of this.

**Comment by andrew6838** [comment]
> If you want to display some ads on a web page, you have to include some HTML / JS / CSS / Image from the ad network.
> 
> This will leak user data to the ad network (user IP, browser, habbits, etc...). And actually the search engines do that too: harvest data from the user.
> 
> The precise purpose of searx is avoid that: to be able to search pages without loosing privacy (or at least try the best way we can):
> 
> * The search engines doesn't know your user IP, your browser configuration, your location, etc...
> * When you click on a result in a searx instance, the target website doesn't know you are coming from a searx instance.

the target website should know it, they can check server log, etc..


> * https://searx.space/ displays if an instance has unknow JS/CSS exactly in that that purpose: make sure there is no data leak outside the searx instance.
> 
> The list is long.
> 
> Ads break all of this.

**Comment by return42** [comment]
> the target website should know it, they can check server log, etc..

**Comment by andrew6838** [comment]
> > the target website should know it, they can check server log, etc..
> 
> No they don't .. read carefully what @dalf wrote:
> 
> > When you click on a result in a searx instance, the target website doesn't know **you are coming from** a searx instance.

can't check in referrer page?

**Comment by return42** [comment]
> can't check in referrer page?

Take a look at searx's templates i.e. [oscar](https://github.com/searx/searx/blob/master/searx/templates/oscar/macros.html#L12), a [noreferrer/noopener attribute](https://www.reliablesoft.net/noreferrer-noopener/) is added to the anchors.
