### ISSUE TITLE
> The ranking is set per engine ..

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2187]
> The ranking is set per engine ..
> 
> The operator of a searx instance can set the weight of each engine (e.g. https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L161 ) / a normal user won't change (nor see) what the weight is.

 in setting.yml?

weight : 10 
the number is larger mean the ranking is higher? or ?

_Originally posted by @andrew6838 in https://github.com/searx/searx/issues/1790#issuecomment-690284287_

**Comment by asciimoo** [comment]
> the number is larger mean the ranking is higher?

Most likely yes, but not in every case. Weight is a multiplier of the result's score. If an engine has a `2.0` weight, it means that the original score of the results of this engine is doubled, with weight `3.0` the score is tripled, with weight `0.5` the score is the half of the original and so on..
