### ISSUE TITLE
500 internal error for json data from some searches

### ISSUE THREAD

**Issue by zuphilip** [searx/searx#2188]
For some searches with searx I receive an 500 internal error when trying to access the json data (or csv or rss). To reproduce this try the following steps:

1. Search for `Maya_sculpture-71.893.4` e.g. https://searx.xyz/?q=Maya_sculpture-71.893.4
2. Click on the `json` button. to download the results as json data.

This leads to the 500 error. However, most other searches work well and also the json data can be downloaded. Only with this very specific search and few others I have experienced this problem.

Does anyone see why this causes a problem? How can this been solved?

**Comment by dalf** [comment]
On a local instance, I get the same error, related to https://github.com/searx/searx/blob/master/searx/utils.py#L112

The exception is not caught.
