### ISSUE TITLE
google (unexpected crash CAPTCHA required

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2193]
Hi all,

google (unexpected crash CAPTCHA required

I got this error when search on page 3 or above, how to fix it?

https://github.com/unixfox/antibot-proxy
can antibot-proxy fix this error?

Thanks

**Comment by unixfox** [comment]
Please please I told you multiple times that an issue related to that error already exist here: #729.

Please stop creating duplicate issues it's annoying. Search the error in the issues of Searx before creating a new issue and if it already exist comment on that issue.
