### ISSUE TITLE
Can i use https for my searx?

### ISSUE THREAD

**Issue by andrew6838** [searx/searx#2194]
Hi

Can i use https (ssl cert) for my searx?
will it work fine ?

Thx

**Comment by dalf** [comment]
> Can i use https (ssl cert) for my searx?

Yes

> will it work fine ?

Yes

But I'm not sure this answer your questions ?

**Comment by andrew6838** [comment]
> > Can i use https (ssl cert) for my searx?
> 
> Yes
> 
> > will it work fine ?
> 
> Yes
> 
> But I'm not sure this answer your questions ?

Have you used it? Any comment

**Comment by dalf** [comment]
> Have you used it?

Yes. 

@andrew6838 what is your intent ?

**Comment by andrew6838** [comment]
> > Have you used it?
> 
> Yes.
> 
> @andrew6838 what is your intent ?

make it be more safe for my users.

**Comment by dalf** [comment]
without context and/or information about your setup, the issue(s) you have despite the documentation: first RTFM, then if you still have an issue come back here with a precise problem, and please provide the context.
