### ISSUE TITLE
When setting "debug : True" getting syntax error

### ISSUE THREAD

**Issue by 573** [searx/searx#2201]
I am using searx from the nixpkgs-unstable channel (v0.17.0).

Setting `debug : True` in settings.yml leads to this error on my system

>DEBUG:searx:read configuration from /home/me/.config/searx/settings.yml
INFO:searx:Initialisation done
INFO:searx.plugins.https_rewrite:29 rules loaded
INFO:searx.search:max_request_timeout=None
DEBUG:searx.webapp:static directory is /nix/store/ba94ymd2ymmz4dsc4dfh53k3iymd0a5f-searx-0.17.0/lib/python3.8/site-packages/searx/static
DEBUG:searx.webapp:templates directory is /nix/store/ba94ymd2ymmz4dsc4dfh53k3iymd0a5f-searx-0.17.0/lib/python3.8/site-packages/searx/templates
DEBUG:searx.webapp:starting webserver on 127.0.0.1:8889
> * Serving Flask app "searx.webapp" (lazy loading)
> * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
> * Debug mode: on
>
>INFO:werkzeug: * Running on http://127.0.0.1:8889/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
  File "/nix/store/ba94ymd2ymmz4dsc4dfh53k3iymd0a5f-searx-0.17.0/bin/searx-run", line 2
    export PATH='/nix/store/bs03sg8b0gq2zr4v252hh9psp780qj5q-python3-3.8.5/bin:/nix/store/ba94ymd2ymmz4dsc4dfh53k3iymd0a5f-searx-0.17.0/bin:/nix/store/b89babrahxcn4r320viqhjvp07sa339l-python3.8-chardet-3.0.4/bin:/nix/store/q90k75gi6pyd16fzczyfs08jdagwm76p-python3.8-Flask-1.1.2/bin:/nix/store/8wf8ivlli0j1wnnwbc4ymnbfqwyqyjyr-python3.8-setuptools-47.3.1/bin:/nix/store/7f85sq4443811s535l5rqz4g7wdfsy91-python3.8-Babel-2.7.0/bin:/nix/store/k7nfysq91j7fflkk99jfp1nbibl22lza-python3.8-Pygments-2.6.1/bin:/nix/store/jif4sjf6mw80n8gh3bn4i9wcw4x30a5k-python3.8-docutils-0.16/bin:/nix/store/y9m3r1lp0z47xyqikws655wmgn4z4mcy-python3.8-ndg-httpsclient-0.5.1/bin'${PATH:+':'}$PATH
           ^
SyntaxError: invalid syntax

`SEARX_SETTINGS_PATH=~/.config/searx/settings.yml nix run -f channel:nixpkgs-unstable searx -c searx-run` is how I call the binary.

**Comment by dalf** [comment]
It seems to be a nix problem:
* searx uses Flask 
* when in debug mode, a dependency of Flask, werkzeug, has an issue with NixOS 

See 
* A fix was pushed on werkzeug but later on was reverted : https://github.com/pallets/werkzeug/pull/1242#issuecomment-511554282
* https://github.com/NixOS/nixpkgs/issues/72345#issuecomment-622244484

**Comment by dalf** [comment]
I close the issue since nothing can be done in this repository.
