### ISSUE TITLE
Service doesn't work while using Firefox tabs isolation

### ISSUE THREAD

**Issue by antailyaqwer** [searx/searx#2202]
I'm using addition "Temporary Containers", which isolates all tabs data from each other. So if I create a new tab, search doesn't work with error "Something went wrong. Please go back and try again".

**Comment by dalf** [comment]
Can you provide some additional information:
* which instance ?
* do you own this instance ?
* do you have some preferences ? ( the temporary tab doesn't have your preferences. )

**Comment by antailyaqwer** [comment]
> Can you provide some additional information:
> 
>     * which instance ?
> 
>     * do you own this instance ?
> 
>     * do you have some preferences ? ( the temporary tab doesn't have your preferences. )

What do you mean by instance?
There are no preferencies. New tab create as I would delete all data before creating this. Every search with searx ends with this error. 
By the way, this might be important, I have installed searx as my default search engine. I'm using just site, I haven't installed any software. Thanks.

**Comment by dalf** [comment]
Can you provide the searx URL you are using ? 

"no" is a possible answer but in this case it will be complicated to provide help (I can't reproduce the bug you are describing with my searx instance).

**Comment by antailyaqwer** [comment]
Okay, sorry, I understand it now.
I'm using (https://searx.info). 
What about preferencies: there are no preferencies on the site, because all cookies and settings are new for the tab.
Settings of the browser are mostly default, except I change my user-agent string.

**Comment by dalf** [comment]
I can't reproduce the same bug (GET or POST requests work for me).

Do you have same behavior with other searx instances ? (pick some at the top list of https://searx.space )

If yes, can you try with a the default user agent.

If it fixes the issue, can you share your user agent ?

**Comment by antailyaqwer** [comment]
Yes, I've been trying searching without useraagent-string changing, it didn't work.
I've  tried several sites, some can't be added to firefox.
searx.privatenet.cf - doesn't work (502)
https://searx.gnu.style - works.
https://searx.be/ - works.
https://searx.dojocasts.com/ - open search page, but doesn't show any result, as I wouldn't entered anything.
https://searx.tuxcloud.net/ - works.

**Comment by unixfox** [comment]
If it works in local and for most of the instances I'm afraid the Searx team can't really solve the issue and you should instead contact the maintainer of the instance.

**Comment by antailyaqwer** [comment]
I think you right, thank you for your help. Should we close the issue?

**Comment by jgsch** [comment]
Just for the record. I also had this problem when on Firefox using the [Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) addon with the same instance (https://searx.info). For it to work, you have to be outside of a container. Or be in a container dedicated to searx.
