### ISSUE TITLE
Autocomplete does not work in latest using "Simple" Theme

### ISSUE THREAD

**Issue by Infi-St** [searx/searx#2203]
Downgraded to an older version, and autocomplete is working.  Verified on private and public instances running 0.17.0-104-ae07f4a2 using edge chromium browser. Edge Version 85.0.564.51 (Official build) (64-bit)

Other themes appear to be working with autocomplete

**Comment by dalf** [comment]
Related to this PR : https://github.com/searx/searx/pull/2127

The HTTP header ```X-Requested-With``` is not sent. (with the value ```XMLHttpRequest``` )

See https://github.com/searx/searx/blob/ae07f4a211ecba0331bcab5903e3263c646f8bdb/searx/static/themes/simple/js/searx_src/searx_search.js#L74-L80
