### ISSUE TITLE
automatic add of searx-categories into translations.

### ISSUE THREAD

**Issue by pointhi** [searx/searx#221]
I have updated the translations of searx today.

Later I found out that the translations of categories were deleted on transifex, because the update script has deleted them from the local files on my computer.

Fortunately we have not much data-lose (only a few Hebrew translation of the categories, because the rest is already inside searx). But we should fix that soon. As transitional solution probably a python file, which declare every possible categorie again as translatable.

sorry for this mistake from me.

**Comment by Cqoicebordel** [comment]
Yes, it would indeed be easier for everyone.

In the future days, I will look into using a web hook to hook transifex and github to automagically update themselves with new translations or new strings to translate. It would simplify a lot the workflow I think.

**Comment by asciimoo** [comment]
@pointhi agree, the current "solution" is a dirty hack. I'll fix it as you suggested

@Cqoicebordel that would be awesome
