### ISSUE TITLE
Add SepiaSearch

### ISSUE THREAD

**Issue by TheEvilSkeleton** [searx/searx#2217]
Here's the search engine: https://sepiasearch.org/

Here's its source code: https://framagit.org/framasoft/peertube/search-index/

They also wrote an article about it: https://framablog.org/2020/09/22/sepia-search-our-search-engine-to-promote-peertube/

**Comment by 0xhtml** [comment]
Here is a snippet one can add to his `settings.yml` to use Sepia Search

      - name : sepia search
        engine : json_engine
        search_url : https://sepiasearch.org/api/v1/search/videos?search={query}&nsfw=false&start={pageno}&count=20&sort=-match
        paging: True
        page_size: 20
        url_query : url
        title_query : name
        content_query : description
        categories : videos
        shortcut : sep

This is however missing fields for e.g. thumbnail, views, or date. Which are all provided by the Sepia Search API but not jet implemented in `json_engine.py`. Here is a little table with the missing information:

| field | JSON query |
|---|---|
| thumbnail | thumbnailUrl |
| date | publishedAt |
| author | account.displayName |
| views | views |

@dalf Maybe those fields should be added to the `json_engine`?

Edit: Fix some typos

**Comment by dalf** [comment]
I see that there are a lot filters:
* NSFW
* date range
* language
* not in searx: license, time length

It would be better to create a new engine.
