### ISSUE TITLE
language parameter: validity

### ISSUE THREAD

**Issue by dalf** [searx/searx#2220]
From https://github.com/searx/searx/pull/2189#discussion_r494123787

When the language parameter is set from the cookies, the validity is checked using the match_language function:
https://github.com/searx/searx/blob/21dbc7e852a5c48097c0067e78f0600972e54823/searx/preferences.py#L165-L168

When the language parameter is set from the URL or from the query, the validity is checked using a regex:
https://github.com/searx/searx/blob/21dbc7e852a5c48097c0067e78f0600972e54823/searx/search.py#L281-L290

The regex is on purpose, see commit https://github.com/searx/searx/commit/fd65c1292179fb082e965a1ee6a88b9298a54fc1

Should we changed preferences to check the validity using a regex instead of match_language ?

ping @MarcAbonce

**Comment by MarcAbonce** [comment]
Yeah, I also think it would make more sense to use the regex to validate both.
By the way, I just noticed that in the `SearchLanguageSetting`, the `_validate_selection` method only runs when initializing the class with a default search language from `settings.yml` but never with the cookie value.
