### ISSUE TITLE
Can't apply new settings

### ISSUE THREAD

**Issue by Porkyofthepine** [searx/searx#2222]
I installed searx with the Installation Scripts. I just edited my settings.yml and restarted the service but my default preferences haven't changed.

I've completely redone the entire installation process with the scripts and verified that they didn't overwrite settings.yml and I've restarted nginx and used uwsgi to restart searx. Am I missing something here?

**Comment by unixfox** [comment]
Try to clear your cookies or use incognito mode.

**Comment by Porkyofthepine** [comment]
That didn't work. I've been checking for the changes in a private window.

**Comment by return42** [comment]
>  I just edited my settings.yml and restarted the service but my default preferences haven't changed.

Did you edited the settings file in the repository from which you installed?   You have to edit the settings file where it has been installed at: /etc/searx/settings.yml

ATM the doc-build is broken, normally you can read here https://searx.github.io/searx/admin/installation-searx.html#configuration  / ATM better use my build from the docs here :  https://return42.github.io/searx/admin/installation-searx.html#configuration

**Comment by Porkyofthepine** [comment]
> Did you edited the settings file in the repository from which you installed? You have to edit the settings file where it has been installed at: /etc/searx/settings.yml

That's what it was. I was editing the settings.yml in /usr/local/searx/searx. I had no idea there was another one in etc.

Thanks.
