### ISSUE TITLE
Server Error after Update Ubuntu 20.04

### ISSUE THREAD

**Issue by poltrian** [searx/searx#2233]
After updating to Ubuntu 20.04 I got an error 500. I reinstalled Searx, the error remains. I do not find the fault

**Comment by unixfox** [comment]
How did you install Searx in the first place?

**Comment by poltrian** [comment]
Like the install instruction from the Searx website

**Comment by unixfox** [comment]
There are multiple ways for installing Searx, please be a bit more descriptive and for example send the URL of the instructions.

**Comment by poltrian** [comment]
https://searx.github.io/searx/admin/installation-searx.html#installation-basic I did these step by step. The old installation is removed. I use Apache

**Comment by unixfox** [comment]
@return42 I'm summoning you here because I'm not really used to the installation wiki :).

**Comment by poltrian** [comment]
ok got it run, mistake from my side. Forgot the uwsgi settings, sorry
