### ISSUE TITLE
Rate limit exceeded for custom URL

### ISSUE THREAD

**Issue by The-Demon-Prosecutor** [searx/searx#2243]
I apologise as this is more of an nginx issue than a searx/filtron one, however I've not been able to fix this and I know there are people here who've setup searx on nginx.

I updated from searx 0.16.0 to 0.17.0 and wanted to setup filtron for my searx instance. The default configuration via scripts use "https://custom.url/searx" as the location, however I prefer using subdomains such as "https://my.custom.url" instead (as well as my previous configuration was on a subdomain).

As per the installation, I changed `$SEARX_URL` and my nginx searx configuration file at `/etc/nginx/sites-available/searx` to:
```
server {
    server_name my.custom.url;
    root /usr/local/searx/searx;

    location / {
            proxy_pass         http://127.0.0.1:4004/;

            proxy_set_header   Host             $http_host;
            proxy_set_header   Connection       $http_connection;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Scheme         $scheme;
            # proxy_set_header   X-Script-Name    /searx;
    }

    location /static {
            alias /usr/local/searx/searx-src/searx/static;
    }
...
```
However, with the above configuration, I am unable to use perform any search query as filtron throws "Rate limit exceeded" everytime at me. Note that if I uncomment the `proxy_set_header X-Script-Name` line, then everything works as expected. This is not ideal as now all the searches have the url "https://my.custom.url/searx". I've tried having an empty string as well, but to no avail.

Any help/insight would be greatly appreciated.

Thanks

**Comment by The-Demon-Prosecutor** [comment]
Instrumenting the rules.json to debug tells me that I'm being blocked due to `Connection=close` being set in the header. Seems similar to https://github.com/asciimoo/filtron/issues/10. However as per the above nginx configuration, `Connection` is being set to match the incoming request. A workaround would be to set `Connection keep-alive`, but that defeats the purpose of having filtron.

**Comment by dalf** [comment]
Which browser are you using ?

There are different rules ( = different fences), if you remove the rule about `Connection=close`, filtron still works, so you can remove it if this is deal breaker for you.

**Comment by The-Demon-Prosecutor** [comment]
I use firefox.

I'll be doing that then, thanks!

Edit: Can confirm that removing the rule allows access to searx instance.

**Comment by chrisJuresh** [comment]
> Edit: Can confirm that removing the rule allows access to searx instance.

how exactly did you remove that rule? did you just replace both instances of Connection=close with Connection=keep-alive?

**Comment by ghost** [comment]
I would also like to know. Doing what @chrisJuresh suggested did not work for me.

**Comment by 0xhtml** [comment]
The referenced rules are located in filtron's `rules.json`. The lines in question are:
https://github.com/searx/searx/blob/8362257b9ad446fff270559fd15eb20e6a7b45b3/utils/templates/etc/filtron/rules.json#L66-L76
The lines should be removed from the file. I have no idea though why precisely the issue occurs and if there is another way to fix it.
