### ISSUE TITLE
Request method preference not respected when addin Search Engine

### ISSUE THREAD

**Issue by michaelschufi** [searx/searx#2245]
1. I've changed the request method to GET in the preferences.
1. I've added searx to my Firefox browser as a search engine

Yet, it still searches using POST when using the address bar. What am I doing wrong?

**Comment by dalf** [comment]
Once you added searx, the opensearch.xml (the POST/GET choice) is cached:
* try to remove searx from the search engine
* re-add the searx

---
Probably related to https://github.com/searx/searx/issues/2069#issuecomment-671099077

**Comment by michaelschufi** [comment]
Yeah, I've tried that. Even tried the "forget about this site" feature. But it still didn't work :/

**Comment by michaelschufi** [comment]
Seems to be working now. Tested it on a.searx.space.
