### ISSUE TITLE
Can't use Searx as Search Engine for Firefox with Multi Account Extension enabled

### ISSUE THREAD

**Issue by Booteille** [searx/searx#2249]
Hi.

As said in the title, with Firefox Multi-Account Containers extension enabled, searx does not work properly.

**What's happening**
If I am not focusing my Searx instance tab and if I try to make a search through Firefox address bar or Firefox search bar, the Searx instance opens but the search is not made. I just arrive on the Searx instance homepage.
However, once I am focusing the Searx instance tab, and if I try to make a search through the address bar or search bar of Firefox, the search is being made correctly.
If the tab is open but I am not focusing it, it does not work neither.

**How to reproduce**

1. Create a fresh Firefox instances (about:profiles) and launch Firefox with this profile
2. Go on a searx instance (I tried different instances but my reference instance will be searx.fmac.xyz/)
3. Add it as search engine (click on the three-dot menu, in address bar, then click on "add search engine")
4. (Optional) Enable it as default search engine in Firefox menus
5. Type `about:addons` in address bar and search for "multi".
6. Download Firefox Multi-Account Container extension
7. Manage containers to add a new one : Searx
8. Set up the searx instance (searx.fmac.xyz/) to always open through this container.
9. Make a search through Firefox search bar or address bar.

**Versions**
I used last Firefox Nightly build and Firefox 81.0. Both on Pop_OS 20.04.
As I said, I tried with fresh profiles with only multi-account containers open.

**More informations**
It's maybe not bound to Searx but Multi-Account containers seems to work properly with **every**
 other websites I am using since months. So that's why I opened this issue here.
I'll open another one on Multi-Account Containers.

**Comment by 0xhtml** [comment]
I am using Temporary Containers and facing the same issue. I think that the POST data is not passed to the newly opened searx tab. Using GET requests for searches should fix this issue, however I couldn't get GET to work because of #2245. This should be fixed with #2247.

**Comment by Booteille** [comment]
Ha. Thanks for your investigation!

I finally succeed to add Searx by using https://addons.mozilla.org/en-US/firefox/addon/add-custom-search-engine/ then uninstalling it.

I'll keep this issue open until we have a confirmed fix.

**Comment by dalf** [comment]
* POST requests: it is an issue with Multi Account Extension implementation
* GET requests: since https://github.com/searx/searx/pull/2247 it is possible to add an searx instance as a search engine with the GET method even if the default method is POST. The public instances have to be updated.

**Comment by derritter88** [comment]
I have set up a [Searx instance](https://searx.lelux.fi) which is mentioned at #2247 and changed method to GET.
I allowed cookies to store and also using a permanent container for that.

As soon as I want to search something via Firefox URL/search bar I get to the regular start page of Searx instead of the search results.

**Comment by dalf** [comment]
@derritter88 Have you removed the "searx" search engine before ? Once the "searx" is in the Firefox search engine list, the configuration is not updated.

I've tried the same setup, and it works for me.

**Comment by derritter88** [comment]
@dalf That did the trick - thanks for that.
Did not know that Firefox is not automatically updating search engines.

**Comment by unixfox** [comment]
Closing as the author seems to have solved the original issue.
