### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by renyhp** [searx/searx#2257]
Visiting the [Step by step installation doc page](https://searx.github.io/searx/admin/installation-searx.html#installation-basic) it seems to me that some of the most important parts of the instructions are missing.

It might be a local problem, but I tried changing browser and accessing the link through Android, and I still see the page the same way.

It might also be that I'm being dense, and I just cannot understand what it is written there...

**Comment by dalf** [comment]
https://github.com/searx/searx/issues/2204 seems not fixed.

**Comment by return42** [comment]
For me `make gh-pages` works (except https://github.com/searx/searx/pull/2256#issuecomment-706672264).  So I guess something went wrong when building the gh-pages branch (commit 235139b18a). @asciimoo could you have a look / thanks!

**Comment by renyhp** [comment]
Well, I'd love to install Searx on my server... Will it take time to solve this issue? Or is there any way I can see the docs in the meantime?

**Comment by dalf** [comment]
I've updated the documentation: it should be okay now.

( Sorry for the delay, I've tried to implement https://github.com/searx/searx/issues/2258 but it is unfinished )

**Comment by return42** [comment]
@renyhp : I guess this issue can be closed now? FYI I opened #2278 to handle the new issue we have since #2256 has been merged.
