### ISSUE TITLE
Error 500: Exception on / [GET] seems to be settings related

### ISSUE THREAD

**Issue by tbergeron** [searx/searx#2261]
Hi,

I tried to update (hadn't updated in about 3 months or so) but it broke my entire configuration due to the Python2 support drop. 

So I re-installed everything from the start following step-by-step instructions. It's almost working but something seems wrong with the server itself.

When doing `curl 127.0.0.1:8888` I get:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

and in the logs I have:

```
ERROR:searx.webapp:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/searx/searx-pyenv/lib/python3.5/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/searx/searx-pyenv/lib/python3.5/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/searx/searx-pyenv/lib/python3.5/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx-pyenv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/searx/searx-pyenv/lib/python3.5/site-packages/flask/app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/searx/searx-pyenv/lib/python3.5/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "/usr/local/searx/searx-src/searx/webapp.py", line 447, in pre_request
    preferences = Preferences(themes, list(categories.keys()), engines, plugins)
  File "/usr/local/searx/searx-src/searx/preferences.py", line 373, in __init__
    settings['ui'].get('theme_args', {}).get('oscar_style', 'logicodev'),
```

It's running on Ubuntu Server 16.04.7 LTS with nginx and uwsgi.

I have the default settings still so it should load but I can't get it to load at all no matter what.

I tried looking around in issues but found nothing related to this. Any idea or suggestion?

Thanks

**Comment by dalf** [comment]
According to this line
```
settings['ui'].get('theme_args', {}).get('oscar_style', 'logicodev'),
```

the ```ui``` section is missing in settings.yml:
https://github.com/searx/searx/blob/e78bfd4d8b62a521e08029bb0e708b2bcec9958d/searx/settings.yml#L21-L27

Perhaps searx loads from a location you don't expect settings.yml ? Searx tries to load
1. settings.yml in the path defined by the SEARX_SETTINGS_PATH env variable.
1. searx/settings.yml (in the git repository)
1. /etc/searx/settings.yml

**Comment by tbergeron** [comment]
> According to this line
> 
> ```
> settings['ui'].get('theme_args', {}).get('oscar_style', 'logicodev'),
> ```
> 
> the `ui` section is missing in settings.yml:
> https://github.com/searx/searx/blob/e78bfd4d8b62a521e08029bb0e708b2bcec9958d/searx/settings.yml#L21-L27
> 
> Perhaps searx loads from a location you don't expect settings.yml ? Searx tries to load
> 
> 1. settings.yml in the path defined by the SEARX_SETTINGS_PATH env variable.
> 2. searx/settings.yml (in the git repository)
> 3. /etc/searx/settings.yml

That's the first thing I thought but I wasn't aware of the alternative paths. I had an old config in `/etc/searx`. I had to copy the one from `/usr/local/searx/searx/settings.yml` to `/etc/searx/` to get it to read it. Now it loads infinitely until it times out:

Logs show this:

```
Tue Oct 13 16:04:00 2020 - DAMN ! worker 1 (pid: 4899) died :( trying respawn ...
Tue Oct 13 16:04:00 2020 - Respawned uWSGI worker 1 (new pid: 4901)
```

with no errors otherwise. I'll keep digging but at least my main error is now resolved so thanks a lot!

**Comment by tbergeron** [comment]
I used the script to remove everything and reinstalled from scratch and now it works.
