### ISSUE TITLE
 how can I make this run when I boot? 

### ISSUE THREAD

**Issue by ghost** [searx/searx#2267]
I plan to use my private searx default search engine. i using arch linux.

**Comment by 0xhtml** [comment]
I'm on Arch and using uwsgi + systemd to start searx on boot. It's setup mostly as described here https://searx.github.io/searx/admin/installation-uwsgi.html
You could also use the AUR package: https://aur.archlinux.org/packages/searx/ or https://aur.archlinux.org/packages/searx-git/

**Comment by return42** [comment]
See our installation instruction ["You’re spoilt for choice, choose your preferred method of installation"](https://searx.github.io/searx/admin/installation.html). In your case I recommend to make use of the scripts as described in chapter "Installation scripts".

**Comment by ghost** [comment]
thanks.
