### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by martin-kostov** [searx/searx#2272]
Hello,
I have set up a custom domain before and it worked fine, however now that I chantged the domain it shows this error: "OSError: [Errno 98] Address already in use" when launching SearX with python3 "python3 searx/webapp.py".

I have installed an SSL Certificate with LetsEncrypt and Apache, so that might be where the issue comes from, however I don't know what to do. Port set in settings.yml is 443. Here are some logs:

![image](https://user-images.githubusercontent.com/53234486/97047345-7bfbdc00-1581-11eb-9a83-e1a492a96df6.png)

**Comment by unixfox** [comment]
Why are you running Searx on port 443? Searx doesn't even handle any TLS/SSL, it's the proxy server aka apache that does that. Set a different port for Searx then forward the requests using apache.

**Comment by unixfox** [comment]
Closing due to lack of reply. Feel free to reopen if you are still experiencing this issue.
