### ISSUE TITLE
travis issue

### ISSUE THREAD

**Issue by dalf** [searx/searx#2279]
travis has became really slow few days ago.

Looking at https://www.traviscistatus.com/#month it seems the number of Linux job has been dived by 2.

According to 
https://twitter.com/nicolasgrekas/status/1321041855065300992
we should switch to travis-ci.com instead of travis-ci.org

**Comment by dalf** [comment]
Additional information:
* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
* https://news.ycombinator.com/item?id=24964601

Alternatives:
* github action
* circle CI
* ...
* move everything to gitlab (perhaps self-hosted somewhere to be define)

Does anyone has some preferences ?

**Comment by unixfox** [comment]
GitHub Actions is a good candidate because it strongly integrates with GitHub which means you can quickly see if a test failed directly in the "Actions" tab: https://github.com/searx/searx/actions

**Comment by kvch** [comment]
I would also go with GH actions.
