### ISSUE TITLE
searx docker build not working after update

### ISSUE THREAD

**Issue by asteriosos** [searx/searx#2293]
Hi,

i updated my local searx git repo. i got 120 new commits to pull. After that i removed the old container/images as i always do.
Then i executed "docker build -t searx ." The build was done without any problems. but when i started the container i got the searx website not displayed properly. I mean that the complete style/website is broken.

so i exeuted a "git reset --merge ORIG_HEAD" to revert the 120 commits and builded it again. After that it works properly without any issues. so it has to be something with the commits. 

I use it behind an apache with this:
```
  ProxyRequests Off
  ProxyPreserveHost On
  AddDefaultCharset utf-8
  HostnameLookups off
  UseCanonicalName off
  ProxyBadHeader Ignore
  KeepAlive off

<Location /searx >
  ProxyPass http://127.0.0.1:8080/
  ProxyPassReverse http://127.0.0.1:8080/
  RequestHeader set X-Script-Name /searx

  AuthType Basic
  AuthName searx
  AuthUserFile /etc/apache2/.ht_searx_passwd
  Require valid-user
</Location>
```

**Comment by unixfox** [comment]
Are you aware of the public Searx image: https://hub.docker.com/r/searx/searx? You could try to use it instead.

**Comment by asteriosos** [comment]
> Are you aware of the public Searx image: https://hub.docker.com/r/searx/searx? You could try to use it instead.

Hi, i tried it just now. With the same result:

![Bildschirmfoto von 2020-11-04 13-10-52](https://user-images.githubusercontent.com/44438259/98110527-82eaee80-1e9f-11eb-972d-95e1d8d742ca.png)

**Comment by asteriosos** [comment]
Hi, 

i found it. It was an option in Apache2 ( RequestHeader set X-Script-Name /searx ) that is not needed anymore.
