### ISSUE TITLE
Image thumbnails not loading

### ISSUE THREAD

**Issue by rickboks** [searx/searx#2294]
Hi, the thumbnails in image searches are not loading for me. The only engine that works partially is google images, but with this engine, always only the first 20 thumbnails are being loaded. See the image below, for an example search with only google images enabled.

![04-11-20_12:03:39](https://user-images.githubusercontent.com/27772913/98104049-351db880-1e96-11eb-9c0c-19b23851c57f.png)

I tried increasing the default timeout, but this had no effect. Does anyone have an idea what is causing this? Thanks in advance.

**Comment by unixfox** [comment]
Are you using a local Searx instance or a public Searx instance?

**Comment by rickboks** [comment]
I set up a public instance. It is behind an Apache reverse proxy.

**Comment by unixfox** [comment]
When I meant public instance, is it an instance from https://searx.space? If that's not the case then it's a private instance.
Look at the logs of Searx and in the network tab of the developers tools of your browser in order to diagnose what's causing this issue.

**Comment by rickboks** [comment]
Thanks, the logs don't report any errors, but there are errors in the developer tools. I will look into it soon.

**Comment by return42** [comment]
FWIW: Do you set up morty? If not ...

I often see this, when CSP is enabled by the HTTP server / another reason could be CDNs blocked by DNS or your WEB-Browser .. (uBlock?) ..

Hope that helps.

**Comment by rickboks** [comment]
@return42, Thanks. I did set up morty, and I have not enabled CSP (as far as I am aware). The problem persists on several browsers/devices. Changing DNS also didn't help.

**Comment by unixfox** [comment]
Please post the logs from your dev tools

**Comment by rickboks** [comment]
@unixfox I get the following errors in the developer tools: 
![04-11-20_16:55:51](https://user-images.githubusercontent.com/27772913/98134116-b38e5080-1ebe-11eb-895e-e199a1c70efa.png)

The requests fail with net::ERR_CONNECTION_REFUSED. I am not sure how to proceed..

**Comment by return42** [comment]
Did you missed to set the url of the [result_proxy](https://searx.github.io/searx/admin/morty.html) ?

**Comment by rickboks** [comment]
@return42 No I have that set up: 
```
result_proxy:
    url : http://127.0.0.1:3000/
    key : !!binary <long key>
```

edit: 
and I confirmed that the key is correct and morty is listening on port 3000.

**Comment by return42** [comment]
`http://127.0.0.1:3000/` is not available from the public http .. set the domain name of your morty installation.

update: By example, my Apache setup:

    result_proxy:
        url: https://darmarit.org/morty/

The `https://darmarit.org/morty/` is served to public by a reverse proxy setup in apache (`/etc/httpd/sites-available/morty.conf`)::

````apache

LoadModule headers_module       modules/mod_headers.so
LoadModule proxy_module         modules/mod_proxy.so
LoadModule proxy_http_module    modules/mod_proxy_http.so
#LoadModule setenvif_module      modules/mod_setenvif.so

# SetEnvIf Request_URI /morty/ dontlog
# CustomLog /dev/null combined env=dontlog

<Location /morty/ >

    <IfModule mod_security2.c>
        SecRuleEngine Off
    </IfModule>

    Require all granted

    Order deny,allow
    Deny from all
    #Allow from fd00::/8 192.168.0.0/16 fe80::/10 127.0.0.0/8 ::1
    Allow from all

    ProxyPreserveHost On
    ProxyPass http://127.0.0.1:3000
    RequestHeader set X-Script-Name /morty/

</Location>
````

**Comment by rickboks** [comment]
That fixed it! I understand that 127.0.0.1 is not accessible from public http, but I thought that morty was used as a reverse proxy by Searx, which should be able to access 127.0.0.1:3000, right?

**Comment by return42** [comment]
>  I thought that morty was used as a reverse proxy by Searx, which should be able to access 127.0.0.1:3000, right?

wrong :) .. its very simple: searx replaces the URLs in the HTML searx produce, this is what you see in your [developer tools](https://github.com/searx/searx/issues/2294#issuecomment-721817018).

**Comment by unixfox** [comment]
It's not Searx that access morty but your browser.

**Comment by return42** [comment]
@rickboks  if you think your questions are answered, please close the issue / thanks!

**Comment by rickboks** [comment]
Ah! That makes sense. Thank you both very much for your help!
