### ISSUE TITLE
Change the default search engines

### ISSUE THREAD

**Issue by stoynoff** [searx/searx#2303]
Hi,
I am reporting not a bug or an issue but I can't find the necessary information in the documentation.
I found Searx before a month, I used public institutions but want to use a personal one hosted by me. I installed on RB Pi with Centos 7 (ARM)  using the Step-by-Step guide - https://searx.github.io/searx/admin/installation-searx.html#installation-basic

However, I can't find a way to change the default search engines in settings.yml. The default engines are bing, google etc. but I want to change them to DDG and Startpage for example. I know, that I can set the engines in "preferences" but this settings are only for the device from which I access Searx. I tried to change the weight of the search engines, but it didn't help. It would be good to be able to modify the default search engines from settings.yml

How they managed to change the default search engines?
https://searx.ninja/preferences

Thank you!

**Comment by return42** [comment]
In the (per) [engine settings](https://searx.github.io/searx/admin/settings.html#engine-settings), set `disabled : False` (or remove the line)

https://github.com/searx/searx/blob/c03e4c86bc49d6ef4664c038066d9f1c16e7dafc/searx/settings.yml#L233-L238
