### ISSUE TITLE
My searx instance has no CSS

### ISSUE THREAD

**Issue by justsharan** [searx/searx#2304]
I just finished going through the setup guide for searx and I have it set up with nginx. When I go to the site, it doesn't have any CSS... just plain text. Any reason why?

<img width="1406" alt="Screen Shot 2020-11-07 at 11 55 44 AM" src="https://user-images.githubusercontent.com/53885408/98447082-2cc0ba00-20f0-11eb-9811-245174b25a51.png">

**Comment by unixfox** [comment]
Please paste the logs of your Searx installation and also the logs found in the "network" tab from the dev tools of your web browser.

**Comment by justsharan** [comment]
Never mind, I was able to fix it.

**Comment by izyuumi** [comment]
Hello. I am having the same problem right now. Would it be possible for you to let me know what you did to fix it? @SinistreCyborg Thanks!

**Comment by officereso** [comment]
What was your solution
