### ISSUE TITLE
Disable cache of results

### ISSUE THREAD

**Issue by dfelici87** [searx/searx#2307]
Can I disable cache of results?
or exists a "no use cache" flag?

thanks

**Comment by unixfox** [comment]
There is no cache in Searx. What do you mean by caching the results?

**Comment by dfelici87** [comment]
whats the meaning of label "cached" at the right of every search result (near engine) ?

**Comment by dalf** [comment]
On each result, there is a "cached" link : it is a link to show the recorded version by https://web.archive.org/ .

**Comment by dfelici87** [comment]
ok, thanks
