### ISSUE TITLE
[i18n] RSS strings are not translatable

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#231]
> Searx search: seeks
> Search results for "seeks" - searx

http://searx.me/?q=seeks&format=rss&category_general=1&pageno=1

Maybe searx RSS URLs should have query string such as `&lang=fr` so prefered language be kept in feed when using RSS readers.

**Comment by Cqoicebordel** [comment]
This one will be tricky to implement :  
The interface language is saved in a cookie, but the purpose of a RSS link is to be given elsewhere, where there are no cookies.
We could pass it as an URL option, like http://searx.me/?q=seeks&format=rss&category_general=1&pageno=1&uilang=he but it would be now a privacy issue. If you use this link in a web based RSS reader, it would know that you want the RSS in Hebrew. That's not a big deal, but could be in a few cases.

Anyway, I think it's a low priority bug, because it influence only the title of the feed.

**Comment by GreenLunar** [comment]
Localized interface issue would occur only with Mozilla Gecko-based web browsers.

Due to potential privacy issues, I am closing this report.

**Comment by GreenLunar** [comment]
Would it be possible to pass `&uilang=fr` and redirect to the same URL without `&uilang=fr`?

EDIT: Never mind. UI alone is too trivial to bother for.

---

> Maybe searx RSS URLs should have query string such as `&uilang=fr` so prefered language be kept in feed when using RSS readers.

If one would want to follow an RSS feed specific for a certain language, they can add language-specific terms or characters that would make results more specific to that language.

**Comment by GreenLunar** [comment]
> Maybe searx RSS URLs should have query string such as &lang=fr so prefered language be kept in feed when using RSS readers.

If one would want to follow an RSS feed specific for a certain language, they can add language-specific terms or letters that would make results more specific to that language.

**Comment by Cqoicebordel** [comment]
You can add `:hebrew` or `:he` in the request string to choose the language of the results.  
Note that it only works on engines that provide the possibility of choosing the language of the results.

**Comment by GreenLunar** [comment]
> You can add :hebrew or :he in the request string to choose the language of the results.

I failed to do it. Please post a complete example string.

**Comment by Cqoicebordel** [comment]
http://searx.me/?q=%3Ahe+%21sp+france

It works only on engines that supports it. Startpage is a good exemple of that.

**Comment by GreenLunar** [comment]
I was confused.  I am reopening this issue.  If header sends language preferences, then there should not be a severe issue, since user may change it at anytime

P.S. User Agent, in and of itself, is the bigger problem.

Feel free to close this issue.
