### ISSUE TITLE
Question: How to remove Link box on results page

### ISSUE THREAD

**Issue by Broeckelmann** [searx/searx#2314]
I would like to remove the link box and number of results, because I never use them. Which files do I need to edit?

![Screenshot from 2020-11-13 12-24-21](https://user-images.githubusercontent.com/45721680/99067605-4b6cf800-25ab-11eb-988b-6f3071d19756.png)

**Comment by dalf** [comment]
For the oscar theme, you have to remove these lines:

https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/templates/oscar/results.html#L19-L21

https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/templates/oscar/results.html#L60-L84

**Comment by dalf** [comment]
I guess the thumb up answer the question, I close the issue. Feel free to reopen / add comment.

**Comment by Broeckelmann** [comment]
Thank you very much
