### ISSUE TITLE
How to hide all sections, some sites and settings for user?

### ISSUE THREAD

**Issue by TimurC1** [searx/searx#2315]
Hello, Searx community! I want to deploy Searx on my server, but I want to hide all sections except the main. And I would also like to clarify how to hide sites manually or automatically with adult and illegal (e.g. torrents) content, settings for user? Thanks.

**Comment by dalf** [comment]
In settings.yml, you can either:
* disable an engine: 
https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/settings.yml#L118
* remove an engine: remove the line or comment out.

Searx will hide a category if it doesn't contain at least one engine.

**Comment by TimurC1** [comment]
Thanks, but how I can hide settings for user?

**Comment by dalf** [comment]
You can lock the preferences, see https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/settings.yml#L42-L49

 The full list: `categories`, `language`, `locale`, `autocomplete`, `image_proxy`, `method`, `safesearch`, `theme`, `results_on_new_tab`, `doi_resolver`, `oscar-style`

The users will still:
* see the /preferences URL , but on the main tab all the preferences will be hidden.
* be able to select engines. As I said, you can remove all the engines except, and keep only some of them.

-----

If this is not enough, you really want to remove the preferences, you will have to modify different things.
Here a patch: I'm not sure if the list will exhaustive, this is not tested and not supported.

Remove preferences:
* Remove: 
https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/webapp.py#L807-L888
* Remove:
https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/webapp.py#L993-L998
* Remove: 
https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/webapp.py#L453-L456
* Replace by `pass`:
https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/webapp.py#L466
* Before:
https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/webapp.py#L469
add 
`
request.form = {k: v for k,v in request.form.items() if k in ['language', 'locale']}
`

Update the oscar theme:
* Remove:
https://github.com/searx/searx/blob/aa6eaf603ff9b403dcc32adadbb1e75445f0348c/searx/templates/oscar/navbar.html#L7

**Comment by TimurC1** [comment]
Thank you! I will try.
