### ISSUE TITLE
base_url setting doesn't force domain when adding searx instance to address bar

### ISSUE THREAD

**Issue by guiand888** [searx/searx#2317]
Hi all,

I run a public searx instance on LXD.   
The instance was installed with the help of install scripts at [https://searx.github.io/searx/admin/installation.html](https://searx.github.io/searx/admin/installation.html) and [https://searx.github.io/searx/admin/installation-nginx.html#installation-nginx](https://searx.github.io/searx/admin/installation-nginx.html#installation-nginx).   
Another nginx instance is configured as a https reverse proxy and serves searx to clients.    

Whereas I'd host at a domain such as: `mydomain.com`

The config file under `/etc/searx/settings.yml` is configured such as:
```
[...]
base_url : https://searx.mydomain.com
[...]
```
Under searx preferences at `https://searx.mydomain.com/searx/preferences`, at the very bottom of the pages, it reads the correct domain:
```
https://searx.mydomain.com/searx?preferences=xyzxyz
```
However, when I try to add my custom searx instance to Firefox/Brave/Chrome search bar, followings instructions from the paragraph _Add a search engine from the address bar_ at [this page](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox), it registers the fqdn of the LXD private network the nginx reverse proxy is pointing to: `http://searx.lxd/searx/search?q=%s`
   
Am I missing something here? Shouldn't the `base_url` setting prevent this?

Thanks in advance

**Comment by dalf** [comment]
Are you using the last version of the master branch ? If no, which commit ?

I remember there is a commit about that subject.

**Comment by guiand888** [comment]
I'm on v0.17.0.  
It seems to be the latest

**Comment by unixfox** [comment]
You aren't on the latest version if you aren't running from the master branch.

**Comment by guiand888** [comment]
> You aren't on the latest version if you aren't running from the master branch.

I was running from the master branch as of Saturday 14/11 at 9:08am UTC.

I just ran:
```
git stash
git pull origin master
git stash apply
```
I rebooted the instance. **No change**

<details>
<summary>What was updated</summary>
<br>

```
.pylintrc
Makefile
requirements-dev.txt
searx/engines/acgsou.py
searx/engines/arxiv.py
searx/engines/bing.py
searx/engines/bing_images.py
searx/engines/bing_news.py
searx/engines/bing_videos.py
searx/engines/btdigg.py
searx/engines/command.py
searx/engines/currency_convert.py
searx/engines/deviantart.py
searx/engines/digg.py
searx/engines/duckduckgo.py
searx/engines/duckduckgo_definitions.py
searx/engines/duckduckgo_images.py
searx/engines/duden.py
searx/engines/elasticsearch.py
searx/engines/google_images.py
searx/engines/google_news.py
searx/engines/google_videos.py
searx/engines/piratebay.py
searx/engines/qwant.py
searx/engines/soundcloud.py
searx/engines/startpage.py
searx/engines/wikidata.py
searx/engines/xpath.py
searx/engines/yahoo_news.py
searx/engines/youtube_noapi.py
searx/plugins/__init__.py
searx/results.py
searx/search.py
searx/settings.yml
searx/utils.py
searx/webapp.py
tests/unit/engines/test_command.py
tests/unit/test_search.py
tests/unit/test_standalone_searx.py
tests/unit/test_webadapter.py
tests/unit/test_webapp.py
```

</details>

**Comment by unixfox** [comment]
Could you paste your nginx configuration?

**Comment by unixfox** [comment]
Closing the issue as a lack of response, feel free to reopen it or asking your question in the new appropriate category: https://github.com/searx/searx/discussions/categories/installation-issue-custom
