### ISSUE TITLE
Re-include theme of seeks.okhin.fr

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#232]
@okhin please share it with us :)

Simple and to my likings.
https://seeks.okhin.fr/

**Comment by asciimoo** [comment]
this is the very first design of searx =)

**Comment by GreenLunar** [comment]
I like it.  This theme lack a preferences link, it seems.

**Comment by asciimoo** [comment]
Yap, a minimal, css free theme would be useful for text based browsers too.

**Comment by GreenLunar** [comment]
tsk... tsk...

**Comment by GreenLunar** [comment]
BUMP!

**Comment by unixfox** [comment]
Feel free to open a PR for adding your theme but meanwhile we are sticking with the current themes.
