### ISSUE TITLE
Install script failing to curl on fresh Debain install

### ISSUE THREAD

**Issue by ghost** [searx/searx#2324]
On a fresh Debain 10 i386 install, the first thing I did was install the git and curl packages, and then clone the repo to run `sudo -H ./utils/searx.sh install all`

The script fails on testing the local instance:
```
curl --location --verbose --head --insecure 127.0.0.1:8888
|searx| DEBUG:searx:read configuration from /etc/searx/settings.yml
|searx| INFO:searx:Initialization done
|searx| -bash: line 4: 8040 Illegal instruction    timeout 10 python searx/webapp.py
```
Before reinstalling, I've tried installing this manually according to the step by step guide on the searx website, and then using the script still on the old installation, all failed at the same point.

**Comment by dalf** [comment]
The `Illegal instruction` is weird.
Looking at https://superuser.com/questions/348028/bash-script-redirecting-to-file-gives-illegal-instruction make wonder what `dmesg` says ?

**Comment by ghost** [comment]
I found the root of the problem. My processor doesn't support a certain instruction that the script calls.
