### ISSUE TITLE
Searx instance only showing wikipedia results

### ISSUE THREAD

**Issue by jonasskanoy** [searx/searx#2328]
Been having some issues with my searx instance only showing wikipedia results. Anyone who know why that might be?
The instance is:
 
![Searx](https://user-images.githubusercontent.com/71043573/99916377-47a74700-2d0a-11eb-9caf-0d3a270750fe.png)

**Comment by unixfox** [comment]
The issue/reason is on the right side of your screenshot, the instance is blocked by Google. Disable the Google engine in the settings and use another engine like Bing or Duckduckgo.

Please see #729 for more information about the Google CAPTCHA error.

**Comment by jonasskanoy** [comment]
It suddenly started working for my, dont know what happend. Thanks anyway!

**Comment by maxweisspoker** [comment]
I am having the same issue.  For some unknown reason, only google and wikipedia are being used, even though other engines are enabled in the settings. Therefore, when google fails with a captcha requirement, few if any results are displayed.  Has anybody else experienced this?

Edit:  It appears that something in the way the settings are parsed is different and a lot of engines in the settings which do not have a "disabled" setting are being disabled by default, and when I add "disabled: False", they end up working again.
