### ISSUE TITLE
Theme: discard all the themes except oscar?

### ISSUE THREAD

**Issue by dalf** [searx/searx#2329]
Currently, the only theme with the required features is the oscar theme.

See the different PR: the only updated theme is oscar.
So my guess is the oscar is wildly use compare to the other themes

May be discard all the themes is exaggerated, so different approach can be this:
* add some statistics about the theme usage: how many of the requests use the oscar theme in percentage.
* decide what to do after looking at the statistics of the public instances.

(related to https://github.com/searx/searx/issues/1025 )

**Comment by return42** [comment]
> May be discard all the themes is exaggerated, so different approach can be this:

I cannot estimate how complex it is, but would a plug-in infrastructure for themes be a solution?

**Comment by allendema** [comment]
Those mentioned themes are as of Pull [2344](https://github.com/searx/searx/pull/2344) discarded.
So v1.0.0 ships without them.
