### ISSUE TITLE
Searx instance sometimes goes insecure

### ISSUE THREAD

**Issue by jonasskanoy** [searx/searx#2330]
Hi, some times when I search on my searx instance @ searx.jonasskanoy.xyz, my browser says the site is "not secured" even though my searx instance has https certificate. I have tried to change the engines running in the meta search, but still getting the same issue. Does anyone know how I can enable safesearch on a search engine in searx?

Not secured:
![Searx not secured](https://user-images.githubusercontent.com/71043573/100069895-8ee02580-2e39-11eb-8245-7f2c07ec4328.PNG)

Secured:
![Searx secured](https://user-images.githubusercontent.com/71043573/100069933-9b647e00-2e39-11eb-80d5-95106176aff3.PNG)

**Comment by unixfox** [comment]
Force HTTPS connections on your web server.

**Comment by dalf** [comment]
In addition, in settings.yml 
https://github.com/searx/searx/blob/aec6a2656c4af5aa307914b78cb4f46f4238109a/searx/settings.yml#L55-L57

* set `url` to https://searx.jonasskanoy.xyz/morty
* set a `key`

start morty with the same key.

**Comment by jonasskanoy** [comment]
Thank you, changing the morty url worked :-)
