### ISSUE TITLE
Some images does not show up

### ISSUE THREAD

**Issue by jonasskanoy** [searx/searx#2334]
I am having some issues viewing some images on my searx instance. Does anyone know how to fix this? Anything I gotta do with the proxy server config?

![Images](https://user-images.githubusercontent.com/71043573/100362998-6b190d00-2ffc-11eb-9a54-5324a441ffc3.png)

**Comment by unixfox** [comment]
Please post the logs of the network tab of your dev tools of your browser (usually F12).

**Comment by return42** [comment]
Did you read https://github.com/searx/searx/issues/2294 ?

**Comment by JenkooTheLegitC** [comment]
I am having the excact problem as in #2294 but I am using nginx for my webserver. Here is the error logs.


![morty error](https://user-images.githubusercontent.com/71043573/100384417-6a926d80-3020-11eb-9b83-a38561d3bb32.png)

**Comment by JenkooTheLegitC** [comment]
This is the config I have for morty at the moment in the nginx config file:

location /morty {
    proxy_pass         http://127.0.0.1:3000/;

    proxy_set_header   Host             $http_host;
    proxy_set_header   Connection       $http_connection;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
}

**Comment by jonasskanoy** [comment]
Sorry... Saw just now that I typed in the wrong domain in the `settings.yml` file. It works now.
