### ISSUE TITLE
Engine request: wiby.me and wiby.org

### ISSUE THREAD

**Issue by ghost** [searx/searx#2339]
They're down right now apparently. But they're pretty good search engines.
* wiby.me search for 1.0 websites 
* wiby.org search any kind of websites

**Comment by ghost** [comment]
They're working now!

**Comment by LukeSmithxyz** [comment]
Yeah, I would definitely second this. Wiby is very unique and has the potential to bring smaller and more personal pages to the front page of a searx instance.

**Comment by unixfox** [comment]
> Yeah, I would definitely second this. Wiby is very unique and has the potential to bring smaller and more personal pages to the front page of a searx instance.

Sure! If you don't mind contributing to Searx by writing this engine we can surely adding it to Searx!

**Comment by ghost** [comment]
Wiby has a JSON output, maybe it helps for adding it.

https://wiby.me/about/

>Developers can connect their applications to Wiby using the JSON output available at wiby.me/json.

For example: https://wiby.me/json/?q=qorg

**Comment by kvch** [comment]
What is the difference between the two engines besides the TLD? I have done some testing, and all of the results are identical for the same queries.

**Comment by ghost** [comment]
Apparently .me only links old websites/1.0 websites and .org any kind of websites

**Comment by wibyweb** [comment]
> 
> 
> Apparently .me only links old websites/1.0 websites and .org any kind of websites

.org is the same as .me now and will remain that way. It used to be a google/bing proxy but was too expensive to run on donations alone.
