### ISSUE TITLE
Only first few results being displayed

### ISSUE THREAD

**Issue by maxweisspoker** [searx/searx#2343]
I run Searx self-hsoted with docker-compose. I updated recently after a few weeks, and it only displayed the first few results:

https://i.imgur.com/yUofS09.png

The google captcha issue is NOT involved here. I get that a lot because I route Searx through a VPN to a public VPN provider, so the results and the morty proxy all go through a VPN. Needless to say, a lot of the time I search, I get that google captcha. But that is unrelated to the issue at hand.

Additionally, I noticed that the settings file had been changed after I updated and ran the containers.  I don't why that happened, but that's obviously pretty startling.

What information can I provide in order to help diagnose what has happened and how to fix it?

---

Edit:  Closing issue since the most recent docker image seems to fix the problem of not displaying results, and I can just mount the settings file as read-only to ensure it doesn't get overwritten.

**Comment by maxweisspoker** [comment]
Re-opening, since it appears google was related. (Not really, but it demonstrates the error.) Google and wikipedia seem to be the only search engines that are being used, even though others are listed and enabled in my settings. Therefore, when google fails with captcha, no other results are displayed. So it turns out that the issue is not in fact fixed, it's just a different problem than I thought. The issue is not a lack of results, it's a lack of using all the search engines.

It appears to be the same problem somebody else mentioned [here](https://github.com/searx/searx/issues/2328)

**Comment by maxweisspoker** [comment]
Alright, it appears that for some reason the default used engines have either changed or mostly been set to False.  If I add disabled: False to every engine in the settings, they start working again.

**Comment by maxweisspoker** [comment]
Closing again because the solution is to explicitly set the "disabled" flag.

**Comment by return42** [comment]
> Therefore, when google fails with captcha, no other results are displayed. 

Just some hints:

- You have to protect your searx instance [see](https://searx.github.io/searx/admin/filtron.html)
- [Docker image](https://searx.github.io/searx/admin/installation-docker.html#installation-docker) and [Installation scripts](https://searx.github.io/searx/admin/installation.html#installation-scripts) comes with filtron installed.
- [Engines configured at built time (defaults)](https://searx.github.io/searx/admin/engines.html)
- [Engine settings](https://searx.github.io/searx/admin/settings.html#engine-settings)
