### ISSUE TITLE
Startpage not returning any results

### ISSUE THREAD

**Issue by patrickpichler** [searx/searx#2374]
**Version:**
I tried it with `v0.17.0` and `820b468bfe96f693d60ce06f1e78af51f00deefc`

**Installation-Method:** 
Manually according to wiki (with uwsgi)

**What happened?**
The startpage engine is not returning any results

**How To Reproduce**
Execute a query with `!sp test`

**Expected behavior**
Results from startpage

**Additional context**
I added some log lines to the startpage engine file and it seems like it gets some
response back from startpage. 

Maybe startpage changed their formatting? 
I didn't have a closer look on the way results are parsed yet.

**Comment by joshu9h** [comment]
startpage.py
change following lines

39 results_xpath = '//div[@class="w-gl__result__main"]'
40 link_xpath = './/a[@class="w-gl__result-url result-link"]'

Sorry I don't know howto make a pull request
Thx unifox

**Comment by unixfox** [comment]
> startpage.py
> change following lines
> 
> 39 results_xpath = '//div[@class="w-gl__result__main"]'
> 40 link_xpath = './/a[@class="w-gl__result-url result-link"]'
> 
> Sorry I don't know howto make a pull request
> 

Edit the file startpage.py using the github interface it will ask you if you want to make a pull request.
