### ISSUE TITLE
Installation on non default port

### ISSUE THREAD

**Issue by ckorder** [searx/searx#2381]
https://searx.github.io/searx/admin/installation.html
https://searx.github.io/searx/admin/installation-searx.html
https://searx.github.io/searx/admin/installation-nginx.html

please make it easy for use different ports because 3000 and 8888 if often taken by other services. ( many docker container, jitsi meet etc.)
i changed the ports in:
./utils/searx.sh
./utils/filtron.sh
./utils/morty.sh
./searx/settings.yml

but still get this:

 **|searx| DEBUG:searx.webapp:starting webserver on 127.0.0.1:8888**
leads to:  **OSError: [Errno 98] Address already in use**
even when i changed the ports in the configs above to 8889
i changed 3000 to 3001 in the config and the nginx config because both ports conflict my other services. within docker i got another response but it was still not working, so either provide ease port changes in normal or in the docker version, best would be making both portable.

please make a call if i got there something wrong but i was not able fix the issue in my sparetime.

```
curl --location --verbose --head --insecure 127.0.0.1:8889
  |searx| INFO:searx:merge the default settings ( /usr/local/searx/searx-src/searx/settings.yml ) and the user setttings ( /etc/searx/settings.yml )
  |searx| INFO:searx:Initialisation done
  |searx| INFO:searx.plugins.https_rewrite:29 rules loaded
  |searx| INFO:searx.search:max_request_timeout=None
  |searx| DEBUG:searx.webapp:static directory is /usr/local/searx/searx-src/searx/static
  |searx| DEBUG:searx.webapp:templates directory is /usr/local/searx/searx-src/searx/templates
  |searx| DEBUG:searx.webapp:starting webserver on 127.0.0.1:8888
  |searx|  * Serving Flask app "webapp" (lazy loading)
  |searx|  * Environment: production
  |searx|    WARNING: This is a development server. Do not use it in a production deployment.
  |searx|    Use a production WSGI server instead.
  |searx|  * Debug mode: on
  |searx| Traceback (most recent call last):
  |searx|   File "searx/webapp.py", line 1143, in <module>
  |searx|     run()
  |searx|   File "searx/webapp.py", line 1097, in run
  |searx|     threaded=True
  |searx|   File "/usr/local/searx/searx-pyenv/lib/python3.7/site-packages/flask/app.py", line 990, in run
  |searx|     run_simple(host, port, self, **options)
  |searx|   File "/usr/local/searx/searx-pyenv/lib/python3.7/site-packages/werkzeug/serving.py", line 1030, in run_simple
  |searx|     s.bind(server_address)
  |searx| OSError: [Errno 98] Address already in use
  |searx| * Expire in 0 ms for 6 (transfer 0x56259979abf0)
  |searx| *   Trying 127.0.0.1...
  |searx| * TCP_NODELAY set
  |searx| * Expire in 200 ms for 4 (transfer 0x56259979abf0)
  |searx|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  |searx|                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 8889 (#0)
  |searx| > HEAD / HTTP/1.1
  |searx| > Host: 127.0.0.1:8889
  |searx| > User-Agent: curl/7.64.0
  |searx| > Accept: */*
  |searx| > 
  |searx| < HTTP/1.1 500 Internal Server Error
  |searx| < Connection: close
  |searx| < Content-Type: text/plain
  |searx| < 
  |searx| * Excess found in a non pipelined read: excess = 21 url = / (zero-length body)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  |searx| * Closing connection 0
  |searx| HTTP/1.1 500 Internal Server Error
  |searx| Connection: close
  |searx| Content-Type: text/plain
  |searx| 
 
```

nginx config:

> server {
> 
> 
> 
> server_name search.mydomain.com;
> 
> location /searx {
>     proxy_pass         http://127.0.0.1:4004/;
> 
>     proxy_set_header   Host             $http_host;
>     proxy_set_header   Connection       $http_connection;
>     proxy_set_header   X-Real-IP        $remote_addr;
>     proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
>     proxy_set_header   X-Scheme         $scheme;
>     proxy_set_header   X-Script-Name    /searx;
> }
> 
> location /searx/static {
>     alias /usr/local/searx/searx-src/searx/static;
> }
> 
> 
> location /morty {
>     proxy_pass         http://127.0.0.1:3001/;
> 
>     proxy_set_header   Host             $http_host;
>     proxy_set_header   Connection       $http_connection;
>     proxy_set_header   X-Real-IP        $remote_addr;
>     proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
>     proxy_set_header   X-Scheme         $scheme;
> }
> 
>     listen 443 ssl; # managed by Certbot
>     ssl_certificate /etc/letsencrypt/live/search.mydomain.org/fullchain.pem; # managed by Certbot
>     ssl_certificate_key /etc/letsencrypt/live/search.mydomain.org/privkey.pem; # managed by Certbot
> 
>     include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
>     ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
> 
> }
> 
> server {
>     if ($host = search.mydomain.com) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
> server_name search.mydomain.com;
>     listen 80;
>     return 404; # managed by Certbot
> 
> }

Result in: 
https://search.mydomain.org/searx
Internal Server Error

mydomain.com/morty
502 Bad Gateway
nginx

please allow providing multiple foss services by using non default ports easily

**Comment by return42** [comment]
Do you asking for the [Installation scripts](https://searx.github.io/searx/admin/installation.html#installation-scripts),  did you read chapter [Tooling box setup](https://searx.github.io/searx/utils/index.html#tooling-box-setup)?

**Comment by ckorder** [comment]
I read the installation chapter, and used the Installation scripts. I detected that the docker container later on was still running. I haven't checked any further but i will take another look on it. At all this referred to the non clear and easy change of the used default ports, which could be improved.
