### ISSUE TITLE
Add hyperlink to searx public instances list in Error massage

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#2383]
**Is your feature request related to a problem? Please describe.**

_Error! Engines cannot retrieve results._
_torrentz (timeout), btdigg (CAPTCHA required)_
_Please, try again later or find another searx instance._

**Describe the solution you'd like**

"searx instance" should be hyperlinked https://searx.space/

**Comment by unixfox** [comment]
What do you mean by hyperlinked? I don't understand.

**Comment by GreenLunar** [comment]
> What do you mean by hyperlinked? I don't understand.

Just like @return42 did [here](https://github.com/return42/searx/commit/1db4c18fb44f6268fac318e9dc5e665b417f0222#diff-b0c6854d32d0c5c8f62e0803e68ae0f59dcadc01a3f6ccf6be2e170db9723bf7R10)
