### ISSUE TITLE
pypi.org: impossible to update searx

### ISSUE THREAD

**Issue by dalf** [searx/searx#2393]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

version 0.18.0 : 002d53abf35192ba1094d7516da10b3442ca1f16

**What happened?**

Currently, `make upload-pypi` doesn't work, it stops with this error:

```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: "linuxdoc @ git+http://github.com/return42/linuxdoc.git@70673dcf69e705e08d81f53794895dc15c4920b3#egg=linuxdoc ; extra == 'test'"
```

**Additional context**

See PR #2154 : the package versions were set to avoid flaky CI.
linuxdoc is one the package, may be we can remove the commit id for this package 
**[EDIT]** I'm not sure it will fix the issue.

I don't know if it is possible to publish on pypi.org with a dry run to detect possible error in the future.
**[EDIT]** the `testpypi` repository seems the solution.

**[EDIT2]** related to https://github.com/return42/linuxdoc/issues/5

**Comment by return42** [comment]
@dalf I will have a look at this .. but ATM I do not have time / may be at the weekend / sorry.

**Comment by return42** [comment]
@dalf sorry for the long delay .. today I released linuxdoc on pypi, before I had to handle some [issues in Sphinx's c-domain](https://github.com/return42/linuxdoc/issues/5#issuecomment-757504341) (not related to searx).

> [EDIT] the testpypi repository seems the solution.
> [EDIT2] related to return42/linuxdoc#5

I also send PR #2456 which includes:

- [mod] add target upload-pypi-test https://test.pypi.org/
- [fix] requirements-dev.txt use linuxdoc==20210110 from pypi

**Comment by return42** [comment]
@dalf I guess we can close this issue, right?
