### ISSUE TITLE
Startpage: The title result is showing the url

### ISSUE THREAD

**Issue by dalf** [searx/searx#2395]
![CleanShot 2020-12-16 at 12 00 49](https://user-images.githubusercontent.com/7293811/102400176-652ca100-3f96-11eb-86be-0aafa9c424e8.jpg)
Just updated to the newest version. 0.18.0. The title in StartPage result is showing the url rather than the page title. Same happens to other public instance.

_Originally posted by @lucky13820 in https://github.com/searx/searx/pull/2385#issuecomment-746927618_

**Comment by lucky13820** [comment]
Create a PR that fixes this issue. It's a simple fix.
