### ISSUE TITLE
Searx search box as site search for own website?

### ISSUE THREAD

**Issue by TheNomad11** [searx/searx#2413]
I would like to remove google from my website and replace it with Searx. I have searched but not found an answer to my question how I can use Searx to search only my website (although I suppose this is a trivial task). 

What I would like to have is a search box as here but using Searx: https://www.mojeek.com/services/sitesearch/searchbox.html I played a bit with different parameters without luck. Thanks!

**Comment by return42** [comment]
You are looking for something like this? ---> https://darmarit.org

Replace `action` with the URL of the searx instance of your [choice](https://searx.space/)

```html
  <form method="post"
        action="/searx"
        onsubmit="return (document.getElementById('q').value != '');">
    <input type="search" placeholder="...   &#x1F50D;" id="q" name="q" autofocus />
  </form>
```

**Comment by TheNomad11** [comment]
Thanks for your answer. Yes something like this, but it should only search a specific domain, the domain of my website - in your case it would be darmarit.org. What do we need to add so that searx only searches darmarit.org?

**Comment by return42** [comment]
[Searx is a metasearch engine which aggregates results from more than 70 search services.](https://searx.github.io/searx/).

**Comment by TheNomad11** [comment]
So it is not possible then

**Comment by return42** [comment]
Not really .. I guess you are looking for a indexer, not for a metasearch engine.  If you  already have a index, it can be include into searx, but this needs some developer knowledge / nothing you can _plug in & play_.

If you think your question is answered, please do not forget to close the issue / thanks!

**Comment by lrehmann** [comment]
you can use append "site:example.com" to the query for most search engines (google, bing, some others) to limit it to results to a particular domain, but this can also increase the chance searx encounters a captcha and the search will fail. 
I don't know if a similar 'site' parameter for mojeek.
