### ISSUE TITLE
Bing engine gives no results

### ISSUE THREAD

**Issue by joshu9h** [searx/searx#2414]
V.0.18
```
git log -1
commit 14c7cc0e118f1d0873b32b34793cdec2c5c9c13e (HEAD -> master, origin/master, origin/HEAD)
Author: Alexandre Flament <alex@al-f.net>
Date:   Fri Dec 18 09:54:03 2020 +0100

    [mod] Makefile: make CONTACT_URL optional

**How did you install Searx?**
wiki

**How To Reproduce**
!bi time

**Expected behavior**
no results

**Additional context**
also have tested on other public instance

**Comment by return42** [comment]
Probably related to https://github.com/searx/searx/issues/1933#issuecomment-617413748, #2092, #2019

**Comment by joshu9h** [comment]
It also doesn't work on searx locally
if i change line 67 to b_title
and line68 to h2
I get a result but it doesn't match
So it looks like there is no ip block

**Comment by return42** [comment]
> It also doesn't work on searx locally
> So there is no ip block

Made a short test, dumping the response: I can confirm, it is no longer IP blocking.

It seems that bing does not like the requests searx sends .. the answer is always "no results" 

OK .. its the useragent, bing does not like.

**Comment by return42** [comment]
@joshu9h I send PR #2415 .. if you like, give it a try.

**Comment by joshu9h** [comment]
@return42 good job it works fine now
