### ISSUE TITLE
Searx Own Search Engine?

### ISSUE THREAD

**Issue by trymeouteh** [searx/searx#2416]
Is it possible for searx to create and develop its own search engine instead of grabbing search results from other search engines like Google and DuckDuckGo? That way Searx has its own independent search engine which does not rely on other search engines for results.

**Comment by dalf** [comment]
Yes it is possible to develop a search from scratch with a lot of time, resources, people : it is really a huge thing.

Clearly Searx won't go into that direction.

Some links:
* https://yacy.net/ : P2P search engine.
* https://github.com/commonsearch : A nonprofit search engine for the Web - project on hold
* https://en.wikipedia.org/wiki/Comparison_of_web_search_engines
* https://en.wikipedia.org/wiki/List_of_search_engines ( the [open source section](https://en.wikipedia.org/wiki/List_of_search_engines#Open_source_search_engines) )
* https://news.ycombinator.com/item?id=25477535 : How AltaVista, the first good search engine, fell into the digital abyss
