### ISSUE TITLE
my settings.yml preferences are not working

### ISSUE THREAD

**Issue by slfg** [searx/searx#2426]
Using the following docker installation guide on searx website I was able to get the search engine running without problems

```
export PORT=80

docker pull searx/searx

docker run --rm -d -v ${PWD}/searx:/etc/searx -p $PORT:8080 -e BASE_URL=http://localhost:$PORT/ searx/searx
```

however when changing some preferences on settings.yml all of the changes except instance_name were not being used, for example autocomplete which I changed from blank to "google" or default_lang being changed from blank to pt-BR (or just pt), neither of the two changes were transfered on the engine after restarting the docker.

**Comment by dalf** [comment]
I close the issue here, there is already https://github.com/searx/searx/discussions/2425
