### ISSUE TITLE
searx website

### ISSUE THREAD

**Issue by dalf** [searx/searx#243]
As suggest by @Cqoicebordel in #222 , may be a website should created to present the project.

Purposes (open questions) : 
- Documentation (user, administrator)
- Report issue
- Brain storming
- searx instances list
- ?

Open questions, which tools should be set up ? 
- CMS
- blog
- forum
- issue tracker
- wiki
- ?

Some tools : 
- github.io (static website) with [Jekyll](http://jekyllrb.com/)
- [Redmine](http://www.redmine.org/)
- [Trac](http://trac.edgewall.org/)

Moreover, what should be kept in the "about" page of each searx instance ?

**Comment by pointhi** [comment]
I think the most important things are:
- forum (for bigger discussions, to provide platform for users/admins without developing reference)
- blog (to introduce new features officially)
- searx-instances overview
- tutorial (first start)
- multilanguage!

Other ideas:
- roadmap?
- creating a searx-style, which is used in oscar as well as on the official website. But I'm not a graphic designer.

**Comment by Cqoicebordel** [comment]
As you may think, I agree with all of you ;)

For the website, I think there shouldn't be the tech doc, at least not at first glance. I think the site should be for everyone.  
Also, Github works pretty well for issues.  
But it could be used for "tourists" to post their issue, so they can receive help.

So, for me :  
1. Index page should be a brief description of searx, with links to an instance of it, and to a tutorial.
2. Blog : so there is a place for an user to have the latest news.
3. Forums : To discuss issues and projects. Also to create a bit of a community.
4. Documentation : Tutorial + User manual + Administrator manual + Dev manual + live infos (your tool @pointhi ) + Github link

Of course, the site must be internationalized (even if we'll start in english). There should be a way to use Transifex here too (I'm against using hundreds of tools to do the same thing).

Personnally, I'm against the roadmap idea, and I don't like Trac or Redmine for the same reasons : we have no idea of what we will code tomorrow. And nobody is giving tasks. We code on what we want, when we want it, and that's what I like about this project. Maybe we need a precise todo list, and call each task so we move forward and not everywhere/nowhere, but for now, it seems to work.

For the tool to use, I have no idea. I didn't know Jekyll, but I like it very much.  
I think that we mustn't use a wiki, but treat the site as code : we (the devs) have access to it, to modify it, but not the users/tourists. So for me, whatever we use, we must put it on Github. But I can totally understand if you disagree :)

Finally, for the searx-style I'm all for it, but I'm also not a graphic designer (technically, I'm not even a webdev...)

**Comment by asciimoo** [comment]
+1
A landing page would be super useful with links and an overview of searx. All the other functionalities are good to have but we already have working solutions.

and +lot for styling (also lack of competence here)

**Comment by GreenLunar** [comment]
There is already https://github.com/asciimoo/searx/wiki/Searx-instances but it may be good to have it on website too, similarly to https://gnu.io/social/try/

**Comment by asciimoo** [comment]
started on https://asciimoo.github.io/searx/ (https://github.com/asciimoo/searx/tree/gh-pages)
