### ISSUE TITLE
Some do not respect the category

### ISSUE THREAD

**Issue by tiotrom** [searx/searx#2438]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
 
0.18.0

**How did you install Searx?**
Manually

**What happened?**
Kickass and 1337x are labeled as: category: Files in our /usr/local/searx/searx-src/searx/settings.yml but they are also available under the "videos" category. Why can't this be changed? 

**How To Reproduce**
 - Edit the  /usr/local/searx/searx-src/searx/settings.yml and label Kickass or 1337x as "category: Files".
 - Save.
 - Reboot the server. 
 - Check the frontend of Searx. 
 - Kickass and 1337x are also enabled for the videos category.

**Expected behavior**
They should only be available under the Files category.

**Screenshots & Logs**

**Additional context**

**Comment by unixfox** [comment]
Please stop removing all the field when creating an issue, those fields are there to be filled not removed!

**Comment by tiotrom** [comment]
Understood. I updated it.

**Comment by kvch** [comment]
Could you please share the exact configuration section of Kickass and 1337x?

I have tried to reproduce the problem you are describing, but it does not show up for me.

**Comment by unixfox** [comment]
Closing as I'm also unable to replace the bug.

I modified kickass like this:
```yml
- name: kickass
    engine : kickass
    shortcut : kc
    timeout : 4.0
    categories: files
```
