### ISSUE TITLE
[Feature] Proxy SearX through other SearX instances

### ISSUE THREAD

**Issue by seniorm0ment** [searx/searx#2466]
Not sure how possible this is, however I've been thinking.
It would be really nice to have the ability to self-host a searx instance, that's a bit more private. However to my knowledge this would negate some of the privacy benefits of using an instance with many other people using it. More people allows for higher anonymity, but if only a few people are making searches from an instance, I imagine it's far easier to identify them.

So I was thinking, could it not be possible to self-host an instance, and just have it send those results through other SearX instances? Not just one, but multiple. This could possibly increase load on those servers, but instead of sending all results to all searx instances, it could send some to one, some to anotherx etc.

So your searx > other searxs > centralized engines

This could possibly also have a benefit of helping searx instances in general if one has trouble with searching, it is a more decentralized redundancy in a way?

The searx host could choose to disable connecting with other searx instances, or block them (maybe the latter best left to server administration tools like nginx rather than searx)

And the searx host could also set a whitelist if they only want to connect to some instances (say they don't want to have their searches sent to searx insrances hosted in america)

I think this could be really cool, it could add redundancy by having a more decentralized approach. Of course searx instances will still need to contact the source engines somewhere.

Not sure how plausible this is, if it's even possible, or if so if it's even a good idea. But I was just thinking.
It would be nice to be able to self-host an instance for yourself (and the few people who find it) while still having those privacy benefits.

**Comment by unixfox** [comment]
It's already possible, you can add other Searx instance as a new engine: https://github.com/searx/searx/blob/master/searx/settings.yml#L753

Does this fit your needs?

**Comment by seniorm0ment** [comment]
Checked, Does this mean the user would need to disable all other search engines and only use SearX? That seems to be the case?

Because that would cause the issue of having a lack of customization of search engines. 

If selfhosting an instance, the user could choose what search engines they wanted, then when connecting to other searx instances if they didn't support one of those engines, it'd try another one of your preferred instances for that engine, then merge the results with the first instance.

**Comment by unixfox** [comment]
> Checked, Does this mean the user would need to disable all other search engines and only use SearX? That seems to be the case?

If you want to only have the results from the proxied Searx instance then yes.

> Because that would cause the issue of having a lack of customization of search engines.

There is no ability to pass any preferences (engines activated, plugins enabled and so on) but feel free to modify your initial feature request if that's what you want.

**Comment by dalf** [comment]
In case you are thinking something similar to https://github.com/searx/searx/issues/792 

To make it simple, searx has to be reliable before thinking about P2P, otherwise the user experience will be disappointing. It requires various metrics, some has been implemented ( #2332 #2375 #2419 ), some others are missing like https://github.com/searx/searx/pull/477

**Comment by seniorm0ment** [comment]
Ok yes @dalf, didn't see that post when searching. That looks to be what I'm suggesting in a nutshell.
Feel free to close this issue.

**Comment by seniorm0ment** [comment]
Looking back on this, basically what does this mean for users wishing to self-host a searx instance?

Are there currently any privacy friendly way to do it currently (without running everything through a proxy/vpn)? 
With big instances, you have many people using it which makes it a bit better for privacy, but when you self-host a private instance mainly for yourself, all your results are essentially linked to you, as well as the ip of your server (which would be the same as browsing directly).
Yes I've read https://searx.github.io/searx/user/own-instance.html but it doesn't entirely address these concerns from what I see besides mentioning it can use tor/proxy.

The reason for wanting to self-host is to have a high performing (less users using it) stable instance with full control.
