### ISSUE TITLE
useless language_support variable ?

### ISSUE THREAD

**Issue by dalf** [searx/searx#2485]
The documentation says 

> `language_support` support language choosing

which make sense according to the variable name. Actually, this variable definition exists but is never used :

```
$ git grep "language_support = False"
searx/engines/doku.py:language_support = False
searx/engines/duden.py:language_support = False
searx/engines/etools.py:language_support = False
searx/engines/genius.py:language_support = False
searx/engines/youtube_noapi.py:language_support = False

$ git grep "language_support" | grep -v "language_support = True" | grep -v "language_support = False"
# documentation
docs/admin/engines.rst:        - {{(mod.language_support and "y") or ""}}
docs/dev/engine_overview.rst:language_support        boolean     support language choosing

# default value is True
searx/engines/__init__.py:                       'language_support': True,

# /config URL
searx/webapp.py:            'language_support': engine.language_support,

# False positives
searx/webapp.py:            stats[e.name]['supports_selected_language'] = _is_selected_language_supported(e, request.preferences)
searx/webapp.py:def _is_selected_language_supported(engine, preferences):
```

The use of this variable has been removed before the version 0.12.0 : https://github.com/searx/searx/commit/fd65c1292179fb082e965a1ee6a88b9298a54fc1#diff-f5962794ee51e4631700f577aa174f19623c87377130020dba94bd55410f5420L376

According to what I understand, the value should be `language_support = len(supported_languages) > 0` :
* `supported_languages` gets it's value from `searx/data/engines_languages.json` https://github.com/searx/searx/blob/f310305c54c3cd1d9fc74f09453294edbd2b5486/searx/engines/__init__.py#L116-L120
* `supported_languages` default value is an empty list : https://github.com/searx/searx/blob/f310305c54c3cd1d9fc74f09453294edbd2b5486/searx/engines/__init__.py#L48

So I suggest:
* to set `language_support = len(supported_languages) > 0`, so the documentation, `/config` can return the right values.
* to remove all `language_support = True` / `language_support = False` in the engines.

ping @MarcAbonce

**Comment by MarcAbonce** [comment]
Yeah, that variable is redundant with `supported_languages` so it could be removed.
