### ISSUE TITLE
Using more memory?

### ISSUE THREAD

**Issue by Fluffkin** [searx/searx#2489]
Searx  5a511f0d620038b8e94c581bcfd3c987082b9414 commit id (0.18.0)
Installed as wiki

Increasing memory use compared to previous versions.
I admit I didn't upgrade for ages, but this version of searx seems to use much more memory over time than previous versions. At the moment around 406KB of memory. Not sure I'd ask if it's a leak (it almost never is), but previous versions didn't seem to retain memory like this. It seems to very slowly increase over time.

**How To Reproduce**
Run searx for a few weeks without restarting it and keep sending it queries.

**Expected behavior**
Less than 400KB of memory used for something that's basically sitting there doing nothing waiting for a query / webpage load. Pretty sure it didn't use this much memory a few months ago. Could be a library searx depends on being a glutton. But it's becoming an issue on a Pi 3b. It wasn't an issue a while back.

**Comment by unixfox** [comment]
We introduced a new component called searx-checker. Maybe you have it enabled in your settings.yml. This component is doing some requests in the background.

Look if scheduling at this line is commented or not: https://github.com/searx/searx/blob/master/searx/settings.yml#L115

**Comment by dalf** [comment]
The other thing I'm thinking about is [searx/data/bangs.json](https://github.com/searx/searx/blob/master/searx/data/bangs.json) (1.43MB on disk)

You can replace the content by:
```json
{
  "bang": []
}
```

**Comment by return42** [comment]
OT: @dalf should we add some documentation about checker? .. if you have some additional hints or links (feel free to send me a PN) I can prepare a PR with reST docs .. BTW It would be an opportunity for me to take a closer look at _checker_ ...

**Comment by Fluffkin** [comment]
I've tried the "scheduling: False" trick. Thanks for the tip @unixfox 
Looks good on startup, will have to wait and see how it does after a few days.

**Comment by unixfox** [comment]
I'm closing this issue and reopen if you still experience the same memory issue.
