### ISSUE TITLE
Add search engines for lbry.tv and odysee.com 

### ISSUE THREAD

**Issue by nukelr** [searx/searx#2496]
**Working URL to the engine**

**Why do you want to add this engine?**

**Features of this engine**

**How can Searx fetch the information from this engine?**

**Additional context**

**Comment by swedneck** [comment]
the search url appears to be https://lighthouse.lbry.com/search?s=QUERYSTRING&size=5&from=0&nsfw=false

**Comment by unixfox** [comment]
Please update your original comment by filling the fields from the issue template. It's really important for us!

Next time please fill them instead of removing them.

**Comment by unixfox** [comment]
Lack of required filled fields, I'll close this issue because those fields are important for the developers!

Reopen when you will have filled the fields.
