### ISSUE TITLE
Automatically block real life gore and awful things like that

### ISSUE THREAD

**Issue by ghost** [searx/searx#2518]
**Is your feature request related to a problem? Please describe.**
I watched a video of richard stallman and his opinions on things,then there was a quote that he finds pedophilia and bestiality not problematic if the sexual partner is ok with that (what doesn't make sense cause kids and animals can't consent).
Cause I didn't know what bestiality is,I searched it up on duckduckgo and saw awful images of abused animals.
The problem is that I didn't even clicked on images,the images were just over the websites.
And the websites were not sites that explained that topic,but animal abuse sites.
I don't actually know if this problem happens on Searx,cause I don't wanna search that topic again,but I don't think that searx is that much more advanced than duckduckgo.
The problem of that all is self explained and I am pretty sure that anyone would be happy if that problem gets blocked,cause it limits my research if there are just gore sites instead of sites that explain bestiality.

**Describe the solution you'd like**
That Searx blocks every image or site or videos that has animal gore,human gore,child porn,corpses,murderer,suicide videos etc..
So basically everything that is ethically not correct.
And I want that this sort of content gets also blocked in adult mode on,cause I have that on,cause I watch much Hentai and don't exspect to see gore on my research.
And I want that content blocker for Clear Web and Dark Web,
Btw I don't want that video game violence gets blocked,cause that isn't real and the demons from doom deserved it.
And also,I want no way to disable that,cause the only people who search up for that are mentally ill people,"trolls" who send links of those sites to people on reddit,dumb kids who wanna flex that they can watch gore videos and people who wanna watch that to see if things like executions really happened.
But no normal person who just researched for dark topics want to actually see images and videos of that.
I also want that animated sexual images/videos of underaged characters,kids or animals get blocked,cause that also isn't good and even if those drawings aren't real people,the mentally ill people who look up those things could perform those actions in real life if they think that it's ok.

**Additional context**
I hate those sites and the research of richard stallman wasn't the only time I saw something like this.
I clicked on random russian sites that I found on darknet link sites cause most of them were normal until one disgusted me,when I clicked on that site I saw corpses and cp.
Or I just was on Reddit and some assholes posted some links and I just had to click on them,then I saw animal torture.
Cause of crap like that,I hate searching on the web,those mentally ill people just destroy any fun of the web.
So with a blocking feature like that,Searx could make the whole web searching more fun.
For the people who send links of gore sites,Searx can't do anything,I will make a firefox feature request to block that.

**Comment by unixfox** [comment]
Duplicate of https://github.com/searx/searx/issues/1433, https://github.com/searx/searx/issues/1410, https://github.com/searx/searx/issues/2446 and https://github.com/searx/searx/issues/2001.

**Comment by ghost** [comment]
Those reports are only for normal porn sites,but what I mean are really disgusting sites that only mentally ill people use.
And I don't want a self hosted block list,I want that those sites get blocked automatically  from every searx host,cause I want that those mentally ill can't access those sites at all.

**Comment by reeseovine** [comment]
Does SafeSearch not take care of that? I'm not sure where it gets its blocklist from but if they still show up with SafeSearch on then that's an issue.

**Comment by ghost** [comment]
SafeSearch won't stop the sickos from accessing illegal content.
My problem is not only that I don't want to see disgusting results,but I also don't want that sickos can access illegal sites with searx.
I take my statement back that it should auto block gore,cause most people who watch gore are not sickos who masturbate to it or whatever but are morbid curiosit or want to know how the human body works or whatever.
For the bestiality block you can argue that it is legal to watch and therefore ok,but I don't think that that makes it ok,cause most people who watch bestiality are probably zoophiles,I mean why the heck would people watch it if they aren't zoophiles?
I mean they could just be extremely morbid curiosit,but the question is,how much of them are vs how many zoophiles watch that?
But the biggest problem with searx is that you can even find illegal porn so easily,look at the results when you search "porn" with the darknet search,it lists many cp and that is even illegal to watch so I don't think that we need an discussion why this should be auto blocked.
Blocking cp only for safe search would be fucking dumb cause the predators can just disable it,and I just hate it that right now probably some predators abuse searx to access illegal material.
Btw I also want that Hurtcore gets autoblocked and that everyone who searches for cp or hurtcore gets results for therapy for those mental illnesses instead of sites that show illegal material.
