### ISSUE TITLE
Display wrong language in the search interface.

### ISSUE THREAD

**Issue by laichiaheng** [searx/searx#2525]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

**How did you install Searx?**

Just use it in the web browser.
**What happened?**

The UI language is wrong.
**How To Reproduce**

Open searx search page.
**Expected behavior**

See the right language.
**Screenshots & Logs**

![圖片](https://user-images.githubusercontent.com/9532105/106374524-08a70900-63bf-11eb-8112-3fba816bd635.png)

**Additional context**

I'm using Traditional Chinese, but it displays the Simplified Chinese.
https://www.transifex.com/asciimoo/searx/dashboard/
It is fully translated to my language, but it still displays Simplified Chinese.
It also searches lots of websites from China, although I have selected Taiwan.

**Comment by laichiaheng** [comment]
I can change the UI language in settings, searx doesn't recognize my language automatically.
It is painful when I am browsing the web in incognito mode
![圖片](https://user-images.githubusercontent.com/9532105/106376781-4e6dcc80-63d3-11eb-9344-339f63d00f38.png)

**Comment by MarcAbonce** [comment]
What's the `Accept-Language` header in your browser?

**Comment by laichiaheng** [comment]
@MarcAbonce Where to see it? I'm using Firefox.

```
❯ pacman -Qs firefox
local/firefox 85.0-1
    Standalone web browser from mozilla.org
local/firefox-i18n-zh-tw 85.0-1
    Chinese (Traditional) language pack for Firefox
```

**Comment by MarcAbonce** [comment]
In `about:config` it appears as `intl.accept_languages`.

**Comment by laichiaheng** [comment]
@MarcAbonce 

`intl.accept_languages | zh-tw`
