### ISSUE TITLE
wolframalpha (unexpected crash) when looking for a chemical reaction 

### ISSUE THREAD

**Issue by buvanenko** [searx/searx#2574]
This happens on all currently running instances. Just try to go to the Science category and find H2 + O 

----

**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

**How did you install Searx?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Comment by unixfox** [comment]
Please fill the correct issue template, it's important for us.

I added it to your original comment, so please fill it.

**Comment by unixfox** [comment]
Reopen this issue when you will have filled the correct issue template.

**Comment by MarcAbonce** [comment]
I could reproduce the bug in master with the example OP provided: `!wolframalpha H2 + O` which returns ` wolframalpha (unexpected crash 'pods') `.

**Comment by MarcAbonce** [comment]
Ok, so with `H2 + O` WolframAlpha returns a JSON with no `"pods"`, which can be validated by `"numpods": 0`. So, the response has basically no valuable information we can show the user.
Instead, the response contains a `"recalculate"` URL which returns the actual results.
However, it takes a couple of seconds to calculate. For example, I got `"timing": 4.95`. So calling this second request is most likely going to reach searx's timeout.

**Comment by dalf** [comment]
We can increase the timeout for the wolframalpha engine.

**Comment by ItsIsmailZ** [comment]
IT category doesn't work either... (I am using searx.ninja)
`searchcode doc (unexpected crash Extra data: line 1 column 5 (char 4))`
And H2 + O using searx.xyz doesn't work in General, IT and some others.
And btw why is there a cookie on every site? I blocked it and searx still works... strange.

**Comment by unixfox** [comment]
> IT category doesn't work either... (I am using searx.ninja)
> `searchcode doc (unexpected crash Extra data: line 1 column 5 (char 4))`
> And H2 + O using searx.xyz doesn't work in General, IT and some others.
> And btw why is there a cookie on every site? I blocked it and searx still works... strange.

Instance specific issues has to be reported here: https://github.com/searx/searx/discussions/categories/public-searx-instances-report-a-bug

**Comment by asciimoo** [comment]
I cannot reproduce it. It works well with the `!wolframalpha H2 + O` query.
