### ISSUE TITLE
Categories are displayed in random order

### ISSUE THREAD

**Issue by dalf** [searx/searx#258]
The order of the categories is not defined somewhere.
The order is different in the preference page.

Here is commit to solve the issue : 
https://github.com/dalf/searx/commit/251635e9538abc8bdb02ae234120f677db500bb2

May be, the order should be set in the settings.yml file ?

**Comment by asciimoo** [comment]
Currently the order of categories: "general" first and alphabetical order after. The bug is in preferences which ignores this (https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L569)

**Comment by dalf** [comment]
Sorry I don't saw that. Do you think it should be configured ? How ?
