### ISSUE TITLE
options for paid google search api (for private instances mostly)

### ISSUE THREAD

**Issue by thesophiaxu** [searx/searx#2622]
**Working URL to the engine**
https://support.google.com/programmable-search/thread/82751048?hl=en

**Why do you want to add this engine?**
Seems like google also offers a way to legally get search results via an Api called the programmable search engine. 

Costs: daily first 100 searches for free, then $5 for every 1000 searches. Considering the average person makes ~70 searches a day (we multiply the number by 2 for tech savvy users) the monthly cost should be roughly the cost of a Netflix subscription, but I'm getting ahead of myself here

**Features of this engine**
- doesn't violate the google TOS (if users care about that) and won't get banned
- search queries not tied to a google account - since this API is intended for website owners, the users' queries shouldn't be logged and profiled; additionally if you have a couple of friends to split the costs you can share the API to obfuscate queries

**How can Searx fetch the information from this engine?**
Probably just use the json-engine preset, but we can also use some heuristics to limit the requests (such as: searching ddg/wikidata/wikipedia only for short queries)

**Applicable category of this engine**
General

**Additional context**
I'm thinking of implementing this feature, haven't looked at the codebase yet, just want to ask if people are interested in this

**Comment by unixfox** [comment]
Apart from just wanting to use the Searx interface with google results I don't get the point of implementing that.

Every request is done under your name (or not? If so please prove it) so on the privacy side it's as bad as using Google Search while being connected with a Google account.

Moreover, with $5 you can get enough proxies for bypassing the Google captcha entirely for one month. Even if this technique does in fact break their TOS.

**Comment by thesophiaxu** [comment]
> Moreover, with $5 you can get enough proxies for bypassing the Google captcha entirely for one month. Even if this technique does in fact break their TOS.

Thanks for the comment! I didn't know there are paid proxies to bypass the google captcha - searched around but to no avail :( Do you have some keywords about them I can search for?

> Every request is done under your name (or not? If so please prove it) so on the privacy side it's as bad as using Google Search while being connected with a Google account.

According to the doc the request is just your regular search term + a custom search engine ID (which is supposed to be exposed over the internet) so there's really no way to identify individuals or profile them.

maybe if the proxy thing doesn't work out I'll just write something for my fork.

EDIT: Found something for proxies - I'll give that a try and come back if it doesn't work out. If I end up implementing this, maybe I can make it into a plugin instead?

**Comment by unixfox** [comment]
> EDIT: Found something for proxies - I'll give that a try and come back if it doesn't work out. If I end up implementing this, maybe I can make it into a plugin instead?

You mean creating a new engine for Google into a plugin? I don't get it. A plugin is not supposed to do that.

**Comment by virtadpt** [comment]
@unixfox Personal use.  Say, one uses Searx for its API and search result feeds, and not necessarily for privacy?
