### ISSUE TITLE
rel="noreferrer"

### ISSUE THREAD

**Issue by dalf** [searx/searx#264]
Adding rel="noreferrer" to the result links would help to "hide" searx : 
https://html.spec.whatwg.org/multipage/semantics.html#link-type-noreferrer

Firefox support : ok since version 33 : https://bugzilla.mozilla.org/show_bug.cgi?id=530396
Chrome support : ok : https://code.google.com/p/chromium/issues/detail?id=345783
IE : I don't know

**Comment by ghost** [comment]
searx/searx/templates/default/result_templates/code.html

<a href="{{ result.url }}">{{ result.title|safe }}</a>
--->
<a href="{{ result.url }}" rel="noreferrer">{{ result.title|safe }}</a>

**Comment by dalf** [comment]
implemented: #299
