### ISSUE TITLE
Search through only given websites.

### ISSUE THREAD

**Issue by bugswriter** [searx/searx#2644]
Search Filtering

So if I have a list of websites and I only want my searx to give results from only those sites and not from the whole internet?
is that possible?

**Comment by virtadpt** [comment]
You can do it with search engines' shortcuts (listed in the searx/settings.yml file).  `!ai` for archive.is, `!bi` for Bing, `!eto` for eTools, `!qw` for Qwant, and so forth.

If you go to the Preferences page of your instance, then click on the Engines tab you'll see a list of all the engines that instance supports as well as their shortcuts.  You can also chain them in the same search:

`!bi !ddg !wp all your base are belong to us`

**Comment by return42** [comment]
Engine overview is documented here https://searx.github.io/searx/admin/engines.html
