### ISSUE TITLE
[invalid] Set language according to header

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#267]
I use Tor and often get searx in German or Russian. Please make searx to set language according to header of web browser user-agent, **only when that header has a language(s) set up**.

From #231

**Comment by asciimoo** [comment]
This is the default behavior: https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L116

**Comment by GreenLunar** [comment]
Sorry, I did not set a preferred language.
