### ISSUE TITLE
Two 404 errors with today’s master installation

### ISSUE THREAD

**Issue by cyclaero** [searx/searx#2670]
***Version of Searx:*** master  7e5553ddb6662c9f6eb46adf77cee84dbcedf2aa

***How did you install Searx?***

On FreeBSD 12.2-RELEASE-p4, I issued from within searx-master which has been extracted from today’s master.zip:

`python3.7 setup.py install`

***What happened?***

When opening searx, the page loads fine, however the web inspectors of any of my browsers (Vivaldi Mac|Win, Firefox Win, Safari Mac show me two 404 errors, for the following links:

`http://searx.mylocal.net/static/themes/oscar/css/css/logicodev.min.css.map`
`http://searx.mylocal.net/static/themes/oscar/css/css/bootstrap.min.css.map`

Note the double `css/css/` in the middle of the URLs.
 
***How To Reproduce***

Visit a public searx instance which is running the latest master, e.g. this one:

https://searx.webheberg.info

Then open the web inspector or developer mode, or however it is called by your browser.

***Expected behavior***

The site loads without 404.

***Screenshots & Logs***

![SearX 2x 404](https://user-images.githubusercontent.com/13712142/111871097-33e1b980-8967-11eb-89ce-f7f6a01b2a21.png)

***Additional context***

When I manually open any of above links, the 404 error page of searx is displayed. When I manually remove one of the double `css/` in the url, then the respective file is loaded correctly.

**Comment by unixfox** [comment]
This won't affect Searx core functionalities. It's just a warning that the DevTools can't load the source maps, more about that here: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

It's caused by the fact that `sourceMappingURL` in `bootstrap.min.css` doesn't have the correct path:
```css
sourceMappingURL=css/bootstrap.min.css.map
```
It should be:
```css
sourceMappingURL=bootstrap.min.css.map
```

@dalf Any ideas about how to fix the path for `sourceMappingURL` in `bootstrap.min.css`? I don't know how is bootstrap minified in the project.

**Comment by cyclaero** [comment]
Sorry, I never dealt with these source maps, and didn’t exactly understand what is going on. Now after reading about it, I understand, that these are only useful when working on the web interface and also only with the web inspectors / developer tools of older browsers. WebKit based bowsers do render minimal CSS and JS files in their web inspectors automatically without map files.

Since, I am a Searx user und merely want to change something of the web interface (for now, I like it very much as it is), I added to my searx installation shell script for macOS the following:

    cd searx-master
    /usr/bin/sed -Ee "s|/{1,2}\**# sourceMappingURL=.*.map.*||" -i "" searx/static/themes/*/*/*.min.*

This resolved the problem for me, and it seems, that the site is loading faster, but the latter may well be delusion. That said, developers who rely on a working .map-file, probably would like to see the sourceMappingURLs fixed.
