### ISSUE TITLE
DOI resolver: replace sci-hub.tw with alternative domains

### ISSUE THREAD

**Issue by 1366613** [searx/searx#2693]
Sci-Hub is no longer operating through the [sci-hub.tw](https://sci-hub.tw) domain, so it can't be used as a DOI resolver.
Better to redirect the Sci-Hub DOI resolver to a randomly-selected domain from the following list:
sci-hub.se
sci-hub.do
scihubtw.tw
sci-hub.it.nf
sci-hub.st
sci-hub.bar

**Comment by unixfox** [comment]
Feel free to open a pull request with a new sci-hub domain included by default in the settings.yml: https://github.com/searx/searx/blob/master/searx/settings.yml#L1398

I'm not familiar with this type of service, so I don't know which domain to update in the settings.yml.
