### ISSUE TITLE
After clicking on "reload the search to include omitted results" launch a search of the said phrase

### ISSUE THREAD

**Issue by stemy2** [searx/searx#2705]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
0.18.0

**How did you install Searx?**
Yunohost installer
**What happened?**
After performing a serach, i clicked on the button "reload the search to include omitted results", then searx searched "reload the search to include omitted results"

**How To Reproduce**
1. Perform a search.
2. Click on "reload the search to include omitted results"

**Expected behavior**
Reloading a search of omitted result instead of searching "reload the search to include omitted results".

**Screenshots & Logs**
Before clicking on the button in the frame "suggestions".
![Screenshot_20210330_233237](https://user-images.githubusercontent.com/22192600/113060300-fae3e900-919f-11eb-8748-1e3aa8065b9a.png)

After clicking on the said button
![Screenshot_20210330_233500](https://user-images.githubusercontent.com/22192600/113060359-0e8f4f80-91a0-11eb-95f9-5f162d840083.png)

**Comment by unixfox** [comment]
Closing as a lack of reply to my question and I'm unable to replicate the bug.
