### ISSUE TITLE
Use the method setting for opensearch.xml

### ISSUE THREAD

**Issue by ldidry** [searx/searx#271]
In the preferences, there is a setting for setting the method (POST or GET) you want to use, but when you add searx to your web browser's search engines, you can only search with POST (except Chrome that can only handle GET method).

It seems logical to use the method the user choose for the web interface, don't you think? I could do a PR if you tell me it's OK.

**Comment by asciimoo** [comment]
For the record, GET request leaks a lot more information than POST. Not just on server and client side, but the referrer also passes the search query to the target site. Thats why searx doesn't support GET by default.

**Comment by ldidry** [comment]
Yes, I know, but I like to get an history of my searches since I often re-search the same thing.

Besides, it will stay on POST by default so it's up to the user to choose an non-private method.

What do you prefer?
- [ ] use the existing setting for method
- [ ] add a new setting just for the browser's integration

**Comment by asciimoo** [comment]
Imho the existing is okay. Thanks!

**Comment by dalf** [comment]
Note : that's point of the rel="noreferrer" : hide the referrer to the target site.
Of course, I would have been too simple if all browser support this feature.
