### ISSUE TITLE
question about opensearch with "get method"

### ISSUE THREAD

**Issue by xavierle** [searx/searx#272]
this is a question about the opensearch functionality

i have the feeling this opensearch is actually implemented in post method not implemented in get method.

am i right ?

for my instance i am actually preferring the get method.
what shall be done to complete the get method for opensearch ? (maybe i can give a hand)

if you think get method for opensearch is not possible i will find a way to adapt my instance for this way

**Comment by dalf** [comment]
I think this is a duplicate of #271 : @ldidry can propose a pull request about this feature.

If you are in hurry, you can hack your instance, see : 
https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L646

Replace 'post' by 'get'.

**Comment by ldidry** [comment]
Ok, I will propose a pull-request soon.

**Comment by xavierle** [comment]
@dalf  yes it seems a kind of duplicate 

and yes
I was looking for this part of the webapp.py file
thank you for confirmation

i will do the hack for now

bonne journee

**Comment by dalf** [comment]
@xavierle :  can you close this issue since there is another one about the same subject ?

**Comment by xavierle** [comment]
ok i close it
