### ISSUE TITLE
Defaults to oadoi.org instead of default DOI resolver

### ISSUE THREAD

**Issue by 0xhtml** [searx/searx#2722]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
76a5305e

**How did you install Searx?**
Installed via AUR.
https://aur.archlinux.org/packages/searx-git/

**What happened?**
The DOI resolver defaults to `oadoi.org` even though `sci-hub.tw` is set as default in `settings.yml`.

**How To Reproduce**
- Clear all preferences / use incognito mode
- Enable Open Access DOI rewrite extension in preferences.
- Search for e.g. `!crossref chess alpha beta pruning` and look at result URLs.

**Expected behavior**
URLs should be rewritten to `sci-hub.tw` and not `oadoi.org`.

**Screenshots & Logs**
N/A

**Additional context**
N/A
Edit: `oadoi.org` also shows up as selected DOI resolver on the preferences page.

**Comment by return42** [comment]
> The DOI resolver defaults to oadoi.org even though sci-hub.tw is set as default in settings.yml.

This should be fixed by #2707 / @0xhtml could you please checkout master and verify that this issue is can be closed / thanks!

**Comment by 0xhtml** [comment]
Thanks, the default DOI resolver can now be set.

However, this raises a new issue I can't set `default_doi_resolver` in `settings.yml` if I'm using `use_default_settings`. Searx seems to try to interpret all settings at root level in `settings.yml` as dict, which is correct except for `default_doi_resolver` which is at root level and a string.

The error message:
```
File "/usr/lib/python3.9/site-packages/searx/settings_loader.py", line 125, in load_settings
    update_settings(default_settings, user_settings)
File "/usr/lib/python3.9/site-packages/searx/settings_loader.py", line 61, in update_settings
    update_dict(default_settings[k], v)
File "/usr/lib/python3.9/site-packages/searx/settings_loader.py", line 48, in update_dict
    for k, v in user_dict.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by return42** [comment]
> this raises a new issue

@0xhtml  thanks for the hint, I sent #2728 to fix that issue.

**Comment by 0xhtml** [comment]
Works now. Thanks.

**Comment by return42** [comment]
> Works now. Thanks.
