### ISSUE TITLE
Infinite redirects if base_url ends with /

### ISSUE THREAD

**Issue by mbirth** [searx/searx#2729]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
1.0.0-26-70895267

**How did you install Searx?**
Docker image: searx/searx:latest

**What happened?**
After upgrading my base image from the version from about 6 days ago to the current one, trying to open my Searx page gave infinite redirects.

**How To Reproduce**
Set base_url to something like `https://searx.mydomain.com/` (trailing slash!)

**Expected behavior**
Start page opens as expected.

**Screenshots & Logs**
```
$ wget -O - http://localhost:8080/
--2021-04-05 23:05:59--  http://localhost:8080/
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 308 PERMANENT REDIRECT
2021-04-05 23:05:59 ERROR 308: PERMANENT REDIRECT.
```

**Additional context**
Solved the issue by changing base_url to `https://searx.mydomain.com` (no trailing slash).

**Comment by Ryonez** [comment]
Will confirm this issue, and the workaround with changing the `base_url` worked for me.

**Comment by cybermcm** [comment]
Can confirm this issue, but workaround is not working in my case (changing base_url).
changing back to 1.0.0-24-ba90c5a2 (working with docker image) -> working (with and without trailing slash).

**Comment by blae-s** [comment]
> Can confirm this issue, but workaround is not working in my case (changing base_url).
> changing back to 1.0.0-24-ba90c5a2 (working with docker image) -> working (with and without trailing slash).

The workaround works for me with a docker image editing base_url in ~/searx/settings.yml file

**Comment by cybermcm** [comment]
@blae-s: thx for your reply, I changed the `base_url` in my environment variable not in the settings file. Changing `base_url` in the `settings.yml` file works!

**Comment by Freekers** [comment]
Same here. Removing the trailing slash from the `base_url` environment variable did not solve my issue, but changing it inside the ```settings.yml``` resolved the issue for me. Thanks!

**Comment by kvch** [comment]
Could you please share what command did you run exactly? I am pretty new at running searx in Docker, and so far I got nothing. :(

**Comment by cybermcm** [comment]
@kvch: no command. You should have a volume for your persistent data (`/etc/searx`). Within this volume you can see 2 files, one of them is `settings.yml`
There is a section called `server:` and there is a setting called `base_url`. You have to edit this setting and remove the trailing slash.
