### ISSUE TITLE
Provide a RSS or Atom feed for the searx blog

### ISSUE THREAD

**Issue by jurgenhaas** [searx/searx#2748]
Would be great if we could subscribe to the blog at https://searx.github.io/searx/blog/index.html

**Comment by return42** [comment]
> Would be great if we could subscribe to the blog at https://searx.github.io/searx/blog/index.html

:-) ..sorry,  the wording is misleading the "blog articles" are common articles, it is not a "blog" one can subscribe.

**Comment by jurgenhaas** [comment]
That's unfortunate because I think it qualifies for being subscribed as the articles are really valuable.

**Comment by return42** [comment]
> That's unfortunate because I think it qualifies for being subscribed as the articles are really valuable.

Thanks a lot for your appreciation! The true is that we are a very small [team](https://github.com/searx/searx/discussions/2474) and we do not often release new articles in this "blog" .. We apologize for not being able to perform all tasks to the extent requested.

**Comment by jurgenhaas** [comment]
No reason to apologize at all !!! You're doing a great job - and some of us may even know how it is in a FOSS environment.

**Comment by return42** [comment]
> and some of us may even know how it is in a FOSS environment.

.. oooh yes :-)  / Thanks a lot for your understanding / If it is OK for you, do you like close this issue?

**Comment by jurgenhaas** [comment]
Sure.
