### ISSUE TITLE
NoScript XSS

### ISSUE THREAD

**Issue by ilf** [searx/searx#277]
Searches via Firefox search-bar with enabled NoScript result in:

> [NoScript XSS] Sanitized suspicious upload to [https://searx.me/] from [chrome://browser/content/browser.xul]: transformed into a download-only GET request.

https://noscript.net/faq#qa4_1

**Comment by Cqoicebordel** [comment]
I guess it's inherent to the way the search is done through POST.
Maybe by setting it to GET in the prefs, would solve this.

I'll nonetheless look into this.

**Comment by asciimoo** [comment]
I can't reproduce, is it occurs on every search?

**Comment by ilf** [comment]
Not every single one, but most. "test", for example.
How about just using GET instead of POST?

**Comment by dimqua** [comment]
I believe this issue is not relevant anymore.
