### ISSUE TITLE
Youtube_noapi engine returns no results due to cookie consent redirect

### ISSUE THREAD

**Issue by Chronody** [searx/searx#2774]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
v1.0.0 commit ae122ea943f77600fd97556503c483dcd92e1e63 official Repo

**How did you install Searx?**
Manual installation via official guide

**What happened?**
When trying to use the youtube_noapi engine it fails with a generic "couldn't find any results" error.
Inspecting the logs shows that searx is being redirected to youtubes cookie consent site (https://consent.youtube.com).

This seems to happen only within the EU. I tested some European instances and found all of them had broken youtube searches while American ones seem fine.

**How To Reproduce**
1. Host/Use a searx instance within the EU
2. Make a request to the youtube_noapi engine (e.g. "!yt test")

**Expected behavior**
Results from youtubes search page should be displayed by searx.

**Actual behaviour**
No results are displayed.

**Screenshots & Logs**
`
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.youtube.com:443
DEBUG:urllib3.connectionpool:https://www.youtube.com:443 "GET /results?search_query=test&page=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): consent.youtube.com:443
DEBUG:urllib3.connectionpool:https://consent.youtube.com:443 "GET /m?continue=https%3A%2F%2Fwww.youtube.com%2Fresults%3Fsearch_query%3Dtest%26page%3D1&
gl=DE&m=0&pc=yt&uxe=48395746&hl=de&src=1 HTTP/1.1" 200 None
`

**Additional context**
The cookie consent site sets a "CONSENT" cookie which subsequently is sent with all requests to youtube.
Without this cookie, using a normal browser, one will always be redirected to the consent page.
This does not happen when using curl, seemingly because it doesn't send a browser User-Agent with it's requests.

**Potential solution**
Trying around i managed to fix this issue in 2 ways:
1. Setting the consent cookie manually in the engines request function. The cookie value is simply copied from the browser:
`params['cookies'] = {'CONSENT': "YES+cb.20210401-14-p0.de+F+512"}`
(The value differs depending on machine/user so the above one should only be used to infer the format.)
2. (Probably preferable) Setting an empty User-Agent in the engines request function:
`params['headers']['User-Agent'] = ""`

**Comment by unixfox** [comment]
Could you submit a pull request for that?

**Comment by kvch** [comment]
@return42 Was it on purpose that you fixed a searx issue in searxng? Next time please open a separate issue in searxng and refer to that in the PR. It was misleading to me. I thought you fixed the problem in searx and I was confused why the issue was still open.

**Comment by kvch** [comment]
Closed by https://github.com/searx/searx/commit/34d7d97e1e59515cd9d81916e273206154bde07e

**Comment by return42** [comment]
@kvch With respect to the creator I always refer to the origin. It is not me who inserts back references which might be misleading here, its github.  But this should not a drawback for you, you see it here and can cherry pick it (what you have done). I guess this was also the motivation why github insert back references.

**Comment by asciimoo** [comment]
@return42 it already caused confusion, see https://github.com/searx/searx/pull/2665 for example.

**Comment by asciimoo** [comment]
@return42 @dalf It's totally fine that you are working on a fork, but please try to fix issues that belong to that repository. Of course we appreciate if you reference the issues in this repo from the issues you created on your fork, but please do not address issues/PRs created here from your PRs, because it can be misleading as you can see from @kvch and from the PR mentioned above. Especially because the name of the fork is quite similar to ours. It's ok if you reference to this repo from an issue, but it can be confusing if it comes from a PR.
