### ISSUE TITLE
Documentation: manage.sh update_packages does not exist enymore

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#2776]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
4828faaa0701a6982becebb8e223e0bbe10ce559

**How did you install Searx?**

Manually installed via quick install documentation, searx-src beside searx-pyenv.

**What happened?**

`update-searx.rst` must be updated concerning `manage` instead of `manage.sh`

Update according to  `update-searx.rst` is not possible:

```
    sudo -H -u searx -i
    (searx)$ git stash
    (searx)$ git pull origin master
    (searx)$ git stash apply
    (searx)$ ./manage.sh update_packages
```
`manage.sh` does not exist anymore (since f7706a5c7fa33f38b4759586b514d64ac659eca3) but there is no documentation
how to update python packages via `manage`

**How To Reproduce**

Try to execute all commands above

**Expected behavior**

`manage.sh update_packages` can be called. No I expect the right documentation via state of the art `manage`

**Comment by kvch** [comment]
Closed by https://github.com/searx/searx/commit/aa8288a9630c10f43e5cf952763a79f00d6a369a
