### ISSUE TITLE
Petalsearch.com Engine & Autocompleter

### ISSUE THREAD

**Issue by allendema** [searx/searx#2779]
**Working URL to the engine**
https://petalsearch.com/

**Why do you want to add this engine?**

As far as I can tell, this uses its own index.

**Features of this engine**

Fast results.

**How can Searx fetch the information from this engine?**

For the autocompleter I made a small code to print the suggestions.

```bash

#!/usr/bin/python3

import requests
from json import loads

query = "why+is+the"


headers = {
	'User-Agent': 'AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0'
}

# petalsearch.com autocompleter

url = "https://petalsearch.com/sugg_search?locale=de-de&sregion=de&query=" + query + "&category=all"
print(url)

r = requests.get(url, headers = headers)

data = loads(r.text)


for suggestion in data["sug_list"]:
	print(suggestion["name"])
```

**Applicable category of this engine**

General

**Comment by unixfox** [comment]
Thank you for your engine request.

As a reminder if you know about python you are always free to code your own engine code and create a pull request for that!
