### ISSUE TITLE
How to specify engine for searx engine

### ISSUE THREAD

**Issue by dylode** [searx/searx#2781]
Hi,

I host my own instance through Tor, which means I cannot get Google results. I saw you can use another Searx engine to get results, like this:

```
  - name : searx (google)
    engine : searx_engine
    shortcut : sego
    categories : general
    instance_urls :
        - https://searx.prvcy.eu/search
```

And, this works. But how do I make sure searx.prvcy.eu only uses Google?

**Comment by virtadpt** [comment]
What happens if you make the instance URL `https://searx.prvcy.eu/search?q=!go+` ?

**Comment by dylode** [comment]
> What happens if you make the instance URL `https://searx.prvcy.eu/search?q=!go+` ?

It works in my browser but the searx engine uses a POST request: https://github.com/searx/searx/blob/master/searx/engines/searx_engine.py

Not sure if that works then?

**Comment by 0xhtml** [comment]
What about `https://searx.prvcy.eu/search?engines=google` as the instance URL?
