### ISSUE TITLE
Very tiny tweak to documentation

### ISSUE THREAD

**Issue by tomlawesome** [searx/searx#2783]
Hello, 

My request is incredibly simple, for noobs like me, please include on the following page:

https://searx.github.io/searx/admin/installation.html

That you should login / switch to root user. I ran the script with sudo, but installing uWSGI failed, and I had to install specifically with the root user. I'm sure it will help someone else! If you can install without being sudo, then it would be good to explain how. 

Debian 10 VM running on Proxmox.

**Comment by return42** [comment]
[For the installation procedure, use a sudoer login to run the scripts. If you install from root, take into account that the scripts are creating a searx, a filtron and a morty user. In the installation procedure these new created users do need read access to the clone of searx, which is not the case if you clone into a folder below /root.](https://searx.github.io/searx/admin/installation.html)

>  I ran the script with sudo, but installing uWSGI failed,

Must failed for some other reasons.

**Comment by tomlawesome** [comment]
Fair enough — switching to root user fixed it though so it’s not package related or anything.
