### ISSUE TITLE
Integrating !bang-functionality

### ISSUE THREAD

**Issue by TheRadialActive** [searx/searx#28]
I would like to see a very nice feature of duckduckgo in searx: Using !bang (like "!youtube" or "!osm" in the search field) to look for a string on a specific platform, not only on categories.

Maybe later there is a way to write plugins for searx like duckduckgo has "goodies": https://duckduckgo.com/goodies

**Comment by Fironet** [comment]
Oh, the shortcuts are activated prefixing `!`. Couldn't find this mentioned anywhere on the site and had been trying to activate them in various combinations. I rarely use DDG so it didn't occur to me.

**Comment by kvch** [comment]
This functionality is documented: https://asciimoo.github.io/searx/user/search_syntax.html

**Comment by dalf** [comment]
oups, right !

**Comment by Fironet** [comment]
@kvch Thanks for the link. Problem I found is it's not mentioned on the searx.me site. Neither the About page links to it, nor the Preferences. For one of the main features it's not clear where the user would discover how to use it from looking at the site.

Something as simple as prefixing the shortcuts with `!` or putting an (i) circle tooltip beside the Shortcuts column, or perhaps in small grey text below the Preferences would be enough to explain it briefly.

**Comment by dalf** [comment]
The /about page should be updated : it is too technical compare to what a normal user expect.
I think it should embedded some documentation about the syntax and gives some links to https://asciimoo.github.io/searx/
