### ISSUE TITLE
Add proxy for Image search

### ISSUE THREAD

**Issue by ghost** [searx/searx#281]
1. Search Image: "something"
2. Searx return these results;

<img src="http://t2.gstatic.com/images?q=t...

Problem:
1. t2.gstatic.com will know the request comes from searx webpage.
2. If user is blocking t*.gstatic.com, he can't see the image.

Expected result:
Add "/imageproxy".

<img src="/imageproxy?url=bykFVDEWTdvckugFVDBYJEDF6er...

User: "/imageproxy?url=bykFVDEW
Searx: Decrypt url and send a request with random useragent
gstatic.com: Here's your image...
Searx: Convert to JPG format(JPG->JPG, to kill EXIF data)
Searx: Send a result to user's browser...

**Comment by pointhi** [comment]
Already implemented in a basic way: #112

Please look at: Preferences->Image proxy
