### ISSUE TITLE
Set parameters in URL

### ISSUE THREAD

**Issue by ghost** [searx/searx#282]
How can I set parameters in URL instead of Cookie?
https://searx.me/preferences

/?q=urlencode(QUERY)&......

**Comment by Cqoicebordel** [comment]
Change the preferences to GET instead of POST

**Comment by ghost** [comment]
Change the preferences to GET instead of POST
and I click save... no GET params.

I don't want to use cookie, so where can I find a list of params?

**Comment by Cqoicebordel** [comment]
Hum, sorry, I didn't fully understand your question the first time, I thought you were asking about search parameters.

There is no way to have the preferences in the URL instead of a cookie right now. I could be an evolution.
But keep in mind that the cookies used by searx are exactly what is displayed in the preferences panel, nothing more. So, there are no way of tracking an user with those.
Furthermore, the cookies are only used by searx, and no one else. If you trust searx to do your searches, you can trust it to store the cookies ;)

**Comment by ghost** [comment]
Let me explain what I wanna do with searx.
I want to use searx as a "backend" server.

User <---> My WebApp ---> searx:localhost <----> Search Engine servers

How can I send a query with URL without cookie? I have no idea.
Why I can't send a query like this:

http://searx.server/?q=AAAAAAAAAAA!&lang=en&img_proxy=on&return=json

q=AAAAAAAAAAA!
&lang=en
&img_proxy=on
&return=json

**Comment by pointhi** [comment]
It's possible, but it is not a documented feature of searx yet.

You have to pass the cookies as get arguments to searx:

https://www.searx.me/?q=AAAAAAAAAAA!&locale=en&image_proxy=1&pageno=1&category_images

**Comment by fr330n1y** [comment]
@pointhi

"image_proxy=1" is not working. Searx isn't proxying images.
Is this a bug?

&lt;a href="//c3.staticflickr.com/7/6142/5969514803_be9a3b42da_o.jpg" data-toggle="modal" data-target="#modal-4"&gt;
    &lt;img src="https://c3.staticflickr.com/7/6142/5969514803_24976cc0e9_n.jpg" alt="aaaaaaaaaaa 013" title="aaaaaaaaaaa 013" class="img-thumbnail"&gt;
&lt;/a&gt;

Expected:
&lt;img src="searx_image?x=afeiarfgb7er8ygfet7rgya3sgnte6g4e5tbg65egat5gh76tbf43gf6b"&gt;

**Comment by fr330n1y** [comment]
and in JSON: https://www.searx.me/?q=AAAAAAAAAAA!&locale=en&image_proxy=1&pageno=1&category_images=1&format=json

"img_src": "https://drscdn.500px.org/photo/68763637/w%3D280_h%3D280/bad92b5e878b1b8638073bc10b7804ad?v=0",
"thumbnail_src": "https://drscdn.500px.org/photo/68763637/w%3D280_h%3D280/bad92b5e878b1b8638073bc10b7804ad?v=0"

Expected:
"img_src": "http://searx.test.server/searx_image?img=jgfhrega7yl37gbn37abgnaw7rfnawrfgab36fg3ag65",
"thumbnail_src": "http://searx.test.server/searx_image?thumb=afhaw7y75ngy537fgyer7yfawlf74byt7fyr7afb5gal"

**Comment by dalf** [comment]
About image_proxy parameter.
Looking at https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L235
searx reads directly the value of the cookie.

About image_proxy and json format : 
https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L230
is called by the HTML templates, but for the JSON output format : 
https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L391  

May be, image_proxy could be a plugin to filter URL ?
The same could be apply to HTTPS rewrite code.

**Comment by asciimoo** [comment]
@dalf yap, good questions. my plan is to rewrite both as plugins

**Comment by fr330n1y** [comment]
> searx reads directly the value of the cookie

Hello @asciimoo, would you consider reading "preferences" from the URL?
1. Searx read session cookie
2. If not exist, Searx read URI (?language=it_IT&safesearch=0&image_proxy=1&q=AAAAAAA!)

I'm happy with Searx's JSON API.
Searx would become best & free & OPEN SOURCE alternative for "Bing API(*1)", "Google Search API", etc..

*1 | http://searchengineland.com/bing-search-api-no-longer-free-118100

**Comment by Cqoicebordel** [comment]
Agreed, but I'll use the inverse order : Use in URL, if not, use cookies.

**Comment by gggirlgeek** [comment]
So is there some documentation or can you tell us here what the search parameters are please? Are they basically the same as Google's?

From what I've tested "site:" works lite Google. But "time_range=" does not work with, for example, "year" or "10years". The "-" exclude parameter doesn't seem to work but, strangely, it changes the results to contain less of the word specified.

Quotes around a phrase does not work as expected either. I do not get results for the exact phrase.

**Comment by kvch** [comment]
Documentation is available on the topic: 
* https://asciimoo.github.io/searx/dev/search_api.html
* https://asciimoo.github.io/searx/user/search_syntax.html

**Comment by kvch** [comment]
Closing, as it has been inactive. Feel free to reopen if needed.
