### ISSUE TITLE
Engine request: https://search.brave.com

### ISSUE THREAD

**Issue by ghost** [searx/searx#2857]
**Working URL to the engine**
https://search.brave.com

**Why do you want to add this engine?**
His own built-from-scratch index

**Features of this engine**
https://brave.com/search/

**How can Searx fetch the information from this engine?**

**Additional context**

**Comment by ghost** [comment]
https://pleroma.envs.net/objects/537c065e-e545-43b5-aaba-2db77778d337

**Comment by allendema** [comment]
As my configuration and other things from my Raspberry were gone,
I updated Searx on my Laptop and tried to implement this engine.

I added this to ```/etc/searx/settings.yml```

```bash

  - name : brave
    shortcut : brave
    engine : xpath
    paging : True
    search_url : https://search.brave.com/search?q={query}
    url_xpath : //cite[@class="snippet-url"]
    title_xpath : //span[@class="snippet-title"]
    content_xpath : //div[@class="snippet-content"]
    page_size : 15
    categories : general
    timeout : 7.0
    disabled : True
    about:
      website: https://brave.com/search/
      wikidata_id: Q22906900
      use_official_api: false
      require_api_key: false
      results: html
```
It return results, but the URL of destination has the prefix of the engine, 
like _"https://search.brave.com/en.wikipedia.org › wiki › The_Matrix"_ 
instead of "https://en.wikipedia.org/wiki/The_Matrix".

Can anyone correct the url_xpath?

Also there is no pagination.

**Comment by allendema** [comment]
Workaround:

Use the ``` api/images ``` endpoint with ```json_engine``` which returns many more results.
And the URLs are correct too.

Add it to ```/etc/searx/settings.yml```

```bash
  - name : brave images
    shortcut : braveimg
    engine : json_engine
    paging : True
    search_url : https://search.brave.com/api/images?q={query}
    url_query : url
    title_query : title
    content_query : title
    categories : images
    timeout : 7.0
    disabled : True
    about:
      website: https://brave.com/search/
      wikidata_id: Q22906900
      use_official_api: false
      require_api_key: false
      results: json

```

**Comment by ghost** [comment]
Try replacing the url_xpath with 
`url_xpath : //div[@class="snippet fdb"]/a/@href`
This seems to fix the URL problem.

Another issue I see that still needs tweaking is in cases where `<div class="snippet-content">` is followed by a video image, it throws the descriptions off from that point on so the descriptions no longer match the URLs.  For example, when IMDB or YouTube videos are in the web search results.

Also, since Brave Search doesn't have pagination, should paging : True be changed to paging : False, and page_size : 15 be deleted?

**Comment by allendema** [comment]
> Try replacing the url_xpath with
> `url_xpath : //div[@class="snippet fdb"]/a/@href`
> This seems to fix the URL problem.
> 

Update: Now it is working!

> 
> Also, since Brave Search doesn't have pagination, should paging : True be changed to paging : False, and page_size : 15 be deleted?
> 
Correct, paging should be set to False, 
as for "page_size : 15", im not sure if it helps to better mix results with other engines.
That's the reason why it is there.
>

**Comment by ghost** [comment]
hmm.. it's working for me and doesn't include the prefix in the URL link.  Full code I have in settings.yml is:

```
  - name : brave
    shortcut : brave
    engine : xpath
    paging : False
    search_url : https://search.brave.com/search?q={query}
    url_xpath : //div[@class="snippet fdb"]/a/@href
    title_xpath : //span[@class="snippet-title"]
    content_xpath : //div[@class="snippet-content"]
    categories : general
```

**Comment by ghost** [comment]
Great to hear it's working!  

Here is a further fix so it now shows descriptions with their correct URLs when there are videos in the search results, pulling content_xpath from snippet-description instead of snippet-content:
```
  - name : brave
    shortcut : brave
    engine : xpath
    paging : False
    categories : general
    search_url : https://search.brave.com/search?q={query}
    url_xpath : //div[@class="snippet fdb"]/a/@href
    title_xpath : //span[@class="snippet-title"]
    content_xpath : //p[1][@class="snippet-description"]
    about:
      website: https://brave.com/search/
      wikidata_id: Q22906900
      use_official_api: false
      require_api_key: false
      results: HTML
```

There is still a problem when search results contain an item that is 
`<div class="product">` because these use neither class="snippet-description" nor class="snippet-content".  For example try in searx, `!brave beatles revolver vinyl `and compare to the same search on search.brave.com.  From the first hit that is div class="product" (the first Walmart link), descriptions are off from that point on.

Does anyone have a fix for this?

**Comment by Hime0698** [comment]
Is there any update on this? 
I would love to see this engine added.

**Comment by ghost** [comment]
I don't know, but Brave search engine is available on [searx.zecircle.xyz ](https://searx.zecircle.xyz) since the first day, I don't know if it will be officially available on the next update of SearX, I guess so...

**Comment by allendema** [comment]
Suggestions should be added too.

``` suggestion_xpath : //div[@class="text-gray h6"]/a ```
 
You can try it with:

``` brave recurzuoin ```

**Comment by kvch** [comment]
I have picked the changes from the referencer PRs. Thanks!
