### ISSUE TITLE
Hide empty search engine categories

### ISSUE THREAD

**Issue by privacytoolsIO** [searx/searx#286]
We've removed all search engines of the category "files" today, but the category didn't disappear. Example: https://www.privatesearch.io/preferences#tab_engine

How can I remove the empty category? 
Can you include a check if search engines exist in a category before showing an empty category?

Thanks guys.

**Comment by asciimoo** [comment]
I can't see any empty categories and `files` isn't in the category list.

**Comment by privacytoolsIO** [comment]
It took some time before it disappeared. Caching?
