### ISSUE TITLE
issues with installation script searx.sh

### ISSUE THREAD

**Issue by miltosc** [searx/searx#2864]
### Discussed in https://github.com/searx/searx/discussions/2863

<div type='discussions-op-text'>

<sup>Originally posted by **miltosc** June 25, 2021</sup>
Hello,

1)
I followed your installation guide with scripts https://searx.github.io/searx/admin/installation.html#installation-scripts

I did the following

```
cd ~/Downloads
git clone https://github.com/searx/searx searx
cd searx
```

Then i change .config.sh with the ports i want, but after issuing
`sudo -H ./utils/searx.sh install all`

at the following step it clones again your repository at `cd "/usr/local/searx/searx-src"`

```
Clone searx sources
-------------------

INFO:  clone into: /usr/local/searx/searx-src
mkdir -p "/usr/local/searx"
cd "/usr/local/searx"
git clone --branch "master" --origin "origin" "/home/myuser/Downloads/searx" "searx-src"
  |searx| Cloning into 'searx-src'...
  |searx| done.
cd "/usr/local/searx/searx-src"
git remote set-url origin https://github.com/searx/searx
git config user.email "root@MCP"
git config user.name "root"
git config --list
  |searx| core.repositoryformatversion=0
  |searx| core.filemode=true
  |searx| core.bare=false
  |searx| core.logallrefupdates=true
  |searx| remote.origin.url=https://github.com/searx/searx
  |searx| remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
  |searx| branch.master.remote=origin
  |searx| branch.master.merge=refs/heads/master
  |searx| user.email=root@MCP
  |searx| user.name=root
** press any [KEY] to continue **
```

and from now on it uses /usr/local/searx/searx-src/.config.sh because of `cd "/usr/local/searx/searx-src"` at the previous log as you see.
so it never uses the ports that i changed at my ~/Downloads/searx/config.sh but the defaults instead

at the readme https://searx.github.io/searx/utils/searx.sh.html#searx-sh you say:

"
If needed, set PUBLIC_URL of your WEB service in the '.config.sh' file::
  PUBLIC_URL          : http://fv-az246-49/searx
  SEARX_INSTANCE_NAME : searx@fv-az246-49 
  SERVICE_USER        : searx
  SEARX_INTERNAL_HTTP : http://127.0.0.1:8888
"

thats why i did it that way

to solve it i executed install once to clone at /usr/local/searx
exited the installation, then 
`sudo cp /home/myuser/Downloads/searx/.config.sh /usr/local/searx/searx-src/.config.sh`
and executed install again to just pull and leave my .config.sh at /usr/local/searx/searx-src/.config.sh that i previously copied

That's ugly. Just saying... 
if you have any idea to solve this, it would be nice!

2)
In file  searx.sh
I couldnt find where to set SEARX_INTERNAL_HTTP in a conf file or somewhere else probably you mean SEARX_INTERNAL_URL from .config.sh instead of SEARX_INTERNAL_HTTP
so i corrected your line

SEARX_INTERNAL_HTTP="${SEARX_INTERNAL_HTTP:-127.0.0.1:8888}"
with
SEARX_INTERNAL_HTTP="${SEARX_INTERNAL_URL:-127.0.0.1:8888}"

and everything gone ok then

3) 

at sudo -H ./utils/filtron.sh install all when setting up nginx confs it links conf file (same for morty) in /etc/nginx/default.d/
but at least in debian buster nginx default includes places are 
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;

A) 

for adding the search engine in firefox search engines list if you set up custom ports the following lines are needed "proxy_set_header   Host             $host:<public_custom_port_searx_exposed>;" to fill correctly custom ports because of using flask "url_for"

in nginx conf file 
```
server {
        listen <public_custom_port_searx_exposed> ssl http2;
...
        location /searx {
                proxy_pass         http://127.0.0.1:<FILTRON_LISTEN_port>/;
                proxy_set_header   Host             $host:<public_custom_port_searx_exposed>;
...
         }
}
```

B) the produced conf files for morty and filtron do not respect the custom ports configured in .config.sh

Thats all, hope i helped you to make the installation script better...</div>

**Comment by unixfox** [comment]
Hello, unless you found a real bug which you can explicitely write some steps in a github issue about how to replicate it I'm going to close this issue.
