### ISSUE TITLE
Hide search engines without removing them

### ISSUE THREAD

**Issue by privacytoolsIO** [searx/searx#287]
I found this in the templates and I'm wondering how to use it:

{% for search_engine in search_engines %}
{% if not search_engine.private %}

I'd like to hide a couple of search engines from the preferences menu without removing the search engine itself. 

Can you help me out please?

**Comment by privacytoolsIO** [comment]
Is this how it works?

settings.yml
    name : soundcloud
    engine : soundcloud
    shortcut : sc
    private : True

-> reload server

**Comment by asciimoo** [comment]
If it isn't represented in any category it won't be listed on the preferences page. Can be accomplished by setting `categories: ""` to the engines in settings.yml
