### ISSUE TITLE
Duckduckgo autocomplete broken

### ISSUE THREAD

**Issue by privacytoolsIO** [searx/searx#288]
https://searx.me/preferences
change autocomplete to duckduckgo -> no suggestions. but all the others work just fine.

**Comment by asciimoo** [comment]
It works for me, tested with the string "south".

**Comment by fr330n1y** [comment]
For autocomplete, how about adding SP?

https://startpage.com/do/suggest?query=aaaa

**Comment by privacytoolsIO** [comment]
It works again, maybe it was just a temp. problem. Thanks
