### ISSUE TITLE
Add public searx server, and select randomly using DNS (idea)

### ISSUE THREAD

**Issue by fr330n1y** [searx/searx#290]
For the people who doesn't have VPS account
or don't know how to deploy searx
or just lazy to install
or doesn't......

---

"How can we trust https://searx.me/ ?
Who runs it? Where is the server location? Does the server logging all queries(URL,StatusCode)?"
...sorry, I don't mean to attack searx.me owner :)

Search from random location is important to enhance privacy.
So, we the people need:
1. Many volunteer servers which setup searx all over the world,
2. With same FQDN (VirtualHost dual stack)
3. And 1 domain(example: random.searx.me) and good DNS server/service.

Let's start with 1 and 2.
Requirements:
- Web server with latest searx package.
- You can set your own domain name(e.g., nice.your.search.engine.server), but must add "random.searx.me" as alias(VirtualHost, CertificateAlternateName).

About 3:
There's plenty of free DNS services.
"random.searx.me"'s owner set A record to volunteer servers:
random.searx.me A 1.1.1.1
random.searx.me A 10.1.1.1
random.searx.me A 1.176.1.1
random.searx.me A 199.1.1.1
random.searx.me A 1.1.17.1
random.searx.me A 1.31.1.1
random.searx.me A 1.1.155.1

---

https://random.searx.me/
^ this will pick one A record from DNS and connect to it.

**Comment by fr330n1y** [comment]
## Related: http://stats.searx.oe5tpo.com/

...or, set up "redirection server" to rediret request to random-picked server.

User: https://random.searx.me/?format=rss&locale=it_IT&q=AAAAAAAAAA
random.searx.me: Pick one from stats.searx.oe5tpo.com...
random.searx.me: I pick https://searx.volcanis.me
random.searx.me: Hey user, go there!
random.searx.me: "Location: https://searx.volcanis.me/?format=rss&locale=it_IT&q=AAAAAAAAAA"
User: HTTP 302 Redirect https://searx.volcanis.me/?format=rss&locale=it_IT&q=AAAAAAAAAA
searx.volcanis.me: Welcome! Here's your result!

**Comment by dalf** [comment]
Related to #39 

It's not easy to solve : 
- search engines use the ip (of the searx instance) to "adjust" the result
- not all searx instances are updated
- some times, searx are customized. 

But what you suggest can be done (either DNS entries, or redirection).

Another ( funky / strange ) solution : implement a searx engine for searx (as there is google engine, yahoo engine etc...). The searx engine chooses a random instance, and send the request. The searx instance list could be downloaded. It (can) makes sense if the searx instances is installed on the user computer.

**Comment by fr330n1y** [comment]
> search engines use the ip (of the searx instance) to "adjust" the result

Yeah, that's one of the reason why I hate google...
http://dontbubble.us/
https://searx.me/?q=guns (<--- where is NRA?)

> not all searx instances are updated

Then these old sites must be removed from redirection target.
Maybe adding "searx-auto-update" and run it using cron-daily is a good start.

searx-auto-update
1. Download raw ZIP(or released ZIP) from https://github.com/asciimoo/searx/
2. If size(downloaded) != size(currently_installed) && unzip(downloaded)===true, unpack it and overwrite current folder.

> some times, searx are customized

I just want to receive JSON result from random servers.
?format=json&engines=common&...&q=AAAAAA
^ "common" engine which volunteer searx owner can't|souldn't edit.

**Comment by asciimoo** [comment]
First of all, do not trust something you red on the internet =)
Second, do not trust searx.me

Searx me is maintained by me with my best effort to protect users privacy. It also uses multiple IPs to spread outgoing requests.

DNS rotation: SSL certs are another question

let's continue the discussion on #39
