### ISSUE TITLE
filtron -> no ipv6 -> alternatives?

### ISSUE THREAD

**Issue by frasersdev** [searx/searx#2906]
Firstly thanks for a great project.

**Is your feature request related to a problem? Please describe.**
This relates to the entire application stack, not just the searx project. Not sure where to place such an item.  

Filtron doesn't support ipv6. 
https://github.com/asciimoo/filtron/issues/19

My hosting setup uses nginx revproxy (+ optionally varnish) as a frontend and application / webservers as a back end.
ipv4 terminate on the rev proxy
the backend is pure ipv6 
there's firewalls etc between everything along the way.

based on your architecture https://searx.github.io/searx/admin/architecture.html I was expecting searx to fit in well.
however the lack of ipv6 support of filtron meant that the nginx frontend couldn't communicate with the backend.

**Describe the solution you'd like**
filtron should support ipv6 as its an internet technology.

**Describe alternatives you've considered**
I think I can do a lot of what filtron is doing directly in nginx. it supports rate limiting and responses based on user agent.  
This makes me wonder if filtron can be dropped entirely from your application stack. 
Thats the path I'm going to take anyway since filtron is a no go for me. 
varnish will be useful for the static content too. 

**Additional context**
not sure what you'd need but happy to provide more info. All the other components can operate with ipv4 or ipv6. I have nginx connecting directly to searx on an ipv6:8888 and its working well.

**Comment by unixfox** [comment]
Closing as one issue on the filtron github repo is enough.
Even if filtron was designed to protect searx, searx the program itself doesn't need filtron to function properly so this enhancement has nothing to do on this github repo.
