### ISSUE TITLE
Make stats restart-proof

### ISSUE THREAD

**Issue by ldidry** [searx/searx#292]
When you restart uwsgi (update, reboot, restart because of new version of a library it uses…), the stats are lost. I think i could be a good thing if searx stored the stats in som way that is restart-proof.

If a continous store of stats is too ressource-greedy, maybe a dump in a flat file every X hours (configurable delay) would do the job.

What do you think of that?

**Comment by Cqoicebordel** [comment]
We are exploring the possibility of using a small database. If and when it's done, it will be possible to store the stats data into it, and be restart proof.

But nothing for right now, sorry...

**Comment by asciimoo** [comment]
see #162

**Comment by ldidry** [comment]
Thx!

**Comment by dalf** [comment]
Some news :
I have an improved version, which display stats by categories (which help to see which engine is slow in one category).

But it's still buggy, and it doesn't handle plugins. 

Sadly, for now I don't have time to work on it...
