### ISSUE TITLE
Porting

### ISSUE THREAD

**Issue by anton-dutov** [searx/searx#293]
Hello, what about porting/python3 compatibility?

I think we need add all version depended imports to some module like searx.utils for example:

``` python
import sys

if sys.version_info[0] == 3:
    from io import StringIO
    from urllib.parse import urlencode, quote, unquote, quote_plus, urlparse, urljoin
    from html.parser import HTMLParser
else:
    from urllib import urlencode, quote, unquote, quote_plus
    from urlparse import urlparse, urljoin
    import cStringIO
    from HTMLParser import HTMLParser
```

And replace import in all engine files:

``` python
# From
from urllib import urlencode
# To
from searx.utils import urlencode
# qoute, unquote, quote_plus, etc.
```

What do you think about?

**Comment by Cqoicebordel** [comment]
That's a way of doing it, but I fear it's not a clean way : we could import the right packages directly into the source without doing version detection, by using the `future` namespace. It allows importing future package from their namespaces, without losing compatibility with Python 2.

**Comment by anton-dutov** [comment]
You're right it's way is more clean.

**Comment by dalf** [comment]
done : https://asciimoo.github.io/searx/blog/python3.html
