### ISSUE TITLE
Add &filter=0 by default to Google Search (include omitted results)

### ISSUE THREAD

**Issue by WAZAAAAA0** [searx/searx#2944]
This is about google.com showing this clickable message at the bottom of certain searches:
> In order to show you the most relevant results, we have omitted some entries very similar to the X already displayed.
> If you like, you can repeat the search with the omitted results included.

SearX should just append `&filter=0` by default to all Google searches to display those hidden results for better searches. Example:
2 results - Google normal - [LINK](https://www.google.ca/search?q=%22%D8%A7%D9%82%D8%B5%D8%AF%20%D9%8A%D8%B9%D9%86%D9%8A%20%D8%A7%D8%B0%D8%A7%20%D8%A7%D9%86%D8%AA%20%D8%B9%D8%A7%D9%88%D8%B2%20%D8%AA%D8%B3%D9%88%D9%82%20%D9%85%D8%B4%D8%B1%D9%88%D8%B9%D9%83%20%D9%84%D8%A7%D8%B2%D9%85%20%D8%A7%D9%86%20%D8%AA%D8%B2%D9%8A%D9%84%20%D9%87%D8%B0%D9%87%20%D8%A7%D9%84%D9%83%D9%84%D9%85%D8%A7%D8%AA%20%D9%84%D9%83%D9%8A%20%D9%8A%D9%83%D9%88%D9%86%20%D8%A7%D9%84%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D8%AC%20%D8%A7%D8%AD%D8%AA%D8%B1%D8%A7%D9%81%D9%8A%22)
17 results - Google &filter=0 - [LINK](https://www.google.ca/search?q=%22%D8%A7%D9%82%D8%B5%D8%AF%20%D9%8A%D8%B9%D9%86%D9%8A%20%D8%A7%D8%B0%D8%A7%20%D8%A7%D9%86%D8%AA%20%D8%B9%D8%A7%D9%88%D8%B2%20%D8%AA%D8%B3%D9%88%D9%82%20%D9%85%D8%B4%D8%B1%D9%88%D8%B9%D9%83%20%D9%84%D8%A7%D8%B2%D9%85%20%D8%A7%D9%86%20%D8%AA%D8%B2%D9%8A%D9%84%20%D9%87%D8%B0%D9%87%20%D8%A7%D9%84%D9%83%D9%84%D9%85%D8%A7%D8%AA%20%D9%84%D9%83%D9%8A%20%D9%8A%D9%83%D9%88%D9%86%20%D8%A7%D9%84%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D8%AC%20%D8%A7%D8%AD%D8%AA%D8%B1%D8%A7%D9%81%D9%8A%22&filter=0)
3 results - SearX 1.0.0-200-313a9847 - [LINK](https://searx.prvcy.eu/search?q=%21go%20%22%D8%A7%D9%82%D8%B5%D8%AF%20%D9%8A%D8%B9%D9%86%D9%8A%20%D8%A7%D8%B0%D8%A7%20%D8%A7%D9%86%D8%AA%20%D8%B9%D8%A7%D9%88%D8%B2%20%D8%AA%D8%B3%D9%88%D9%82%20%D9%85%D8%B4%D8%B1%D9%88%D8%B9%D9%83%20%D9%84%D8%A7%D8%B2%D9%85%20%D8%A7%D9%86%20%D8%AA%D8%B2%D9%8A%D9%84%20%D9%87%D8%B0%D9%87%20%D8%A7%D9%84%D9%83%D9%84%D9%85%D8%A7%D8%AA%20%D9%84%D9%83%D9%8A%20%D9%8A%D9%83%D9%88%D9%86%20%D8%A7%D9%84%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D8%AC%20%D8%A7%D8%AD%D8%AA%D8%B1%D8%A7%D9%81%D9%8A%22&categories=none&language=def)

Additionally, this would also fix the bug in the `Suggestions` panel mentioned here: https://github.com/searx/searx/issues/2705 *(After clicking on "reload the search to include omitted results" launch a search of the said phrase)*

**Comment by unixfox** [comment]
Feel free to submit a PR, the source code of the google engine is here: https://github.com/searx/searx/blob/master/searx/engines/google.py
