### ISSUE TITLE
No query analyse in seek

### ISSUE THREAD

**Issue by Battant** [searx/searx#295]
Hello,

If I search any think on searx.me or framabee.org, the search is annalyse word by word and not the global query by default

Sould I put some quote ?

Thanks for your answers

Best regards

Battant

**Comment by Cqoicebordel** [comment]
It depends on the engines you choose. But yes, most of the search engines use word by word search and if you need to search a phrase, you have to put quotes.

**Comment by unixfox** [comment]
Hugely depend on the engine behavior and can't really be controlled by Searx.
