### ISSUE TITLE
Use user agent from browser

### ISSUE THREAD

**Issue by kdxcxs** [searx/searx#2956]
**Is your feature request related to a problem? Please describe.**

I just cannot receive any response from bing.com.

**Describe the solution you'd like**

As I changed the header with my browser's user agent, bing.com now works just fine.
Could searx just use the same ua as browser?

**Describe alternatives you've considered**

**Additional context**

**Comment by unixfox** [comment]
Searx is already using a browser user agent. Can you send me the user agent that you used?

Maybe we are using an user agent from an older firefox version.

**Comment by kdxcxs** [comment]
I'm currently using `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84`.

If it's possible for Searx to use the user agent from browser request header? Or may be make it a configurable option in settings page?

**Comment by unixfox** [comment]
> I'm currently using `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84`.

Bing is probably rate limiting less Chromium browsers, but unfortunately we only use Firefox user agents, we may consider using Chromium user agents though.

> If it's possible for Searx to use the user agent from browser request header? Or may be make it a configurable option in settings page?

Currently it's not possible.
