### ISSUE TITLE
Add bang! functionality like duckduckgo has

### ISSUE THREAD

**Issue by pschwede** [searx/searx#296]
!wa for wolframalpha
!g for google
!i for google images

etc.

**Comment by dalf** [comment]
There is already some searx bangs as describe here https://github.com/asciimoo/searx/wiki/Query-language

About the redirections as you describe, duckduckgo exposes its API.
[example](https://api.duckduckgo.com/?q=!wa sin%28x%29&format=json&pretty=1&no_redirect=1&d=1)
(replace the 0 by 1 with no_redirect parameter to have a redirection)

This API is used by the duckduckgo_definitions engine. 

If this is implemented, I don't know : 
- how to not conflict with existing searx bangs
- how searx should behave : direct redirection, display a link to the web site (like an answer)

**Comment by pschwede** [comment]
I just was looking for something similar. So now I know it exists, thank you.
