### ISSUE TITLE
images/videos/etc. tab buttons don't work

### ISSUE THREAD

**Issue by ghost** [searx/searx#2966]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

commit `1ea573dc88ab37d05e47110d6080fda5b656cb81`
**How did you install Searx?**

i think by the wiki, using master branch
**What happened?**

when trying to switch tabs (i.e.  to images), nothing happens when clicking on them. Actually, they sort of act like checkboxes?

**How To Reproduce**

1. Go to a search
2. hit "images", "videos", or any of the other tabs

**Expected behavior**

It should switch to those tabs

**Screenshots & Logs**

https://user-images.githubusercontent.com/65276418/132153753-d8308135-c2b6-411b-aff0-90c56b67fa92.mp4

**Additional context**

not a browser issue, happened on librewolf as well

**Comment by kvch** [comment]
I cannot reproduce your issue. Also, the video you have attached seems corrupt. Could you please reload a video or give me more details about how to reproduce the problem?
