### ISSUE TITLE
duckduckgo bang-like behaviour

### ISSUE THREAD

**Issue by mpldr** [searx/searx#2979]
**Is your feature request related to a problem? Please describe.**

I am a big fan of being able to "direct" my searches directly to the page where I know I can find it. Duckduckgo solved this with bangs, where for example `!aw docker` would search for "docker" in the ArchWiki directly.

**Describe the solution you'd like**

It would be great if you could add config entries with a certain prefix that redirect your search (or redirect to a page with the url-encoded search-query inserted.

Basically something like a custom answerer that redirects to the destination. This reduces the number of interactions, thereby speeding up searches for users.

**Describe alternatives you've considered**

maybe something similar might be possible with defining custom engines, but I've not yet found a way to make them redirect on an exact match

**Additional context**

https://duckduckgo.com/bang (having 13k of these would probably be excessive as a default, so it would probably be preferable to just have an commented out example in the config)

**Comment by 0xhtml** [comment]
`!!aw docker` and similar bangs are already possible. Only difference to DDG is that you have to prefix the bang with `!!` instead of `!`.
