### ISSUE TITLE
No DuckDuckGo paging

### ISSUE THREAD

**Issue by Baarten** [searx/searx#2982]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
0.18.0 and 1.0.0/1.0.0-1.0.0

**How did you install Searx?**
Via FreedomBox web-GUI.

**What happened?**
When I configure DuckDuckGo as the only engine, there's only one page of results opposed to multiple pages on DuckDuckGo for the same search query. I have this on my own 0.18.0 instance and I tested 2 public vanilla 0.18.0 instances and 8 public vanilla 1.0.0/1.0.0-1.0.0 instances with the same result.

**How To Reproduce**
1. Use a 0.18.0 or 1.0.0/1.0.0-1.0.0 instance of Searx.
2. Go to _Preferences_ > _Engines_.
3. Click _Disable all_.
4. Toggle _duckduckgo_ to on.
5. Click _save_.
6. Search for something that gives multiple pages of results on https://duckduckgo.com (eg. _test_).

**Expected behavior**
A _next page_ button at the bottom of the first page of search results to go to the next page.

**Screenshots & Logs**
![Screenshot_2021-09-24 test - FreedomBox Web Search](https://user-images.githubusercontent.com/1261041/134629240-667436e7-2ccc-4500-89df-d6399d9d157a.png)

**Additional context**
I'm using the 0.18.0 version of Searx as it comes with FreedomBox. FreedomBox uses Debian's repositories and version 1.0.0 isn't in it yet. I'm fine with it as long it's safe, unless 1.0.0 will solve this issue, but it doesn't appear to do so.

**Previous (similar/related) closed issues**
#1677 and #847

**Comment by kvch** [comment]
The paging support has been removed on purpose because one of the params required requires searx to forward a unique value for each request: https://github.com/searx/searx/pull/2254

**Comment by Baarten** [comment]
And that's bad, because then DuckDuckGo can link the different page requests to the same client?

**Comment by unixfox** [comment]
It's possible to have the paging through https://lite.duckduckgo.com without any tracking identifier (unique value) though.

Technical details :
- Headers:
	- Content-Type: application/x-www-form-urlencoded
- Form data:
	- q: _the query keyword_
	- o: `json`
	- dc: _the number of the first result, for example 1 is the first result_
	- api: `d.js`
- HTTP method: POST
- URL: https://lite.duckduckgo.com/lite/
- Additional notes: If `o` and `api` are not provided, then duckduckgo only return 5 results.

I'm reopening the issue.

**Comment by kvch** [comment]
I have picked the changes in c218fb76b86a8cf4a42a56c07e94bbc75ff5bdee, now paging should work.
