### ISSUE TITLE
Support OpenSearch description format (so you can add the search engine to firefox, etc easily?)

### ISSUE THREAD

**Issue by romulasry** [searx/searx#3027]
**Is your feature request related to a problem? Please describe.**
searx doesn't support OpenSearch

**Describe the solution you'd like**
Support OpenSearch

**Describe alternatives you've considered**
None.

**Additional context**
OpenSearch description format
https://developer.mozilla.org/en-US/docs/Web/OpenSearch

The OpenSearch description format lets a website describe a search engine for itself, so that a browser or other client application can use that search engine. OpenSearch is supported by (at least) Firefox, Edge, Internet Explorer, Safari, and Chrome. (See Reference Material for links to other browsers' documentation.)

**Comment by unixfox** [comment]
It already does: https://github.com/searx/searx/blob/7089526723394e7492762b7e5cdd112e1da28990/searx/templates/__common__/opensearch.xml
