### ISSUE TITLE
[xpath engine] return the search url when no result is found

### ISSUE THREAD

**Issue by qaristote** [searx/searx#3039]
Many websites skip the result page when the user searches for something that has an exact match. For example, when searching for Searx on [AlternativeTo](https://alternativeto.net/), the result page https://alternativeto.net/browse/search?q=searx directly redirects the user to https://alternativeto.net/software/searx/. 

This is a problem when trying to add the website as a search engine using xpath because the page to which the result page redirects to may not be parsed the same way as the result page itself, leading to a false-negative "no results found" error.

For example, when adding AlternativeTo to Searx using the configuration
```
- name : alternativeto
  engine : xpath
  paging : True
  search_url : https://alternativeto.net/browse/search?q={query}&p={pageno}
  results_xpath : //article[@class="row app-list-item"]/div[@class="col-xs-10 col-sm-10 col-md-11 col-lg-offset-1 col-lg-11"]
  url_xpath : ./h3/a/@href
  title_xpath : ./h3/a
  content_xpath : ./div[@class="itemDesc read-more-box"]/p[@class="text"]
```
the `alternativeto` engine will return results when searching for "sear" but will not return any result when searching for "searx".

My current solution is to add an invisible whitespace at the end of the queries, for example using 
```
search_url : https://alternativeto.net/browse/search?q={query}%E2%80%8E&p={pageno}
```
for AlternativeTo, but this is not ideal as it doesn't return the exact same results as without the invisible whitespace and requires that the `%E2%80%8E` string be copied in each xpath engine entry.

What I think would be a great solution would be that the xpath engine return the search url given in `search_url` whenever no result is found when parsing the page. The title and content of the result may then simply be the title and description of the webpage found in the HTTP header.
Of course this may only be added as an option that is disabled by default.

What do you think ?

**Comment by allendema** [comment]
Works well - you can just add ```/?ignoreExactMatch=true``` to search_url variable like below.
This way it will ignore popular matches.


```diff
  - name : alternativeto
    shortcut : ato
    engine : xpath
    timeout : 4.0
    paging : True
    search_url : https://alternativeto.net/browse/search/?ignoreExactMatch=true&q={query}&p={pageno}
    results_xpath : //article[@class="row app-list-item"]/div[@class="col-xs-10 col-sm-10 col-md-11 col-lg-offset-1 col-lg-11"]
    url_xpath : ./h3/a/@href
    title_xpath : ./h3/a
    content_xpath : ./div[@class="itemDesc read-more-box"]/p[@class="text"]
    disabled : True
```
Notice that ```shortcut```, ```timeout``` and ```disabled``` are addded but you can change them to your liking.
