### ISSUE TITLE
Broken pipe in latest git

### ISSUE THREAD

**Issue by g4jc** [searx/searx#304]
Hello,
## I have compiled searx minimal per the instructions. It runs, but am unable to perform searches. Everytime I click search it times out in the browser and shows this in the logs...

Exception happened during processing of request from ('127.0.0.1', 44855)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by dalf** [comment]
Dependencies has been updated yesterday. Could you try again ? (`git clone`, `make minimal`). And if it still doesn't work, could try (`make clean`, `make`). Really not sure if it helps.

**Comment by g4jc** [comment]
# Just tried per instructions, including make clean and make... still getting this. :(

---

Exception happened during processing of request from ('127.0.0.1', 57830)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])

## error: [Errno 32] Broken pipe

---

Exception happened during processing of request from ('127.0.0.1', 58543)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])

## error: [Errno 32] Broken pipe

**Comment by dalf** [comment]
Broken pipe : it's like the TCP connection was closed. Do you have a firewall ? 
What does `iptables -L` say  ?

**Comment by dalf** [comment]
@g4jc  : did you gave up ? found a solution ?

**Comment by g4jc** [comment]
I have been unable to find a solution to this so far. I have no IPTable rules setup. 

Here is my IPTables:

root@host:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 

And here is the bug from latest git (compiled using 'make minimal' less than an hour ago):

Exception happened during processing of request from ('127.0.0.1', 60115)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

**Comment by dalf** [comment]
Ok ! I think I get it.
Everything is working, except those errors ? 
Try to disable the autocomplete feature, and see if the logs stay clean.

Explanation : when you type of the search input field, the autocomplete makes request. Read: javascript is making AJAX request.
When you click on the search button, the page is unloaded and the pending AJAX request is cancelled. From the searx point of view the TCP connection was broken.

There is nothing wrong with this those errors, except that the logs are not very clear about what is happening.

**Comment by Cqoicebordel** [comment]
If it's that, the logs should be fixed ;)

**Comment by g4jc** [comment]
@dalf, I will try your suggestion as soon as I get a chance and follow with an update once I disable autocomplete.

The original problem I am experiencing however, is that any search query I make results in "Connection timeout" in Firefox. I have also tried other browsers and had someone else attempt to search from my node which also failed.

During each failed attempt to search - the broken pipe error appears in logs, hence I think it is related.

**Comment by dalf** [comment]
How did you configure searx ? I mean do you use Apache ou Ngnix ?

Can you try this :
- stop apache / ngnix / uwsgi etc...
- edit `searx/settings.yml` : set debug to True
- run `bin/searx-run`
- send a request to localhost:8888 even using curl or wget.

**Comment by g4jc** [comment]
I finally was able to determine this problem. I was actually running the service directly, and I realized that it worked on localhost, but not remotely after your curl suggestion. I seem to have discovered the reason. 
When your internet connection is very slow, unreliable, or proxied (e.g. any clients using privoxy + TOR), it results in a broken pipe.

Running nginx as reverse proxy and allowing a longer timeout actually seems to have partially-resolved this issue for me and normal use.

Further testing revealed that I can reproduce this bug on your main (searx.me) TOR instance nearly everytime however, (due to the added latency):
1) Install Privoxy --> uncomment " forward-socks5   /               127.0.0.1:9050 ." in /etc/privoxy/config --> Start service
2) Set your browser to use HTTP proxy 127.0.0.1:8118
3) Make sure TOR is running
4) Navigate to any "Hidden Service" Searx instance. (https://github.com/asciimoo/searx/wiki/Searx-instances)
5) Try running a search
6) Client will show timeout error
7) Server will get bad pipe error.

I am unsure if this is a bug in privoxy, or searx, or both. Please feel free to see if you can also reproduce with this setup. I will reach out to privoxy as well.

Thanks for your trouble shooting assistance!

**Comment by dalf** [comment]
From a fresh Debian Jessie installation, I installed privoxy and tor on the same machine as you described. But, I don't have any timeout (ifconfig.me shows that tor is correctly configured). The response time on searx.me is bellow 13 seconds (sometimes, 2 sec, 4 sec, 12 etc...)

How long does it take to have a time out ? 60 seconds ? The number could help to find the layer that is involved.

In Debian Jessie, the privoxy configuration doesn't set a timeout.  As I understand the [documentation](http://www.privoxy.org/user-manual/config.html#DEFAULT-SERVER-TIMEOUT), there is no timeout. Does it help if remove privoxy ?

About [Nginx, there is a default 60 seconds timeout](http://wiki.nginx.org/HttpUwsgiModule#uwsgi_read_timeout)

I can't find anything about Flask (the Python framework used by Searx)

**Comment by g4jc** [comment]
I can confirm removing privoxy was the issue, and after a lot of debugging upstream (privoxy bug #1686) this has fixed it. :+1: 

Apologies for confusing you all with this bug report, and thanks for pointing me in the right direction. :)
