### ISSUE TITLE
Set number of results per page

### ISSUE THREAD

**Issue by DUOLabs333** [searx/searx#3045]
**Is your feature request related to a problem? Please describe.**
This may exist somewhere in the yaml, but I couldn't find it -- is there a way to set the number of results per page? Or make it "endless"?

**Describe the solution you'd like**
A preference, either in "preferences" or in the settings.yaml to set the number of results per page

**Describe alternatives you've considered**

**Additional context**

**Comment by unixfox** [comment]
You can activate the plugin "Infinite scroll" in the preferences.
