### ISSUE TITLE
Britannica

### ISSUE THREAD

**Issue by DUOLabs333** [searx/searx#3046]
**Working URL to the engine**
`https://www.britannica.com/search?query={query}`

**Why do you want to add this engine?**
It's an authoritative source of information

**Features of this engine**

**How can Searx fetch the information from this engine?**
It might be possible to use xpath for this.

**Applicable category of this engine**
general

**Additional context**

**Comment by MarcAbonce** [comment]
Related to #2331. I don't know why that one was closed.
