### ISSUE TITLE
Google images not working

### ISSUE THREAD

**Issue by antonino-arcudi** [searx/searx#3054]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

**How did you install Searx?**

I installed following the official wiki and execute it as webapp.py file
**What happened?**

An error message in the UI when selectin the "image" tab saying "unexpected crash" for google images:

![image](https://user-images.githubusercontent.com/38839719/140664872-73725420-7a8f-4444-994b-82a136080aa1.png)

**How To Reproduce**

Search for anything and then switch to image tab
**Expected behavior**

Google images returns results
**Screenshots & Logs**

ERROR:searx.search.processor.online:engine google images : exception : 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 139, in search
    search_results = self._search_basic(query, params)
  File "/usr/local/searx/searx-src/searx/search/processors/online.py", line 109, in _search_basic
    self.engine.request(query, params)
  File "/usr/local/searx/searx-src/searx/engines/google_images.py", line 103, in request
    params, supported_languages, language_aliases, False
  File "/usr/local/searx/searx-src/searx/engines/google.py", line 185, in get_lang_info
    ret_val['params']['lr'] = "lang_" + lang_list.get(lang_country, language)
**Additional context**

**Comment by unixfox** [comment]
I can replicate this issue on SearX. If you want a working google images on SearX you may use this popular fork which has Google images engine fixed: https://github.com/searxng/searxng/
