### ISSUE TITLE
Startpage autocomplete is broken

### ISSUE THREAD

**Issue by renyhp** [searx/searx#3060]
**Version of Searx** v1.0.0 ae122ea943f77600fd97556503c483dcd92e1e6

**How did you install Searx?** Manually step by step

**What happened?**

Autocomplete from startpage gives some HTML code as results

**How To Reproduce**

Set startpage as autocomplete engine, then type a search for anything

**Expected behavior**

Some actual searches should be suggested

**Screenshots & Logs**

![immagine](https://user-images.githubusercontent.com/20142663/141593924-ab7e7bd7-6500-47b8-8165-440a944602fe.png)

**Comment by ghost** [comment]
I can correctly reproduce this bug on Arch Linux.

**Comment by kvch** [comment]
I cannot reproduce it on master. Could you please retry it with the latest commit?

**Comment by ghost** [comment]
I can still reproduce the bug even on freshly intalled master.

**Comment by kvch** [comment]
A possible fix was picked in ad7e00ad033490679d56175add531653b713f06a

Let me know if the issue persists.
