### ISSUE TITLE
Customizing searx to return search results from a certain set of websites?

### ISSUE THREAD

**Issue by prp-e** [searx/searx#3075]
Hey guys. 
Imagine I have `example.com` and `example1.com` and `example2.com`. These website include some sort of data that I want to search in. 
So, How can I have a customized searx which only searches in them? 

P.S : I don't want something like `event site:example.com`. I want my users to be able to search inside certain websites with ease.

**Comment by unixfox** [comment]
Duplicate of https://github.com/searx/searx/issues/2952
