### ISSUE TITLE
Startpage seems to be partially broken

### ISSUE THREAD

**Issue by patrickpichler** [searx/searx#3084]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
`1.0 - f2f72575023b9a08081f6c87bf309f1f12fa9978`
**How did you install Searx?**
Official wiki with uwsgi
**What happened?**
Requests to startpage trigger their abuse protection. The strange thing is, that
I can use curl without problems on the same host (when I change the user agent).

**How To Reproduce**
I'm not 100% sure how to reproduce this  on other machines, as startpage seem to
work fine when I tried it with a searx docker instance running on my local PC. 

**Expected behavior**
Startpage should return search results, not the abuse protection page. 

**Additional context**
I tried setting the `User-Agent` header by modifying the engine, but it changed nothing.

**Comment by unixfox** [comment]
Did you try disabling HTTP2 or enabling it?

**Comment by patrickpichler** [comment]
I've tried setting `outgoing.enable_http2` to `False`, but it is still not working as expected.

**Comment by kvch** [comment]
Closed by 4750586fb0b5844bded294b1334c1ff4c0114f61
Feel free to reopen the issue if it persists.
