### ISSUE TITLE
Image json output lacks schema for flickr results

### ISSUE THREAD

**Issue by ndren** [searx/searx#3092]
**Searx v1.0.0**

Querying images with the json format does not give any schema for some outputs. For example, '?q=!images grizzly bear&format=json' sometimes returns img_src in the format '//example.com'.

Expected behavior: The format should be either 'example.com' or, preferably, 'https://example.com'.

**Comment by allendema** [comment]
Which engines are been used/enabled?

**Comment by ndren** [comment]
Thank you, I was able to narrow it down to 'flickr' engine causing the issue.
