### ISSUE TITLE
Create a browser addon

### ISSUE THREAD

**Issue by aha999** [searx/searx#3105]
**Is your feature request related to a problem? Please describe.**
Currently we have to set up settings on every device we are using.

**Describe the solution you'd like**
Create a desktop/mobile browser addon (Firefox, Chrome...) that would have our settings saved and where we could maybe also change them.

addon could also serve as to add SearX search engine into a browser so it would also show searx icon like other engines do.

**Comment by unixfox** [comment]
Probably the tool you are looking for: https://github.com/SimonBrazell/privacy-redirect

You can use the preferences URL too in the bottom of the preferences page.

**Comment by unixfox** [comment]
Closing because the alternative solutions should match the expectations of the user.

**Comment by aha999** [comment]
it would be best if SearX had it's own addon that i could trust and was made only for SearX purposes.

**Comment by unixfox** [comment]
We don't have the resources for managing a web extension.

**Comment by slrslr** [comment]
It seems that You can add search engine to a web browser.
Open some search engine from https://searx.space/
Click address bar (to open search suggest drop down menu) and on the bottom should be a button for that. Also some browser has separate search bar and it can have button too).
In Firefox this worked for me. Then setting it as default in _[about:preferences#search](about:preferences#search)_ no extension needed.
