### ISSUE TITLE
install instructions : disable ngnix and apache logs 

### ISSUE THREAD

**Issue by dalf** [searx/searx#313]
In this page https://github.com/asciimoo/searx/wiki/Installation there is the set up for nginx and apache. All IP are recorded in the access.log by default, and even the requests when the GET method is used. 

Should we modify this page to explain how to disable logs ? Perhaps with a warn about legal issue ?

**Comment by Cqoicebordel** [comment]
YES for the logs !!!
If you know how to do it, you're welcome to modify this page :)
Just, allow the user to choose (ie. don't add it hidden in the installation process, but instead in a sub chapter)

For the legal part, is there a legal issue ?
I know there might be in France, because ISP have to log for a year the connections, but I'm not sure about websites. And I don't know about others countries.

**Comment by xinomilo** [comment]
i saw that for nginx, access_log is set to off.  i think  its probably better to use access_log /dev/null; & error_log /dev/null;, cause otherwise access_log goes to default access and error log, of nginx.conf main config.  could edit wiki myself, would like to hear more opinions on this.

**Comment by dalf** [comment]
I didn't know that. Let's go with /dev/null

**Comment by ghost** [comment]
I think there should be (**well, there already is, but still adding this comment**) an addition to the installation instructions providing this so they can check up if it works in their country or if they want to ignore this law, keeping the logging settings to each persons choice.
I personally have to use a combination of anonymized IPs log in nginx + /dev/null for @searx location + haven't figured out yet how to get rid of logging the actual keywords of the proxyimage search (the normal queries aren't logged in content)

```
        map $remote_addr $ip_anonym1 {
            default 0.0.0;
            "~(?P<ip>(\d+)\.(\d+)\.(\d+))\.\d+" $ip;
            "~(?P<ip>[^:]+:[^:]+):" $ip;
        }

        map $remote_addr $ip_anonym2 {  
            default .0;  
            "~(?P<ip>(\d+)\.(\d+)\.(\d+))\.\d+" .0;  
            "~(?P<ip>[^:]+:[^:]+):" ::;  
        }  

        map $ip_anonym1$ip_anonym2 $ip_anonymized {
            default 0.0.0.0;
            "~(?P<ip>.*)" $ip;
        }
        log_format anonymized '$ip_anonymized - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent"';

        # log format for searx
        # regex: (searx/search)+([\w+?\.\w+])+([a-zA-Z0-9\~\!\@\#\$\%\^\&amp;\*\(\)_\-\=\+\\\/\?\.\:\;\'\,]*)?
        # 
```

the regex would get the searx/search part but not the proxie,
so at the moment it's access_log /dev/null which just logs the anoymized IPs of the proxy searches.

**Comment by dalf** [comment]
done https://asciimoo.github.io/searx/dev/install/installation.html ?
