### ISSUE TITLE
Google engine is broken

### ISSUE THREAD

**Issue by Golddouble** [searx/searx#3138]
**How did you install Searx?**
I have not installed anything, I just use this site: https://sx.fedi.tech/searx/search

**What happened?**
Google engine does not work if I make a "general" search

**How To Reproduce**
1. Go to https://sx.fedi.tech/searx/
2. preferences: Only activate "general" tab
3. In Engines unactivate all engines and activate only "google"
4. save
5. search for "auto"
6. Message:
![ksnip_20220117-210747](https://user-images.githubusercontent.com/13977359/149831461-49c4fad5-602a-48a6-9fc4-7a5b88bc22b0.jpg)

**Expected behavior**
It will find some million results with "auto"

**Comment by unixfox** [comment]
Cross-linking this issue on SearXNG: https://github.com/searxng/searxng/issues/771

**Comment by unixfox** [comment]
Fix implemented in [SearXNG](https://github.com/searxng/searxng): https://github.com/searxng/searxng/pull/777

**Comment by rekahsoft** [comment]
@unixfox thanks for all your work on searx! Are you planning on fixing this for searx along with searxng? Or should users look to migrate from searx to searxng?

**Comment by unixfox** [comment]
> @unixfox thanks for all your work on searx! Are you planning on fixing this for searx along with searxng? Or should users look to migrate from searx to searxng?

I've unfortunately no write access to the searx codebase, so you will either have to wait for @kvch to merge the fix from searxng or you can migrate to searxng.

**Comment by noctux** [comment]
Yep, thanks for the fix! For what it is worth, commit `6670063e0d2930bc40a7936829070ffc199e4a8d` by unixfox in searxng applys cleanly on searx release v1.0 for everyone who is willing to patch locally.

**Comment by kvch** [comment]
I have picked the fix from searxng. Thanks @unixfox for the ping and @noctux for the ref to the fix.

**Comment by unixfox** [comment]
> I have picked the fix from searxng. Thanks @unixfox for the ping and @noctux for the ref to the fix.

@kvch You should pick this one too: https://github.com/searxng/searxng/commit/f0102a95c96605cb0702a374f084f82074698cf2

**Comment by kvch** [comment]
Done. Thanks.

**Comment by ganeshlab** [comment]
This issue popped up again and part of the fix was in https://github.com/searxng/searxng/commit/6f9e678346e5978a09ee453a62fa133cdc0ee0bd. 

The specific change I made to fix it was: 

`content_xpath = './/div[@data-sncf]'` in place of `content_xpath = './/div[@data-content-feature]'`
