### ISSUE TITLE
Use OpenSearch instead of Elasticsearch

### ISSUE THREAD

**Issue by ThatOneCalculator** [searx/searx#3153]
Elasticsearch is [no longer  free and open source](https://www.elastic.co/blog/licensing-change), they call the blog post "Doubling Down on Open", but in reality they changed to being proprietary and source-available. [OpenSearch](https://github.com/opensearch-project/opensearch) is a fork of Elasticsearch 7.10.2, developed by Amazon, which stays open source and removes Elastic telemetry.

**Comment by unixfox** [comment]
Is the current elasticsearch engine for searx still working for opensearch?
If so I don't see any point of renaming it because we don't want to confuse people that are used to elasticsearch and we don't want to break the existing setup that already have elasticsearch in their settings.yml

**Comment by ThatOneCalculator** [comment]
> Is the current elasticsearch engine for searx still working for opensearch?

It is, but OpenSearch also has better performance. But i can totally see why it would be hard for migration

**Comment by unixfox** [comment]
Ok thanks for the reply but there is no plan to rename anything as the elasticsearch engine works like you said with opensearch. Even though it's two different projects, it's just a name for the engine internally in SearX.

You can submit a PR with a comment at this line saying that it works with opensearch too though: https://github.com/searx/searx/blob/master/searx/settings.yml#L381
