### ISSUE TITLE
I get ... triple dots in the URLs in the output.

### ISSUE THREAD

**Issue by 621625** [searx/searx#3168]
Hello,

I'm BM. A very nice and polite guy.

I get ... triple dots in the URLs in the output from serx.cf. Like this:

https://www.adb.org/news/adb-signs-68-[...]-access-affordable-green-housing-india

This doesn't work, it happens ever so often. How can I change the configuration or something so that I get the full URL?

Browser: links, OS: *Nix

**Comment by unixfox** [comment]
Can you explain in a bit more details?
Like which keyword did you use when searching or if you know that which engine did you enable?

**Comment by unixfox** [comment]
Closing due to a lack of replies.

**Comment by 621625** [comment]
![image_2022_02_23_16_49_47](https://user-images.githubusercontent.com/2834754/155296780-6d9cd7bf-f716-4018-8b28-4a51596a6b90.jpg)

Lots of triple dots in the output. About 50% of the URL's have triple dots in the middle so they cannot be used.

**Comment by unixfox** [comment]
You didn't reply to all of my questions from https://github.com/searx/searx/issues/3168#issuecomment-1046854549

**Comment by 621625** [comment]
1. This issue occurs regardless of keyword choice.

2. As far as I can tell it occurs with every search engine (I have all search engines enabled).

This is probably an issue with searx because it seems to occur with many different types of browsers such as brave, links, lynx, elinks etc. I often see those triple dots and then I cannot process the output further.

**Comment by unixfox** [comment]
Can you show a screenshot of brave with the issue?

Can you give the keyword that you used even though it occurs on every keyword.

Can you give the URL of the searx instance if you used a public instance?

**Comment by 621625** [comment]
Update: Searx seems to almost be able to display URL's in Brave as of today. They are partially hidden:

![Screenshot_20220223-173445_Brave](https://user-images.githubusercontent.com/2834754/155302741-3af193a4-1caa-490c-ac31-b44c553e73b2.jpg)

Lightning browser - three dots in the output:

![IMG_20220223_173630_444](https://user-images.githubusercontent.com/2834754/155303024-d9d6216e-139d-4e0f-a7ac-91a1d90ebc4f.jpg)

Lynx browser - three dots in the output:

![image_2022_02_23_17_38_49](https://user-images.githubusercontent.com/2834754/155303385-e997b6bc-b517-4eb9-910d-3833ba076e91.jpg)

Keyword: cat

Instance: serx.cf

**Comment by 621625** [comment]
I cannot pipe from Brave anyway so I'm primarily looking for a fix for the output in links and lynx and these types of terminal browsers.

**Comment by unixfox** [comment]
Why is it an issue if you can get the URL from the title?

Take the URL from this part:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/4016501/155306405-16537f14-91ac-4fff-9685-b101b0bc6997.png">

On brave right click then copy. On links idk

**Comment by 621625** [comment]
I don't use Brave. I use the Linux terminal. 

The output from searx has three dots in the middle if using links, lynx, elinks etc. Therefore the URL cannot be processed further because there is information missing.

Perhaps the UX designers decided to abbreviate the URLs at some point but I think it should be possible to disable this feature, to make Searx (more) useful in the command line.

From my perspective it's more of a bug than a feature request. The output is just not rendered correctly in the Terminal.

For reference, ddgr and s (two somewhat similar tools) will render the full URL's but lack other features that searx has.

**Comment by unixfox** [comment]
But you can get the URL from the title, isn't that possible from links or any browser in the terminal?

The URL is cropped so that it doesn't take too much space on the screen of the user. That's an UX design.

**Comment by 621625** [comment]
Ir's probably possible if parsing the source instead of parsing the web view rendered HTML page. But then the rendered page is kind of useless in Terminals. What is the point of providing URLs if they cannot be read or used?

I feel that searx should not output triple dots in the middle of the URL like that in text based browsers.

Also, it seems to go against the goal of the project. 

The catchphrase is "hackable metasearch engine", right?

To me, hackable means I can use it together with my other Unix tools. That's the allure to me with Searx.

And in that case it should be able to at least output URLs correctly in the terminal. That's like the most important function of this tool in a way : )

Anyway if there is a reasonably easy way to fix this in a future version then please implement if possible. It's so close to being useful in text based browsers, just a little push and it crosses the goal line : )

Otherwise I will try to work around it myself.

**Comment by unixfox** [comment]
I don't quite understand why it's such an issue when you can still get the full URL using another method. For instance, on lynx you can use shift + e in order to get the URL of the selected link: https://superuser.com/a/82991

What are you really trying to achieve here? You are saying that searx should hackable, but if you want to fetch all the links of a search then you are better off using the API of searx.

It is not enabled on every public instances, serx.cf doesn't have it enabled, but if you use a local install of searx you can fetch the results in:
- JSON: /search?q=ok&format=json
- CSV: /search?q=ok&format=csv
- RSS: /search?q=ok&format=rss

Some public instances have it enabled but you will have to find the ones on https://searx.space
