### ISSUE TITLE
custom error-sites

### ISSUE THREAD

**Issue by pointhi** [searx/searx#317]
We could support custom error sites inside the templates, to show for example 404-Errors in the design of the template instead of some naked text. (continuous design).

But we have to be cautious with 5xx-Errors caused by template problems (fallback-solution, if the error-template is not working like expected)

**Comment by dalf** [comment]
404 error page can be the search page with a clear message.
- it's avoid one click to go elsewhere most of the time ( the purpose of searx is to search something )
- it's simple to implement

Just an idea.

If we display one dedicated error page, we should provide links to elsewhere. 
It's more or less "free" with the oscar theme, but not with the others themes.
