### ISSUE TITLE
robots.txt is gziped

### ISSUE THREAD

**Issue by pointhi** [searx/searx#318]
I cannot read the [robots.txt](https://searx.oe5tpo.com/robots.txt) of my server because it is gziped, and the browser is not detecting that fact. I have looked over some other searx instances, and it looks like some other sites have the same problem, and other are working fine.

I am using apache, but adding the following line doesn't helped: 

```
AddOutputFilterByType DEFLATE html txt xml css js php
```

I'm not sure, but either my option is wrong, or gzip is done by uwsgi or flask.

**Comment by Cqoicebordel** [comment]
I'm not sure, but I think it's the other way around : you have to add in the result header that it's gzipped so the browser can open it properly.

But I don't reallty know...

**Comment by dalf** [comment]
In Google Chrome, I have looked on the network tab of the developper console for three urls : 
- /robots.txt
- /opensearch.xml
- /

On searx.me and al-f.net, there is a reponse header for /robots.txt, the content is not compressed according to response header.

On searx.oe5tpo.com there is no response header, it look like the robots.txt is sent without HTTP headers.

There is same behaviour (no header) with /opensearch.xml, but it works on all servers (except I remember there was a similar bug with this URL few months ago).

About the /, it is different, there is a header for everyone, and the content is compressed.

If I compare : 
- https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L725
- https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L702

There is no http status code, perhaps something like that should help : 

``` python
    return Response(response="""User-agent: *
Allow: /
Allow: /about
Disallow: /stats
Disallow: /preferences
""", status=200, mimetype='text/plain')
```

It's only a guess.

EDIT : see http://flask.pocoo.org/docs/0.10/api/#response-objects , perhaps try [`make_response`](http://flask.pocoo.org/docs/0.10/api/#flask.Flask.make_response)

**Comment by pointhi** [comment]
I changed it on my server, but it doesn't helped.

**Comment by dalf** [comment]
@pointhi > if possible, can you share your apache configuration ?

**Comment by pointhi** [comment]
Yes, this is my apache configuration:

```
<VirtualHost *:80>
    ServerName searx.oe5tpo.com
    ServerAlias searx.oe5tpo.com searx.server1.oe5tpo.com

    ErrorLog ${APACHE_LOG_DIR}/searx.oe5tpo.com_error.log
    CustomLog ${APACHE_LOG_DIR}/searx.oe5tpo.com_access.log combined

    <Location />
        Options FollowSymLinks -Indexes
        SetHandler uwsgi-handler
        uWSGISocket /run/uwsgi/app/searx/socket
    </Location>

    <IfModule mod_rewrite.c>
        RewriteEngine On
        RewriteCond %{HTTPS} off
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
    </IfModule>

    <IfModule mod_evasive20.c>
        DOSHashTableSize 3097
        DOSPageCount 20
        DOSSiteCount 500
        DOSPageInterval 1
        DOSSiteInterval 1
        DOSBlockingPeriod 60
        #DOSEmailNotify <someone@somewhere.com>
    </IfModule>

    # HSTS (mod_headers is required) (15768000 seconds = 6 months)
    Header always add Strict-Transport-Security "max-age=15768000"

</VirtualHost>

<VirtualHost *:443>
    ServerName searx.oe5tpo.com
    ServerAlias searx.oe5tpo.com searx.server1.oe5tpo.com    

    ErrorLog ${APACHE_LOG_DIR}/searx.oe5tpo.com_error.log
    CustomLog ${APACHE_LOG_DIR}/searx.oe5tpo.com_access.log combined

    <Location />
        Options FollowSymLinks -Indexes
        SetHandler uwsgi-handler
        uWSGISocket /run/uwsgi/app/searx/socket
    </Location>

    <IfModule mod_evasive20.c>
        DOSHashTableSize 3097
        DOSPageCount 20
        DOSSiteCount 500
        DOSPageInterval 1
        DOSSiteInterval 1
        DOSBlockingPeriod 60
        #DOSEmailNotify <someone@somewhere.com>
    </IfModule>

    SSLEngine on
    SSLCompression off
    SSLProtocol +All -SSLv2 -SSLv3
    SSLHonorCipherOrder On

    SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA

    SSLCertificateFile /etc/apache2/ssl/searx.crt
    SSLCertificateKeyFile /etc/apache2/ssl/searx.key
    SSLCertificateChainFile /etc/apache2/ssl/sub.class1.server.ca.pem

    # HSTS (mod_headers is required) (15768000 seconds = 6 months)
    Header always add Strict-Transport-Security "max-age=15768000"
</VirtualHost>
```

**Comment by dalf** [comment]
In fact, it's a whole configuration that should be analyse (an which module are enabled) : could be http://httpd.apache.org/docs/2.2/mod/mod_mime.html#removetype for instance

**Comment by pointhi** [comment]
Thanks for that hint. `$ a2dismod deflate` solved this issue, but I don't know why it is not working with searx, but working correctly with other php-applications running on the same webserver.
