### ISSUE TITLE
Disable the Error box Option

### ISSUE THREAD

**Issue by JoshWho** [searx/searx#3226]
I do not see any option to disable the error bos. Is this a thing?

![9fc10db8-9780-4b7a-97ba-7425fad86b43](https://user-images.githubusercontent.com/39392449/167078441-9eba23a2-dba7-4078-94c6-e54f001b091e.png)

**Comment by JoshWho** [comment]
Nevermind I just removed it from the source

**Comment by unixfox** [comment]
Set `display_error_messages: false`
Explained here: https://searx.github.io/searx/admin/settings.html#id8
