### ISSUE TITLE
Error when installing Searx

### ISSUE THREAD

**Issue by nytche** [searx/searx#323]
I have followed the install tuto, and got an issue there:
(searx-ve)$ python searx/webapp.py
ERROR:searx.plugins.https_rewrite:directory not found: '/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.7.0-py2.7.egg/searx/plugins/https_rules'
any idea of what is wrong?

**Comment by Cqoicebordel** [comment]
Can you check what is installed and in what directory you are ?
If you can give us the result of the commands `tree` and `pwd` it would help a lot.

Can you also try to run it when exiting the virtual env ?
Just run it with `python searx/webapps.py`, but not from "/usr/local/, but from a path that looks like "/usr/local/searx/searx-ve/lib/python2.7/site-packages/searx-0.7.0-py2.7.egg/"

**Comment by pointhi** [comment]
I think we have to add that directory into https://github.com/asciimoo/searx/blob/master/setup.py#L76

**Comment by Cqoicebordel** [comment]
Again the same thing ?!

There is a big chance that you are right.
We have to be careful about that thing, it's not new.

**Comment by nytche** [comment]
tree: command not found
pwd: /usr/local/searx

**Comment by asciimoo** [comment]
@pointhi yes, i forgot to update the setup.py, sry
