### ISSUE TITLE
Exclude banned websites from results

### ISSUE THREAD

**Issue by ghost** [searx/searx#3231]
Hi there,

Would be really useful to have a configurable list of excluded or banned websites which do not appear in the search results. Perhaps the user itself could configure the ban list in the «preferences» window, with a few added websites by default by the instance maintainer.

Thus, for example, if in the ban list appears «fake-news.com» and «pure-propaganda.net», then when searching for anything that websites will not appear.

This is important given the ability of some propaganda outlets to place themselves at the top of the results of some search engines.

Regards.

**Comment by unixfox** [comment]
Duplicate of https://github.com/searx/searx/issues/2001
