### ISSUE TITLE
Engine request: Psychonautwiki

### ISSUE THREAD

**Issue by ghost** [searx/searx#3236]
**Working URL to the engine**
https://psychonautwiki.org

**How can Searx fetch the information from this engine?**

Psychonautwiki uses mediawiki, so I tried using the following configuration:

~~~yaml
  - name : psychonautwiki
    engine : mediawiki
    shortcut: psy
    base_url: https://psychonautwiki.org
    disabled: True
~~~

But I got timeout or HTTP error when trying to use it.

They also have a GraphQL API: https://api.psychonautwiki.org/

**Applicable category of this engine**

General

**Comment by devinprice** [comment]
I agree, it's about as reputable a source as it's intended audience could ask for and promotes harm reduction practices and safer substance use.

Reducing the barrier of entry to knowledge about potentially life-saving info is a worthwhile project

**Comment by kvch** [comment]
I have added the engine. Your configuration was mostly correct, the problem was the missing `/` from the end of the `base_url`.

Now you can run `!psy lucid dreaming` and get a result. \o/
