### ISSUE TITLE
Bing engine returns unsanitized URLs

### ISSUE THREAD

**Issue by BBaoVanC** [searx/searx#3239]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**

Docker, version `1.0.0-372-6ffa70d8`

**How did you install Searx?**

Docker Compose

**What happened?**

The URLs in results from the Bing engine are not sanitized. For example:

```
https://www.bing.com/ck/a?!&&p=c4b4301ae7afbd0a1071c3cfeb006528b245f72840bdd2cfb45fa713e8e4233aJmltdHM9MTY1Mzc5NDI2MSZpZ3VpZD01YjM5NjkwMC1kYTU5LTQ3NjktYThhZC0wZDdjNTI3NTkxYWUmaW5zaWQ9NTEwNw&ptn=3&fclid=e658a0c1-defd-11ec-a532-579bfbff64fd&u=a1aHR0cHM6Ly9taW5lY3JhZnQubmV0Lw&ntb=1
```

**How To Reproduce**

1. Make a search using Bing (`!bing minecraft` for example)
2. Read the links in the search results.

**Expected behavior**

The link in my example should have said `https://www.minecraft.net/en-us`.

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/17971474/170850550-968845b9-3ef3-4ed2-ab9c-5a8681365a79.png)

**Additional Context**

This bug also happens on every single public instance I tested on https://searx.space.

**Comment by unixfox** [comment]
Related: https://github.com/searxng/searxng/pull/1219

**Comment by filip-769** [comment]
If you change user agent from firefox to chromium, the urls are normal.

**Comment by asciimoo** [comment]
> If you change user agent from firefox to chromium, the urls are normal.

Interesting, but seems like it works, thanks!

**Comment by lolcatw** [comment]
I don't know if this has been implemented yet, but if that URL format is forced on you, here's what you can do:

The parameter &u (towards) the end is actually Base64 for the destination URL. Just replace the first occurrence of `a1` with nothing at the start of the string.

Cheers
