### ISSUE TITLE
Embed a searx search bar inside a web portal

### ISSUE THREAD

**Issue by HLFH** [searx/searx#324]
Hi,

Is there some HTML5/JS code to add a searx search bar inside a web portal, and when you use this searx search bar - for example you type "searx is cool', you are redirected from the web portal (example.com) to the searx results (searx.example.com/?q=searx%20is%20cool&pageno=1&category_general).

On this private web portal, there are several shortcuts to subdomains with webapps like ownCloud, gogs, Transmission, etc. I would like to put in the header a basic searx search bar. Is that a thing possible?

Thanks in advance,

**Comment by dalf** [comment]
How do you want to include searx ? with a iframe as you descibe it ? another solution could use the JSON API (even if there is some missing information like the info boxes or the right side).

I think the IFrame solution is possible but 
- I don't know why the search result replace the portal page (this is a simple HTML form without target or something else).
- the theme has to be modify to be nicely include into a portal (source code of the oscar theme : https://github.com/asciimoo/searx/tree/master/searx/templates/oscar ). Perhaps create a new theme ?

Can you post some code to test what you descibe ?

**Comment by Cqoicebordel** [comment]
I think what he wants is that searx provide a small page to be included in a iframe, with only the text input and a search button, which would redirect to a choosen page.
That could be really easy to implement.

**Comment by HLFH** [comment]
@Cqoicebordel Hi and thanks for translation.

@dalf What I would like to add as @Cqoicebordel explained is a "text input and a search button, which would redirect to a chosen page": the dedidated results page of the searx instance. And where? For example here: https://gitnote.eu in the header, before the "webapps boxes". This call-to-action shortcut would improve the use of Searx and reduce the direct use of Google Search. In fact, a lot of open source users love their personal data, so they want to protect them with ownCloud, Cozy, ...and also with dedicated operating systems like YunoHost, arkOS. In this trend, these people use a lot of open source webapps in one single domain. 
![screenshot 2015-05-19 at 13 48 06](https://cloud.githubusercontent.com/assets/2359059/7702084/b9109b60-fe2d-11e4-822e-ff076764b972.png)
For this Yunohost example, I believe we need to add the search bar - maybe in a lighter version - on this homepage/web portal. 
![screenshot 2015-05-19 at 13 53 15](https://cloud.githubusercontent.com/assets/2359059/7702179/74abc764-fe2e-11e4-95bc-53167979d854.png)
If it could be done with an iFrame or using the JSON API, I would love to know how to do it.

Because search engines for now are the key to the web surfing & productivity, they **need to be more present** than an subdomain (for example: https://searx.gitnote.eu) with just a "box area" in the homepage to reminder you that you have Searx on your server too. If you provide some code to implement directly the searx search bar inside the webapps portal, a lot of open source users would really appreciate that. It would be a shortcut that would redirect from the second-level domain (here: gitnote.eu) to the third-level domain (here with the running searx instance: searx.gitnote.eu) on the dedicated searx results page, according to the user input.

Thanks in advance,

**Comment by privacytoolsIO** [comment]
Check out the source code on www.privacytools.io - I've included it there. Maybe that helps?

**Comment by HLFH** [comment]
@privacytoolsIO Btw, will https://github.com/privacytoolsIO/privacytools.io be an open source repo? I would like to add Sailfish OS in here: https://www.privacytools.io/#mobile_os, [AsusWRT Merlin](https://github.com/RMerl/asuswrt-merlin) in "worth mentioning": https://www.privacytools.io/#firmware, [ownCloud Desktop Syncing Client](https://github.com/owncloud/client/) in "worth mentioning": https://www.privacytools.io/#sync, I believe you should switch Pydio and ownCloud here: https://www.privacytools.io/#mycloud, here you should place Firefox in "worth mentioning", and replace Firefox's nice place by its fork [Pale Moon](https://www.palemoon.org/), that will never support HTML5 DRM (Encrypted Media Extensions) and Ads: http://www.ghacks.net/2014/05/21/palemoon-author-confirms-browser-will-ship-eme-ads-australis/ Also in VPN tools, you should add [HideMyAss](https://www.hidemyass.com/) because it's a famous one that supports also BitCoin and is located for the most part outside of the US: https://www.privacytools.io/#vpn, in DNS, you should add the DNS server PowerDNS in "worth mentioning": https://www.privacytools.io/#dns, add Movim in "worth mentioning": https://www.privacytools.io/#social, and here, I believe it would be great to warn a little more about France, because with the recent law "Projet de loi relatif au renseignement", the intelligence agencies DGSI & DGSE could use Deep Packet Inspection (DPI) technologies to control the Internet, and IMSI-catchers to control phones: https://www.privacytools.io/#ukusa

And thanks your search implementation clearly helps. I'll close this issue, when I'm done with the implementation on my side.

**Comment by stef** [comment]
sorry for going off-topic: when i last checked palemoon a few months ago i found out, that backporting of security patches is not very diligent.

**Comment by privacytoolsIO** [comment]
@HLFH: Thanks for your great feedback and sorry that I got back to you so late. I'll discuss all your ideas with my team now. Please message me on reddit if you want to help setting up a github repo: https://www.reddit.com/message/compose/?to=BurungHantu thanks!

**Comment by nixoye** [comment]
@privacytoolsIO can you explain or share the code you used to embed the search their? I would like to make on with my searx instance. Also it seems https://www.privatesearch.io/ is down.

**Comment by asciimoo** [comment]
closing, see #679
