### ISSUE TITLE
Feature: Firefox / Chrome Browser Plugin

### ISSUE THREAD

**Issue by privacytoolsIO** [searx/searx#325]
I just installed the DuckDuckGo Firefox plugin and I'm impressed. It's simple and effective:
https://duckduckgo.com/extensions/thanks/

What do you guys think?

**Comment by dalf** [comment]
Note : the Search Bar, and Context Search is native as soon as you choose searx as your default search engine. Address Bar Search works without the suggestions.

About "Instant Answers Everywhere", is it something everyone want ? 

Don't get me wrong, I'm not saying that we should do an FF / Chrome extension.

I just saw this extension : https://addons.mozilla.org/en-Us/firefox/addon/searx-me/

The duckduckgo source code : https://github.com/duckduckgo/firefox-zeroclickinfo

(I was thinking about an Android version too : https://github.com/duckduckgo/android)

**Comment by unixfox** [comment]
Opensearch is better suited for that and already do most of the job of the described duckduckgo extension.
