### ISSUE TITLE
Add engine Qwant 

### ISSUE THREAD

**Issue by beudbeud** [searx/searx#326]
Qwant is a french search engine respectful of privacy

**Comment by dalf** [comment]
Seems doable : 
https://api.qwant.com/api/search/web?count=10&offset=0&f=&locale=fr_fr&q=qwant
the response is in JSON format.

Replace web by knowledge, social, news, suggest, smart_top (no count or offset for this one).

**Comment by dalf** [comment]
Done

**Comment by beudbeud** [comment]
thanks
