### ISSUE TITLE
Kagi UI emulation

### ISSUE THREAD

**Issue by ylluminate** [searx/searx#3261]
After testing Kagi for a while, I've really come to love what they're doing as far as the user experience goes with their user interface. Some of the functionality such as "Order by" with "Recency" + "Ascending" vs "Descending" is really slick. There are a lot of other aspects about it that are quite nice. I believe a study of the UI elements could be extremely productive for refining and enhancing SearX.

Hoping we can document various elements that could be useful to emulate here for review and implementation.

**Comment by unixfox** [comment]
What is kagi UI though? Can you post a link to this project?

**Comment by ylluminate** [comment]
Sign up for free access (paid service but you get like 50 free searches a month): https://kagi.com/

Here's a short video just clicking around to give you an idea: https://share.getcloudapp.com/E0uybr6j

**Comment by unixfox** [comment]
Please add your suggestion about UI changes here: https://github.com/searx/searx/issues/2440
