### ISSUE TITLE
Show search result in browser tab

### ISSUE THREAD

**Issue by AE720** [searx/searx#3275]
I've looked through settings and searched with as many keywords as I can think of but never found anything concrete. In a searx instance, the tab just says what searx instance you're using which makes me have to go to the tab to see what I searched in that tab before needing to decide if I need it or not. It would be nice if that tab would show what I searched instead like it does with other search engines. I apologize if this can be done and I neglected to look in the right places.

**Comment by unixfox** [comment]
You are probably using searxng because only searxng has this feature.

You need to enable `Query in the page's title` in the settings in the privacy tab.
