### ISSUE TITLE
Cannot use just google as an engine

### ISSUE THREAD

**Issue by TimTam4U** [searx/searx#3282]
If I disable all engines and only allow google, the search queries fail with the error 'Sorry! we didn't find any results. Please use another query or search in more categories.'
<img width="1438" alt="Screen Shot 2022-07-11 at 3 35 23 pm" src="https://user-images.githubusercontent.com/69711161/178195709-83f570cc-7579-4e96-a267-dc5769598404.png">

Why is that? I would only like google results to be shown - hence why I disabled it. Is there an alternative on how to do this?

My preferences:
[Click Here](https://searx.org/?preferences=eJx9V02P3DYM_TU7F2ODJmnR5jCHNEXbAAUSdLe9GrTE8TCWRUWSZ8b760uNv6SZRQ_rhWlJ5CMfnzgKIrbsCcO-RYsezM6AbQdocY_28Y9fd4YVmPSygyGy4t4ZjLjXg-rSX8s76mV17Txfxv3vYALueoxH1vuvX56edwEOGBC8Ou5_2MUj9rjnoMDvPIbBxFCzrS2e6wjN_tkPuNNMtXxjc0K_Z5DXN-zb3XXTY4ijBGO4JcUaT48afLcDfQKrUNezn-kYCtAYMaJtyQo-6_q6pvjw7lNDtq2uUQexXP-L9czm4KEH445Q10ERyplih9DV9Zwcef1-Bhvvd7ND69Gx2A5kriaH6OPQYF2fSCMnkx0BtgXU6yY_ugfbEfo5ynRiiB4x9uDqWh5pCV2U4UHL-xBIpUOsnE48hM0U2Xu08WWztI61Tidvzsa2nddtAclXyg9qmVuD92DhxYyeVMjPm3JHjcc5_sjdyJHDkTuwm48pBYuHgC8W-vwchxFMbhhscAbCMfPfkeogZIHmYBab0IOkVOBjtlMDmbHnSMK6rSxTTafXzJwo1qBvZ0BzNu6WCUGGZrBxmNdNCNfPPSnPgQ-xAgUa5TVnV8oY-LFKeAMVGV2LtqTuyts79yMPE8sW4A1YraB3r3Jki9pf6JRH4o5SLbsQTQ0pnWrMAwoRVMfSlgfD5xnsmTrqyVK-TiO-pLgX94NPIZFKWResBcYppyIAElt6rtUoTMfrstmlR60pL6obml4aPcOCns-kc0c3bFxCc-RFARsYc0omEUm1r9Jjdko2r2kC88IWC9SrIt43zNv373--ZPsDSq9HUlVQRzbg89j7sceehRLRgw1GwiuABB6kvKUGbA2_djJFA81NwuZkZpg3qgtFg8dDHoj4jMzzGSkndBItCHdimBveXjLUSqnHeMq8JEkDknAgQkDR_rxk4suU_KdWFBxC4SDxTRgYKI435lfYFUX4R8wiunZQwSzpvlNRxhP1yFnMGEUvrKGy2OejXIrBkMZX2CxyNVY9nwjzhjuz15aKu8QPfWPy--FODZZ6roq3GJSa7rUMXM_fEIvzm6ipbbdNG0VvUyqs8qrAMqnYJrkwHGQyKKgoDTA1S3GJoSaQe74T-OczNnkGxJFLn4t7CKS5y5pcTUVr6bbSeBCZSUUOr0FcWsEPzdhiHzLaVlK84VIl77P1YCSdPr8WrmcEVgSmuiKYeug43PbQzZpVfO84LqIkXmAOOBsnXFf15D0Xwh4bKQvG2dlCAz6IBNlWpqFcTA7acxK3ZXcC1jB3RV7Cw6efHn55x2ehXPXt4dOPDx8-vIwdVE66TKaMkgIBHcFSyxVKTmdwLmPfkvWitN8HjgWFUreVGrzIVLavee0-eEUWQ7rJXZo0b6ibxOR_lH51tVRwW7k21dbsV1WUrc5J7LODgpsT7vnl4EkmNlBZcQw3IeIbvxAwn0xWN04nymzYjiD1To-FnzL1VWlkOIPHSgublBwyzl8z_V7qEQaHfgjr7HhVSR5vsmVF6ooZUHPryJQStgwdN0R3o1u6Rw8abbFHZCeKbC6Yz3yhju0buUHDaNnKhVbeYKKbc1IWTu2kaYppvZ1v_OVXyTrOOzPIirB_mtgqE4uafsOMMv4bSZR4-Jf6R0Md1jLSdDimDH2Rtqw_impKvX_78ll-YZw9xZT8P9NsOZ0qb89eZhzB_8_ff8maPk07aQ2HKHMqikm64Vqzz_aqRyhl9GwSric0h1rM7Pup7dPG5-evT4uzFeSCYSdclSF__x_iuBhn&q=%s)

**Comment by unixfox** [comment]
Did you try to turn `use_mobile_ui:` to true and restart searx if that fixes the issue?
