### ISSUE TITLE
Video search when using either Bing or Google doesn't get you past the first page

### ISSUE THREAD

**Issue by Krando** [searx/searx#3294]
This is an universal issue with Searx which strangely has never been noticed although it's so obvious when you start messing around with the settings and engine selection. Get a searx instance where bing & google work on video search and search for anything. You will notice now that when you go the next page for more results, the same results that were on the first page are being repeated. In other words, you can't get more results.

Please fix this issue, we should be able to get as many results as we wish. There is nothing technical truly making this impossible, it can be done.

**Comment by unixfox** [comment]
Can you reproduce the issue on SearXNG: https://github.com/searxng/searxng?

Here is one of the SearXNG public instances: https://paulgo.io/

**Comment by Krando** [comment]
1. Go to https://searx.be
2. Reset all settings, go to "engines" and then "video", select Bing and Google as engines ONLY.
3. Turn off infinite scrolling from the user interface.

After saving the settings, go to "videos" and search for "roosevelt". As you can see, the last video is "Theodore Roosevelt Slideshow". Now go to the next page and scroll down again. You'll now see that nothing different happened, searx merely repeated the results from the first page as the last video is also "Theodore Roosevelt Slideshow" on the second page. In other words, there are no new results. You can turn on infinite scrolling too and see that the same 21 results are being repeated again all over.

However, this issue only concerns Bing. If you turn off Bing and just select Google for videos, you'll see that there is no such thing as a second page. There is no next page. Infinite scrolling also doesn't work on Google video search.

This issue may be easier to fix, because for google videos, no infinite scrolling is occurring unlike for google images.

**Comment by unixfox** [comment]
Searx.be is using SearXNG not SearX, please report the issue on the correct GitHub repository: https://github.com/searxng/searxng/issues

If you can reproduce the issue on SearX (not on SearXNG) then please reopen this issue.

You can find multiple SearX public instances on this website: https://searx.space. The SearX instances don't have a date in their version number and usually start with 1.0.0.
