### ISSUE TITLE
Config switch for "Show advanced settings"?

### ISSUE THREAD

**Issue by r4dh4l** [searx/searx#3297]
**Is your feature request related to a problem? Please describe.**

As far as I know: No.

**Describe the solution you'd like**

There is a GUI preference switch for "Show advanced settings", default is "Off". I would like to switch it to "On" via `settings.yml` so it is active on default for all users. Maybe I just didn't notice the [config line](https://searx.github.io/searx/admin/installation-searx.html#configuration)?

**Describe alternatives you've considered**

(none)

**Additional context**

(none)

**Comment by unixfox** [comment]
Try:
```yaml
ui:
  advanced_search: True
```

I found it in the source code: https://github.com/searx/searx/blob/968b28991595c5971b4299b4b300c020b39f02a9/searx/preferences.py#L398

It's unfortunately not documented.

**Comment by r4dh4l** [comment]
Thank you. For others: I had to restart my browser to the see advanced settings unfolded.

**Comment by r4dh4l** [comment]
But maybe the issue could be used as "update request" for the documentation?
