### ISSUE TITLE
Piratebay engine : update the URL

### ISSUE THREAD

**Issue by dalf** [searx/searx#330]
The current URL is https://thepiratebay.se which doesn't respond.
This one seems to work https://thepiratebay.mn  (see https://en.wikipedia.org/wiki/The_Pirate_Bay )

Another solution : disable / remove the engine in settings.yml

**Comment by asciimoo** [comment]
According to wikipedia, the official site is the `.se` again and it redirects to `.la`, but the engine works again..
+1 to default disable without domain modifications

**Comment by dalf** [comment]
I can't access .se web site. Same for http://downforeveryoneorjustme.com/thepiratebay.se

**Comment by Cqoicebordel** [comment]
And https://thepiratebay.mn/ ?

I can't agree with disabling this engine. Look at my comment in the PR
