### ISSUE TITLE
Youtube engine is broken

### ISSUE THREAD

**Issue by dalf** [searx/searx#331]
The only result result returns by the youtube engine is to https://youtube.com/devicesupport

**Comment by dalf** [comment]
I'm not sure if the API v2 is still working (it is deprecated since last year).

And the v3 API requires a key.

I suggest the same implementation than the flickr engine : 
- an engine based on scraping ( see https://www.youtube.com/results?search_query=test without javascript)
- an engine based on the API v3 if we have time to write it.

**Comment by Cqoicebordel** [comment]
I'm waaaaaaayyyyyyy behind on searx dev, but I like writting engines, so I'm OK to do it, probably within the next week.

**Comment by asciimoo** [comment]
@Cqoicebordel that would be awesome, thanks!
