### ISSUE TITLE
Bing: don't show bing.com urls

### ISSUE THREAD

**Issue by br4nnigan** [searx/searx#3335]
bing shows these really useless bing.com urls in which it encodes the actual url. Google does this too but Google replaces the actual url with a Google url only when you visit (or copy) it. So these bing urls are really useless seeing in searx. I realize the code uses the same url for display and the href but there could be a property to override it, like `display_url` which could then be used in the bing engine

**Comment by TheRealGrimlok** [comment]
The nefarious thing though, is that, the bing URLs have Bing's tracking URLs in it.  Is there a way that Searx can strip that out before being clicked?  The workaround I have been using is just disabling that engine all together.  Bing seems to be the only one doing this.
