### ISSUE TITLE
Wrong Links to Blog in Documentation

### ISSUE THREAD

**Issue by larskasper** [searx/searx#3342]
In the Searx documentation on https://searx.github.io/searx/ there is in the sidebar navigation a link to the Blog amidst other Project Links. On that home page the link to the Blog is
https://searx.github.io/searx/blog/index.html
and it works.

But on other (sub-)pages of the documention, the link to the Blog is wrong and results in Page Not Found errors. For example, on
https://searx.github.io/searx/user/index.html the link to the Blog is
https://searx.github.io/searx/user/blog/index.html; on
https://searx.github.io/searx/admin/index.html it is
<https://searx.github.io/searx/admin/blog/index.html>.

**Comment by kvch** [comment]
Thank for reporting it!
