### ISSUE TITLE
Couldn't find correct source of a featured snippet content

### ISSUE THREAD

**Issue by etanot** [searx/searx#3351]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
2022.08.23

**How did you install Searx?**
Reproducible on [searx.be](https://searx.be) instance.

**What happened?**
For some keyword searches source of Google's featured snippet content is missing from search result entirely.

**How To Reproduce**
- Search for ["apply dijkstra's algorithm with negative edge weight cycle"](https://searx.be/search?q=apply%20dijkstra%27s%20algorithm%20with%20negative%20edge%20weight%20cycle&categories=general) on [searx.be](https://searx.be) instance.
- Look for source of the snippet result i.e. [Why doesn't Dijkstra's algorithm work for negative weight ...](https://stackoverflow.com/questions/13159337/why-doesnt-dijkstras-algorithm-work-for-negative-weight-edges) in the search results.

**Actual behavior**
Actual source of the featured snippet (i.e. [Why doesn't Dijkstra's algorithm work for negative weight ...](https://stackoverflow.com/questions/13159337/why-doesnt-dijkstras-algorithm-work-for-negative-weight-edges)) is missing from search results entirely.

**Expected behavior**
Either source of the featured snippet should be present inside the Searx's infobox or it should be first search result.

**Screenshots & Logs**
Google search result:

![google](https://user-images.githubusercontent.com/28824347/187061917-b7019068-35f2-4792-845a-6a3366a072f5.png)

Searx.be search result:
![searx](https://user-images.githubusercontent.com/28824347/187061988-aab4c87a-b46e-40b9-ad3e-62836bb923b1.png)

**Additional context**
Some more keywords for which snippet's source is missing.

| Keyword | Snippet's Source|
| ----------- | ---------------------- |
|[dijkstra's algorithm on negative edge weight cycle](https://searx.be/search?q=dijkstra%27s%20algorithm%20on%20negative%20edge%20weight%20cycle&categories=general)|[1 Negative Edge Weights 2 Bellman-Ford Algorithm](http://web.stanford.edu/class/archive/cs/cs161/cs161.1176/Lectures/CS161Lecture11.5.pdf)|
|[why does dijkstra fail for negative weights](https://searx.be/search?q=why%20does%20dijkstra%20fail%20for%20negative%20weights&categories=general)|[Why does Dijkstra's algorithm fail on negative weights?](https://www.codingninjas.com/codestudio/library/why-does-dijkstra-s-algorithm-fail-on-negative-weights)|

**Comment by unixfox** [comment]
Thank you for the detailed issue report but searx.be doesn't use SearX anymore but instead SearXNG so please report there instead: https://github.com/searxng/searxng/issues
