### ISSUE TITLE
Brave engine (brave only) not working, yields no results.

### ISSUE THREAD

**Issue by Entheologian** [searx/searx#3362]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
Using official version 1.1.0 (latest) on OpenBSD and downloaded via git.

**How did you install Searx?**
Using this how-to: https://www.tumfatig.net/2021/running-the-searx-metasearch-engine-on-openbsd/

**What happened?**
I don't know if it is a bug, but when I select Brave as the only search engine and do a search, it yields nothing and this message:
"Sorry! we didn't find any results. Please use another query or search in more categories."

**How To Reproduce**
Enable only brave engine, then do a search.

**Expected behavior**
Some results would be returned. =)

**Screenshots & Logs**
If needed, I can provide but it's basic.

**Additional context**
Question: Can I change something in settings.yml to resolve this?

**Comment by unixfox** [comment]
Probably related: https://github.com/searxng/searxng/issues/1651

**Comment by allendema** [comment]
Check https://github.com/searx/searx/pull/3361

**Comment by rob4226** [comment]
Yes, see my pull request #3361. You can fix it by making the following change to `settings.yml` under `-name: brave:`

```yaml
 url_xpath: //a[@class="result-header"]/@href
```
