### ISSUE TITLE
[QUESTION] problem with curl not retrieving searx.be search results

### ISSUE THREAD

**Issue by Extr3m4R4710** [searx/searx#3380]
As I mentioned in the title, I am unable to get search results from a searX instance (searx.be) using curl. google seems to be able to search by specifying a cookie, is it possible to get results from searX in this way?

I am developing a Google Dorking automation script for OSINT research, and I am planning to switch its engine from Google to searX. The structure of the shell script is to first check the given base URI (i.e. https://searx.be/search?q=site:$1&categories=general) for verity, and then retrieve the URL or file from the retrieved source using a regular expression.

However, when I test with curl, I get "403 Forbidden". The browser returns normal results, but how can I get the page source from curl?

![Screenshot from 2022-10-07 12-29-36](https://user-images.githubusercontent.com/48596072/194463620-c9ae401d-dc6b-4496-913b-0e422bc709e9.png)

**Comment by unixfox** [comment]
That's expected, searx.be only allow "human" traffic.

If you want to do some scrapping find instances that don't block curl: https://searx.space. there are not a lot because instances don't want bot traffic but some do allow it.

Or easier way just run searx locally.
