### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dalf** [searx/searx#339]
The 0.7.0 version has been released the Feb 3th, almost 4 months ago, 174 commits has been added.
According to http://stats.searx.oe5tpo.com/ most of the searx instance are using the 0.7.0.

I think it's time for a new release ?

I added a [release 0.8.0](https://github.com/asciimoo/searx/milestones/version%200.8.0) that included all the known bugs, and a second one, the [release 0.9.0](https://github.com/asciimoo/searx/milestones/version%200.9.0) that include some "easy" enhancement.

I know that every one is contributing when they can, so this "issue" is more open discussion about release than a real issue.

**Comment by asciimoo** [comment]
Ah, yes, it's time to release! We have plenty of new features since 0.7.0. I'll focus on fixing the remaining bugs, when it's done we can release the 0.8.0.

**Comment by pointhi** [comment]
I would propose also to use the build number inside the version string in the future, to label some changes, which are improving searx noticeable. (Language update, new engines, things like the plugin system,...).

**Comment by Cqoicebordel** [comment]
We are in no hurry :)

I'm planning of tackling the youtube issues next week, and wanted to do the dict.cc and qwant engines in the same time.
Also, one big request I had when I asked "not geeks" to test searx, is to have more info on the prefs. So I was planning of doing a FAQ page, including links from the prefs.

So please, and if you agree, let's wait 2 weeks so I have the chance to do what I planned :)
And if I don't succed, it was only two weeks ;)

Also, I vigorously agree with @pointhi. 
But, build number, or Git id ?

**Comment by pointhi** [comment]
I would propose build number, because the git id is not very meaningful to most people. Furthermore, people who install searx from a fork (like me, because I added some dev-patches) returning another git id than default searx sites which are building from the official repository.

2 weeks are a good deadline. Until then I can probably port the basic spell checker (#190) as plugin (based on suggestions).

**Comment by asciimoo** [comment]
@Cqoicebordel wow, sounds nice!
2-3 weeks are okay.
@pointhi build id is also a good idea, if it's automatically generated =)
What can be the build id if not the last git commit id? Maybe a git hook which counts the commits of the local master and stores it to a file

**Comment by dalf** [comment]
@pointhi +1 for the build id (if automatically generated).
@Cqoicebordel : yes no hurry, like I said, it's only to discuss about it. Anyway, there will be other release (I hope), so no stress. Also, nice idea about the FAQ :)

**Comment by dalf** [comment]
A little experiment : https://gist.github.com/dalf/9e9a6d519350180c4b69

**Comment by Cqoicebordel** [comment]
I'll put it there so we don't forget : we must update the project on transifex before the release, there are a lot of strings not translated in the current version.

**Comment by pointhi** [comment]
Ok, about 3 months ago we thought about version 0.8.0. Probably we can do it in some weeks. There are many new features/changes, and I think there is no release blocker which has to be fixed before 0.8.0.

I updated the translations on transifex so we can merge them in a few days hopefully.

**Comment by asciimoo** [comment]
I agree, i've finished the changelog - we can release tonight if there is no blocking issue

**Comment by Cqoicebordel** [comment]
I wouldn't recommend it.
Yeah, there is no blocking issue, but we are still in the summer holiday time, which means that we can't have a bit of press with this release.
Let's wait one or two weeks to be in september instead.

**Comment by asciimoo** [comment]
mkay

**Comment by asciimoo** [comment]
mkay

**Comment by Cqoicebordel** [comment]
So, tuesday ?

**Comment by asciimoo** [comment]
it would be good to fix #419 before

**Comment by Cqoicebordel** [comment]
Indeed :)

**Comment by Cqoicebordel** [comment]
Yeah !!!
Now, let's flood our social medias ! :D

**Comment by GreenLunar** [comment]
BOOM!

**Comment by dalf** [comment]
Close ?
(and / or new release since the 0.8.1, the google and bing image have been fixed ?)

**Comment by dimqua** [comment]
Please close the issue.
