### ISSUE TITLE
Autocomplete : pressing enter key, when the mouse is on the completion list.

### ISSUE THREAD

**Issue by dalf** [searx/searx#340]
Case : 
- start typing a request
- the autocompletion choices appear
- finish typing what you want
- press enter

Important note : the mouse was above the autocompletion choices

Issue : the sent request is not what has been typed, but the suggestion bellow the mouse.

**Comment by Cqoicebordel** [comment]
I think that is an OS issue here, but I may be wrong.

**Comment by pointhi** [comment]
I think it's an js issue, because we disabled this "feature" in the old autocompletion-js-library. Probably I can fix this issue while completing #259, but it would need some time until this patch is ready.

**Comment by astier** [comment]
I still have this issue. Seaxng seems to have fixed it.
