### ISSUE TITLE
Mobile/android keyboard enter/search key does not trigger search. Instead the search icon needs to be manually clicked.

### ISSUE THREAD

**Issue by advait404** [searx/searx#3419]
**Is your feature request related to a problem? Please describe.**
On mobile, searching through the searx website is a bit tedious, since clicking the 'enter' button does not trigger the search. It requires users to click the 'search' icon.

**Describe the solution you'd like**
Ideally, when editing the search query, pressing enter/search key on the bottom right of the android keyboard will trigger the search, like it does on other search engine like duckduckgo.

**Describe alternatives you've considered**
Other search engines generally do not have this problem. Eg: on duckduckgo, pressing the enter/search key triggers the search.

**Additional context**
the keyboard key I am referring to:
![image](https://user-images.githubusercontent.com/83760070/204542405-223520fd-abaa-4548-8d23-8c5c4a4a5301.png)

**Comment by unixfox** [comment]
See https://github.com/searx/searx/issues/340#issuecomment-940047457

**Comment by advait404** [comment]
@unixfox I am trying this on 
https://searx.be/  but it does not work.

I think its because of the ui layout. it works fine on the Oscar layout, but not on the simple layout.

**Comment by unixfox** [comment]
If it affect the simple layout then you are on the wrong repository, please open an issue on https://github.com/searxng/searxng/

Meanwhile I'm closing this issue because it works fine on my end on both the oscar and the simple theme. Make sure to test on a vanilla browser.
