### ISSUE TITLE
No Bing results for Searx (but for SearxNG)

### ISSUE THREAD

**Issue by juusoohtonen** [searx/searx#3466]
The public instances Searx instances don't seem return any results for Bing but SearxNG instances do. I think the situation has been the same for days or even weeks.

I tried out several searx and searxng instances: https://searx.space/

### Searx

Example Searx instance: https://searx.roflcopter.fr/ (1.1.0-53-c647b55e)
[Bing search in roflcopter.fr](https://searx.roflcopter.fr/search?q=%21bi%20foo&categories=none&language=en-US) gave "Sorry! we didn't find any results."

### SearxNG

Example SearxNG instances: https://northboot.xyz/ (2023.2.4+7320b0c7)
[Bing search in northboot.xyz](https://northboot.xyz/search?q=%21bi+foo&category_general=1&language=en-US&time_range=&safesearch=1&theme=simple) gave a pageful of results.

### Suggestion

Might the fix be included in the [SearxNG commit list](https://github.com/searxng/searxng/commits/master/searx/engines/bing.py)? There are several references to Bing that are not included in [Searx commit list](https://github.com/searx/searx/commits/master/searx/engines/bing.py)
There is a big diff between https://raw.githubusercontent.com/searxng/searxng/master/searx/engines/bing.py and https://raw.githubusercontent.com/searx/searx/master/searx/engines/bing.py

**Comment by glanham-jr** [comment]
@juusoohtonen Should be fixed in the PR - simply adding the Accept header seems to have fixed the issue 😄

**Comment by juusoohtonen** [comment]
@glanham-jr  Might similar fix be needed for DuckDuckGo?
There are no results from searx 1.1.0-53-c647b55e: https://searx.roflcopter.fr/search?q=%21duckduckgo%20foobar&categories=none&language=en-US
However, there are results for searxNG 2023.2.15+52f6bc74: https://northboot.xyz/search?q=%21duckduckgo+foobar&category_general=1&language=en-US&time_range=&safesearch=1&theme=simple

I haven't checked other search engines...

**Comment by glanham-jr** [comment]
@juusoohtonen Lets move the convo to this [discussion](https://github.com/searx/searx/discussions/3476), as we may want to triage + discuss each engine not working, and see what all may be affected.

**Comment by br4nnigan** [comment]
I noticed something odd about this. Not sure if you can reproduce it, but try this:

- search for lets say "foo" in your searx instance using bing engine - you get no results (bing actually returns a "sorry but there were no results" page, I checked it)
- now open a tab on your local pc browser and search on bing.com "language:DE foo" (replace language with the selected language in your searx, this is actually what searx will send to bing)
- now repeat step 1, and magically you get results

Another thing I noticed is that the bing in my local pc browser is set to dutch language (I'm German), which is where my server is located (NL). Isn't this strange?

the fix with the accept header doesn't work for me :(

**Comment by br4nnigan** [comment]
The fix now actually works, **but only if you also remove the user agent header**
