### ISSUE TITLE
Add Aria recommandations changes

### ISSUE THREAD

**Issue by Cqoicebordel** [searx/searx#350]
Let's add a few changes to improve accessibility.

EDIT by @kvch:

Result from the accessibility test by the Accessibility Foundation for the Oscar theme:

- [x] **Non-text content**
  - [x] remove redundant alt texts from image results in info box
  - [x] remove redundant alt texts from images in Videos, Social Media and Music
- [x] **Info and relationship**
  - [x] do not use `h1` element for the logo
  - [x] indicate visually active tab programmatically on the page Preferences
  - [x] `select` and `input` tags are not connected programmatically on the page Preferences
  - [x] use `scope="col"` for headers to describe properties in the Engines table
  - [x] use `scope="row"` for headers for the name of the engines in the Engines table
- [ ] **Use of colour**
  - [ ] links should be distinguished from other text not only by colour (e.g. underline)
  - [x] indicate too high max time by e.g. icon not only by colour
- [x] **Contrast**
  - [x] 4.5:1 contrast value for normal text
  - [x] 4.5:1 contrast value for white texts on green buttons such as ‘Wikipedia (en)’
  - [x] 4.5:1 contrast value for green URLs below each result
  - [x] 4.5:1 contrast value for engine names (grey texts next to those links, such as ‘google scholar’)
  - [x] 4.5:1 contrast value for focused tab on preferences and blue links
  - [x] 4.5:1 contrast value for text on Save button
  - [x] 4.5:1 contrast value for label "supported"
  - [x] 4.5:1 contrast value for label "not supported"
  - [x] 4.5:1 contrast value for grey text and slightly grey background on Answerers page
- [x] **Resize text**
  - [x] maximum-scale in meta tag have to be at least 2.0
- [x] **Non-text contrast**
  - [x] 3:1 contrast value for search input border
  - [x] 3:1 contrast value for borders of the input fields for period and language in Advanced search
  - [x] 3:1 contrast value for `select` on Preferences under General section
  - [x] 3:1 contrast value for focused tab on Preferences
  - [x] 3:1 contrast value for Allow engines for both on and off state
- [x] **Keyboard**
  - [x] make "Advanced settings" openable and usable with keyboard
  - [x] switch between different tabs on Preferences with keyboard
  - [x] toggle on-off buttons with keyboard for Engines and Plugins
- [x] **Bypass blocks**
- [x] **Link purpose**
  - [x] add label to proxied and cached to show what those are
  - [x] Files >> magnet link (add label)
  - [x] Map >> show map, show details (add label)
  - [x] Videos >> show video (add label)
- [x] **Language of page**
  - [x] when language of the UI is changed, change `lang` as well
- [ ] **Error identification**
  - [ ] provide more info about error when search query is empty
- [x] **Labels and instructions**
  - [x] add label/info to Time range search and Language
- [x] **Parsing**
  - [x] remove unnsecessary `</small>`
  - [x] remove `overflow:none` as `none` is invalid
  - [x] check page with W3C validator
- [x] **Name, role, value**

**Comment by asciimoo** [comment]
Most of the issues are fixed, the remaining ones are only recommended and as I see the majority of other sites don't implement them, so I'm closing this issue. Feel free to reopen if you think anything else should be implemented from the above list.
