### ISSUE TITLE
Now 0 engines are working ...

### ISSUE THREAD

**Issue by rowie** [searx/searx#3544]
Fehler! Die folgenden Suchmaschinen können die Ergebnisse nicht empfangen:

duckduckgo ( [Ausgesetzt: Zugriff verweigert](https://search.rowie.at/stats?engine=duckduckgo) )

google ( [Ausgesetzt: Zugriff verweigert](https://search.rowie.at/stats?engine=google) )

qwant ( [Server-API-Fehler](https://search.rowie.at/stats?engine=qwant) )

startpage ( [Ausgesetzt: CAPTCHA](https://search.rowie.at/stats?engine=startpage) )

**Comment by rowie** [comment]
latest version ... configured as described

**Comment by unixfox** [comment]
Wrong repository, this is searx repository not searxng.
