### ISSUE TITLE
Disabled search engines don't appear as blocked in settings

### ISSUE THREAD

**Issue by Cqoicebordel** [searx/searx#358]
I don't know how it must work really, but I would guess that every disabled engines from settings.yml should appear as blocked in the user settings, so he can activate them if he wish to.

Does it seem a correct approach to you ?

**Comment by dalf** [comment]
I agree

**Comment by Cqoicebordel** [comment]
Sorry for this one, it seems that having olds cookies can mess with the blocked/disabled engines. Reseted the settings and everything worked as it should.
Closing it.

**Comment by leepfrog-ger** [comment]
This is currently happening for me too.

Engines that are disabled in settings.yml are showing up as enabled (and giving results) even when using an incognito session and/or clearing all cookies.
