### ISSUE TITLE
currency engine : regex

### ISSUE THREAD

**Issue by dalf** [searx/searx#359]
https://github.com/asciimoo/searx/blob/master/searx/engines/currency_convert.py#L12
the regex should be something like 

```
^\W*(\d+(?:\.\d+)?)\W+([^.0-9].+)\W+in?\W*([^\.]+)\W*$
```

some `\W*` are replaced by `\W+`, may be a better one could be found.

fro now,  the currency engine catches `3d dinosaures` : 
http://searx.me/?q=3d+dinosaures&category_general=on

**Comment by Cqoicebordel** [comment]
Lol
Maybe, an easier way would be to include the spaces around 'in' in the regex.

**Comment by asciimoo** [comment]
fixed: #362
