### ISSUE TITLE
make searx installation work in subfolder

### ISSUE THREAD

**Issue by ghost** [searx/searx#366]
Sorry, I'm a complete novice in these matters but I think I've carefully folllowed your instructions.
I cannot get searx to work from a **subfolder** of my domain. It will run fine in the root folder of any (sub)domain but not from a subfolder (which is what I need).
Here's what I did:

In the _searx/searx/settings.yml_ I set

`base_url https://mydomain.com/search/` 

and inside the _subfolder_ named _search_ I have this _htaccess_

```
RewriteEngine On   
RewriteBase /   
RewriteRule ^(.*) http://127.0.0.1:58630/$1 [P]   
```

(also tried it without the RewriteBase)

This is not working in the subfolder. 
Files from the static folder are not loaded. And if I hit search anyway it defaults to my root folder and gives an error (there's nothing in there). 
I think it's a path problem, maybe it's still treating this as an installation in a root folder instead of a subfolder. 

I should add that this is running in a shared web hosting environment. Therefore I'm not allowed to make changes to Apache or nginx configuration settings (if they were necessary).

Could you _please_ tell me what I need to do to make searx work from a _sub_folder? After many hours and days I've run out of ideas. If there is a way, maybe you could add a line to the installation instructions for other beginners.
Thank you so much.

**Comment by asciimoo** [comment]
With a small fix (6ef7c3276c308ba12b80e22068de422247fdb4b9) searx now can be used behind a reverse proxy. Example apache configuration: http://ubuntuguide.org/wiki/Apache2_reverse_proxies

**Comment by asciimoo** [comment]
@autrui could you verify the fix?

**Comment by ghost** [comment]
Unfortunately, I can't. My web hosting company told me that I couldn't make searx work in a subfolder because some of the config changes required clash with the way their servers are set up. Probably because there are multiple users on one server. 
Sorry. Hope someone else can verify this. Thank you for your help!!!
