### ISSUE TITLE
defaut search language

### ISSUE THREAD

**Issue by Eldouf** [searx/searx#373]
![capture d ecran 2015-06-17 a 16 42 09](https://cloud.githubusercontent.com/assets/12937785/8210037/70f1614e-1510-11e5-8ec0-cb8855e7409a.png)
Hi,
When i set up searx 'defaut search language' to "french", this setting remains until i restart 'Firefox' (wich i only use). Then the setting box goes back on the "automatic" field again, which even if i set the 'interface language' box to "french" is in english by defaut.
Any ideas to fix this ? thx.

**Comment by Cqoicebordel** [comment]
Those settings are stored in cookies. So if you use an extension or a setting in Fx that deletes automatically thoses cookies when you close the browser, that's the cause.

Also if you use private browsing.

**Comment by cy8aer** [comment]
Usage problem: Did you really "save" the settings?

**Comment by Santobert** [comment]
Is there a way to store this setting in the settings.yml file?
Thank you

**Comment by gsantner** [comment]
@Eldouf 
searx/settings.yml
```
search:
    safe_search : 0 # Filter results. 0: None, 1: Moderate, 2: Strict
    autocomplete : "" # Existing autocomplete backends: "dbpedia", "duckduckgo", "google", "startpage", "wikipedia" - leave blank to turn it off by default
    language : "fr"
```

or by using the GET variant:
https://DOMAIN/searx/?q=QUERY&category_general=on&time_range=&language=LANG
