### ISSUE TITLE
quickly change language like in Duckduckgo...

### ISSUE THREAD

**Issue by ghost** [searx/searx#376]
should be a nice improvement

**Comment by dalf** [comment]
+1

**Comment by Cqoicebordel** [comment]
I'm not familiar enough with DDG. What does it means ?
We can switch language in the settings pretty quickly, isn't that enough ?

**Comment by dalf** [comment]
This option : 
![ddg](https://cloud.githubusercontent.com/assets/1594191/8354042/04a5e9c0-1b45-11e5-9f19-8191b6cc631e.jpg)

It's about quick, but also to make it obvious : since it's part of the search parameters, IMHO it should be display.

**Comment by Cqoicebordel** [comment]
So, +1 indeed.
It could be done with a few other button to increase specificity of the search, not related to the settings.

**Comment by dalf** [comment]
Off topic : we could even replace part of preferences page by "Save as default preference" button on the main page. This button could save the language / region / defaults categories.

**Comment by asciimoo** [comment]
+1 to all

**Comment by dalf** [comment]
implemented with search_on_category_select plugin : 
https://github.com/asciimoo/searx/blob/master/searx/static/plugins/js/search_on_category_select.js
