### ISSUE TITLE
youtube engine and cookies

### ISSUE THREAD

**Issue by dalf** [searx/searx#380]
As soon as preference cookies are set, the youtube engine is ignored, even with the "!youtube" bang.
If the cookies are cleared, the youtube engine work as excepted.

**Comment by asciimoo** [comment]
It works for me with `!youtube` as expected even if i disable youtube engine in the preferences

**Comment by dalf** [comment]
I can't reproduce the bug...
But when I wrote this issue, searx.me, my instance, and a local instance had the problem.
Closing for now...

**Comment by upskaling** [comment]
if you put the french language research, the bug occurs.
whereas if you leave it in automatic its work, anyway.
