### ISSUE TITLE
Small license issues

### ISSUE THREAD

**Issue by rrooij** [searx/searx#382]
First of all, I think it is great that this software is licensed AGPLv3+. It is an awesome project and we really need a free as in freedom search engine, which also contains server code available to the users.

There are however some small license issues. Those are not major problems, but it would be nice to have them solved.
1. The software doesn't include a full copy of the license. A full copy of the license can be retrieved here:
   https://www.gnu.org/licenses/agpl-3.0.txt
2. The full source code of the minified JS scripts aren't available in the repositories. As far as I know, it should be according to the AGPLv3+ license.

This is what I could find so far. I'm not an expert in licensing issues, so feel free to correct me.

And thanks for the awesome software!

**Comment by asciimoo** [comment]
Thanks, the first note fixed. I'm not sure about the second one, could you please point out which section of the AGPLv3+ describes it?

**Comment by rrooij** [comment]
@asciimoo Cool!

I'm also not sure about the second one. It'd be of help if someone from GNU could help. I interpreted this way because of section 6, however, I'm no expert on this matter.

**Comment by Pastaf** [comment]
In section 1, "The 'source code' for a work means the preferred form of the work
for making modifications to it", and as the AGPL demands release of source code, the form in which you choose to edit it must be provided, not the minified version.

**Comment by vyp** [comment]
IANAL so I could very well be wrong, but it's my understanding that free software in general has to distribute the source code in form the author originally writes it in. Meaning minified code does not fulfill that (even if it can be unminified).

But looking at the JS scripts, all the minified ones seem to be third party libraries (and all the ones that are searx specific seem to be unminified). If this is correct and the minified third party scripts are _unmodified_ from the original ones, then I think it should be okay if there are just _links_ to the original source code libraries themselves. But I'm not even sure if that is _needed_ by the license, just it would probably clarify things/solve this issue.

That can still be a pita though, so maybe it's worth looking into something like [bower](http://bower.io/) if that really is an issue for the license.
