### ISSUE TITLE
Filter search results by date

### ISSUE THREAD

**Issue by Francisco-Ordas** [searx/searx#383]
In Google Search, I often use date criteria to filter results. For me, it would it's a key feature to replace Google Search by Searx.

**Comment by dalf** [comment]
Technical note : 
- a way in searx to specify the date criteria (from the user point of view and from the code point of view)
- when a date criteria is asked, searx must not use engines that don't support this criteria
- implements for different search engine this criteria

**Comment by asciimoo** [comment]
closing, see #634
