### ISSUE TITLE
infobox: date of birth

### ISSUE THREAD

**Issue by ghost** [searx/searx#387]
How is the info for this box section pulled in?

I find
Date of birth   07/01/15
highly inaccurate for Aidan Baker (canadian musician) and others.

**Comment by dalf** [comment]
The date of birth comes from wikidata and there is a bug when the wikidata date contains only a year.

**Comment by ghost** [comment]
https://en.wikipedia.org/wiki/Aidan_Baker
"Born   1974/1975[1] "
oh, I see.

**Comment by dalf** [comment]
For information, it's wikidata not wikipedia : 
https://www.wikidata.org/wiki/Q403873

The lines of code that should be fixed (starting from, including the get_time function) : 
https://github.com/asciimoo/searx/blob/master/searx/engines/wikidata.py#L167
