### ISSUE TITLE
Rewriting results with  "www.***" to "http://www.***

### ISSUE THREAD

**Issue by pointhi** [searx/searx#390]
Today, I got a result only with `www.***`, and my browser tried to open it as subpath from my search-engine: `https://searx.oe5tpo.com/www.***`. We should add a http to those strings to prevent such behaviour.

**Comment by ghost** [comment]
I can confirm this on several occasions.

**Comment by rascul** [comment]
I've been seeing this also, a page reload seems to "fix" it.
