### ISSUE TITLE
Fast answers with search suggestion and autocomplete mechanisms

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#392]
When user type a mathematical operation (maybe even free-text) into the searchbar, the result will show in the first line of the dropdown menu, of web interface of searx or a web browser.

See
http://kplug-list.kernel-panic.narkive.com/wa7cLdWb/firefox-instant-calculator
https://support.mozilla.org/en-US/questions/928747
http://blogoscoped.com/forum/68013.html

This is a feature that should be disabled by default, or be provided by a plugin or might not, at all, be fit to searx.  It appears, to me, that a plugin would be the best way to implement and examine such low priority feature.

**Comment by GreenLunar** [comment]
You can start by user typing _ip_ and the IP address of a user would be displayed in search suggestions.

**Comment by unixfox** [comment]
Search suggestions are implemented.

**Comment by xeruf** [comment]
Simple things such as `1+5` are not evaluated though - maybe ddg instant answers as mentioned in #60 would help
