### ISSUE TITLE
[ENGINE] iZSearch

### ISSUE THREAD

**Issue by bitwave** [searx/searx#394]
I found a new search engine: http://izsearch.com/

see http://www.businesswire.com/news/home/20150713005476/en/Search-Engine-Startup-iZSearch-Inc.%E2%84%A2-Announced-Public#.VaPwPflVhBc for more information

Maybe it's possible to integrate it into searx

**Comment by GreenLunar** [comment]
Change label to "engine request"

https://github.com/asciimoo/searx/issues?q=is%3Aopen+label%3A%22engine+request%22

**Comment by GreenLunar** [comment]
Ping Ping

Rename label to https://github.com/asciimoo/searx/issues?q=is%3Aissue+is%3Aopen+label%3A%22engine+request%22

**Comment by unixfox** [comment]
The website http://izsearch.com/ doesn't respond anymore, closing the issue.
