### ISSUE TITLE
how to change default per-user values?

### ISSUE THREAD

**Issue by leepfrog-ger** [searx/searx#396]
Hi,

thanks for this great project!

I'd like to change some default values for the users (specifically: theme, safe search and auto correct), however I was not able to figure out where I need to do this.

Can you point me to the right direction please?

**Comment by asciimoo** [comment]
ohi, i've extended the settings file with the missing options, check out the latest version

**Comment by leepfrog-ger** [comment]
Thanks, will test this later!
