### ISSUE TITLE
configuration option for bind address in settings.yml

### ISSUE THREAD

**Issue by leepfrog-ger** [searx/searx#397]
Hi,

I am running searx in a private network and I'm publishing it through an external (=not on the local machine) reverse proxy.
This means that the default listeing address of 127.0.0.1 does not work for me. Installing apache/nginx as reverse proxy on the machine itself is unnecessary overhead.

As a workaround I've modified the webapp.py in the following way:

```
app.run(
    debug=settings['server']['debug'],
    use_debugger=settings['server']['debug'],
    port=settings['server']['port'],
    host='0.0.0.0'
)
```

This works for now however as this is I'd like to see the "bind address" as configuration option (defaulting to 127.0.0.1) in the settings.yml as this is not an uncommon scenario

**Comment by jpope777** [comment]
+1
