### ISSUE TITLE
HTTP Header Send

### ISSUE THREAD

**Issue by magaretha42** [searx/searx#399]
Is there a way to send information in the HTTP header, for instance a username and password for basic access authentication, during a query on a particular engine?

I've been thinking of using searx with some servers on my intranet that require a username and password to access their API (obviously I will be using HTTPS).

**Comment by dalf** [comment]
Can you use Apache or Nginx as a reverse proxy ?
This would solve the issue.

**Comment by magaretha42** [comment]
That might be a workable idea, but I would rather it be on a per user basis.

I was planning on coding to interface with other servers that have internal search with API access so that I can use the Access Control functionality in those applications to manage user data access (all handled on their end, I just need to send them the user/password when I run a request, .

Can plugins modify the HTTP Request (specifically to send data)?  Perhaps when run on pre_search?

**Comment by asciimoo** [comment]
@magaretha42 universally not yet, but searx can be extended easily with the required hook to have access to the desired state. The hard part is the per user customization.

**Comment by unixfox** [comment]
You can restrict the engines using an access token: https://searx.github.io/searx/blog/private-engines.html
