### ISSUE TITLE
Q: which instances of searx anonymize IPs?

### ISSUE THREAD

**Issue by ghost** [searx/searx#400]
Since this is not possible to figure out on my end, can someone tell me which searx instances anonymize IPs in logs by default?  
I am writing a script I want to either provide the option to search on these instances by default and add the rest to a list selection the user can make.  
As far as I know this can't be figured without information given by the admins.  
Could the stats page, or the one listing the http|https instances, be improved by adding something like
"Anonymized IPs: [YES/NO]" ?

**Comment by dalf** [comment]
Easy part, make sure that 
- searx log (uwsgi) are disabled even in case of error 
- apache or nginx as reverse proxy : anonymize IP.

For this part you have to rely / trust what the admins say or skills (they can think that everything is ok and forget something).

Note : even this is unlikely to happen, the server can be configured to anonymize IP, and a mistake can "restore" real IP (upgrade or something like that).

Another point : internet provider can log IP (according to the laws of country). It can be your ISP or the server ISP.

Side note : make sure that all requests from the searx instance are using https connection. Otherwise, someone can eavesdrop the outgoing requests. Same : you have to trust that admins have updated their searx instances.

**Comment by ghost** [comment]
Thanks,

yes i am aware of the technical how-to and the points of failure.
The script in question is just an elvi for surfraw.
It's just the same conditions for accessing those instances from the open web or tor exit nodes directly with web browsers.

**Comment by ghost** [comment]
My comment might have been too unspecific:
I am aware of the things you mentioned, but something which points out
- this server does keep logs
- this server doesn't keep logs
- this server anonymizes IPs

and so forth, like in the TIER2 server list of the opennic project might help get additional transparency.

**Comment by xinomilo** [comment]
+1

**Comment by asciimoo** [comment]
The problem with these info chunks is that you can't be sure about the correctness of them..

**Comment by Cqoicebordel** [comment]
Maybe this is stupid, but couldn't we include a PHP page that lists the options of the server, so we can know how it is configured ? Like a phpinfo() page, but only with what we need ?

**Comment by asciimoo** [comment]
Still, it can be replaced with a static page

**Comment by ghost** [comment]
Before we end up in a long discussion which leads to "trust no one but yourself"...
What would be more effective in my opinion, would be:
- thinking about a validation process which could provide at least a basic level of trust
  or
- do it like opennic (see: http://wiki.opennicproject.org/Tier2) and trust the statements of people running the instances. Eventually with a discussion on individual instances if it turns out the admin does indeed do thing X and wrote down that they do not do thing X.

**Comment by xinomilo** [comment]
have you noticed the Self Informations plugin? you can check which searx instances provide your real ip and which ones dont. just search for "ip" in any searx instance. could be a way to check, although maybe not be 100% reliable and certainly doesnt prove anything about server logs.

**Comment by ghost** [comment]
xinomilo, how is providing a lookup on IP related to logs and other things?
for example: connecting to the .onion of my searx instance and asking for "ip" gives 127.0.0.1 (like it is intended to with tor), "what is my ip" gives something else (in onion and in clearnet) and simply "ip" in the clearnet address gives your real ip. that's no proof of $instance log policy.
*keep in mind this was tested on a system I normally don't use/have not configured yet: so no dnscrypt, no local dns server running, no webrtc leakage fix in the clearnet browser.

asciimoo, what about if we come up with an undefined (because I have no specific idea right now) way of providing verification or at least the possibility for instance admins to state further details in an overview, an overview which is located in a public place and not the instances server?

**Comment by xinomilo** [comment]
as i said it doesnt say anything about server logs. thats something only server admins know about. but if someone anonymizes ips in web server, this is visible on searx (not 100% reliable as stated). eg, my instane displays 127.0.0.1 ip for every guest, other instances i checked provide server ip for every guest (= replacing real ips with server ip) and others provide real ips. so its something to check... and if you're a server admin there are a lot of ways to implement this.

**Comment by ghost** [comment]
Okay, this doesn't sound like what I had in mind, but wouldn't it be possible to
set server-ip and :: / 127.0.0.1 and similar IPs, then let an external script check the IP and see which value gets returned (the way searching for "IP"/"what is my ip" does now) and maybe provide a way to display the IP, so this could be a way to display this part?
I still think a list like wiki.opennicproject.org/Tier2 would be okay, giving a bit more details then the current list.
Possible fields: instance name, URL(s), certificate check link, State, Country, Anon Logs(yes,no,other), Log Comment, Other Comment

If this is a format some of you are generally okay with, I will create a wiki page for this tomorrow.

sidenote:
There are too many factors to rule out to say "this is 100% pseudo anonymous!", for example VPS, consider all VPS compromised, but telling this to people who just want to search things is too much.
I personally am thinking of ways to separate website services + everything else, and DNS servers I run.

**Comment by xinomilo** [comment]
I'm ok with the wiki page. i'd suggest adding a contact field(s) such as contact_email (+ gpg_key), like in tor relays. 
Anon logs could be specified by the instance admin like : 1) no logs (/dev/null) 2) anon_ip logs 3) full detail logs. with comments as you suggest to clarify special setups.
and maybe hidden services should be stated as different instances. not along with the public ones as it is now.

**Comment by unixfox** [comment]
It's a tough question because we don't know the configuration of each existing public instances but if you care about your IP you should use a Searx instance hosted on Tor. A list is available here: https://searx.space
