### ISSUE TITLE
Add theme of search.jpope.org

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#401]
https://code.jpope.org/jpope/search.jpope.org/src/search.jpope.org/searx/templates/jpope

EDIT: I knew I have seen that theme before, MediaGoblin http://media.jpope.org/

**Comment by jpope777** [comment]
I can totally submit a PR for the theme. :)

Should note, that theme is also included in Mediagoblin as well (see https://media.jpope.org/ for example).

**Comment by GreenLunar** [comment]
Great!

**Comment by GreenLunar** [comment]
I did not know of the ability to incorporate GitHub comments into DIASPORA\* https://pod.jpope.org/posts/669100

**Comment by jpope777** [comment]
@GreenLunar The comments are embedded into D\* via the [opengraph metadata](http://ogp.me/).

**Comment by GreenLunar** [comment]
I think you should set the logo width to 100% on smaller screens, such as cellular phones, and add the transparent top bar, similarly to Sandy Seventies Speedboat theme of Mediagoblin, and no top of it add RSS link and other links of About, Home (may be in a form of the searx logo), and Preferences.

**Comment by unixfox** [comment]
Feel free to open a PR for adding your theme but meanwhile we are sticking with the current themes.
