### ISSUE TITLE
Spam filter

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#407]
Ability to hide/skip links to websites considered as spam.

When querying for person name, I am getting roughly 50% results of websites that offer me to get more information on that person, these spam sites are either a _scam_, _illegal_ or just provide the same queries data that anyone can obtain from Ministry Of Internal Affairs, for an _expropriated_ price.

When spam results are detected (and are hidden), Searx would notify that spam results were detected and it would offer to display these results by a press of a button.

**Comment by GreenLunar** [comment]
This may be used to filter spam and unwanted results; I, for example, am not interested to see results from mostly low-class and mostly satirical websites, such as *Urban Dictionary* and *Uncyclopedia*.

**Comment by GreenLunar** [comment]
First comment has been edited.

- When spam results are detected, Searx would notify that spam results have been detected and would offer to hide these results by a press of a button.

+ When spam results are detected, Searx would notify that spam results have been detected and would offer to display these results by a press of a button.

**Comment by Cqoicebordel** [comment]
I think it would be dangerous to do that on the whole searx plateform, but a plugin allowing the user to blacklist some URL could be feasible.

**Comment by GreenLunar** [comment]
Agreed.

**Comment by ibrokemypie** [comment]
+1 for plugin

**Comment by 1xPdd** [comment]
+1

I've always wanted to blacklist sites from search results.

**Comment by GreenLunar** [comment]
Similarly to [Ahmia](https://github.com/ahmia/search), I suggest to make a [list of check-sums](https://ahmia.fi/blacklist), so that blacklisted websites would not be promoted by searx.

**Comment by Quix0r** [comment]
On [my instance](https://searx.mxchange.org) I got image results always with Simpson family. Example: "Kakamega Sheywe Hotel" has nothing to do with that, yet still images from frinkiac are included containing said cartoon.

**Comment by Quix0r** [comment]
@GreenLunar Please no global (committed) blacklist, let the individual administrator decide which site should be excluded. Otherwise this asks for DMCA/censorship requests on searx it self.

**Comment by GreenLunar** [comment]
Just so you all know, I'm against censorship of any type.

@Quix0r This is a feature that intends to ease on users to make research tasks with searx. Seeing links to adult-contents or vain-marketing results might turn off users.

We can enable this feature by default and place a big noticeable message that user can turn off the filter.

**Comment by Quix0r** [comment]
I found that frinkiac is a search engine in searx. I can just disable it. Thank you for your feedback. :-)

And filtering out specific domains is instance-based not global and can be exposed and controlled to/by the user:

1. Fully exposed filter/block list
2. Only an indicator that filtering/blocking of domains is active
3. Can be turned off by user (cookie-based setting)

**Comment by unixfox** [comment]
Closing in favor of https://github.com/searx/searx/issues/2001
