### ISSUE TITLE
ipv6 compalibity of engines

### ISSUE THREAD

**Issue by pointhi** [searx/searx#412]
I have enabled some time ago one of my ipv6 adresses as source_ip, which resulted in some errors beause not all engines are supporting ipv6 yet.

I think we should add a `ipv6_ready = True` to ipv6 ready search engines, and changing the ConnectionPool in a way to disable ipv6 addresses when making a request with an ipv4 only engine.

**Comment by Cqoicebordel** [comment]
Shouldn't it be done at DNS level ?
If the DNS return an AAAA response, it has ipv6, if only A, only ipv4. Which means that if we limit ourselves to the domain names (and not their IP adresses), we should be fine.
Or am I wrong ?

**Comment by pointhi** [comment]
Yes, theroretical using DNS should be fine.

**Comment by unixfox** [comment]
I don't understand why is this issue still open, I don't get it why we should add a `ìpv6_ready` for filtering the engines? I mean, Searx is working perfectly with IPv6 and also works perfectly in an IPv6 only environment (an environment where IPv4 is disabled).

Even if not all the engines are supporting IPv6 there is a solution for that which is called [NAT64](https://en.wikipedia.org/wiki/IPv6_transition_mechanism#NAT64) and [DNS64](https://en.wikipedia.org/wiki/IPv6_transition_mechanism#DNS64), basically this translate an IPv4 address to an IPv6 address. Nowadays it's commonly deployed in IPv6 only environment (I personally deployed that on my network) and a lot of mobile carriers also deployed this technology, in fact its deployment is increasing as less IPv4 public addresses are available.

**Comment by asciimoo** [comment]
@unixfox thanks for the detailed reply. I think we can close this one. Feel free to reopen in case it still has significance.
