### ISSUE TITLE
general question, themes

### ISSUE THREAD

**Issue by ghost** [searx/searx#420]
My question is, what are the exact steps to get searx to read and accept a theme?
I tried copying and changing paths in the oscar theme, but it did not really work.

Maybe this could be added to the wiki.

**Comment by pointhi** [comment]
It's very simple. You have to copy the theme folders which are contained in `/searx/templates` and `searx/static/themes`. Afterwards, searx should automatically detect the new theme.

**Comment by Cqoicebordel** [comment]
And rename the folders to you name theme. It's the folder name that searx detect and is used as name.

Also, modifying a theme doesn't need a restart of searx, but adding one does, so don't forget to restart it after the copy :)

**Comment by ghost** [comment]
Weird, i tried this approach earlier and it did not work.
I copied oscar to oscar-$myname and did some changes without it appearing when I restarted searx.

**Comment by pointhi** [comment]
have you changed the used theme in the web interface? does the new menue entry appear in the web interface?

**Comment by ghost** [comment]
The new menu entry does not appear in the webinterface after restart.
So what I did so far was copying '/searx/templates/oscar' to '/searx/templates/libertad' and 'searx/static/themes/oscar' the same thing, edited all references to the files which pointed to oscar to point to libertad/ to play around with theming.

**Comment by ghost** [comment]
Is there any further information I could post to debug this situation?

**Comment by pointhi** [comment]
- try to delete/rename a theme (is it disapearing in the menue?)
- use a theme name without special characters (like `-`)

**Comment by ghost** [comment]
ls -al /usr/local/searx/searx/templates
total 28
drwxr-sr-x 7 searx searx 4096 Sep  7 19:48 .
drwxr-sr-x 9 searx searx 4096 Sep  7 20:03 ..
drwxr-sr-x 3 searx searx 4096 Sep  1 19:02 courgette
drwxr-sr-x 3 searx searx 4096 Sep  1 19:02 default
drwxr-sr-x 4 searx searx 4096 Sep  7 20:36 libertad
drwxr-sr-x 4 searx searx 4096 Sep  1 19:02 oscar
drwxr-sr-x 3 searx searx 4096 Jun 17 22:41 pix-art

looks like this at the moment, so no special chars, pix-art has "-" as well, but i'm trying to temporarily remove one of the themes now.

**Comment by ghost** [comment]
So this is weird. I move the pix-art outside of /searx/ root, and I can stil access it after restart of searx.
git status:
        deleted:    searx/static/themes/pix-art/css/style.css
        deleted:    searx/static/themes/pix-art/img/favicon.png
        deleted:    searx/static/themes/pix-art/img/preference-icon-pixel.png
        deleted:    searx/static/themes/pix-art/img/search-icon-pixel.png
        deleted:    searx/static/themes/pix-art/img/searx-pixel-small.png
etc

**Comment by ghost** [comment]
Cleared the cache of the webbrowser, still getting funky results under 'settings > theme'

**Comment by pointhi** [comment]
probably you are working on the wrong searx project.

**Comment by ghost** [comment]
i am not sure.
I branched searx recently. Maybe I dive into that and see how to fix things. Thanks for your help anyway.

**Comment by ghost** [comment]
I ended up with the need to nuke the searx instance, even after hard reset,
but now I am left with: https://ptpb.pw/v7D3 and I wonder why, because it worked before.

**Comment by Cqoicebordel** [comment]
It looks like an issue with your settings.yml file.

As for the "restarting searx" how do you do it ? Do you restart just apache ? Or uwsgi too ?
Or do you run searx by running it directly using the command line ?

**Comment by ghost** [comment]
this was run directly as the user searx runs as, in the python virtualenv.
restarting involved stop nginx, stop uwsgi, start nginx start uwsgi

I could paste the settings.yml (minus the secret_key?)

**Comment by ghost** [comment]
well, minus the local modifications, it looks similar to this: https://github.com/krosos/searx/blob/libertad/searx/settings.yml
and hasn't changed much locally, could be reset though tomorrow:  https://ptpb.pw/x1Dp

**Comment by Cqoicebordel** [comment]
Ok, I think the whole thing is an issue with virtualenv. If you followed the wiki to install searx, virtualenv copied the whole repository in its virtualenv folder. Which means that every modification you made at the root of the repository (something like /usr/local/searx) weren't visible in your instance of searx, because it didn't look in that folder, but looked in the virtualenv folder (something like /usr/local/searx/searx-ve/lib/python2.7/site-packages/searx-0.7.0-py2.7.egg/searx/)

If you didn't make too much change, I recommand that you scrape the whole thing, to start from fresh.
And before deploying using nginx, uwsgi, virtualenv etc., if you have some devs to do, you should try to just run in the searx folder `python searx/webapp.py`. It will run an instance of searx following the settings (using the port number in the settings). With that, you can start, kill, restart searx with ease with that. And it will give you some more info if you activate the debug mode in the settings.

**Comment by ghost** [comment]
thanks for the tip with the virtualenv, i think it was just too late yesterday for my brain to work okay. It is solved.
