### ISSUE TITLE
rewrite 500px to api

### ISSUE THREAD

**Issue by pointhi** [searx/searx#421]
It seems 500px has changed the website, and the simplest way to access the data would be using the api: https://github.com/500px/api-documentation

We should deactivate the engine until a rewrite is done.

**Comment by Cqoicebordel** [comment]
Ok I'll do it, probably tonight.

But using the API will mean having an API key. So first, I'll fix the non-API engine, and next, provide a new APIable one.

**Comment by pointhi** [comment]
What I found out the search now is using the api. Without API-Key no search

**Comment by Cqoicebordel** [comment]
Yep. But it means that we can use 500px own key to request the API.
In that case, `sdk_key=b68e60cff4c929bedea36ca978830c5caca790c3` :D

So I'll build an engine that is based on the API, but can work without a key, using 500px key.

But it would be useful to look at it, to know if that key get revoked a lot, or change every day, or just, is stable.

**Comment by asciimoo** [comment]
onice =)
@Cqoicebordel  where did you found it?
I rewrote the engine with the `sdk_key` and it works fine

**Comment by Cqoicebordel** [comment]
Oh, too fast !
You didn't commit it ?

I found it in a cookie. I wasn't logged or anything, and in a new profile of the browser, so, nothing personnal to my account.

**Comment by asciimoo** [comment]
cool, there's only one issue: the results are watermarked by 500px, i don't know why - yet.

**Comment by Cqoicebordel** [comment]
Hum, weird. No idea.

**Comment by asciimoo** [comment]
there are two types of urls:
- https://drscdn.500px.org/photo/71951633/m%3D2048_k%3D1_a%3D1/2cbfd85f1131b508cc4d654c8f869da6 (watermarked, comes from searx using the sdk_key)
- https://drscdn.500px.org/photo/71951633/m%3D2048/4969ea5fb32b23b9cb13fc3ba5938835 (comes from 500px.com)

seems, there is connection between the `k=1_a=1` part and the hash

**Comment by Cqoicebordel** [comment]
What requests do you do to get those ?
Just to be sure we are talking about the same thing...

**Comment by asciimoo** [comment]
https://github.com/asciimoo/searx/commit/a58944892851d1de8e2b060318b925bf7347508f

**Comment by Cqoicebordel** [comment]
Hum, I have no idea.
I tried with every cookie I had, but nothing. There is a callback present in one cookie, that could be a clue. But I won't look into it until tomorrow.

In the mean time, having the engine would be good, even with watermark, they still can go to the website to get the full image.

Also, from https://github.com/500px/api-documentation/blob/master/basics/formats_and_terms.md#image-urls-and-image-sizes : 
"You'll find the URLs to the image(s) for a photo in the images field in the returned JSON for a photo. The images provided with our standard API access will be watermarked with the 500px logo and attribution. For non-watermarked images please contact sales@500px.com"

I think it could be possible to get image without watermark, but it's not that bad.

Also, why `'&exclude_nude=true'\` ? :rolleye:

**Comment by kvch** [comment]
Closing as 500px engine rewrite was merged a few months ago.
