### ISSUE TITLE
cant install 0.8.0 (fresh installation)

### ISSUE THREAD

**Issue by xinomilo** [searx/searx#423]
try to install 0.8.0 from scratch, follow installation step-by-step instructions and end up with this error : 
  File "/tmp/easy_install-ogHa2N/cryptography-1.0.1/cffi-1.2.1-py2.7-linux-x86_64.egg/cffi/api.py", line 56, in **init**
ImportError: /tmp/easy_install-ogHa2N/cryptography-1.0.1/cffi-1.2.1-py2.7-linux-x86_64.egg/_cffi_backend.so: failed to map segment from shared object: Operation not permitted

first seen it during : pip install -r requirements.txt ,
rerun that command and it finished succesfully, but now on :  python setup.py install 
it cant proceed beyond the above error.
server is a debian jessie x86_64 machine, python 2.7.9

would also like to report that upgrade instructions never worked for me, will open up a new ticket about that.

thx.

**Comment by asciimoo** [comment]
@xinomilo isn't your /tmp mounted with noexec flag?

**Comment by xinomilo** [comment]
yes it is. damn forgot all about it. can i change tmp dir during installation?

**Comment by asciimoo** [comment]
if you use pip, `export TMPDIR=/your/tmp` can help

**Comment by xinomilo** [comment]
it did, thx very much for the help.
