### ISSUE TITLE
File hosting websites

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#425]
Does searx make use of websites that crawl for files from file hosting websites?
### Files

| site-url | api-doc (if available) | comments |
| --- | --- | --- |
| http://www.filespump.net |  | e-Books |
| http://www.filewatcher.com |  |  |
| http://www.general-ebooks.com |  | of General World |
### Audio

| site-url | api-doc (if available) | comments |
| --- | --- | --- |
| http://www.audiopoisk.com |  |  |
| http://cloud-vibe.com |  | may be related to mp3vampire.com |
| http://mp3bear.com |  |  |
| http://mp3-center.net |  |  |
| https://mp3skull.is |  |  |
| http://muzoferma.com |  |  |
| http://vmp3.eu |  |  |
| http://xmusic.me |  |  |
### Files from forum boards

| site-url | api-doc (if available) | comments |
| --- | --- | --- |
| http://www.accuratefiles.com |  |  |
| http://www.alluc.com |  |  |
| http://cognitivefiles.com |  |  |
| http://downloadarquivo.com |  |  |
| http://filecraft.com |  |  |
| http://filecrop.com |  | PIPCU Domain Suspension |
| http://filegaga.com |  |  |
| http://filenewz.com |  |  |
| http://filespart.com |  |  |
| http://www.filespr.org |  |  |
| http://filetram.com |  |  |
| http://www.general-world.com |  |  |
| http://pron.tv |  | of alluc |
| http://rapid4me.com |  |  |
| http://rapidsharemix.com |  |  |
| http://rapid-search-engine.com |  |  |
| http://rapidsharemix.com |  |  |
| http://sharedir.com |  |  |
| http://www.sharegloo.com |  | website temporarily disabled due to DDOS |

By observing the sources at filediva.com (not listed due to suspicious .exe files), I suspect that fboom.me and k2s.cc have API to retrieve list of files.

**Comment by Cqoicebordel** [comment]
You can add them in https://github.com/asciimoo/searx/wiki/possible-search-engines if they are relevant.

**Comment by GreenLunar** [comment]
Thanks.

**Comment by GreenLunar** [comment]
Thanks.

@Cqoicebordel, I have updated the first post.  I am not sure if I should include _Files from forum boards_ since it is too much work to keep up with changes, I think.
