### ISSUE TITLE
Use filetype: search operator to look up for files

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#426]
For information, see:
http://www.marcandangel.com/2006/10/13/turn-google-into-napster-2000/
http://lifehacker.com/136578/geek-to-live--find-free-music-on-the-web
https://torrentfreak.com/google-filetypetorrent/
http://www.googletutor.com/voyeur-heaven/

**Comment by Cqoicebordel** [comment]
You can do that already, no ?
As for other engines than google, it depends on those engines.

**Comment by GreenLunar** [comment]
Do you mean that searx utilizes such techniques automatically (when File category is selected) or users can use the above techniques directly from searx or did you mean to both?

I was thinking of the automated manner, the first one.

**Comment by Cqoicebordel** [comment]
Oh, didn't understand that.
That could be a good idea indeed.

**Comment by GreenLunar** [comment]
I have added two search engines to https://github.com/asciimoo/searx/wiki/possible-search-engines

Add search engines for **Files**, **Audio** and **Video** based upon advanced search operators

**Comment by GreenLunar** [comment]
I figured to compose a file with common Video formats from which Searx would draw information, yet it would not be practical with Files search due to large range of file types.

**Comment by GreenLunar** [comment]
@ukwt and @pointhi, may you suggest a better way to handle this?

**Comment by allendema** [comment]
Some engines like Qwant and DDG support this.
Can this issue be closed?

**Comment by asciimoo** [comment]
Yup, we cannot give a general solution to this issue, because most of the search engines don't support this.
