### ISSUE TITLE
[ENGINE] Yandex

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#430]
Is there some interest in using Yandex? Seems to have an opensearch api: https://yandex.com/opensearch.xml

**Comment by thfree** [comment]
It would be very good if it is implemented.

**Comment by cy8aer** [comment]
Ahem thanks for implementing it. But two things: shortcut yandex is ya, shortcut for yacy is ya, prefer yn for yandex.
Second thing (yes this is an early implementation): yandex has international services so a localisation would be nice.

**Comment by asciimoo** [comment]
@cy8aer thanks the notes. I fix the shortcut. Can you help with the localization part? I couldn't find related search parameters.

**Comment by cy8aer** [comment]
I am not sure but they seem to select it by domain: yandex.ru russian, yandex.com english, yandex.com.tr for turkey. Just look at http://www.yandex.com for other languages.

**Comment by cy8aer** [comment]
yes, tested it on hard changing https://yandex.ru to https://yandex.com in the engines file and it answers english

**Comment by asciimoo** [comment]
@cy8aer thanks! =)

**Comment by ghost** [comment]
I'm also thank you!
And just to say: when i'm using _**Yandex Images**_, i always have very good results, so perhaps needs to be included as separate engine!
Thanks again!

**Comment by ghost** [comment]
_Yandex !bang_ does not give me any result on https://searx.me/ and locally it search `yn word`.

**Comment by asciimoo** [comment]
seems it throws captcha

**Comment by return42** [comment]
closed by fafc564874c
