### ISSUE TITLE
Trim results by region

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#431]
There is a discussion at https://github.com/nylira/prism-break/issues/168 which yielded some points about country-specific results.

The meta-search engines in question in the aforementioned discussion appear to be sending user GeoIP to the search engine they use, something that instruments breaking of user privacy.

**In this issue, I ask to provide (preferably) a plugin that would trim results by origin, if possible.  The algorithm to achieve that may be pretty long and complicated, I think.**  On the other hand, searx may not have to follow, searx may have its own way to retrieve localized results that would excel the biggest search engines.

Related: #376 #407 #429

**Comment by GreenLunar** [comment]
On the other hand, searx may not have to follow, searx may have its own way to retrieve localized results that would excel the biggest search engines.

**Comment by Cqoicebordel** [comment]
Hum, I don't understand.
Do you want us to implement a way to restrict results to the localization of the user ?
If so, it's partially done, but is set in the settings, by choosing your search language.

But doing more, as in, finding out where the users are, shouldn't be our goal.

**Comment by GreenLunar** [comment]
By no means I asked to find out where users are.

Maybe I should have asked for a feature to use several searx nodes of different ip addresses/locations and sort them out in the node which operates as client.

This is what I ask.

```
                              +-- searx node in never-land
                              | 
User < searx UI < filter node +-- searx node in wonder-land
                              | 
                              +-- searx node in no-land
```

Each node, if a searx server is connected to more than a node, searches for the same thing, according to user preference (e.g. by language) in different territories.  This is a way to circumvent censorship, maybe.

If you think the issue I have referred to has no new idea to implement on searx or is too complicated or expensive to implement, then please close this issue.

**Comment by GreenLunar** [comment]
This is what I ask.

```
searx UI +-- searx node of wonder-land
         | 
         +-- searx node of never-land
         | 
         +-- searx node of no-land
```

Each node, if a searx server is connected to more than a node, searches for the same think, according to user preference (e.g. language) in different territory.  Some way to circumvent censorship, maybe.

**Comment by Danie10** [comment]
Language is not unique to a country eg. English is spoken in many countries but the point is often you want to find products or information in a country you live in. Choosing English is not going to differentiate between US, UK, Australia, or South Africa. A regional site may be determined from the hosting domain suffix or possibly the public IP address range.

**Comment by GreenLunar** [comment]
Yes, and, in fact, it is important to get results according to region (e.g. Local Doctors or Shops), but my point here was to undisclose user's possible location and to overcome censorship.

Search engines, for profit, must comply with governments in order for them not to be censored and keep their business plan survive.

**Comment by allendema** [comment]
Not sure if thats what you mean, but changing the locale gives different results.
