### ISSUE TITLE
[RTL] Search button should be placed at left side

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#433]
Similar problem as in #388

`search-icon-pixel.png`

**Comment by kvch** [comment]
I believe this is not an issue anymore. When I switch to Hebrew locale, the buttons seem to be in the correct order.

![image](https://user-images.githubusercontent.com/3876218/83359561-3d1f7c80-a37b-11ea-88bc-f8207ab02011.png)

Feel free to reopen the issue, if you think it is still a problem.
