### ISSUE TITLE
issue with searches above certain length?

### ISSUE THREAD

**Issue by ghost** [searx/searx#434]
I have not yet updated searx to 0.8 (setting up new DNS servers has a higher priority), but I keep getting errors when search strings are too long or contain too much unicode, like:

update: wrong url.
same issue still applies, but it happens randomly.

**Comment by moritan** [comment]
The size for an url is near 2000 chars so if you are in http GETmethod you may have reach the limit

**Comment by ghost** [comment]
The keywords after q= weren't _that_ long, I doubt the url in its whole reached 2000 chars.

**Comment by unixfox** [comment]
Probably fixed.
