### ISSUE TITLE
Getting redirected to searx.me when using any tab besides General and when not searching from address bar

### ISSUE THREAD

**Issue by ghost** [searx/searx#439]
Title is pretty much it... if I search in the address bar I'm fine, but if I use the actual search bar on searx.me it redirects me back. Same happens if I try to search images, videos, etc. Additionally, I am redirected when I try to go to the next page...

Thanks for any help!

**Comment by xinomilo** [comment]
works fine for me. have you tried clearing the cache from your browser?

**Comment by ghost** [comment]
Hmm, no that didn't fix it.

**Comment by nettlebay** [comment]
Hello,
same problem with Ubuntu and Slimjet Browser (Chromium based). It can be fixed by changing Method: "POST" by "GET" in "preferences"

**Comment by ghost** [comment]
That did it! Woo!
