### ISSUE TITLE
Results links open in the same tab

### ISSUE THREAD

**Issue by nettlebay** [searx/searx#444]
How to set searx to open links in a new tab?

**Comment by lucarabistouille** [comment]
You just need to do a little modification in the html code of the template you're using. By adding a target attribute to a tag with the value "_blank", it makes the click open a link.

Assuming you're using the default template, you just have to replace : 

``` html
<a href="{{ result.url }}" rel="noreferrer">{{ result.title|safe }}</a>
```

by : 

``` html
<a href="{{ result.url }}" rel="noreferrer" target="_blank">{{ result.title|safe }}</a>
```

in templates/default/result_templates/default.html

PS : You can also add this attribute to every link of your template that you want to be opened in a new tab.

**Comment by nettlebay** [comment]
Thanks
But I guess this is possible only with my own Searx? 
But I use only the standard Searx: searx.me

**Comment by lucarabistouille** [comment]
It seems you're right :)

It's however (perhaps) not hard to imagine to let the user choose what he wants in his preferences. I'll see that when I find some time for it... but as I've never work on searx it will certainly take me some time !

**Comment by nettlebay** [comment]
OK, thanks!

**Comment by Cqoicebordel** [comment]
@nettlebay No, keep this bug open, it's not resolved yet :)
While it's open, it's on our todo list, if it's closed, we'll probably forget it...

**Comment by nettlebay** [comment]
OK! Thanks

**Comment by BARETC** [comment]
I like to use a direct click with an open of a new tab and to keep the request page with its result in the original tab (for example like https://www.ixquick.com/)
It is possible by add inside the <A tag the javascript code onclick="window.open(this.href); return false;"
For exemple 
<a href="http://www.w3schools.com/html/default.asp" onclick="window.open(this.href); return false;">
Is it posible to add an option to choose if you want add this option?
So the people like me that prefer to keep the original request tab and to open a new tab can choose this option
And the people which prefer to not open a new Tab can not use this option

**Comment by erdmark** [comment]
The user can choose to open links in new tab by going to
preferences -> General -> Results on new tabs

But it would be useful to be able to set the default value in settings.yml

**Comment by victoriastuart** [comment]
Conversely I want to open links from searx in the same tab.

I had (Preferences) "Results on new tabs" set to "Off" but it was ignored.

**Solution**

I'm calling searx from a local webpage that has links that I commonly access: I needed to add `target="_self"` to this form on my HTML page:

```html
<!-- <form action="https://searx.me/" id="search"> -->
<!-- https://stackoverflow.com/questions/44884990/opening-a-link-in-the-same-tab-with-html : target="_self" -->
<form action="http://127.0.0.1:8888/" id="search">
  &nbsp;&nbsp;&nbsp;<b>searX</b> <input name="q" id="q" type="text" size="120" target="_self" />
</form>
```
