### ISSUE TITLE
Infobox is always in English

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#447]
A search for [שלום](https://searx.me/?q=%D7%A9%D7%9C%D7%95%D7%9D) (hello/peace) or  [שחיתות](https://searx.me/?q=%D7%A9%D7%97%D7%99%D7%AA%D7%95%D7%AA) (corruption), returns information in English in Searx Infobox.  Sometimes, the InfoBox returns nothing; [הגשש החיוור](https://searx.me/?q=%D7%94%D7%92%D7%A9%D7%A9%20%D7%94%D7%97%D7%99%D7%95%D7%95%D7%A8) (HaGashash HaHiver).

_Users who use Searx in languages that are not English, would expect or prefer to see text of Infobox with their respective language._

**Comment by GreenLunar** [comment]
The above search term is not a good example.  Try this https://searx.me/?q=%D7%94%D7%92%D7%A9%D7%A9%20%D7%94%D7%97%D7%99%D7%95%D7%95%D7%A8 (no InfoBox)

**Comment by GreenLunar** [comment]
Correction, it is mostly and only in English https://searx.me/?q=%D7%A9%D7%97%D7%99%D7%AA%D7%95%D7%AA

שחיתות = corruption
IfoBox shows whistleblower (in English)

**Comment by MarcAbonce** [comment]
I'm currently working on this one here: https://github.com/a01200356/searx/commits/wikipedia_infobox

It cuts out the middleman by scraping wikipedia directly because I couldn't find in duckduckgo's api's documentation how to set the language (I don't even know if they support it at all).

It still needs testing though.

**Comment by asciimoo** [comment]
fixed by @a01200356 , thanks

**Comment by GreenLunar** [comment]
I don't see any difference.

**Comment by asciimoo** [comment]
@GreenLunar it works for me: https://searx.me/?q=%21wp%20%3Ahu%20k%C3%A1poszta&categories=none - it is hungarian

**Comment by GreenLunar** [comment]
It appears not to work when `!wp :hu` is not used https://searx.me/?q=k%C3%A1poszta&categories=none

**Comment by dalf** [comment]
The data seems to come from the wikidata engine.
