### ISSUE TITLE
searx forum

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#448]
Related to #243

I suggest to open a forum with help of Seeks and YaCy fans!

There will be a sub-forum for searx, Seeks, YaCy and more.  Such forum would also be a central to propose new ideas and even promote new meta-search projects!

Ping @beniz @yacy

**Comment by beniz** [comment]
open it up,  and I ll contribute happily!

**Comment by songproducer** [comment]
I opened Yacy and searx chat rooms on Matrix:
#searx:monero.fun
#yacy:monero.fun
You'll need a client like Riot.im

**Comment by unixfox** [comment]
https://github.com/searx/searx/discussions
