### ISSUE TITLE
change website name

### ISSUE THREAD

**Issue by jpcaruana** [searx/searx#450]
It would be great to be able to change website name. Templates have `searx` hard coded in the HTML and hosting a personalized version requires a lot of work.

Could this be in `config.yml` like `base_url` parameter ?

**Comment by Cqoicebordel** [comment]
It could be mostly done, but there is the issue of the images. The logo contains the text searx and it's not that easy to change the text on an image. So some work should be done on your side too.

Beyond that, I don't know if it must be done on our side : the project is named searx, so it would be normal that the name appeared on it. If you want to change its name, you are free to do so as it's an open source project, but I don't think (and it's only my own opinion) that we should help you change its name.
For me (again, just for me), it's like we gave you a car, and you asked us to also change the logo of the brand on it. It would be weird to ask Mercedes, or Audi (or any other) to do that.
Again, just my own opinion, and it's open for debate.

**Comment by jpcaruana** [comment]
Hi, 

thanks for sharing your opinion.

It is very easy to change an image: just replace it _once_ and you're done. I think it would be great to be able to change the name on every pages by changing just _once_. A lot of open source sofware allow personalisation and they are perfectly fine with it (see wordpress for one example). I also think this is a better design to template (almost) everythink than to have hard coded values.

If you look at https://framabee.org/, there is no mention to searx everywhere like there is on the default theme (but you still have the "powered by searx" link at the end) - they removed the name everywhere and this instance is popular, and everybody knows it is searx powered. (I think your car analogy is unrelated to my suggestion.)

ps: marrant ton pseudo

**Comment by GreenLunar** [comment]
> but you still have the "powered by searx" link at the end

This is also subjected to removal, as it is in many websites, mostly commercial websites, that are powered by Joomla or WordPress; nevertheless, I tend to support your request.

Another reason to implement this is to see how themes appear against different graphics, such scenario might lead to rethink the Searx logo and make Searx more attractive to new users.

**Comment by GreenLunar** [comment]
Another reason to implement this is to see how themes appear against different graphics, such scenario might lead to rethink the Searx logo and make Searx more attractive to new users.
