### ISSUE TITLE
No virtual-env: incorrect redirect when saving preferences

### ISSUE THREAD

**Issue by minami-o** [searx/searx#451]
Hi there,
First off, thanks for the great job providing this very nice tool!
I just installed my own instance, and chose for various reasons not to use the virtual environment setup. Instead I used the alternative (recommended) setup in README.rst, via _make minimal_ and _bin/searx-run_, and redirected external flow via a reverse proxy rule in my (h2o) webserver.
This setup requires the use of the **base_url** setting from _searx/settings.yml_ (**server** section), to have a consistent "Search URL" link in the bottom right panel of the search page (not doing so results in a misleading "http://localhost:_port_..." link).
I noticed however that, when saving preferences via the dedicated "save" button, preferences were saved (which is good), but the redirection was done towards the "internal" url, ie "http://localhost:_port_" (which is bad, obviously).
To correct this, I simply replaced line 534 of file _searx/webapp.py_ with the following lines:
Before:

>  &nbsp;&nbsp;&nbsp;&nbsp;resp = make_response(redirect(url_for('index')))

After:

> &nbsp;&nbsp;&nbsp;&nbsp;if settings['server']['base_url']:
>   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resp = make_response(redirect(settings['server']['base_url']))
> &nbsp;&nbsp;&nbsp;&nbsp;else:
>     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resp = make_response(redirect(url_for('index')))

This makes sure the **base_url** is used if it was set by the admin.
I only tested on my own server, but I guess the code is rather generic and should work anywhere...
Cheers,
Minami-o

edit: just noticed the same behavior on line 769 for the "Reset defaults" button, correction is exactly the same.

**Comment by asciimoo** [comment]
First of all, thanks the detailed description. It's definitely bug, but it requires some further investigation, since it can occur in other parts of the code.

**Comment by minami-o** [comment]
In the meantime, I realized that you already created a function to recover the **base_url**, _get_base_url_.
It solves the issue in the two mentioned cases (at least) in a more elegant way:

> &nbsp;&nbsp;&nbsp;&nbsp;resp = make_response(redirect(get_base_url()))
