### ISSUE TITLE
UI::Clear Button

### ISSUE THREAD

**Issue by ghost** [searx/searx#454]
Hi, i like Yandex and DuckDuckGo **Clear Button**  ![capture du 2015-10-31 09 06 50](https://cloud.githubusercontent.com/assets/5161278/10862497/00486510-7fb3-11e5-8a83-70daf5e32205.png), so it would be nice if can be implemented here!
~~And since i'm said Yandex, maybe to be [add](https://github.com/asciimoo/searx/issues/430) it to search engines is not a bad idea....~~ **«««DONE**
Thanks!

**Comment by eht16** [comment]
That would be nice.
I often use the primary clipboard (select some text and paste it with middle click) but if you have already text in the search box you cannot clear it by selecting it as it would override the previous clipboard content.

I guess such a button should be easy to implement, probably in JS only?
