### ISSUE TITLE
ERR_CONNECTION_RESET in Chrome/Chromium

### ISSUE THREAD

**Issue by admirabilis** [searx/searx#457]
Hello! First of all, thank you for searx, it is a great search engine!

I know there are other instances available, but my favourite is searx.me, and I thought it would be best to solve this problem, instead of ignoring it!

On both Google Chrome 42.0.2311.90-1 and Chromium 44.0.2403.157 on Debian Wheezy, connecting to searx.me via HTTPS always returns: This page is not available: ERR_CONNECTION_RESET. It works in Firefox, though!

**Comment by xinomilo** [comment]
works fine in debian sid with chromium. 
maybe clearing the cache, or trying a new profile in chrome to check?

**Comment by admirabilis** [comment]
Hi, @xinomilo! The Chrome profile was old, but the Chromium one is totally new!

**Comment by admirabilis** [comment]
I don't know if this is related, but the only thing I could find about the ERR_CONNECTION_RESET error for specific sites on Chrome in Debian, is this page talking about mod_spdy: http://blog.php-function.de/err_connection_reset-mediawiki-im-chrome-nach-debian-update/

**Comment by admirabilis** [comment]
On Chromium 46 it works OK!
