### ISSUE TITLE
oscar theme does not render nicely with dark CSS

### ISSUE THREAD

**Issue by mpancorbo** [searx/searx#458]
I've played a bit with [bootswatch](http://bootswatch.com/) replacement for `bootstrap.min.css` in oscar theme.

Clear bootswatch CSS's fit well with the theme, but dark ones have issues when rendering results.

After reading a bit the code I catched that `oscar.min.css` defines own colours for, i.a., highlighting coincident words. So, it breaks the coherence of the original style.

Can it be somehow fixed?

**Comment by asciimoo** [comment]
@mpancorbo this inconsistence should be eliminated.
any ideas?

**Comment by unixfox** [comment]
Oscar dark theme seems fine for me, anyway I'm closing in favor of https://github.com/searx/searx/issues/2440
