### ISSUE TITLE
Engine > Files > F-Droid

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#459]
Add F-Droid apps directory.

Maybe Cydia too.

@f-droid

**Comment by GreenLunar** [comment]
@f-droid

**Comment by Cqoicebordel** [comment]
I love that idea, especially f-droid, for their Open sources softwares.

**Comment by GreenLunar** [comment]
This will probably be in next release.  See #526 and http://i.imgur.com/jHgJg2X.png

Thanks to @ukwt.

**Comment by GreenLunar** [comment]
This has been accomplished in #526
