### ISSUE TITLE
Searx isn't starting

### ISSUE THREAD

**Issue by virse** [searx/searx#464]
Hi there,

I'm a Newbie to Searx and trying to install Searx on a VServer. The installation went fine, but when I try to start Searx via _python searx/webapp.py_ the following error appears n the console:

```
python searx/webapp.py
Traceback (most recent call last):
  File "searx/webapp.py", line 53, in <module>
    from searx.engines import (
  File "/usr/local/searx/searx/engines/__init__.py", line 212, in <module>
    engine = load_engine(engine_data)
  File "/usr/local/searx/searx/engines/__init__.py", line 51, in load_engine
    engine = load_module(engine_name + '.py')
  File "/usr/local/searx/searx/engines/__init__.py", line 44, in load_module
    module = load_source(modname, filepath)
  File "/usr/local/searx/searx/engines/wikidata.py", line 4, in <module>
    from searx.poolrequests import get
  File "/usr/local/searx/searx/poolrequests.py", line 50, in <module>
    http_adapters = cycle((HTTPAdapterWithConnParams(pool_connections=100), ))
  File "/usr/local/searx/searx/poolrequests.py", line 16, in __init__
    self.max_retries = requests.adapters.Retry(0, read=False)
AttributeError: 'module' object has no attribute 'Retry'
```

Thx in advance for any hints.

mike

**Comment by pointhi** [comment]
look here: https://github.com/asciimoo/searx/issues/253#issuecomment-76009918

**Comment by virse** [comment]
I tried it with make clean but the error is the same.

Or have I misinterpreted something?

**Comment by asciimoo** [comment]
@virse what is the version of your requests package?

**Comment by virse** [comment]
Hi asciimoo,

_python2 -c 'import requests; print requests.**version**'_ shows me

```
2.2.1
```

**Comment by virse** [comment]
Hi Asciimoo,

sorry for pushing but should another version of the request package be installed?
And if so how can I fix it?

 Thx a lot!

**Comment by pointhi** [comment]
Hy, it's very likely, that you have an too old version of requests. Looking at [versions.cfg](https://github.com/asciimoo/searx/blob/master/versions.cfg#L25), searx is currently using version 2.7.0.

Try to run `pip install --upgrade -r requirements.txt` in the virtual enviroment (if you are using it) which should update your dependencies.

**Comment by virse** [comment]
Hi pointhi,

thx for your help.

I've installed requests version 2.8.1. 

```
python2 -c 'import requests; print requests.__version__'
2.8.1
```

I could now access Searx on https://searx.abc.de but when I start a search query then a 500 error in the browser appears.

I'm using an Apache 2 as webserver and use the config as mentioned in the installation guide

```
ServerName searx.abc.de

SSLEngine on
SSLCertificateFile /etc/ssl/certs/abc.de.crt
SSLCertificateKeyFile /etc/ssl/private/abc.de.key
SSLCertificateChainFile /etc/ssl/certs/ca-bundle.crt


<Location />
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>
```

Do I need to change anything in the /usr/local/searx/searx/settings.yml (Server part)

```
server:
    port : 8888
    bind_address : "127.0.0.1" # address to listen on
    secret_key : "1212" # change this!
    base_url : False # Set custom base_url. Possible values: False or "https://your.custom.host/location/"
    image_proxy : False # Proxying image results through searx
```

I alreayd tried port 443, bind-address localhost and abc.de.
Always the same error.

Thx again for helping me out!

**Comment by pointhi** [comment]
uwsgi should write a logfile into `/var/log/uwsgi/app/searx.log`.

If there are no errors shown, look at the apache logfile `/var/log/apache2/error.log` (or similar logfiles).

You should get a hint why you get a 500 Error in those logfiles. Normaly those bugs are caused by a misconfiguration of apache or uwsgi.

**Comment by virse** [comment]
Hi,

uwsgi brings me in the log this one (apache logs are all "clean"):

```
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
```

It's a self signed certificate. Could this be the cause of the error. and when so what can I do to fix it? Is there any config-file in searx where I can tell searx (or maybe uwsgi) to skip checking the self signed certificate?

Thx again!

**Comment by virse** [comment]
Hi pointhi,

I figured out that my installation is working when i disable Google as Search engine that caused this error:

```
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
DEBUG:requests.packages.urllib3.connectionpool:"GET /do/suggest?query=dgfgfg HTTP/1.1" 200 0
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.google.de
```

When I googled ;o) I found this:

```
Security: Verified HTTPS with SSL/TLS
Very important fact: By default, urllib3 does not verify HTTPS requests.
```

So is there any possibility to make google https-search accessable via searx? Other than using

```
pip install certifi
```

Thx a lot!

**Comment by virse** [comment]
For those who have the same problem just do 

```
pip install certifi==2015.04.28
```

and activate Google afterwards in your (personal) settings.
