### ISSUE TITLE
RSS button does not enable subscription to RSS feed

### ISSUE THREAD

**Issue by jibe-b** [searx/searx#468]
Hi,

I'd like to subscribe to the RSS feed correspending to a few searx queries, but the RSS icon opens a page that displays error:

> This XML file does not appear to have any style information associated with it. The document tree is shown below.

It is indicated here:
http://validator.w3.org/feed/docs/error/WPBlankLine.html
that a possible problem is the presence of a whitespace at the beginning of a file

Is the RSS button intended for subscribing a RSS feed or rather download the file? Maybe should I reformulate my issue as a feature request, let me know.

Best regards

**Comment by asciimoo** [comment]
It works for me with Firefox 42.0 if i click on "Subscribe now" button.
Tested url: https://searx.me/?q=python&format=rss

**Comment by GreenLunar** [comment]
I guess, @jibe-b has referred to the button in Searx, not of a web browser.

**Comment by jibe-b** [comment]
Right, in the 'Links' pannel

> Download results
> [csv][json][rss]

clicking on the rss 'button' returns a RSS/XML file but does not open the same page as the one obtained with https://searx.me/?q=python&format=rss

In case the 'rss' button is intended to return this RSS/XML page, I'd suggest to add a 'Subscribe' button that sends to the https://searx.me/?q=python&format=rss page. One reason is that the 'Subscribe now' button is not by default on the UI of browsers.

Thanks anyway for this way to subscribe to an rss page for the moment.

**Comment by GreenLunar** [comment]
I have the same problem.
Web browser RSS button refers to https://searx.me/?q=python&format=rss&category_general=1&pageno=1
Searx button refers to https://searx.me/ which would not fit in a feed reader.

**Comment by jibe-b** [comment]
In order for a browser to identify there is an RSS feed on the page, there is the need to have a link in the head. source: https://www.xul.fr/en-xml-rss.html#Browser

It might also be needed that this link and the one you click on (`rss` button in the right pannel) be exactly matching. source: just a guess, one should try.

**Comment by jibe-b** [comment]
Thank you for the work done @asciimoo! And great to see you're still working on it!

I now earn a bit of money, I'll start a (small) regular payment because I really appreciate what you do!
