### ISSUE TITLE
500 internal server error when trying to search from firefox search bar

### ISSUE THREAD

**Issue by carlzoo** [searx/searx#469]
Firefox 43.09b

After I added privatesearch as one of my search engines, when I search for something it says 

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

However, if I hit enter again it works.

**Comment by asciimoo** [comment]
fixed in d8f8bdc951f40fa56f1ff61306a78a28958dd41b
@privacytoolsIO could you update privatesearch.io?

**Comment by dalf** [comment]
close ?
