### ISSUE TITLE
Prompt user to add Searx to search engine list of smartphones

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#470]
I did not check how this is being done.  Last time I checked, several years ago, Bing has this feature.

**Comment by nixoye** [comment]
there should be a button to do easily change default search engine to searx both on desktop and mobile

**Comment by GreenLunar** [comment]
Big web companies have no interest in doing so, they like to foist their tracking services on us and they do not like to provide us with easy, documented, and simpler means to custom user preferences.

**Comment by return42** [comment]
Klick 'about', there you find a description how to add search engine.

**Comment by GreenLunar** [comment]
Well, long time ago, when I was using a proprietary smartphone (iPhone 3s), I had only one website that prompted me to add it to my list of search engines. Other than that, there was no way for user to add new search engines.
