### ISSUE TITLE
Unable to install - documentation needs updated?

### ISSUE THREAD

**Issue by loganmarchione** [searx/searx#471]
Using Ubuntu 14.04 with Nginx, located at [blackholeroutercondition.com](https://blackholeroutercondition.com/). Was receiving 500 errors, but after some tweaking I'm receiving a 502.

I just tried to install a new instance of Searx (blew away old, working instance), and it seems the documentation/code has changed since I last installed it. I am no longer able to install as per [these](https://github.com/asciimoo/searx#installation) instructions.

I tried to use the "[recommended](https://github.com/asciimoo/searx#alternative-recommended-installation)" instructions, but am unable to get it working either.

Are there new install docs to use? Seems like this [link](https://github.com/asciimoo/searx/wiki/Installation) doesn't go anywhere.

This is my current Nginx setup.

```
server {
        listen 80;                                      #Listen on IPv4
        listen [::]:80;                                 #Listen on IPv6
        server_name blackholeroutercondition.com;
        return 301 https://$host$request_uri;           #Redirect HTTP to HTTPS
        access_log /dev/null;
        error_log /dev/null;
}

server {
        listen 443 ssl spdy;                            #Listen on IPv4
        listen [::]:443 ssl spdy;                       #Listen on IPv6
        server_name blackholeroutercondition.com;

        ssl on;
        ssl_certificate /etc/nginx/ssl/blackholeroutercondition.com/unified.crt;
        ssl_certificate_key /etc/nginx/ssl/blackholeroutercondition.com/my-private-decrypted.key;
        ssl_buffer_size 1400;

        #Add perfect forward secrecy and prevent BEAST attacks
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 24h;
        ssl_ciphers "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK";

        #Prevent POODLE attacks
        ssl_protocols TLSv1.1 TLSv1.2;

        #Enable HSTS
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
        ssl_dhparam /etc/nginx/ssl/blackholeroutercondition.com/dhparam4096.pem;

        #Enable SSL stapling
        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_trusted_certificate /etc/nginx/ssl/blackholeroutercondition.com/ca-certs.pem;

        root /var/www/searx/searx/templates/oscar;                              #Set document root
        autoindex off;                                  #Turn off index browsing everywhere
        index index.php index.html;                     #Set indexes to include .php before .html
        access_log /dev/null;
        error_log /dev/null;

        location / {
        include uwsgi_params;
        uwsgi_pass unix:/run/uwsgi/app/searx/socket;
        }

        #Allow access to favicon.ico and robots.txt and don't log that access
        location = /favicon.ico {
        log_not_found off;
        access_log off;
        }

        location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
        }

}
```

**Comment by pointhi** [comment]
Hy, try to use this instructions for installation: http://asciimoo.github.io/searx/dev/install/installation.html

You have to note, we updated the dependencies, and also changed the logical structure of `settings.yml`. Probably this is causing the problems.

**Comment by loganmarchione** [comment]
Are those accurate? I didn't see the searx-ve folder anywhere....

**Comment by pointhi** [comment]
have you created a virtualenv when installing searx?

**Comment by loganmarchione** [comment]
No, I thought those instructions were no good because the searx-ve folder wasn't there in the first place for me to run these commands.  

```
sudo -u searx -i
cd /usr/local/searx
virtualenv searx-ve
. ./searx-ve/bin/activate
pip install -r requirements.txt
python setup.py install
```

**Comment by pointhi** [comment]
when you look on the install instruction, there is the command `virtualenv searx-ve`. When you installed searx in another way, the update instructions won't work

**Comment by loganmarchione** [comment]
I tried to blow it away and start fresh using the recommended way, but I'll try it fresh with the virtual environment.

**Comment by loganmarchione** [comment]
I tried again with the [instructions you linked](https://asciimoo.github.io/searx/dev/install/installation.html) from a fresh install and it worked. I didn't realize I needed to use special instructions to update.

```
cd /usr/local/searx
sudo -u searx -i
. ./searx-ve/bin/activate
git stash
git pull origin master
git stash apply
pip install --upgrade -r requirements.txt
sudo service uwsgi restart
```

However, when I search any pages, I'm now getting this message.

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Below is the log from `/var/log/uwsgi/app/searx.log`. My site is [here](https://blackholeroutercondition.com). I don't think the SSL error is on my end, is it?

```
WARNING:searx.search.google engine:cannot fetch PREF cookie
ERROR:searx.webapp:Exception on /autocompleter [GET]
Traceback (most recent call last):
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/searx/searx/webapp.py", line 501, in autocompleter
    raw_results.extend(completer(query.getSearchQuery()))
  File "/usr/local/searx/searx/autocomplete.py", line 145, in google
    + urlencode(dict(q=query)))
  File "/usr/local/searx/searx/autocomplete.py", line 34, in get
    return http_get(*args, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 82, in get
    return request('get', url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 75, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
ERROR:searx.webapp:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/searx/searx/webapp.py", line 382, in index
    search.search(request)
  File "/usr/local/searx/searx/search.py", line 294, in search
    engine.request(self.query.encode('utf-8'), request_params)
  File "/usr/local/searx/searx/engines/google.py", line 209, in request
    params['cookies']['NID'] = get_google_nid_cookie(google_hostname)
  File "/usr/local/searx/searx/engines/google.py", line 149, in get_google_nid_cookie
    resp = get('https://' + google_hostname)
  File "/usr/local/searx/searx/poolrequests.py", line 82, in get
    return request('get', url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 75, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)
```

**Comment by THS-on** [comment]
I can confirm this issue. I'm running searx on Ubuntu 14.04 Nginx and have the same error message. 
It is a problem with the google search because when I disable google search all is working fine.

**Comment by loganmarchione** [comment]
@THS-on, same thing here. Just tried turning off Google search (left Google autocomplete on) and it worked fine. I'll use DDG for now.

**Comment by THS-on** [comment]
Latest version fixed it for me. Close?

Edit: This just fixed the 500 Error not the search itself. The search returns nothing when I use !go

**Comment by asciimoo** [comment]
@THS-on it works for me: https://searx.me/?q=%21go%20south

**Comment by Liandriz** [comment]
Same here, before 0.8.1, got 500 errors on Google searches, now, blank result page.

**Comment by THS-on** [comment]
@asciimoo on which system you are running searx and what python version?  I just did a fresh install on my server and have the same error as before. This is a log from my local install on Linux Mint 17.3:

`ERROR:searx.search:engine crash: google
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 38, in search_request_wrapper
    return fn(url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 82, in get
    return request('get', url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 75, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)`

Edit: Location of the server is France maybe that helps.

**Comment by THS-on** [comment]
I just started a docker container from https://hub.docker.com/r/wonderfall/searx/ and this container is working fine. Maybe the issue is related to the Ubuntu installation because the container uses [Alpine Linux](http://alpinelinux.org/).

**Comment by Trim** [comment]
Hello,

I had same issue with Debian Jessie (with backports) and searx 0.8.0 (proxied by Apache 2.4.10).

I have to disable Google engine (either from settings.yml or by cookie) to be able to have no internal server error (see https://s.adorsaz.ch ).

Here is my last `make production` results:

```
make production
bin/buildout -c production.cfg 
Develop: '/srv/opt/searx/searx/.'

/srv/opt/searx/searx/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Updating omelette.
omelette: Warning: (While processing egg cryptography) Package '_Cryptography_cffi_26cb75b8x62b488b1' not found.  Skipping.
omelette: Warning: (While processing egg cryptography) Package '_Cryptography_cffi_590da19fxffc7b1ce' not found.  Skipping.
omelette: Warning: (While processing egg cryptography) Package '_Cryptography_cffi_a269d620xd5c405b7' not found.  Skipping.
Updating pyscripts.
Updating supervisor.
Updating crontab_reboot.
Versions had to be automatically picked.
The following part definition lists the versions picked:
[versions]
collective.recipe.supervisor = 0.19
meld3 = 1.0.0
supervisor = 3.0
z3c.recipe.usercrontab = 1.1
* Please modify /srv/opt/searx/searx/searx/settings.py
* Hint 1: on production, disable debug mode and change secret_key
* Hint 2: searx will be executed at server startup by crontab
* Hint 3: to run immediatley, execute 'bin/supervisord'
```

**Comment by loganmarchione** [comment]
@THS-on and @asciimoo, same results here. Just updated via [these](https://asciimoo.github.io/searx/dev/install/installation.html#how-to-update) instructions. The 500 error is gone, but even with Google enabled, I get no Google results and the Google bang (!) does not work.

> Latest version fixed it for me. Close?
> 
> Edit: This just fixed the 500 Error not the search itself. The search returns nothing when I use !go

![capture](https://cloud.githubusercontent.com/assets/4955337/11995567/08d5bf14-aa21-11e5-8211-1c0f968415d8.PNG)

**Comment by asciimoo** [comment]
@loganmarchione could you verify @misnyo's fix?

**Comment by loganmarchione** [comment]
@asciimoo and @misnyo, it works, thanks!

@asciimoo, the reason I opened this issue initially was because there are three sets of installation instructions (below), and only the third worked for me. Which set is the right set? Are 1 and 2 supported anymore? Should the README be updated?
- [#1](https://github.com/asciimoo/searx#installation)
- [#2](https://github.com/asciimoo/searx#alternative-recommended-installation)
- [#3](https://asciimoo.github.io/searx/dev/install/installation.html)

**Comment by asciimoo** [comment]
@loganmarchione i've started to refactor/simplify it on https://github.com/asciimoo/searx/tree/install-refactor - reviews are welcome.

**Comment by loganmarchione** [comment]
I like it, thanks! It was just a little misleading that there were two installations on one page.
