### ISSUE TITLE
[sponsorship] Ask worthy commercial interest groups to be included in InfoBox

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#476]
Example case:
1. User searches for Ramsomware.
2. InfoBox would display information from an Anti-virus website.

The above, specifically, is NOT a good idea, because some of these Anti-virus companies demonize [GNU Privacy Guard](https://www.gnupg.org/) and [Tor](https://www.torproject.org/) by explicitly and exclusively mentioning them in that negative context; one must wonder why don't they suggest their users _to protect themselves with these tools_.

**I figured it might be a good idea to suggest to some companies, that have their own definition directories, to include their reference in official code or server (searx.me) in return to a certain amount of annual or monthly fee.**

**Comment by GreenLunar** [comment]
I have changed the title and added to it "worthy commercial interest groups", which I doubt exist.

**Comment by ghost** [comment]
Can you show a single example of GnuPG or Tor being mentioned in a negative context when you search for them? I can't see it.

**Comment by GreenLunar** [comment]
Certainly, but not publicly.  I did not open this thread to promote commercial anti-virus companies.  Anyhow, please focus on the subject thread.

**Comment by ghost** [comment]
But what is your point? The very first thing you write in your suggestion is a completely hypothetical example which has nothing to do with real life. searx has no infoboxes displaying information straight from antivirus websites and I'm quite sure this will never be the case. Right now, there are infoboxes with information from DuckDuckGo, and what do you know, searching for 'Cryptolocker' gets you a nice infobox with a short description of Cryptolocker. Searching 'GnuPG' gets you an infobox with a short description of GnuPG. So, what's the problem?

Your suggestion itself doesn't make any sense either. You don't want infoboxes written by antivirus companies, but you don't have a problem with them as long as said companies pay for them and are 'worthy', but then just after you write that you doubt those even exist. If you think that is the case, why even make this suggestion in the first place?
"Nice photography collection, but it would be nice if you could get some pictures of unicorns. I doubt they exist, but I figure it might be a good idea for you to take some pictures of them."

**Comment by pointhi** [comment]
I also don't see what you want to achieve with this proposal.
For me, payed content wouldn't work, because of the low userrange as well as most user's and admins wouldn't accept it (like me).

When you want to display more/better infoboxes inside searx I would suggest improving the database on [wikidata](https://www.wikidata.org/wiki/Q17639196), and improving the wikidata parser inside searx.

**Comment by GreenLunar** [comment]
@d9h02f

> You don't want infoboxes written by antivirus companies, but you don't have a problem with them as long as said companies pay for them and are 'worthy', but then just after you write that you doubt those even exist.

I think you have missed the point.  The "anti-virus" mentions are for realization only!
I also see the problem with my wish, as you can tell.

> Right now, there are infoboxes with information from DuckDuckGo, and what do you know, searching for 'Cryptolocker' gets you a nice infobox with a short description of Cryptolocker. Searching 'GnuPG' gets you an infobox with a short description of GnuPG. So, what's the problem?

Your comment is meaningless.  I will not respond to your next comments.

@pointhi

> I also don't see what you want to achieve with this proposal.

Revenue.

This is an idea.
Think about it.

**Comment by GreenLunar** [comment]
P.S. I advise you to refrain from Wikmedia.  It is a propaganda and centralization operation. (this comment will be deleted)
