### ISSUE TITLE
New search engine for files: torrentz.eu

### ISSUE THREAD

**Issue by afita** [searx/searx#482]
torrentz.eu searches through many torrent sites. It would be useful to have it in the files section.

The Help section contains the API for the searches: https://torrentz.eu/help

Thanks.

**Comment by GreenLunar** [comment]
I think this issue has been resolved in #526 by @ukwt, even though not using an API.  See https://github.com/asciimoo/searx/pull/526/files#diff-30ca69a7974663a3b84d9047bd867a91

**Comment by asciimoo** [comment]
yap, thanks
