### ISSUE TITLE
Searching with Google not working anymore

### ISSUE THREAD

**Issue by admirabilis** [searx/searx#489]
Since yesterday, results from Google Search are unavailable in searx.me. I have tried a few other instances, and the result is the same.

**Comment by asciimoo** [comment]
@teresaejunior thanks the report

**Comment by admirabilis** [comment]
OK, thank you for the fix!

**Comment by rototom** [comment]
No succes here, after changing those files.
Still no results from google. (https://search.klein-hitpass.net)
