### ISSUE TITLE
Relax new requirements a bit

### ISSUE THREAD

**Issue by Glandos** [searx/searx#492]
I know that supporting a software is easier when you control the environment, but is it possible to relax the requirements.txt versioning a bit?

Currently, I'm trying to use as less as possible the pip dependencies, and rely as much as possible on my distro's package manager (Debian/testing). I do this because I don't have the time to run `pip install -U` on every Python application I have every time a security issue appears. And the distro handles everything for me (which is why I'm using a distribution ;) ).

Maybe some requirements like `>=2.11.0` should be enough?

**Comment by asciimoo** [comment]
@Glandos I understand your point, but I don't want to allow `>=` in requirements.txt. The main reason behind it is that if a dependency has backward incompatible changes, then it breaks searx.
You can still experiment with other dependency versions, probably searx will work fine with it.

**Comment by unixfox** [comment]
@dalf Is it still a case that we want to support in the future, reducing the amount of included python libraries?

**Comment by return42** [comment]
We recommend virtualenv and we have pined our [requirements](https://github.com/searx/searx/blob/master/requirements.txt).

**Comment by Glandos** [comment]
In another project I contribute to, we already had [this discussion](https://github.com/spiral-project/ihatemoney/issues/658#issue-660754645). The conclusion is to use lower bounds and exclusion with known incompatible version and semantic matching (like `babel~=2.9`). Otherwise it renders packaging much harder, and security is also a concern here. If a new `certifi` package is published with removed certificate because of trust issues, then users must wait for `requirements.txt` to be updated first.
Of course, things like dependabot renders this easier.

To avoid infinite debate, I'll avoid to answer more here, so if you still don't agree, it's not needed to add more comment here :wink:

**Comment by return42** [comment]
>  then users must wait for requirements.txt to be updated first.

That is right .. see last paragraph tagged with TLDR in my https://github.com/searx/searx/pull/2473#issuecomment-761582153

All solutions have their PROs and CONs and we rated the robustness and code maintenance higher than upward compatibility.

Searx is a meta search engine and its scrappers are needing regularly updates. That is why we recommend  to install from clone and maintain/update instance in short periods of time.

This scenario is complete different from developing and deploying a versioned application.

To pin versions is just a decision which fits best to our development and deployment cycles.
