### ISSUE TITLE
opensearch.xml ShortName should be domain-specific to avoid naming conflict (firefox)

### ISSUE THREAD

**Issue by vn971** [searx/searx#494]
Currently, `opensearch.xml` has the following line:
`<ShortName>searx</ShortName>`

In firefox though, `ShortName` is the _key_ under which a search engine is saved. So if I use two searx instances, I would only be able to add one of them as a search engine to firefox. Firefox will not ask me to add searx as a search engine while visiting the second instance (because the key is already taken).

Proposed solution: include something domain-specific to the "ShortName" attribute. Suggestions welcome. Maybe "searx @ example.com"? Or just the domain name, "example.com" ?

**Comment by ibrokemypie** [comment]
+1

**Comment by fabianski7** [comment]
up for 2021

**Comment by unixfox** [comment]
If you set `instance_name` to a different name then you will be able to add a second Searx instance.

**Comment by fabianski7** [comment]
> If you set `instance_name` to a different name then you will be able to add a second Searx instance.

is this something that can be done on the users side?

**Comment by unixfox** [comment]
no, it has to be done on the administrator side of the searx instance. If the administrator didn't do it then we can't do much.

**Comment by fabianski7** [comment]
then the issue should remain open

**Comment by vn971** [comment]
Can we automatically set it based on the domain name, e.g. `searx mydomain.me` ?

**Comment by dalf** [comment]
Multiple virtualhosts can target the same searx instance:
* searx.mydomain.com
* mydomain.com
* mydomain.com/searx

--> which name should be picked to avoid conflict ?

**Comment by vn971** [comment]
@dalf if searx owner hasn't set the domain name explicitly, use the domain that the user asked for, e.g. the domain from the HTTP request? So if I'm accessing `searx.mydomain.com`, then `searx.mydomain.com`.

**Comment by unixfox** [comment]
> Can we automatically set it based on the domain name, e.g. `searx mydomain.me` ?

no because if the administrator wants to customize the displayed name (like most of the public instances) then he won't be able to do that if we change to the name displayed based on the domain name.

> @dalf if searx owner hasn't set the domain name explicitly, use the domain that the user asked for, e.g. the domain from the HTTP request? So if I'm accessing `searx.mydomain.com`, then `searx.mydomain.com`.

We don't know if the owner hasn't specified a domain name because `instance_name` is set as `searx` by default. And no we won't check if it's the default value and then display the domain name instead because this would mean introduce a possible breaking change into some existing setups.

------------

In the end, for all of you, the easiest solution is to ask the Searx instance maintainer to set `instance_name` to a different name and that's it. Or use another public instance that have a different name than the default one.

**Comment by vn971** [comment]
> `instance_name` is set as `searx` by default

Can we avoid setting a value for future searx installations, or introduce a key to derive the name automatically?

On a meta-level, I just don't understand why the issue is closed so opinionatedly, even though there are people who'd want a nicer UI and the current system is just _broken_ for normal Firefox users and lazy/default searx owners. Can we at least open the issue so that we can _search_ for solutions?

**Comment by vn971** [comment]
EDIT: Was a bit tempered, edited the message above -^  (for those who get email notifications)

**Comment by unixfox** [comment]
> > `instance_name` is set as `searx` by default
> 
> Can we avoid setting a value for future searx installations, or introduce a key to derive the name automatically?

It's partially tracked in https://github.com/searx/searx/issues/2252

> On a meta-level, I just don't understand why the issue is closed almost religiously, even though there are people who'd want a nicer UI and the current system is just _broken_ for normal Firefox users and lazy/default searx owners. Can we at least open the issue so that we can _search_ for solutions?

I just gave the solution in https://github.com/searx/searx/issues/494#issuecomment-800372047.

On https://searx.space we have 96 online Searx instances, I bet you are going to find an instance that set a different Searx name and that suit to your needs. If you really love a specific Searx instance you can always try to contact the maintainer by trying to find his/her GitHub profile in the commits here: https://github.com/searx/searx-instances/commits/master or use the `Contact instance maintainer` at the bottom of the page if the instance configured a contact email.

Also, you are free to run your own Searx instance and set a different name if you want to solve this issue by yourself.

**Comment by fabianski7** [comment]
> On https://searx.space we have 96 online Searx instances, I bet you are going to find an instance that set a different Searx name and that suit to your needs. 

I think that is the point of this issue.
There are many instances, and I don't know how many others, but most of the top ten "git" instances don't modify the ShortName tag.

- searx
https://searx.maxxblow.de
https://searx.semipvt.com
https://searx.bar
https://searx.divided-by-zero.eu
https://searx.lnode.net
https://searx.webheberg.info
https://searx.mastodontech.de

- others
https://zoek.anchel.nl (anchel.nl)
https://metasearch.nl (metasearch)
https://privatesearch.app (PrivateSearch.app)
