### ISSUE TITLE
Products category

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#496]
At first sight, this might be difficult to provide in an up-to-date manner with as much of online stores, but many local retailers, the world over, who have their own websites (and indexing system within their websites), would love to provide API in order to have them included in Searx.

**This is something you may demand fees for** (do consider this!)

_We also have the big 3 multinationals; I guess, the Chinese Ali Baba would be wiling to donate or pay something to this project._

**Comment by GreenLunar** [comment]
IMHO, this should be considered for searx.me, this is apart of a business plan to increase profit.

**Comment by Pofilo** [comment]
I don't think that the initial goal of searx is to make money. However, the licence allows everybody to make money using it (as long as the licence is unchanged). So everyone is free to make a products category if wanted.

**Comment by GreenLunar** [comment]
Yes, but I think it would be great if it would be a built-in feature.
It might increase instances also among those who operate "stores" in e-commerce websites.
