### ISSUE TITLE
XSS vulnerability on searx

### ISSUE THREAD

**Issue by ky0p** [searx/searx#499]
Well, this is pretty funny, I was looking for XSS vector through svg tags, so I typed "svg src xss".

And I was not disappointed...

https://searx.me/?q=svg%20src%20xss&categories=general

Don't know why, but it happens in Firefox with the "courgette" theme.

![svg_xss](https://cloud.githubusercontent.com/assets/7203063/12530444/d6fcb2be-c1df-11e5-819a-3a660492d2bc.jpg)

**Comment by pointhi** [comment]
More specific urls:

https://searx.me/?q=!yandex%20svg%20src%20xss&categories=none
https://searx.me/?q=!swisscows%20svg%20src%20xss&categories=none

Seems, the yandex engine and swisscows engine have insufficient input validation, but swisscows cause currently "only" template bugs.

@ky0p Thanks for your report. We already had some of those bugs, and they were currently always solved in the engine. #441 Now it should be clear to move thos validation code into a central place. 

@asciimoo As solution, I would propose unescaping all results (if already escaped) in the engine, and then doing the escaping the collected results in the core at a specific position. (Not in the template!) This should fix all those engine based XSS Bugs

**Comment by asciimoo** [comment]
@pointhi i agree, it's not the first time this bug occurs, but first we should fix these unescaping issues
