### ISSUE TITLE
how do i edit css after i've used docker to setup an instance?

### ISSUE THREAD

**Issue by nixoye** [searx/searx#500]
I have my searx instance up and running and would like to edit my html\css and maybe some defaults.

**Comment by Wonderfall** [comment]
How did you install searx with Docker?  If you want to do so, you have to clone this repository, modify your files, and then build yourself from the embedded Dockerfile.

Another, not recommended option : you can use `docker exec -ti searx_container_name sh` to modify your files directly within the container.

**Comment by nixoye** [comment]
"If you want to do so, you have to clone this repository, modify your files, and then build yourself from the embedded Dockerfile."

can you explain how to do this in laymen terms?

I installed searx with docker with the instructions on https://github.com/asciimoo/searx/wiki/Installation 

> docker pull wonderfall/searx
> docker run -d --name searx -p $PORT:8888 wonderfall/searx

**Comment by Wonderfall** [comment]
Pulling from Docker Hub is OK, but you shoudn't customise searx files with this method.
Everything is already builded and all of your changes will be lost after recreating the container.
This is what you should do instead : 
`git clone https://github.com/asciimoo/searx.git && cd searx`
Then, you do your things... and once you're done : 
`docker build -t whatever/searx .`
Voilà, you'll get your own Docker image of searx. Run a new container with : 
`docker run -d --name searx -p $PORT:8888 whatever/searx`

**Comment by nixoye** [comment]
does it matter if ive already done 

> docker pull wonderfall/searx
> docker run -d --name searx -p $PORT:8888 wonderfall/searx

also, after i edit the html\css and run my image im probably going to find more things i want to edit
how can i make updates to it with starting all over every time?

**Comment by Wonderfall** [comment]
No it doesn't matter, you can even remove this image.
`docker rm wonderfall/searx`
(you can list downloaded images with `docker images` and running containers with `docker ps`)

Whenever you want to update, you have to build a new image and recreate the container.

`docker build -t whatever/searx .`
Here we build a new image, the old one is not referenced as `whatever/searx` anymore.

`docker stop searx && docker rm searx`
We remove the running container.

`docker run -d --name searx -p $PORT:8888 wonderfall/searx`
We run a new container from the new builded image.

As far as I know there's no other way! docker-compose might help you too. Also don't forget to remove your old images, list them with `docker images` and remove them with `docker rmi`.

**Comment by nixoye** [comment]
ok so i 

> git clone https://github.com/asciimoo/searx.git && cd searx
> Then, edit html\css files in /searx/... and once you're done :
> docker build -t whatever/searx .
> Voilà, you'll get your own Docker image of searx. Run a new container with :
> docker run -d --name searx -p $PORT:8888 whatever/searx

to update i have to

> docker build -t whatever/searx .
> Here we build a new image, the old one is not referenced as whatever/searx anymore.

(does ^ keep my edited html\css?)

> docker stop searx && docker rm searx
> We remove the running container.

dont i have to edit the html\css again here and then run

> docker run -d --name searx -p $PORT:8888 wonderfall/searx
> We run a new container from the new builded image.

**Comment by Wonderfall** [comment]
Your local changes are unchanged, you're just building a new image in order to include them.
I advice you to read this : https://docs.docker.com/engine/userguide/dockerimages/

**Comment by NIXOYE** [comment]
@Wonderfall that really just complicates things more. can you just explain when\where i edit the html and css?

**Comment by nixoye** [comment]
If anyone needs help with this here's what you do.

find html/css files which I believe is in searx/searx/static/ and edit the html/css.

build the container with 

`docker build -t nix/searx .`

then stop the container and remove it with 

`docker stop searx && docker rm searx`

and then loaded it back up with 

`docker run -d --name searx -p 80:8888 nix/searx`

That's it!
(Replace "nix" in the first and last command with whatever you want to name your container and the 80 in the last command if you want to use a different port.)

This issue can be closed.
