### ISSUE TITLE
pycurl ?

### ISSUE THREAD

**Issue by dalf** [searx/searx#503]
The current implementation uses Requests to send HTTP requests...
One issue of this : it's need one thread per requests.
So if six engines are used in the general category, for each user request six thread are created and then destroy.

pycurl can send multiple HTTP requests without threads (except for DNS requests).

Some code : 
- http://pycurl.io/docs/latest/curlmultiobject.html
- https://gist.github.com/kaka19ace/b953c4d026381b4ac5cc

I know, @asciimoo you are waiting for the metrology code. Sorry for the long delay.

Take this issue as a side note.

**Comment by asciimoo** [comment]
Very-very interesting idea, curl is much more flexible than requests (and probably also faster). i'll experiment with it =)

**Comment by asciimoo** [comment]
@dalf here's the current state: https://github.com/asciimoo/searx/tree/pycurl
Most of the original functionality works.

Known issues:
- google engine doesn't work (?)
- HTTP compression not implemented.
- Not tested with all engines/encoding

**Comment by dalf** [comment]
Whaa,  nice!!! 
I've added some comments to the code.  My big concern is about the fact that there is one thread :-)
I hadn't  think about it before, but with pycurl and your PR :
- all requests are done in one thread : nice
- all callbacks  are also done on one thread : less nice  since some of them take time

**Comment by asciimoo** [comment]
@dalf, that's what i really like in this solution that we don't have to depend on the not too reliable python threading =)
Result parsing could be threaded, but i can't see the advantage of it, measurements needed

**Comment by dalf** [comment]
## micro benchmark requests vs pycurl (libraries)

### with an local http server

I've [forked and updated an existing repository](https://github.com/dalf/python-client-benchmarks) to micro-benchmark pycurl and requests  ( [edit] the tests in this message have done with this version : https://github.com/dalf/python-client-benchmarks/tree/26b5c69857653db1d3487ab5ca2398139113555e )

One result for 10000 requests for each tests :
- pycurl, saving in a new buffer, connection reuse : 15.6638448238 seconds
- requests, connection reuse : 38.2421951294 seconds
- requests, no connection reuse : 44.2702360153 seconds
- pycurl, saving in a new buffer, no connection reuse : 66.603479147 seconds
- pycurl, saving in the same buffer, connection reuse : 21.8963730335 seconds
- pycurl, no saving, connection reuse : 18.0446221828 seconds

Notes : 
- using the same buffer is slower than using creating a new one. Not sure if it is a real thing or a benchmark issue
- "pycurl connection reuse" means reuse the `Curl` instance.
- pycurl is slower then requests when the connection is not reused.
- it's only an HTTP "benchmark", not an HTTPS benchmark.

### https !

a more realistic test must do HTTPS connections since most of engines used HTTPS connections. 

Results of an ugly HTTPS test on amazon.com with 100 requests : the first 2 tests are both around 30 seconds (a little more for requests). 

One nice way : docker container with nginx + ssl serving a static file. An self signed certificate can be created.

## benchmark of the pycurl branch

Use `ab  -c 1 -n 100 http://127.0.0.1:8888/?q=grouik`

I give the results but they are _not relevants_, may be some search engines have given captcha or errors with 200 requests in a few minutes... 

@asciimoo  : may be from searx.me host, you could do the test since there is a set of different IP.

with the pycurl branch

```
Percentage of the requests served within a certain time (ms)
  50%   1652
  66%   1734
  75%   1778
  80%   1813
  90%   1892
  95%   1997
  98%   2259
  99%   2259
 100%   2259 (longest request)
```

with the master branch

```
Percentage of the requests served within a certain time (ms)
  50%   1263
  66%   1292
  75%   1308
  80%   1320
  90%   1417
  95%   2001
  98%   2045
  99%   2045
 100%   2045 (longest request)
```

**Comment by dalf** [comment]
A possible architecture evolution : 
- everything in one process (uwsgi would be here only to recreate the process)
- a thread pool to run CPU task (typically one thread per CPU core / hyperthread)
- a task queue to submit task to the thread pool 
- a flask interface with multiple threads to parse user requests, do the network requests, as the results arrive, use the thread pool to parse them.  

But there are still a flaws :
- some engine do secondary network requests, that's mean that the thread pool dedicate to CPU tasks will still do network requests.
- in the future, some engine won't need to send network requests (calculator for example)

**Comment by dalf** [comment]
I have create a NGINX docker image to create some more realistic tests.
So to sum up for 10000 requests (time express in second) and response of 20480 bytes : 

|  | HTTP (Flask), total time | HTTP (NGINX), total time | HTTPS (NGINX), total time | HTTPS (NGINX), cpu time |
| --- | --- | --- | --- | --- |
| pycurl, saving in a new buffer, connection reuse | 15.7 | 4.1 | 12.8 | 4.9 |
| requests, connection reuse | 38.2 | 23.18 | 30.3 | 27.0 |
| requests, no connection reuse | 44.3 | 39.7 | 122.8 | 63.4 |
| pycurl, saving in a new buffer, no connection reuse | 66.7 | 56.4 | 130.8 | 32.3 |
| pycurl, saving in the same buffer, connection reuse | 21.9 | 4.5 | 13.7 | 4.8 |
| pycurl, no saving, connection reuse | 18.0 | 4.0 | 13.0 | 4.5 |

Note : The "no connection reuse" speed tests are limited by my laptop CPU (i3-2367M, 1.4Ghz)

With the HTTPS protocol, for each request, when the connection is reused, the pycurl overhead time is 1.2ms, and the requests overhead time is 3ms : requests is twice as slow or same thing, requests uses 2ms more than pycurl (compare to the network time it's nothing).  

For a full HTTPS connection without reusing an existing one, requests seems to be a little faster but it uses twice more CPU (difference of less than 4ms CPU time per request).

**Comment by dalf** [comment]
Another point about pycurl vs requests : certificates trust store. 

requests uses certifi, but [is considering the use of the system trust stores](https://github.com/kennethreitz/requests/issues/2966) by default in 3.0.0

pycurl [don't use certifi by default](https://curl.haxx.se/docs/sslcerts.html).The Curl documentation explains [how to use the Firefox certificates](https://curl.haxx.se/docs/caextract.html). There is [stackoverflow thread](http://stackoverflow.com/questions/21487278/ssl-error-installing-pycurl-after-ssl-is-set) about pycurl and SSL

Honestly I don't know what is the best solution, perhaps the one which use the Firefox store ?

**Comment by asciimoo** [comment]
@dalf, after 34afcf2 the search with pycurl is still 100-200ms slower in average. I don't really know why, any ideas? It reuses connections, shares dns and parses results in threads just like in the original code

**Comment by dalf** [comment]
It seems that the connections are no reused.
I've made some tests with this version : 

``` python
def show_debug(debug_type, debug_msg):
    if debug_type not in [3, 5, 6]:
        logger.debug("debug(%d): %s" % (debug_type, debug_msg.strip()))


def get_new_connection(source_address=None):
    global curl_share

    # pycurl initialization                                                                                                                           
    h = pycurl.Curl()
    h.setopt(pycurl.VERBOSE, 1)
    h.setopt(pycurl.DEBUGFUNCTION, show_debug)
    h.setopt(pycurl.SHARE, curl_share)
    h.setopt(pycurl.ACCEPT_ENCODING, 'deflate, gzip')

    # Follow redirect and send referer                                                                                                                
    h.setopt(h.FOLLOWLOCATION, True)
    h.setopt(h.AUTOREFERER, True)
    h.setopt(h.MAXREDIRS, 5)

    # certifi                                                                                                                                         
    h.setopt(h.CAINFO, certifi.where())

    # consistently use ipv4                                                                                                                           
    h.setopt(h.IPRESOLVE, pycurl.IPRESOLVE_V4)

    if source_address:
        h.setopt(h.INTERFACE, source_address)

    return h
```

On second try : 

```
2016-02-08 00:41:11.142 debug(0): Hostname was found in DNS cache
2016-02-08 00:41:11.143 debug(0): Trying 198.35.26.96...
2016-02-08 00:41:11.357 debug(0): Connected to fr.wikipedia.org (198.35.26.96) port 443 (#1)
```

There is about 200ms lattency which isn't normal is the connection is reused.

**Comment by asciimoo** [comment]
if i set pycurl.VERBOSE, it tells, that there is connection reuse:

```
* Hostname was NOT found in DNS cache
*   Trying 208.80.154.224...
* Connected to en.wikipedia.org (208.80.154.224) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
*        subject: C=US; ST=California; L=San Francisco; O=Wikimedia Foundation, Inc.; CN=*.wikipedia.org
*        start date: 2015-12-10 23:22:05 GMT
*        expire date: 2016-12-10 22:46:04 GMT
*        subjectAltName: en.wikipedia.org matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Organization Validation CA - SHA256 - G2
*        SSL certificate verify ok.
> GET /w/api.php?action=query&list=search&srsearch=south&srprop=timestamp&format=json&sroffset=0&srlimit=1 HTTP/1.1
Host: en.wikipedia.org
Accept: */*
Connection: keep-alive
User-Agent: Mozilla/5.0 (X11; Linux x86; rv:35.0) Gecko/20100101 Firefox/35.0

< HTTP/1.1 200 OK
* Server nginx/1.9.4 is not blacklisted
< Server: nginx/1.9.4
< Date: Sun, 07 Feb 2016 18:13:04 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: HHVM/3.6.5
< X-Content-Type-Options: nosniff
< Cache-control: private, must-revalidate, max-age=0
< X-Frame-Options: SAMEORIGIN
< Vary: Accept-Encoding,X-Forwarded-Proto,Cookie
< Backend-Timing: D=200372 t=1454868784611699
< X-Varnish: 2605412932, 1114822312
< Via: 1.1 varnish, 1.1 varnish
< Age: 0
< X-Cache: cp1066 miss+chfp(0), cp1055 frontend miss+chfp(0)
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Set-Cookie: WMF-Last-Access=07-Feb-2016;Path=/;HttpOnly;Expires=Thu, 10 Mar 2016 12:00:00 GMT
< X-Analytics: https=1;nocookies=1
< X-Client-IP: 84.1.214.170
< Set-Cookie: GeoIP=HU:05:Budapest:47.50:19.08:v4; Path=/; Domain=.wikipedia.org
<
* Connection #0 to host en.wikipedia.org left intact
INFO:werkzeug:127.0.0.1 - - [07/Feb/2016 19:13:25] "POST / HTTP/1.1" 200 -
-===========================END OF FIRST REQUEST====================================-
* Found bundle for host en.wikipedia.org: 0x38f4c01be50
* Re-using existing connection! (#0) with host en.wikipedia.org <<<<<<<<
* Connected to en.wikipedia.org (208.80.154.224) port 443 (#0)
> GET /w/api.php?action=query&list=search&srsearch=south&srprop=timestamp&format=json&sroffset=0&srlimit=1 HTTP/1.1
Host: en.wikipedia.org
Accept: */*
Connection: keep-alive
User-Agent: Mozilla/5.0 (X11; Linux x86; rv:34.0) Gecko/20100101 Firefox/34.0

< HTTP/1.1 200 OK
* Server nginx/1.9.4 is not blacklisted
< Server: nginx/1.9.4
< Date: Sun, 07 Feb 2016 18:13:30 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: HHVM/3.6.5
< X-Content-Type-Options: nosniff
< Cache-control: private, must-revalidate, max-age=0
< X-Frame-Options: SAMEORIGIN
< Vary: Accept-Encoding,X-Forwarded-Proto,Cookie
< Backend-Timing: D=221809 t=1454868810267092
< X-Varnish: 1785515536, 1114948799
< Via: 1.1 varnish, 1.1 varnish
< Age: 0
< X-Cache: cp1065 miss+chfp(0), cp1055 frontend pass+chfp(0)
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Set-Cookie: WMF-Last-Access=07-Feb-2016;Path=/;HttpOnly;Expires=Thu, 10 Mar 2016 12:00:00 GMT
< X-Analytics: https=1;nocookies=1
< X-Client-IP: 84.1.214.170
< Set-Cookie: GeoIP=HU:05:Budapest:47.50:19.08:v4; Path=/; Domain=.wikipedia.org
<
* Connection #0 to host en.wikipedia.org left intact
INFO:werkzeug:127.0.0.1 - - [07/Feb/2016 19:13:50] "POST / HTTP/1.1" 200 -
```

**Comment by dalf** [comment]
The comment about the commit 34afcf254193498e3c0d1411d84e895efb1ebc4b doesn't completely solved the issue about slower response time with pycurl.

Using the response time of the metrology2 branch, I see that slower engine in pycurl are also the engines that have an important response time in the `response` function.

So the issue seems to be related to parsing of the result.

Side note (but it seems to have no effect in response time...) : the wikidata engine in `response` function sends a HTTP request using `requests`. In the case of the pycurl branch, the HTTPS connection can't be reused.

[Edit] I forget, I have try cProfile and pycallgraph : it's not easy to use that since 
- it's involved network, so multiple measure must be done
- pycurl is C module which isn't catched by cProfile

Second note : DNS request are synchronised, see https://curl.haxx.se/dev/internals.html#multi

**Comment by dalf** [comment]
The +200ms exists for google engine even if it is the only engine called. As least the difference seems to be consistent.

From that, I have added logs to the `send_requests` function, and I noticed few points :
- the `self._curl_multi_handler.select(...)` function returns many times for nothing (no result to parse)
- the delay seems to exists when CURL get the HTTP response even with multiple tries. So this is the opposite of my first hypothesis, still I have to investigate. Perhaps give a try with wireshark. 

(Is there a simple way to have a colored and millisecond timestamp logs in the console ? I end up with a messy code wrapping webapp.py... and I have still have duplicate logs)

**Comment by dalf** [comment]
After adding debug a little everywhere in curladapter.py, it seems that there is about  200ms delay when the response is get the network.

```

6410 (0): Found bundle for host www.google.co.th: 0x7fe40c00a430
6411 (0): Re-using existing connection! (#0) with host www.google.co.th
6411 (0): Connected to www.google.co.th (61.91.17.168) port 443 (#0)
6412 (2): GET /search?q=test&start=0&gbv=1&gws_rd=ssl HTTP/1.1
Host: www.google.co.th
Accept-Encoding: deflate, gzip
Connection: keep-alive
Accept-Language: th,th-th
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0
6412 (9): --select exits for nothing0
6512 (9): --select exits for nothing0
6613 (9): --select exits for nothing0
6693 (1): HTTP/1.1 200 OK
6694 (1): Date: Sun, 21 Feb 2016 09:37:56 GMT
6694 (1): Expires: -1
6694 (1): Cache-Control: private, max-age=0
6694 (1): Content-Type: text/html; charset=UTF-8
6694 (1): P3P: CP="This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info."
6694 (1): Content-Encoding: gzip
6695 (0): Server gws is not blacklisted
6695 (1): Server: gws
6695 (1): X-XSS-Protection: 1; mode=block
6695 (1): X-Frame-Options: SAMEORIGIN
6695 (1): Set-Cookie: NID=76=C3EdCg9TWUmZuZKaVzD2Vu4ge9zIsICyCY6bZsPYHv06YrDa6FNdsTheeTuhfanuQcNxduuQnxqNONh8RYWlsVD-JYZB9HpJLYPIFQE1PYbAVZUGzdDWy1PLObpb38Vq; expires=Mon, 22-Aug-2016 09:37:56 GMT; path=/; domain=.google.co.th; HttpOnly
6695 (1): Transfer-Encoding: chunked
6695 (1): 
6696 (9): --select exits for nothing, StringIO buffer size= 835
6748 (9): --select exits for nothing, StringIO buffer size= 5936
6748 (9): --select exits for nothing, StringIO buffer size= 14092
6748 (9): --select exits for nothing, StringIO buffer size= 19233
6749 (9): --select exits for nothing, StringIO buffer size= 19233
6783 (9): --select exits for nothing, StringIO buffer size= 24899
6783 (9): --select exits for nothing, StringIO buffer size= 27720
6784 (9): --select exits for nothing, StringIO buffer size= 30827
6784 (9): --select exits for nothing, StringIO buffer size= 34205
6784 (9): --select exits for nothing, StringIO buffer size= 34205
6785 (9): --select exits for nothing, StringIO buffer size= 37639
6785 (9): --select exits for nothing, StringIO buffer size= 41419
6786 (9): --select exits for nothing, StringIO buffer size= 43731
6786 (9): --select exits for nothing, StringIO buffer size= 48713
6786 (9): --select exits for nothing, StringIO buffer size= 48713
6786 (9): --select exits for nothing, StringIO buffer size= 54158
6787 (9): --select exits for nothing, StringIO buffer size= 61806
6787 (9): --select exits for nothing, StringIO buffer size= 69468
6787 (9): --select exits for nothing, StringIO buffer size= 70845
6787 (0): Connection #0 to host www.google.co.th left intact
6787 (9): finish call (create thread)
6788 (9): finish called (thread started)
6788 (9): self.response = self._extract_response()
6788 (9): return self.callback(self.response)
```

The first number is a timestamp in millisecond

**Comment by dalf** [comment]
with this version https://gist.github.com/dalf/d179276d73de9dd9bf1d : 
- the response time for one engine is the same than master branch
- the response time for three or more engines still have a problem

I've used https://mitmproxy.org/ to get the response time (far more easier to understand than wireshark).

[edit] the pycurl / requests benchmark has updated : https://github.com/svanoort/python-client-benchmarks 
[edit] with pycurl, searx can moved to python 3

**Comment by asciimoo** [comment]
I just found this: https://curl.haxx.se/libcurl/c/CURLMOPT_PIPELINING.html , maybe helps

**Comment by ibrokemypie** [comment]
any progress on this?

**Comment by return42** [comment]
Now we are at python 3 .. are the performance gains still significant?

**Comment by dalf** [comment]
Yes pycurl provides better response times on slow server, moreover
* it can use HTTP/2 or even QUIC.
* it supports SOCKS4/5 proxies.
* on top of it: it is async compatible.

See PR https://github.com/asciimoo/searx/pull/1725 (the requests API has been implemented on top of pycurl, but see the notes).

The big drawback is ... curl dependency: each distro provides a different version of curl with different compilation options. So in the end we don't control the HTTP client.

And the thing that has puzzled me is a segfault with Ubuntu 18.04 under heavy load: https://github.com/asciimoo/searx/pull/1725/files#diff-f873ca5d750fe1d8ca82baef73c8e3f3R20 (take it with a pinch of salt, if it can't be reproduce on another machine).

There is the [aiohttp](https://docs.aiohttp.org/en/stable/client.html) client:
* https://github.com/asciimoo/searx/pull/1724#issuecomment-554285649
* https://gitlab.e.foundation/e/cloud/my-spot/commit/d24d6e3012db55860444cb0dee035e338254ef7a

And there is [httpx](https://github.com/encode/httpx). Most probably the right solution because it is Python solution, it supports async and HTTP/2 (so requests are multiplexed through the same HTTPS connection, so it saves some time on the SSL negotiation, but a benchmark is better that a long sentence).

Another PR has been made about httpx : 
* https://github.com/asciimoo/searx/pull/1856
* see this commit https://github.com/dalf/searx/commit/b387b0655e697a438298ea7020fc9f2078781040 (in another branch).
* but for now:
  * it is not possible to set [the source IP](https://github.com/asciimoo/searx/blob/c83007a6bcd2a7f765e7655b91cc6714fbc4ab01/searx/settings.yml#L54-L58) : https://github.com/encode/httpcore/issues/88
  * it doesn't support [SOCKS proxies](https://github.com/asciimoo/searx/blob/c83007a6bcd2a7f765e7655b91cc6714fbc4ab01/searx/settings.yml#L48-L53): https://github.com/encode/httpx/issues/1019 (but it supports HTTP proxies).
  * perhaps some rough edge: https://github.com/encode/httpx/issues/1017

I close this issue except if we intend to embed a pre-compiled libcurl with searx.
