### ISSUE TITLE
Engine > Science > BASE

### ISSUE THREAD

**Issue by jibe-b** [searx/searx#506]
BASE (Bielefield Academic Search Engine) is a proxy to search in 4000 open access science publications databases (including ArXiV, BiomedCentral). It harvests available databases through the "Open Archives Initiative Protocol for Metadata Harvesting" (OAI-PMH) and stores its own index. 

Search webpage:
https://base-search.net/

About:
https://www.base-search.net/about/en/help.php

API:
http://api.base-search.net/

(OAI: http://oai.base-search.net/ )

In PDF
http://www.base-search.net/about/download/base_interface.pdf

List of other OAI-PMH harvesters:
https://www.openarchives.org/service/listproviders.html

People searching scientific literature would benefit from having both engines "general" and "science" on the same search webpage.

I will suggest this idea to the people behind BASE.

**Comment by jibe-b** [comment]
@asciimoo, I try to aggregate as much information as possible to make it "let's read the spec, let's implement it" in case there is conscensus in adding this engine (and it could be me who implements it, indeed). What information lack?

By the way, I  sent a message to the BASE team.

**Comment by asciimoo** [comment]
@jibe-b thanks the suggestion. It would be a useful engine and seems, it isn't hard to integrate it to searx. Could you work on it? If you can't, i'll do it =)

**Comment by jibe-b** [comment]
Unfortunately, BASE requires authentication. I will discuss with them this point, even though I already guess possible reasons for locking. But I think there should not be neasons for keeping it locked.

Anyhow, there are other search engines that index Open Archives:
- OpenAire.eu [](openaire.eu), a European Union funded harvester and working group
  [limited API doc](http://api.openaire.eu/#cha_http-api)
- OAISTER by worldcat.org [](oaister.worldcat.org)
  [API doc](www.oclc.org/developer/develop/web-services/worldcat-search-api.en.html)

but BASE seems the most mature.

**Comment by pietsch** [comment]
BASE member of staff here. I like your idea, @jibe-b! We will discuss it in our team meeting tomorrow. There might be a way to authenticate searx instances automagically.

**Comment by pietsch** [comment]
Good news: On behalf of the BASE team, I can confirm that BASE Search is interested in becoming integrated with Searx. We will implement an authentication mechanism that is compatible with Searx's distributed, easy-to-install approach, e.g. by matching the User-Agent HTTP header. Please state your preferences and the next steps to take here.

**Comment by asciimoo** [comment]
@pietsch first of all, thanks. Searx tries to avoid tracking, so we prefer accessing the remote content without any kind of authentication, so the https://www.base-search.net/ web form would be the best for us if it's acceptable to you.

**Comment by pietsch** [comment]
@asciimoo Oops, I wrote authentication when I meant authorization. BASE (Bielefeld Academic Search Engine) does not track anyone. Using the Web interface would cause a much higher load on our servers, and there would be no benefits for your users. On the contrary: The search API is faster.

To protect our search API against abuse, we have so far used an IP address whitelist. What we propose is to implement another authorization mechanism for you – perhaps based on the User-Agent HTTP header that Searx probably uses.

**Comment by pietsch** [comment]
I just noticed that @jibe-b's original post contains a link to the wrong API (the OAI API which is for bulk data transfer which does not apply here). This is the search API we offer you: https://api.base-search.net/

**Comment by asciimoo** [comment]
@pietsch sounds reasonable. Do you have a preferred user-agent string or `searx` is okay?

**Comment by pietsch** [comment]
Just leave it as it is ("searx/$version", if I read the code correctly).

**Comment by jibe-b** [comment]
Here is a first try: https://github.com/jibe-b/searx/blob/master/searx/engines/base.py
I have not yet tried it.
1. parsing could be done better. But it seems that results tree has a few flavors. Is there a document describing the result tree? @pietsch 
2. I have not yet found where in searx's code engines are listed to show up in the Preferences tab @asciimoo.

**Comment by asciimoo** [comment]
@jibe-b if you add it to the settings.yml and restart your searx, it'll appear

**Comment by jibe-b** [comment]
thanks @asciimoo. 

> "Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

as I expected it.

**Comment by asciimoo** [comment]
@jibe-b turn on debug mode in settings.yml to get more detailed error messages

**Comment by jibe-b** [comment]
good idea.

I am looking at what the engine must return to satisfy the expectations from the main engine.

**Comment by jibe-b** [comment]
nice debugging interface :) @asciimoo

**Comment by jibe-b** [comment]
Good news, it basically works!

At least it does on my computer, but I added searx.useragent() in the parameters list to match the exception on BASE server.

To be fixed:
- dates are not returned in a standard format (would you consider improve this server-side @pietsch?)
- only the 10 first results are returned (the answer is probably in the API doc)

You were right @asciimoo, it wasn't really hard. What take some time is to dive into searx's code, but now I have an idea of the structure of the code.

**Comment by pietsch** [comment]
Hi @jibe-b, you seem to have found the documentation – everything is in the PDF. I would have thought all dates are in standard format. Please send me specimens by e-mail. We could make changes if they don't break existing API clients.

**Comment by jibe-b** [comment]
@pietsch For the moment, I have seen <str "name":"dcdate"> either in a %Y-%m-%d %H:%M:S format or %Y and searx takes only the former (I still need to check the exact date format expected by searx).

I guess they are stored this way after harvesting, as replacing 2014 by 2014-01-01 00+00 does not have the same meaning. Depending on your answer, I may write a function that does the job of adding this pseudo-information.

**Comment by jibe-b** [comment]
@pietsch, how should I write the http request in order to obtain more than 10 results?

**Comment by jibe-b** [comment]
@pietsch, how should I write the http request in order to obtain more than 10 results?

**Comment by pietsch** [comment]
@jibe-b Please look for the parameters `hits` and perhaps `offset` on page 4 of the documentation.

**Comment by jibe-b** [comment]
Dear @pietsch and @asciimoo, the base engine works on my machine :)

https://github.com/jibe-b/searx/blob/master/searx/engines/base.py

BASE returns published dates as %Y or %Y-%m or %Y-%m-%d so I simply added exception handling of datetime.strptime().

Do I make a pull request?

**Comment by pietsch** [comment]
@jibe-b You wrote “%Y or %Y-%m or %Y-%m-%d”. The latter two are identical.

**Comment by jibe-b** [comment]
They don't: 2016 or 2016-03 or 2016-03-17.

Anyway, it seems from the tests I made that the base api returns dcdates in these formats, so the engine is ok with them.

**Comment by jibe-b** [comment]
@pietsch in its current state, the engine enables to perform basics search.

Next, I will try to add regex search on the query in order to enable faceted search like "author:Einstein -> in URL dccreator=Einstein"

**Comment by jibe-b** [comment]
@pietsch though I am an open access advocate, I chose not to add OA boost in the engine (I consider adding a facet-like oa:true or maybe as a searx plugin). Is it wise or would you advise OA boost by default?

**Comment by pietsch** [comment]
@jibe-b OA boost is the default in the BASE web interface. As a boost, it only affects ranking, so non-OA results are still included. If you want Searx to behave similarly, you should keep the OA boost on. If you think Searx users will prefer results with full text available, then you should keep the OA boost on, too. I think only a small minority will be interested in citations without full text.

**Comment by asciimoo** [comment]
@jibe-b nice! please open a pull request, then I can add review notes to it

**Comment by jibe-b** [comment]
Ok @pietsch, I agree that the BASE default should be kept.

The [API specification](https://www.base-search.net/about/download/base_interface.pdf) indicates "Default: without boosting" (p4). I will add oa boosting to the engine.

**Comment by pietsch** [comment]
The API specification should still be correct.

**Comment by jibe-b** [comment]
It is @pietsch! I was mistaken. The API has OA boost deactivated by default, and the web interface activates OA boost.

**Comment by pietsch** [comment]
@asciimoo @jibe-b Good news: As discussed [before](#issuecomment-185281639), I have added a special authorization for Searx to the BASE HTTP API so that users do not have to register their IP address with BASE.

**Comment by jibe-b** [comment]
Thanks @pietsch! I'll try this evening on another machine/IP.

**Comment by asciimoo** [comment]
@pietsch thank you so much the collaboration and your help to make searx a more useful tool
