### ISSUE TITLE
"exec format error" with docker in ARM (Cubietruck)

### ISSUE THREAD

**Issue by ghost** [searx/searx#514]
Hello,

thanks for this great search engine! 

After setting up docker on my Cubietruck running Armbian (Debian8) following https://github.com/umiddelb/armhf/wiki/Get-Docker-up-and-running-on-the-RaspberryPi-%28ARMv6%29-in-three-steps I've tried to run searx using docker.

Unofrtunately after

```
git clone https://github.com/asciimoo/searx.git
cd searx
docker build -t searx .
```

I get

```
$ docker build -t searx .
Sending build context to Docker daemon 9.021 MB
Step 1 : FROM alpine:3.3
 ---> 90239124c352
Step 2 : MAINTAINER searx <https://github.com/asciimoo/searx>
 ---> Using cache
 ---> a0724a20a9a5
Step 3 : LABEL description "A privacy-respecting, hackable metasearch engine."
 ---> Using cache
 ---> 0c730b5bb60a
Step 4 : ENV BASE_URL False IMAGE_PROXY False
 ---> Using cache
 ---> 6fd37303a372
Step 5 : EXPOSE 8888
 ---> Using cache
 ---> dedd12586d2d
Step 6 : WORKDIR /usr/local/searx
 ---> Using cache
 ---> b1e53153461f
Step 7 : CMD /usr/bin/tini -- /usr/local/searx/run.sh
 ---> Using cache
 ---> 90dd6d1a32e2
Step 8 : RUN adduser -D -h /usr/local/searx -s /bin/sh searx searx  && echo '#!/bin/sh' >> run.sh  && echo 'sed -i "s|base_url : False|base_url : $BASE_URL|g" searx/settings.yml' >> run.sh  && echo 'sed -i "s/image_proxy : False/image_proxy : $IMAGE_PROXY/g" searx/settings.yml' >> run.sh  && echo 'sed -i "s/ultrasecretkey/`openssl rand -hex 16`/g" searx/settings.yml' >> run.sh  && echo 'python searx/webapp.py' >> run.sh  && chmod +x run.sh
 ---> Running in 1e1aefb31480
exec format error
Cannot start container 1e1aefb31480bc33aa9bc6910397aa07f772584aeccbb958d0bef316685a3a37: [9] System error: exec format error
```

Will it work like this using docker on ARM systems?

**Comment by dalf** [comment]
Is it related to the fact that alpine contains x86 binary, and the Cubietruck has an ARM cpu ?
Is there an official Alpine docker image for ARM ?
I found this one : https://hub.docker.com/r/dduportal/rpi-alpine/ which seems to be build for Raspberry Pi.

@saljut7 : if you want to try this image, replace this first line of Dockerfile by
`FROM dduportal/rpi-alpine`

Really not sure if it will work or not...

[Edit] I found this project : https://github.com/multiarch/alpine

**Comment by ghost** [comment]
Thank you so much. Build process just started and since 5minutes no errors. Will report if it works in ... well, when it's done. ;)

**Comment by ghost** [comment]
```
user@cubietruck:/$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
b631461262f8        searx               "/usr/bin/tini -- /us"   12 minutes ago      Up 9 minutes        0.0.0.0:8888->8888/tcp   searx-noproxy
user@cubietruck:/$ 
```

:) :) :)

So building process ended just fine.
Well, another problem was totally not related to searx but. I didn't know that Docker reconfigures your iptables settings so after editing my standard settings and applying `iptables-restore` I couldn't run docker-searx anymore. https://fralef.me/docker-and-iptables.html was very helpful (for others with the same problem:
Append

```
-A FORWARD -i docker0 -o eth0 -j ACCEPT
-A FORWARD -i eth0 -o docker0 -j ACCEPT
```

to your iptables settings and 
`-A INPUT -p tcp -m tcp --dport 8888 -s 0.0.0.0/0 -j ACCEPT`
for the case docker-searx is listening to port 8888 - and don't forget to forward the port in your router!).

Well, anyway searx only works for me starting it via
`docker run -d --name searx-noproxy -p 8888:8888 -e IMAGE_PROXY=True searx`
 at the moment. _**http**://my.ddns.net:8888_ works just fine.

Using
`docker run -d --name searx -e IMAGE_PROXY=True -e BASE_URL=https://my.ddns.net searx`
and trying _**https**://my.ddns.net:8888_ gives me

> Unable to connect
> Iceweasel can't establish a connection to the server at my.ddns.net:8888

Before trying some more hours let me guess: I need to run another docker container for Nginx and link it to the searx container?

**Comment by dalf** [comment]
Related to docker.
Reopen if you need.
