### ISSUE TITLE
Proxying via Tor

### ISSUE THREAD

**Issue by ghost** [searx/searx#519]
Is it possible to proxy to the search engines via Tor using socks5 to port 9050? I've tried a few things and so far none of them have worked.

**Comment by GreenLunar** [comment]
Also consider to forge/switch timezone once IP changes or every X minutes.

**Beware of changing time itself**, because Tor would not let you in to the Tor network once your time has an unreasonable difference (e.g. a difference of an hour).

Notice that only after I setup system clock to a reasonable time, Tor would connect.

```
Apr 13 16:55:29.000 [notice] Application request when we haven't used client functionality lately. Optimistically trying directory fetches again.
Apr 13 17:56:09.000 [notice] Your system clock just jumped 3595 seconds forward; assuming established circuits no longer work.
```

```
$ tailf /var/log/tor/tor.log
Apr 13 16:54:48.000 [notice] Bootstrapped 5%: Connecting to directory server
Apr 13 16:54:48.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Apr 13 16:54:49.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
Apr 13 16:54:49.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
Apr 13 16:54:50.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no recent usable consensus.
Apr 13 16:54:50.000 [notice] Bootstrapped 25%: Loading networkstatus consensus
Apr 13 16:54:51.000 [notice] Application request when we haven't used client functionality lately. Optimistically trying directory fetches again.
Apr 13 16:54:52.000 [notice] I learned some more directory information, but not enough to build a circuit: We have no recent usable consensus.
Apr 13 16:55:05.000 [notice] Application request when we haven't used client functionality lately. Optimistically trying directory fetches again.
Apr 13 16:55:29.000 [notice] Application request when we haven't used client functionality lately. Optimistically trying directory fetches again.
Apr 13 17:56:09.000 [notice] Your system clock just jumped 3595 seconds forward; assuming established circuits no longer work.
Apr 13 17:56:09.000 [notice] Tried for 3680 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3681 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3681 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3681 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3681 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3678 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3664 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3664 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3664 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:09.000 [notice] Tried for 3640 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
Apr 13 17:56:11.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Apr 13 17:56:11.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Apr 13 17:56:12.000 [notice] Tor has successfully opened a circuit. Looks like client functionality is working.
Apr 13 17:56:12.000 [notice] Bootstrapped 100%: Done
```

**Comment by MarcAbonce** [comment]
The requests library doesn't handle SOCKS, only HTTP(S), I think.

What worked to me was to combine Privoxy with Tor.
So you proxy searx (from the settings) to the port where privoxy is listening and you configure privoxy to forward everything to tor's port.
Also, don't forget to increase the timeouts in searx to account for the slower responses.

I'm no security expert, so I don't know how secure is this configuration but it seems to work.

**Comment by dalf** [comment]
Just as a reminder, some engines make HTTP request, so the exit Tor node can see the request in clear (if the engine is used directly or in a category).

The engines that make HTTP request at first sight : 
- faroo
- filecrop
- general-file
- nyaa
- subtitleseeker

**Comment by GreenLunar** [comment]
Perhaps there should be added a note for these search engines at bottom of page, or in configuration files.

**Comment by dalf** [comment]
The last version of `requests` adds the support of SOCK5 proxy (version 2.10.0) : 
http://docs.python-requests.org/en/master/user/advanced/#socks

[requirements.txt](https://github.com/asciimoo/searx/blob/master/requirements.txt) needs to be modified to use the right `requests` version and to add `requests[socks]`

A hack about HTTP requests: send HTTP requests to a dummy / non existant proxy.

**Comment by ibrokemypie** [comment]
google has issues with tor and appears to throw a captcha every second request, something to consider

**Comment by ghost** [comment]
True, but other search engines are available.

**Comment by GreenLunar** [comment]
Which is even better, if users would be satisfied with results that are not provided by it.

**Comment by MarcAbonce** [comment]
Also frinkiac, 1x and torrentz request captcha. The only thing that comes in my mind would be to relay the captcha to the user, so they can solve it themselves (#520). However, this would become annoying very quickly and users would blame us, rather than google et al. for requesting captchas.

**Comment by unixfox** [comment]
Pass the tor socks proxy in the settings, and it will work.
