### ISSUE TITLE
disabling yahoo as one of the default search engines.

### ISSUE THREAD

**Issue by nixoye** [searx/searx#521]
I went into settings.yml and added `disabled: True` under the yahoo section,
 built the container with 
`docker build -t whatever/searx .`
then ran 
`docker stop searx && docker rm searx`
and then loaded it back up with 
`docker run -d --name searx -p 80:8888 whatever/searx`

but whenever i do a search yahoo is still being used.

**Comment by ibrokemypie** [comment]
is the settings.yml being replaced by a new one? or is it simply being ignored?

**Comment by nixoye** [comment]
@PwnArt1st its just being ignored. I also want to remove deviantart as a default engine as its results are pretty awful. I added the `disabled : True` to it also but still no luck. Am I supposed to do something else?

**Comment by Wonderfall** [comment]
You're saying you built an image named `whatever/searx`. But you ran a container with the image `wonderfall/searx`, [which exists on Docker Hub](https://hub.docker.com/r/wonderfall/searx/), so Docker will download and then use this image instead of the one you've just built.

Am I right or did you make a mistake when describing your problem?

**Comment by nixoye** [comment]
@Wonderfall your right, testing again.
 I edited my first post so i could copy and paste it to try it

now when i do `docker start 633f70901ae25309628ca451b85e530ffe7ec8ae21c430429e2fdc234f8f3e20`
i get `633f70901ae25309628ca451b85e530ffe7ec8ae21c430429e2fdc234f8f3e20`in the next line but it doesnt start

if i do `docker run whatever/searx` I get

```
sed: searx.setting.yml: No such file or directory
Traceback (most recent call last):
  File "searx/webapp.py", line 826, in <module>
    run()
  File "searx/webapp.py", line 781, in run
    host=settings['server']['bind_address']
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 656, in inner
    fd=fd)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 550, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 464, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied

```

**Comment by dalf** [comment]
It's working for me :

``` sh
docker build -t dalf/searx .
docker run -d --name searx -p 80:8888 dalf/searx
```

About your logs : 
`sed: searx.setting.yml: No such file or directory` : was the Docker image built without error ?

`socket.error: [Errno 13] Permission denied` : may be related to be previous error, missing settings.yml

If I do `docker run -t -i dalf/searx ls searx`, the results is 

``` sh
__init__.py         plugins             search.py           testing.py
autocomplete.py     poolrequests.py     settings.yml        translations
data                preferences.py      settings_robot.yml  utils.py
engines             query.py            static              version.py
languages.py        results.py          templates           webapp.py
```

I can see settings.yml, what about your Docker image ?

You can try `docker run -t -i dalf/searx cat searx/settings.yml` to make sure your modifications have been taken into account.

**Comment by nixoye** [comment]
@dalf hmm seems like changing the name from whatever/searx to tstnix/searx works. or anything other than whatever/searx works. Thanks for the help.

this can be marked as closed @Wonderfall
