### ISSUE TITLE
vieweing the searx.me logo

### ISSUE THREAD

**Issue by juanpide** [searx/searx#524]
Hello.

The searx.me icon/logo doesn't appear on any brwoser search engine settings nor metasearch extension,  instead we see an ugly long name o grey rectangle.
All other search engines do have a recognizable one.

https://i.imgur.com/elSkca2.jpg
http://images.pcworld.com/images/article/2012/02/search1-11087297.png

I think it's not a user configuration problem but a problem related with the searx.me site.

**Comment by GreenLunar** [comment]
I think Searx should also offer a 16x16 icon.  Qupzilla displays a default search icon while Otter Browser displays Searx logo.

**Comment by ibrokemypie** [comment]
Does it work with any other instance? I believe it is an issue in implementation on browser development end. Chrome allows you to set custom search engines and I believe there are extensions that allow that on Firefox as well, although Internet Explorer is locked to the presets afaik, although why you'd use IE is beyond me.

**Comment by kvch** [comment]
This is already implemented. See the image of Firefox attached: 

![image](https://user-images.githubusercontent.com/3876218/84688084-0337a400-af3f-11ea-9ced-53a2bb0504cd.png)

Also, searx.me is no longer a search engine. It is a landing page for the searx project.
