### ISSUE TITLE
crash on specific search [BUG]

### ISSUE THREAD

**Issue by prolibre** [searx/searx#527]
Online exemple : https://www.heraut.eu/search/
go to **news** and search "_yahoo lent_"

Result : Internal Server Error

Logs:

> ERROR:searx.search:engine crash: google news
> Traceback (most recent call last):
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.1-py2.7.egg/searx/search.py", line 40, in search_request_wrapper
>     ret = fn(url, *_kwargs)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.1-py2.7.egg/searx/poolrequests.py", line 82, in get
>     return request('get', url, *_kwargs)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.1-py2.7.egg/searx/poolrequests.py", line 75, in request
>     response = session.request(method=method, url=url, *_kwargs)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
>     resp = self.send(prep, *_send_kwargs)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 582, in send
>     r = dispatch_hook('response', hooks, r, *_kwargs)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
>     _hook_data = hook(hook_data, *_kwargs)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.1-py2.7.egg/searx/search.py", line 117, in process_callback
>     search_results = callback(response)
>   File "/usr/local/searx/searx-ve/lib/python2.7/site-packages/searx-0.8.1-py2.7.egg/searx/engines/google_news.py", line 50, in response
>     if not search_res.get('responseData', {}).get('results'):
> AttributeError: 'NoneType' object has no attribute 'get'
> ERROR:searx.webapp:Exception on / [POST]
> Traceback (most recent call last):
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.1-py2.7.egg/searx/webapp.py", line 407, in index
>     result['pretty_url'] = prettify_url(result['url'])
>   File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.1-py2.7.egg/searx/utils.py", line 222, in prettify_url
>     return u'{0}[...]{1}'.format(url[:chunk_len], url[-chunk_len:])
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
> [pid: 27828|app: 0|req: 492/2391] IP.IP.IP.IP () {44 vars in 1202 bytes} [Tue Mar 29 15:47:06 2016] POST /search/ => generated 291 bytes in 900 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)

**Configuration :**
Debian
Python 2.7.9
[GCC 4.9.2]
_
locale -a_
C
C.UTF-8
en_US.utf8
eu_FR
eu_FR.iso88591
eu_FR.utf8
franÃ§ais
french
fr_FR
fr_FR@euro
fr_FR.iso88591
fr_FR.iso885915@euro
fr_FR.utf8
fr_FR.utf8@euro
POSIX

Thanks for your work.

Anthony

**Comment by prolibre** [comment]
Surprise...
Bug with Firefox 45.0.1 (standard version)
but no bug in Firefox Dev edition (47.0a2)
No bug in chrome.

I can reproduce the bug in instance : https://framabee.org/  but not on all engines

**Comment by ghost** [comment]
While debugging this I've found a similar problem. Steps to reproduce:
1. Go to the settings page, set your search language to fr_FR.
2. Search for "yahoo lent" in the news category.

I am able to reproduce this bug in Firefox 45.0.1 and Midori 0.5.11, both on https://searx.me/ and my local installation.

Stacktrace:

> /home/neko/searx/searx/results.py:32: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
>   return unquote(path_a) == unquote(path_b)
> ERROR:**main**:Exception on / [POST]
> Traceback (most recent call last):
>   File "/home/neko/searx/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/neko/searx/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/neko/searx/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/neko/searx/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/neko/searx/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "searx/webapp.py", line 461, in index
>     favicons=global_favicons[themes.index(get_current_theme_name())]
>   File "searx/webapp.py", line 344, in render
>     '{}/{}'.format(kwargs['theme'], template_name), **kwargs)
>   File "/home/neko/searx/env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
>     context, ctx.app)
>   File "/home/neko/searx/env/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
>     rv = template.render(context)
>   File "/home/neko/searx/env/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/home/neko/searx/env/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/neko/searx/searx/templates/oscar/results.html", line 1, in top-level template code
>     {% extends "oscar/base.html" %}
>   File "/home/neko/searx/searx/templates/oscar/base.html", line 70, in top-level template code
>     {% block content %}
>   File "/home/neko/searx/searx/templates/oscar/results.html", line 22, in block "content"
>     {% include get_result_template('oscar', result['template']) %}
>   File "/home/neko/searx/searx/templates/oscar/result_templates/videos.html", line 3, in top-level template code
>     {{ result_header(result, favicons) }}
>   File "/home/neko/searx/searx/templates/oscar/macros.html", line 14, in template
>     <h4 class="result_header">{% if result.engine~".png" in favicons %}{{ draw_favicon(result.engine) }} {% endif %}<a href="{{ result.url }}" rel="noreferrer">{{ result.title|safe }}</a></h4>
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 54: ordinal not in range(128)

**Comment by asciimoo** [comment]
seems it's an encoding issue again - probably the url contains utf characters

**Comment by prolibre** [comment]
Yes thank you @ukwt. I did not say (sorry).
I am French and the default encoding is fr_FR

**Comment by prolibre** [comment]
good ! it works. Thank you very much and good day.
