### ISSUE TITLE
Cannot download opensearch.xml

### ISSUE THREAD

**Issue by sachaz** [searx/searx#532]
Searx 0.8.1 on Debian Jessie
On the about page: FAQ How to add to firefox? Install link is not working. I cannot download https://searx.aquilenet.fr/opensearch.xml

**Comment by dalf** [comment]
For some reason there is no HTTP header in the response, and the content seems to be keep gziped with firefox (Chrome or curl seems to handle that).
Seems to be related to https://github.com/asciimoo/searx/issues/209
Try this in the apache configuration : 

```
  <FilesMatch \.xml$>
  SetEnv no-gzip 1
  </FilesMatch>
```

**Comment by pointhi** [comment]
#318 seems also to be releated

**Comment by sachaz** [comment]
Thanks dalf's apache conf fixes this issue
pointhi's sould work but I need deflat...

<3 <3 <3

**Comment by sut12** [comment]
I had the same Problem. I think dalfs solution should be mentoined in the installation wiki.
