### ISSUE TITLE
Little spelling mistake in french translation

### ISSUE THREAD

**Issue by ghost** [searx/searx#533]
https://github.com/asciimoo/searx/blob/master/searx/translations/fr/LC_MESSAGES/messages.po#L589

```
msgid "currently, there are no cookies defined."
msgstr "il n'y a pas de cookies définit pour le moment."
```

It should be :

> il n'y a pas de cookies défini**s** pour le moment.

**Comment by pointhi** [comment]
Localisation is handled on transifex: https://www.transifex.com/asciimoo/searx/

When you are interested, you can fix this error by yourself.

**Comment by ghost** [comment]
I believe this has been resolved, perhaps it should be closed?

**Comment by dalf** [comment]
I confirm : resolved.
https://github.com/asciimoo/searx/blob/master/searx/translations/fr/LC_MESSAGES/messages.po#L679
