### ISSUE TITLE
A crash when opening popup images

### ISSUE THREAD

**Issue by metal3d** [searx/searx#535]
I installed searx here: https://search.metal3d.org and I'm surching "gopher golang" in "images"

Images are ok but when I click on image, popup appears and the "raw content" of image is displayed (not always)

In my console:

```
ERROR:searx.search:engine crash: google images
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 40, in search_request_wrapper
    ret = fn(url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 82, in get
    return request('get', url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 75, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 582, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/searx/searx/search.py", line 117, in process_callback
    search_results = callback(response)
  File "/usr/local/searx/searx/engines/google_images.py", line 52, in response
    data_url = result.xpath('./a/@href')[0]
IndexError: list index out of range
```

Any idea ?

Thanks a lot

**Comment by metal3d** [comment]
Just a precision, that's a docker image I built myself from you Dockerfile :)

**Comment by metal3d** [comment]
PS: I just pull master, seeing that a new commit should change the problem 9331fc28a8ac2f898a437d126ee59353f7f1bfde => but it doesn't fix my problem

**Comment by kvch** [comment]
Are you sure pulled master properly? The trace shows that the error comes from the line which was deleted in the commit you referenced.

**Comment by metal3d** [comment]
Yes sorry, I did a new build with no cache. The error is now from another provider.

Example: https://search.metal3d.org/?q=gopher+golang&category_images=on then click the image:

![image](https://cloud.githubusercontent.com/assets/100080/14391868/bc2ea742-fdbe-11e5-8cd5-06ed6d833086.png)

I've got:

![image](https://cloud.githubusercontent.com/assets/100080/14391880/ca21a71e-fdbe-11e5-85d7-fd981af16719.png)

**Comment by metal3d** [comment]
Great ! it' working like a charm now. Thanks a lot !

PS: if you want to add my server in the https://github.com/asciimoo/searx/wiki/Searx-instances page, no problem

**Comment by asciimoo** [comment]
@metal3d thanks, if you consider it as a public instance, feel free to add to the wiki

**Comment by metal3d** [comment]
I'll do it, no problem. And a big thanks for that project :)
