### ISSUE TITLE
implement/improve anti abuse systems

### ISSUE THREAD

**Issue by pointhi** [searx/searx#543]
I notice much abuse on my engine (and I think also the other searx engines) for content ranking (I think, but the search queries are in my view to generic for specific products).

I think it's clear abuse is negativ for normal searx users. Beside of bounded ressources which those requests need, some search engines are blocking us because of the big amout of requests. I also think response time could suffer because of abuse.

I haven't seen abuse of the image_proxy system yet, but it's also not so interresting as the generic search, and secured with hash values.

I would propose to add hash verification to as much parts of searx as possible. And because of that also something like an api system to allow external services based on searx.

Also It would be a good idea to allow extended uwsgi logging (which shows things like, what format and page was requested via POST), to allow fail2ban rulesets for POST requests.

Later it would be a good idea to implement intelligent filters. Most abuses are following predictable patterns like:
- similar search queries over a long time
- always the same request methodology
  - page 1...10 with the same query, then the same with another ip and a similar search query
  - page 1 of rss feed with logical equivalent queries from 1. ip (hard to block, probably adding a limit of rss feeds per ip. One ip for example requested about 1400 rss feeds)

**Comment by pointhi** [comment]
The bots are causing more and more problems now, which results in regular blocks of many engines.

I think the only way to detect such abuse automatically would be creating lots of metrics for each user (I collected about 30 metrics which could probably be used for bot detection), and use a self learning/responding system to do real time tracking of abuse.

I'm aware this is not pretty helpful for privacy, but this is the best idea I have.

**Comment by asciimoo** [comment]
Yes, the problem exists, but there is no good solution. Another possibility is throwing captcha after a specified amount of requests per minute.

**Comment by pointhi** [comment]
the problem is, the abuse (in my case) seems to be done by a botnet (Mostly single ip's), but follows other pattern (currently, the requests are always done with format=rss, at least by one of those bots, and mostly coming from russia).

My Idea would be, bot's normaly create some specific pattern, which should occour in some metrics. (Like an abnormal count of `format=rss` combined with russian search queries as GET-Request and always the same server string, but different ip's).

Using algorithms, which look for gatherings in all metrics, and cross checking those gatherings with other metrics should be able to create rules which can be used to detect bot behaviour. (most Bot's should normaly be found in the same gathering groups of different metrics).

When I have time, I would do some tests how good this work on real live data. The Apache logs should give me more than enough metrics for first tests.

**Comment by asciimoo** [comment]
I've created a filtering middleware and using it on searx.me.
https://github.com/asciimoo/filtron

it can effectively work even with a basic ruleset:

``` json
[
    {
        "name": "search request",
        "interval": 60,
        "limit": 60,
        "filters": ["Param:q", "Path=^(/|/search)$"],
        "actions": [
            {"name": "log",
             "params": {"destination": "stderr"}},
            {"name": "block",
             "params": {"message": "Rate limit exceeded"}}
        ],
        "subrules": [
            {
                "name": "rss/json limit",
                "interval": 60,
                "limit": 5,
                "filters": ["Param:format=(rss|csv|json)"],
                "actions": [
                    {"name": "log",
                     "params": {"destination": "stderr"}},
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            },
            {
                "name": "useragent limit",
                "interval": 60,
                "limit": 15,
                "aggregations": ["Header:User-Agent"],
                "actions": [
                    {"name": "log",
                     "params": {"destination": "stderr"}},
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            }
        ]
    }
]
```

**Comment by cy8aer** [comment]
I tried it with uwsgi http port and apache reverse proxying via filtron and get:
`Response error: the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection HTTP/1.1 200 OK`

often. Any hints to solve this? Reverse proxying apache -> uwsgi http port works smooth.

**Comment by asciimoo** [comment]
@cy8aer what is your uwsgi version (`uwsgi --version`)? I'm using the same setup on searx.me (except nginx instead of apache) with uwsgi 2.0.13.1, and it works well for me.
The above error message happens if a new request sent after connection keep-alive ended. I'm not sure how is it possible, because filtron disables http keep-alives: https://github.com/asciimoo/filtron/blob/master/proxy/proxy.go#L15

**Comment by cy8aer** [comment]
Standard Jessie 2.0.7.  I guess it is a frontend problem and the apache closes the connection to the uswgi.
It is a comprehension problem for me. We need a cascading of reverse proxies (so no mod_uwsgi for apache), right? Then I configure the apache proxy connecting to the filtron and then filtron to the locally running uwsgi of searx with an open http port.

Filtron makes no keep-alive to searx but what makes apache by default (or ist this some misunderstanding by me that apache has some influence?)

Maybe we need an reference documentation for the whole proxy chain in the classical installation document?

**Comment by asciimoo** [comment]
@cy8aer yap, you have to use reverse proxy both between apache-filtron and filtron-uwsgi/searx.
uwsgi part: http://uwsgi-docs.readthedocs.io/en/latest/HTTP.html#the-uwsgi-http-https-router - see "Embedded mode".

**Comment by cy8aer** [comment]
Yeah, that is the document I try it with. For me it fails with both http and http-socket. The first connection to the server works and with starting up the first search it creates the error. I tried http-keepalive on the uwsgi side but this makes no effect (just for playing around).

**Comment by cy8aer** [comment]
next test scenario: Going directly to the filtron port (no apache in front). Still the same problem. So it is definitely a problem filtron -> uwsgi for me. Sniffing the connection shows a direct tcp-rst from the uwsgi server with the second request and filtron puts HTTP 429 Too many requests to the front.

**Comment by asciimoo** [comment]
@cy8aer 429 means filtron blocks the requests because configured  rate limit is exceeded. Increase limits in filtron config to avoid this message. So, probably the keep-alive issue exists between apache and filtron.

**Comment by unixfox** [comment]
Filtron is the tool for protecting against abuses: https://github.com/asciimoo/filtron.
