### ISSUE TITLE
Issues creating engines 

### ISSUE THREAD

**Issue by freedomtrain** [searx/searx#548]
I m having some difficulty adding engines. 
I add the new engine to /searx/searx/engines
I add the new engines to settings....
I stop and restart the service.
I receive an error message "Internal Server Error"
I have to delete t the new entry in settings to have  searx working again....
I noticed that this happens if I add any new engine to into the settings file.

Has anyone had this issue ?

Thanks

**Comment by kvch** [comment]
Hey! Turn on debug logging as described in the documentation.
https://asciimoo.github.io/searx/dev/quickstart.html#tips-for-debugging-development

**Comment by freedomtrain** [comment]
I have almost figured it out…..
Below is what I have in the engine file…….. can you take a look…..I think that the # do search-request section is not correct 

from urllib import urlencode
from lxml.html import fromstring
from searx.engines.xpath import extract_text

# engine dependent config

categories = ['news',]
paging = True

# search-url

base_url = 'http://sparks.leola.me/'
search_url = base_url + '?action=search&query={query}&search_more=feeds'

# specific xpath variables

result_xpath = '//div[@class="result results_links results_links_deep web-result "]'  # noqa
url_xpath = './/a[@class="result__a"]/@href'
title_xpath = './/a[@class="result__a"]'
content_xpath = './/a[@class="result__snippet"]'

# do search-request

def request(query, params):
    offset = (params['pageno'] - 1) \* 30

    if params['language'] == 'all':
        locale = 'en-us'
    else:
        locale = params['language'].replace('_', '-').lower()

    params['url'] = url.format(
        query=urlencode({'q': query, 'kl': locale}),
        offset=offset)

    return params

# get response from search-request

def response(resp):
    results = []

    doc = fromstring(resp.text)

    # parse results
    for r in doc.xpath(result_xpath):
        try:
            res_url = r.xpath(url_xpath)[-1]
        except:
            continue

        if not res_url:
            continue

        title = extract_text(r.xpath(title_xpath))
        content = extract_text(r.xpath(content_xpath))

        # append result
        results.append({'title': title,
                        'content': content,
                        'url': res_url})

    # return results
    return results

                         

 

On April 27, 2016 at 11:51:55 PM, Noémi Ványi (notifications@github.com) wrote:

Hey! Turn on debug logging as described in the documentation.
https://asciimoo.github.io/searx/dev/quickstart.html#tips-for-debugging-development

**Comment by asciimoo** [comment]
try this:

``` python
search_url = base_url + '?action=search&{query}&search_more=feeds'

# do search-request
def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params
```

**Comment by freedomtrain** [comment]
I m receiving this message in the log file 

File "/usr/local/searx/searx/engines/sparksnews.py", line 40, in request
    params['url'] = search_url.format(query=urlencode({'query': query}))
NameError: global name 'urlencode' is not defined

This is the content of sparksnews.py

from urllib import quote_plus
from json import loads
from lxml import html
from cgi import escape
from dateutil import parser

# engine dependent config

categories = ['news',]
paging = True

# search-url

base_url = 'http://sparks.leola.me/'
search_url = base_url + '?action=search&{query}&search_more=feeds'
                         

# specific xpath variables

results_xpath = '//article'
link_xpath = './/small[@class="time"]//a'
title_xpath = './/h2//a//text()'
content_xpath = './/p//text()'
pubdate_xpath = './/time'

# do search-request

def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params

# get response from search-request

def response(resp):
    results = []

    search_res = loads(resp.text)

    # return empty array if there are no results
    if not search_res.get('responseData', {}).get('results'):
        return []

    # parse results
    for result in search_res['responseData']['results']:
        # parse publishedDate
        publishedDate = parser.parse(result['publishedDate'])
        if 'url' not in result:
            continue

        # append result
        results.append({'url': result['unescapedUrl'],
                        'title': result['titleNoFormatting'],
                        'publishedDate': publishedDate,
                        'content': result['content']})

    # return results
    return results

Thanks so much for your help

 

On April 29, 2016 at 12:35:00 AM, Adam Tauber (notifications@github.com) wrote:

try this:

search_url = base_url + '?action=search&{query}&search_more=feeds'

# do search-request

def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params

**Comment by fredhampton** [comment]
I m receiving this message in the log file 

File "/usr/local/searx/searx/engines/sparksnews.py", line 40, in request
    params['url'] = search_url.format(query=urlencode({'query': query}))
NameError: global name 'urlencode' is not defined


This is the content of sparksnews.py

from urllib import quote_plus
from json import loads
from lxml import html
from cgi import escape
from dateutil import parser


# engine dependent config
categories = ['news',]
paging = True

# search-url
base_url = 'http://sparks.leola.me/'
search_url = base_url + '?action=search&{query}&search_more=feeds'
                         

# specific xpath variables
results_xpath = '//article'
link_xpath = './/small[@class="time"]//a'
title_xpath = './/h2//a//text()'
content_xpath = './/p//text()'
pubdate_xpath = './/time'



# do search-request
def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params



# get response from search-request
def response(resp):
    results = []

    search_res = loads(resp.text)

    # return empty array if there are no results
    if not search_res.get('responseData', {}).get('results'):
        return []

    # parse results
    for result in search_res['responseData']['results']:
        # parse publishedDate
        publishedDate = parser.parse(result['publishedDate'])
        if 'url' not in result:
            continue

        # append result
        results.append({'url': result['unescapedUrl'],
                        'title': result['titleNoFormatting'],
                        'publishedDate': publishedDate,
                        'content': result['content']})

    # return results
    return results




Thanks so much for your help

**Comment by freedomtrain** [comment]
I m receiving this message in the log file 

File "/usr/local/searx/searx/engines/sparksnews.py", line 40, in request
    params['url'] = search_url.format(query=urlencode({'query': query}))
NameError: global name 'urlencode' is not defined

This is the content of sparksnews.py

from urllib import quote_plus
from json import loads
from lxml import html
from cgi import escape
from dateutil import parser

# engine dependent config

categories = ['news',]
paging = True

# search-url

base_url = 'http://sparks.leola.me/'
search_url = base_url + '?action=search&{query}&search_more=feeds'
                         

# specific xpath variables

results_xpath = '//article'
link_xpath = './/small[@class="time"]//a'
title_xpath = './/h2//a//text()'
content_xpath = './/p//text()'
pubdate_xpath = './/time'

# do search-request

def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params

# get response from search-request

def response(resp):
    results = []

    search_res = loads(resp.text)

    # return empty array if there are no results
    if not search_res.get('responseData', {}).get('results'):
        return []

    # parse results
    for result in search_res['responseData']['results']:
        # parse publishedDate
        publishedDate = parser.parse(result['publishedDate'])
        if 'url' not in result:
            continue

        # append result
        results.append({'url': result['unescapedUrl'],
                        'title': result['titleNoFormatting'],
                        'publishedDate': publishedDate,
                        'content': result['content']})

    # return results
    return results

Thanks so much for your help

 

On April 29, 2016 at 12:35:00 AM, Adam Tauber (notifications@github.com) wrote:

try this:

search_url = base_url + '?action=search&{query}&search_more=feeds'

# do search-request

def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params

**Comment by kvch** [comment]
You have to import urlencode in order to use it.

**Comment by freedomtrain** [comment]
I imported urlencode……I think its close to working…..
I received the following errors in the log 

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): sparks.leola.me
DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Clinton&search_more=feeds HTTP/1.1" 200 5724
ERROR:searx.search:engine crash: sparks news feeds

and..

 File "/usr/local/searx/searx/engines/sparksnews.py", line 50, in response
    search_res = loads(resp.text)

The sparksnews.py file contains

from urllib import quote_plus
from urllib import urlencode
from json import loads
from lxml import html
from cgi import escape
from dateutil import parser

# engine dependent config

categories = ['news',]
paging = True

# search-url

base_url = 'http://sparks.leola.me/'
search_url = base_url + '?action=search&{query}&search_more=feeds'
                         

# specific xpath variables

results_xpath = '//article'
link_xpath = './/small[@class="time"]//a'
title_xpath = './/h2//a//text()'
content_xpath = './/p//text()'
pubdate_xpath = './/time'

# do search-request

def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params

# get response from search-request

def response(resp):
    results = []

    search_res = loads(resp.text)

    # return empty array if there are no results
    if not search_res.get('responseData', {}).get('results'):
        return []

    # parse results
    for result in search_res['responseData']['results']:
        # parse publishedDate
        publishedDate = parser.parse(result['publishedDate'])
        if 'url' not in result:
            continue

        # append result
        results.append({'url': result['unescapedUrl'],
                        'title': result['titleNoFormatting'],
                        'publishedDate': publishedDate,
                        'content': result['content']})

    # return results
    return results

Thanks for your help !!!!

 

On May 2, 2016 at 9:46:52 AM, Noémi Ványi (notifications@github.com) wrote:

You have to import urlencode in order to use it.

**Comment by kvch** [comment]
Is it the whole stack trace?

**Comment by freedomtrain** [comment]
This is the stack trace

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): sparks.leola.me
DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Clinton&search_more=feeds HTTP/1.1" 200 5726
ERROR:searx.search:engine crash: sparks news feeds
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 40, in search_request_wrapper
    ret = fn(url, *_kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 82, in get
    return request('get', url, *_kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 75, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 582, in send
    r = dispatch_hook('response', hooks, r, *_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, *_kwargs)
  File "/usr/local/searx/searx/search.py", line 117, in process_callback
    search_results = callback(response)
  File "/usr/local/searx/searx/engines/sparksnews.py", line 50, in response
    search_res = loads(resp.text)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

 

On May 2, 2016 at 1:18:00 PM, Noémi Ványi (notifications@github.com) wrote:

Is it the whole stack trace?

**Comment by kvch** [comment]
What is the content of resp.text? Is it JSON? Is it HTML?

**Comment by freedomtrain** [comment]
HTML

 

On May 2, 2016 at 1:26:10 PM, Noémi Ványi (notifications@github.com) wrote:

What is the content of resp.text? Is it JSON? Is it HTML?

**Comment by kvch** [comment]
Then you should use `dom = html.fromstring(resp.text)`. The function `loads` is used in case of JSON response.

**Comment by freedomtrain** [comment]
I m using dom = html.fromstring(resp.text) …..It seems like there are results but they are not outputting to the page ?

The stack trace is 

INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: sparks.leola.me
DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Prince&search_more=feeds HTTP/1.1" 200 6148
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): sparks.leola.me
DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Prince&search_more=feeds HTTP/1.1" 200 6148
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: suggestqueries.google.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /complete/search?client=toolbar&q=P&hl=en HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: suggestqueries.google.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: sparks.leola.me
DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Prince&search_more=feeds HTTP/1.1" 200 6148
DEBUG:requests.packages.urllib3.connectionpool:"GET /complete/search?client=toolbar&q=Prince&hl=en HTTP/1.1" 200 None

———————————
the content of the engine is below 

from urllib import quote_plus
from urllib import urlencode
from json import loads
from lxml import html
from cgi import escape
from dateutil import parser

# engine dependent config

categories = ['news',]
paging = True

# search-url

base_url = 'http://sparks.leola.me/'
search_url = base_url + '?action=search&{query}&search_more=feeds'
                         

# specific xpath variables

results_xpath = '//article'
link_xpath = './/small[@class="time"]//a'
title_xpath = './/h2//a//text()'
content_xpath = './/p//text()'
pubdate_xpath = './/time'

# do search-request

def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params

# get response from search-request

def response(resp):
    results = []

    dom = html.fromstring(resp.text)

    # parse results
    for result in dom.xpath(results_xpath):
        link = result.xpath(link_xpath)[0]
        href = urljoin(url, link.attrib.get('href'))
        title = escape(extract_text(link))
        content = escape(extract_text(result.xpath(content_xpath)))

        # append result
        results.append({'url': href,
                        'title': title,
                        'content': content})

    # return results
    return results

 

On May 2, 2016 at 1:34:01 PM, Noémi Ványi (notifications@github.com) wrote:

Then you should use dom = html.fromstring(resp.text). The function loads is used in case of JSON response.

**Comment by freedomtrain** [comment]
I m using dom = html.fromstring(resp.text) …..It seems like there are results but they are not outputting to the page ?

The stack trace is 

INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: sparks.leola.me
DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Prince&search_more=feeds HTTP/1.1" 200 6148
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): sparks.leola.me
DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Prince&search_more=feeds HTTP/1.1" 200 6148
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: suggestqueries.google.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /complete/search?client=toolbar&q=P&hl=en HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: suggestqueries.google.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: sparks.leola.me
DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Prince&search_more=feeds HTTP/1.1" 200 6148
DEBUG:requests.packages.urllib3.connectionpool:"GET /complete/search?client=toolbar&q=Prince&hl=en HTTP/1.1" 200 None

———————————
the content of the engine is below 

from urllib import quote_plus
from urllib import urlencode
from json import loads
from lxml import html
from cgi import escape
from dateutil import parser

# engine dependent config

categories = ['news',]
paging = True

# search-url

base_url = 'http://sparks.leola.me/'
search_url = base_url + '?action=search&{query}&search_more=feeds'
                         

# specific xpath variables

results_xpath = '//article'
link_xpath = './/small[@class="time"]//a'
title_xpath = './/h2//a//text()'
content_xpath = './/p//text()'
pubdate_xpath = './/time'

# do search-request

def request(query, params):
    params['url'] = search_url.format(query=urlencode({'query': query}))
    return params

# get response from search-request

def response(resp):
    results = []

    dom = html.fromstring(resp.text)

    # parse results
    for result in dom.xpath(results_xpath):
        link = result.xpath(link_xpath)[0]
        href = urljoin(url, link.attrib.get('href'))
        title = escape(extract_text(link))
        content = escape(extract_text(result.xpath(content_xpath)))

        # append result
        results.append({'url': href,
                        'title': title,
                        'content': content})

    # return results
    return results

 

On May 2, 2016 at 1:34:01 PM, Noémi Ványi (notifications@github.com) wrote:

Then you should use dom = html.fromstring(resp.text). The function loads is used in case of JSON response.

**Comment by freedomtrain** [comment]
I m receiving results but they are not showing up in the search results 
Do I need to have any additional info for the engine in settings ?

DEBUG:requests.packages.urllib3.connectionpool:"GET /?action=search&query=Apple&search_more=feeds HTTP/1.1" 200 5509

**Comment by kvch** [comment]
Are you sure that your xpath is right?

**Comment by kvch** [comment]
I tested your XPATH expressions using Firebug. None of those worked. However, I have found a few examples which works for me. You could try these. :)

Title: `//h3[@class="title"]/a/text()`
URL: `//h3[@class="title"]/a/@href`
Pubdate: `//span[@class="feed_item_date"]/text()`
Content: `//div[@class="block_content"]/p`

**Comment by freedomtrain** [comment]
Thanks for your help !!!
This is what i have in settings file and it is not showing results on search page 

 - name : sparks social
    engine : xpath
    paging : True
    search_url : http://sparks.leola.me/?action=search&query={query}&search_more=all  
    results_xpath : //div[@class="description"] 
    url_xpath: .//h3[@class="title"]/a/@href    
    title_xpath: .//h3[@class="title"]/a/text()
    content_xpath: .//div[@class="block_content"]/p
    pubdate_xpath: .//span[@class="fu_date"]/text()
    categories : general
    shortcut : so
    disabled : False

Thanks !!!!

 

On May 8, 2016 at 1:22:29 PM, Noémi Ványi (notifications@github.com) wrote:

I tested your XPATH expressions using Firebug. None of those worked. However, I have found a few examples which works for me. You could try these. :)

Title: //h3[@class="title"]/a/text()
URL: //h3[@class="title"]/a/@href
Pubdate: //span[@class="feed_item_date"]/text()
Content: //div[@class="block_content"]/p

**Comment by asciimoo** [comment]
try with these xpaths:

```
  - name : sparks news feeds
    engine : xpath
    paging : True
    search_url : http://sparks.leola.me/?action=search&{query}&search_more=feeds
    results_xpath : //div[@class="feed_item_inner"]
    url_xpath : .//h3[@class="title"]//a/@href
    title_xpath : .//h3//a//text()
    content_xpath : .//p//text()
    categories : news
    shortcut : sn
```

it works for me

**Comment by freedomtrain** [comment]
Thanks !!!!
This works for the query = feeds 
I tried the paths with this query http://sparks.leola.me/?action=search&query={query}&search_more=all  
And it seems to not work

 

On May 11, 2016 at 1:51:53 PM, Adam Tauber (notifications@github.com) wrote:

try with these xpaths:

name : sparks news feeds engine : xpath paging : True search_url : http://sparks.leola.me/?action=search&{query}&search_more=feeds results_xpath : //div[@class="feed_item_inner"] url_xpath : .//h3[@class="title"]//a/@href title_xpath : .//h3//a//text() content_xpath : .//p//text() categories : news shortcut : sn
it works for me

**Comment by kvch** [comment]
If the param `search_more` is set to all, JS is utilized while retriveving results. In this case XPATH engine is not enough. An independent engine is needed to get the results. :)

**Comment by kvch** [comment]
Closing, as it is inactive. Feel free to reopen if needed.
