### ISSUE TITLE
Bug in show/hide map event listener on middle click

### ISSUE THREAD

**Issue by cookiengineer** [searx/searx#556]
Hey guys,

I noticed a very small bug in the results details view of map results.

I was looking at the templates and the static assets, and I only found [this event listener](https://github.com/asciimoo/searx/tree/master/searx/static/themes/oscar/js/searx_src/leaflet_map.js#L102) and I'm unsure if this exists for all templates. The default template seems to not have map functionality!?!?

I would love to fix this small bug myself with a pull request. It would be awesome if you guys could give me some hints :)

**Bug Description**

I created a [short video screencast](https://vid.me/ql5k) of the bug and uploaded it.

Video Interaction:
- 2 Middle clicks
- 2 Left clicks
- 2 Middle clicks
- 2 Left clicks

**What happens:**
- Middle click on show/hide map toggle link does not work properly.
- The show event listener switches to "hide" on middle click.
- The hide event listener does `not` switch back to `show` on middle click.

**What should happen:**
- Either have new window opened with detail view of map or ignore it completely.

**What I expected to happen:**
- Middle click opens a new window with the map link directly. So the href attribute of the link (or window.open() call afterwards) would lead to the details view.

**Comment by asciimoo** [comment]
Cannot reproduce with the latest chrom* or firefox browsers.
