### ISSUE TITLE
Limit Results by Time Range

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#557]
Feature request to limit results by time range, eg last 24 hours, last week, last month, last year.

**Comment by LuccoJ** [comment]
Seconded. At least some search engines being used as backends (e.g. Google) support this, so it should be possible to provide it to some extent at least.

**Comment by dalf** [comment]
+1

**Comment by ammarnajjar** [comment]
+1

**Comment by Yodan** [comment]
+1

**Comment by 1xPdd** [comment]
+1

Would also be cool if one could set date ranges, e.g., 1998-2000, rather than simply newness, e.g., 2015-present.

**Comment by asciimoo** [comment]
closing, see #634
