### ISSUE TITLE
SafeSearch Boxes Not Changeable

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#558]
The safesearch buttons under engines cannot be changed, a couple are on and most are off, but they cannot be ticked or unticked. Major problem

**Comment by dalf** [comment]
Actually this is only an information that's why the boxes are read only.
When the engine support safe search, the box is checked otherwise the box is left unchecked.

**Comment by ibrokemypie** [comment]
Perhaps making this clearer, at the very least making it "Supports SafeSearch" rather than simply Safesearch which is incredibly misleading and potentially frustrating for users, would be a good idea.
