### ISSUE TITLE
google images and bing images arent being searched.

### ISSUE THREAD

**Issue by nixoye** [searx/searx#563]
I've never changed any settings regarding them and the only settings I've ever changed is disabling Yahoo and Deviantart by default. Not sure how to go about checking what the issue is. They are both enabled by default and appear to be on in the preferences. Under avg time in the preferences they both list N/A.

**Comment by nixoye** [comment]
any idea what it is @asciimoo?

**Comment by asciimoo** [comment]
@NIXOYE is this happens on searx.me?
Try to reset your preferences.

**Comment by nixoye** [comment]
@asciimoo it was fixed after updating to 0.9 thanks a ton for the update!

on another note, how can i change the default search engines used for the music category or the videos category? I want to remove btdigg from being used in the videos and music section but not for files

**Comment by kvch** [comment]
Hey! You can remove btdigg from videos and music by blocking them on the preferences page and blocking them in their categories. Or if you are the admin of the instance and you want to change the global default value, you should simply add the line `catergories: files` to the config of btdigg.
