### ISSUE TITLE
Searx as a project of the Mozilla Science Global Sprint

### ISSUE THREAD

**Issue by jibe-b** [searx/searx#564]
On June 2-3, the Mozilla Science Lab organizes the "Global Sprint" which involves people from several cities around the globe as well as remote participants hacking several projects about Science, be they numerical tools, open educational resources, citizen science or open data analysis and visualization.

More info [here](https://mozillascience.org/global-sprint-2016)

A project around Searx could be proposed if some of you in the dev team like the project. The "Science" tab of Searx connects with the questions of Sciences. There could be improvements made around #557 as well as linguistic filtering of results (I will suggest it to the [SOHA project](https://www.facebook.com/groups/collectifsoha/) they deal with the question of access to science in the mother tongue, as a necessary step towards cognitive justice).

Having a project running during the Mozilla Science Lab Sprint requires to develop the project a bit more and have someone available during the two days in order to moderate and launch the dynamics.

Please tell me if you are interested in such a project taking Searx as object. I am greatly interested by your ideas!

cc @pietsch @asciimoo

**Comment by jibe-b** [comment]
Time goes by and this idea does not bring much attention, so let's say it's not for this time.

**Comment by GreenLunar** [comment]
I think that every chance for an activity with Mozilla is an opportunity, because of its poor state.

If Mozilla would attempt to force or foist on Searx a different agenda, just break up with it.

**Comment by jibe-b** [comment]
@GreenLunar, I have to admit I don't understand your message. I was thinking about the Science Sprint and the SOHA project mostly (and the use of Searx for Open Science).
