### ISSUE TITLE
Wish: API to programmatically query capabilities

### ISSUE THREAD

**Issue by LuccoJ** [searx/searx#566]
I have a practical need to be able to know beforehand from my program which engines and plugins a given Searx server supports and/or has enabled. Right now, the only way I know of that would allow me to do that would be to scrape the Preferences HTML. That is not ideal.

Searx would probably benefit from wider API in general, but this is probably the most immediately obvious missing thing to tackle after having an interface to obtain search results themselves (which we have).

My use case, in case this is of interest, involves having multiple Searx servers at my disposal (most of the publicly available ones), and being able to choose the ideal one not just randomly but according to what it offers. This general problem may be related to things proposed in other issues, involving the ability to use Searx itself as an engine, and automatically picking a Searx server.

**Comment by LuccoJ** [comment]
Bear with me and even though this is done and closed, consider adding to this interface a field to tell me what the shortcut for each engine is, not just its name. I need this to programmatically find a Searx instance that can/will provide a specific engine when a user asks for it using a !shortcut.

**Comment by asciimoo** [comment]
@LuccoJ added: fbbb307
