### ISSUE TITLE
Plugin Management

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#569]
searx needs some kind of uniform plugin system in which installation and removal of plugins is simple and easy for instances without having to pull from old forks that havent been updated for ages and hacking them into something that works. A plugin directory with downloadable plugin zips that should be entirely self contained and install into a plugins folder, removal being simply removing the directory. 

additionally, a documented plugin api should be made to make development of a wider range of plugins possible and more accessible.

i see plugins as being instance specific, with the owner deciding what to and what not to include, while the general preferences should be the generic things in every instance.

**Comment by kvch** [comment]
IMHO plugin management the way you describe is unnecessary for searx. I don't think that 5 plugins require such a complex management. I would say that this feature request right now is irrelevant. However, it can be revisited if and when searx has 20-30 plugins.

ATM creating and adding new plugins to the existing plugin "store" is easy and does not require black magic. But creating a documentation page for describing plugin creation might be a good idea. (But I am not sure if it is necessary based on the simplicity of creations of plugins.)

**Comment by kvch** [comment]
Invalid and abandoned.
