### ISSUE TITLE
Chameleon Theme Broken

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#570]
on the chameleon theme you cannot save any settings, which means the only way to change to another is to delete the cookie.

[edit] chameleon not pixart

**Comment by Cqoicebordel** [comment]
Works for me in searx.me, in Chromium, Opera 12 and Firefox.

**Comment by kvch** [comment]
Works for me, too. Which instance is the problematic one? Which version does it run on? Could you provide further information on how to reproduce the bug?

**Comment by ibrokemypie** [comment]
sorry, made a mistake, the problematic theme is actually chameleon. had problems with both firefox and safari so far

**Comment by kvch** [comment]
How and where have you found chameleon theme?

This theme is my work, but it is not finished yet. It is in my fork of searx. I haven't created a PR so it is not released. I don't understand why you opened an issue here, when the theme resides at my repo.

**Comment by ibrokemypie** [comment]
@kvch sorry, forgot that I pulled it into mine, sorry for the inconvenience

**Comment by kvch** [comment]
No problem. Then this issue can be closed because it is invalid.
