### ISSUE TITLE
Category Order

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#573]
What determines the category order? Is there a way to change it? Any setting in the settings.yml?

**Comment by dalf** [comment]
Categories are sorted by alphabetic order except for the general which is the first one.
This order can't be modified.
See : https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L268

Related to https://github.com/asciimoo/searx/issues/258
It should be configured by settings.yml IHMO.

**Comment by ibrokemypie** [comment]
> On 7 Jun 2016, at 7:52 PM, Alexandre Flament notifications@github.com wrote:
> 
> Categories are sorted by alphabetic order except for the general which is the first one.
> This order can't be modified.
> See : https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L268 https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L268
> Related to #258 https://github.com/asciimoo/searx/issues/258
> It should be configured by settings.yml IHMO.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub https://github.com/asciimoo/searx/issues/573#issuecomment-224233338, or mute the thread https://github.com/notifications/unsubscribe/AHdxhqWIF2tTYahXQWIJ9WqTvt-5uop6ks5qJT9YgaJpZM4IpOJb.

i agree, settings.yml OR by users for their own settings.
