### ISSUE TITLE
RuntimeError: working outside of application context

### ISSUE THREAD

**Issue by gregoirefavre** [searx/searx#574]
Hello,

I used to use a perfectly usable sear-git under my archilinux but for some times I got :

`python2.7 /usr/lib/python2.7/site-packages/searx/webapp.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/searx/webapp.py", line 66, in <module>
    from searx.plugins import plugins
  File "/usr/lib/python2.7/site-packages/searx/plugins/__init__.py", line 22, in <module>
    from searx.plugins import (https_rewrite,
  File "/usr/lib/python2.7/site-packages/searx/plugins/https_rewrite.py", line 29, in <module>
    description = gettext('Rewrite HTTP links to HTTPS if possible')
  File "/usr/lib/python2.7/site-packages/flask_babel/__init__.py", line 538, in gettext
    t = get_translations()
  File "/usr/lib/python2.7/site-packages/flask_babel/__init__.py", line 215, in get_translations
    babel = current_app.extensions['babel']
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/python2.7/site-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/lib/python2.7/site-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context`

I have tried [https://asciimoo.github.io/searx/dev/install/installation.html] which gave me the same issue...

Any idea on how I could fix it ?

Thank you very much !

**Comment by ibrokemypie** [comment]
have you run ./manage.sh update_packages and ./manage.sh update_dev_packages from the searx root?

**Comment by gregoirefavre** [comment]
No, I didn't do the dev's one which I just tried :
`Collecting robotframework-selenium2library==1.7.4 (from -r /usr/local/searx/requirements-dev.txt (line 6))
  Downloading robotframework-selenium2library-1.7.4.tar.gz (234kB)
    100% |████████████████████████████████| 235kB 5.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-afyawjqt/robotframework-selenium2library/setup.py", line 7, in <module>
        from ez_setup import use_setuptools
      File "/tmp/pip-build-afyawjqt/robotframework-selenium2library/src/ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-afyawjqt/robotframework-selenium2library/
`
Thank for your answer. The problem now might (?) comes from python being python3 on my system and searx needs python2 ?

**Comment by ibrokemypie** [comment]
Yes that would be it, searx will not run on python3, i suggest completely remvoing everything python related from your system then running pacman -S python2 python2-pip python2-openssl python2-setuptools and then running the update scripts again. you may need to ln -s /usr/bin/python2 /usr/bin/python

**Comment by gregoirefavre** [comment]
That's not so easy as lots of other packages requires python2 or python3.
Thanks for your help.

**Comment by ibrokemypie** [comment]
> On 30 May 2016, at 6:52 PM, gregoirefavre notifications@github.com wrote:
> 
> That's not so easy as lots of other packages requires python2 or python3.
> Thanks for your help.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub https://github.com/asciimoo/searx/issues/574#issuecomment-222445165, or mute the thread https://github.com/notifications/unsubscribe/AHdxhtfuoAGPURXJd408lEVriZNgNwfAks5qGqVYgaJpZM4IpSo2.

Other packages? If you are running searx on a platform that is currently running other things that are preventing you of meeting searx’s requirements then the problem is not with searx.

**Comment by gregoirefavre** [comment]
I learn quiete a few thanks to searx (and answers here) : it know works tremendously, all I needed was to install python2-virtualenv as my virtualenv was with python3 !!!

Thank you very much !!!
