### ISSUE TITLE
Geektimes and Gigablast engines stopped working

### ISSUE THREAD

**Issue by MarcAbonce** [searx/searx#575]
It's probably just some xpath changes, but I'm not really sure.

**Comment by ibrokemypie** [comment]
`May 31 04:33:29 searxpi python[1918]:     search_results = engine.response(response)
May 31 04:33:29 searxpi python[1918]:   File "/root/searx/searx/engines/gigablast.py", line 77, in response
May 31 04:33:29 searxpi python[1918]:     response_json = loads(resp.text)
May 31 04:33:29 searxpi python[1918]:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
May 31 04:33:29 searxpi python[1918]:     return _default_decoder.decode(s)
May 31 04:33:29 searxpi python[1918]:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
May 31 04:33:29 searxpi python[1918]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
May 31 04:33:29 searxpi python[1918]:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
May 31 04:33:29 searxpi python[1918]:     raise ValueError("No JSON object could be decoded")
May 31 04:33:29 searxpi python[1918]: ValueError: No JSON object could be decoded`

+1
