### ISSUE TITLE
GoogleScraper

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#577]
[GoogleScraper](https://github.com/l2inc/GoogleScraper)

An adaptation could be implemented into searx so as to fix #576 #520 #561 by distributing searches over a list of instance defined proxies, while also potentially improving privacy even further.

**Comment by dalf** [comment]
It's require Python 3 and Chrome Browser !
For Python 3, searx will most probably need to switch to this version one day or another, but Chrome is another beast.

From the documentation :

> I am pretty sure that it must be possible to handle 20 such browser sessions in a parallel way without stressing resources too much.  

It will require far memory and CPU ressource than the current implementation, and at the same time :

> Alone the dynamic nature of Javascript makes it impossible to scrape undetected.

But for sure it will solve the issues you have referenced in many more cases than the current implementation.

About proxies, this bring this idea for searx : to be able to use different proxies as it is possible to use different IPs.

The documentation / code about [google dorks](http://www.webvivant.com/google-hacking.html) is interesting. [This file](https://github.com/l2inc/GoogleScraper/blob/master/GoogleScraper/search_engine_parameters.py) too.

The requests are prepared here : 
https://github.com/l2inc/GoogleScraper/blob/master/GoogleScraper/http_mode.py
and
https://github.com/l2inc/GoogleScraper/blob/master/GoogleScraper/selenium_mode.py

The response are parsed here : 
https://github.com/l2inc/GoogleScraper/blob/master/GoogleScraper/parsing.py
