### ISSUE TITLE
Block/Allow buttons make no sense

### ISSUE THREAD

**Issue by jmaris** [searx/searx#579]
Hey !

First of all I'd like to say that I totally love searX, We're running it on our server and it's my everyday searchengine, but there is this  _one little thing_ that has been getting to me recently : The buttons to toggle Engines are really badly designed.

These are the reasons I think it needs to change : 
- Generally speaking, tables should contain Data
- The current setup does not show the _Current state_ of the engine, but rather shows the state it will be when the button is clicked.
- This can confuse users

My Answer to this would be to change the text on the buttons to "On" and "Off",  So that it displays "On" when the engine is enabled and "Off" when it's disabled. In my opinion this will be considerably clearer for the user.

What do you guys think ?

**Comment by kvch** [comment]
Possible duplicate of #284, so I think it can be closed. What do you think?

**Comment by jmaris** [comment]
Can be closed, sorry , I saw that thread but i didn't read down
