### ISSUE TITLE
extending search algorithm

### ISSUE THREAD

**Issue by freedomtrain** [searx/searx#583]
I m interested in understanding how we could go about to adding/extending/changing the algorithm in searx that weighs the search results.
Is there documentation for this ?

Thanks !!!

**Comment by dalf** [comment]
The results are merged using this implementation : 
https://github.com/asciimoo/searx/blob/master/searx/results.py#L145 

Then the results are scored using this implementation : 
https://github.com/asciimoo/searx/blob/master/searx/results.py#L196

I don't think there is documentation for now.

**Comment by asciimoo** [comment]
@fredhampton engines have weight `1.0` by default which affects result scoring. You can change it in settings.yml if you add `weight: n` to an engine.
Currency convert engine is a good example which has custom weight.

**Comment by freedomtrain** [comment]
Thanks !!!

 

On June 10, 2016 at 2:30:03 AM, Adam Tauber (notifications@github.com) wrote:

@fredhampton engines have weight 1.0 by default which affects result scoring. You can change it in settings.yml if you add weight: n to an engine.
Currency convert engine is a good example which has custom weight.

**Comment by freedomtrain** [comment]
Thanks !!!

 

On June 9, 2016 at 8:26:02 PM, Alexandre Flament (notifications@github.com) wrote:

The results are merged using this implementation :
https://github.com/asciimoo/searx/blob/master/searx/results.py#L145

Then the results are scored using this implementation :
https://github.com/asciimoo/searx/blob/master/searx/results.py#L196

I don't think there is documentation for now.

**Comment by kvch** [comment]
Closing, as the question is answered. Feel free to reopen if needed.
