### ISSUE TITLE
Search Language without cookies

### ISSUE THREAD

**Issue by errxr** [searx/searx#587]
Hi,
Can we have the content for the language/or country selected in our browsers? On firefox, I don't have history enabled so that when I search "football" in the news section, I don't get Euro2016's soccer news but american news... Also, on the french instance " https://trouvons.org/ ", it's only in english that so if I type "Apple" I only get the english wiki page.

Thanks for your solicitude

<img width="1280" alt="sans titre" src="https://cloud.githubusercontent.com/assets/19875803/16362917/75b028ca-3bc3-11e6-8462-999da3023960.png">

**Comment by return42** [comment]
already Implemented
