### ISSUE TITLE
Infobox : duplicate links to wikipedia pages when search language is not English and using ddd engine

### ISSUE THREAD

**Issue by dalf** [searx/searx#593]
Example (setting the search language to FR_fr) : 
https://searx.me/?q=!ddd%20!wd%20linux&categories=none

The problem is the ddd engine which publish an URL with a http link to Wikipedia (not https).

I think the URL should be normalized here : 
https://github.com/asciimoo/searx/blob/master/searx/engines/duckduckgo_definitions.py#L97

**Comment by asciimoo** [comment]
Result merger partially handles it: https://github.com/asciimoo/searx/blob/master/searx/results.py#L186

**Comment by dalf** [comment]
But, here, the URLs are not merged using this code : there are inside one infobox.

**Comment by asciimoo** [comment]
ah yes, sry
Then maybe infobox merge function could handle these deduplications.

**Comment by asciimoo** [comment]
seems solved - thanks to @a01200356
