### ISSUE TITLE
Mobile menu needs adjustment

### ISSUE THREAD

**Issue by johnjago** [searx/searx#596]
The mobile menu that appears when the viewport is small enough does not work quite right.

In this view, the menu seems too close to the bottom. I am not sure if that was intentional.

![menu1](https://cloud.githubusercontent.com/assets/19847480/16423704/b9299a72-3d22-11e6-8108-cd572dfa1512.PNG)

When I remove the `margin-top: 8px;` it looks a little better.

![menu2](https://cloud.githubusercontent.com/assets/19847480/16423703/b9258f22-3d22-11e6-8057-ad540f947264.PNG)

Finally, this is the real issue:

![menu3](https://cloud.githubusercontent.com/assets/19847480/16423705/b936594c-3d22-11e6-9f4a-bc4e5364af39.PNG)

**Comment by asciimoo** [comment]
thanks the detailed report
