### ISSUE TITLE
Firefox search bar: query is lost on searx.me

### ISSUE THREAD

**Issue by jibe-b** [searx/searx#599]
Since new theme appeared (correlation, not causation, indeed! ;) ),
searching in the Firefox adress bar only opens searx.me
and the text of the query is lost (neither executed nor available in the search form).

Illustration:
- open Firefox
- enable searx.me as default search engine in search bar
- type "searx" in search bar

-> result: searx.me loads, empty form.

**Comment by asciimoo** [comment]
@jibe-b searx.me does not support `http://` anymore, only `https://`. Delete it from your search engines and add `https://searx.me/` and it will work.

**Comment by kvch** [comment]
Closing, as it is inactive.

**Comment by Pofilo** [comment]
If this happens on your own instance of searx, you need to change the parameter `base_url ` in the file `searx/settings.yml` (specifying that you use `HTTPS`).
