### ISSUE TITLE
Does the searx project focuses only on privacy?

### ISSUE THREAD

**Issue by jan-kleks** [searx/searx#602]
Or maybe you want to create better searching (metasearching?) experience overall by adding some unique features? If it is so, you might want to state this clearly in the searx's description.

**Comment by kvch** [comment]
No, the other main focus is hackability, just like stated in the description and also in the [How to contribute](https://asciimoo.github.io/searx/dev/contribution_guide.html#prime-directives-privacy-hackability) page of the docs.

**Comment by Erfahrungen** [comment]
> by adding some unique features

What do you have in mind?

**Comment by jan-kleks** [comment]
@Erfahrungen I mean stuff like this:

[Use adblocking list to limit search results to adfree websites #568 ](https://github.com/asciimoo/searx/issues/568)

[direct torrent download via webtorrent #123](https://github.com/asciimoo/searx/issues/123)

[ [plugin] download video #537](https://github.com/asciimoo/searx/issues/537) 

Something that would make searx stand out from the crowd.

**Comment by kvch** [comment]
@jan-kleks I would not say that these features would make searx outstanding. But I agree on that these requests are good and could be valuable features. :)

AFAIK #537 is in progress. Unfortunately, after the first review phase with @asciimoo the author of the PR has disappeared. :( I am not sure about the other two, but it would be nice to have those features, too.

**Comment by unixfox** [comment]
The main focus for this project is explained on the home page of the wiki: https://searx.github.io/searx/
