### ISSUE TITLE
Twitter: make links clickable

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#605]
quant_social links are clickable, twitter links not.

try

!tw android
!qws_social android

and look at links in the texts. Links in twitter entrys should be clickable too. Combined Twitter/Quant entries have clickable links.

**Comment by cy8aer** [comment]
Some further enhancement: why not make @ and # clickable too (to search in twitter)

**Comment by unixfox** [comment]
Qwant social is broken and twitter engine got removed.
