### ISSUE TITLE
searx.me as an interface (central hub) for other instances

### ISSUE THREAD

**Issue by jan-kleks** [searx/searx#622]
Would it be possible to use searx.me as a kind of a central hub for other instances?  To ensure their quality, to share traffic equally between instances, to make the service more reliable, etc. It's a bit like with Tor, there are various nodes, but we use one client.

Of course, if someone would really like to create a completely separate searx instance, it should be still allowed. However, I think decentralization needs some organization, otherwise it can prove confusing (large number of strangely named instances) to the end-user.

**Comment by kvch** [comment]
Just to clear things up, is your problem is that a few search engines (Google, DDG) block your IP and does not return any results?

If so, I don't think that making searx.me the central instance for others is the way. I don't like the idea of centralizing searches. If searx.me would be the central instance it would run out of IPs after a while, and would not be able to serve requests just like other instances. So it is not a real solution for the problem.
Another type of search could be implemented where the request of the user would go through more instances without centralization, but still I don't think that is the way either.

**Comment by virtadpt** [comment]
It could be done by setting up a round-robin DNS entry for searx.me (one A record, multiple IP addresses) with a relatively short lifetime (five minutes).  The problems would then be the browser noticing that every instance had a different SSL certificate (or none at all) (which is a serious problem with the SKS keyserver network's HTTPS interface...), not knowing which of the instances were configured for privacy (i.e., reconfigured logging), keeping them all on the same version of searx...

The organizational overhead would be pretty serious, but it's not an insurmountable problem, either.

**Comment by jan-kleks** [comment]
@kvch 

> Just to clear things up, is your problem is that a few search engines (Google, DDG) block your IP and does not return any results?

Nope, I have not experienced this issue, but I know it exists.

> If so, I don't think that making searx.me the central instance for others is the way. [...]
> 
> Another type of search could be implemented where the request of the user would go through more instances without centralization, but still I don't think that is the way either.

I don't want searx.me to act as the central instance, but as the central interface for other instances. Maybe the example with Tor nodes wasn't the best... I would like this central interface to automatically (but it also should be made configurable) switch instances under-the-hood. The switching could be based on time (e.g. once an hour), location (an instance closer to the user), amount of traffic (to avoid situations like the one with missing results, described by you), etc. I don't think it is necessary for the search to go through multiple instances at once either. As you can see, the system described here is still decentralized, but only the interface is central. And the user don't have to go through long lists of instances. Anyway, don't most people use searx.me as their main instance already?   

Maybe an alternative would be to teach instances to talk to each other, so that any searx instance would be able to do this instance switching, and to share traffic. Hmm...

**Comment by asciimoo** [comment]
duplication of #39
