### ISSUE TITLE
[UI] Improve Block/Allow box

### ISSUE THREAD

**Issue by ghost** [searx/searx#625]
https://searx.me/preferences

When I see red "Allow" button, I think it is:
- currently "blocked", click to "allow" it
- currently "allowed", click to "block"

It is not clear.

[(O)**] something
[**(O)] something

how about changing them to iPhone style button, so the user can understand better.

**Comment by MarcAbonce** [comment]
#284 This has been an issue for almost a year now. :P
I think it's as simple as changing the text to On/Off (as proposed in this duplicate: #579).

**Comment by ibrokemypie** [comment]
whats the chance of this actually happening?

**Comment by kvch** [comment]
Closing, see #654
