### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by jleclanche** [searx/searx#63]
Python 3 does not appear to be supported and I can't find any info concerning this. Is this on the roadmap?

**Comment by asciimoo** [comment]
@jleclanche  Gevent has been purged from searx, so there is no py3 blocking dependency - only searx

**Comment by stef** [comment]
@jleclanche what benefit comes from porting to a new language?

**Comment by jleclanche** [comment]
@stef huh?

**Comment by stef** [comment]
python3 is a new language, in comparison to py2. and if you port to a new language, then there should be some reason for that. i mean, why not then do it properly and go for erlang instead?
but as far as i know, there's no plan to port to new languages.

**Comment by jleclanche** [comment]
@stef Ive ported hundreds of apps to Python 3, please don't spread random FUD. 2to3 does 90% of the work and it's very easy to be compatible with both 2 and 3.

**Comment by stef** [comment]
excellent, but in this regard you can consider that py2 and py3 are different languages, and porting searx i think brings absolutely no benefit for the users. if searx would at least be a lib^Wmodule then maybe it'd make sense to provide it to other users. sorry if my consideration of this issue was incomprehensible to you. it was definitely not meant as fud. and if searx would be ported to another language, i think it'd make much more sense to chose erlang, as it provides much better support for all this network shoveling stuff, and being transient.

**Comment by Cqoicebordel** [comment]
py2 and py3 aren't different languages. As such, it isn't porting to go from py2 to py2+py3, it's only evolving toward the future.  
It's like compiling a C program with a C++ compiler : it works almost out of the box, and allow greater possibilities for the future.

So the benefits aren't for the users, but for the developers.  
There are also benefits to the admins that can deploy searx without installing another environnement for another version of python than they used to.

So it's win win win.

As for erlang, as it's not a port, there is no point of it here.

**Comment by stef** [comment]
so the developer benefit by having to support 2 languages now?
what other benefits?

**Comment by Cqoicebordel** [comment]
NO ! It's the same language !

**Comment by jleclanche** [comment]
@stef Python 3 is not a different language, and if you really believe that, I suggest you port this just so you understand how easy it is for your own benefit.

**Comment by stef** [comment]
if it's not a different language, why do you need porting, and this issue about it?

**Comment by stef** [comment]
but, i think the main question is still, what's the benefit, if it is a different or the same language is irrelevant. what is, how much effort is this now, how much effort is this later, and what is the benefit of spending all this effort?

**Comment by Cqoicebordel** [comment]
Because there are some cleanup tasks to do, and imports to organize.

The effort now is like solving a bug, so a bit. Effort in the future, nil. Benefits : I have already listed a few above.

**Comment by stef** [comment]
i guess we only disagree about epsilon, where epsilon is the distance between two languages, anything closer is "the same", anything beyond epsilon is a "different language". in this context, i hope you can see, that not everyone has the same epsilon threshold, and thus whether two things are different or the same lie in the discretion of the observer.

so searx has been initially written in py2, i'd say a prudent choice, someone else might have made a different one. but searx is py2, so what would be the reaction if someone came, with even more radical epsilon thresholds, say, equating every script language as "the same", i'm sure we both have met this kind of person ;) if we'd be polite, i guess i'd ask, what would be the benefits of that, and what the cost. so i see the argument, that porting can be done 90% automatically, having seen asciimoo dig deeply into much of the code, i'm not sure if this is a bit optimistic. but let's say, it's done. what then? can someone come and commit py2 code, and be happy it'll work with py3? or vice versa? how much effort is it to support both? or does this porting mean in the end, that it's basically py3, but it might run also on py2? as for the benefits, compiling c with a c++ compiler is no fun, if it's a serious project, as is various compilers and interpreters. having to support suddenly py3 additionally brings no benefit but more work for the developer. and i'm not sure that our developer resources are so plentiful as to spend all this for 1 or 2 admins, who for some weird reason have no py2. in total this does not sound like a beneficial issue, irrespective of where our epsilon thresholds are.

**Comment by Cqoicebordel** [comment]
If the code stay the same, there are no epsilon, like in this case. Whatever the words you use, IT IS THE SAME LANGUAGE !

I already did the conversion to py3 of searx. So I know the change is minimal.  
I also already responded to all of your questions above, but I will again as you don't seem to read my answers.

> Can someone commit py2 code, and be happy it'll work with py3 ?

It's the SAME CODE ! So yes. The only thing that change is the name of the import.

> or vice versa?

Obviously, yes.

> how much effort is it to support both?

None

> or does this porting mean in the end, that it's basically py3, but it might run also on py2?

Yes, but it's not "might", it's "will".

> having to support suddenly py3 additionally brings no benefit but more work for the developer.

No, it's the SAME LANGUAGE, and so, the same work. The only differences, is that now, the py3 lib are at hands reach.  
Also "no benefit" ?! Please read again, and again, and again, what I posted above. And once more.

> i'm not sure that our developer resources are so plentiful as to spend all this for 1 or 2 admins, who for some weird reason have no py2

Sure, and we shouldn't use IPV6 for the three of four sites that use it...  
Py3 is the future. Py2 is dead and will disappear sooner or later. We **_have**_ to move to Py3.  
Unless you want the project to be dead when py2 will be ?

**Comment by jleclanche** [comment]
I'm unsubscribing from this issue. If @stef is the sort of mindset people have to deal with in this project, I want nothing to do with it.

**Comment by stef** [comment]
ok so you say the change is minimal. but you fail to show any benefit either. so why do this? i think besides epsilon we also disagree on the vision of our future, not very uncommon i say. ;) and if py2 really dies, i guess erlang is still a more prudent choice for this kind of transient network proxying stuff. but let's focus on the benefits.

**Comment by Cqoicebordel** [comment]
Please don't. He is only one guy that is trolling. And he doesn't matter. I only like to show people they are wrong ;)

I rather like you to stay, for tomorrow, when he will be gone :)

**Comment by Cqoicebordel** [comment]
Benefits : Future proof, py3 libs. As stated again and again above.

**Comment by stef** [comment]
thanks for making that so clear. and sorry for the guy if my questions were inconvenient for him.

**Comment by ibrokemypie** [comment]
Has any work been done on this? Another benefit would be easier installation on distros that have replaced the default python install from their package manager with 3

**Comment by josch** [comment]
Hi, I'm interested in packaging searx for Debian but as Debian is trying to get rid of Python2 ([it will not be maintained past 2020](https://www.python.org/dev/peps/pep-0373/) and is [already on the way out of the standard installation](https://lists.debian.org/385f53ae-0ef0-382e-61e0-f4d5307a490e@debian.org)) I would not like to add yet another package which is python2-only.

@Cqoicebordel you say you already did the conversion to py3. Is your patch public somewhere?

**Comment by asciimoo** [comment]
@josch great! There is a py3 branch where the search functionality works, but there can be bugs in other parts of the code.
The robot testing is completely missing, since it is a py2 only dependency.

**Comment by josch** [comment]
Excellent! The py3 branch works great. Thank you!

Isn't this a py3 fork of the robot framework (which also happens to be compatible with python 2.7): https://pypi.python.org/pypi/robotframework-python3

**Comment by asciimoo** [comment]
@josch onice!
I haven't found this - looks super promising. I'll rebase the py3 branch to the top of the current master (there were bigger changes in the code since the last update of py3 branch) and experiment with this lib. Thanks!

**Comment by dalf** [comment]
done. see https://asciimoo.github.io/searx/blog/python3.html
