### ISSUE TITLE
Scholar: Google sees automated query

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#631]
The following respond comes from scholar:

> Google  Sorry...
> 
> We're sorry...
> 
> ... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
> 
> See Google Help for more information.
> 
> Google Home

and: in settings.yml the url ends with an ' which must be deleted!

**Comment by kvch** [comment]
On searx.me it works.

**Comment by cy8aer** [comment]
hm, it did not work with searx so I tried the url via curl. It works on my lap, but not on the server. They seem to kick out my IP. When opening the site with a browser they do not show me a "I am a human" captcha. Boom

**Comment by ghost** [comment]
@cy8aer your global IP is banned by google, then. Scroogle. > https://github.com/disconnectme/search/issues/53
