### ISSUE TITLE
How SERAX protect itself from Google?

### ISSUE THREAD

**Issue by ghost** [searx/searx#632]
https://github.com/disconnectme/search/issues/53

@Disconnectme said they're working on a so-called "solution", but they didn't fix their search
webpage, https://search.disconnect.me/ yet.
I wonder _how_ searx protect itself from Google. Are you using proxy to connect to Google? Or have
some kind of agreement with Google?

**Comment by ghost** [comment]
(if any of you have Twitter, please tweet this URL to https://twitter.com/disconnectme to caught their attention, ty)

**Comment by ibrokemypie** [comment]
Searx is hosted by users on their own servers. Searx is not protected at all, just some instances have not been blocked yet. I host my own and every few days google comes back online before blocking me again.

**Comment by Pulsera** [comment]
Sorry to be late to the conversation.

But how about when I go to searx.me I'm connecting to a random user? or its hosted by the creater for searx

**Comment by ibrokemypie** [comment]
searx.me is one instance run by one person as searx.space is run by me,  they aren't connected or shared at all

**Comment by kvch** [comment]
Closing, as the question is answered and the user who opened is has diappeared. Feel free to reopen if needed.
