### ISSUE TITLE
TypeError: 'map' object is not subscriptable

### ISSUE THREAD

**Issue by songproducer** [searx/searx#635]
Trying to get working in Python 3.5 . I'm confused by this code in search.py.

I made some changes suggested by 2to3.

What does pd and categ mean?

```
# set categories/engines
            load_default_categories = True
            for pd_name, pd in list(self.request_data.items()):
                if pd_name == 'categories':
                    self.categories.extend(categ for categ in map(str.strip, pd.split(',')) if categ in categories)
                elif pd_name == 'engines':
                    pd_engines = [{'category': engines[engine].categories[0],
                                   'name': engine}
                                  for engine in map(str.strip, pd.split(',')) if engine in engines]
                    if pd_engines:
                        self.engines.extend(pd_engines)
                        load_default_categories = False
                elif pd_name.startswith('category_'):
                    category = pd_name[9:]

```

> ERROR:**main**:Exception on / [POST]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
>     raise value
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "searx/webapp.py", line 385, in index
>     search.search(request)
>   File "/usr/local/lib/python3.5/site-packages/searx-0.9.0-py3.5.egg/searx/search.py", line 299, in search
>     engine.request(self.query.encode('utf-8'), request_params)
>   File "/usr/local/lib/python3.5/site-packages/searx-0.9.0-py3.5.egg/searx/engines/qwant.py", line 35, in request
>     if categories[0] and categories[0] in category_to_keyword:
> TypeError: 'map' object is not subscriptable

**Comment by kvch** [comment]
I think `pd` means payload data and `pd_name` payload data name. So basically the code snippet you pasted here sets the categories and the engines based on the data in the request.

**Comment by dalf** [comment]
done. See https://asciimoo.github.io/searx/blog/python3.html
