### ISSUE TITLE
with KAT being targeted, could we get digbt search working as a backup?

### ISSUE THREAD

**Issue by nixoye** [searx/searx#638]
I predict this wont be the last we here about torrent sites being targeted and after KAT domain seizure i believe the mirrors might get targeted as well. could searx get http://www.digbt.org/ as a backup since btdigg is also down

**Comment by ibrokemypie** [comment]
how about bitcq?

**Comment by nixoye** [comment]
@PwnArt1st ive never used it but it also looks nice.

**Comment by ibrokemypie** [comment]
it is very nice to use,  fast,  extensive and includes inline magnet and torrent links,  however the uptime in the past has been a bit iffy

**Comment by ibrokemypie** [comment]
torrentz.eu has also gone down it seems, "Torrentz will always love you. Farewell."
