### ISSUE TITLE
[Oscar theme] change MapQuest to OSM ? 

### ISSUE THREAD

**Issue by dalf** [searx/searx#640]
MapQuest is no more free : http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/ and https://developer.mapquest.com/plans

Should the choice be removed ?

https://github.com/asciimoo/searx/blob/master/searx/static/themes/oscar/js/searx_src/leaflet_map.js#L152

**Comment by pointhi** [comment]
Yep, it doesn't make sense to show broken tiles.
