### ISSUE TITLE
What do you think if searx supported by Tor?

### ISSUE THREAD

**Issue by ghost** [searx/searx#642]
https://trac.torproject.org/projects/tor/ticket/19747

**Comment by dalf** [comment]
What do you mean to support TOR ?
Searx is a proxy between your computer and different search engines.
- TOR can be used from Searx to the search engines (actually not possible now, but the implementation is possible, see https://github.com/asciimoo/searx/issues/519 )
- TOR can be used from your computer to the searx instance (hidden service / .onion). In this case have a look to https://github.com/asciimoo/searx/wiki/Searx-instances . For example you can access searx.me using this link http://ulrn6sryqaifefld.onion/

**Comment by ghost** [comment]
Seems this is off-topic, sorry XD
