### ISSUE TITLE
Text Wrap Theme Issue on Mobile

### ISSUE THREAD

**Issue by ibrokemypie** [searx/searx#652]
Issue on Oscar-Logicodev theme (not sure about others)  with text not being consistently wrapped and sometimes extending out to the side,  adding a horizontal scroll.

**Comment by ibrokemypie** [comment]
![ ](http://picpaste.com/pics/Screenshot_20160801-155725.1470651783.png)

**Comment by asciimoo** [comment]
@ibrokemypie could you send a screenshot or example query where the problem occurs?

**Comment by dalf** [comment]
https://searx.me/?q=Go+vs+python&category_general=on&time_range=

The layout has an problem with this link :
https://www.reddit.com/r/golang/comments/2aup1g/why_are_people_ditching_python_for_go/

The pretty url isn't cut.

**Comment by asciimoo** [comment]
@dalf thanks!
