### ISSUE TITLE
Another search engine: deusu.de

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#665]
http://deusu.de. Seems to have opensearch support.

**Comment by cy8aer** [comment]
Pull request is running... https://github.com/asciimoo/searx/pull/666 but this is simly xpath...

**Comment by ghost** [comment]
I'm the person running DeuSu. There is a free API in testing now. Will probably be ready for production use this month.

There is also https://deusu.org which has slightly different ranking. deusu.de ranks for a German speaking audience while deusu.org ranks for English speaking audience. There will be APIs for both.

**Comment by cy8aer** [comment]
API exists: https://deusu.org/api/api_v1.html

**Comment by maximilianpreisinger** [comment]
It seems to me, that this search engine doesn't exist any more.

**Comment by rachmadaniHaryono** [comment]
i checked both website

deusu.de just show `deusu.de`

i got `NET::ERR_CERT_COMMON_NAME_INVALID` on deusu.org

**Comment by maximilianpreisinger** [comment]
@rachmadaniHaryono I accepted the certificate, there is only a link to a webmailer on deusu.org (pointing to the domain https://webmail.your-server.de/login.php). The impressum link points to https://www.hetzner.de/rechtliches/impressum

So I guess the domains got sold.

**Comment by return42** [comment]
Yes, its dead / thanks for info. I will close #666 also.

**Comment by rachmadaniHaryono** [comment]
based on #666 https://github.com/MichaelSchoebel/DeuSu is already gone from github. But from google i find https://github.com/mediafactory/DeuSu which is fork from https://github.com/AcoonDe/OpenAcoon

@return42 maybe we can add this to `abandoned` section on `possible search engine` page documentation?

**Comment by return42** [comment]
I don't think so .. we have a lot of tasks open which are more important for our users. But if one wants to add a contribution, I will pick it up.
