### ISSUE TITLE
Infinite scroll: answer are repeated on each page

### ISSUE THREAD

**Issue by dalf** [searx/searx#668]
How to reproduce : search for ["user agent"](https://searx.me/?q=user+agent) with Infinite scroll activated.

Should the answer be disabled except the first page ? or should Infinite Scroll hide the answer ?

I vote for the first option : disabled answers except on the first page on the server side.

**Comment by kvch** [comment]
:+1: for disabling answers except in the first page

BTW why is the answer shown in every page? Google, Yahoo and Bing show answers only on the first page of the results. Following their practice would make it mush easier to fix this problem.

**Comment by dalf** [comment]
Good point, the answer should been given only on the first page.
So I guess `ctx['search'].pageno` should be tested here https://github.com/asciimoo/searx/blob/master/searx/plugins/self_info.py#L32
