### ISSUE TITLE
infoboxes doesn't merge with "bubalus" search

### ISSUE THREAD

**Issue by dalf** [searx/searx#669]
https://searx.me/?q=bubalus&category_general=on&time_range=

There are two infoboxes, both of them talk about the same subject and link to the same wikipedia page.

**Comment by kvch** [comment]
I checked the URL you provided, but there is only one infobox containing two different links to two differen pages. What do I miss?

**Comment by dalf** [comment]
The ddd engine was activated. With [!wikidata !wikipedia !ddd bubalus](https://searx.me/?q=%21wikidata+%21wikipedia+%21ddd+bubalus&time_range=) (language set to fr_FR) I can reproduce the bug :
![screenshot bubalus](https://cloud.githubusercontent.com/assets/1594191/17859962/df69c3c6-688b-11e6-87ed-d74d8f855a05.png)

The first infobox (from ddd) has a link to https://en.wikipedia.org/wiki/Bubalus 

The second infobox has links to : 
- https://fr.wikipedia.org/wiki/Bubalus
- https://en.wikipedia.org/wiki/Bubalus
- https://www.wikidata.org/wiki/Q83521?uselang=fr

**Comment by kvch** [comment]
Ah, I see.

**Comment by asciimoo** [comment]
I cannot reproduce it anymore. Feel free to reopen in case i messed up something and it is still reproducible.
