### ISSUE TITLE
Punycode to IDN conversion ?

### ISSUE THREAD

**Issue by dalf** [searx/searx#673]
Some DNS names are encoded with [punycode](https://en.wikipedia.org/wiki/Punycode)

searx doesn't decode them in the displayed URL, example :
https://darmarit.org/searx/?q=cafe-vie-privee.fr&categories=general&language=fr-FR

The displayed URL is `https://xn--caf-vie-prive-dhbj.fr/`
The displayed URL in the browser is `https://café-vie-privée.fr/`

It can be seen as a feature : there are many UTF characters that can't misread.
But it's also less user friendly.

A compromise : show the IDN version, and display the punycode in a tooltip (with the tooltip HTML attribute, so javascript is not required).
Another solution : a preference setting.

**Comment by dalf** [comment]
Python seems to support punycode natively : https://docs.python.org/2/library/codecs.html

**Comment by dalf** [comment]
For information :
https://news.ycombinator.com/item?id=14119713
https://www.wordfence.com/blog/2017/04/chrome-firefox-unicode-phishing/

**Comment by kvch** [comment]
To protect our users from phising attacks, I would rather not implement this at all. The articles you have shared demonstrate why it is a bad practice to use punycode in search results.

**Comment by dalf** [comment]
An example where the IDN version is useful as a user: search for ```/?q=!google+site%3A.香港&time_range=&language=en-SG```, the displayed URL are useless.

A more privacy version would be:
* display the punycode version in the result as now <-- not readable.
* display the IDN version in a tooltip <-- readable.

Actually, with the desktop browser, it is already the case with the tooltip at the bottom of the screen.

**Comment by kvch** [comment]
What do you mean exactly? You want to show the IDN version in a tooltip?

**Comment by dalf** [comment]
> What do you mean exactly? You want to show the IDN version in a tooltip?

Yes, that's why I trying to describe:
* display ```https://xn--caf-vie-prive-dhbj.fr/```
* show in tooltip ```https://café-vie-privée.fr/``` 
Basically as it is now with the addition of a tooltip.

Another way: 
* display ```https://café-vie-privée.fr/``` with a warning before or after the URL ```<p class="bg-warning" tooltip="punycode"><small>puny</small></p>```
* show in tooltip ```https://xn--caf-vie-prive-dhbj.fr/```

**Comment by SuperSandro2000** [comment]
I would just show the decoded name as text but the actually link is still encoded so that on hover you see the xn--.

**Comment by return42** [comment]
Hum, I try to follow the discussion but I cant reproduced the objective:

Since the old searx.me does no longer exists, I changed https://github.com/asciimoo/searx/issues/673#issue-173614541 to https://darmarit.org/searx/?q=cafe-vie-privee.fr&categories=general&language=fr-FR 

The first hit links to https://xn--caf-vie-prive-dhbj.fr/ and when I open that link, the (FFox) Browser shows me exact the same.  Hm ... where is my fail?
