### ISSUE TITLE
Add preferences to Firefox

### ISSUE THREAD

**Issue by cryptono** [searx/searx#675]
I would like to add Searx with all preferences I set to Firefox. 
Like at Startpage: https://www.startpage.com/do/preferences

**Comment by kvch** [comment]
Startpage has two options to save preferences: cookies and custom link. Both are supported by searx.

If you save your preferences on the page, the cookies are get saved. If you are not fine with cookies, you can copy the link at the bottom of the page, and add it to Firefox as a new search engine.
