### ISSUE TITLE
Support changing the default style on the server side.

### ISSUE THREAD

**Issue by Eig8phei** [searx/searx#683]
It would be great to have an option in settings.yml to change the default style.

**Comment by potato** [comment]
the default_theme in the ui section does exactly this afaik

**Comment by Eig8phei** [comment]
@potato This is for the style of the theme not the theme itself. For example the Pointhi style for the Oscar theme.

**Comment by TheChiefMeat** [comment]
I'd also like to see this so I can set the default style to Logicodev dark.

**Comment by silvernode** [comment]
I would like this as well. This would allow us to have a dark theme for all users by default

**Comment by kvch** [comment]
This is already implemented. Admins can configure `ui.theme_args` to pass theme-specific settings.

Set `oscar_style` to customize the style of Oscar. Available options are: `logicodev`, `logicodev-dark` and `pointhi`.

```yaml
 ui:
     theme_args :
         oscar_style : logicodev
```
