### ISSUE TITLE
0.10.0: Wrong redirection when BASE_PATH isn't /

### ISSUE THREAD

**Issue by nRaecheR** [searx/searx#684]
I'm trying to setup the docker image as an additional location on my domain with an "domain.tld/searx/ location. I've configured the Apache2 server to make a ProxyPass for the mentioned location to the server with the Searx instance.

Problem: Searx seems to rewrite the URL to the root (/) location which leads to a redirect to my main webpage.

Is there any way to prevent this rewrite of the URL? This seems to be new to 0.10.0, my previous (native) installation of 0.9.0 worked as expected.

**Comment by nRaecheR** [comment]
Is there anything new on this one? I had to shutdown my searx instance because it won't work anymore.

**Comment by pointhi** [comment]
did you try to set: https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L14 ?

**Comment by nRaecheR** [comment]
I had it running with 0.9.0 on a native installation, now I've migrated the whole server to docker usage and searx with 0.10.0 with the searx docker file. Unfortunately there is no way to customize the settings.yml in this scenario.

**Comment by Pofilo** [comment]
A new docker repo can help you: https://github.com/searx/searx-docker.
Feel free to reopen the issue if needed.
