### ISSUE TITLE
[task] Abandon bootstrap

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#687]
By my opinion. it is too big, wasteful, and unnecessary.  It does not offer anything special aside from having even worsen and weaken and more dependent web designers.

The new green/black oscar theme is very good, but even that theme should be bootstrap-free.

**The bandwidth it requires, and the consequent load it consumes, do not worth it, by my opinion.**

**Comment by dalf** [comment]
The simple theme is far lighter.
Reopen the issue, if you want to replace the default theme.

**Comment by GreenLunar** [comment]
The default theme is fine.
The bootstrap CSS files of the default theme are the files that I want to replace.
