### ISSUE TITLE
Problem with starting 0.10.0/New installation

### ISSUE THREAD

**Issue by zafai** [searx/searx#688]
Hello,

i just installed on a Debian Jessie searx but when i try to start searx i get his error message:

`WARNING:searx:You are using an old openssl version(OpenSSL 1.0.1t  3 May 2016), please upgrade above 1.0.2!
Traceback (most recent call last):
  File "searx/webapp.py", line 46, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ImportError: No module named werkzeug.contrib.fixers`

Please help me with this error thank you in advance

By the way really great project!

**Comment by nevtag** [comment]
First off all, this is not an error, it's a warning.

And what to do is still standing in the warning: upgrade openssl above 1.0.2.

But searx will run with your old openssl version.

**Comment by zafai** [comment]
Thank you for you reply please read the traceback Part of the warning that is the reason the server is not starting. Thank you

**Comment by nevtag** [comment]
Sorry, was not yet fully awake when I replied.
Did you install all the needed packages?

**Comment by zafai** [comment]
No problem yes all packages that are in the wiki install manual but I still get this error

**Comment by nevtag** [comment]
Ok, I test the installation on my jessie virtual machine clone(basic installation only web server, ssh deamon), and I must say it is running with no errors.
Well the openssl warning was shown.
I think delete the searx dir and try the installation again.

**Comment by zafai** [comment]
Thank you for your fast help i just try is again and with the fix from another thread it worked 
https://github.com/asciimoo/searx/issues/686
