### ISSUE TITLE
[doc] How to optimize searx performances?

### ISSUE THREAD

**Issue by tetraf** [searx/searx#69]
It may be interesting to add some doc on what to do to boost performances of searx.

I followed your install doc (with Debian/Nginx) and my search queries take 6 seconds (during which the Web page doesn't show anything). Well, I've seen other instances of searx which answers nearly instantly then I certainly miss something in the configuration but I don't find it in the doc.

**Comment by dalf** [comment]
stale ?

**Comment by unixfox** [comment]
Issue opened for improving Searx codebase in order to improve performance: https://github.com/searx/searx/issues/2067

**Comment by virtadpt** [comment]
For what it's worth, I'm using uwsgi to run multiple instances in parallel and it's been working nicely.  I haven't had a chance to sit down and write it up, though.  My searx.ini file:
```
[uwsgi]
workers = 12
disable-logging = true
single-interpreter = true
master = true
plugin = python
lazy-apps = true
enable-threads = true
module = searx.webapp
route-run = fixpathinfo:
virtualenv = /opt/searx/searx/env/
pythonpath = /opt/searx/searx/
chdir = /opt/searx/searx/searx/
socket = 0.0.0.0:8888
```
