### ISSUE TITLE
User guide for custom engines?

### ISSUE THREAD

**Issue by 1xPdd** [searx/searx#690]
Is there a how-to for users to add custom search engines? I looked but am not seeing anything.

**Comment by kvch** [comment]
There is a guide on search engies in the docs: https://asciimoo.github.io/searx/dev/engine_overview.html
However, a new engine guide is planned to be written. So if something is not clear in this guide, you could help us identify the problems of the docs. Thus, the new page could be more informative. :)

**Comment by 1xPdd** [comment]
Excellent. That's just what I was looking for. I'll give it a read and see if I come up with anything. Thanks.

**Comment by kvch** [comment]
Closing, as it has been inactive. Feel free to reopen if needed.
