### ISSUE TITLE
Missing UTF-8 encoding with Apache 2.4.18 and mod_h2 http2 --> Firefox won't display search page

### ISSUE THREAD

**Issue by klepptor** [searx/searx#693]
I just installed mod_h2 on my Apache 2.4.18 webserver under Ubuntu 16.04 which worked fine for all my sites, e.g. Owncloud.

Searx 0.10.0 just won't work. It seems to send the wrong encoding using http, see attached images. At least Firefox 48.0.2 can't handle this.

Maybe it's an Apache issue, but all other websites work well.
![1](https://cloud.githubusercontent.com/assets/3921511/18413045/e25aeeb8-779d-11e6-9b1f-3a85b0147856.PNG)
![2](https://cloud.githubusercontent.com/assets/3921511/18413046/e25bf7fe-779d-11e6-9296-746d93c303c0.PNG)

**Comment by Pofilo** [comment]
No news of the problem. Feel free to open again if it's still relevant !
