### ISSUE TITLE
Does searx.me anonymous via proxy servers?

### ISSUE THREAD

**Issue by rieje** [searx/searx#698]
Does searx.me anonymous via proxy servers? I couldn't find any mention of it but surely it is an important component of a privacy-oriented search engine. I'm also not sure if DDG uses proxy servers, but startpage appears to both proxy searches and the results (searches on search engines come from startpage's servers and clicking the results can optionally be proxied as well, which is incredibly useful).

**Comment by ghost** [comment]
If you use clearnet service(searx.me), you are 100% NOT anonymous.
Use http://ulrn6sryqaifefld.onion/ instead of clearnet.

**Comment by dalf** [comment]
Why is there a problem with clearnet service?

**Comment by asciimoo** [comment]
@rieje, searx.me doesn't use proxies to reach search services. Proxies are one more entity where the data possibly can be intercepted, so while it can increase privacy it can also create new attack surface.

**Comment by kvch** [comment]
Closing, as it has been answered and inactive. Feel free to reopen if needed.
