### ISSUE TITLE
New Feature: Proxify all search results for increased privacy

### ISSUE THREAD

**Issue by ajvsol** [searx/searx#707]
Function: Replicating Ixquick's proxified metasearch capabilities.

Right now there's proxified image results, but not general.

To replicate them a solution would be to extract the text and formatting from search results. Results may in some cases look a bit odd if the site uses lots of javascript for example but it would be a fair tradeoff for maximum privacy.

Give this issue a +1 or a comment if you'd like to see this feature and asciimoo said he'd implement it if it was the most desired feature.

**Comment by virtadpt** [comment]
:+1: 

I was going to implement something like this in my bot that uses Searx as its search front-end, anyway.

**Comment by asciimoo** [comment]
The first beta version is available on searx.me and can be activated from settings.yml in other instances.
The proxy is a standalone app, available here: https://github.com/asciimoo/morty.
I'll document the setup if it found to be usable after some tests.

**Comment by ajvsol** [comment]
Awesome! Where is the preference to enable it on searx.me?

**Comment by kvch** [comment]
It is already available on searx.me. You just have to click on "proxied", instead of the big result url.

**Comment by ajvsol** [comment]
Oh cool I hadn't tried a search on this instance, thanks it works!

**Comment by jeroenev** [comment]
when will the docker-container be updated to add this feature? :D

**Comment by Pofilo** [comment]
A new docker repo can help you: https://github.com/searx/searx-docker.
Feel free to reopen the issue if needed.
