### ISSUE TITLE
Tags <xml> are hidden from result titles

### ISSUE THREAD

**Issue by GreenLunar** [searx/searx#711]

**Comment by dalf** [comment]
Example : https://searx.me/?q=%21google+xml+header+syntax&category_general=on&time_range=

The title to the link 
http://stackoverflow.com/questions/13743250/meaning-of-xml-version-1-0-encoding-utf-8
should be
`xml declaration - Meaning of - <?xml version="1.0" encoding="utf-8`
it is
`xml declaration - Meaning of -`
in searx

(the `<?xml version="1.0" encoding="utf-8` is not in the HTML source).

**Comment by dalf** [comment]
Technical details : 
* [```extract_text```](https://github.com/asciimoo/searx/blob/master/searx/engines/google.py#L223) is used in google.py
* Inside this function, [```xpath_results.text_content()```](https://github.com/asciimoo/searx/blob/master/searx/engines/xpath.py#L31) returns ```... <?xml ...``` instead the original content ```... &lt;?xml ...```
* Then [```html_to_text```](https://github.com/asciimoo/searx/blob/7eed8a5dd909ca70d45fdff5706bb207e6aa8bdf/searx/utils.py#L127) sanitizes the content, and removes the thing that look like an xml tag

About ```xpath_results.text_content()``` it seems there are an option not to decode entities for the XML parser but not for the HTML parser : http://lxml.de/parsing.html#parsers

Perhaps extract_text should uses [```etree.tostring(html, method="text")```](http://lxml.de/tutorial.html)
