### ISSUE TITLE
Unit conversions returning incorrect results

### ISSUE THREAD

**Issue by thaokai** [searx/searx#712]
[x] [unit] to [unit2] searches for conversions consistently return incorrect results. Some tests below:

AREA:
1.0 sq ft = 11.69 sq m, 1 sq ft (sq ft) = 11.69 sq m (sq m) [INCORRECT, should be 0.092903]
1.0 sq m = 11.7 sq ft, 1 sq m (sq m) = 11.7 sq ft (sq ft) [CORRECT]
1.0 sq m = 11.665 sq cm, 1 sq m (sq m) = 11.665 sq cm (sq cm) [INCORRECT, s.b. 10,000]
1.0 sq m = 11.71 sq in, 1 sq m (sq m) = 11.71 sq in (sq in) [INCORRECT, s.b. 1550]

TORQUE:
1.0 ft lb = 6.82 n m, 1 ft lb (ft lb) = 6.82 n m (n m) [should be 1.35581795]
1.0 n m = 109.91 ft lb, 1 n m (n m) = 109.91 ft lb (ft lb) [should be 0.737562149]

VOLUME:
L to oz does not work

VELOCITY:
km/h to m/h does not work

No further tests were performed.

**Comment by kvch** [comment]
AFAIK these results are coming from DuckDuckGo (from definitions). So it is a bug in DDG, not in searx.

**Comment by dalf** [comment]
(I can't reproduce the bug)
