### ISSUE TITLE
ImportError: No module named certifi

### ISSUE THREAD

**Issue by Tobus** [searx/searx#713]
Hello,
I installed searx according to the searx wiki. When I try to start webapp.py, following error occurs:

root@:/var/www# python searx/searx/webapp.py
Traceback (most recent call last):
  File "searx/searx/webapp.py", line 31, in <module>
    from searx import logger
  File "/var/www/searx/searx/**init**.py", line 18, in <module>
    import certifi
ImportError: No module named certifi

What did I wrong? Anybody a idea?

Best regards
Tobus

**Comment by nerzhul** [comment]
just install python-certifi

**Comment by devonhk** [comment]
Did you run `pip install -r requirements.txt` from within a virtual environment?
The `certifi` package is in the `requirements.txt`

**Comment by Tobus** [comment]
Ok thanks, may I forgot this ;)

**Comment by ayaanalamansari** [comment]
hi, I am also facing the same problem, but `certifi` package is already installed.
when running webapp.py, then it is running fine,
But after configuring uwsgi when testing uwsgi then it says the same error, 
Unable rectify what's the issue. Can anybody help?
