### ISSUE TITLE
Time menu german translation: Letzten Monat

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#714]
In the actual version "Letztes Monat" is written. Right would be: "Letzten Monat"

**Comment by DanielGilbert** [comment]
I don't agree with @cy8aer - it should be the nominative, which is "Letzter Monat", not the accusative.

**Comment by cy8aer** [comment]
@DanielGilbert sic! You are right.

**Comment by kvch** [comment]
Closing as old and should have been addressed in Transifex.
