### ISSUE TITLE
Search API - Did not retrieve search results

### ISSUE THREAD

**Issue by ThraaxSession** [searx/searx#716]
Hello, 

when I use the search API like this: [/search?q=test 2](/search?q=test 2)
I'll get this result:

> Sorry! we didn't find any results. Please use another query or search in more categories.

After reloading the page it retrieves the results. Might be related to a previous issue ticket. #710 But not sure.

Edit: It seems to be random, sometimes I get a result and sometimes I don't. 

Regards
Gino

**Comment by devonhk** [comment]
Can you provide more information? Like what search engines you were using. Whether you were testing locally or using a `searx` instance. Also if this is random it could just be requests timing out.

**Comment by ThraaxSession** [comment]
Hi,
I use my own instance: [GinoHereIam's Searx instance](https://searx.gino-atlas.de/)
hm might be timeout, how to figure out? Is there an option to increase the timeout?
I use following search engines: `Wikipedia, Bing, Currency, Wikidata, Google, Yahoo, dictzone`

**Comment by asciimoo** [comment]
@GinoHerelam, you can finetune timeout values in `settings.yml` for each engine.

**Comment by ThraaxSession** [comment]
@asciimoo Is there a global timeout, which I can finetune afterwards?

**Comment by dalf** [comment]
There is request_timeout :
https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L22

**Comment by return42** [comment]
Feel free to reopen issue, if your problem is not solved.
