### ISSUE TITLE
remove ixquick from general search engines

### ISSUE THREAD

**Issue by ghost** [searx/searx#719]
It looks like StartPage and Ixquick have merged. There's no need to offer both Ixquick and StartPage now.

**Comment by ajvsol** [comment]
Legally merged but they still offer the separate searches (SP for Google proxy and IX for metasearch proxy).

> StartPage results in a classic interface are available at classic.startpage.com.
> 
> Current Ixquick search results are still available at www.ixquick.eu in a modern interface.

[Link](https://classic.ixquick.com/eng/classic-ixquick.html).

**Comment by ghost** [comment]
@neomodern I didn't know that Ixquick search is still available at https://www.ixquick.eu/. Thanks for the heads up!
