### ISSUE TITLE
"Tracker URL remover" incorrectly removing parts of URLs

### ISSUE THREAD

**Issue by ghost** [searx/searx#722]
I've noticed that some URLs break when the plugin is activated. Specifically [**NSFW**] pornhub.com video results. Examples:
`https://searx.me/?q=cod%20montage%20pornhub&categories=general`
`https://searx.info/?q=cod%20montage%20pornhub&categories=general`
Everything behind `/view_video.php?vie` is removed resulting in a redirection to the wrong page (`/video`).

**Comment by devonhk** [comment]
This is the regex that's the problem `re.compile(r'(wkey|wemail)[^&]+&?')`. It matches the `wkey` in `viewkey`.

It's in the tracker_url_remover.py
