### ISSUE TITLE
Bing image search result case insensitivty leads to wrong images being returned

### ISSUE THREAD

**Issue by Fironet** [searx/searx#723]
Was testing the SearX image results for the first time and searching for `site:neogaf.com jim2point0` returned a single odd result of a scantily clad woman among the dozens of other expected PC gaming screenshots (pixelated it just a bit as we're on Github).

![image result censored](https://cloud.githubusercontent.com/assets/6971981/19157479/2c8dee16-8c31-11e6-9522-eac2d953f407.png)

Since this isn't the type of thing typically allowed on the site I was searching for I clicked on the original URL and discovered the actual image on the page shared the same characters but a different case.

The direct image from the Bing-powered image results is: `http://i.picpar.com/gXY.jpg`
The actual image from the source page is: `http://i.picpar.com/GXY.jpg`

Two completely different images. I'm guessing this is a Bing crawling bug or limitation but I wasn't sure. Any thoughts?

**Comment by Pofilo** [comment]
Problem seems to be solved. Feel free to open again if it's not !
