### ISSUE TITLE
This stopped working today

### ISSUE THREAD

**Issue by nerotic** [searx/searx#725]
It's not just you! http://searx.me looks down from here.

**Comment by asciimoo** [comment]
There are service independent networking issues. Working on the solution

**Comment by nerotic** [comment]
Great Adam,

Thanks for the update!

 Mark Oren                         http://nerotic.net/
 magento specialist

mark@nerotic.net [image: callto:neromadrid] callto:neromadrid [image:
tel:+1-347-875-0046] <+1-347-875-0046> [image:
http://www.linkedin.com/in/markoren] http://www.linkedin.com/in/markoren

**Comment by ghost** [comment]
@asciimoo your clearnet domain is now online, but I still can't connect to your hidden service(onion).
