### ISSUE TITLE
is ixquick working as intended?

### ISSUE THREAD

**Issue by ghost** [searx/searx#727]
Although using the Ixquick search engine returns results, I think it doesn't use https://www.ixquick.eu/ but rather https://www.ixquick.com/ which is just StartPage. Am I right?

https://github.com/asciimoo/searx/search?utf8=%E2%9C%93&q=ixquick&type=Code

**Comment by dalf** [comment]
https://support.ixquick.com/index.php?/Knowledgebase/Article/View/103/19/what-is-the-difference-between-ixquickcom-and-ixquickeu

**Comment by ghost** [comment]
I know that. I'm trying to say that I think it's redundant to provide the option to search from both StartPage and Ixquick when their results won't differ. Instead of just forwarding Ixquick queries to StartPage, `searx` should fetch results from https://www.ixquick.eu/ when Ixquick is turned on.

**Comment by ghost** [comment]
@asciimoo @dalf Would this change fetch results from https://www.ixquick.eu? I don't see a engine [here](https://github.com/asciimoo/searx/tree/master/searx/engines) for Ixquick.

**Comment by kvch** [comment]
@sixpointzero Yes.
