### ISSUE TITLE
Country-specific censorship

### ISSUE THREAD

**Issue by ghost** [searx/searx#730]
Since searx.me is hosted in Germany some music results are censored.

For example:
https://searx.me/?q=gangnam%20style&categories=music
https://searx.at?q=gangnam%20style&categories=music
The official music video is returned only on searx.at which is hosted in Austria.

I suppose this happens because the GEMA forced YouTube to remove access from German IPs to a wide range of music.
https://en.wikipedia.org/wiki/Blocking_of_YouTube_videos_in_Germany

This illustrates the problem further:
https://polsy.org.uk/stuff/ytrestrict.cgi?ytid=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9bZkp7q19f0

I think a workaround would be desirable if possible.

**Comment by devonhk** [comment]
There is a workaround, you can use a searx instance hosted in a different country. 
http://stats.searx.oe5tpo.com/
If the country in question is not available you can always take the initiative to host an instance yourself.

**Comment by ghost** [comment]
Thanks but I'm aware of this like you can see in my example case. I was referring to a workaround within searx's code itself.

**Comment by devonhk** [comment]
> Thanks but I'm aware of this like you can see in my example case

My bad I only skimmed over your post.
Do you know of any way of detecting when a search engine is omitting results due to take-down requests?
I don't have any good ideas on how to tackle this problem.

**Comment by ghost** [comment]
I'm unfortunately in the dark myself here. I just know that when I search on `google.de` it omits the official video but if I search from the same IP on `google.com` it shows it. I don't know about a way to do the same on YouTube. In the past you could set the region in the footer to `Worldwide` which displayed all videos but that option was removed recently and `USA` doesn't seem to work.

**Comment by ghost** [comment]
They just came to an agreement which should resolve the issue for most YouTube results.
https://en.wikipedia.org/wiki/Blocking_of_YouTube_videos_in_Germany#Agreement
Please feel free to close if this solves the problem sufficiently in your opinion. It does for me since I now get the results I was looking for.
Thanks a bunch for the awesome engine by the way. :)

**Comment by unixfox** [comment]
Feel free to choose the engine based on the country code listed on https://searx.space.
