### ISSUE TITLE
Question: Can I limit number of results per page ?

### ISSUE THREAD

**Issue by robogirl** [searx/searx#743]
I have a question.

Is it possible to limit the number of results per page to 10 or 20 or some other arbitrary number ?

**Comment by kvch** [comment]
Unfortunately, it is not possible. However, you could turn on the plugin "infinite scroll" so you don't have to care about the number of the results.

**Comment by kvch** [comment]
Closing, as the question is answered and it has been inactive. Feel free to reopen if needed.

**Comment by Zero3K** [comment]
Why is it not possible?

**Comment by Pofilo** [comment]
Simply because the functionality is not developed.
Feel free to open a PR if you take the time to develop it.
