### ISSUE TITLE
Stop showing Warning message against user

### ISSUE THREAD

**Issue by ghost** [searx/searx#747]
Warning! Please enable javascript to use full func of this website

Above big message shows in the browser when I use searx.me..
It's up to user to decide allow Javascript or not. Are you saying you want your users
to enable Javascript to harvest more data for profit or something?

Anyway, would you consider removing it? This is annoying because it's too large(waste 25% of smartphone screen)

**Comment by kvch** [comment]
No, the intention is not to make users leak more data. This message is shown to tell the user that using javascript more features are accessible (just like on every other pages). Users have the right to know that if JS is enabled, the page looks and acts different.
I agree with you, it is the users' decision to enable javascript or not.

But, it is worth considering to remove on mobiles devices and/or make the warning less prominent on the page.

**Comment by pointhi** [comment]
This message is shown because small screen + js disabled results in a not working menue -> user cannot go to the settings page without editing the url.
When this gets fixed, removing the message would be the logical way. Probably adding some icons when no js is enabled, or some other workaround.

**Comment by asciimoo** [comment]
It would be good to rewrite the menu to js-free, then we could remove the js required message.

**Comment by ghost** [comment]
That big box is gone, nice work! Now I can use searX with small screen mobile phone.
