### ISSUE TITLE
HowTo enable "infinite scroll" by default for each user?

### ISSUE THREAD

**Issue by der-domi** [searx/searx#754]
Hello all!

Can you please tell me how can I enble "infinite scroll" by default for each user?

dalf answered me some similar question a few weeks ago. But I don't know how to adapt this to the plugins.
https://github.com/asciimoo/searx/issues/703

By the way: The translation in:
https://github.com/asciimoo/searx/blob/master/searx/translations/de/LC_MESSAGES/messages.po#L113
must be "Unendliches Scrollen"

Thanks!
Dominik

**Comment by kvch** [comment]
AFAIK plugins cannot be configured using `settings.yml`. A possible workaround is to change `default_on` to `True` in `infinite_scroll.py` but I don't think that is the right solution. Best would be to load plugins like engines are loaded.

**Comment by der-domi** [comment]
Thanks for your help! This seems to be the correct setting. For example is in https_rewrite.py default_on "True".

Could it be that the infinite scroll currently (latest git master) not work? The content is not loaded when I reach the last search entry.

**Comment by kvch** [comment]
Well, it work for me. Have you tried restarting searx after modifying the file?

**Comment by der-domi** [comment]
Yes, I restarted uwsgi and apache. But it still not work.

I wondering. I updated to the latest git master version today and it works fine with scrolling. Then I made a fresh installation to a new directory and it seems that only the scrolling does not work.

Does make this sense?
