### ISSUE TITLE
Next Page returns the same results

### ISSUE THREAD

**Issue by schwarzwhite** [searx/searx#755]
Hi all

Whenever I click next page or the infinite scroll happens, the same results as page 1 are displayed.

If I manually try going from page to page via the URL, I also get the same issue:

/search?category_general=1&q=test&pageno=1&time_range=
/search?category_general=1&q=test&pageno=2&time_range=

Both of these pages would have the same results, perhaps with an ordering change.

I can see the infinite scroll is correctly posting the new page number every time.

Do you know what could cause this issue?

For the record the only thing I changed was using /search for the URL instead of /searx
My server uses HTTPS.

Be aware the POST URL 'out of the box' in infinite-scroll.js was '/' which I had to manually change to '/search'.

Any advice appreciated.

**Comment by schwarzwhite** [comment]
Oh, hang on, I've just noticed this page is having the exact same problem:

https://searx.me/

Is this a bug in the latest code...?

**Comment by asciimoo** [comment]
seems, bing paging doesn't work

**Comment by schwarzwhite** [comment]
Thanks for your update.

Does this require me to get your latest code?

The reason I as is because it seemed to magically start working again, but I can see it is broken now.

**Comment by kkaiser** [comment]
I can see this bug is marked as closed but in fact it still exists in 0.11.0 for example when bing returns only one result. You can try `"2016-03-26" "TKP New York Conference Center"` as a query to reproduce the bug.
