### ISSUE TITLE
unable to change certain preferences in some searx instances

### ISSUE THREAD

**Issue by ghost** [searx/searx#756]
There are several searx instances in which the _autocomplete_ (and sometimes, _style_) preference doesn't change if it's been preset with a search engine.

On my end, this includes the following searx instances -

https://www.citizen-cam.de
https://suche.elaon.de
https://www.heraut.eu/search
https://searx.info
https://searx.ch
https://searx.potato.hu

Is it just me or is anyone else facing this problem?

**Comment by prolibre** [comment]
Yes. In my instance ( https://www.heraut.eu/search/ ) I can change autocomplete ( ex. wikipedia or statpage) but can't desactivate it.

**Comment by kvch** [comment]
It seems that cookie setting fails when autocomplete and/or image proxy is default enabled.
