### ISSUE TITLE
infinite scroll does not work on installations not on root

### ISSUE THREAD

**Issue by der-domi** [searx/searx#758]
As mentioned in https://github.com/asciimoo/searx/issues/754 my infinite scroll does not work. Now I found out that it seems that I running searx in a non-root installation.

Can you reproduce this issue?

Best regards,
Dominik

**Comment by der-domi** [comment]
Hello, I want to ask carefully what's the state with this issue?

You can reproduce the wrong behaviour on the public instance: https://www.heraut.eu/search/

**Comment by asciimoo** [comment]
@der-domi sorry for the late answer, could you verify the fix?

**Comment by der-domi** [comment]
Great! Thanks for the fix! :-)
No problem. I have time. :-)
