### ISSUE TITLE
Preferences (german) Ergebniss in neuem Tab

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#766]
... this would be:

Ergebnis (singular)
Ergebnisse (plural)

... but not "Ergebniss"

**Comment by kvch** [comment]
Please, update the translations on Transifex: https://www.transifex.com/asciimoo/searx/ :)

**Comment by cy8aer** [comment]
That is an argument. Just wait, till I get transifex under control...

**Comment by cy8aer** [comment]
... done (hopefully...)

**Comment by kvch** [comment]
Cool, thanks. :)

**Comment by kvch** [comment]
Closing as string is updated.
