### ISSUE TITLE
[survey] Remove "cached" link from oscar results

### ISSUE THREAD

**Issue by asciimoo** [searx/searx#767]
I never use "cached" link which appears on all default results (oscar theme). The question is: do you use it/find it useful? React with :+1: if you vote for removing and :-1: for keeping.

**Comment by LuccoJ** [comment]
I definitely vote "keep" as it's not at all uncommon for me to try to read pages that have ceased existing, but perhaps it could be hidden inside a less conspicuous dropdown arrow like Google have moved to doing.

**Comment by realitygaps** [comment]
I'd vote for keep, i've used it a few times just in the last week (where the original page was taken down by court order for example).

**Comment by pointhi** [comment]
I also think it's quite useful on a regular basis. Like when a site is offline / no longer reachable

**Comment by LuccoJ** [comment]
Err, for the record, I thumbed up even though I meant "keep". It might be unintuitive that the thumbs-up means "remove this"... or I might simply be stupid.
But, a heads-up in case others did this.

**Comment by negroblack** [comment]
You can just edit the template to remove it if you don't like it.

**Comment by ghost** [comment]
I also think it's quite useful from time to time. Maybe if a future release adds more entries it could become too cluttered but currently it's fine.

**Comment by asciimoo** [comment]
Seems it is an actively used and useful feature, so keeping it. Thank you for your responses
