### ISSUE TITLE
POST requests (searches) have stopped working in Chrome

### ISSUE THREAD

**Issue by negroblack** [searx/searx#768]
Hello

This is not a problem in Firefox or Safari.

The latest version of Chrome on Mac (Version 54.0.2840.98 (64-bit)) can no longer do POST searches. If you do a search using POST, it just reloads the search index page.

How can I debug this to figure out what's causing it?

Note GET works fine.

Thanks.

**Comment by asciimoo** [comment]
@negroblack chrome cannot send POST on the URL which is set to the default search URL. Is searx the default search engine in your case? If so, try to rewrite your default search URL from `/?q=%s` to `/search?q=%s`

**Comment by nixoye** [comment]
@asciimoo how do we make it by default use GET so users coming to our site on chrome can browse without a problem?

**Comment by kvch** [comment]
@NIXOYE It is already handled in `opensearch.xml`. If the user agent is Chrome, it uses `/search` as the default search url. So `POST` can work at `/`. If searx is added to Chrome as it supposed to be done, it should work without any problems.

**Comment by thearkadia** [comment]
@kvch @asciimoo POST isn't working on chromium and it doesnt change to Get by default

**Comment by asciimoo** [comment]
@arkgit it works for me with the latest chromium. Do you have any custom browser settings/plugins?

**Comment by unixfox** [comment]
Works for me. I cannot replicate anymore.
