### ISSUE TITLE
Fetch Search Results According to Users Locale

### ISSUE THREAD

**Issue by Zeriuno** [searx/searx#77]
I tried to replace someone's browser's home pagewith searx, forcing him to quit Google. It failed and asked me to switch back to Google because searx was providing english-tailored results instead of french.
It is something I experienced myself, indeed: one can easily overcome it, but it slows down the user and really hinders searx wide adoption.

I think searx should provide user-language-oriented results.

**Comment by return42** [comment]
> Why wouldn't you automatically match the user preference to the browser language?

See https://github.com/asciimoo/searx/pull/1860
