### ISSUE TITLE
searx stopped working under Arch Linux

### ISSUE THREAD

**Issue by dagaz** [searx/searx#771]
Hello all!
Searx stopped working under Arch Linux. Installed ist 0.10.0-3. It just stopped working 2 days ago and to be frak: I dont have any idea why, beause I am just a user and no developer.

Here ist the output of `systemctl status searx.service`

```
[root@localhost user]# systemctl status searx.service 
● searx.service - Searx server
   Loaded: loaded (/usr/lib/systemd/system/searx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sa 2016-11-26 15:55:49 CET; 625ms ago
  Process: 27183 ExecStart=/usr/bin/searx-run (code=exited, status=1/FAILURE)
 Main PID: 27183 (code=exited, status=1/FAILURE)

Nov 26 15:55:49 localhost searx-run[27183]:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in _build_master
Nov 26 15:55:49 localhost searx-run[27183]:     return cls._build_from_requirements(__requires__)
Nov 26 15:55:49 localhost searx-run[27183]:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 674, in _build_from_requirements
Nov 26 15:55:49 localhost searx-run[27183]:     dists = ws.resolve(reqs, Environment())
Nov 26 15:55:49 localhost searx-run[27183]:   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
Nov 26 15:55:49 localhost searx-run[27183]:     raise DistributionNotFound(req, requirers)
Nov 26 15:55:49 localhost searx-run[27183]: pkg_resources.DistributionNotFound: The 'PySocks!=1.5.7,>=1.5.6' distribution was not found and is required by requests
Nov 26 15:55:49 localhost systemd[1]: searx.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 15:55:49 localhost systemd[1]: searx.service: Unit entered failed state.
Nov 26 15:55:49 localhost systemd[1]: searx.service: Failed with result 'exit-code'.
```

PySocks 1.5.7-1 is installed - but that is since 2016-08-20 wich worked finde. With the rest of the output I am totallay overstrained.

**Comment by kvch** [comment]
According to the requests requirements (https://github.com/kennethreitz/requests/blob/master/requirements.txt), version of PySocks must be 1.5.6.

**Comment by dagaz** [comment]
Thaks for the clarification and the dependencylist.
Unfortunally I could not downgrade the package directly. And it would be great if 1.5.7 would be supportet. (Therefore i let this issue open. If there is already an issue für 1.5.7 close this, please.)

But here is the solution for other Arch users:

Get PySoks 1.5.6 from here: https://pypi.python.org/pypi/PySocks/1.5.6
Extrackt the package, cd into the directory with the setup.py file and run:
sudo python2 setup.py install
Then start the service with "systemctl start searx.service" and check the status with "systemctl status searx.service". It shoud be running now.

Do not forget to blacklist python2-socks in /etc/pacman.conf and run "yaourt -Syyua" to rebuild the database.

**Comment by sukramblak** [comment]
it works with any pysocks version above 1.5.7. The community version was updated to  1.6.4-1 on 01.12.2016. These should install automaticly now. I would suggest closing this bug report

**Comment by dagaz** [comment]
Works fine. Thanks for the note.
