### ISSUE TITLE
searx only work with 80:8888 port and not with reverse proxy setup

### ISSUE THREAD

**Issue by nixoye** [searx/searx#774]
if i launch searx with sudo docker run -d --name searx -e IMAGE_PROXY=True -e BASE_URL=https://domain.tld searx

with my domain in the url searx doesnt work even though the docker contianer loads but when i launch searx with docker run -d --name searx -p 80:8888 -e IMAGE_PROXY=True searx it works fine.

**Comment by thearkadia** [comment]
@kvch any update on this?

**Comment by kvch** [comment]
I think that in the first case your searx is unreachable because the containers ports are not published. In the second command `-p` is specified, so it is made public. Thus, it is reachable from the host.
At least that is what I gathered from https://docs.docker.com/engine/reference/builder/#expose.
So if you run searx using 
```
sudo docker run -d --name searx -p 8888:8888 -e IMAGE_PROXY=True -e BASE_URL=https://domain.tld searx
```
your containers 8888 port is published at port 8888 at your host.

**Comment by thearkadia** [comment]
thanks @kvch that worked. shouldn't the "proxied" icon now appear under the results where the search engine used is displayed though?

**Comment by dalf** [comment]
You need to install [morty](https://github.com/asciimoo/morty) and then configure [settings.yml](https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L26-L27).

Morty is written in GoLang.

**Comment by josch** [comment]
Just as a data point, I run searx behind a reverse proxy myself (pound) and that works fine. So maybe the problem is not with searx but with your reverse proxy setup.

**Comment by hovancik** [comment]
Totally not sure whether this is related, but when I try: `docker run -d --name searx -p 8888:8888 -e IMAGE_PROXY=True searx` I am getting `docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/bin/tini\": stat /usr/bin/tini: no such file or directory".`

I am following https://github.com/asciimoo/searx/wiki/Installation on my macOS

**Comment by Wonderfall** [comment]
The Dockerfile needs an update. Perhaps I'll do it this weekend.
In the meantime you can use or build my image wonderfall/searx.

**Comment by nixoye** [comment]
any update on the dockerfile?

**Comment by Pofilo** [comment]
A new docker repo can help you: https://github.com/searx/searx-docker.
Feel free to reopen the issue if needed.
