### ISSUE TITLE
Add ability to turn plugins on by default

### ISSUE THREAD

**Issue by craftyguy** [searx/searx#778]
Similar to #754, this request is to add an option in settings.yml for toggling plugins so they can be configured to default to 'enabled' or 'disabled' for clients. 

One idea is to add sections for plugins in a similar format to that used for search engines, where a ```disabled : True``` could be configured for each one to explicitly disable it by default. 

Another idea might be to add a ```enabled_plugins``` option under the server tag, and plugins could be listed in comma-delimited form (similar to how this option is stored in the client cookie) to enable them by default.

**Comment by joshp23** [comment]
+1 for this. Being able to have DOI resolver on by default would be fantastic.

**Comment by asciimoo** [comment]
Implemented in a05c660
