### ISSUE TITLE
html tags in search content

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#779]
(found at git commit be6ae81cb2dbe3a9524470c6e16fca699950ce61, seems to occur in the last two days). There are html tags shown in captions and teaser texts of the search results (especially `<b>`-Tags). These should be rendered or ignored.

(funny: Github renders `<b>` in issue texts ;-)

**Comment by cy8aer** [comment]
example: 

`<b>searx</b>.me

<b>searx</b> - a privacy-respecting, hackable metasearch engine ... Powered by <b>searx</b> - 0.10.0 - a privacy-respecting, hackable metasearch engine
`

**Comment by cy8aer** [comment]
hm, `<b>` **is shown and rendered** `</b>`

**Comment by cy8aer** [comment]
... in addition: Ponthi is not rendered well (Line breaks in captions)

**Comment by asciimoo** [comment]
@cy8aer how can i reproduce the issue?

**Comment by cy8aer** [comment]
hm, just search for "searx". Looks like attachment.
![Uploading screenshot-searx.png…]()

**Comment by cy8aer** [comment]
I am sorry, reopening. I am not able to upload a screenshot...

**Comment by cy8aer** [comment]
![screenshot-searx](https://cloud.githubusercontent.com/assets/578172/21075842/62dce9e0-bf1c-11e6-9692-fb2b83cdfaf0.png)

Just search for "searx" and look at the entries... Looks for me like in this attachment done with newest version.

**Comment by cy8aer** [comment]
this looks fine with version 7e1f27e45924147cc2219ddb9299460f202b206b version (screenshot), d80fb2c8e8995facb3a25c152c47a93eecf1fee4 fails. 

![bildschirmfoto von 2016-12-10 21-14-16](https://cloud.githubusercontent.com/assets/578172/21075885/ac0906de-bf1d-11e6-87f2-2f151d7f7019.png)

**Comment by asciimoo** [comment]
@cy8aer thanks, checking. I rewrote the result escaping, that can cause problem in some engines

**Comment by asciimoo** [comment]
qwant fixed in c3dcebb, could you verify?

**Comment by cy8aer** [comment]
yes, works for me.
