### ISSUE TITLE
Enable HTTPS/TLS check from searchcode.com

### ISSUE THREAD

**Issue by boyter** [searx/searx#784]
Specificly this line https://github.com/asciimoo/searx/blob/8f48c518aa049a37e6e7721cb17ceef92c519ca8/searx/engines/searchcode_code.py#L40

It should be removed.

There was an issue with the root cert installed on searchcode.com a while ago which has since been resolved. Should enable this again. I suspect it may be an issue in the documentation index as well but have not checked.

**Comment by asciimoo** [comment]
@boyter great, thanks - both the project and the clarification =]
