### ISSUE TITLE
Support multiple shortcuts per engine

### ISSUE THREAD

**Issue by kekscode** [searx/searx#787]
At the moment, this works:

```
  - name : ccc-tv
    engine : xpath
    paging : False
    search_url : https://media.ccc.de/search/?q={query}
    url_xpath : //div[@class="caption"]/h3/a/@href
    title_xpath : //div[@class="caption"]/h3/a/text()
    content_xpath : //div[@class="caption"]/h4/@title
    categories : videos
    shortcut : c3tv
```

but this:

```
  - name : ccc-tv
    engine : xpath
    paging : False
    search_url : https://media.ccc.de/search/?q={query}
    url_xpath : //div[@class="caption"]/h3/a/@href
    title_xpath : //div[@class="caption"]/h3/a/text()
    content_xpath : //div[@class="caption"]/h4/@title
    categories : videos
    shortcut : c3tv, ccctv
```

does not work.

It does not break, which is good in my opinion. It still allows queries with `!c3tv <queryterm>` _but_ `!ccctv <queryterm>` seem to be converted silently to just `queryterm`. On the other hand: Introducing the same shortcut twice will not be tolerated at startup time. Good!

But: Over the time it will be difficult to find good and intuitive shortcuts for some search engines. It may be a good idea to allow rather cryptic (but very short) shortcuts and longer ones (more intuitive maybe) to balance that usability-wise.

The above mentioned `c3tv` shortcut is a mix between being short but rather intuitive (ccc for chaos computer club is quite often abbreviated as c3something or c3anything).

**Comment by kvch** [comment]
Engines can be used either by using their shortcut or the full name of the engine. For example you can search the new engine both using `!c3tv` and `!ccc-tv`.
I don't think that searx needs that feature right now. Maybe later, when too many engines are introduced.

**Comment by kekscode** [comment]
I though about it and i guess you're right.
