### ISSUE TITLE
editing html and css for themes

### ISSUE THREAD

**Issue by nixoye** [searx/searx#791]
I'd like to change the image on the homepage of my searx instance and change the name that appears on the top left corner. Where do I go to change these and how do I save them and get them up and running?

**Comment by kvch** [comment]
The name of your instance can be configured in `settings.yml` using the `instance_name` variable. Unfortunately, the image is not configurable yet using the config file. However, you could edit `templates/oscar/index.html` (if you use oscar :)) and change `img/searx_logo.png` to the path of the image you would like to use. Make sure that the image is under searx dir.
Little tutorial on how to build styles of searx after editing `less` files: https://asciimoo.github.io/searx/dev/quickstart.html#how-to-build-the-source-of-the-oscar-theme

**Comment by nixoye** [comment]
thanks @kvch trying to figure out how to have the advanced settings menus appear by default so its obvious you can also search for files\images on my instance.

**Comment by kvch** [comment]
Well, it is not configurable yet either. I guess it could be a useful feature. :)
In the mean time you could  remove `{% if advanced_search %}` and `{% endif %}` from `templates/oscar/advanced.html`. But these changes might conflict with future patches of searx.

**Comment by nixoye** [comment]
thanks so much @kvch its so much smoother now :)

**Comment by nixoye** [comment]
@kvch is it possible to edit this so it happens on the homepage as well? 0.12.0 seems to have this by default after searching but not on the homepage

**Comment by silvernode** [comment]
Old thread but I just named my image the same as the one in /usr/local/searx/searx/static/theme/oscar/searx_logo_a.png and overwrote it. For each style there is a different image to replace so keep that in mind.

**Comment by dorianvalerian** [comment]
*Really* old thread, but I've been wanting to change the homepage image for my private instance, and I followed all the above steps (added the image I wanted to /usr/local/searx/searx/static/themes/oscar/img/ and named it searx_logo_a.png, and also made the relevant change in index.html). However, the image is still the default searx logo. What am I missing?

(I did also want to change the name in the top left, but that happened without much trouble through the yml file)

**Comment by dalf** [comment]
@dorianvalerian  make sure sure to clean the cache of your browser.

**Comment by dorianvalerian** [comment]
@dalf I did that, no change. However, this time round I kept my eye on the Ubuntu command line (I'm on windows) while I ran it, and apparently it runs into an error when it comes to showing my image:
`PermissionError: [Errno 13] Permission denied: '/usr/local/searx/searx/static/themes/oscar/img/dorianx.png'`
Note that everything else is working just fine.
I don't understand — why would this image throw up this error when the default image had also been in the same /oscar/img directory?

**Comment by dalf** [comment]
> `PermissionError: [Errno 13] Permission denied: '/usr/local/searx/searx/static/themes/oscar/img/dorianx.png'`

It is a ... permission problem. `dorianx.png` must have the permission and user than the other files in this directory.

Have a took to : https://www.howtogeek.com/437958/how-to-use-the-chmod-command-on-linux/

**Comment by jatojoseph** [comment]
![searx-error](https://user-images.githubusercontent.com/29528121/101491589-37c37000-3964-11eb-9add-c0d8207bbb52.png)

Hi all,
I have done a few edits in my templates and wish to update the changes but `./manage.sh styles ` seems not to be working, also, `./manage.sh tests` is not working for PRs.
Lastly, how can I remove some of the categories under "Advanced Search"?
Any help pls.?
