### ISSUE TITLE
An option to use GET parameter instead of cookie to keep settings.

### ISSUE THREAD

**Issue by ghost** [searx/searx#796]
Current version of searx require user to accept cookies to remember settings.
Why not there's an option for GET request?

> [X] When I hit Save, make a URL.
> [ Save]
> 
> result: https://searx.what/?paramz=uvcgersvhwoarlfhernhverngfhvpa3rfwcnmg78cyhp7w4sgytcyz7

**Comment by ghost** [comment]
IIRC startpage/ixquick already support this.

**Comment by kvch** [comment]
There was already a discussion on the topic in #695

**Comment by ghost** [comment]
Sorry for this @kvch. Next time, if the issue is duplicate you can close and link to other issues.
