### ISSUE TITLE
Recent changes to Oscar (default) theme causing image search UI issues

### ISSUE THREAD

**Issue by Fironet** [searx/searx#806]
After the recent changes to the Oscar default theme the image result popups don't close consistently when clicking elsewhere on the screen and frequently don't load the images in the modal, in both Firefox and Chromium. Pressing the Escape key also doesn't close the modal window.

The main changes of this new version I've observed are:

- The removal of the close button for result modal pop-ups.
- Making the result thumbnails link to the modal pop-ups rather than the original URL (I believe the previous version linked to the URL and used Javascript to override it to display the modal).

Personally prefer the previous UI with its dedicated close button and more reliable experience. Any chance the previous features could be incorporated into the theme again?

**Comment by kvch** [comment]
I am sorry for your inconvenience. Are images not loading at all or just taking too long? When I tested it is sometimes takes 10-20 seconds depending on the size of the picture.

A close button is being born right now. :)

**Comment by asciimoo** [comment]
It is really nice that we have a pure css modal window, but it has other bugs too. E.g. the middle click (open in new tab) doesn't work which is a big regression.
As I saw it isn't possible to create css only modal window which also can open the given image on middle click.

Possible solutions:
 - revert the changes
 - user can enable/disable the current modal window functionality (question: what would be the good default? on or off?)
 - a css guru fixes the missing features somehow

devs what do you think?

**Comment by kvch** [comment]
As we want to release soon, I vote for reverting the changes. The other options raise lots of questions and answering those questions might take time. Unless the release can be delayed, I see no other way.

**Comment by Fironet** [comment]
> I am sorry for your inconvenience. Are images not loading at all or just taking too long? When I tested it is sometimes takes 10-20 seconds depending on the size of the picture.

It sometimes loads, sometimes just blank. When you say 'depending on the size of the image' is it now loading the full image in the modal window? As previously it only loaded the larger thumbnail IIRC. This may explain it. I may have just not waited so long as I'd been used to the quicker loading previously.

> A close button is being born right now. :)

Appreciated! Though it looks like some kind of reversion is being suggested anyway.

**Comment by kvch** [comment]
Closing, as these UI changes were reverted.
