### ISSUE TITLE
Search autocomplete suggestions when pressing enter once

### ISSUE THREAD

**Issue by ghost** [searx/searx#807]
This is a minor issue but why would a user have to press enter twice to search for an autocomplete term? In detail:
1. Activate any of the autocomplete engines.
2. Start typing a search term and select a suggestion with the arrow keys.
3. Press enter twice to search.

Why press enter twice? If the user wanted to keep editing the search term before searching they can do so with the autocomplete dropdown still open. One press of enter should be enough like DDG does it.

DDG also starts searching immediately when you click on a search term. I don't necessarily agree with that as I sometimes still edit after clicking it but I'm just going to assume most users don't if that's their design choice.

**Comment by dakotaclemenceplaza** [comment]
This is really annoying thing as it differs from most search engines behaviour (or at least from google). I constantly press enter on an autosuggestion and become irritated for a second because nothing happens.
