### ISSUE TITLE
Please allow installing static files and configuration to a different path

### ISSUE THREAD

**Issue by josch** [searx/searx#815]
Hi,

currently, setuptools will install everything into a path like `/usr/lib/python3/dist-packages/searx` on the system where searx gets installed. Unfortunately some of the content that thus ends up in `/usr/lib` then violates the Filesystem Hierarchy Standard. Thus, in Debian, we must put some files into different locations, like:

 - putting `README.rst` into `/usr/share/doc/searx`
 - putting `searx/static` into `/usr/share/searx` and adding a symlink to that into `/usr/lib/python3/dist-packages/searx`
 - putting `searx/settings.yml` into `/etc/searx` and using `SEARX_SETTINGS_PATH` when executing searx

While I could now maintain a patch in Debian that does all this, it would be easier for me if you could integrate at least some of that functionality on your side. That would then not require me to rebase my patch upon every release you make. There are different things you can do:

 - allow installing data files and configuration files into a custom directory through setuptools
 - make the path to the data files configurable either through a variable in the code that we can patch in Debian or through an environment variable

In the best case of course, I do not need to carry any patch against searx on the Debian site but I wanted to raise the issue here to see what your position on the issue is. Depending on what you are willing to do, I can then provide you with a patch.

Thanks!

cheers, josch

**Comment by josch** [comment]
Let me propose the following patch:

```patch
--- a/searx/utils.py
+++ b/searx/utils.py
@@ -181,15 +181,24 @@ class UnicodeWriter:
 def get_themes(root):
     """Returns available themes list."""
 
-    static_path = os.path.join(root, 'static')
-    templates_path = os.path.join(root, 'templates')
+    if 'SEARX_STATIC_PATH' in os.environ:
+        static_path = os.environ['SEARX_STATIC_PATH']
+    else:
+        static_path = os.path.join(root, 'static')
+    if 'SEARX_TEMPLATES_PATH' in os.environ:
+        templates_path = os.environ['SEARX_TEMPLATES_PATH']
+    else:
+        templates_path = os.path.join(root, 'templates')
 
     themes = os.listdir(os.path.join(static_path, 'themes'))
     return static_path, templates_path, themes
 
 
 def get_static_files(base_path):
-    base_path = os.path.join(base_path, 'static')
+    if 'SEARX_STATIC_PATH' in os.environ:
+        base_path = os.environ['SEARX_STATIC_PATH']
+    else:
+        base_path = os.path.join(base_path, 'static')
     static_files = set()
     base_path_length = len(base_path) + 1
     for directory, _, files in os.walk(base_path):
@@ -200,7 +209,10 @@ def get_static_files(base_path):
 
 
 def get_result_templates(base_path):
-    base_path = os.path.join(base_path, 'templates')
+    if 'SEARX_TEMPLATES_PATH' in os.environ:
+        base_path = os.environ['SEARX_TEMPLATES_PATH']
+    else:
+        base_path = os.path.join(base_path, 'templates')
     result_templates = set()
     base_path_length = len(base_path) + 1
     for directory, _, files in os.walk(base_path):
```

This introduces the environment variables `SEARX_STATIC_PATH` and `SEARX_TEMPLATES_PATH` which set the path to the static files and templates, respectively. Or would you rather have this be implemented as a configuration option in `settings.yml`, maybe under the `general` section?

I also might've found a bug. `webapp.py` calls `searx.utils.get_themes` with the configuration value for `themes` path if it is non-empty. But `get_themes` will append `static` and `themes` to the path that it is given and thus, the argument to the function is not so much the theme path but the searx path. This might also hint to some refactoring being required. The `get_themes` function being responsible for resolving the static and templates path is suboptimal and should be moved to a separate function.

**Comment by asciimoo** [comment]
done in #816
