### ISSUE TITLE
installation using docker file

### ISSUE THREAD

**Issue by vigneshchalapathy** [searx/searx#818]
#vigne@Vignesh MINGW64 ~/searx (master)
$ docker pull wonderfall/searx
Using default tag: latest
latest: Pulling from wonderfall/searx
3690ec4760f9: Pull complete
d44c1bf90f81: Pull complete
309dce69ebc0: Pull complete
a75502d70df7: Pull complete
Digest: sha256:e9f8acaaa90abe453bc7c0bd36e4c8515b4aa129a7aecda08bdb94657f1bc7f9
Status: Downloaded newer image for wonderfall/searx:latest

vigne@Vignesh MINGW64 ~/searx (master)
$ docker run -d --name searx -p $PORT:8888 wonderfall/searx
59dd4918e8d83f1adc51ad7003bb334e9a43fe3428d8bd7a3393cb947f3c7605

all is fine but  when I opened localhost:8888 ,it showed unable to connect

Please help me to run the file using docker

**Comment by vigneshchalapathy** [comment]
you can see the deployed image  here  http://192.168.99.100:32786/

**Comment by dalf** [comment]
Note : 192.168.99.100 is a private IP : https://en.wikipedia.org/wiki/Private_network
So this IP can't be access from public Internet.

**Comment by vigneshchalapathy** [comment]
yeah ok,I will correct that.But please suggest me a way to customize that
to the core for our college project.I have installed that by docker and
find no way to customize that.

I am attempting to make changes to the core logic.

**Comment by vigneshchalapathy** [comment]
Hello,

 I have  made changes to

httpd.conf file

ServerRoot "C:\xampp\htdocs\virtual"


and added this snippet


<Location /C:\xampp\htdocs\virtual>
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>



I recive his error

Status change detected: stopped

 Error: Apache shutdown unexpectedly.

  This may be due to a blocked port, missing dependencies,

 improper privileges, a crash, or a shutdown by another method.

  Press the Logs button to view error logs and check
 the Windows Event Viewer for more clues

  If you need more help, copy and post this
  entire log window on the forums


On Mon, Jan 9, 2017 at 7:16 AM, vignesh vicky <vigneshchalapathy11@gmail.com
> wrote:

> yeah ok,I will correct that.But please suggest me a way to customize that
> to the core for our college project.I have installed that by docker and
> find no way to customize that.
>
> I am attempting to make changes to the core logic.
>
>
>
>
> On Sun, Jan 8, 2017 at 6:10 PM, Alexandre Flament <
