### ISSUE TITLE
How to install searx in windows?

### ISSUE THREAD

**Issue by vigneshchalapathy** [searx/searx#821]
#Can anyone suggest me a way to install searx  which permits me to customize it to the core.

I use apache from xampp(windows 10 operating system)

I followed these installation procedures for apache.

Add wsgi mod:

sudo apt-get install libapache2-mod-uwsgi
sudo a2enmod uwsgi

Add this configuration in the file /etc/apache2/apache2.conf:

Snippet:

<Location />
    Options FollowSymLinks Indexes
    SetHandler uwsgi-handler
    uWSGISocket /run/uwsgi/app/searx/socket
</Location>

Note that if your instance of searx is not at the root, you should change <Location /> by the location of your instance, like <Location /searx>.

Restart Apache:
sudo /etc/init.d/apache2 restart

But when  i attempt to paste this snippet in  httpd.conf file,

Apache fails to run.

Also suggest me anyother basic installation procedures for windows.

**Comment by dalf** [comment]
If you use xampp, you should install mod_wsgi.

I think, but can't confirm that ```sudo apt-get install libapache2-mod-uwsgi``` installs mod_wsgi for apache, the one included in embedded Linux (The Ubuntu included in Windows).

So either : 
* you choose to use xampp, and you have to adapt the installation steps for Windows (python for windows, wsgi for windows, etc...). See https://code.google.com/archive/p/modwsgi/wikis/InstallationOnWindows.wiki and http://enkoding.blogspot.fr/2013/01/setup-python-for-web-in-7-steps-on.html
* or you use the embedded Linux. Install apache using ```apt install apache2```. The point I don't know is how to turn apache2 into a service. You can still start it by hand using ```service start apache2```

**Comment by vigneshchalapathy** [comment]
LoadModule wsgi_module modules/mod_wsgi.so
WSGIScriptAlias /<yourfoldername>"C:/xampp/htdocs/<yourfoldername>/"
<Directory "C:/xampp/htdocs/<yourfoldername>">
    Order allow,deny
    Allow from all
</Directory>


what does <yourfoldername> implies...

**Comment by vigneshchalapathy** [comment]
Hello,
          I  followed these steps,
http://enkoding.blogspot.fr/2013/01/setup-python-for-web-in-7-steps-on.html



when i  pasted this snippet 

LoadModule wsgi_module modules/mod_wsgi.so
WSGIScriptAlias /virtual"C:/xampp/htdocs/searx"
<Directory "C:/xampp/htdocs/searx">
    Order allow,deny
    Allow from all
</Directory>

in httpd.conf file


it throwed a error,

19:07:55  [Apache] 	Status change detected: stopped
19:07:55  [Apache] 	Error: Apache shutdown unexpectedly.
19:07:55  [Apache] 	This may be due to a blocked port, missing dependencies, 
19:07:55  [Apache] 	improper privileges, a crash, or a shutdown by another method.
19:07:55  [Apache] 	Press the Logs button to view error logs and check
19:07:55  [Apache] 	the Windows Event Viewer for more clues
19:07:55  [Apache] 	If you need more help, copy and post this
19:07:55  [Apache] 	entire log window on the forums

**Comment by vigneshchalapathy** [comment]
Can searx  be installed with Django

**Comment by dalf** [comment]
It's a different topic but : 
* there is no specific integration with Django. Searx just uses the HTTP protocol to produce HTML, JSON, RSS, CSV output.
* ampps uses Python 3.5, for now searx is written in python 2. There a port python 3 under development in the [py3 branch](https://github.com/asciimoo/searx/tree/py3/searx). mod_wsgi is included according to the documentation, so it should works as long as you can install the searx dependencies.
