### ISSUE TITLE
[ENGINE] unsplash.com

### ISSUE THREAD

**Issue by thearkadia** [searx/searx#822]
https://unsplash.com/ provides people with images under the Creative Commons Zero license so people can create awesome works of art with them.

https://madewith.unsplash.com/ has some art made with images from unsplash.com

**Comment by jfowl** [comment]
Can be closed because of 4a127b19de860a1f1e75f597dc0d53bfdd06e52e

**Comment by dalf** [comment]
https://github.com/searx/searx/pull/1412
