### ISSUE TITLE
the yandex search engine isn't working and other multiple issues

### ISSUE THREAD

**Issue by ghost** [searx/searx#823]
I tried to search with only the `yandex` search engine enabled for common terms like `s`, `a`, `city` etc. on several searx instances like

https://searx.hardwired.link/
https://searx.ch
https://searx.at
https://www.citizen-cam.de/

but that doesn't give me any results. This is in addition to `yacy` and `swisscows` not working [here](https://github.com/asciimoo/searx/issues/757) and [here](https://github.com/asciimoo/searx/issues/720). 

Can we do something about **three** search engines not working simultaneously? Moreover, my question over [here](https://github.com/asciimoo/searx/issues/727) hasn't been answered.

**Comment by kvch** [comment]
Closing as duplicate of #430, #757, #720.

**Comment by dalf** [comment]
Thank you for reporting issues.

Just notice that I do this project on my spare time, I think it's the case for all other contributors. There are more 70 engines now, most of them scrape pages, that's mean the API is not clearly defined : at any time an engine can starts to fail. Maintaining all these engines and the core of searx starts to be a huge thing. Feel free to contribute by writing code (python is not that hard, and it can be funny actually).
