### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request is being made.

### ISSUE THREAD

**Issue by craftyguy** [searx/searx#824]
It seems that Searx does not use https certificate verification, I see this message in the log every so often:

```

 /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

I'm not sure yet which search engine it is associated with.

**Comment by dalf** [comment]
Can you try : 
```sh
./manage.sh update_packages
```

According to the link you give : 

> Older versions of Python 2 are built with an ssl module that lacks SNI support and can lag behind security updates. For these reasons it’s recommended to use pyOpenSSL.
> If you want to install the packages manually, you will need pyOpenSSL, cryptography, idna, and certifi.

```./manage.sh update_packages``` will make sure that these packages are installed (except idna) as specified in https://github.com/asciimoo/searx/blob/master/requirements.txt

The ```urllib3.contrib.pyopenssl.inject_into_urllib3()``` is not done but it has been working since a long time without it.

**Comment by dalf** [comment]
Actually ```urllib3.contrib.pyopenssl.inject_into_urllib3()``` is done inside [requests package](https://github.com/kennethreitz/requests/blob/1285f576ae0a848de27af10d917c19b60940d1fa/requests/__init__.py#L53)

So HTTPS should works fine, try to run  ```./manage.sh update_packages```
if it's still not working, can you post here the result of ```pip freeze```

**Comment by craftyguy** [comment]
So I'm using my distribution's (Arch Linux) [package management system to install Searx and its dependencies](https://aur.archlinux.org/packages/searx/), and non pip. This pulls the latest version of Searx from git, and installs all of the dependencies listed in the requirements.txt. I have confirmed that the versions of the dependencies installed on my system reflect those listed in requirements.txt (see pip freeze output attached)

[pip_freeze.txt](https://github.com/asciimoo/searx/files/702781/pip_freeze.txt)

**Comment by dalf** [comment]
* How do you start searx ? using uwsgi ?
* If you start searx directly with ```python searx/webapp.py``` does it work ?

In both case, have you this warning in the log : 
```
The pyopenssl, ndg-httpsclient, pyasn1 packages have to be installed. 
Some HTTPS connections will fail
```

**Comment by kvch** [comment]
This warning is no longer show up when running searx. Feel free to reopen the issue if it shows up again.
