### ISSUE TITLE
Please consider adding a minimal theme that saves bandwidth

### ISSUE THREAD

**Issue by josch** [searx/searx#828]
The default theme (oscar) is unbearably slow with my internet connection (128 kbit/s). Loading only the front page takes 106 seconds. To fix this, I implemented a new theme which does not need css and javascript and does not load any images or icons.

To illustrate my situation, I took a screenshot of the firebug network graph:

![firebug output](https://mister-muffin.de/p/EWvO.png)

As you can see, nearly a third of a megabyte has to be downloaded only to display the front page.

And the above output is even a best-case scenario. Sometimes (probably since all resources are loaded at once) some javascript or css files will not be loaded at all because the request would timeout.

Yet another reason for my efforts are costs of mobile internet. When I'm abroad I easily pay 15 EUR per 10 MB. I don't want searx to already take up 0.3 MB of that...

Thus, I created a more minimal theme. Basically I just took oscar and removed the css, javascript and images from it. With that theme, the front page requires only 1.1 KB to be downloaded which can be done in under a second.

I just would like to ask you: would you appreciate adding a minimal theme like this?

I thought of adding certain styles to the theme to adjust how minimal the user wants it. For example: also disable images in the image search or the map preview in the map search. Or maybe allow some very minimal CSS to make things look better. Or maybe even allow some very minimal javascript for some very basic usability features.

For this to work better, I also have two wishlist bugs:

It would be nice if the theme could be chosen via the url. Otherwise, whenever I change to my slow internet connection, I first have to wait painfully long until the preferences page loaded which allows me to change the theme from oscar to the minimal one. Allowing something like `?theme=foo` in the url would be nice.

Secondly, the list of available themes is currently determined by the existance of a directory with the theme name in `searx/static/themes`. But that doesn't make any sense for the minimal theme because it ships nothing in that directory. It would make more sense to check `searx/templates` for the list of available themes because there cannot be a theme without a template, right?

You can grab the current status of my template from here as a gzipped tarball:

https://mister-muffin.de/p/Ss7y.gz

It follows two screenshots of the search results (top and bottom). As you can see, everything is still nicely usable.

![top](https://mister-muffin.de/p/3noV.png)
![bottom](https://mister-muffin.de/p/dAwf.png)

**Comment by kvch** [comment]
Just being curious... Why is the legacy theme not sufficient?

**Comment by josch** [comment]
Because the name of the legacy theme suggests that it is just still there for "legacy" reasons and that it might be dropped at some point in favor of themes with more "bling" like oscar. On the other hand it might also just be poorly named and instead the plan is to keep it around exactly to provide a theme for low bandwith users. Could you clarify?

**Comment by dalf** [comment]
for reference, more or less related to #687

**Comment by virtadpt** [comment]
👍 for this suggestion.  I've had problems loading the Oscar theme on my phone and tablet (multiple browsers), and a lightweight, no bells and whistles theme would be a really handy thing to have available.

**Comment by asciimoo** [comment]
`Legacy` is just the name of the theme - I admit it isn't the best.
We can rename it.

**Comment by dalf** [comment]
The simple was merged into the master branch, it can be use on searx.me.

On first load (compression enabled) : 
* for the first page : 23.3kb
* for a result page : 29,7kb

With js,css in cache (compression enabled) : 
* for the first page :  3.3kb (the size can be cut down by reducing the number of available languages).
* for a result page without image : 13,6kb

Not everything is implemented, but most of it the oscar features (RTL languages are not supported for now).
