### ISSUE TITLE
About new design: searx.me

### ISSUE THREAD

**Issue by ghost** [searx/searx#838]
I like the new look. However,

1. White + Bright green = Hurt my eye. Can you make that "green" URL to more dark green color?
2. "Start Search" --> "Search"(text) or (search icon)
3. I always see many [ ] boxes when I searched. Any ideas?

> [EI44] cached [EI50] Proxied

> [E075] Next page

To reproduce: Use TBB with searx.me. You'll see these boxes.

**Comment by asciimoo** [comment]
fixed, thanks the report

**Comment by ghost** [comment]
Hmm, I don't see color difference on http://ulrn6sryqaifefld.onion/ , but No.3 is definitely resolved.
Thanks!
