### ISSUE TITLE
Proxy Image URL(stop 3rd party connection).

### ISSUE THREAD

**Issue by ghost** [searx/searx#839]
Select "image" and search something. You'll get image results - but these are not proxied.
The Image server can know you are from searx.

expected:
http://ulrn6sryqaifefld.onion/imageproxy?hash=yugkcbeyrfverky&url=brkavreufbvaerfvberafver

hash=randomvar(100)
RealUrl=Decrypt(url,hash)
GetUrlAndRetrun(RealUrl)
/

**Comment by ghost** [comment]
Google Image Search can serve images directly from google servers.

**Comment by unixfox** [comment]
Use morty for that: https://github.com/asciimoo/morty
