### ISSUE TITLE
add embedded player to show videos directly inside searx

### ISSUE THREAD

**Issue by pointhi** [searx/searx#84]
It would be nice to show videos directly inside searx. Probably configurable in the preferences.

To be privacy-safe and make a continuous look and feel for that, I would prefer an open source player like [video.js](https://github.com/videojs/video.js), which also allows plugins for showing videos from youtube, vimeo,...

(probably, I would do the implementation of that functionality)

**Comment by asciimoo** [comment]
it's implemented in oscar theme, thanks to @Cqoicebordel

**Comment by Cqoicebordel** [comment]
You're welcome.

But what I can gather from @pointhi implementation, is that it's wildly different from mine, and I think, way better : I use players from the sites, when he is providing a unified searx player.

Anyway, I think we should keep in mind his way, to one day upgrade mine.
