### ISSUE TITLE
What is "it"?

### ISSUE THREAD

**Issue by ghost** [searx/searx#842]
"general
files
images
it <------------------------------------- ?
map
music
news
science
social media
videos"

**Comment by ghost** [comment]
also, "social media" can become "SNS" (shorter text).

**Comment by kvch** [comment]
"it" is short for information technology. :)

Could you tell me how social media can become SNS? I don't see any connection between the two.

**Comment by ghost** [comment]
No, the "information technology" is "IT", not "it".
Who will use this "IT" category? For what?

SNS = Social Network Services. Facebook, Twitter, and so on.

**Comment by kvch** [comment]
Closing, as the original user who opened it has disappeared. Feel free to reopen if needed.
