### ISSUE TITLE
Use browser's regional settings to show homepage and results

### ISSUE THREAD

**Issue by eemantsal** [searx/searx#844]
By default Searx loads the american version of its homepage, with all the text in english, and also the search results are from pages in english and the interface is in english as well, even if the browser's user agent shows other regional settings.
This, by one side makes the results poorly accurate, for most users expect results in their own language and related to their region (e. g. if I search for some gadget to buy, or some news regarding ome person I surely prefer stores in my country or that at least speak my language, and digital newspapers written in my lenguage and preferably from my region), and by other side, most people just don't understand english well enough for a good Internet browsing or don't feel comfortable being forced to read in a language that isn't their native ones.
So, I suggest to use the browser's user agent and the IP to improve the accuracy and utility of the results (the "default language shouldn't be english but the browser's language declared in the UA, for instance) and also the understanding. Sure the user can change all thi by hand, but I think it's an unnecessary inconvenience; other search providers work as I propose by default; IMHO it's the correct approach.

**Comment by asciimoo** [comment]
@eemantsal searx uses the `Accept-Language` HTTP header for the locale settings. How could be the user-agent used for this purpose?
IP based language selection is not always accurate and can cause problems if you are not in your home country/behind a proxy. I don't think that it generally improves searx.

**Comment by eemantsal** [comment]
Perhaps I haven't used the correct terminology. Pardon. :-s I'm not an informatics/web stuff professional and maybe I have some misunderstood concepts in my head. I thought the user agent in a web browser identifies the browser, its version, the operating system, screen resolution and several other things like the language settings. Excuse if my commentary was confusing.
What I meant was that web browsers have a method to communicate the language setting to websites, be it their user agent string or other thing, and most search engines seem to identify it correctly and load their websites in the corresponding localized versions, and filter the search results to priorize the ones in the browser's language. Couldn't Searx do the same? As I said, it loads the interface in english and returns results in english.

You are right about the IP thing when behind a proxy, VPN or such, but do you really think that the majority of computer and mobiles users in all the world (who I suppose are your target; if you are just centering in the US and its satellites then I should probably stop talking), are using a proxy?
The IP thing in fact was suggested thinking on improving precision of certain search results: Using the users' IP to priorize results if search "buy leather boots" the search engine could priorize results for websites and shops, phisical or virtual, in the user's country, even in his city; if looking for some regional info, like national news, the search engine should priorize news sites from the user's country, which have probably better info and understanding than foreign media, even if written in the same language. AFAIK that's what Google/Startpage and others do (I suspect Duckduckgo doesn't and that's why the results when searching info outside the english speaker world are so mediocre).
If you are hungarian or chinese you are getting results from your own country almost always since those languages, even if so big as mandarin is, are very geographically localized, but think of hispanics or english speakers, who are spread across the world. The results may be way unprecise: I don't think that an equatorial guinean person is very interested in look for something common he wants to buy in stores located in Spain or Argentina nor I think a new yorker prefers to read the national news from jamaican or irish media.
If I'm confusing concepts here too, and search engines use other "thing" different to the users' IP to localize the search results, it doesnt really matter, I suppose you get the idea and can "translate" to the right concept.

**Comment by asciimoo** [comment]
> What I meant was that web browsers have a method to communicate the language setting to websites

This is the `Accept-Language` HTTP header: https://www.w3.org/International/questions/qa-lang-priorities.en#background and searx uses it for the locale settings. Search language does not depend on this value currently. Allowing this behavior in search language selection could be a configurable option for an instance in the future.

> do you really think that the majority of computer and mobiles users in all the world (who I suppose are your target; if you are just centering in the US and its satellites then I should probably stop talking), are using a proxy?

This software is built and defaulted to support privacy minded users, even if some of the solutions are not the most comfortable for regular users with fancy smart phones and tablets.
Proxy/VPN/Tor usage is very popular in this field, I think.
For more details, see our contribution guide: https://asciimoo.github.io/searx/dev/contribution_guide.html

> are using a proxy?

Of  course, and I recommend it to you too. =]

**Comment by eemantsal** [comment]
> This is the `Accept-Language` HTTP header: https://www.w3.org/International/questions/qa-lang-priorities.en#background and searx uses it for the locale settings.

Oh, ok. Sorry for my ignorance xD
I don't understand why my Firefox loads the wrong language. I'm on a fresh clean profile. Qupzilla shows Searx interface in my language and also does Firefox on mobile. I suppose this issue is just a problem of my Ffox installation on the PC and other users aren't affected. :-|

> Allowing this behavior in search language selection could be a configurable option for an instance in the future.

Great to read! I suppose I'm not the unique that most of the time wants information in their language.

> This software is built and defaulted to support privacy minded users, even if some of the solutions are not the most comfortable for regular users with fancy smart phones and tablets.
> Proxy/VPN/Tor usage is very popular in this field, I think.

Ah, well, I guess I misunderstood the target users for Searx; I thought you were aiming it for general use, like Duckduckgo, Startpage, Disconnect, etc, even if on PC, not only fancy portable devices.
It's a pity, but, well, it's your project and you are free to develop it as you want, of course.

> > do you really think that the majority of computer and mobiles users [...] are using a proxy?
> 
> Of  course

Don't cheat, little trickster. xP. You do know perfectly that the huge majority of the Internet users don't even know what is a proxy. (¬.¬)

> and I recommend it to you too. =]

Hehe, thanks, I already do, ;); although most of the time I set my VPN client to use proxies in my country, precisely because I'm a heavy search engines user, and, if I'm searching for something, I want the search engine to find what I want, not results that may interest to people who lives in other continent but probably not to me. Life is too short to waste it in wrong search results. :P. As long as a search engine doesn't log my IP, access times, user agent (a recommendation in return, in case you aren't aware of it already: Random Agent Spoofer, a nice extension for Firefox that will fake your browser's user agent periodically), etc, I am reasonably safe, after all I dont live in Afkhanistan or such; and nothing best to trust a search engine that having its code visible to any expert that wants to verify it, like Searx's code.

Anyway, thanks for your explanations, I understand that your project is more focused on people from the english-über-alles speaking “geeky” world, very concerned that value privacy over everything even if that means lose basic efficacy and time. I don't share that vision, but it's a perfectly valid one and I wish you a big success with the project; it is still a very interesting search engine.
Cheers.

**Comment by ShalokShalom** [comment]
The very same happens here. German install, German browser (Firefox) and English/American UI and results, which means basically that the whole experience is confusing.

**Comment by nfk** [comment]
Hi,

Fixed on spot project see this [commit](https://gitlab.e.foundation/e/cloud/my-spot/commit/3425b984feb1eedd44d21bbd38e88050e05d245e). Now, by default locale and search language depends on the browser language settings. I can suggest an MR for searx if you want.

BR
