### ISSUE TITLE
number_of_results in JSON does not match frontpage

### ISSUE THREAD

**Issue by kkaiser** [searx/searx#855]
Hello,

For example the query _new york city_ shows:
> Number of results: 449,200,010

But in the JSON data the number always differs:
> {"number_of_results": 29400001, ...

Does the number in JSON represent something else? Or are maybe only a specific amount of pages returned for the JSON?

I have also noticed that when nothing has been found (``"number_of_results": 0, ``) the JSON document still shows some data. That seems to be Google's feature to show something close even no results matched the query.

Maybe you can explain.

regards,
Kevin

**Comment by dalf** [comment]
It seems there is bug : the link the json output has ```pageno=2``` instead on ```pageno=1``` or nothing.  When the pageno parameter asks the first page, number_of_results contains the right value.

Notes : 
* if you refresh the page, you may notice that the number may change
* this value is the max of values return by the different engines
* if this number is bellow the number of result, then the value becomes 0

**Comment by kvch** [comment]
Now that I fixed the bug described by @dalf, I still wouldn't close this issue, as @kkaiser's question is not answered fully yet. But let me answer it. When rss or rss or csv or json button s clicked on, a new search request is made, so it is possible that different engines respond in that case. Thus, the number of results may be different.

**Comment by kvch** [comment]
Closing, as it is have been inactive. Feel free to reopen if needed.
