### ISSUE TITLE
Is there still the bang-like feature on SearX?

### ISSUE THREAD

**Issue by ghost** [searx/searx#857]
Hello everyone,

First, a great thank you for all the job done! :+1: I saw on issue #296 that the bang-feature was implemented on SearX, but the linked wiki page has been removed, and trying with this [instance](https://searx.laquadrature.net/) something like `!wfr batman` gave me no result from WikipediaFR, as expected...
As the feature been removed? Or maybe I type an unknown bang for SearX? Thx in advance for your answer!

**Comment by ghost** [comment]
Quick answer: I just saw in the instance preferences, that the prefixes were documented there... Fill a bit dumb, but if I may, is there a reason why there no redirection, as DuckDuckGo does?

**Comment by kvch** [comment]
Yes. There is no redirection, because of security reasons described in #870.

**Comment by kvch** [comment]
Closing, as the question is answered and issue is inactive. Feel free to reopen if needed.
