### ISSUE TITLE
Searx.me is down.

### ISSUE THREAD

**Issue by ghost** [searx/searx#860]
searx.me (as Hidden Service) - Issuer : Let's Encrypt Verification

It's hidden service are also not accessible.

**Comment by asciimoo** [comment]
There are service independent network errors. Please use another public instance while it is down or setup your own searx: https://asciimoo.github.io/searx/user/own-instance.html
Thanks

**Comment by kskarthik** [comment]
You can use searx instance at search.disroot.org

**Comment by kskarthik** [comment]
https://search.disroot.org

**Comment by ghost** [comment]
I'll use my own instance, thanks.
