### ISSUE TITLE
not related to searx

### ISSUE THREAD

**Issue by ghost** [searx/searx#861]
not related to searx

**Comment by githubbantor** [comment]
c. Cache system: if same keyword, cache the result 1 hour(don't make internet request)

written in: PHP
tested by: 10+ users
for: local network

**Comment by kvch** [comment]
Is the source available somewhere?

**Comment by githubbantor** [comment]
It's in beta stage(but it's usable). The source code will be open source, but the main developer asked me
to check @asciimoo's feelings(if he say "no, stop it" we don't share our work).

Yes, once @asciimoo say go ahead, we'll upload our work once it's done(might take time).
