### ISSUE TITLE
qwant  bug with specific languages

### ISSUE THREAD

**Issue by remy18** [searx/searx#863]
Hello ,
From my tests I can say that qwant images works but only with "default language", if I set a language like french or english it give nothing

**Comment by kvch** [comment]
As I can see on the engine page, qwant engine does not support these languages. I wonder if the language support refactor missed qwant.

**Comment by remy18** [comment]
On the qwant website I can select france,gb or us.

**Comment by kvch** [comment]
Yes, but that does not mean necessarily that it is supported by searx. However, in this case it seems to me that these languages are supported by searx, but somehow does not work.

**Comment by kvch** [comment]
My bad, I checked the wrong part of the code. So the current implementation of qwant engine does not support searching when selected languages are English or French. This could be an enhancement of qwant engine.

**Comment by MarcAbonce** [comment]
Yes, Qwant requires a country code to work. I will send a fix when I have time.

Meanwhile, the workaround is to specify a country code (fr-FR instead of fr) when using Qwant.
