### ISSUE TITLE
/

### ISSUE THREAD

**Issue by ghost** [searx/searx#864]
/

**Comment by ghost** [comment]
Now I can search when searx.me goes offline again! Good.

So I tried searching some keywords and I found that some servers are doing filter bubble.

proof 1:
server name / results
searx.itunix.eu	0
search.mailaender.coffee	2
search.homecomputing.fr	1

proof 2:
framabee.org	15
search.deblan.org	0
searx.laquadrature.net	16
search.matrix.ac	15
search.alecpap.com	20

**Comment by ghost** [comment]
Search "fox pet" on searxes several times and you'll get:

A:
     How to Care for a Pet Fox (with Pictures) - wikiHow
    How to Care for a Pet Fox. Domesticated foxes can make great pets. They're often described as giant kittens, or a mix between cats and puppies. Because foxes are not ...
    http://www.wikihow.com/Care-for-a-Pet-Fox

    Can I Have A Pet Fox? | Popular Science
    Jan 23, 2013 · Foxes do not make good pets, it's only legal to own them in a handful of states, and domesticated ones can only be imported from a facility in Siberia.
    http://www.popsci.com/science/article/2012-10/fyi-domesticated-foxes

    Fennec fox - Wikipedia
    The fennec fox or fennec (Vulpes zerda) is a small nocturnal fox found in the Sahara of North Africa. Its most distinctive feature is its unusually large ears, which ...
    https://en.wikipedia.org/wiki/Fennec_fox

B:
     How to Care for a Pet Fox (with Pictures) - …
    How to Care for a Pet Fox. Domesticated foxes can make great pets. They're often described as giant kittens, or a mix between cats and puppies. Because foxes are not ...
    http://www.wikihow.com/Care-for-a-Pet-Fox

    Can I Have A Pet Fox? | Popular Science
    23/01/2013 · Do a YouTube search for pretty much any smallish animal you can think of and there'll be several videos of a "tame" or "pet" version. Any feline, any canid ...
    http://www.popsci.com/science/article/2012-10/fyi-domesticated-foxes

    Meet Juniper, The Pet Fox Who’s Basically An …
    We first met Juniper on Instagram, where we saw her frolicking on her mom's bed, and instantly fell in love. Who was this cute fox? So we decided to reach out
    http://www.boredpanda.com/juniper-pet-fox-happiest/

C:
     Can I Have A Pet Fox? | Popular Science
    Jan 23, 2013 · Foxes do not make good pets, it's only legal to own them in a handful of states, and domesticated ones can only be imported from a facility in Siberia.
    http://www.popsci.com/science/article/2012-10/fyi-domesticated-foxes

    Fennec fox - Wikipedia
    The fennec fox or fennec (Vulpes zerda) is a small nocturnal fox found in the Sahara of North Africa. Its most distinctive feature is its unusually large ears, which ...
    https://en.wikipedia.org/wiki/Fennec_fox

    Aidra Fox : Penthouse Pet October 2014
    Penthouse Magazine has for almost 50 years found the sexiest models to pose in risque nude photos just for you. Penthouse showcases every single Penthouse Pet that ...
    http://www.penthousestars.com/aidra-fox-penthouse-pet-october-2014/

Hmm. Results are different.

**Comment by ghost** [comment]
As a conclusion, user shouldn't use one searx website.
Instead, they should install searxes and use all searx engine randomly. I think.

**Comment by kvch** [comment]
Isn't this what searx engines would do in searx? I mean if you add multiple instances to a searx engine. it is possible to search using multiple instances.

**Comment by login2github** [comment]
@searxes
I was waiting for a simple UI, and this will reduce my smartphone's bandwidth. GJ.

@ghost
I removed "searx.xyz" from 'SES_SERVERS'. You should do that too.

@kvch
> Isn't this what searx engines would do in searx?

You're missing the point.
Searx don't make a connection to other searx servers.

I'm using searx.at, and if the website goes down/my network admin blocked it, I can no longer search anything.
Related to https://github.com/asciimoo/searx/issues/860 if they are down, the user will scratch their heads.

If the user install Searxes on their side, it will make a connection to all possible searx servers,
returning results when searx.at/searx.me is down.

**Comment by kvch** [comment]
> Searx don't make a connection to other searx servers.

@login2github  What do you mean? If you define an engine which is a type of searx engine, you can set multiple searx instances, like it is written in settings.yml: https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L468
Searx can make a connection to other searx servers, if you configure it to do it.

**Comment by searxes** [comment]
@ghost Yes, some Searx instances are editing their search result. These servers are removed from 'SES_SERVERS' array to keep searxes results clean.
@kvch It's about "simplicity". Anyone can install Searxes if they have WWW server, and a permission to add "1 file".

Here's a public instance: http://search.mkf2sbzzzllepeva.onion/
