### ISSUE TITLE
[SOLVED]Installation Problems

### ISSUE THREAD

**Issue by jnnngs** [searx/searx#866]
Hi Everyone,

I'm struggling to get searx installed and wondering if someone can point me in the right direction. I've tried VPS's from ovh, digital ocean and azure. I tried ubuntu 1404, 1504, 1510 and 1604, with docker, virtualenv and nginx , ports 8888, 8080 and 80. All of them result with searx running, but the web request to access it just times out. I've checked firewall rules and that searx is servicing the port correctly, but it now driving me crackers! :)

Does anyone have a known VPS (digital ocean?), OS (Ubuntu 1404?), and example working configuration (nginx ?) that I can use as a baseline?

Many thanks in advance!

**Comment by virtadpt** [comment]
Yes, I'm running a copy in a VM at DO (Ubuntu v16.04 LTS).  I basically followed the installation instructions and started it inside of a GNU Screen session, and it works a treat.  I didn't do anything special to the VM, I just used the CIS Benchmarks to harden it before I did anything else on the machine.

**Comment by jnnngs** [comment]
@virtadpt Which instructions did you follow? Docker? nginx? virtualenv ?

**Comment by virtadpt** [comment]
The virtualenv instructions from here: https://asciimoo.github.io/searx/dev/install/installation.html#basic-installation

**Comment by jnnngs** [comment]
Thanks. @virtadpt What your DO spec and what port number do you use? Also, do you access it over the internet or internally within the DO network?

Cheers dude!

**Comment by jnnngs** [comment]
SOLVED

For anyone else having issues, here is my set-up:
Instructions: https://asciimoo.github.io/searx/dev/install/installation.html, virtualenv & uwsgi  method

Port 8080 used
Digital Ocean - 2 Cores, 2GB mem, ubuntu 1604
UFW is disabled
IPTABLES, ports 8080 and 80 opened
`sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT`
IPTABLES redirected; port 8080 to 80
`iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080`

Tested on ports 8080 and port 80.

@virtadpt thanks for your help!

**Comment by virtadpt** [comment]
@neggs My VPS @ DO spec is pretty high because I use that VM for quite a few things, not just Searx.  4 CPUs, 4GB RAM, 60GB disk space.  I use it internally only (listens on 127.0.0.1) because I use Searx for its search API ALONE (https://github.com/virtadpt/exocortex-halo/tree/master/web_search_bot

**Comment by kvch** [comment]
Closing as it is marked solved.
