### ISSUE TITLE
Add a static file

### ISSUE THREAD

**Issue by jnnngs** [searx/searx#868]
Hi Everyone,

Quick question: Is it possible to add a static HTML file, either per theme/template or as common?

I'm using nginx location /, as per instructions.

**Comment by asciimoo** [comment]
@neggs I'd suggest to put static files to the `searx/static/` folder. Templates are for python generated content.

**Comment by jnnngs** [comment]
@asciimoo Yeah, I've tried that and I'm getting file not found (404). I've using searx with nginx with the following config:

```
server {
        listen   443;
        ssl on;
        ssl_certificate /etc/ssl/search404.io.pem;
        ssl_certificate_key  /etc/ssl/search404.io.key;

    server_name search404.io;
    root /usr/local/searx;

    location / {
            include uwsgi_params;
            uwsgi_pass unix:/run/uwsgi/app/searx/socket;
    }
```
any ideas?

**Comment by asciimoo** [comment]
@neggs try to restart searx after adding a static file, or serve static files directly from nginx with the following additions to the `server { .. }` block:

```
    location /static/ {
           alias /path/to/your/searx/static/;
           autoindex off;
    }
```

**Comment by jnnngs** [comment]
@asciimoo Many thanks, that worked a treat!!
