### ISSUE TITLE
Is there any point using both Yahoo & Bing?

### ISSUE THREAD

**Issue by OJFord** [searx/searx#869]
I believe Yahoo is just a front-end for Bing. [0] [1]

With that in mind, is there any point having even options for both in searx - nevermind both on by default?

[0] - http://www.pandia.com/articles/yahoo-bing
[1] - http://money.cnn.com/2013/05/10/technology/yahoo-microsoft/

**Comment by asciimoo** [comment]
@OJFord they provide different results.

**Comment by MarcAbonce** [comment]
Some times they return some slightly different results, but overall it seems like they indeed return the same.

For example:
!bing !yahoo are yahoo and bing the same now?
!bing !yahoo The Beatles Abbey Road
!bing !yahoo how many roads must a man walk down

Only when the query is short there is variation:
!bing !yahoo python
!bing !yahoo Bee Gees

**Comment by pietsch** [comment]
@asciimoo, please reconsider this one. Yahoo gets all its results from Bing these days. Time and again, I get poor results listed first because they appear in both Bing and Yahoo. This flaw diminishes the usefulness of Searx.

**Comment by kvch** [comment]
@pietsch Why is turning off either Bing or Yahoo using settings.yml or cookies not an option for you?

**Comment by pietsch** [comment]
I do not currently self-host a Searx instance. And I do not wish to keep cookies around. Why should Searx not work well out of the box?

**Comment by kvch** [comment]
Which engine should be disabled by default? Bing or Yahoo?

**Comment by pietsch** [comment]
Other things being equal, I would disable Yahoo by default as it is just a reseller these days.
