### ISSUE TITLE
Open Wikipedia/et al. when successful !wp result

### ISSUE THREAD

**Issue by OJFord** [searx/searx#870]
Searching with `!wp` yields at most one result: an exact match, or nothing.

For example, `!wp elliptic curve` shows only the Wikipedia page "Elliptic curve" despite "Elliptic curve cryptography" also being a page.

It seems to me then that a `!wp` hit should just redirect - I found what I'm looking for, I'm always going to click on that link next since I can't see any more information than was contained in my own search term.

**Comment by kvch** [comment]
Redirect is not enabled in these cases, because of security reasons. Users must validate the result and decide if it can be trusted or not. It would be quite a pain if searx redirected to a malicious site which could have been prevented by the user if he/she checked the result. Although, I see that Wikipedia engine can be trusted service, so enabling redirect might be reasonable for this specific engine.

**Comment by Zebrazilla** [comment]
I used to use bangs for instant redirect with wikipedia and youtube on ddg quite a bit and it's super useful in my book. It'd be great if redirection like this could be explicitly defined in settings for certain engines.

**Comment by 12people** [comment]
@kvch Is it really a safety issue, though? When I use a bang over on DDG, I know fully well what page I'm going to get. Bangs are learned, so there shouldn't be much of people accidentally being redirected somewhere where they didn't want to go.

Having bangs not redirect makes the feature completely useless for me.

**Comment by Madis0** [comment]
Since Searx is a _metasearch engine_, not a _search engine with meta options_, I would say the default should continue to be loading external results within Searx UI. However, I do support #1146 as a different method (!! vs !) of executing external search shortcuts.

**Comment by OJFord** [comment]
Closing this since it seems rejected, and doesn't personally bother/affect me any more since I no longer use Searx. (I use DDG exclusively, and make _heavy_ use of `!` searches going directly to the page I want, fwiw.)
