### ISSUE TITLE
Up-to-date health report: HTTP 301's

### ISSUE THREAD

**Issue by jnnngs** [searx/searx#871]
Hi,

The health report page could do we two instances updating to point to HTTPS rather than HTTP, as they using 301 to redirect;

57	recherche.monpsc.ca
58	search404.io

Cheers.

**Comment by dalf** [comment]
side note : search404.io oscar template has been modified to include roboto font from google : 
```html
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
```
as long
```html
<meta name="referrer" content="no-referrer">
```
is used by the browser there is no problem otherwise GET requests are leaked to google.

**Comment by jnnngs** [comment]
@dalf  Thanks for the heads-up. I guess its low risk as search404.io uses POST requests but to be on the super safe side I'll remove it completely!

Thanks again!

**Comment by jnnngs** [comment]
Change has now been made. @dalf thanks again for pointing it out.

**Comment by dalf** [comment]
Great :-) 

But there are two additional requests, one to download cloudflare.min.js and second one to download Rocket Loader. 

Disabling Rocket Loader won't solved the issue :  CloudFlare is used anyway.

About your issue, I think that @pointhi should be able to fix that ?

**Comment by pointhi** [comment]
I updated the entries in the database. Fixed stats should be visible tomorrow.

**Comment by jnnngs** [comment]
@dalf I've removed the additional requests so its now vanilla searx unless you spot anything else?

Thanks again.

**Comment by dalf** [comment]
@neggs : the search requests are going through CloudFlare (I guess CloudFlare provides the SSL termination), so the privacy is not increased.

So : 
* if CloudFlare provides Roboto, you can use it (or download Roboto font localy, see https://www.fontsquirrel.com/fonts/roboto for instance)
* Rocket Loader can be use

**Comment by jnnngs** [comment]
@dalf I'll sort out the Roboto fonts locally - thanks for the link.

Is it not recommended to use Cloudflare for certs/SSL in terms of privacy? If so I can use something else.

**Comment by dalf** [comment]
About Cloudfare and MITM : 
https://info.ssl.com/the-real-cost-of-a-cloudflare-free-ssl-certificate/
https://www.reddit.com/r/privacy/comments/41cb4k/be_careful_with_cloudflare/
(may be not the best articles, but they give the idea)

About Cloudfare about TOR users : https://en.wikipedia.org/wiki/Talk:Cloudflare#Tor

In my opinion the best option for privacy is no intermediate. If correctly configured, the static resources (js, css, fonts) are loaded only once by each browser.

**Comment by jnnngs** [comment]
Thanks. I'll move to a direct model rather than a MITM, as security is king with searx. It's not much effort and as you point out, caching performance wont be a problem :)

Cheers.

**Comment by jnnngs** [comment]
Done. COMODO cert installed and getting an A+ rating on [www.ssllabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=www.search404.io).

This blog post helped getting the A+ rating; [Optimizing HTTPS on Nginx](https://www.bjornjohansen.no/optimizing-https-nginx#comment-560)
