### ISSUE TITLE
How to make custom theme?

### ISSUE THREAD

**Issue by cswag** [searx/searx#875]
Hey, to test i've copied /themes/oscar and /templates/oscar and renamed them both to "custom", and re-uploaded them to the server running the searx instance. In the preferences section, the theme "custom" does not show. Is there any explanation on how to make a custom theme or how to add another theme?

Thx

**Comment by jnnngs** [comment]
Hi Mate,

This is what I did for search404.io, although its a lazy static method. There's probably a better way, so please consider this a cheap and dirty way of doing things :)

- Copy searx\searx\static\themes\oscar to new theme name (in same folder)
- Copy searx\searx\templates\oscar to new theme name (in same folder)
- Perform a global 'find and replace' within the searx\searx\templates\[new name] replacing 'oscar' with new theme name. This is to fix hard coded folder paths with the template files.
- Restart searx

Looking at what you have done above, it would seem that you haven't copied the static theme?

**Comment by cswag** [comment]
Works perfect, thanks :) I forgot to find and replace
