### ISSUE TITLE
Cannot combine words with quotes when searching

### ISSUE THREAD

**Issue by kuspilur** [searx/searx#876]
Being able to use quotes to combine words that appear in a certain order is a nice feature that many search engines support. It seems that this is missing in searx. Looks easy to implement, just pass on the quotes. Will this feature be available? 

Similar features that also are missing are using wildcards for matching any word (for example "this is a * test" will return "this is a big test", "this is a small test" and so on, or "+word" for returning results that contain the "word" word or "-word" for ignoring results that contain a "word". 

Anyway, thanks for the great work!

**Comment by kvch** [comment]
AFAIK quotes are passed to search engines. Thus, if an engine supports this "advanced" search, searx supports it, too.
