### ISSUE TITLE
How to use through Tor

### ISSUE THREAD

**Issue by levinuss** [searx/searx#886]
Hey,
according to the "Why use a private instance?" (https://asciimoo.github.io/searx/user/own-instance.html) paper searx can be configured to route the search traffic through Tor. I successful activated a proxy connection (for proxies, the config is obvious, I think). But how to go through Tor?

**Comment by MarcAbonce** [comment]
In the proxies section of your settings.yml file, you can use a socks5 proxy pointing to the port where you are running Tor. For example:
```
proxies :
    http : socks5://localhost:9050
    https: socks5://localhost:9050
```
Then you will probably also want to adjust your settings to disable engines that block Tor exit nodes and increase the timeout to account for Tor's slowness.

Or, if you want, you can pull my branch in #565 which tries to do all this in an easier way and supports hidden engines as well. And if anything goes wrong or you find a bug, you can obviously report it there.

**Comment by levinuss** [comment]
Thank you :)
