### ISSUE TITLE
import/export preferences support

### ISSUE THREAD

**Issue by anarcat** [searx/searx#892]
it would be nice to be able to import / export settings between instances. we're setup our own instance following the temporary shutdown of searx.me but now we must re-create our precious prefs there...

couldn't we just have a way to import/export a file?

(note: i know i can probably do this by inspecting cookies, but that's hardly intuitive for users. in fact, even if i could have done this myself, i didn't bother and just recreated the settings as it seemed easier...)

**Comment by stef** [comment]
indeed copying cookies is what you want to do to use your settings on other domains. maybe it makes sense to open an issue at the browser vendors tracker to make cookie/local storage handling more user friendly as cookies seem to be entirely in the interest of the tracking industry currently thus also the hidden nature of the management of those.

**Comment by Rik44444** [comment]
is there any progress on this? Any way to export/import or sync different Searx instances ?

**Comment by asciimoo** [comment]
It is implemented, check out the `/preferences` page.
