### ISSUE TITLE
default search tag

### ISSUE THREAD

**Issue by anarcat** [searx/searx#893]
when you setup a new instance, the "search tag" is "searx". (i'm not sure how this is called, but it's the search engine name when added to firefox.) because it's always the same name, firefox will refuse to add multiple searx engines because they are all named "searx".

this is a configuration option, so admins can fix this by changing the tag, but most admins don't, which makes it difficult to flip between entries or have multiple searx backends configured.

it would be better to (say) default the config setting to the FQDN (hostname -f) of the machine searx is running on. for example, be `searx.example.net` instead of `searx`.

thanks!

**Comment by asciimoo** [comment]
@anarcat searx uses the `instance_name` string from settings.yml for this purpose. It is "searx" by default, but you can modify it. E.g. firefox displays `Add "searx.me"` on searx.me.
I don't think that `$(hostname -f)` would be a better default. It can be confusing on systems with no proper domain configuration (my hostname is often just a single character).

**Comment by anarcat** [comment]
On 2017-04-08 09:28:29, Adam Tauber wrote:
> @anarcat searx uses the `instance_name` string from settings.yml for this purpose. It is "searx" by default, but you can modify it. E.g. firefox displays `Add "searx.me"` on searx.me.

Yeah, that's what we found in our deployment as well. I'm arguing the
default should be changed.

> I don't think that `$(hostname -f)` would be a better default. It can be confusing on systems with no proper domain configuration (my hostname is often just a single character).

Well, if not "hostname -f", something unique should be chosen, because
there are lots of conflicting instances out there.

I would argue that having "a single character" is still better than
"searx" as a default, because then it's unlikely to conflict with others
(unless the same letter is chosen of course). Besides, as you said it's
only the default...

(That's a rather strange convention, actually - i haven't seen many
hosts with single-character hostnames...)

For the record, the proper way to get the FQDN in Python is
socket.getfqdn(). See this for a more in-depth discussion:

http://stackoverflow.com/questions/11580023/how-do-i-get-my-computers-fully-qualified-domain-name-in-python

**Comment by asciimoo** [comment]
>  I would argue that having "a single character" is still better than "searx" as a default, because then it's unlikely to conflict with others (unless the same letter is chosen of course). Besides, as you said it's only the default...
> (That's a rather strange convention, actually - i haven't seen many hosts with single-character hostnames...)

It was just an example. What if the hostname isn't related to searx or there are multiple services under the same hostname? Or, the default hostname of an AWS server is the server's internal IP, in this case displaying hostname would be an automatic info leak.
FQDN is not a unique identifier for services, so i still don't agree that it would be a better default.

> Well, if not "hostname -f", something unique should be chosen, because there are lots of conflicting instances out there.

This makes sense

**Comment by anarcat** [comment]
On 2017-04-08 11:02:00, Adam Tauber wrote:
> It was just an example. What if the hostname isn't related to searx

then the admin needs to change the default. otherwise the search tag
will be a little weird, but this will still work.

> or there are multiple services under the same hostname?

then they would collide, by default, which is already the case.

> FQDN is not a unique identifier for services, so i still don't agree that it would be a better default.

well, it would more unique than a static default, so i think it would be
better...

**Comment by asciimoo** [comment]
> well, it would more unique than a static default, so i think it would be better...

More unique doesn't mean that the whole solution is better. It would solve (more or less) your exact problem, but it would also introduce new ones.

**Comment by allendema** [comment]
So can this issue be closed?
