### ISSUE TITLE
Como instalo Searx en Windows?

### ISSUE THREAD

**Issue by Elianmauri123** [searx/searx#895]
tengo entendido que tengo que instalar Docker, pero no entiendo la parte de "cd searx", que puedo hacer? como lo instalo? llevo usandolo como mi buscador preferido y ahora quisiera poder cambiar algunas cosas para hacerlo mas personal :) gracias de antemano.

**Comment by dalf** [comment]
are talking about : 
```
git clone https://github.com/asciimoo/searx.git
cd searx
docker build -t whatever/searx .`
```
from https://asciimoo.github.io/searx/dev/install/installation.html#docker ?

What do you want to do ? customize the installation ?

**Comment by Elianmauri123** [comment]
yes, well, i would like personalize it to make a little more personal, can i do?, have downloaded the git clone but i don't know to do after :/ what is the cd searx? where do i find it? i don't speak very well english but hope to understand me :), thanks.

**Comment by MarcAbonce** [comment]
No uso Windows ni Docker, así que no se cómo instalarlo allá.
Pero `cd searx` es solo el comando en la línea de comandos (cmd o PowerShell) para cambiarte al directorio [searx](https://github.com/asciimoo/searx/tree/master/searx) donde está el código.
Si el comando no funciona, probablemente es porque no estás en el mismo directorio en el que se descargó searx. Entonces tienes que ir al directorio desde la línea de comandos con `cd C:\lugar-donde-se-descargo-searx/searx`.

**Comment by Pofilo** [comment]
A new docker repo can help you: https://github.com/searx/searx-docker.
Feel free to reopen the issue if needed.
