### ISSUE TITLE
Minor correction to spelling on page

### ISSUE THREAD

**Issue by JamesColeman-SH** [searx/searx#900]
On the page https://asciimoo.github.io/searx/user/own-instance.html you have the phrase "Searx does not serve adds or tracking content" which should be "Searx does not serve ads or tracking content".

Sorry for having to point this out. I tried looking for the repository which contains the page, but I don't know where to find it.

**Comment by kvch** [comment]
The process of updating the documentation can be found here: https://asciimoo.github.io/searx/dev/contribution_guide.html#documentation It would be great if you updated the docs. :)

**Comment by JamesColeman-SH** [comment]
Oh... It is a branch....

**Comment by JamesColeman-SH** [comment]
https://github.com/asciimoo/searx/pull/902
