### ISSUE TITLE
An useless thread is created on each request in the general category

### ISSUE THREAD

**Issue by dalf** [searx/searx#903]
The commit 01e2648e93e718f84c77aed16326a14f2b498a2e introduces a regression : 
* before this commit, the request function was calls then if an url was requested a thread was created
* with this commit a thread is created for each engine 

It's not an issue except for one engine in the general category: currency.

Most of the time the currency engine doesn't send a request, but a thread is still created (which take time)

The call to the request function in the main thread is also a problem since some engine sends an HTTP request ([wolframalpha](https://github.com/asciimoo/searx/blob/master/searx/engines/wolframalpha_noapi.py#L66) for example).

A better solution would be a function can_accept defined inside the engine ? (similar to the PR #797) 

Edit : the PR #853 could be implemented as an engine too.

**Comment by kvch** [comment]
Closing the issue as @dalf is refactoring the request/response mechanism in searx. It will be asynchronous, so threads will be gone.
