### ISSUE TITLE
Add the Fediverse in social search

### ISSUE THREAD

**Issue by mangeurdenuage** [searx/searx#906]
Hello,
Would it be possible to add the instances of Gnu social in the search engine ? (for those who have a timeline that is public that is)
There's a lot of servers available
see:
https://social.guhnoo.org/
http://www.fediverse.org/

Happy hacking :)

**Comment by dalf** [comment]
gnusocial search can be implements with the json engine : 
```https://instance.hostname/api/search.json?q=%s&rpp=15```
accoding to http://skilledtests.com/wiki/Twitter-compatible_API#Search

**Comment by mangeurdenuage** [comment]
@dalf 
Seems promising.

**Comment by mangeurdenuage** [comment]
@dalf 
I just noticed something on loadaverage.
When your research on it doesn't work at all LA proposes to use multiple engines and searx is part of them.
See for [example](https://loadaverage.org/search/notice?q=s4g65s4hgr)

**Comment by Openmedianetwork** [comment]
The new version of mastodon has search built in https://github.com/tootsuite/mastodon/releases/tag/v2.3.0 ElasticSearch

**Comment by ahangarha** [comment]
Any update? We now have mastodon v3.

**Comment by tiotrom** [comment]
Take a look at https://fedisearch.com/ - it can search on the fediverse. Maybe you can use that. Would be super cool!

**Comment by seniorm0ment** [comment]
+1 to this, would be cool to get federated social media results. We have peertube for videos.

**Comment by dalf** [comment]
All the results I get from https://fedisearch.com are 9 months old.
The last message on https://qoto.org/@fedisearch is from July 13th 2020.

Is the backend / crawler still running ?

**Comment by return42** [comment]
I try to summarize

- API is broken
- result are old
- in the last 3 years many asked for but no one is willing to implement a PR

In short: I appreciate fediverse, but the search engine is crap.

Before we and others wasting more time with, lets close #906 and #2704.

We can reopen the issue when a working search engine is available.

**Comment by seniorm0ment** [comment]
There are multiple search indexes that exist for Peertube 

https://sepiasearch.org/
Being the "official" one I believe

**Comment by return42** [comment]
I am not familiar with fediverse  but I guess sepiasearch is indexing  Peertube not the fediverse, so how is it related to this issue asking for a fedisearch engine?

**Comment by dalf** [comment]
I close the issue "Add the Fediverse in social search"

**Comment by seniorm0ment** [comment]
Oh my bad, I'm dumb
