### ISSUE TITLE
Search request in the URL

### ISSUE THREAD

**Issue by sachaz** [searx/searx#911]
Hi,

(This is a feature request)
when I re-open my navigator it loose the last searches because the url is always the same and doesn't contain the searched worlds.
As result of a search we should be redirected on a url like: searx.aquilenet.fr/search?my++super++search 

Regards

**Comment by dalf** [comment]
In the preferences, choose GET for the Method : 
https://searx.me/preferences

**Comment by sachaz** [comment]
Hoo thanks ! Sorry for the noise.
Is it possible possible to set this value in the settings.yml ?

**Comment by dalf** [comment]
on settings.yml : 

``` yml
search:
    ...
    method : "GET"
```

solved in https://github.com/asciimoo/searx/issues/703

**Comment by mangeurdenuage** [comment]
@sachaz 
Remember that URLs aren't encrypted so the words that you search are in plain text in the URL. (If I don't mistake, if I am, please correct me).
Have a good day ;)

**Comment by sachaz** [comment]
Ho nice thanks !
@mangeurdenuage if I'm requesting the URL in SSL the text is encrypted ?

**Comment by mangeurdenuage** [comment]
@sachaz 
When you say " requesting the URL in SSL" you mean for example a URL like this
HTTPS://searx.gnu/search=pin+trees

If yes then no the URL itslef isn't necessarily encrypted.
I recommend you to read this post #695 
To extend your knowledge about internet privacy please watch this conference (only 30 min)
https://www.youtube.com/watch?v=eM4J7ljCExM

**Comment by dalf** [comment]
@mangeurdenuage, what do you mean not necessarily encrypted? 

If HTTPS is used, everything is encrypted except the domain name and the TCP port/IP couples. Of course there is the problem with compression, weak protocol, etc.. 

May be I miss a point? 

IMO, the two issues about URL are :
* the browser history. 
* logs : form (when POST is used) are not logged by default on server, URL are logged by default. 

But note that the title of page contains the query. So the browser may store that query in the history (whatever the method GET or POST).

**Comment by mangeurdenuage** [comment]
@dalf 
I thought the rest of the link got revealed too.
My mistake then.
Isn't their a problem with DNS tho ? or it is just the beginning of the URL that gets revealed ?

**Comment by sachaz** [comment]
For me there is no issue on using the post method: all the traffic goes through the encrypted SSL  channel between the client and the server (https://en.wikipedia.org/wiki/Transport_Layer_Security).
You can test the SSL/TLS capabilities of Your Browser: https://www.ssllabs.com/ssltest/viewMyClient.html
and the servers part: https://www.ssllabs.com/ssltest/index.html
As dalf mentioned in the browser history, the risk is on the user side in his browser history, the user he have to be aware on his system privacy (using an open source system) and by disabling these logs if needed.
DNS is not related because the post request goes to the searx server through the SSL channel.
Open DNS server can be used like https://diyisp.org/dokuwiki/doku.php?id=technical:dnsresolver

**Comment by d0t1q** [comment]
The SSL encryption is done at the tcp layer between the server and client, everything sent via ssl is then encrypted (post/get). This means the URI is encrypted, DNS is not encrypted though so the domain itself is visible.
