### ISSUE TITLE
Google Web Search API deprecated

### ISSUE THREAD

**Issue by dalf** [searx/searx#92]
The google, google_news, google_image engines use the Google Web Search API.
According to https://developers.google.com/web-search/docs/ the service stops the September 29, 2014 !

**Comment by asciimoo** [comment]
Seems, google api is still fully functional, so closing this issue

**Comment by MarcAbonce** [comment]
Now it's really deprecated.
I get "This API is no longer available." from google news.

**Comment by kvch** [comment]
Closing, see f6e9c074bbe8b4237ee361befa8dcb2c6d31a11a. The last Google service which depended on it was rewritten.
