### ISSUE TITLE
different search results on public instances for bing search

### ISSUE THREAD

**Issue by kkaiser** [searx/searx#923]
Hello,

I noticed very different search results when using public instances compared to my own and wonder what the reason could be. I get that the order can be different but it seems totally off, also when I go to bing directly. It doesn't seem to occur with google results.

searx.me all
![searx.me all](https://cloud.githubusercontent.com/assets/1774205/26142782/6639f8ac-3ae2-11e7-89bd-bea52f0ae82f.png)
searx.me bing
![searx.me bing](https://cloud.githubusercontent.com/assets/1774205/26142781/6638e516-3ae2-11e7-971c-1fde6bba3f0b.png)
local bing+google in preferences
![local bing+google in preferences](https://cloud.githubusercontent.com/assets/1774205/26142779/66365210-3ae2-11e7-9a1a-7e2f48f84bb3.png)
local bing only
![local bing only](https://cloud.githubusercontent.com/assets/1774205/26142780/6637f2dc-3ae2-11e7-80f0-6de4c1482e6c.png)

Is there a change you made in recent versions or could you imagine something that explains this behavior? I also tried to use a POST request directly with `engines` set with the same outcome.

**Comment by dalf** [comment]
I haven't checked the details, but quick answer : 
* the search language
* the IP of the instance

Search engines in addition to the search language uses the GeoIP to give customize results.

So even, if the real IP is hidden, different the searx instances can provides different results.

There is nothing that can be done about that in a reasonable way. 

A hammer solution could be : 
* have different IP in different region of the world.
* searx send the same request to the same engine from different IP

A more practical way : 
* configure a searx instance to proxy requests to other searx instances and merge the results, may be more than one instance. Of course the response time will be affected ( see https://github.com/asciimoo/searx/blob/master/searx/engines/searx_engine.py ).

**Comment by kkaiser** [comment]
Thanks for the quick answer. I think the IP has the most impact and was actually aware of that but it still surprises me how "gmail" can be a match for the entered query, even though it is a bit more complex. But thanks for the clarification. I just wanted to make sure this wasn't a mistake of any sort.
