### ISSUE TITLE
Doesn't seem to respect quotes in searches

### ISSUE THREAD

**Issue by mattinnova** [searx/searx#935]
The past few days, it appears searx is not respecting quotes in searches (i.e. "test search" vs. test search) when I believe it did as recently as last week. I'm getting Google results that I shouldn't get with quotes and was curious if anybody else had seen this behavior.

**Comment by ghost** [comment]
I seem to be experiencing this issue as well.

**Comment by dimqua** [comment]
It appears to be fixed, please re-check.

**Comment by unixfox** [comment]
The quotes are now passed to the engine.
Here is a log confirming the case:
```
DEBUG:urllib3.connectionpool:https://www.google.com:443 "GET /search?q=%22test+search%22&hl=en-US&lr=lang_en&ie=utf8&oe=utf8&start=0 HTTP/1.1" 200 None
```
