### ISSUE TITLE
Difference between German and German_Germany

### ISSUE THREAD

**Issue by ShalokShalom** [searx/searx#937]
Is there a markable difference?

![bildschirmfoto vom 2017-06-06 12-29-20](https://cloud.githubusercontent.com/assets/6344099/26825065/ead66538-4ab3-11e7-92ab-1813667c5cdc.png)

**Comment by kvch** [comment]
Yes, according to strings in `messages.po` files. For example "images" is translated to Bilden in German and Fotos in German_Germany. Or "allow" is translated to Erlauben in German but Zulassen in German_Germany. I don't know what is the difference, because I don't speak German. But I hope it helps.

**Comment by ShalokShalom** [comment]
These are simply two different words, everybody understands both.

**Comment by bamstam** [comment]
Any progress on this issue?

From a translator's perspective it is highly inefficient to maintain two translations of the same language, if there is no significant difference (e. g. the formal "Sie" vs. the informal "du" in German).

I would suggest deleting one of the two translations to avoid double work for translators in the future.

**Comment by ShalokShalom** [comment]
I agree. Its also for the users confusing. Looks like one language is left from a past clean up.
+1

**Comment by ShalokShalom** [comment]
And i think Portugese_Brazil should get renamed into Brazil.

**Comment by kvch** [comment]
Which German translation should be kept?

**Comment by bamstam** [comment]
I paged the translators who contributed to both translations in the past and referred to this issue to get more input. I would recommend a coin flip :-)

**Comment by Siggi0904** [comment]
Hi, I didn't use these sotware but I'd like to help with translations.
I copyed the non formal version to the fermal version and updated some strings.

But I can not change all strings because I'm not a reviewer.
Please update myself to a reviewer, then I will optimize many strings.

Thanks.

**Comment by kvch** [comment]
@Siggi0904 I think you can edit translations without joining the maintainers of searx on Transifex.

**Comment by bamstam** [comment]
Both versions are fully translated and of comparable quality as far as I can see, so I guess it is safe to randomly pick one translation for deletion. y/n?

**Comment by ShalokShalom** [comment]
You can remove it from the page and if anything happens any time, can you restore it. 
Where can I see both, to compare? I mean, as a list.

**Comment by Siggi0904** [comment]
@kvch No, please read the transifex group guidelines. Only reviewer can change reviewed strings.

And if the community will find a solution please delete the whole language in transfex.

@ShalokShalom Download the files from transifex and use a tool to compare.
Transifex itself can't do this.

**Comment by kvch** [comment]
@Siggi0904 I've just added you as a reviewer. Sorry for the delay. Also, thank you for in advance for taking care of German translation.

**Comment by bamstam** [comment]
We still have two flavors of German :-) How to proceed? @Siggi0904 @kvch @ShalokShalom

**Comment by kvch** [comment]
I added @Siggi0904 to `de`, so I would get rif of `de_DE` and keep `de`.

**Comment by ShalokShalom** [comment]
+1

**Comment by Siggi0904** [comment]
Please delete all translators from DE_de in Transifex and remove this ressource.
Thanks.

**Comment by kvch** [comment]
Done by @asciimoo
