### ISSUE TITLE
Yandex doesn't work with searx

### ISSUE THREAD

**Issue by leedoyle** [searx/searx#938]
I've checked two searx instances, searx.me and searx.ch and neither one works with Yandex, even when it's selected as the sole search engine.
One of the instances is searx 0.11.0, another  0.12.0.
I suspect Yandex have changed their API.

EDIT: it also may be possible that Yandex has simply banned searx bots from these two servers (.ch and .me) after a number of queries. But in this case it would help to somehow notify users of the fact that Yandex is unavailable at the very least.

**Comment by leedoyle** [comment]
@asciimoo updated the issue.

**Comment by leedoyle** [comment]
Steps to reproduce: try to search !yn test

**Comment by dimqua** [comment]
It seems that Yandex doesn't work time to time only if you use one of the most popular instances like searx.me.

**Comment by Youaresmarter** [comment]
It seems not working for now. I've checked 5 public searx instances and self-hosted docker instance. No luck with Yandex. Any ideas how to fix it?

**Comment by dimqua** [comment]
The engine has been updated a year ago, that's why it doesn't work anymore, I believe.

>I suspect Yandex have changed their API.

Searx does not use their API, it parses HTML instead.

**Comment by asciimoo** [comment]
Works for me
