### ISSUE TITLE
Patch 78365ffb8a083 (threading init()) - searx just hangs

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#939]
Patch 78365ffb8a083ca3e3ea905db12bdac9f273f460 let's searx just hang - no response from server. Back to f82646f38605a999f22bc4662f591cd56d022170 (0.12.0) everything works fine again.

**Comment by asciimoo** [comment]
@cy8aer this is strange, I can't reproduce. What is your environment?

**Comment by cy8aer** [comment]
I am running a classical no-docker setup on Debian Jessie, uwsgi, apache2 according to this installation documentation https://asciimoo.github.io/searx/dev/install/installation.html.

**Comment by cy8aer** [comment]
... python 2.7.9, uwsgi 2.0.7, apache 2.4.10

**Comment by cy8aer** [comment]
There is also no connection entry in my uwsgi log either.

**Comment by cy8aer** [comment]
After a connection try to the web page I cannot stop the uwsgi via systemd, I really need to kill -9 the uwsgi processes.

**Comment by dalf** [comment]
Is there any errors in /var/log/uwsgi ?

**Comment by cy8aer** [comment]
No, the log is empty - it begins to hang right before the connection itself is mentioned in the log.

**Comment by xinomilo** [comment]
i can confirm this with debian jessie, nginx 1.6.2, python 2.7.9, uwsgi 2.0.7. 
after reverting back to 0.12 release patch, searx starts normally. 
with latest patches, uwsgi doesn't log any error, and nginx justs timeouts : 
connect() to unix:/run/uwsgi/app/searx/socket failed (11: Resource temporarily unavailable) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: searx_instance, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/searx/socket:", host: "searx_instance"

**Comment by cy8aer** [comment]
It looks like a "wait for thread" race condition (just a comment of a moron). Then everything hangs and waits for a thread which does not come back.

**Comment by prolibre** [comment]
+1 I can confirm in debian with Apache/2.4.10 , uWSGI 2.0.7-debian and Python 2.7.9 : **no response from server**

**Comment by asciimoo** [comment]
Hmm, I'm using the following command: `uwsgi --plugin python -w searx.webapp --http-socket 127.0.0.1:4000 --master --processes 8 -H env --enable-threads --lazy-apps`. Without `--lazy-apps` option I can reproduce the mentioned issue (still no idea why). Could you try the `--lazy-apps` flag (http://uwsgi-docs.readthedocs.io/en/latest/Options.html#lazy-apps) ?

**Comment by prolibre** [comment]
@asciimoo yes ! :-) ça marche / it's OK !

**Comment by cy8aer** [comment]
does anyone has a clue how to set --lazy-apps in a debian jessie uwsgi environment? For me uwsgi does not start when start it by hand and the uwsgi call itself is deeply hidden in the init scripting of the package. Does uwsgi 2.0.7 have this option --lazy-apps?

**Comment by cy8aer** [comment]
Ok, got it inserted into /usr/share/uwsgi/init/specific_daemon but this does not look not wery legal. Anyways: now uwsgi is called with --lazy-apps and it works.

**Comment by gled-rs** [comment]
just adding in uwsgi/app-enabled/searx.ini:

lazy-apps = true
enable-threads = true

solved the issue for me ( the enable-threads is the one that definitely helped ). I tend to recall that threads are disabled by default on uwsgi.

**Comment by cy8aer** [comment]
@gled-rs thank you for your legal configuration description. This should be added to the documentation https://asciimoo.github.io/searx/dev/install/installation.html
