### ISSUE TITLE
Engines & categories disappear when using uwsgi

### ISSUE THREAD

**Issue by levinuss** [searx/searx#940]
Hi,
I installed searx on my new Ubuntu 16.04 Server, wanted to use my old setup (searx started by uwsgi, apache as reverse proxy)
I tried to install it and it worked if I started it manually and apache pointed to `http://127.0.0.1:8886`. When I set up uwsgi I wanted uwsgi to use port 8886 for communication and apache would point on `uwsgi://127.0.0.1:8886` (so mod_proxy_uwsgi).
This setup works also BUT I can't perform a search query. When I try to search something searx says no results could be found and I can't select another category because there is only one.
When I go to settings > search engines the table is completely empty.
Log & config files below, could'nt get anything interesting from them.

[uwsgi config](https://hastebin.com/ayoroniwiv.ini)
[uwsgi log file](https://hastebin.com/anubakajad.pas)
[apache config](https://hastebin.com/tewapapazi.cs)
[apache log file](https://hastebin.com/tokuyoravu.erl)
[settings.yml](https://hastebin.com/ihedomoyal.coffeescript)

It would be great it someone could find a solution for this problem.

**Comment by MarcAbonce** [comment]
If you turn `debug` to False in searx's settings.yml they will appear.
I don't know why, but it seems like it's the [intended behaviour](https://github.com/asciimoo/searx/blob/master/searx/webapp.py#L123).

**Comment by dalf** [comment]
Related to these two commits : 7388067 and 68cbf04

When in DEBUG mode, the engines are initialized twice when started using
```sh
python searx/webapp.py
```

See:
https://stackoverflow.com/questions/25504149/why-does-running-the-flask-dev-server-run-itself-twice

I haven't tried with uwsgi and debug mode.

Which version of uwsgi do you use ?

**Comment by levinuss** [comment]
Thank you! Runs now fine.
Actually I thought of this because the installation tutorial metions to turn debug off (in a step before installing uwsgi). I thought I tested it with debug off. My fault.
uwsgi version is 2.0.12-debian from official ubuntu 16.04 package repo. See uwsgi log for further details.
