### ISSUE TITLE
Largest images engines, Bing and Google, no results

### ISSUE THREAD

**Issue by jodo13** [searx/searx#943]
If we can trust http://stats.searx.oe5tpo.com/ and by the results we can, Searx instances can't retrieve results for the largest engines.

Searx becomes almost useless for image searching then with the rest of available engines.

**Comment by pointhi** [comment]
please note this site is testing the connectivit on my instance, which wasn't update a long time now. Many engines likely have fixes, as well as some engines are probably blocked. Dont trust the results to much :-)

**Comment by jodo13** [comment]
I see, that is why I said too that by the results (at least I have).

Anyway, I use laquadrature.net instance (0.11) and searx.me (0.12) and along the last week and these last couple of days, both couldn't retrieve from Google and Bing. Now Searx.me can't still retrieve from Google and intermittent with Bing.

So, let me tell it here, just in case something is broken too ;-)

Thanks anyway for all your work :)

**Comment by kvch** [comment]
@jodo13 Do you mean Bing or Bing Images? Both of them are seem to work on searx.me.

**Comment by jodo13** [comment]
@kvch as the subject of the issue says, I'm talking about images engines, or images results, so, Bing Images :)

As told in the previous message to yours, it is intermittent with Searx.me instance. Sometimes display Bing images results, and some doesn't. Might be high load on Bing Images or whatever.

Thanks for the google fix. I hope to see it soon on instances :)

**Comment by kvch** [comment]
@jodo13 Thank. :) So far I haven't been able to reproduce it so far nowhere. So yes, it is possible that it is a Bing problem.
