### ISSUE TITLE
Morty proxy service - no proper documentation

### ISSUE THREAD

**Issue by poosey** [searx/searx#949]
I'm trying to enable the morty proxy service for my searx instance. I've made changes to settings.yml and can see the "proxied" link, but it's unable to connect (morty is running, listening to port 3000 on localhost). There's no documentation on how to set this up with nginx in the installation instructions or on the morty github page.

**Comment by Pofilo** [comment]
There is some documentation here: [https://asciimoo.github.io/searx/admin/morty.html](https://asciimoo.github.io/searx/admin/morty.html).

Feel free to reopen if you still need some assistance !
