### ISSUE TITLE
[Science tab] resolve DOI with a service promotting OpenAccess records

### ISSUE THREAD

**Issue by jibe-b** [searx/searx#953]
Scientific publications often have a record on the website of a publisher.

The author of a scientific publication may archive her.his work in an open archive, enabling anyone to access and read her.his work.

Some DOI resolvers return URL of an open access version of the publication and link to the paywalled version only when it is the only link available.

The choice of the DOI resolver's URL could be set in preferences. An OpenAccess DOI resolver by default would improve the access to scientific publication to users.

**Comment by jibe-b** [comment]
Now that I wrote the idea I was having, I see clues of this being at least partly achieved: https://github.com/asciimoo/searx/blob/4cffd78650c3f1dfce413ae0a1cd0453ebe6f277/searx/plugins/doai_rewrite.py

**Comment by dalf** [comment]
done : #1075
