### ISSUE TITLE
Why using POST HTTP for csv,json,rss output?

### ISSUE THREAD

**Issue by aurora-anon** [searx/searx#955]
#1 Why they're not accessible?
#2 How could I grab the url of e.g. a json response?

**Comment by kvch** [comment]
It is possible to retrieve results using GET in the formats you mention. You need to specify `format=csv` or `format=json`, etc. Apparently, it is missing from the search API documentation. Thanks for pointing this out. :)

**Comment by aurora-anon** [comment]
But why it says it ran out of limit?

I see lotta searx clones that provide csv,json and xml output without any problems.
What do they do?

**Comment by dalf** [comment]
![bots-bots-everywhere](https://user-images.githubusercontent.com/1594191/28056432-3509ad98-661d-11e7-827f-1b99aff4ea62.jpg)

So searx.me uses https://github.com/asciimoo/filtron otherwise google and all will ban all searx.me ips.

**Comment by kvch** [comment]
Some of the instances limit the amount of possible requests in these formats. It's up the admin of each searx. Personally, I use filtron to limit these requests.
