### ISSUE TITLE
New URL saving feature does not apply sometimes

### ISSUE THREAD

**Issue by ShalokShalom** [searx/searx#958]
Here, on Firefox 55b7 is the newly implemented feature to create URLs based on your current settings sometimes not working: I change settings like the categories and they simply do not apply. 

Confirmed on Opera.

**Comment by asciimoo** [comment]
@ShalokShalom preferences coming from GET HTTP parameters have bigger priority than preferences saved in cookies, so cookies will be overwritten by GET params. You have to rewrite the search URL to the new one genearated on preferences page if you save the preferences.

**Comment by ShalokShalom** [comment]
Nice to know. This is something different, as i mean.

**Comment by ShalokShalom** [comment]
Still the case.

**Comment by asciimoo** [comment]
@ShalokShalom what would be the desired functioning?

**Comment by ShalokShalom** [comment]
That its applies every time, when i click on save.

**Comment by asciimoo** [comment]
This would require storing user's preferences data on server side what raises privacy concerns.

**Comment by ShalokShalom** [comment]
?
You seriously dont get, what i mean. There is a save settings button on the bottom of the page.
It works sometimes, and sometimes not.

**Comment by ShalokShalom** [comment]
Ah yeah, and the function so create URLs, who save the settings, is gone.

**Comment by asciimoo** [comment]
> You seriously dont get, what i mean.

Seems, it is true. Could you describe your problem a bit more elaborately?

> There is a save settings button on the bottom of the page. It works sometimes, and sometimes not.

It works for me every time I push the button.

> Ah yeah, and the function so create URLs, who save the settings, is gone.

It is on the bottom of this page: https://searx.me/preferences

**Comment by ShalokShalom** [comment]
> It is on the bottom of this page: https://searx.me/preferences

Yeah, now its back again. 
Seems both, the save function and the URL creation happen to dropout sometimes.

**Comment by ShalokShalom** [comment]
This is still broken. 

Sometimes do I get the result of %s, when I use a saved URL:

![screenshot_20170929_174205](https://user-images.githubusercontent.com/6344099/31023897-95b3aa54-a53d-11e7-88a0-09560a9995a9.png)

Sometimes a white screen: 

![screenshot_20170929_174352](https://user-images.githubusercontent.com/6344099/31023959-c7a7f6be-a53d-11e7-8255-b3a60f6aee18.png)

And still, sometimes does a saved change in the settings not apply at all, which might be an issue on its own. It includes anyhow that the search URL does not get refreshed as well..

All reproducible on Opera, Chrome, Firefox, Qupzilla and Liri-Browser.

**Comment by unixfox** [comment]
I cannot reproduce the bug. I created a custom preferences one year ago on https://searx.be, and I used the same one now, and it still works with the same URL.
My browser: Firefox 84.0.1
