### ISSUE TITLE
Photobucket-hosted site background is broken

### ISSUE THREAD

**Issue by Fironet** [searx/searx#970]
Recently Photobucket began blocking hotlinked images in an effort to get users to pay for the hosting. Didn't realize SearX was using it until...

![searx](https://user-images.githubusercontent.com/6971981/28404636-849a88a8-6d6d-11e7-98e9-d56cd24f192c.png)

Yeah.

**Comment by kvch** [comment]
How did you get this picture? AFAIK there is no picture apart from the searx logo in the index page.

**Comment by Fironet** [comment]
> How did you get this picture? AFAIK there is no picture apart from the searx logo in the index page.

I'm using the Logicodev theme, which is the default I believe? It's one of only two themes available. The background displays on all SearX pages.

**Comment by kvch** [comment]
On my instance https://searx.kvch.me it works. I haven't modified the themes at all. And on searx.me it is working, too. Do you use anything like userstyles to change its background on you side?

**Comment by Fironet** [comment]
> Do you use anything like userstyles to change its background on you side?

Oh my goodness. For some reason I had forgotten completely about a dark theme userstyle I had installed months ago, which I began to assume was the default for whatever reason (I'd normally remember such things).

Closing as not a issue.
