### ISSUE TITLE
Blank page when I use Search URL of the currently saved preferences 

### ISSUE THREAD

**Issue by mrtargaryen** [searx/searx#979]
When I use the "Search URL of the currently saved preferences" it returns a blank page. I'm using Firefox 54 on macOS 10.12.6.

**Comment by mrtargaryen** [comment]
This is the URL with the preferences set and it returns a blank page on https://searx.me on multiple browsers: https://searx.me/?results_on_new_tab=False&language=en-US&locale=en&disabled_plugins=Vim-like_hotkeys&image_proxy=True&autocomplete=startpage&safesearch=0&theme=oscar&enabled_plugins=Open_result_links_on_new_browser_tabs%2CInfinite_scroll%2CDOAI_rewrite%2CHTTPS_rewrite%2CTracker_URL_remover%2CSelf_Informations%2CSearch_on_category_select&disabled_engines=duckduckgo+images__images%2Cccc-tv__videos%2Cfree+software+directory__it%2Cvoat__social+media%2Cbase__science%2Cina__videos%2Cbing+images__images%2Cgoogle+play+apps__files%2Csubtitleseeker__videos%2Cpdbe__science%2Cnyaa__videos%2Cbing+news__news%2Ccrossref__science%2Cfdroid__files%2Csemantic+scholar__science%2Cseedpeer__files%2Ckickass__videos%2Cgoogle+play+music__music%2Cyandex__general%2Cdeezer__music%2Cgeektimes__it%2Cmymemory+translated__general%2C500px__images%2Cdigbt__videos%2Carchive+is__general%2Cgoogle+play+movies__videos%2Cdictzone__general%2Cseedpeer__music%2Ccurrency__general%2Cgitlab__it%2Cmixcloud__music%2Cqwant+social__social+media%2Csoundcloud__music%2Cdigbt__files%2Cerowid__general%2Cseedpeer__videos%2Cnyaa__images%2Cdigg__news%2Clibrary+genesis__general%2Cgoogle+scholar__science%2Creddit__general%2Cdailymotion__videos%2Cbitbucket__it%2Cfrinkiac__images%2Chabrahabr__it%2Cetymonline__general%2Ctokyotoshokan__music%2Cflickr__images%2Cframalibre__it%2Cmicrosoft+academic__science%2Cdigbt__music%2Cvimeo__videos%2Creddit__images%2Copenrepos__files%2Cqwant+news__news%2Carch+linux+wiki__it%2Clobste.rs__it%2Choogle__it%2Cswisscows__general%2Cqwant+images__images%2Ctokyotoshokan__videos%2Cqwant__general%2Cdeviantart__images%2Cnyaa__files%2Cswisscows__images%2Cgigablast__general%2Cscanr+structures__science%2C1x__images%2Cdigg__social+media%2Csearchcode+code__it%2Cspotify__music%2C1337x__videos%2Csearchcode+doc__it%2Cnyaa__music%2Ctokyotoshokan__files&enabled_engines=kickass__files%2Cduckduckgo__general%2Creddit__social+media%2Creddit__news%2Cixquick__general%2Cstartpage__general%2Cddg+definitions__general%2Ckickass__music&method=POST&categories=general&q=%s

**Comment by kompowiec** [comment]
I checked, if afther write simply searx it settings are saved in cookie. 

_Sent from my HUAWEI NEM-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ghost** [comment]
@kompowiec Can you elaborate? How you fixed this issue? Adding "searx" to the string doesn't solve the problem.

**Comment by ghost** [comment]
With [my custom URL](https://github.com/asciimoo/searx/issues/1056) Searx performs a search instead.

**Comment by kompowiec** [comment]
hard to say, because for some reason the error no longer exists. I used this link now: http://tinyurl.com/yb9c88q5 and redirect normally on search page with string %s and work. Interestingly, this string is absent in shortly, with fewer settings URLs.
edit: just like you.

**Comment by ghost** [comment]
@mrtargaryen I get a blank page with your URL in the second message.

**Comment by asciimoo** [comment]
Cannot reproduce with the current codebase.
