### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by 644** [searx/searx#982]
I'm unable to proxy morty with searx via HTTPS, though HTTP works fine.

`error when serving connection "CENSOREDIP:3000"<->"CENSOREDIP:26999": error when reading request headers: cannot find http request method in "\x16\x03\x01\x00\xa3\x01\x00\x00\x9f\x03\x03R\xad\xc1X\xbe\x93/\x97\x82pӃH\xc0-\xba\xd1.\x9fG\xec\xa7\xe1\v\fr\xb9a\x82~\x1a\x8e\x00\x00\x1e\xc0+\xc0/̨̩\xc0,\xc00\xc0\n\xc0\t\xc0\x13\xc0\x14\x003\x009\x00/\x005\x00\n\x01\x00\x00X\x00\x17\x00\x00\xff\x01\x00\x01\x00\x00\n\x00\n\x00\b\x00\x1d\x00\x17\x00\x18\x00\x19\x00\v\x00\x02\x01\x00\x00#\x00\x00\x00\x10\x00\x0e\x00\f\x02h2\bhttp/1.1\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\r\x00\x18\x00\x16\x04\x03\x05\x03\x06\x03\b\x04\b\x05\b\x06\x04\x01\x05\x01\x06\x01\x02\x03\x02\x01". Buffer size=168, contents: "\x16\x03\x01\x00\xa3\x01\x00\x00\x9f\x03\x03R\xad\xc1X\xbe\x93/\x97\x82pӃH\xc0-\xba\xd1.\x9fG\xec\xa7\xe1\v\fr\xb9a\x82~\x1a\x8e\x00\x00\x1e\xc0+\xc0/̨̩\xc0,\xc00\xc0\n\xc0\t\xc0\x13\xc0\x14\x003\x009\x00/\x005\x00\n\x01\x00\x00X\x00\x17\x00\x00\xff\x01\x00\x01\x00\x00\n\x00\n\x00\b\x00\x1d\x00\x17\x00\x18\x00\x19\x00\v\x00\x02\x01\x00\x00#\x00\x00\x00\x10\x00\x0e\x00\f\x02h2\bhttp/1.1\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00\r\x00\x18\x00\x16\x04\x03\x05\x03\x06\x03\b\x04\b\x05\b\x06\x04\x01\x05\x01\x06\x01\x02\x03\x02\x01"`

I really have no idea what's causing this issue. I'm running searx on nginx with let's encrypt.

**Comment by asciimoo** [comment]
Morty can listen on HTTP only. If you want to use it with HTTPS, put it behind the nginx and use that address in your searx config.
Example nginx snippet:
```
server {
    listen 3000;
    server_name xy.com;
    [SSL config]
    location / {
         # morty's HTTP address
          proxy_pass http://127.0.0.1:4006/;
    }
}
```
With the above configuration `morty_url` should be `https://xy.com:3000/` in searx settings.yml.
