### ISSUE TITLE
systemd init file

### ISSUE THREAD

**Issue by inattendu** [searx/searx#985]
Hi !
Thanks for this awesome soft.
Here is a very basic systemd unit file that work with the latest version of searx (tested with debian8)

**/etc/systemd/system/searx.service**
```[Unit]
Description=searx
After=syslog.target network.target

[Service]
Type=simple
User=searx
WorkingDirectory=/usr/local/searx
ExecStart=/usr/local/searx/searx-ve/bin/python /usr/local/searx/searx/webapp.py

[Install]
WantedBy=multi-user.target
```
-----
Reload the config & activate the service's persistance with : 
```
systemctl daemon-reload && systemctl enable searx.service
```
-----
_My searx instance is configured with apache only, acting as a reverse proxy ; CF [this part of the official documentation](https://asciimoo.github.io/searx/dev/install/installation.html#with-apache)_

Thanks, and keep up the good work.

**Comment by dalf** [comment]
It seems there is no uwsgi at all ?

**Comment by inattendu** [comment]
Nope, sorry i've missed that the apache part of the doc I've linked use UWSGI, i prefer using apache as a HTTP reverse-proxy with directives like  : 
```
        ProxyRequests Off
        <Proxy *>
                AllowOverride None
                Require all granted
        </Proxy>
        ProxyPass / http://localhost:8888/
        ProxyPassReverse / http://localhost:8888/
```

**Comment by unixfox** [comment]
There is now an official systemd service included with Searx official script.

**Comment by tacerus** [comment]
> There is now an official systemd service included with Searx official script.

That needs to be tediously dug out if one wants to install it manually. It is nice for you to provide scripts, however disguising configuration pieces within them is not nice.
