### ISSUE TITLE
Oscar pointhi: Try Searching not well rendered

### ISSUE THREAD

**Issue by cy8aer** [searx/searx#986]
The "Try searching" block is not well rendered with Oscar Pointhi. Sorry no attachment upload possible.

**Comment by cy8aer** [comment]
![bildschirmfoto von 2017-08-01 15-10-20](https://user-images.githubusercontent.com/578172/28826985-68382892-76cc-11e7-885d-929e11eec0a8.png)

**Comment by asciimoo** [comment]
As I see, it is fixed.
