### ISSUE TITLE
List of engines / add github api code search 

### ISSUE THREAD

**Issue by roscopecoltran** [searx/searx#987]
Hi guys,

Hope you are all well !

Here are some search engine lists, classified by types:
https://github.com/wowdd1/xlinkBook/blob/master/db/metadata/engin_list
https://github.com/wowdd1/xlinkBook/blob/master/db/metadata/engin_type
https://github.com/wowdd1/xlinkBook/blob/master/db/metadata/engin_list-duckduckgo2017

For the github api, I was thinking about adding the api.github.com/search/code endpoint and un-duplicate/group results per project URI. Do you have this feature in your roadmap ? Any objections ?

Have a great day !

Cheers
Richard

**Comment by unixfox** [comment]
Unfortunately Searx cannot maintain this amount of engines at the same time, it would be too much time-consuming. If you want to have a specific instance added in the code base then feel free to open a new corresponding issue.
