### ISSUE TITLE
Noob needing help

### ISSUE THREAD

**Issue by mrtargaryen** [searx/searx#989]
Hi,
Total noob (sorry)

Im trying to learn how to run Searx on my iMac macOS 10.12.6

I installed the Docker app and ran the following in Terminal:

git clone https://github.com/asciimoo/searx.git
cd searx
docker build -t searx .

Everything appeared to install but I am unsure where to go from here to access Searx and use it. If someone can point me in the right direction I will be very thankful.

Are there any step by step directions I can find for someone learning how to do this?

Thank you very much.

Edit: I managed to access Searx on my localhost, does anyone know of a step by step guide to setting up a proxy/ securing Searx for local use?

**Comment by dalf** [comment]
Look at https://asciimoo.github.io/searx/dev/install/installation.html#docker

```sh
docker run -d --name searx -p $PORT:8888 searx
```
will run the images you have built. 
Replace $PORT by the number you want too.

You may want to instantiate different instances and run nginx as a front-end using docker compose. But you can start without, especially if searx runs on your laptop.

**Comment by mrtargaryen** [comment]
Thank you for your reply,

When I use https://searx.me and search for something I am given the option to view the results via a proxy. How do I set up a proxy so I can view sites through a proxy in my instance of searx on my imac?

**Comment by dalf** [comment]
You have to install https://github.com/asciimoo/morty

Then you can configure searx to use it in settings.yaml : see result_proxy section.

**Comment by mrtargaryen** [comment]
Thanks,

I tried to run $ go get github.com/asciimoo/morty in terminal on my imac but it returns a message -bash: $: command not found Terminal also doesn't recognise "get"

Like I said I'm a total noob, I'll just keep reading what ever I can to get this working. 

Thanks for your help :-)

**Comment by mrtargaryen** [comment]
Hi,

Does anybody know how to install Morty on macOS 10.12.6

When I follow the instructions here: https://github.com/asciimoo/morty   This is the result in Terminal:

iMac$ go get github.com/asciimoo/morty
-bash: go: command not found

I have tried asking elsewhere but have had no replies.

I am only very new to doing things like this but I am very keen to learn but do not know where to learn this stuff. I don't want to waste anyones time but if someone could point me in the right direction I would be very grateful.

Thank you very much.

**Comment by MarcAbonce** [comment]
It seems like you need to install [go](https://golang.org/doc/install).

**Comment by mrtargaryen** [comment]
> It seems like you need to install go.


Thanks for the reply.
I installed Go for macOS and restarted my Mac, then opened Terminal and typed in:

 go get github.com/asciimoo/morty

Terminal gave me this result:

My-iMac:~ iMac$ go get github.com/asciimoo/morty
package github.com/asciimoo/morty: mkdir /Users/imac/go: not a directory

In /Users/imac/ there is a empty text file named go but no directory.

Any idea what I can do?

Sorry about this, I'm in uncharted territory for myself.

**Comment by asciimoo** [comment]
> In /Users/imac/ there is a empty text file named go but no directory.
> Any idea what I can do?

Remove that file and create a folder with the same name (in console: `rm /Users/imac/go && mkdir /Users/imac/go`)

**Comment by mrtargaryen** [comment]
> Remove that file and create a folder with the same name (in console: rm /Users/imac/go && mkdir /Users/imac/go)

Thank you so much! 

I ran the tests and it appears to be working.

Can I ask one last question if its not too much (if you're too busy I understand).

In order for the proxy to work in the search results how do I configure Searx/Morty to do that? On Searx.me (which I have been using for some time) I see the option to view the page via a proxy version of the page or the cached version. I'd like to be able to have that available to me on mine.

Again thank you very much for taking the time to help, its a bit of a learning curve for me. I've purchased a book on docker & command line which I'm intending to read.

**Comment by asciimoo** [comment]
> In order for the proxy to work in the search results how do I configure Searx/Morty to do that? 

I've created a documentation page which explains the setup: https://asciimoo.github.io/searx/admin/morty.html

>  I've purchased a book on docker & command line which I'm intending to read.

:+1:

**Comment by mrtargaryen** [comment]
searx supports result proxification using an external service: https://github.com/asciimoo/morty
 uncomment below section if you have running morty proxy
result_proxy:
    url : http://127.0.0.1:3000/
    key : your_morty_proxy_key

So the URL is  http://127.0.0.1:3000/ but the morty proxy key is that a specific number I need to input in that line? If so where do I find that?
