### ISSUE TITLE
[feature-request] Support defining custom sites

### ISSUE THREAD

**Issue by aurora-anon** [searx/searx#999]
Provide support for connecting to an API endpoint with an structure like JSON or XML that users exactly describe for searx.

**Comment by asciimoo** [comment]
This is the purpose of the json and xpath engines. `settings.yml` contains some exaples about the usage of these engines.

**Comment by aurora-anon** [comment]
I mean defining a custom site by the user, not the server.

**Comment by dalf** [comment]
What do you want to customize ? Can you elaborate ?

**Comment by aurora-anon** [comment]
Adding sites to the search engines by the user.
